### ISSUE TITLE
New alert route in AlertManager

### ISSUE THREAD

**Issue by asmega** [ministryofjustice/cloud-platform#1000]
## Service name

Form Builder

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Required to implement AlertManager for Form Builder

## Problem description

Implement new AlertManager routes for Form Builder test environment. Below is the requested information to do this. Note: this is required in 7 namespaces

```
namespace names

===
formbuilder-platform-test-production
formbuilder-platform-test-staging
formbuilder-platform-test-dev

formbuilder-services-test-production
formbuilder-services-test-staging
formbuilder-services-test-dev

formbuilder-publisher-test
===

team name
Form Builder

application name
Form Builder

slack channel
form-builder-alerts
```

## Contact person

Phil Lee (me)

**Comment by vijay-veeranki-moj** [comment]
This is blocked until digitalservicedesk fix the permissions issue.

https://mojdt.slack.com/archives/C59CX1RHN/p1560421540279400

message from Muqi (digitalservicedesk)

muqi [4:58 PM] on 13-06
Hi @Vijay Veeranki, just to keep you updated the admin permissions are still being reviewed
it has been esculated and will inform you as soon as we receive a update

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/286

**Comment by pwyborn** [comment]
merged and terraform applied.
Now in: 
https://alertmanager.cloud-platform.service.justice.gov.uk/#/status

**Comment by pwyborn** [comment]
Hi Phil @asmega Regarding ticket ```https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/1000``` New alert route in AlertManager - Form Builder Should be there now. The “custom severity level” is “form-builder” . Please follow the instructions here
user-guide/creating-a-slack-webhook-and-amend-alertmanager
. Can you please test?

**Comment by pwyborn** [comment]
All done - awaiting user confirmation

**Comment by pwyborn** [comment]
Phil Lee [12:27 PM]
I can confirm the web hook is working and alert manager sent a message to correct slack channel. you can close the ticket now
many thanks

paulwyborn [12:51 PM]
Thank you Phil
