### ISSUE TITLE
Disable Service Team access to Terraform Plan Outputs

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1004]
## Service name

Disable Service Team access to Terraform Plan Outputs

## Service environment

- [ x] Dev / Development
- [ x] Staging
- [ x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Due to how TF plan works it is including information that we would not want available in the Plan output. This may expose sensitive information.

## Problem description

TF Plan output in including data that should not be available. We want to disable access to the output.

We'll issue comms to users informing them of the change. Please speak to Tony about user communication.

## Definition of done

 - [ ] Users who are not in the webops team cannot see the output of the plan pipeline
 - [ ] Users who are in the webops team can see the output of the plan pipeline
 - [ ] We have announced this change, and the reasoning behind it, on #cloud-platform-update

## Contact person

Tony

**Comment by alkar** [comment]
For now, to simplify the workaround I've only "censored" the output to hide any attributes from the plan. This would at least allow users to see which resources are going to be deleted / created / modified and we can always run the plan manually if we need more detail.

Splitting off to a separate concourse team is a bit more involved and would require more time to address. We will be doing this team split as part of our CI efforts on clusters and we can re-evaluate all other pipeline at that time.
