### ISSUE TITLE
Add a user guide article showing how (and why) to use TZ Cronjobs

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1006]
Relates to https://github.com/ministryofjustice/cloud-platform-environments/pull/875

**Comment by ushkarev** [comment]
having just tried this, something that might be worth noting: it looks like you don't get any of the fancy prometheus data for alerts or graphing. i.e. i cannot find anything akin to `kube_cronjob_status_last_schedule_time`

**Comment by alkar** [comment]
@ushkarev thanks for the input, it looks like they haven't implemented metrics at all in that project so unfortunately we can't do much about it right now. Should definitely mention in the documentation, however.
