### ISSUE TITLE
Create an OPA policy that introduces a domain whitelist

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#1009]
## Background

Open Policy Agent already has examples of a domain and hostname whitelist. The idea is that before I can use a hostname
in an Ingress, the namespace where the Ingress is created should have an annotation that defines the list of domains
that are valid for this namespace.

This prevents accidental use of hostnames in namespaces where they should not be used and allows a team to be confident
that they completely own their zone.

Since namespaces are managed through the environment repository and users cannot edit them, it should be an adequate
mechanism for separating access to hostnames.

## Example

Given the following namespace annotation:
```
cloud-platform.justice.gov.uk/domain-whitelist: foo.service.justice.gov.uk
```

I should be able to use the following hostnames in my Ingress,
- `foo.service.justice.gov.uk`
- `dev.foo.service.justice.gov.uk`
- `staff.dev.foo.service.justice.gov.uk`

but not these:
- `bar.service.justice.gov.uk`
- `dev-foo.service.justice.gov.uk`

Additionally, we should by default allow access to `*.apps.live-1.cloud-platform.service.justice.gov.uk`.

## Done when

- [ ] We have a new policy that implements this restriction
- [ ] We have tests covering our new policy
- [ ] `cloud-platform-environments` has been updated to define a whitelist for all namespaces (we can use some sort of
wildcard notation for the namespaces we're unsure about)
- [ ] The user doc on creating and using zones has been updated to explain the annotation

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
