### ISSUE TITLE
SPIKE: Write the SNS terraform module

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#101]
## Background

As part of #62 we are giving users a way to create AWS resources through our Kubernetes environment creation repo. We have started with S3 by writing a module for it (#69) that users will call when they want to add S3 to their application (#70). This story is to work out what a similar module for SNS would look like.

We want users to be able to request an SNS topic and create a user that can connect to that topic.

## Proposed user journey

- User goes to the environment creation repo
- User adds to a file in that repo to request an SNS topic (based on #70)
- A terraform pipeline runs to create that SNS topic (#74 )
- The SNS topic is created and the secrets for connecting to it and put into a Kubernetes secret (like #75) 

## Approach

Do this ticket by *writing an example module*. We can then use that module if we think it works or start again if we need to take a different approach.

## Questions / Assumptions

A lot of this should be based on the way that #69 was done:

- What should the topic be called?
- What tags do we need to add and how do we add them?
- What inputs do the users need to provide?
- What outputs should the module provide (e.g. secrets that can be put into Kubernetes)?

## Done when
- [x] There is a new repo for the module called `cloud-platform-terraform-sns`
- [x] tag resources according to the [tag guidance](https://ministryofjustice.github.io/technical-guidance/standards/documenting-infrastructure-owners/#documenting-owners-of-infrastructure)
- [x] work out what the user input needs to be  (e.g. team name, topic name, tags)
- [x] suggest any other options we could give a user
- [x] create IAM user credentials for accessing the topic (in this iteration it should be based on access keys not IAM roles for simplicity)
- [x] add a readme like the [ECR module](https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials)

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ollieanwyll** [comment]
SNS is not a resource that supports tagging.

**Comment by ollieanwyll** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-sns/tree/create

**Comment by ollieanwyll** [comment]
Review PR:
https://github.com/ministryofjustice/cloud-platform-terraform-sns/pull/2
