### ISSUE TITLE
Custom URL request - dev.data-capture-service.claim-criminal-injuries-compensation.service.justice.gov.uk

### ISSUE THREAD

**Issue by ross75** [ministryofjustice/cloud-platform#1010]
## Service name 

data-capture-service

##Service environment

- [x ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Low

## Problem description
Hi, I'm trying to get a custom url for my app. I need to be able to access it on:

dev.data-capture-service.claim-criminal-injuries-compensation.service.justice.gov.uk

The app is currently up and running on the cluster but it is accessible on:

dev.data-capture-service.claim-criminal-injuries-compensation.apps.live-1.cloud-platform.service.justice.gov.uk

I need to drop the …..apps.live-1.cloud-platform.... from the url

I understand that you will provide the certificate provider name and I will update the ingress file and a certificate yaml.

## Contact person

ross callaghan
ross,callaghan@cica.gov.uk
slack\; rosscallaghan

**Comment by digitalronin** [comment]
Hi @ross75 

Please could you add a hosted zone resource to your production namespace in the [environments repo](https://github.com/ministryofjustice/cloud-platform-environments), as per [this topic](https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#creating-a-route-53-hosted-zone) in the user guide?

Once you've done that, we can add the nameserver records for this domain.

There is more information [here](https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#using-a-custom-domain) about the overall process of setting up a custom domain.

**Comment by digitalronin** [comment]
Sorry @ross75 - I've just realised that you already have a hosted zone. I was looking for 'cica' but of course it's 'claim-criminal-injuries-compensation'.

My bad. I'll set up those nameserver records for you.

**Comment by digitalronin** [comment]
The team already have a sub-domain, with NS records set up. So they are able to create these URLs themselves, via PRs against the environments repo.
