### ISSUE TITLE
Create a regular check to ensure that the cluster backup ran successfully

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1012]
This relates to https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/284

The PR above will alert us if the cluster backup encounters an error, but it won't tell us if the job doesn't run (e.g. because someone deleted it by accident, or if the wrong region is set (which has happened before)).

In addition to that, we should have a check that runs once per day which checks the backup snapshots to ensure that the most recent one is less than 36 hours old. If it fails to find a recent snapshot, it should alert us (probably using the same SNS topic as the PR above). This should mean we always have faith that our cluster backups are working (or, at least, that multiple things have to break simultaneously for that not to be true).

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-cluster-backup-checker/pull/6
