### ISSUE TITLE
Discover all Cloud Platform Terraform state

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1013]
## Background

We have done some work on upgrading to Terraform 0.12.

So that we can plan the upgrade we need to understand what Terraform we have.

This story is a discovery exercise to document what Terraform we have so that we can plan the upgrade.

## Proposed user journey

N/A

## Approach

Document what Terraform we have and it's state.

## Which part of the user docs does this impact

N/A

## Definition of done

- [ ] Document detailing our current Terraform state.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-moj** [comment]
Added tfstate files from cloud platform, platform integration and mojdsd AWS accounts.

Live document for team to update.

https://docs.google.com/spreadsheets/d/1eYXCahHJ7cbhvw0HnryEwHCZE6BfszOSuUxqQsSG1TY/edit?usp=sharing
