### ISSUE TITLE
Elasticache/Redis connectivity issues

### ISSUE THREAD

**Issue by rossjones** [ministryofjustice/cloud-platform#1014]
## Service name

Offender Management

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

`offender-management-staging` and `offender-management-production` 

## Impact on the service

Limited impact, delays email delivery, generates noise, _may_ impact caching.
As we onboard more teams this will become more of an issue.

## Problem description

We are receiving a lot of sentry.io notifications complaining that our application timed out when connecting to our redis instances.  The vast majority of these notifications are raised in the staging environment, but more are appearing in production.  

It would be helpful to understand why this is happening so that we can take steps to resolve the issue, but we don't have access to any logging information from redis.

## Contact person

@rossjones (gh/slack)

**Comment by razvan-moj** [comment]
I think https://sentry.service.dsd.io/mojds/live1-allocation-manager-produ/ gives the most accurate info

**Comment by mtrblmoj** [comment]
Increased the node type from cache.t2.medium  to cache.m4.xlarge.

**Comment by rossjones** [comment]
The change to the staging environment doesn't seem to have impacted anything negatively.  Everything is still running, and no sign of any connectivity issues yet.

**Comment by mtrblmoj** [comment]
Resolved after upgrading the node size to cache.m4.xlarge
