### ISSUE TITLE
Set up pull panda to automate PRs

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1019]
https://github.com/marketplace/pull-panda

**Comment by poornima-moj** [comment]
Installed Pull Panda
Enabled Pull reminders and Pull Assigners for cloud-platform repo for testing

Configured Pull reminders to send messages to cloud-platform-notify when someone creates a new PR in cloud-platform repo 
    - Working fine. But we might not need this as we already have a SlackBot do the similar job
Configured Pull Assigners to automatically assign reviewers when there is a new PR for repo cloud-platform from WebOps team
    - Not working. Raised the issue with support@pullreminders.com to check and advise why and other settings needed.

Analytics and Leaderboard sections looks great and will be useful.
