### ISSUE TITLE
Improve our cluster integration tests

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1023]
The current smoke tests could be better if we:

* had a defined test framework, instead of ad hoc scripts (see #1047)
* remove baked-in assumptions about which cluster we're testing
* remove baked-in assumptions about namespaces that exist already
* tested more features of the cluster
* integrated the tests into the cluster build process (see #1050)

related to #1048
related to #1049

**Comment by AntonyBishop** [comment]
Breakdown

**Comment by AntonyBishop** [comment]
We now have a suite of integration tests that we are adding to on a rolling basis. This EPIC ticket can now be closed.
