### ISSUE TITLE
Request for new alert routes in Alertmanager

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#1025]
Following guidance here:
https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#creating-a-slack-webhook-and-amend-alertmanager

I would like to request alert routes and slack webhooks for the following applications (please note the alerts, although coming from different services, should be sent to the same channel, so maybe just one slack webhook is enough):

1.
* namespace: `c100-application-production`
* team name: `Family Justice`
* application name: `Apply to court about child arrangements (C100)`
* slack channel: `#cross_justice_team`

2.
* namespace: `family-mediators-api-production`
* team name: `Family Justice`
* application name: `Family Mediators API`
* slack channel: `#cross_justice_team`

3.
* namespace: `fj-cait-production`
* team name: `Family Justice`
* application name: `Get help with child arrangements (CAIT)`
* slack channel: `#cross_justice_team`

## Contact person

Jesus @ Slack

**Comment by vijay-veeranki-moj** [comment]
Created a webhook for slack channel: #cross_justice_team

`family-justice` is custom severity level
