### ISSUE TITLE
Explore ModSecurity nginx connector

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#1026]
## Background

We would like to setup a Web Application Firewall (WAF) in front of the services we host. This should help reinforce the security of our cluster and prevent a wide variety of attacks.

Given the nature of our setup (NLB -> nginx-ingress -> application), we're somewhat limited in our options. The following are some of the available solutions:

- https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#lua-resty-waf
- https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/modsecurity/
- https://wallarm.com/solutions/waf-for-kubernetes

Talking with @sid234, we have identified ModSecurity as the best candidate. It is a well known product and should cover all our needs. Initially, we only want to set it up with the default rules.

## Proposed user journey

As a user, I want my application to be protected by a WAF without me having to manually set it up.

To provide an opt-in/opt-out mechanism, we could have two nginx-ingress controller deployment, one with a WAF and one without and use [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/#using-multiple-ingress-controllers) (see also [this](https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/)) to control which one caters to a specific service.

## Questions / Assumptions

- Can we use AWS WAF at all with our current setup?

ModSecurity:
- What is the extra overhead for HTTP requests? (compare p99 response time between nginx-ingress without modsecurity and with)
- What kind of attacks are we protected from, out of the box?
- How easy is it to replace the rules with custom ones?

## Definition of done

- [x] the questions above have been answered

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
I wonder if it would be worth enabling this only for production namespaces?

My thinking is that, if there's a WAF in front of every service, then pen tests of new services might give better scores than the services 'deserve' because many tests would be blocked by the WAF before they can test the service's actual code.

If we leave non-production namespaces unprotected by the WAF, then the security team can actually test the service's own security, which will help us maintain good coding standards.

**Comment by alkar** [comment]
@digitalronin interesting idea. Didn't look like you can enable for part of the platform but we could introduce a second nginx-ingress for prod environments only and do it that way.

**Comment by sid234** [comment]
whitepaper on adding rules to aws waf -
https://d0.awsstatic.com/whitepapers/Security/aws-waf-owasp.pdf

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/133

https://www.modsecurity.org/CRS/Documentation/exceptions.html
