### ISSUE TITLE
Block Services of type LoadBalancer

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#1027]
## Background

We do not want tenants to use `Services` of type `LoadBalancer`. This creates an AWS LB pointing to a `NodePort`. We want to maintain control over the entrypoints to our cluster in order to be able to provide our tenants with a secure environment. Currently, only `nginx-ingress` is required to use such a `Service`.

## Approach

Create a new policy that prevents creating `Services` of type `"LoadBalancer"` unless the namespace where the `Service` is created has the following annotation:

```
cloud-platform.justice.gov.uk/can-use-loadbalancer-services: ""
```

The policy should return a user-friendly message.

## Definition of done

- [x] an OPA policy has been written, implementing the above
- [x] OPA unit tests have been written to cover the new policy
- [x] any namespaces that currently use LoadBalancer Services should be properly annotated
- [x] the policy is applied on the `live-1` cluster
- [x] we have a runbook describing how to add OPA policies

**Comment by digitalronin** [comment]
What's the problem with LoadBalancer services?

**Comment by vijay-veeranki-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/311/files
