### ISSUE TITLE
Block Pods that use tolerations for the master nodes

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#1028]
## Background

We do not want the master nodes to run any workload, except for _required_ system services (eg.: `fluentd`). The master nodes come with a [taint](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/) so by default, unless a toleration is specified, no `Pods` will be scheduled on them. However, one can override this behaviour [like this](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/helm-charts/fluentd-es/templates/fluentd-es.yaml#L120-L123).

We do not want our tenants to be able to schedule workloads on master nodes and we should prevent the use of this toleration.

## Approach

Create a new policy that prevents using the toleration described above unless the namespace where the `Pod` is created has the following annotation:

```
cloud-platform.justice.gov.uk/can-tolerate-master-tains: ""
```

The policy should return a user-friendly message.

## Definition of done

- [x] an OPA policy has been written, implementing the above
- [x] OPA unit tests have been written to cover the new policy
- [x] any namespaces that currently run workloads on master nodes should be properly annotated
- [x] the policy is applied on the `live-1` cluster

**Comment by digitalronin** [comment]
Could you expand on this a bit, Mitch? What are tolerations, and why are they bad?
