### ISSUE TITLE
Add a dummy elasticsearch endpoint for test clusters

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1030]
When building a test cluster, fluentd fails to install. This is because it
tries to connect to elasticsearch, the new cluster's IP numbers are not in
the relevant whitelist, so the connection fails.

For the purpose of building a test cluster, this is irrelevant.

Add an elasticsearch pod, as part of the test cluster build script. This
should only be created for test clusters (as opposed to production clusters).

Configure fluentd so that its endpoint is the elasticsearch pod, so that the
cluster create script runs without errors.

**Comment by mtrblmoj** [comment]
After investigation, we found that : 
- fluentd crashes when it tries to access a valid remote `FLUENT_ELASTICSEARCH_HOST`, but is not whitelisted (403)
- fluentd crashes when `FLUENT_ELASTICSEARCH_HOST` is null (!=Nil)
-  **fluentd does not crash when `FLUENT_ELASTICSEARCH_HOST` is set to a random string** (Timeout)
