### ISSUE TITLE
Improve User guide for 'Route 53 hosted zone'

### ISSUE THREAD

**Issue by poornima-moj** [ministryofjustice/cloud-platform#1032]
## Background

Not very clear on how to create custom domains using Route 53

## Proposed user journey

Not sure where and which terraform file the custom domain name has to be provided

Not very clear on how to create the custom domain once the hosted zone is created on Route 53

## Approach

Update/Improve the steps in User guide - Section "Creating a Route 53 Hosted Zone" to include Route53.tf files

We'll do this by creating a walkthrough for the Ruby "Hello World" app.

## Which part of the user docs does this impact

User guide - Section "Creating a Route 53 Hosted Zone" 

## Questions / Assumptions

Is there any verification required for Cloud Platform team to approve the custom domains?

## Definition of done

- [ ] Create a custom domain example for the "Hello World" app
- [ ] Document steps
- [ ] Update the user guide
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mtrblmoj** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/126

https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#creating-a-route-53-hosted-zone
