### ISSUE TITLE
Backup policy for all EBS volumes that are not etcd Volumes

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#1033]
We need a policy to back up EBS volumes (and restore). Currently there is a DLM policy that backs up all etcd volumes for a 2 week period.  This is on the cloud-platform-account level terraform in the cloud-platform-infrastricture repo. 

We also need to think about if we and how we back up user volumes.

**Comment by AntonyBishop** [comment]
Wait to see if we implement Velero

**Comment by sablumiah** [comment]
Velero does this, but it is only accessible by webops team
