### ISSUE TITLE
Leavers - Lukasz

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1036]

**Comment by kcbotsh** [comment]
N.B. please be careful before deleting speak to @sablumiah 

Leavers process defined here https://dsdmoj.atlassian.net/wiki/spaces/PLAT/pages/324076142/Leavers

**Comment by jasonBirchall** [comment]
I've decided to break this ticket down into four parts:
- Observation
Find out what groups Lukasz belongs to.
- Orientation
Use experience from team members, people outside the team and written documentation to decide if removing Lukasz from the groups breaks anything, as he has been in the org for a long time. 
- Decision
Make a decision on when and how to remove his access. 
- Action
Pull trigger and remove, depending on the above steps.

**Comment by jasonBirchall** [comment]
Posted a question to the digital service desk about recovery of slack webhooks. Placing this ticket in blocked until we have a response.
