### ISSUE TITLE
Process For Faster Notification of MoJ Leavers

### ISSUE THREAD

**Issue by pwyborn** [ministryofjustice/cloud-platform#104]
Noticed today (05/06/2018) that Stuart Hollands is still an MoJ team member on Github. Stuart left 31/05/2018. Quite likely that leavers may be on for longer if not spotted.

In collaboration with digitalservicedesk create an automated process for leavers to be removed within a day of leaving

+Defintion of Done +
A Process for removing users promptly (see comment below about contacting Alex Clarke)

**As at 05/06/2018 12:58. There is a possibility that we may be able to offload everything apart from ssh keys and Jenkins removal. So ticket is now probably more to carry on dialogue with Alex 

A question - is it worth spending any time on looking at automation of leavers on our existing structure to connect to such a process?
Also consider how could this benefit out new set up?

**Comment by kalbir** [comment]
Worth talking to Alex Clarke about this (he is in slack) -- he has been talking to service desk about this exact issue 😄

**Comment by pwyborn** [comment]
Note please see ticket https://waffle.io/ministryofjustice/cloud-platform/cards/5b166085f6a608001b124bb2 for correspondence with Alex Clarke
