### ISSUE TITLE
Create a grafana dashboard of circleci average queue times

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1040]
The circleci data from elasticsearch is available in kibana:

https://kibana.cloud-platform.service.justice.gov.uk/circleci-20190625/_search

Use this data to create a grafana dashboard showing average queue times per
hour

**Comment by pwyborn** [comment]
Average time in queue:

https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/dashboard/16aa4330-c35e-11e9-a859-bbe630739c91?_g=(refreshInterval:(pause:!t,value:0),time:(from:now%2Fd,mode:quick,to:now%2Fd))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(darkTheme:!f,hidePanelTitles:!f,useMargins:!t),panels:!((embeddableConfig:(),gridData:(h:15,i:'1',w:24,x:0,y:0),id:'465e3490-c35b-11e9-a650-71c90d5c8ee2',panelIndex:'1',type:visualization,version:'6.4.2')),query:(language:kuery,query:''),timeRestore:!t,title:'Circleci-average%20time_in_queue%2Fproject',viewMode:view)

And Average duration:

https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/dashboard/71bd0d90-c361-11e9-bc3d-8392d34c7adf?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-15m,mode:quick,to:now))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(darkTheme:!t,hidePanelTitles:!f,useMargins:!t),panels:!((embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:15,i:'1',w:24,x:0,y:0),id:'537fcfc0-c361-11e9-a859-bbe630739c91',panelIndex:'1',type:visualization,version:'6.4.2')),query:(language:kuery,query:''),timeRestore:!t,title:'Circleci%20Avg%20duration%20for%20Project',viewMode:view)

**Comment by pwyborn** [comment]
I’m having some problem getting meaningful data  because there are no date fields (start_time) coming from circleci/elasticsearch.
I am assuming that that whole field including “UTC” is just a string

and therefore I cannot do sorts or filtering to the latest minutes/hour etc

Question:
Is there any way of manipulating the data to Kibana? (making it a date field)

**Comment by pwyborn** [comment]
paulwyborn 1:17 PM 17/09/2019
That’s ok David. I assume it will take affect with tomorrows circleci es file?
davidsalgado 3:02 PM 17/09/2019
Yes, that's right. The data that's in there already is the wrong shape, so it's probably simplest to just delete it, rather than going through it all and updating it to have the right field types.
paulwyborn 8:11 PM 17/09/2019
Thankd David - will have a look upon my return on Friday at the Kibana visualisation reports

**Comment by pwyborn** [comment]
## Kibana Dashboards

### summary	
[Circleci-projects-jobs-summary-table-(today-and-yesterday)]	(https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/16e2740af624f450c89e1c8ae93b2dae)
[Circleci-projects-summary-today]	(https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/da59bdf943e39d7204ead313871f2258)
[Circleci-projects-summary-yesterday]	(https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/74cd68379f025634209a20b9137a002c)
	
### duration	
[Circleci-projects-total-duration-(today-and-yesterday)]	(https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/04137ac13e7d7524b7b561692df4e740)
[Circleci-projects-longest-duration-(today-and-yesterday)]	(https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/fca30053abdb1931c778b08429455422)
[Circleci-projects-average-duration-(today-and-yesterday)]	(https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/08919c78411809e87657e939d71c980b)
	
### time in queue	
[Circleci-projects-total-time-in-queue-(today-and-yesterday)]	(https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/85321102913545fd22fd246c17b2e845)
[Circleci-projects-longest-job-time-in-queue-(today-and-yesterday)]	(https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/defee85a7a39669e0425da47072e1038)
[Circleci-projects-average-time-in-queue-(today-and-yesterday)]	(https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/9ade2157c8c285d0f9194262c4b6359e)
	
### jobs Count	
[Circleci-projects-jobs-count-(today-and-yesterday)]	(https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/5707cc023dddca9f4bb09a3d1ba6f0d6)

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/145

**Comment by digitalronin** [comment]
Closed by https://github.com/ministryofjustice/cloud-platform-user-guide/commit/7ec760e2b79598dec606d0c94da13ec0fc6ea9d0
