### ISSUE TITLE
Convert our leavers document to a runbook

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1041]
NB: The runbooks site is publicly-viewable, so we need to remove any details
of specific people from the leavers document, during the conversion.

There is at least one person mentioned by name and email address. Replace
this with a generic address and/or contact procedure.

Run final version via Security as part of the review.

Current leavers document:

https://dsdmoj.atlassian.net/wiki/spaces/PLAT/pages/324076142/Leavers

**Comment by pwyborn** [comment]
Hi Sid,

	As part of the ticket https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/1041 Convert our leavers document to a runbook
I am supposed to "Run final version via Security as part of the review.”

Therefore before I commit my branch to GitHub can you please just check the attached code file to make sure I am not exposing anything to the outside world that I should not.





Paul Wyborn
Senior WebOps Engineer
Cloud Platforms | Justice Digital & Technology
10.54 Tower (Orange Core)

mailto:paul.wyborn@digital.justice.gov.uk

**Comment by pwyborn** [comment]
Anyway I’ll await your or another security engineer’s clearance after looking over the whole document?

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform/pull/1136
