### ISSUE TITLE
Revisit our disaster recovery process, now we have encrypted EBS volumes

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1045]
* Make sure our process works
* Convert the process to a runbook

**Comment by vijay-veeranki-moj** [comment]
https://github.com/ministryofjustice/cloud-platform/pull/1205

**Comment by vijay-veeranki-moj** [comment]
Created a run book for disaster recovery, to restore using etcd-manager.

From the disaster recovery document from Kops `https://github.com/kubernetes/kops/blob/master/docs/etcd/backup-restore.md` , 
Restore volume backups are treated as (legacy etcd), as  etcd-manager (introduced in kops 1.12). Backups for both the main and events etcd clusters are stored in object storage (like S3) together with the cluster configuration.
