### ISSUE TITLE
Default Error Pages for Form Builder

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1046]
## Background

Applications running on the platform can manager their own error pages. However, in cases where the application is offline or otherwise completely unreachable, `nginx-ingress` will serve its own default error page. That page is not helpful to users. We would like to have properly styled fallback error pages that provide a tailored message to the users.

## Approach
`nginx-ingress` provides the ability to serve [custom error pages](https://kubernetes.github.io/ingress-nginx/user-guide/custom-errors/).

There is guidance in that page and links to examples. Essentially, we need to build an image with our custom logic & error pages and plug it into `nginx-ingress`.

With the provided HTTP headers we should be able to provide the desired functionality.

## Questions / Assumptions

The error pages will be provided by the formbuilder team.

This doesn't have to be designed to cater for any user at the moment, we only need to provide this functionality for the formbuilder platform for now.

## Definition of done

- [ ] there is a custom error pages implementation for nginx-ingress that build a docker image
- [ ] it serves formbuilder-styled error pages when the provided headers point to formbuilder
- [ ] it is deployed on live-1

# References
- https://dsdmoj.atlassian.net/jira/software/projects/FB/boards/323?selectedIssue=FB-448

**Comment by alkar** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1562936591480400

**Comment by digitalronin** [comment]
We've created a new repo to manage the docker image we will use to serve custom error pages:
https://github.com/ministryofjustice/cloud-platform-custom-error-pages

This image will only be able to serve a single HTML response, so I've asked the formbuilder team to give us a version of their error page with absolute URLs to assets (images, stylesheets, etc.)
