### ISSUE TITLE
Provide way for nginx ingress to not leak server version details

### ISSUE THREAD

**Issue by solidgoldpig** [ministryofjustice/cloud-platform#1054]
## Service name

Form Builder

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [x] All

## Impact on the service

MoJ's security team carried out a secpen test on a form running on the Form Builder platform and reported Server Version Disclosure as a low-severity vulnerability  - `this information allows an attacker to fingerprint the application and aids in identifying any potential vulnerabilities`.

## Problem description

From our recently performed secpen test:

> *Description*
>
> The web application server returned verbose version information in the 'server' HTTP response header. Although minor, this information allows an attacker to fingerprint the application and aids in identifying any potential vulnerabilities.
>
> *Details*
>
> The following HTTP header returned the version of Nginx in use.
>
> Server: nginx/1.15.8
>
> *Remediation*
>
>It is recommended to remove the 'server' header from the HTTP response.

We need a way (and presumably all other services using CP's nginx ingress) to suppress the server version info being returned.

## Contact person

Alex Robinson @alex.robinson

**Comment by jasonBirchall** [comment]
Passing to backlog for grooming.

**Comment by catelas** [comment]
I do not recommend attempting the proposed resolution.

Rather than attempting to remove the server header (which I do not believe is technically possible) I would recommend changing the header to something which gives away no vendor or product specific technical information and which will remain true for a long period of service, regardless of what the underlying technology is e.g. changing the server header to "MoJ Cloud Hosting Platform".

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.

**Comment by markberridge** [comment]
Hi, this has been raised again as a CVSS 5 in a pen test we had commissioned last month.  Can this please be re-opened?

**Comment by digitalronin** [comment]
As per Mark's comment, I'm reopening this so that we do get around to fixing it.

**Comment by mattmachell** [comment]
The fix is pretty easy: ` server_tokens off;`

http://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens

We do it as part of our nginx container builds:

https://github.com/ministryofjustice/opg-sirius/blob/master/nginx/nginx.conf#L44

**Comment by markberridge** [comment]
Alternatively, for commercially supported Nginx, the header can be disabled completely with `server_tokens "";`
