### ISSUE TITLE
Please add ssh key for all environments for Correspondence Tool and People Finder

### ISSUE THREAD

**Issue by Polsonby** [ministryofjustice/cloud-platform#1059]
## Service name
correspondence_tool_staff
https://track-a-query.service.justice.gov.uk
https://github.com/ministryofjustice/correspondence_tool_staff

peoplefinder
https://peoplefinder.service.gov.uk/
https://github.com/ministryofjustice/peoplefinder

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production
- [X] Other - demo

## Impact on the service

As a new developer on Staff Tools & Services team
I need SSH access to these environments and products listed above
So that I can investigate bugs, deploy releases, and update production data where required

Impact - only one backend developer currently has access to the servers, and neither of us have access to people finder environments so urgent work is blocked

## Problem description

Please can you add my SSH key to the environments for people finder and for correspondence tool staff

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjkPun3OH8n6xPNzQcKLsnc0v75flUFvfkkRuyjjkjj+T/+l3oKAlI9ZL+MmlDzP4EVZTwceQKLjsB0QV4N3Jl89L0Zp7VKoJF7ZFzfocKyHA/l3fvgsZ7dsFY+B8Oc/lPgFvNCy42JNXi7TB3ReQr0RKxmLzQZgtJovZFu0PycDSUKVhs1h6TiYH2QTBHda9x5s9tx8z8B/mPBQgciej7c3kPcAyMmssIGxIKPCYWtWueRZp1DJXlVW+t6DHBegUp/xVGMZ1KX0E5zT48kumtvxCCUig9/rUG4ITyCle8OmbFinzVCL8kTvwmdLgfjMlLPck/3G4eNUl60ZpU0Yfn ipanderson@gmail.com
```

## Contact person

Ian Anderson - please check with Natalya Wells or Alex Douglas if you need further confirmation of the need.

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/pf-deploy/pull/109

**Comment by pwyborn** [comment]
Slack 03/07/2019 11:24:
paulwyborn [11:24 AM]
Hi @Ian Anderson re ticket
```https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/1059```
can you please advise me as to whether you are able to get ssh access to all environments now (both correspondence deploys and peoplefinder deploy?) please?

**Comment by pwyborn** [comment]
Slack 03/07/2019 paulwyborn [4:50 PM]
Hi Ian - you should be able to ssh onto them all now?

Ian Anderson [4:52 PM]
That's fantastic, tried a couple of the ones that weren't working and they're fine now :slightly_smiling_face:
Thanks very much for all your help, it was good to meet you

paulwyborn [4:53 PM]
Presumably you know about
```https://ci.service.dsd.io/view/PeopleFinder/```
and
```https://ci.service.dsd.io/view/correspondence/```

Ian Anderson [4:54 PM]
Ah, kind of - yes, I've used the correspondence tool deploy stuff
My team is getting a few more services over the coming months - presumably we need to do this again for each one?

paulwyborn [4:58 PM]
I think we are encouraging people to move away from template - deploy things in future as we will not be supporting it. Moving towards Kubernetes https://user-guide.cloud-platform.service.justice.gov.uk/#cloud-platform-user-guide (edited) 

Ian Anderson [5:02 PM]
ah yes, that's on our todo list too
thanks again

paulwyborn [5:03 PM]
If you want any information re moving over I’m sure Anthony Bishop or David Salgado would be only too happy to hear from you
Thanks Ian

**Comment by pwyborn** [comment]
To be closed
