### ISSUE TITLE
Show the Thing 28/06/18

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform#106]

**Comment by AntonyBishop** [comment]
Initial suggestion:
Show the Thing on 28th June. Around the whole comms piece we talked about the fact that we have told users that we are building a new thing and we demo’d some Circle stuff. What we didn’t tell them is why and what it means to them. I suggest this be the next STT. My thinking is something along the lines of:
- Why we are building a new platform?
- Benefits of what we are building
- What changes this introduces for Product Teams?
- Where to go to find out more - I.e. speak to us over at the users channel

**Comment by AntonyBishop** [comment]
Draft presentation - https://docs.google.com/presentation/d/16wYlmNJPX85wkIL9rzfGorCGSajF9eDtftkwAepd9PU/edit?usp=sharing

**Comment by AntonyBishop** [comment]
Steve and Tony met to discuss presentation and iterate on content.

**Comment by AntonyBishop** [comment]
Presentation updated. Slides 12 onwards.

**Comment by AntonyBishop** [comment]
Presentation done. Dry run tomorrow.

**Comment by AntonyBishop** [comment]
Dry run done.

**Comment by AntonyBishop** [comment]
STT done.
