### ISSUE TITLE
Fix and alert on support-webhook-labelling

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1062]
**Background**
---
We have a support labelling webhook for tagging issues with the support tag. 

This is failing in live-1 due to the pod security policy not allowing the container to run as the root user. 

**Task**
---
Either:
- find away to run the container as non-root
- don't use the support labelling webhook and use something like github actions
- add support labelling webhook namespace to the allowed list of namespaces running root user.

And:
- Create an alert for when this fails in the future.

**Comment by AntonyBishop** [comment]
Old ticket. Already fixed.
