### ISSUE TITLE
Deprecate external-dns-dsd and cert-manager-dsd

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#1066]
Since we are now hosting all zones in the same account, we do not require this temporary workaround.

Additionally, this setup could potentially cause problem for applications moving from the `live-0` into `live-1`.

- [ ] make sure all zones are currently hosted in the correct account
- [ ] make sure all `Certificates` are configured correctly
- [ ] remove `external-dns-dsd` and `cert-manager-dsd`
- [ ] the user guide has been updated to reflect this change

Related: https://dsdmoj.atlassian.net/browse/LGA-680

**Comment by AntonyBishop** [comment]
This one is a duplicate of an older ticket. Gonna close this one. Update the original and bring that one into the next sprint.

**Comment by alkar** [comment]
@AntonyBishop can you please link the other ticket? Thanks

**Comment by AntonyBishop** [comment]
#984 is original ticket.
