### ISSUE TITLE
Enable SQS queue naming via terraform

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/cloud-platform#1071]
## Service name

Claim for crown court defence

## Service environment

- [X] Dev / Development
- [X] Staging
- [ ] Prod / Production
- [X] Other

## Impact on the service

Improvement - currently SQS generation via terraform creates randomly named queues. 

## Problem description
Fixed queue names would be an improvement because relying on a random url (or randomly generated name) means we need different methods to access them in 3 different apps (CCCD, CCR and CCLF) and 3 different deployment orchestration tools (TD, k8s and AWS-CodePipeline). 

Giving SQS queues a fixed name means we should be able to, app-side, retrieve the url, and transparently poll different queues based on AWS credentials alone

## Contact person
Joel Sugarman
@jsugarman

**Comment by AntonyBishop** [comment]
Hi @jsugarman. What's the urgency on this one? Just so I can get it prioritised. Thanks.

**Comment by jsugarman** [comment]
Hi Anthony, it is not urgent. 

It is more related to having a neater and more robust solution for SQS infrastructure use. current implementation means we have to hardcode a randomly generated URL into
3 codebases. If we need to regenerate these URLs then it would cause failure that, in the case of 2 of those, would have to wait for out of hours deployment to fix.

**Comment by vijay-veeranki-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-sqs/pull/9
