### ISSUE TITLE
Increase SES quota for Form Builder

### ISSUE THREAD

**Issue by jennyd** [ministryofjustice/cloud-platform#1074]
## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We're planning performance testing on Form Builder, and need to increase the daily quotas for email sending in advance of that, in case it impacts the production service.

## Problem description

The FB team don't have access to do this themselves, so need the Cloud Platform team to request this for them. The address from which emails are sent is `formbuilder@digital.justice.gov.uk` and uses SES on the DSD account.

## Contact person

Jenny Duckett, Phil Lee

**Comment by AntonyBishop** [comment]
This ticket will involve raising a support request with AWS.

**Comment by sid234** [comment]
request raised for daily sending quota
