### ISSUE TITLE
Increase capacity for Form Builder go-live

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1076]
## Background

Form Builder requires sufficient capacity to be able to scale in the event of heavy usage of the service.

## Approach

Work with the Form Builder Team to increase limits and replica counts.

## Which part of the user docs does this impact

N/A

## Definition of done

- [ ] Limits increased
- [ ] Replica Counts increased

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
Increased the capacity for Form Builder and Phil from Form-builder is happy to close this.
