### ISSUE TITLE
Namespace level alerting for Form Builder Team

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1077]
## Background

To ensure that Form Builder can scale after go-live we want to ensure that they have alerting in place to ensure that they have sufficient capacity.

## Proposed user journey

Form Builder Team receive appropriate alerts to ensure that they manage capacity of their service.

## Approach

We already have guidance that explains to teams how to set this up. However, as Form Builder team have specific concerns around capacity we want to work with them to ensure that namespace related capacity alerts are in place. 

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

Assumes that appropriate alerts have not already been set up.

## Definition of done

- [ ] alerting in place

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Confirmed with Form Builder team that issue has been dealt with.
