### ISSUE TITLE
New alert routes in AlertManager for Form Builder

### ISSUE THREAD

**Issue by asmega** [ministryofjustice/cloud-platform#1078]
## Service name

Form Builder

## Service environment

- [ ] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Required to implement AlertManager for Form Builder in staging and production environments

## Problem description

Important note: Some work has already been done here https://github.com/ministryofjustice/cloud-platform/issues/1000 as a result a slack webhook already exists and can be reused.

Implement new AlertManager routes for Form Builder staging and production environments. Below is the requested information to do this. Note: this is required in 14 namespaces

namespace names

```
formbuilder-platform-live-production
formbuilder-platform-live-staging
formbuilder-platform-live-dev

formbuilder-services-live-production
formbuilder-services-live-staging
formbuilder-services-live-dev

formbuilder-publisher-live


formbuilder-platform-integration-production
formbuilder-platform-integration-staging
formbuilder-platform-integration-dev

formbuilder-services-integration-production
formbuilder-services-integration-staging
formbuilder-services-integration-dev

formbuilder-publisher-integration
```

team name
Form Builder

application name
Form Builder

slack channel
form-builder-alerts

## Contact person

Phil Lee (me)

**Comment by vijay-veeranki-moj** [comment]
Hi @asmega 

As you want to use the same slack channel `slack channel:form-builder-alerts` to sent the Alerts to, please use the same “custom severity level: form-builder”

Please follow the instructions here
https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#creating-a-slack-webhook-and-amend-alertmanager

Let me know if you have any issues.

**Comment by asmega** [comment]
Thanks! I thought some additional plumbing would be required
