### ISSUE TITLE
Check what version of Postgres we have running for Template Deploy services

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1080]
## Service name

Template Deploy

## Service environment

- [x] Dev / Development
- [x ] Staging
- [x ] Prod / Production
- [x ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

N/A

## Problem description

I am looking to determine if we are running and Postgres 10 or 11 with anything usingTemplate Deploy. Just need a list that can be used to identify which teams might have one.

## Contact person

Tony

**Comment by jasonBirchall** [comment]
Checked all prod DB's in known MOJ prod AWS accounts. All DB's are < 10.
