### ISSUE TITLE
Setup a performance test for Form Builder

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#1082]
## Background

> We want to understand:
> - how many concurrent users can be supported on a form like CFF with our default number of replicas
> - to what extent eg tripling the number of replicas increases that
> - what the impact of people only visiting the first page of the form is on users actually filling it in (ie whether curiosity/publicity-driven traffic is likely to prevent real users from completing the journey)

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by alkar** [comment]
https://github.com/ministryofjustice/fb-performance-tests

**Comment by vijay-veeranki-moj** [comment]
Spoke to Phil in Form-builder team he used this to test Performance for the form-builder application and happy to close this.
