### ISSUE TITLE
How do we know when the Cloud Platform needs more capacity

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1084]
## Background

We have had recent stories that have raised questions about how we manage capacity. What alerts do we need? Capacity of what? What runbooks do we need to manage capacity?

## Proposed user journey

The Cloud Platform Team is alerted when capacity reaches a certain threshold and can take appropriate and timely action to ensure that users of the platform are not negatively impacted.

## Approach

This EPIC is a discovery exercise, which will be followed by a number of smaller stories that will result in changes.

## Which part of the user docs does this impact

TBC

## Definition of done

TBC

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
Closed in favour of #2449
