### ISSUE TITLE
Slow, laggy behaviour in kubernetes Jobs on live-1

### ISSUE THREAD

**Issue by exonian** [ministryofjustice/cloud-platform#1086]
## Service name

LAA legal adviser api (LAALAA)

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Preventing us from deploying to our new kubernetes environments for LAALAA, which is delaying our migrating the service off template deploy

## Problem description

Jobs are being created immediately but they are taking 2-4 minutes to create their pods (normally this is instantaneous)
The pods are then completing quickly but the jobs then are still not recognising this for a couple more minutes

This is intermittent behaviour: it happened on Monday and eventually stopped happening towards the end of the day, but started happening again yesterday.

![Screen Shot 2019-07-12 at 10 32 54](https://user-images.githubusercontent.com/1237986/61119113-0e15c900-a492-11e9-9dfb-196212b80e8b.png)

https://mojdt.slack.com/archives/C57UPMZLY/p1562840906445500

## Contact person
Michael Blatherwick, on slack

**Comment by exonian** [comment]
![Screen Shot 2019-07-12 at 11 07 15](https://user-images.githubusercontent.com/1237986/61120673-6bf7e000-a495-11e9-947b-8cac1a062c77.png)
Example of jobs not detecting that their pods have completed

**Comment by jasonBirchall** [comment]
Cluster resources were limited when this ticket was raised. This should've been resolved by the node scale yesterday. Will check with @exonian

**Comment by jasonBirchall** [comment]
```jasonb 11:04
Good morning. RE https://github.com/ministryofjustice/cloud-platform/issues/1086: this was down to the resource pool being depleted. We've doubled capacity to cope with the recent spike in activity. Can you confirm your jobs are scheduling as expected?```

**Comment by exonian** [comment]
Yep I just did a deploy and everything went through fine. Thanks.
