### ISSUE TITLE
EPIC: Cluster build pipeline with tests

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1090]
Create a regular task, in a separate AWS account, which;

* Creates a new cluster from our codebase
* Runs all our cluster tests, and keeps the output
* Destroys the cluster (if the tests passed)

The purpose of this is to ensure that we are notified if we ever make changes
to the cluster which would break any of the tests.

By using a separate AWS account, we can be confident that this process can
never affect the live cluster, by mistake.

**Comment by AntonyBishop** [comment]
We have made the following decisions in relation to this EPIC:
1. We will not create this for a separate AWS account
2. We will automatically destroy the test cluster when tests are concluded, irrespective of test outcome.
