### ISSUE TITLE
Automate scaling the cluster to match demand for capacity

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1097]
## Background

Currently, we learn we need to increase the size of the cluster when we get alerts about pod scheduling failures. Then we make a manual change to (usually) add more nodes to the cluster.

This isn't great, because users are impacted by the lack of capacity, and it takes manual intervention to fix the problem.

We should be able to automate this, so that we don't run into the scheduling problems in the first place.

relates to #1094, #1093, #1092, #1091 

## Proposed user journey

Cluster capacity should increase, by itself, in response to increased demand.

Also, if demand falls, the cluster should scale itself down so that we're not wasting money on unneeded capacity.

## Approach

One possibility is the [Cluster Autoscaler Addon](https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler)

This sounds as if it will do what we need.

Some caveats are mentioned in [this issue](https://github.com/kubernetes/kops/issues/5646#issuecomment-417751750)

## Which part of the user docs does this impact

The only effect on users is that they should not run into errors when the cluster tries to schedule their workloads, so no user doc changes should be necessary.

## Questions / Assumptions

* If we want the cluster to scale down, we need to confirm that this happens 'gracefully' (i.e. the node is drained, *then* removed from the cluster, and *only then* is the AWS EC2 instance terminated.
* Our kops config will still set a maxSize for the number of nodes in the cluster. We need an alert when we get close to this value (80%?), so that we can intervene either to raise the limit, or fix things if something is eating resources by mistake.
* We should create a script that we can point at a test cluster to start consuming more and then less resources, and confirm that the autoscaler behaves the way we want it to.

## Definition of done

- [ ] we have confirmed that the autoscaler meets our requirements
- [ ] the autoscaler is installed and working in live-1
- [ ] we have set suitable min/max values for the number of nodes
- [ ] team docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
