### ISSUE TITLE
Set a limit on how long concourse keeps build logs

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1099]
We had an incident on 17/07/19 where our concourse instance stopped working
because its database had run out of storage space:

https://mojdt.slack.com/archives/C514ETYJX/p1563349720101000

To prevent this happening again, we should limit the retention of old build
logs, so that the database storage is recycled, and the database does not grow
indefinitely.

Concourse has a
[build_log_retention](https://concourse-ci.org/jobs.html#job-build-log-retention)
configuration parameter, which looks like what we need, although it's not clear
if the helm chart exposes this.

We have [asked the security
team](https://mojdt.slack.com/archives/C52LPHPK8/p1563353220229500) if they
have a preference for how long we should keep build logs (in case they are
relevant to a post-mortem investigation of a security incident).

Their initial thoughts are that logs should be kept for 2 years.  Eventually,
the security team should maintain their own log destination, where they keep
logs for as long as they need them.  Once that is available, we should ship
build logs to that, and reduce the amount of logs we keep.

## Definition of done

 - [ ] Our concourse instance is configured to retain build logs for a limited amount of time and/or number of logs.
 - [ ] The database has enough storage to keep that amount of logs.
 - [ ] The limit, and how to change it, is described in the README of the cloud-platform-concourse repo.

**Comment by davidread** [comment]
https://github.com/ministryofjustice/cloud-platform/issues/2864 is a better way to solve this

**Comment by AntonyBishop** [comment]
Replaced by #2864
