### ISSUE TITLE
Update the documentation of the cloud-platform-concourse repo.

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1100]
The README for the repo. seems a bit stale (e.g. `.k8s.integration.dsd.io`).

Have a look through the repo to tidy up any stale/unneeded stuff, and bring the
README (and any other documentation) up to date.

**Comment by vijay-veeranki-moj** [comment]
This is already completed by @digitalronin.

Closing this issue.

https://github.com/ministryofjustice/cloud-platform-concourse
