### ISSUE TITLE
PersistentVolume deleted with prometheus

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1106]
ISSUE
It seems deleting the prometheus-operator (inc. PVC) also deletes the PV, which led to dataloss.

SOLUTION
 - Investigate the PV <-> PVC relation 
 - Tweak the Retain Policy on PV 
 - Update Disaster Recovery doc

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
