### ISSUE TITLE
Find out why we were not able to cleanly destroy live-1

### ISSUE THREAD

**Issue by mtrblmoj** [ministryofjustice/cloud-platform#1110]
Test clusters destroy cleanly, but when we tried to destroy the live-1 components, the destroy failed. This is probably because the terraform state and the cluster state were out of sync.

Try to replicate the problem by creating a test cluster and deliberately forcing the states out of sync, then see if we can reproduce this problem.

Once we are able to reproduce the problem, figure out a way to get past it.

**Comment by AntonyBishop** [comment]
No longer required.
