### ISSUE TITLE
S3 Lifecycle rule config

### ISSUE THREAD

**Issue by asmega** [ministryofjustice/cloud-platform#1119]
## Service name

Form Builder 

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X] Other

## Impact on the service

We need to be able to delete user data uploaded to S3 to meet data retention policies.

## Problem description

The latest (3.2) s3 terraform module https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket does not support lifecycle configuration rules. One is able to give the user correct permissions to set lifecycle rules on the bucket. However when kubernetes re-applies the module any rules added will be deleted.

From https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/build-environments/jobs/apply-live-1/builds/5995
```
module.user-filestore-s3-bucket.aws_s3_bucket.bucket: Modifying... (ID: cloud-platform-842fe0dec2702daa3a6ca9be44f03b3f)
  lifecycle_rule.#:                                                    "1" => "0"
  lifecycle_rule.0.enabled:                                            "true" => "false"
  lifecycle_rule.0.expiration.#:                                       "1" => "0"
  lifecycle_rule.0.expiration.2705454921.date:                         "" => ""
  lifecycle_rule.0.expiration.2705454921.days:                         "28" => "0"
  lifecycle_rule.0.expiration.2705454921.expired_object_delete_marker: "false" => "false"
  lifecycle_rule.0.prefix:                                             "28d/" => ""
module.user-filestore-s3-bucket.aws_s3_bucket.bucket: Modifications complete after 0s (ID: cloud-platform-842fe0dec2702daa3a6ca9be44f03b3f)
``` 

We would like to be able to create lifecycle rules on buckets which persist when kubernetes reapplies. I see one of 2 choices:
- Either any rules which exist are ignored and not deleted.  
- Or we add our lifecycle rules into the module which kubernetes then applies.  

## Contact person

Phil Lee (me)

**Comment by vijay-veeranki-moj** [comment]
Updated the module, Lifecycle can be created as part of the module
