### ISSUE TITLE
Add `live-0` to environment creation pipeline

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#112]
## Background

We create piplelines by using the [environment creation repo](https://github.com/ministryofjustice/cloud-platform-environments). When you add your environment to the repo it kicks off a pipeline that will build the environment in the appropriate Kubernetes cluster. 

We need to add the `live-0` cluster to this pipeline so that people can build environments in a programmatic way.

## Proposed user journey

- User goes to the [environment creation repo](https://github.com/ministryofjustice/cloud-platform-environments)
- User navigates to the directory for the `live-0` cluster
- User adds their environment defintion as per the [user documentation](https://ministryofjustice.github.io/cloud-platform-user-docs/01-getting-started/003-env-create/#creating-a-cloud-platform-environment)
- The environment builds on the `live-0` cluster
- The user gets a notification in the `cp-build-notification` slack channel

## Approach

Look at the existing pipeline, you should be able to add the new cluster in there. 
You will need to have a credential for building environments on the `live-0` cluster.

## Definition of done

- [x] A user can add an environment to the repo and it builds an environment on `live-0` cluster
- [ ] Someone other than you has tested adding a cluster via this environments repo
- [x] The create environments [user documentation](https://ministryofjustice.github.io/cloud-platform-user-docs/01-getting-started/003-env-create/#creating-a-cloud-platform-environment) is updated to say that people should create environments on the `live-0` cluster (and *not* mention the `non-production` cluster) 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by lukaszraczylo** [comment]
@kalbir as per my conversation with @alkar - I think it'll be better ( for easier pipeline naming for example ) to keep the concourse configuration file(s) within the namespace directory. What's your opinion on that?

**Comment by ale-novo** [comment]
this depends on https://github.com/ministryofjustice/cloud-platform/issues/38

**Comment by kalbir** [comment]
@lukaszraczylo do you mean the configuration files for each pipeline? I think they would be better in a "pipelines" repo.

**Comment by ale-novo** [comment]
i agree that the pipleline files should live inside the corresponding cluster directory, since we will end up having one pipeline per cluster.
questions:
1) think if it would be better to re organice the dir structure, instead of namespaces/<cluster>/<namespace> do clusters/<cluster-name>/namesapces/<namespace-name>/ being <> variables
we could also place a clusters/<cluster>/pipeline/pipeline.yaml file there.

2) is it worth having one pipeline per cluster? or maybe have one pipeline for all supported clusters

**Comment by kalbir** [comment]
I think putting `/clusters/namespaces/$namespace` makes *a lot* more sense. So I agree with 1. 

But we should keep the pipelines separate to repos here, think of the repos here as the data and the pipeline as the way in which we will apply that data. They serve different purposes so they should be in a different repo (one for all pipelines). 

That way it would also make it super easy to build a new concourse instance and recover all the pipelines if they are in a pipelines repo.

**Comment by alkar** [comment]
I don't really see how increasing the depth and complexity of this structure would make it better? I think its current form is the simplest we could go and therefore easier to work with.

**Comment by ale-novo** [comment]
should read `clusters/$cluster-name/namespaces/$namespace-name/ ` instead of `/clusters/namespaces/$namespace`

**Comment by alkar** [comment]
Also, why are we thinking one pipeline per cluster? The way I see it, it's a single pipeline controlling the entire repository. Is there any technical reason why we can't do that?

**Comment by ale-novo** [comment]
i agree with that

**Comment by alkar** [comment]
We could remove the `namespaces` top level directory and bring the individual cluster directories at the top level of the repo.

**Comment by tatyree** [comment]
@alkar / @kalbir I'm moving this to 'done' the last comment was a month ago and it otherwise appears to be merged.
