### ISSUE TITLE
Please setup DNS record for `bookasecuremove.service.justice.gov.uk`

### ISSUE THREAD

**Issue by stevehook** [ministryofjustice/cloud-platform#1120]
## Service name

HMPPS Book A Secure Move

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Needed to roll out the service for our initial MVP release

## Problem description

We have created a Route 53 zone (https://github.com/ministryofjustice/cloud-platform-environments/pull/1016) and now need to configure DNS for `bookasecuremove.service.justice.gov.uk` (following https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#creating-the-resource).

## Contact person

`Steve Hook` on Slack

**Comment by AntonyBishop** [comment]
@stevehook what are your timescales for this. Just so we can prioritise accordingly. Many thanks.

**Comment by stevehook** [comment]
@AntonyBishop we've been asked to get everything setup by tomorrow midday. Sorry it's a bit rushed.

**Comment by AntonyBishop** [comment]
Thanks @stevehook. Vijay is looking into it.

**Comment by vijay-veeranki-moj** [comment]
Done adding the NS records in dsd account, closing this issue now.
