### ISSUE TITLE
Investigate programmatic measures to prevent terraform operations when the terraform state does not match the current kubernetes context

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1123]
## Background

It is too easy to make terraform changes that can impact the wrong cluster. This was the root cause of the recent service failure.

## Proposed user journey

As user should be prevented from making terraform actions when the state does not match the Kubernetes context.

## Which part of the user docs does this impact

N/A

## Definition of done

- [ ] 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
Could this be done with some kind of pre-execution hook which, before doing a terraform apply, compares the current terraform workspace to kubectl cluster-info?

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
