### ISSUE TITLE
Continuous Cluster Deployment for Service Teams

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1126]
**Background**

As some point in time the Cloud Platform is going to fail. The team is optimising the Platform to reduce Mean-Time to Repair. We aim to be able to completely recover the cluster and it's state from code.

Following a recent failure we were able to restore the cluster, however certain parts of the code that teams built could not automatically be recovered. This means more disruption to service team, and a need for them to be part of the recovery process rather than the Cloud Platform team being able to manage it on our users behalf.

To address this problem we believe a GitOps approach to deployment would address this problem. 

*Key benefits of GitOps*
*Automated delivery pipelines roll out changes to your infrastructure when changes are made to Git. But the idea of GitOps goes further than that – it uses tools to compare the actual production state of your whole application with what’s under source control and then it tells you when your cluster doesn’t match the real world.*

*By applying GitOps best practices, there is a ‘source of truth’ for both your infrastructure and application code, allowing development teams to increase velocity and improve system reliability.*

While this will help address the problems we encountered this would potentially introduce changes in how teams deploy to the cluster. These changes in practice will need to be tested with our users.

This story is to investigate how we might manage CD for service teams.
 
**Approach**

Investigate options for how we might manage CD for service teams.

**Questions/Assumptions**
* How could we ensure that users code/state is made available to us to deploy?
* How will we manage secrets?
* Which pipeline will be use to deploy?
* What user documentation will de required?
* What runbooks will be required?
* What impact will this have on Service Teams? (this will be tested with users to understand the impact)
* Opt in/opt out by default?
* List of pros and cons for users?

It's assumed that if we proceed the solution would be implemented one team at a time.

It's assumed that most teams already have separate build and deploy repositories.

**Definition of done:**

We have a plan for how we would implement a solution to this problem that we can discuss with users and get feedback on our proposal.

**Comment by AntonyBishop** [comment]
Tony needs to add more background to this story.

**Comment by AntonyBishop** [comment]
I have updated the story ready for next sprint.

**Comment by razvan-moj** [comment]
https://docs.google.com/document/d/1xGQ6YDUdO4B58g8Z-Lv2fFZJaxBWTlC9UTzG2NbzqSM/edit
