### ISSUE TITLE
Create a document which describes how the various components of the cluster interact

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1127]
## Background

Create a document which describes how the various components of the cluster interact, what their responsibilities are, and how they depend on each other

## Approach

This could be quite an ongoing task. This will be the first iteration and should be kept to a about 1 page.

## Which part of the user docs does this impact

Add as a knowledge item to the user guide.

## Questions / Assumptions

N/A

## Definition of done

- [ ] Created 1 pager
- [ ] Review by the team
- [ ] added as a knowledge items to user guide

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
See https://docs.google.com/spreadsheets/d/1a2nqTqPc_G7jBJ2aW-cjEu9rjI-1vfAEp7P5SdTxPXo/edit#gid=0
