### ISSUE TITLE
Remove `sandbox` cluster

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#113]
## Background

The `sandbox` cluster has run its course, it is built in an entirely different way to our current process and does not have a clear purpose. So this issue is to delete that cluster and any references to it. 

## Approach

I'm not entirely sure how it was built, I think it was entirely with kops, so one option might be to use kops. Other option would be to do it manually, this is obviously more prone to error or leaving things behind. 

## Questions / Assumptions

- Can we delete it and all resources using kops?
- Do we know all the things we need to delete to get rid of it (I've tried to make a list below)?

## Definition of done

- [x] The sandbox cluster does not exist
- [x] Migrate any users (there shouldn't be any really)
- [x] Any resources created for it have been deleted (best list I could think of below):
- [x] delete AWS compute-y resources (EC2, ELB, RDS, storage, VPC)
- [x] delete AWS address-y resources (DNS, certificates)
- [x] delete Auth0 resources
- [x] delete terraform-y resources (state file?) -- be careful with this one, other clusters might share the same e.g. S3 bucket
- [x] delete any references to sandbox cluster in docs/repos (search in out github repos) 
- [x] make some rough notes on how to do this so we can work out how to automate it (super rough)

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ale-novo** [comment]
how to delete a cluster:
kops delete cluster --name=`cluster-name` --state=s3://`state-store`

**Comment by ale-novo** [comment]
cluster was destroyed using kops and terraform

aws resources  were destroyed

**Comment by ale-novo** [comment]
terraform workspace was deleted

**Comment by ale-novo** [comment]
pr https://github.com/ministryofjustice/kubernetes-investigations/pull/39 was raised to remove any reference of the sandbox cluster in the repo

**Comment by ale-novo** [comment]
oidcClientID is shared with other clusters so we cant remove for now the Auth0 entry.

**Comment by ale-novo** [comment]
this pr was merged
this tkt is now completed.
