### ISSUE TITLE
New alert routes in Alertmanager live-1

### ISSUE THREAD

**Issue by Kalagan** [ministryofjustice/cloud-platform#1133]
## Service name

`laa-apply-for-legal-aid`

## Service environment

- [ ] Dev / Development
- [X] Staging
- [X] Prod / Production
- [X] UAT

## Problem description

As per https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#creating-your-own-custom-alerts, we would like new alert routes in Alertmanager live-1?

```
namespace: laa-apply-for-legalaid-uat
team: apply-for-legal-aid
application: laa-apply-for-legal-aid
slack: #apply-alerts-uat
severity: apply-for-legal-aid-uat
```

```
namespace: laa-apply-for-legalaid-staging
team: apply-for-legal-aid
application: laa-apply-for-legal-aid
slack: #apply-alerts-staging
severity: apply-for-legal-aid-staging
```

```
namespace: laa-apply-for-legalaid-production
team: apply-for-legal-aid
application: laa-apply-for-legal-aid
slack: #apply-alerts-prod
severity: apply-for-legal-aid-prod
```

## Contact person

Slack: Julien Sansot

**Comment by Kalagan** [comment]
It would be great if you could use the severity names provided. So they can be the same as the ones we have on live-0

**Comment by pwyborn** [comment]
paulwyborn  [30/07/2019 #ask-cloud-platform]
Hi Julien @Julien Sansot - my apologies - those severities should already be there in live-1. You just need to reapply your alert ConfigMaps in your live-1 namespaces. Let me know if you have any problems please?

**Comment by pwyborn** [comment]
To be closed

**Comment by pwyborn** [comment]
Closed pull request https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/332
As i believe that the config is already there (carried out in a different way to live-o)

Hi @Julien Sansot - I believe that the severities are there. Can you please reapply your alert ConfigMaps in your live-1 namespaces and test - thanks Julien

**Comment by pwyborn** [comment]
To be closed
