### ISSUE TITLE
Prison Visits Pingdom Integration ID

### ISSUE THREAD

**Issue by KPobeeNorris** [ministryofjustice/cloud-platform#1137]
## Service name

Prison Visits Booking

## Service environment

- [ ] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

We would like improved visibility of our service.

## Problem description

We have recently migrated Prison Visits Booking on to K8s and would like to set up Pingdom alerts.  As per the CP User Guide I am submitting a request for an integration to be set up:
Team name: PVB / Prison Visits Booking
App name: Prison Visits Booking
Slack channel: #prison-visits-alerts

I have started a branch for adding Pingdom to our namespace, but wasn't sure if this needed to be merged in before the integration creation, or after we get the integration ID and add it in to what will be the final PR.

## Contact person

@kath.pobee-norris (Slack)

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/blob/master/docs/creating-pingdom-webhook.md

**Comment by jasonBirchall** [comment]
Work complete.
