### ISSUE TITLE
Request for new alert route in Alertmanager - Prison Visits

### ISSUE THREAD

**Issue by KPobeeNorris** [ministryofjustice/cloud-platform#1138]
## Service name

Prison Visits Booking / PVB

## Service environment

- [ ] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Improved alerting for our app

## Problem description

We would like to request a new alert route in the Alertmanager so we can set up custom Prometheus rules in both our staging and prod namespaces.

namespace name: prison-visits-booking-staging / prison-visits-booking-production
team name: Prison Visits Booking / PVB
application name: Prison Visits Booking
slack channel: prison-visits-alerts

Please do get in touch if you need any additional information.

## Contact person

Slack - @kath.pobee-norris

**Comment by pwyborn** [comment]
Hi Kath @kath.pobee-norris - looking at your ticket “Request for new alert route in Alertmanager - Prison Visits#1138”. It should be there. Severity/Team name “Prison Visits Booking / PVB”. (edited) 
The only query I have is that normally the severity/team name does not have spaces in it i.e “prisoner-money”
Could you please test to see if it works ok?
```https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#create-a-prometheusrule```

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/337

**Comment by pwyborn** [comment]
kath.pobee-norris [12:18 PM]
Hi Paul, thanks for this.  We’re just in the middle of dealing with a couple of issues on our service at the moment, but will try and get this tested ASAP and let you know if it works
