### ISSUE TITLE
Setup nameserver for apply for legal aid

### ISSUE THREAD

**Issue by willc-work** [ministryofjustice/cloud-platform#1139]
## Service name

Apply for Legal Aid

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

none, this is adding a new domain to a private beta service
domain name required: apply-for-legal-aid.service.justice.gov.uk
## Problem description

need to set up name server for the new domain under ```.service.justive.gov.uk```

## Contact person

will clarke
slack @willclarke
email william.clarke@digital.justice.gov,uk

**Comment by vijay-veeranki-moj** [comment]
Added NS records in the parent zone(DSD account)
