### ISSUE TITLE
Problems pushing branch to git repo /wp-cloudformation-params

### ISSUE THREAD

**Issue by brown-a2** [ministryofjustice/cloud-platform#114]
## Service name
https://github.com/ministryofjustice/wp-cloudformation-params

## Service environment

Github

## Impact on the service

I'm making changes to the IP whitelist for the intranet

## Problem description

While I can clone the repo, when I push my branch back up to the repo, git gives me a message saying that the repo doesn't exist. That normally means that the permissions are set to read-only. 

## Contact person

Adam Brown
@abrown

**Comment by jasonBirchall** [comment]
Developer was missing a GH group, which he now has access to and can confirm access. 

Closing ticket.
