### ISSUE TITLE
Move authorized-keys-provider to live-1

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#1141]
In order to bootstrap our nodes with the team member SSH keys, we have the following setup:

- [authorized-keys-provider][akp] is a service that regularly fetches the keys of the `webops` team members from GitHub and generates an `authorized_keys` file in a _public_ S3 bucket. The entire setup is contained within `cloud-platform-environments`.
- [authorized-keys-manager][akm] is a systemd service that's deployed on each node (masters, workers and the bastion) that will regularly fetch the generated `authorized_keys` file from the bucket and update their local copy.

The provider service lives on the `live-0` cluster and will have to be migrated:

1. Duplicate the setup on `live-1` (this will create a new S3 bucket)
2. Update namespace owner tags to platforms team email address
3. Update the [URL to the file](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/terraform/cloud-platform/bastion.tf#L5) after you've verified it's being generated properly.
4. `terraform apply` and `kops update`:
    - for the bastion host, you can simply terminate the old instance for this to take effect
    - for the kube nodes, you will need to start a rolling update
5. Add a unit test

[akp]: https://github.com/ministryofjustice/cloud-platform-environments/tree/master/namespaces/cloud-platform-live-0.k8s.integration.dsd.io/authorized-keys-provider
[akm]: https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/terraform/cloud-platform/resources/bastion/authorized_keys_manager.service

**Comment by vijay-veeranki-moj** [comment]
Created a new ticket for Integration tests
