### ISSUE TITLE
Reduce the size of the Alertmanager configuration

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#1142]
As more teams are setup to use Alertmanager for monitoring, its configuration file will increase in size.
For every new team setup, we need to create a "route" and a "receiver". The configuration for the [receiver][receiver] is mostly the same across different configuration (with the exception of the slack webhook and channel) so we could easily extract it as a YAML anchor to the top of the [config file][am-config] and use the merge feature. This should decrease the overall size of the config significantly and prevent and unfortunate issues in the future.

[receiver]: https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/terraform/cloud-platform-components/prometheus.tf#L53-L78
[am-config]: https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl#L88

**Comment by kcbotsh** [comment]
We think this has already been done. Double-check, and close if this is redundant.

**Comment by AntonyBishop** [comment]
Check this has been completed

**Comment by AntonyBishop** [comment]
Already done.
