### ISSUE TITLE
Cleanup prisonvisits.service.gov.uk zone

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#1144]
We currently have two zones:
- prisonvisits.service.gov.uk
- prisonvisits.service.justice.gov.uk

The latter was created to solve a temporary DNS issue and should be redundant now.

The former one has a CNAME for `www.prisonvisits.service.gov.uk` which is supposed to be record managed by `external-dns` and so produces an error in its logs.

Additionally, there are a number of additional records in the first zone that are not defined in code. It would be prudent to have them version controlled like other resources [here](https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-visits-booking-production/resources/route53.tf).

**Comment by AntonyBishop** [comment]
Have raised question about priority with the PVB team. Workaround may need to be long lived.

**Comment by AntonyBishop** [comment]
PVB team been to review their domains. It's very likely that tidying up this workaround would break production service. PVB team have raised a ticket to review the situation (https://dsdmoj.atlassian.net/jira/software/projects/VISITS/boards/367?selectedIssue=VISITS-21) but it is likely that the workaround will remain in place.

Review in 2 months.

**Comment by vijay-veeranki-moj** [comment]
Hi @AntonyBishop 
I think we should look at below ones, as for 1st one we are getting error in external DNS, and the second one is to make sure that it is inline with all the zones in cp account.

May be they should be treated as two separate stories?

1) The former one has a CNAME for www.prisonvisits.service.gov.uk which is supposed to be record managed by external-dns and so produces an error in its logs.


```
external-dns-5479789fb8-p8rmf external-dns time="2019-08-05T15:26:24Z" level=error msg="InvalidChangeBatch: [RRSet of type A with DNS name www.prisonvisits.service.gov.uk. is not permitted because a conflicting RRSet of type  CNAME with the same DNS name already exists in zone prisonvisits.service.gov.uk.]\n\tstatus code: 400, request id: 569891c4-5f51-4c4f-a1f0-42bd231dcdb8"
````

2) Additionally, there are a number of additional records in the first zone that are not defined in code. It would be prudent to have them version controlled like other resources here.

**Comment by AntonyBishop** [comment]
Assume that part 2 or this is covered by #1087?

**Comment by AntonyBishop** [comment]
On the first part why are we getting errors? What is the impact of these errors?

**Comment by vijay-veeranki-moj** [comment]
Additionally, there are a number of additional records in the first zone that are not defined in code. It would be prudent to have them version controlled like other resources here.

The above is covered in #1087 

I think we need to look at this error:

`The former one has a CNAME for www.prisonvisits.service.gov.uk which is supposed to be record managed by external-dns and so produces an error in its logs.`

Not sure about what is the impact of this error, we need to figure it out, creating a task for it?
