### ISSUE TITLE
Restart RDS instance

### ISSUE THREAD

**Issue by asmega** [ministryofjustice/cloud-platform#1146]
## Service name

form builder

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

To test `force-ssl` on non-production RDS instance 

## Problem description

Following on from https://github.com/ministryofjustice/cloud-platform-environments/pull/1051 we would like to restart the rds instance to test `force-ssl`. The rds instance info can be found at `kubectl -n formbuilder-platform-test-dev get secrets rds-instance-formbuilder-user-datastore-test-dev -o yaml` as this is a non-production instance there is no need to schedule and this can happen at the earliest convenient moment.

## Contact person

Phil Lee (me)

**Comment by digitalronin** [comment]
Rebooted the RDS instance.
