### ISSUE TITLE
Add a 'data sanitisation' concept article to the user guide

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1148]
Based on a conversation with Adrian Warman in the security team, we should add
an article to the user guide that makes it clear to service teams that it is up
to them if they need special cleanup of any data they store in the cluster.

i.e. if an application writes a sensitive file into local storage in a
container (e.g. a temporary copy of a generated PDF containing personal
information on a user), such files are not guaranteed to be securely erased
from the cluster if/when the pod is evicted/terminated. Any filespace used by
the container will be marked as unused by the OS, but it would still be
possible to recover the data if you had access to the node.

In many cases, this will not be an issue, because data will normally not be
stored in the container filesystem. But it is important that teams are aware of
this issue, so that they can take appropriate steps to securely erase any
temporary data their applications generate.

Here is the relevant part of the email from Adrian:

> What we'd like to do is to progress an update to the Cloud Platform SAT entry accordingly. Namely, to work towards changing the OID26 entry: "Protect: data is adequately sanitised at end of lifecycle" from an N/A rating to a 'Held' and confidence score of 14 (ie, high confidence).  To do this, it would be helpful if you point me at the section of Cloud Platform docs that specifically mentions that applications (ie, any consumer of a Cloud Platform service provision) have responsibility for sanitising the data or requesting assistance from the Cloud Platform team to do so. If the docs don't currently call that out, we would advise that a suitable sentence or two be added at the earliest opportunity to do so.  I very much hope that this is not a burdensome request; we are primarily interested in making sure that consumers of the service know they have the responsibility for sanitising data at the end of lifecyle, rather than the Cloud Platform team.

**Comment by warmanaMOJ** [comment]
Definitely doesn't need to be a big item or article - just a couple of sentences making clear where the responsibility lies, and what the service team needs to be aware of about data sanitising.

Very happy to help - just ask.

Thanks,

Adrian

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
