### ISSUE TITLE
Request a new alert route in Alertmanager for MOIC

### ISSUE THREAD

**Issue by KPobeeNorris** [ministryofjustice/cloud-platform#1159]
## Service name

MOIC / offender-management

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [x] Other - preprod

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Without being able to set up custom alerts we will have reduced visibility of our service. 

## Problem description

We would like to request a new alert route in the Alertmanager so we can set up custom Prometheus rules in both our staging, preprod and prod namespaces.

namespace name: offender-management-production/offender-management-staging/offender-management-preprod
team name: moic
application name: Manage Offenders In Custody
slack channel: moic-alerts

Please do get in touch if you need any additional information.

## Contact person

Slack - @kath.pobee-norris

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/342

**Comment by pwyborn** [comment]
paulwyborn [10:12 AM]
Hi Kath your alert route (severity “moic”) should be there now?

**Comment by pwyborn** [comment]
kath.pobee-norris [10:21 AM]
Thanks Paul, I’ve seen the message in the channel saying it’s been added.  I’ll set aside some time later to get some custom alerts added to the namespaces


paulwyborn [10:24 AM]
ok thanks Kath
