### ISSUE TITLE
Test increasing the number of master nodes from 3 to 5 on a test cluster

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1166]
**Background:**
This is considered best practice, and should make the cluster more
resilient.

**Approach:**

This is a well documented process, however we would like to trial this on a test cluster prior to applying on `Live-1`.

**Definition of Done:**

- [ ] Test cluster is running with 5 master nodes
- [ ] Documentation in support of process to increase number of master nodes
- [ ] List of any issues encountered that need to be addressed for `Live-1` production upgrade

**Comment by AntonyBishop** [comment]
We can't do this. Revisit when we build a new live cluster
