### ISSUE TITLE
checkmydiary.service.justice.gov.uk DNS record

### ISSUE THREAD

**Issue by jhackettpps** [ministryofjustice/cloud-platform#1174]
## Service name
Check My Diary

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

We need `checkmydiary.service.justice.gov.uk` setting up as a zone so we can add records for it as resources in the `check-my-diary-prod` namespace. 

PR for zone creation: https://github.com/ministryofjustice/cloud-platform-environments/pull/1119

Original request by Murilo Lessa who is their DM.

**Comment by jhackettpps** [comment]
Created the zone for this now.

**Comment by vijay-veeranki-moj** [comment]
Created NS records in parent zone(dsd)
