### ISSUE TITLE
Add a CNAME to `apply-to-court-about-child-arrangements.dsd.io`

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#118]
## Apply to court about child arrangements

https://apply-to-court-about-child-arrangements.dsd.io

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Our current service domain is quite long and we need a shorter version to print the URL in posters and other physical assets to show in participant courts (our service is on a private beta with limited courts).

Also the short URL will be provided via call centres.

Ideally what we want is the following suggested domain: https://c100.dsd.io

We will append some tracking bits so, for example https://c100.dsd.io/xyz will hit our service, where we will expand it to redirect to https://apply-to-court-about-child-arrangements.dsd.io?utm_source=court&utm_medium=poster

## Problem description

There are no problems.

## Contact person

Thank you 💯 

Jesus / @zheileman

**Comment by jasonBirchall** [comment]
Transcript of conversation with Developer:

jesus [Yesterday at 15:28]
in #ask-cloud-platform
Hello. What would be the procedure to add a CNAME to our current service domain? (our service URL is a dsd.io one). Should I submit a request ticket?


11 replies
jasonb [5 minutes ago]
Morning @jesus, do you want your new CNAME pointing at the same value: `apply-to-court-about-child-arrangements.dsd.io.herokudns.com`?


jesus [4 minutes ago]
yes I think so, it will use the same app


jasonb [4 minutes ago]
:thumbsup: no probs.


jasonb [4 minutes ago]
two secs


jesus [4 minutes ago]
great thx!


jasonb [2 minutes ago]
CNAME `c100.dsd.io` created and pointing at `apply-to-court-about-child-arrangements.dsd.io.herokudns.com` as per request.


jesus [1 minute ago]
fantastic, thank you very much :tada:

jasonb [1 minute ago]
Do you want to trash the old CNAME?


jesus [< 1 minute ago]
oh no, we will use both, this new one is just a shorter alias, but the other dsd.io domain is going to be the main one


jasonb [< 1 minute ago]
:thumbsup: All done. I'll close the ticket.


jesus [< 1 minute ago]
cool, thx!

**Comment by jasonBirchall** [comment]
Task complete. Closing ticket.
