### ISSUE TITLE
Change the concourse pipelines to use the tools image from docker hub

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1187]
The bootstrap, plan and build pipelines are using the tools image from the
platforms-integration AWS account. Change this to use the image from docker hub.

NB: The cloud-platform tools image has been altered to run as a non-root
user, so there may be some other changes required.

**Comment by AntonyBishop** [comment]
This is still one pipeline for tz-cronjobber that needs to be completed.
