### ISSUE TITLE
Catalogue and import any manually-created DNS records in route53

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1188]
All route53 zones are now defined in our terraform code.

For each route53 zone we create via terraform, 4 DNS records are automatically
created;

* start of authority record (created with the zone)
* nameservers (created with the zone)
* A record created by external DNS
* txt record created by external DNS

Depending on when you look, there might also be an ephemeral TXT record
created by cert-manager during the letsencrypt validation process.

All of these records will be automatically recreated if we were ever to lose
the route53 zone. However, some teams have added additional DNS records
'manually' In the event that we lose the zone, these records would also be
lost.

We need two things;

1. A script which iterates over all route53 zones, and identifies any DNS
records which would *not* be recreated automatically, if the zone were lost

2. A process (preferably automated or semi-automated) for importing those
DNS records into our terraform code and state.

Ultimately, we should have all essential DNS records as code in our repo, and
a process which automatically alerts us about (and/or automatically imports)
any DNS records which are created outside of our terraform code.

**Comment by AntonyBishop** [comment]
Completed. There is only one domain outstanding, however the service team have it in their backlog to address this.
