### ISSUE TITLE
Maintain a list of all DSD route53 zones which delegate to zones in the cloud platform account

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1190]
We have around 40 zones in DSD which are delegated to zones in cloud platform.

The cloud platform zones are defined in terraform code, but the delegation is
not documented anywhere, as far as we know.

1. Create a script which iterates over DSD route53 zones and generates a text
file containing all the details of relevant zone delegation

2. Check the text file into our environments repo, somewhere

3. Create a runbook describing this process, and how the text file could be
used to recreate the zone delegation setup (manually would do, scripted would
be better).

4. Create a recurring ticket to re-create the text file every so often (every
month?) and add any updates to the environments repo

**Comment by davidread** [comment]
OpsEng are talking about managing DSD's R53 as code. Not our responsibility.
