### ISSUE TITLE
Plan for upgrade to kubernetes 1.13.10

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1192]
## Background

For a number of reasons we want to upgrade to Kubernetes v1.13.10 - go1.11.13.

## Approach

We need to upgrade but need to understand what changes the upgrade introduces and what testing we need to carry out. This story is to plan the upgrade.

New stories will be created for the upgrade.

## Definition of done

- [x] We have documented what breaking changes the upgrade might include
- [x] Plan to address any breaking changes
- [x] Testing strategy
- [x] Draft runbook for the upgrade

## Reference

[Upgrade documentation](https://kubernetes.io/docs/tasks/administer-cluster/cluster-management/#upgrading-a-cluster)

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
Changes listed in
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/374
https://github.com/ministryofjustice/cloud-platform/pull/1207
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/374

**Comment by sablumiah** [comment]
https://docs.google.com/document/d/1iQI22PM_gAi2fteHWO_dCgUpKSweL-ag3sT2ZxMW3XY/edit?usp=sharing
