### ISSUE TITLE
Add a runbook for the 'manual' certificate renewal procedure

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1200]
The process of issuing/renewing SSL certificates which are NOT
managed by cert-manager is manual, and depends on specific
individuals.

e.g. https://mojdt.slack.com/archives/C57UPMZLY/p1566987997001800

Document the procedure in a runbook, so that certificates can be renewed,
regardless of which team members are available.

**Comment by AntonyBishop** [comment]
Current documented process can be found here - https://docs.google.com/document/d/1H8Hco4dzJwcjXXZzyQc_0ivqLw-Q9z3BuqBnlL5lA7Y/edit?usp=sharing

**Comment by AntonyBishop** [comment]
Reading "Add a new runbook" from the runbook site

**Comment by AntonyBishop** [comment]
Runbook created.
