### ISSUE TITLE
What problems do we want to solve with a GitOps approach?

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1206]
## Background

We are looking at implementing GitOps. Are we clear about what we mean by GitOps? What problems are we trying to solve? How to we ensure that anything implement is aligned to out longer terms goals and user needs.

## Approach

A session for the team to discuss out longer terms strategy for implementing GitOps.

## Definition of done

- [ ] Documented set of problems we wish to address with GitOps.
- [ ] Roadmap for GitOps

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
This will be answered in Continuous Cluster Deployment for Service Teams#1126
