### ISSUE TITLE
Please add my ssh key to the correspondence-staff-deploy repo

### ISSUE THREAD

**Issue by danielatdigital** [ministryofjustice/cloud-platform#1208]
## Service name
Correspondence tool

## Service environment
- [ ] Other
Deployment repo

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description
Please add the following public key to the repo, so I can access the Correspondence tool AWS instances.

(please dm me for the key - doesn't feel right adding it to the issue)

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/correspondence-staff-deploy/pull/74

**Comment by pwyborn** [comment]
paulwyborn 3:17 PM
Hey Daniel - re ticket
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/1208
can you let me know if you are able to ssh onto the correspondence-staff-deploy repo?
https://github.com/ministryofjustice/correspondence-staff-deploy/pull/74
refers
