### ISSUE TITLE
Change the kuberos page you get when you first login to a cluster

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#121]
## Background

When you first authenticate to a cluster you get taken to a Kuberos page that explains how to setup your kubectl so that you can access the cluster. The page looks like this:

![screen shot 2018-06-06 at 12 28 00](https://user-images.githubusercontent.com/3952074/41044192-9311793c-699d-11e8-8b50-fcb3c17b9f15.png)

We have found from some users that this page is confusing.

<img width="920" alt="screen shot 2018-06-06 at 15 24 38" src="https://user-images.githubusercontent.com/3952074/41044287-d342e63a-699d-11e8-8ffb-448c01c6bd90.png">

<img width="898" alt="screen shot 2018-06-06 at 15 25 56" src="https://user-images.githubusercontent.com/3952074/41044343-f312de84-699d-11e8-8f95-0f93305a220e.png">

## Proposed user journey

We currently ask users to authenticate to the cluster *before they create a namespace*. So there is not much they can do with the resulting credential. What we want then is for:

- User to go to user docs to authenticate to the cluster
- User goes through auth process (auth0-github handshake)
- [NEW] User lands on a you have completed authentication page
- [NEW] Page explains:
    - how the user setups up `~/.kube/config`
    - how the user can add the new cluster to their config if they already have a cluster configured
    - which commands they can currently run and what the output looks like 
     - what to do next (create a namespace)

## Approach

Kuberos is a docker image that we deploy onto the cluster through helm, see https://github.com/ministryofjustice/kubernetes-investigations/blob/master/cluster-components/non-prod-kuberos/deployment.yml

We will want to fork kuberos, change the page that you are presented with when you authenticate, build a new image and then deploy that new image. 

You'll want to test this on the test cluster, it might be a little tricky to test as if you break something you'll potentially screw up auth. But the change is pretty simple so it should be okay.

## Definition of done

- [x] When a user authenticates they get shown a page explaining how to set up their `~/.kube/config` to connect to the cluster
- [x] When a user authenticates they get shown a page explaining how the user can add the new cluster to their config if they already have a cluster configured
- [x] When a user authenticates they get shown a page explaining which commands they can currently run and what the output looks like 
- [x] When a user authenticates they get shown a page explaining what to do next *with a link to the user documentation on creating a namespace*

Maybe break out the following ones into their own story
- [x] Push the docker image somewhere we can deploy it to the cluster 
- [x] We have an automated way of creating the new image and pushing it to a repo
- [x] Add details in the readme of how to build the image and push it to the repository

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by nayoa** [comment]
New kuberos page - http://login.apps.cloud-platform-live-0.k8s.integration.dsd.io/
CircleCI build - https://circleci.com/gh/ministryofjustice/kuberos
Kuberos ECR - https://eu-west-1.console.aws.amazon.com/ecs/home?region=eu-west-1#/repositories/cloud-platform:kuberos#images;tagStatus=ALL

PR's
https://github.com/ministryofjustice/kuberos/pull/1
https://github.com/ministryofjustice/cloud-platform-environments/pull/162
https://github.com/ministryofjustice/kuberos/pull/2
https://github.com/ministryofjustice/kubernetes-investigations/pull/74
https://github.com/ministryofjustice/kuberos/pull/3

Next steps -
To automate the cluster name in the application
