### ISSUE TITLE
Create a `test-0` cluster

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#122]
## Definition of done

- [ ] must compile
- [ ] must pass tests
- [ ] must address all the steps of user journey

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by alkar** [comment]
- https://github.com/ministryofjustice/kubernetes-investigations/pull/38
- https://github.com/ministryofjustice/kubernetes-investigations/pull/40
- https://github.com/ministryofjustice/cloud-platform-environments/pull/14

Completed
