### ISSUE TITLE
Deafault error pages cannot load the design system assets

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#1221]
CP custom error pages no longer can load the design system assets.

https://github.com/ministryofjustice/cloud-platform-custom-error-pages/blob/master/rootfs/www/4xx.html#L11

It may be because of  the links we use.

Need to find a root cause of it and fix this

**Comment by digitalronin** [comment]
Fixed by https://github.com/ministryofjustice/cloud-platform-custom-error-pages/pull/3
