### ISSUE TITLE
Create a new joiner guide in our internal cloud platform runbooks

### ISSUE THREAD

**Issue by pwyborn** [ministryofjustice/cloud-platform#1224]
## Background

We created a new joiner guide however - this was when there was only Template Deploy.(see the confluence one for template-deploy https://drive.google.com/open?id=1NKyEsW4UIewELvvmurQpqhg3Y2cM-rrF)

We need a new a guide. This might be a good one for someone that has joined recently and has recent experience of the things that have helped them?

## Approach

* Create it as a guide (find out if there is anything already in existence)
* Create it as a run-book here https://runbooks.cloud-platform.service.justice.gov.uk/#cloud-platform-runbooks (note there is already a "Leavers Guide here")

## Which part of the user docs does this impact

N/A

## Definition of done

- [ ] We have a "New Joiner" run-book guide in situ.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Runbook created.
