### ISSUE TITLE
Deploy concourse onto the `test-0` cluster

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#123]
## Background

Depends on #122.  

Use the instructions

## Approach

Follow instructions in https://github.com/ministryofjustice/cloud-platform-concourse

## Definition of done

- [ ] must compile
- [ ] must pass tests
- [ ] must address all the steps of user journey

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by alkar** [comment]
Resolved by https://github.com/ministryofjustice/cloud-platform-concourse/pull/10
