### ISSUE TITLE
Live-1 RootVolUtilisation-High

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1231]
[FIRING:1] :warning: RootVolUtilisation-High
Alert: 172.20.55.101:9100 has exceeded the threshold of root volume utilisation with a value of 87.93392284370277. Instance 172.20.55.101:9100 root volume utilisation usage is high
     Details:
      - alertname: RootVolUtilisation-High
      - device: /dev/nvme0n1p2
      - endpoint: metrics
 Show more
https://alertmanager.cloud-platform.service.justice.gov.uk

**Comment by pwyborn** [comment]
![Screen Shot 2019-09-17 at 10.56.34.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/2094c85f-315c-483f-a191-78f38a49a7f0)

![Screen Shot 2019-09-17 at 10.56.16.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/b3ba5ba6-1d73-49c8-b910-c336f2da5be3)

**Comment by pwyborn** [comment]
DiskPressure     True    Tue, 17 Sep 2019 12:51:18 +0100   Mon, 16 Sep 2019 14:48:04 +0100   KubeletHasDiskPressure       kubelet has disk pressure

**Comment by pwyborn** [comment]
![Screen Shot 2019-09-17 at 14.11.21.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/bfdee087-a3da-4926-97a8-f4c2abafcd4d)![Screen Shot 2019-09-17 at 14.12.27.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/0c030b4e-81bb-4e86-8f4b-dd006982e943)

**Comment by pwyborn** [comment]
![Screen Shot 2019-09-17 at 14.56.13.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/a4c4c7a9-265e-4f66-acf4-e458be20404d)

**Comment by pwyborn** [comment]
jasonb 3:51 PM 17/09/2019
Hey.

I have a feeling the fluentd buffer full issue is causing this alert to trigger

paulwyborn 8:09 PM 17/09/2019
Thanks Jason - will have a look at on my return on Friday (unless it needs dealing with before then)?

**Comment by pwyborn** [comment]
jasonb 8:20 PM 17/09/2019
It's sorted. The node needed restarting.
:thumbsup:
paulwyborn:speech_balloon: 8:21 PM  17/09/2019
Hi Jason - was it the fluentd buffer in the end (I will have to find out how you sorted it - for my info)?
jasonb 8:22 PM  17/09/2019
there were containers using ephemeral storage, could've been fluentd so we'll see if it fills up again.
paulwyborn:speech_balloon: 8:23 PM  17/09/2019
:thumbsup:
