### ISSUE TITLE
Create a list of components that require an upgrade

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1239]
## Background

We are upgrading our version of Kubernetes. We also want to ensure that our components are upgraded.

We are unclear what components need to be updated so we want to create a list so that we can plan the relevant upgrades.

## Proposed user journey

Components are upgraded to a supported level.

## Approach

Review all our components. Identify which components need to be upgraded.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

- [x] We have a list of components to be upgraded
- [x] List includes current version
- [x] List included version to which we should upgrade.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
Some of the components i came across:

1) Concourse
 we are at:
    chart version: 5.0.0
    appVersion: 5.0.0
   
  latest:
    
    chart version: 8.2.5
    appVersion: 5.5.0
  

2) Nginx-Ingress-controller

we are at:
     Chart version   = "v1.3.1"

   latest:
    Chart version: 1.21.0
    appVersion: 0.25.1

3) Externel-dns

**Comment by pwyborn** [comment]
https://docs.google.com/spreadsheets/d/1a2nqTqPc_G7jBJ2aW-cjEu9rjI-1vfAEp7P5SdTxPXo/edit#gid=0
