### ISSUE TITLE
Kubernetes 1.13 upgrade - Build Test Cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1243]
## Background

As part of the upgrade we want to test on a "live like" test cluster.

Prior to the work we will create a 40 node cluster. 

## Approach

Create a large test cluster specifically for the upgrade.

## Definition of done

- [ ] test cluster created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://docs.google.com/document/d/1iQI22PM_gAi2fteHWO_dCgUpKSweL-ag3sT2ZxMW3XY/edit?usp=sharing
