### ISSUE TITLE
Kubernetes 1.13 upgrade - Deploy multi-container app to test cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1244]
## Background

As part of our test for the upgrade we what a suitable app running on the cluster to performance test with. 

We have decided the multi-container app is suitable for these tests.

## Approach

Deploy the multi-container app to the test cluster

## Definition of done

- [ ] multi-container app deployed and running on the test cluster

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
Done as part of the upgrade testing
