### ISSUE TITLE
Kubernetes 1.13 upgrade - Apply upgrade to test cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1246]
## Approach

Apply the upgrade to the test cluster

## Definition of done

- [x] Test cluster successfully upgraded to 1.13
- [x] Tests complete successfully

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://docs.google.com/document/d/1iQI22PM_gAi2fteHWO_dCgUpKSweL-ag3sT2ZxMW3XY/edit?usp=sharing
