### ISSUE TITLE
Kubernetes 1.13 Upgrade - Write test strategy and identify test tool requirements

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1248]
## Background

As part of the upgrade we need a test strategy.

This story is to come up with a test plan to determine that the upgrade has been successful.

## Approach

Come up with a test plan

## Questions / Assumptions

It is possible that this story many create further stories e.g. installation of tools we might need

## Definition of done

- [x] we have a clear test plan for the upgrade detailing how we will test
- [x] we have agreed success criteria for tests
- [x] we have identified what tools we might need to support the tests

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://docs.google.com/document/d/1iQI22PM_gAi2fteHWO_dCgUpKSweL-ag3sT2ZxMW3XY/edit?usp=sharing
