### ISSUE TITLE
Kubernetes 1.13 upgrade - Check node limits

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1249]
## Background

In support of the upgrade we will be building a "live like" test cluster. This will have 40 nodes.

We are concerned that this might exceed our limit on number of nodes.

## Approach

To ensure we understand any limitation around nodes will will review Kops source code, and/or as Kops if there are any node limits.

## Questions / Assumptions

- Are there any node limits?
- What impact does this have on the upgrade.

## Definition of done

- [ ] We understand if there are any node limits.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Confirmed we have the required space to build another 40 node cluster and some.
