### ISSUE TITLE
List of all services alerting in low level alerts

### ISSUE THREAD

**Issue by jojuolape** [ministryofjustice/cloud-platform#125]
### Background
An audit on #low-priority-alarms  slack channel is required. In the past, alarms have not been triggered into the slack room due to the alarm incorrectly configured in Pagerduty or missing from Pagerduty or CloudWatch. Additionally, some alarms are unnecessary and do not need to be alerted at all.

### Aim
The aim of the ticket is to create a list of services that are alerting in #low-priority-alarms  slack channel

### DOD
- [ ] Create a list of all services alerting in the #low-priority-alarms  slack channel.
- [ ] Share a doc or comments with the team 

Note: Alerts come into the channel via Pagerduty and AWS CloudWatch.

**Comment by ale-novo** [comment]
issue description was improved

**Comment by ale-novo** [comment]
ive listed all the alarms for the low-priority slack channel for the last 30 days. Ive filtered them by name and removed duplicates. this is the list of uniq alarms:

*AlarmName*: ci-prod-monitoring | network-out-high-alarm
*AlarmName*: graphite-staging-monitoring | CPU-high-threshold-alarm
*AlarmName*: graphite-staging-monitoring | network-out-high-alarm
*AlarmName*: peoplefinder-prod-monitoring | network-in-high-alarm
*AlarmName*: peoplefinder-prod-monitoring | network-out-high-alarm
*AlarmName*: pvbpublic-staging-monitoring | elb-500-error-alarm
*AlarmName*: pvbpublic-staging-monitoring | http-500-error-alarm
*AlarmName*: pvbpublic-staging-monitoring | unhealthy-hosts-alarm
*AlarmName*: pvb-staging-monitoring | unhealthy-hosts-alarm
*AlarmName*: sensu-prod-monitoring | CPU-high-threshold-alarm
*AlarmName*: sentry-prod-monitoring | elb-500-error-alarm
*AlarmName*: sentry-prod-monitoring | http-400-error-alarm
*AlarmName*: sentry-staging-monitoring | network-out-high-alarm
*Triggered #62409:* DOWN alert: Judicial Office Blog (judicialoffice.blogs.justice.gov.uk) is DOWN

**Comment by ale-novo** [comment]
a team decision was made to Remove Cloudwatch alerts from low-priority-alarms slack channel

**Comment by ale-novo** [comment]
graphite-staging-monitoring  updated

**Comment by ale-novo** [comment]
pagerduty alerts were reviewed

unsuported apps were removed  from slack low priority channel alerting:

IRAT - Pingdom (Low Priority)

**Comment by ale-novo** [comment]
this is now completed
