### ISSUE TITLE
Create a system for cleaning up 'personal' namespaces

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1252]
It's common for developers to create 'sandbox' namespaces to experiment with.
If people create a namespace, and then leave the organisation, we could end
up with orphaned namespaces in the cluster. This probably isn't a huge
problem, but it is messy, and costs the organisation money (if they use any
AWS resources).

Decide on a system which will ensure that personal namespaces are only kept
as long as they are needed.

One approach could be tagging personal namespaces so that we can identify them,
and then pinging the owners periodically to ask if they still need them (this
would mean only personal namespaces owned by an individual with a valid
organisation email address would be allowed).

The outcome of this ticket should be to decide what process we are going to
use, and then create tickets for whatever tools/changes we need in order to
implement it.

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
