### ISSUE TITLE
Guidance for users about deploying multiple replicas in production namespaces

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1264]
## Background

To mitigate risk of loss of services users should deploy replicas of namespaces. This will mitigate against downtime in the event of loss or recycling of pods

## Proposed user journey

Users know to create replicas of production namespaces and how to do it.

## Approach

Write user guide

## Which part of the user docs does this impact

New section, or is there somewhere in the guide that this should go?

## Definition of done

- [ ] Guidance created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
Is this fulfilled by https://user-guide.cloud-platform.service.justice.gov.uk/documentation/concepts/deploying.html#multiple-replicas ?
