### ISSUE TITLE
Investigate WeaveWorks Flux as our GitOps solution

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1269]
https://www.weave.works/oss/flux/

related to #1158

**Comment by mtrblmoj** [comment]
I have looked into Flux.The main takeaways are : 
- Flux doesn't support multi-repo yet:  we would need a flux daemon running fro each namespace.
- Flux requires a deploy key to the repo it manages
- No easy way of managing secrets

This is not an interesting solution for our usecase
