### ISSUE TITLE
Examine teams' circleci configs, to see what they're doing for CD

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1271]
related to #1158

**Comment by vijay-veeranki-moj** [comment]
Investigated some of repos, also created a poll to get an understanding of what users are doing.
https://mojdt.slack.com/archives/C3F8L6XQU/p1569579887045900

Helm: 
https://github.com/ministryofjustice/laa-apply-for-legal-aid/blob/master/.circleci/config.yml#L215

https://github.com/ministryofjustice/whereabouts-api/blob/master/.circleci/config.yml

Kubectl: 

https://github.com/ministryofjustice/offender-management-allocation-manager/blob/master/.circleci/config.yml

https://github.com/ministryofjustice/money-to-prisoners-cashbook/blob/master/.circleci/config.yml

**Comment by vijay-veeranki-moj** [comment]
Created a poll to get an understanding of what users are doing.
https://mojdt.slack.com/archives/C3F8L6XQU/p1569579887045900

Discussed with ppl who opted other option in the poll

https://mojdt.slack.com/archives/GNH7H8C2W/p1569850360001000
