### ISSUE TITLE
Create a spike of a "hand-rolled" gitops solution

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1272]
This would be a script which runs as a pipeline, following the source code URL
in a namespace annotation and automatically deploying code from a
specially-named folder.

related to #1158

**Comment by vijay-veeranki-moj** [comment]
Worked on a spike using concourse as a gitops solution.

--> Created a concourse pipeline which will iterate though all the environment repo namespaces.
--> Pick up repo url, which is an annotation in Namespace.
--> Use a service account created in a namespace and create a config file of it and upload to s3.

--> The pipeline above Create a Pipeline  for environment/namespace  using fly commands. with url and namespace as variables.

--> Pipeline created for environment will run a script in the user repo( which can be kubecgtl or helm commands),  using the service account config from s3 bucket and apply resources in the cluster.
