### ISSUE TITLE
Ensure our gitops solution does not allow teams to escalate their cluster permissions

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1273]
Our gitops solution will run as a pipeline, and will have permission to deploy
into any namespace. So, there is the potential for someone in a service team to
write a deployment task that has the effect of escalating their permissions in
the cluster.

Investigate approaches which will mitigate this risk.

related to #1158

**Comment by vijay-veeranki-moj** [comment]
Investigated options and can be restricted using one of the options below.

1) For the namespaces we have , create a service account that only has access to that particular namespace, using Kubernetes’s Role-Based Access Control (RBAC) system. We will export the config needed to access that namespace.

https://jeremievallee.com/2018/05/28/kubernetes-rbac-namespace-user.html


2)  Create a cluster level RBAC but with limited permissions .( as we have for concourse)

3) Create a pipeline github team, add this to namespace rbac group in every namespace
or create a rbac at cluster level using this github team. 

4) We need to apply the same for tiller.
https://docs.bitnami.com/kubernetes/how-to/configure-rbac-in-your-kubernetes-cluster/#use-case-2-enable-helm-in-your-cluster

**Comment by vijay-veeranki-moj** [comment]
From the above Option 1 seems more reasonable approach

1) For the namespaces we have , create a service account that only has access to that particular namespace, using Kubernetes’s Role-Based Access Control (RBAC) system. We will export the config needed to access that namespace.

https://jeremievallee.com/2018/05/28/kubernetes-rbac-namespace-user.html
