### ISSUE TITLE
Re-factor the tools image pipeline

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1274]
## Background

The Cloud Platform team use an image called [cloud-platform-tools](https://github.com/ministryofjustice/cloud-platform-tools-image/) that performs various functions required to create/delete/test a Kubernetes cluster. This image has a build, tag and push pipeline in concourse that is currently out of date. 

This ticket requires you to refactor this pipeline to build, tag and push what's in master. We've recently moved to tagging an image so please take this into consideration. We require you to push the image to the ministryofjustice DockerHub account using the `cloudplatformmoj` user. This user account is stored in LastPass.

**Comment by jasonBirchall** [comment]
@digitalronin yours to close.

**Comment by digitalronin** [comment]
closed by https://github.com/ministryofjustice/cloud-platform-concourse/pull/107
