### ISSUE TITLE
Investigate Concourse as our GitOps solution

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#1276]
With the new concourse release, there are options to build the pipelines, to do CD with gitops.

https://medium.com/aptomi/ci-cd-with-concourse-5-2-audit-logs-secret-cache-better-rbac-1575e5cdc4ea

related to #1158

**Comment by poornima-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-gitops-spike/pull/1
