### ISSUE TITLE
Filter out the external services that are relevant / not relevant

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform#128]
his ticket connects to #130

As cloud platform team, we want to know which services are relevant to us, meaning we support them. The goal if this ticket is for us not to be alerted by external services that are not relevant to our work

Definition of done:

- [ ] make a list of  relevant external services from the list of alerts
- [ ] make a list of  irrelevant external services from the list of alerts and remove them

**Comment by lukaszraczylo** [comment]
Heads up - statusgator account has been removed / changed as details stored within password manager don't match. Sending recovery email returns 'no email associated'.
