### ISSUE TITLE
Copy send-money-to-prisoner.service.gov.uk route53 zone to the moj-cp account

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1283]
This is a pre-requisite for migrating the service to the cloud platform, which
is due to happen on 17th October.

The team will be talking to GDS to get them to delegate this domain to our zone
on moj-cp, so this work needs to be done before that happens.

**Comment by digitalronin** [comment]
@vijay-veeranki-moj @ushkarev Is this done now?

**Comment by vijay-veeranki-moj** [comment]
@digitalronin , Yes this is done now.
