### ISSUE TITLE
enable "Anomaly Detection" in AWS

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#1285]
You can now enable machine learning models to detect anomalous behavior of your metrics. Learn more at the documentation page. Your feedback is welcome for the feature in Public Preview.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Anomaly_Detection.html

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
