### ISSUE TITLE
mojdsd IAM account please

### ISSUE THREAD

**Issue by danielatdigital** [ministryofjustice/cloud-platform#1286]
## Service name
AWS mojdsd account

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description
I need an aws account under the mojdsd root so that I can access the Correspondence Tool infrastructure please

## Contact person
Daniel Penny, @daniel

**Comment by pwyborn** [comment]
Mojdsd account created

**Comment by pwyborn** [comment]
paulwyborn 08/10/2019 - 12:32 PM
Daniel - If you could just confirm that you are able to login ok please?

**Comment by danielatdigital** [comment]
Yes, thanks.
