### ISSUE TITLE
Allow users to set their own backup window in RDS module

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1291]
## Background

At the moment, this is set to the default which is 7 days and nightly snapshots. This issue is a placeholder for allowing a user to define this themselves. 

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
