### ISSUE TITLE
check external-dns policy

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#1292]
## Background

Our deployments of external-dns use the parameter `--policy=upsert-only` which doesn’t allow external-dns to delete any records but only create them

## Approach

1. check if `sync ` works with route53
2. ensure external-dns will not decide to wipe any records it doesn't own from the zone (eg cleanup all of service.justice.gov.uk)

## Definition of done

we can reliably cleanup hostnames from any zone

**Comment by AntonyBishop** [comment]
Done
