### ISSUE TITLE
Isolate production services in their own cluster & AWS account

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1294]
This is a placeholder ticket. It needs more discussion and planning
before we can implement it.

Update 2019-10-11
It may not be necessary to do this, after all. So far, both the issues that have affected multiple users have been related to the ingress-controller. It's possible that increasing the restrictions on how users can configure their ingresses may be enough to keep the cluster 'safe' from this type of issue.

For at least 2 reasons, we need to isolate production services:

* The incident with ingress controllers on 09/10/19 shows that a misconfiguration
  in one namespace can (and did) bring down services in another, including
  production services.

* The AWS route53 API (possibly among others) is rate-limited to 5 requests
  per second. It is trivially easy (and has happened several times), to
  deploy a misconfigured ingress into the cluster and cause cert-manager to
  spam the API fast enough to exhaust this limit. This can make it impossible
  to redeploy services, or renew expired SSL certificates.
  NB: This is an *account level* limit which cannot be increased.

These are 2 things that have happened already. It is likely that there are
other scenarios where production services could be affected by issues
outside of their own namespace.

So, I believe we need to have a separate cluster, in a separate AWS account,
reserved for production services. The most straightforward way to do this
seems to be to repurpose live-1 as the production cluster, and move all
non-production stuff to a new cluster in a different account (moj-pi?).

Some areas to think about:

* This is going to make it harder for teams to go live. How do we facilitate
  teams being able to get their services working in the production cluster
  while maintaining the "production only" restriction?

* What are the rules for getting onto the production cluster? Can we restrict
  it so that the only access for teams is via a deployment pipeline?

* As part of this ticket, reverse the "one cluster" architecture decision
  record and add a new one explaining the change: https://github.com/ministryofjustice/cloud-platform/blob/master/architecture-decision-record/012-One-cluster-for-dev-staging-prod.md

**Comment by AntonyBishop** [comment]
We'll time box discussion for this story in Planning

**Comment by AntonyBishop** [comment]
Story closed due to age.

We will revisit as part of multi-cluster work.
