### ISSUE TITLE
Restrict access to live-1 such that everything has to go via a deployment pipeline

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1297]
This is a placeholder ticket for discussion.

Once we have a CD pipeline for service teams to deploy their configs to live-1
we should prevent them from deploying to live-1 in any other way.

This gives us the opportunity to run automated checks and tests against their
configs before they hit live-1, which could prevent some outages.

**Comment by AntonyBishop** [comment]
Closed due to pivot on how we intend to implement GitOps
