### ISSUE TITLE
Apply Validating webhook (admission controller) for ingress-controller.

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#1298]
We had an issue on 09/10 , where a syntax error in ingress file caused the whole ingress-controller go down.

To prevent this Nginx-Ingress provided a fix here.

https://github.com/kubernetes/ingress-nginx/pull/3802

A feature to reject the admission of ingresses that generates invalid configuration using Validating webhook (admission controller) for ingress-controller.

Guidence to create a validation web-hook below.

https://kubernetes.github.io/ingress-nginx/deploy/validating-webhook/

Definition of Done:

Apply and test it in test cluster
Run smoke tests in test cluster
Apply it in live-1

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/commit/006031673385942be2b002d798480def36b9ac4e
