### ISSUE TITLE
Etcd metrics not being exported

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1300]
## Background

Whilst working on another issue I noticed the [etcd](https://grafana.cloud-platform.service.justice.gov.uk/d/81-KsChZk/etcd?orgId=1) dashboard has no datapoints. I then went into Prometheus and attempted to query etcd using `up{job="kube-etcd"}` which returned no data. 

This might not have ever worked in kops due to their implementation of etcd-manager but I'm unsure.

## Proposed user journey

Investigate why there are no exported etcd metrics. Find a way to implement in the Cloud Platform, with a dashboard and relevant triggered alarms.

## Questions / Assumptions

ASSUMING this won't work on any kops created cluster. 

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Please see this link for a potential solution.

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
