### ISSUE TITLE
Find out how many RDS instances in the mojdsd account use SSL

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1301]
NB: Just because the RDS instance doesn't have 'force_ssl' turned on, it
doesn't guarantee that the applications which talk to it aren't using SSL.
So this is just the first bit of information gathering we need to do.

Here is the relevant email from AWS:

> Hello,
>
> Please act before October 31, 2019 to address an upcoming interruption of your applications using RDS and Aurora database instances.
>
> To protect your communications with RDS database instances, a Certificate Authority (CA) generates time-bound certificates that are checked by your database client software to authenticate any RDS database instance(s) before exchanging information. Following industry best practices, AWS renews the CA and creates new certificates on a routine basis to ensure RDS customer connections are properly protected for years to come. The current CA expires on March 5, 2020, requiring updates to existing RDS database instances with certificates referencing the current CA.
>
> You are receiving this message because you have an Amazon RDS database instance(s) in the EU-WEST-1 Region. If your applications connect to those instances using the Secure Sockets Layer (SSL) or Transport Layer Security (TLS) protocol please follow the detailed instructions in the link below to complete your update(s). If not completed, your applications will fail to connect to your DB instances using SSL/TLS after March 5, 2020.
>
> We encourage you to test these steps within a development or staging environment before implementing them in your production environments. Beginning today, you can start testing and updating your existing RDS database instances. For detailed instructions, please visit: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html
>
> Any new RDS instances created after November 1, 2019 will default to using the new certificates. If you wish to temporarily modify new instances manually to use the old (rds-ca-2015) certificates, you can do so using the AWS console or the AWS CLI. Any instances created prior to November 1, 2019 will have the rds-ca-2015 certificates until you update them to the rds-ca-2019 version.
>
> If you have questions or issues, please contact AWS Support at: https://aws.amazon.com/support
>
> Sincerely,
> Amazon Web Services
>
> Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210
>
> ---
> Reference: https://phd.aws.amazon.com/phd/home#/event-log?Event%20ARN=arn:aws:health:eu-west-1::event/RDS/AWS_RDS_SECURITY_NOTIFICATION/AWS_RDS_SECURITY_NOTIFICATION_efb3c046-60a9-4150-a0e7-811f21d82833&eventID=arn:aws:health:eu-west-1::event/RDS/AWS_RDS_SECURITY_NOTIFICATION/AWS_RDS_SECURITY_NOTIFICATION_efb3c046-60a9-4150-a0e7-811f21d82833&eventTab=details&layout=vertical

**Comment by AntonyBishop** [comment]
This story is most likely progressed by asking AWS to identify specific DBs that might be using SSL.

**Comment by vijay-veeranki-moj** [comment]
Received 3 mails related to this for 
--> moj-dsd (ireland)
--> moj-dsd (london)
--> moj-pi (ireland)

Spoke to aws support for dsd account, they confirmed that all rds instances fall under this.

Created a spreadsheet below, with details about the DB Instances. spreadsheet tabs have data for --> moj-dsd (ireland)
--> moj-dsd (london)
--> moj-pi (ireland)

https://docs.google.com/spreadsheets/d/11HAStXxrLlXyCrw1SLebRUFbw6ZBmrWPttfYuEd0XFk/edit?usp=sharing

**Comment by vijay-veeranki-moj** [comment]
Response from aws

Hey Vijay,

Ciarán here from the Security profile in AWS Technical Support. It was a pleasure chatting with you earlier. This is just a quick recap on what we covered.

The notification which you have recieved via e-mail and the PHD, regarding the rotation of a CA certificate in RDS instances in the eu-west-1 region, is applicable to all of your RDS instances within that region. This is because only RDS DBs provisioned after Nov 1st 2019 will contain the new CA certificate.

In order to rotate the certificate, you will need to follow the documentation provided in the notification. I've also linked it here [1], but there is more information regarding the expiration of the CA certificate in the notification itself.

As this issue is not related to the ACM service, I have moved it to the RDS team so that if you have any follow-up queries then a member of the support team there can address them for you. this case has been left in a state where it will auto-resolve in 10 days without update from your end.

I hope that you enjoy the rest of your day.

[1] Rotating Your SSL/TLS Certificate - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html 

Best regards,

Ciaran C.
Amazon Web Services

**Comment by AntonyBishop** [comment]
This looks like a big job? 

Everything is **using** SSL or has the ability to use SSL? 

Is the activity to address this something that teams need to do or do we need to address this across the platform?

Looks like the update requires access to the console which we don't give users access to?

**Comment by AntonyBishop** [comment]
I see there is AWS CLI also.

**Comment by vijay-veeranki-moj** [comment]
Everything is using SSL or has the ability to use SSL?
Ans: Yes Everything is using SSL
Certificate authority
rds-ca-2015


Looks like the update requires access to the console which we don't give users access to?
Ans: 
We can use cli by writing a script.
aws rds modify-db-instance \
    --db-instance-identifier mydbinstance \
    --ca-certificate-identifier rds-ca-2019 \
    --no-apply-immediately

**Comment by AntonyBishop** [comment]
@vijay-veeranki-moj Thanks for confirming. I see you have picked up the follow up ticket.

**Comment by vijay-veeranki-moj** [comment]
Issues:

--> DSD account, not sure about all those rds instance and who own them, we can trace it some of them if they named it properly or used some tags.

--> PI account, can we rotate to new rds-ca-2019 certificates or we need to discuss with teams and get a time to do it?

Important: 
This operation reboots your DB instance. By default, this operation is scheduled to run during your next maintenance window. Alternatively, you can choose to run it immediately.
But choosing Apply immediately option causes an outage.

**Comment by vijay-veeranki-moj** [comment]
aws confirmed as below

It is for all DB instances on all AWS accounts that were created before Nov 1, 2019
