### ISSUE TITLE
Trivy_Container image vulnerability scanner for cloud-platform.

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#1305]
## Background

As a spike, we have looked into vulnerability/Image scanners. As a result we would like to implement Trivy on live-1. #855

Trivy is an open-source is a simple and comprehensive vulnerability scanner for container images. It detects vulnerabilities of OS packages (Alpine, RHEL, CentOS, etc.) and application dependencies (Bundler, Composer, npm, yarn etc.)
Trivy is easy to use. Just install the binary and you're ready to scan. All you need to do for scanning is to specify an image name of container.

## Proposed user journey
N/A

## Approach

Install Trivy: https://github.com/aquasecurity/trivy#installation
Create a new Image or update tools images with Trivy.

Create a pipeline to get the list of images in all namespaces by running below.
kubectl get pods --all-namespaces -o jsonpath="{..image}" |\
tr -s '[[:space:]]' '\n' |\
sort |\
uniq -c

https://github.com/aquasecurity/trivy#continuous-integration-ci
Run the below as part of the pipeline, this is the option in circleci can be run in any pipeline
script:
  - ./trivy --exit-code 0 --severity HIGH --no-progress --auto-refresh trivy-ci-test:${COMMIT}
  - ./trivy --exit-code 1 --severity CRITICAL --no-progress --auto-refresh trivy-ci-test:${COMMIT}

https://github.com/aquasecurity/trivy#usage

Can use the options provided above.
trivy [options] image_name

## Questions / Assumptions

Scanned results, find out -severity CRITICAL and report back to users?

## Definition of done

- [ ] Implement Trivy
- [ ] Get results based on the severity for images under each namespace, and reported in ?
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
There are some conclusions about Trivy here: https://docs.google.com/document/d/1aB0rwj7lYw1pB_f0rZZK8KxXkcgAyBtkmM4Ld2Aqx2U/edit
