### ISSUE TITLE
Sonarqube to scan users projects to get the  code quality.

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#1307]
## Background

As a spike, we have looked into vulnerability/Image scanners. As a result we would like to implement Sonarqube on live-1. [#855 ](https://github.com/ministryofjustice/cloud-platform/issues/855)

SonarQube is an open source platform developed by SonarSource for continuous inspection of code quality to perform automatic reviews with static analysis of code to detect bugs, code smells, and security vulnerabilities on 25+ programming languages. SonarQube offers reports on duplicated code, coding standards, unit tests, code coverage, code complexity, comments, bugs, and security vulnerabilities.

## Proposed user journey
N/A

## Approach

To install SonarQube on to our cluster, this can be done using a stable/hemlchart from SonarQube
Configure SonarQube plugins with the chart.
Provide access to the SonarQube Dashboard
Get users to use the SonarQube Dashboard and to analyze code and inspect results.

Or 

https://aws.amazon.com/marketplace/pp/Bitnami-SonarQube-Container-Solution/B07KCQN3CC
https://docs.bitnami.com/aws/get-started-containers-eks-marketplace/

https://aws.amazon.com/marketplace/pp/B089YVJ1VS?ref_=beagle

we can try this on EKS, than our live-1 cluster

## Which part of the user docs does this impact
user-guide

## Questions / Assumptions

https://community.sonarsource.com/t/sonarqube-failing-on-kubernetes-eks-with-persisten-storage-and-rolling-update-deploymentstrategy/24294/5

This is investigated under the assumption that we can provide sonarqube service for users. Where users use the sonarqube we provided to scan their projects to get the  code quality.

## Definition of done

- [ ] Implement SonarQube
- [ ] Update user-guide for users on how to use SonarQube
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
A requirement for this is to be able to accept reports from other sonarqube (SQ) analyses running elsewhere.

For example, some teams in the LAA plan to incorporate SQ in their build pipelines, and it would be valuable for them to have a centralised instance of the SQ web interface. So, their build jobs would send SQ reports to our SQ instance, which would store the report data in the database and make it available via the normal SQ interface.

So, we should explore the options for accepting such reports, including authentication, and what (if any) partitioning of user groups we can/should do in SQ to give the right people access to their reports (e.g. an approach where everyone in the MoJ can see every report might be adequate, but making it publicly viewable outside of the MoJ isn't advisable).

**Comment by vijay-veeranki** [comment]
created terraform module for sonarqube 
https://github.com/ministryofjustice/cloud-platform-terraform-sonarqube
