### ISSUE TITLE
Quick review of Keeper vs Lastpass

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#131]
## Background

We need a little bit more information on keeper vs. lastpass. The key things to investigate are:

1. How teams are implemented
2. How easy it is for people to get set up, create a team etc
3. How data can be moved across from rattic (is there an API? if not is there an import function)
4. Do each of them meet our security checklist (ask @kalbir for this)

## Definition of done

- [ ] We know how lastpass and keeper perform on each of the 4 points above.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Comparison done here:
https://docs.google.com/document/d/12UGbV-hBf0TdKb0Fm6Oz6uTp8xpwUW0UE6eKOO2kOO4/edit?usp=sharing

Conclusion:
Overall both applications offer the same thing and answer all questions raised positively. There is a bit of a learning curve in regards to the terminology used by LastPass. Keeper is by far the smoother and more intuitive choice but ultimately, both apps do the same thing. 

LastPass has a better reputation but Keeper looks like it'll be cheaper.
