### ISSUE TITLE
Create an admission webhook to prevent bad domain names in ingress controllers

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1317]
If someone tries to deploy e.g. the hello world demo application in a test
cluster, it often causes a problem

https://github.com/ministryofjustice/cloud-platform-helloworld-ruby-app/blob/master/kubectl_deploy/ingress.yaml

The ingress definition has a "live-1" domain name, and cert-manager in the
test cluster will not be able to make the change it wants to make to the
route53 API. This causes it to spam AWS, resulting in our account getting
throttled because we exceed the 5 requests/second limit for our account.

Create an admission webhook that rejects ingresses which define a domain
name which is obviously meant for a different cluster than the curren one.

NB: This doesn't have to catch *every* bad domain, just the most common
case that we've seen in the past.

This will need to be written in go. This article might be useful:

https://blog.container-solutions.com/a-gentle-intro-to-validation-admission-webhooks-in-kubernetes

**Comment by vijay-veeranki-moj** [comment]
OPA Policy
https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/#4-define-a-policy-and-load-it-into-opa-via-kubernetes

**Comment by vijay-veeranki-moj** [comment]
Created a task for this Spike, where we can write an OPA Policy to restrict the hostnames that an ingress can use in test cluster

https://github.com/ministryofjustice/cloud-platform/issues/1743
