### ISSUE TITLE
Fix this cert-manager issue

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1318]
https://github.com/jetstack/cert-manager/issues/2159

This is the cause of route53 API throttling.

There appears to be some code in cert-manager which tries to back off
on API call failure, but I'm pretty sure that isn't working for us.
It may be that we need to configure cert-manager before it will use
it, or it might be that it just doesn't work.

Either way, if cert-manager implemented a kinder exponential backoff
in response to route53 API errors, it would be a good thing.

**Comment by digitalronin** [comment]
Just checked, and this issue is still open.

**Comment by AntonyBishop** [comment]
Issue still not resolved

**Comment by AntonyBishop** [comment]
Looks like this may now be resolved by https://github.com/jetstack/cert-manager/pull/2898

**Comment by AntonyBishop** [comment]
Will be addressed by Cert Manager upgrade.
