### ISSUE TITLE
Correspondence-staff DEMO environment - not enough disk space

### ISSUE THREAD

**Issue by stephenrichards** [ministryofjustice/cloud-platform#132]
## Service name

correespondence-staff

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X] Other   - Demo

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

We have booked a pen test for this week; they are unable to carry it out because of timeouts, and an inability to deploy the latest version of the app to this environmnet

## Problem description

The demo environment is a cluster of two servers.  One of them yesterday was non-responsive; unable to ssh to it, unable to reboot it.  I terminated the instance, and a new instance was created ( i-0d1cc9fe103a41695  / 34.245.8.16 ).  When trying to deply, the deploy failed on this instance due to lack of disk space.  Inverstigation shows that this instance only has 8GB disk, whereas the other has 16GB.  8GB disk is not enough to deploy the app.
--

## Contact person

Stephen Richards  
stephen.richards@digital.justice.gov.uk  
@stephenrichards

**Comment by misaka** [comment]
Also, could we just match the `dev` servers that have 40GB on them please?

**Comment by sablumiah** [comment]
Disk space was upped to 16GB
