### ISSUE TITLE
Alter the namespace creation process so teams get alerted about errors in their namespace

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1330]
During the namespace creation process, add a question "Which slack channel should receive error alerts for this namespace?"
and set up a prometheus rule etc. to send messages to that channel in response
errors in the namespace (e.g. pod crash-looping, failing to launch, etc.)

**Comment by davidread** [comment]
We are some way there:
* Tenants do provide their team slack channel in their namespace config.
* We have a severity level mapper.
Remaining to do:
* Need to link prometheus linked, creating alarms automatically
* They need to be able to configure / mute them.

**Comment by AntonyBishop** [comment]
Closed to to age of story.
