### ISSUE TITLE
Research Sealed-Secrets and an alternative to Git-Crypt

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1335]
GDS use Sealed-Secrets. Investigate if this would work for us.

It would be worth having a conversation with GDS about this as part of this story.

**Comment by vijay-veeranki-moj** [comment]
https://docs.google.com/document/d/1swqooT70VRNwIEfSdz84-8KhWn_crIruTKoM-2gvB7Y/edit#

**Comment by vijay-veeranki-moj** [comment]
Findings in the document,

https://docs.google.com/document/d/1swqooT70VRNwIEfSdz84-8KhWn_crIruTKoM-2gvB7Y/edit#

Gave a Demo on this topic
