### ISSUE TITLE
Set up a process to  run recycle-node.rb periodically which recycle oldest worker node.

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#1336]
Background: 
As part of (https://github.com/ministryofjustice/cloud-platform/issues/1153), we want to automate the process of gracefully replacing  oldest worker node, periodically.

Before this set to run periodically in live-1, Team want to run this process manually in live-1 and get a customer view as this will drain pods in the oldest node.

When team finishes running this manually multiple times and confident that it can be run as a job periodically.

Create a cronjob or pipeline to run periodically  and execute  recycle-node.rb in 
https://github.com/ministryofjustice/cloud-platform-infrastructure

Proposed user journey:
The recycle-node.rb script needs, aws iam role which have permission to terminate an instance and need to create a  new service account with rbac which can perform `kubectl drain node`

It can run in circle-ci, make sure we give limited permissions and discuss with the team.
Create a Cron job or a pipeline.
There is an issue running this on the same cluster as it may drain the pod running this job.

Look at the below options to run it as a cron job or in concourse pipeline.
Gracefully shutting down Pods
Delaying Shutdown to Wait for Pod Deletion Propagation
Avoiding outages with PodDisruptionBudgets
 
Approach:
N/A

Questions / Assumptions:
 If it runs as a cronjob or concourse pipeline, how to run this without a failure?
Where to run this job.
 
Definition of done:
 Comms: Tell users before we start doing this for real
 another team member has reviewed
 smoke tests are green

Reference:
How to write good user stories

**Comment by digitalronin** [comment]
We can't start doing this until we run prometheus as a high-availability service. Right now, if we delete the node that our single instance of prometheus is on, we'll lose all the service monitors until either the pipeline or the service teams put them back.

We need to fix this before we can start deleting nodes. We also need to find any other components which we're not running in a highly-available way, and fix them (since that's what we're telling teams to do).

**Comment by digitalronin** [comment]
The prometheus issue was a red herring. As long as we're only moving pods around, not deleting the prometheus installation, service monitors are not affected.

**Comment by digitalronin** [comment]
closed by https://github.com/ministryofjustice/cloud-platform-concourse/pull/143
