### ISSUE TITLE
CLA service certificates

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#1337]
## Service name

Certificates

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [x] Other

## Impact on the service

Unable to train new operators as a result of this issue. Currently affecting ~15 users receiving training

## Problem description

Recently the certificates for some of our services have expired. We have raised the issue with cloud platform on slack but some services are still showing invalid certificates.  Below is a list of service domains, the unchecked ones have an invalid certificate:

- [x] https://staging-backend.cla.dsd.io
- [x] https://training-backend.cla.dsd.io
- [x] https://fox.civillegaladvice.service.gov.uk
- [ ] https://staging-frontend.cla.dsd.io
- [ ] https://training-frontend.cla.dsd.io
- [x] https://cases.civillegaladvice.service.gov.uk
- [x] https://staging.laalaa.dsd.io/
- [x] https://prod.laalaa.dsd.io/

## Contact person

[at]Said
[hash]laa-cla-fala

**Comment by razvan-moj** [comment]
fixed
