### ISSUE TITLE
Tidy deletion of namespace

### ISSUE THREAD

**Issue by asmega** [ministryofjustice/cloud-platform#1340]
## Service name

Form Builder

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

n/a

## Problem description

Please see:
https://github.com/ministryofjustice/cloud-platform-environments/pull/1443

This is a follow up task due to the deletion of the namespace `formbuilder-publisher-integration` in live-1 cluster

## Contact person

Phil Lee (me)

**Comment by digitalronin** [comment]
Thanks, @asmega I've deleted the namespace.
