### ISSUE TITLE
Tidy deletion of 3 namespaces

### ISSUE THREAD

**Issue by asmega** [ministryofjustice/cloud-platform#1341]
## Service name

Form Builder

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

n/a

## Problem description

Please see:
https://github.com/ministryofjustice/cloud-platform-environments/pull/1444

This is a follow up task due to the deletion of the namespaces in the live-1 cluster:
- `formbuilder-services-integration-dev`
- `formbuilder-services-integration-staging`
- `formbuilder-services-integration-production`

## Contact person

Phil Lee (me)

**Comment by digitalronin** [comment]
I've deleted these namespaces.
