### ISSUE TITLE
Improve the namespace deletion process, for users

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1345]
Currently, the process for removing a namespace works like this:

* User raises a PR, removing everything except the `main.tf` file
* Pipeline removes all AWS resources for the namespace (this often fails because of module changes, and we have to manually tidy up)
* User raises a second PR, removing the `main.tf` file and the namespace folder
* User raises a ticket, reminding us to manually delete the namespace (or the weekly 'namespaces with no source code' message in Slack reminds us)

This isn't great. It pushes a lot of responsibility and awkwardness onto
the user.

We have this script, which will delete a namespace and all its AWS resources
in one go:
https://github.com/ministryofjustice/cloud-platform-environments-checker/blob/master/bin/delete-namespace.rb

(It may need a bit of work, and it may still break if the module version
problem applies)

How about changing the namespace deletion process to work like this:

* User creates a github issue from a template (cf. the support template - this would be a special case of a support ticket)
* The cloud platform team member who picks up the ticket does the following:
  * Raise a PR to remove all the namespace files
  * Wait for the pipeline to run (so that it doesn't replace the namespace, after deletion)
  * Runs the namespace deletion script to remove the AWS resources and the namespace itself (the CP team member will have to fix anything that breaks, just as we do now).

This would make things much easier for the user, and we could automate this
gradually, to make it easier for us, too.

**Comment by AntonyBishop** [comment]
Done
