### ISSUE TITLE
Tidy deletion of another 3 namespaces

### ISSUE THREAD

**Issue by asmega** [ministryofjustice/cloud-platform#1346]
## Service name

Form Builder

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

n/a

## Problem description

Please see:
https://github.com/ministryofjustice/cloud-platform-environments/pull/1448

This is a follow up task due to the deletion of the namespaces in the live-1 cluster:
- `formbuilder-platform-integration-dev`
- `formbuilder-platform-integration-staging`
- `formbuilder-platform-integration-production`

## Contact person

Phil Lee (me)

**Comment by vijay-veeranki-moj** [comment]
Delete namespaces in live-1

formbuilder-platform-integration-dev
formbuilder-platform-integration-staging
formbuilder-platform-integration-production
