### ISSUE TITLE
logstash value nginx-ingress.upstream_response_time stored as string should be number

### ISSUE THREAD

**Issue by feedmypixel** [ministryofjustice/cloud-platform#1352]
## Service name
Book a secure move

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [x] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

We need to see `response_time` on various `url` across the service to see bottlenecks. I have created a dashboard in Kibana to view these things. `Hmpps book secure move frontend - Response Time`

## Problem description

We are wanting to identify `response_time` bottlenecks in the application. To do this I have created a dashboard. I would like to create a bar chart with the `url` on the `x-axis` and `nginx-ingress.upstream_response_time` on the `y-axis`.
Currently the `nginx-ingress.upstream_response_time` is stored as a string in logstash.
![Screenshot 2019-10-30 at 10 13 13](https://user-images.githubusercontent.com/2305016/67849134-e8bed080-fafd-11e9-9f67-fc40203b95c4.png)
I need this to be stored as a number so I can have graphs with `average`, `max`, `min` on.

## Contact person

Ben Chidgey (find me on MoJ slack) or drop me an email on MoJ email

**Comment by razvan-moj** [comment]
fixed by https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/446
