### ISSUE TITLE
Fix cert-manager on live-0

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#1353]
We have an (expected) e-mail from Letsencrypt stating "we plan to start
blocking all traffic from cert-manager versions less than 0.8.0 (the
current semver minor release), as of November 1, 2019. Please upgrade
all of your cert-manager instances before then.

We're sending this email because this is the contact address of your
cert-manager instance at:

 52.17.133.167 ."

^ which is live-0

**Comment by digitalronin** [comment]
Unless this is a trivial fix, I think we shouldn't bother with it.

We want to decommission live-0 ASAP, so any time we spend fixing it is wasted.

**Comment by pwyborn** [comment]
![Screen Shot 2019-11-04 at 14.25.19.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/16f467c5-302a-42b4-869b-e4af6ded94c4)
![Screen Shot 2019-11-04 at 14.25.47.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/e438b3df-99a3-4dfa-871b-f378f0953791)
![Screen Shot 2019-11-04 at 14.26.13.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/2105cb9a-7fb7-4791-a194-83caf0cb1b34)
![Screen Shot 2019-11-04 at 14.26.40.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/d2ae262d-1f0e-447c-8e2b-5abaca0c006c)
![Screen Shot 2019-11-04 at 14.26.59.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/80683827-4f8c-40a3-8647-121cdfb172ee)

Started looking at this. In view of above comments and hearing that with past experience certs may be deleted when an upgrade made - have decided to put this on the back burner:
