### ISSUE TITLE
Need to add my ssh keys to peoplefinder

### ISSUE THREAD

**Issue by danielatdigital** [ministryofjustice/cloud-platform#1356]
## Service name
Peoplefinder

## Service environment

- [ x] Dev / Development
- [ x] Staging
- [ x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description
Need access as team now supports peoplefinder
https://github.com/ministryofjustice/pf-deploy

## Contact person
Daniel Penny, @daniel

**Comment by pwyborn** [comment]
04/11/2019 - Hi Daniel re ticket
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/1356
- are you able to ssh onto the peoplefinder envs now please? (edited) 
https://github.com/ministryofjustice/pf-deploy/pull/113
refers
04/11/2019 - Daniel 11:06 AM
Thanks Paul, that's fine
