### ISSUE TITLE
User communications for Terraform upgrade

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1360]
## Background

As part of the Terraform upgrade work we have some important messages that we want users to take action on. We'll issue a message via #cloud-platform-update which will include the following:

- Don't use any Terraform 12 resources we create until we give the ok 
- "Freeze" on module updates
- Upgrade to latest version of the modules

## Proposed user journey

User understand what we are working on and know what they need to do prior to release of changes that impact them.

## Definition of done

- [ ] comms issued

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
https://mojdt.slack.com/archives/CH6D099DF/p1573041258005100

**Comment by vijay-veeranki-moj** [comment]
comms sent out:

We are working on Terraform version upgrade to (Terraform v0.12.13) from (Terraform v0.11.14) ,for all the modules [https://github.com/ministryofjustice/cloud-platform#terraform-modules].
Although this looks like a minor release, it's actually a significant change[https://www.terraform.io/upgrade-guides/0-12.html].

As part of the Terraform upgrade work we are planning to follow this process, and we have some important messages that we want users to take action on.
We will update you if any change in this plan.

Pre-requisites:

-> Pin all main.tf in environments repo with terraform version to 0.11.14 (cloud-platform team will perform this action)
    [https://www.terraform.io/docs/configuration/terraform.html#specifying-a-required-terraform-version]
-> Request users to update all their modules to use the latest module version (users perform this action with support from cloud-platform team)
-> "Freeze" on module updates (no updates to the existing modules)

Upgrade-step:

-> Upgrade all the modules to use Terraform v0.12.13 and pin it to upgraded version (cloud-platform team will perform this action)
-> users should not use any new modules that they might find until we give the OK.
-> Test existing modules upgrading to terraform v0.12.13 created module have no effect (cloud-platform team will perform this action)

After Upgrade-step:

-> Update all the modules to use the latest module created using Terraform v0.12.13 and change the pinned version to the new terraform version in environments repo(cloud-platform team will perform this action)
