### ISSUE TITLE
Pin Providers everywhere

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1362]
Prior to the TF upgrade we want to pin latest Providers

**Comment by vijay-veeranki-moj** [comment]
The way pin provider versions work differently in tf v.0.11 and v.012.

In tf v0.11 should be added in provider block 
https://www.terraform.io/docs/configuration-0-11/providers.html#provider-versions
```
provider "aws" {
  version = "~> 1.0"
}
```
In tf v0.12 it is changed to add providers as required_providers as shown below
```
terraform {
  required_providers {
    aws = "~> 1.0"
  }
}
```
https://www.terraform.io/docs/configuration/providers.html#provider-versions

**Comment by vijay-veeranki-moj** [comment]
Closed this ticket as we are working on updating all our tf code to upgrade to tfv0.12.

So add this pinning providers in terraform upgrade tickets
