### ISSUE TITLE
Compare previous TF 0.12 spike upgrade investigations with latest TF version change log

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1364]
## Background

We spiked the upgrade in an earlier sprint. We want to check that there have been no further breaking changes introduced since the last assessment.

## Questions / Assumptions

- Are there any new breaking changes that we need to investigate?

## Definition of done

- [ ] comparison completed
- [ ] confirm no further issues to address or plan to investigate any changes

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/285
Link to the spike PR
