### ISSUE TITLE
Terraform 0.12 Release for ECR credentials module

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1371]
Also Pin Providers while doing this upgrade

**Comment by mtrblmoj** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials/pull/23

**Comment by mtrblmoj** [comment]
Blocked by the circleci formatter that is not compatible with terraform 12

https://circleci.com/gh/ministryofjustice/cloud-platform-terraform-ecr-credentials/73?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
