### ISSUE TITLE
Terraform 0.12 check point

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1378]
We've created all the modules and have upgrade all the Terraform for Infrastructure.

How and when do we release changes to users?

**Comment by vijay-veeranki-moj** [comment]
Out come of the discussion

-> Test existing modules upgrading to terraform v0.12.13 created module have no effect (cloud-platform team will perform this action)

After the Pre-requisites and Upgrade-step completed. Perform below in dev namespaces first and when they are applied successfully, apply it to production namespaces

-> Update all module examples and readme to have latest tf 12 version.

-> Update all the modules to use the latest module created using Terraform v0.12.13 and change the pinned version to the new terraform version in environments repo.

-> Perform tf 0.12upgrade for all the modules used and also pingdom and route-53 terraform resource.

-> Make sure they are applied successfully, though the pipeline process created by David which handles both tf0.11 and tf0.12.
