### ISSUE TITLE
Custom properties and values parsed to be available in Kibana

### ISSUE THREAD

**Issue by feedmypixel** [ministryofjustice/cloud-platform#1380]
## Service name
Book a secure move frontend

## Service environment
- [x] Staging
- [x] Prod / Production

## Problem description
We would like to see response time on our `Kibana` dashboard [Hmpps book secure move frontend - Response Time](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/be23fdbd4cd2e03096cea98882e2bab3) -  grouped by Location Type:
- police custody suite 
- prison

We can provide this property via logs for each request. However, custom properties and values cannot be currently parsed and provided to `Kibana`

## Task
Allow custom properties to be parsed and made available to `Kibana`.

## Contact person
Ben Chidgey in MoJ Slack

**Comment by razvan-moj** [comment]
solution we used for the shared Ingress proxies: https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/cc9e41b470711708815aa70e547227a64d48e9c9/terraform/cloud-platform-components/nginx-ingress-acme.tf#L51

**Comment by feedmypixel** [comment]
@razvan-moj @pwyborn is there any news on this work? Thanks 🙏

**Comment by razvan-moj** [comment]
hi - not yet but not forgotten, will update after a planning session tomorrow

**Comment by pwyborn** [comment]
As discussed at team review/planning 15/11/2019. To be part of a wider discussion/review regarding collection of log info to fluentd

**Comment by jason-sims** [comment]
Hi @pwyborn - Can you please confirm you are not going to address this issue anytime soon. There are impacts to the team around not being able to address performance issues which is why we raised this. Can you please provide some idea when the wider discussion is occurring?

**Comment by AntonyBishop** [comment]
This issue remains open. Needs to be addressed as part of the wider EPIC looking at re-architecting the logging solution.
