### ISSUE TITLE
[EPIC] Monitoring key cluster metrics

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#139]
## Background

As we add live services to the cluster we need to know to take actions on key events. The initial things we want to have alerts on are:

- the amount of memory/cpu available on the cluster overall running out
- any nodes dead for a period of time
- any masters being up or down
- node disk space

We need to be able to: 

- measure that metric, 
- alert when it is nearing capacity and 
- have a process for adding more resources when we are near capacity

## Proposed user journey

- Cloud platform team member gets alert that cluster is at e.g. 80% capacity for CPU and Memory in slack and pagerduty
- Team member goes to a run book that explains how to provision a new node (could be a readme for a repo)
- Team member provisions a new node
- Alert stops firing as the new node comes into service and overall capacity increases

## Questions / Assumptions

- We will use prometheus for monitoring
- We will use existing pagerduty and slack mechanisms as where we find out about alerts
- We will complete all of this work on a `test-0` cluster, when it is signed off we will deploy it to the `live-0` cluster
- Autoscaling is not in scope of this story -- we will complete a "manual" process to remediate these issues (where that might be a script, a concourse job, or similar). 

## Definition of done

- [ ] 
- [ ] 
- [ ]

**Comment by kerin** [comment]
@kalbir node disk space? That’s the thing most likely to bite you in my experience

**Comment by kalbir** [comment]
@kerin good point -- added in the description

**Comment by sid234** [comment]
@kalbir also could we check for Network In/Out/Errors
