### ISSUE TITLE
Allow s3 bucket with public-read policy

### ISSUE THREAD

**Issue by exonian** [ministryofjustice/cloud-platform#1396]
related to #1506

## Service name
LAA Find a Legal Advisor

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Our migration of the live FALA service from live-0 to live-1 is being delayed by static file issues

## Problem description

As part of our move from live-0 to live-1, we are switching from serving static files from an nginx container to uploading them to s3
We've set up `django-storages` to use s3 as its backend, which has made file syncing straightforward and properly handles files referenced in html templates, including the `get` params needed for public access to files in a private bucket.
However, our css pipeline (sass precompile, uglification) in gulp is not aware of the storage and so just refers to the resources by filename without the get params, resulting in a `403 Forbidden`.

I attempted to quickly hook up `django-compressor` to get past this, but ran into conflicts with the 3rd-party package we're using to handle `jinja2` templates, so at that point figured a public bucket might make most sense for now (given that none of the assets are sensitive). 

## Contact person

Michael Blatherwick
michael.blatherwick@digitial.justice.gov.uk
#laa-cla-fala slack channel

**Comment by vijay-veeranki-moj** [comment]
Hi @exonian,

Can you let me know the bucket name you want to have public access to?

**Comment by vijay-veeranki-moj** [comment]
Spoke to Michael Blatherwick,

He Informed that he have a workaround for it now.

We need to work on a solution for this.

@AntonyBishop this needs a triage, can we get this in to planning?

**Comment by sldblog** [comment]
Thank you for picking this up!

I'm unaware of the underlying conversations; apologies if the below thoughts have been mentioned already :bowing_man: 

Our applications are public on GitHub, and we intend to use the created S3 buckets as asset (image, CSS, javascript) storage.

For this use-case, a "public-read" ACL sounds sensible. My understanding is that this setting is periodically overridden to "private" to avoid accidental exposure.

However, as a tenant on Cloud Platform, we provision our S3 buckets via Terraform resources, where the ACL defaults to "private".

:thought_balloon: It seems the platform could have controls in place to avoid creating publicly writeable buckets, which would remove the need to override ACL externally within the platform's scope. What do you think?

**Comment by AntonyBishop** [comment]
Relates to #1425 created in backlog

**Comment by AntonyBishop** [comment]
Also related to #1506

**Comment by AntonyBishop** [comment]
This ticket is blocked until we address #1425 and #1506

**Comment by AntonyBishop** [comment]
https://mojdt.slack.com/archives/C514ETYJX/p1594631283029400
