### ISSUE TITLE
Sanitise tag values we set via our terraform modules

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1398]
In some of our terraform modules (dynamodb, at least), we use some of the
values the user supplies as tags, e.g.

https://github.com/ministryofjustice/cloud-platform-terraform-dynamodb-cluster/blob/f1142666f548f2abf4167704c02020a12adb56e7/main.tf#L48

But, AWS doesn't like some characters in tags, particularly < and > which will
often be there, e.g.

"Probation in Court Team" <probation-in-court-team@digital.justice.gov.uk>"

Is there anything we can do in terraform to sanitise strings before we try and
send them to AWS as tag values?

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
