### ISSUE TITLE
Decide how to cycle nodes with manually-created pods

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1403]
We have told users we will regularly replace worker nodes in the cluster.

When we tried to do this just now, there was an error:

```
error: cannot delete Pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet (use --force to override): cccd-api-sandbox/cccd-template-deploy-migrator, check-my-diary-dev/port-forward-pod2, offender-categorisation-prod/port-forward-pod
```

The relevant pods were created manually, using `kubectl create ...` or `kubectl
run ...` and the cluster won't evict them unless we force it to.

On the one hand, forcibly killing those pods (since they won't be rescheduled
elsewhere) will encourage users to create pods via deployments, which is much
more robust.

Any node could die at any time, and getting teams used to this is a large part
of why we want to deliberately replace worker nodes in the first place.

On the other hand, these pods seem to be part of users' migration tasks, and we
don't want to make users' lives harder unnecessarily.

I would suggest we put out some comms, including the names of the pods in the
error message, warning teams not to depend on ephemeral pods which don't have
proper configuration in the cluster, and then next time we try to replace a
node, use `--force` to override the command, which will kill the relevant pods.

**Comment by vijay-veeranki-moj** [comment]
These pods are created for port-fwd to access RDS

**Comment by digitalronin** [comment]
That makes sense. I guess we need to add some guidance in the documentation to tell people that they need to create deployments for those pods, unless they're happy for them to disappear.
