### ISSUE TITLE
Upgrade RDS cert

### ISSUE THREAD

**Issue by asmega** [ministryofjustice/cloud-platform#1404]
## Service name

Form Builder 

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

n/a

## Problem description

Change RDS certificate to 2019 cert to test compatibility. The RDS instance is in the namespace `formbuilder-platform-test-dev` and the secret is in `rds-instance-formbuilder-user-datastore-test-dev`

The application code should be compatible with either version of the certs. This is to test if this is the case

Feel free to reboot and apply changes immediately

## Contact person

Phil Lee (me)

**Comment by vijay-veeranki-moj** [comment]
Updated rds instance to use Certificate authority: rds-ca-2019
