### ISSUE TITLE
Enable `TTLAfterFinished` gated feature

### ISSUE THREAD

**Issue by exonian** [ministryofjustice/cloud-platform#1405]
## Service name

FALA
We would also probably use it on all our other services, either going back to add it (laa-legal-adviser-api) or doing it as we migrate them from TD (cla_backend, cla_frontend) or live-0 (cla_public).

## Test this:

* Create a test cluster with the flag enabled
* Run the integration tests
* Test that jobs are deleted X minutes after they complete (add an integration test for this)

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Our cronjobs will accumulate completed jobs, and using the built-in k8s feature seems preferable to reinventing a way of pruning them.
Our deploy pipeline handles the deletion of the one-off jobs it runs, which is a slightly brittle implementation I'd also feel more comfortable removing.

## Problem description
Kubernetes 1.12 introduced `TTLAfterFinished` as a gated feature to manage the clear up of completed jobs https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
It's opt-in, through a key in the jobTemplate spec, so I wouldn't expect it to affect anybody unless they chose to engage with it.

## Contact person
Michael Blatherwick
CLA / FALA team
#laa-cla-fala on slack

**Comment by vijay-veeranki-moj** [comment]
This needs a Kops change and testing.

@AntonyBishop can we discuss this in the planning?

**Comment by jasonBirchall** [comment]
https://github.com/kubernetes/kops/issues/8267

**Comment by jasonBirchall** [comment]
```
spec:
  kubeControllerManager:
    featureGates:
      TTLAfterFinished: "true"
  kubeAPIServer:
    featureGates:
      TTLAfterFinished: "true"
```

**Comment by jasonBirchall** [comment]
Related to https://github.com/ministryofjustice/cloud-platform/issues/1593

**Comment by jasonBirchall** [comment]
Feature flags added in https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform-infrastructure/604
