### ISSUE TITLE
RDS CA Replacement - C100 - Staging

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1409]
This is a ticket for the RDS CA replacement for C100 (aka Apply to court about child arrangements) staging.

RDS instance: `cloud-platform-e9ec53894cc75435`

Environment Type: Staging

Forced Reboot?: Yes

Contact: @jesus. Contact him just prior to the change to let him know we are making that change.

**Comment by vijay-veeranki-moj** [comment]
Done updating it to `Certificate authority rds-ca-2019` and did a immediate reboot for it to apply.

**Comment by vijay-veeranki-moj** [comment]
Also update other two 

cloud-platform-ead3b759b8d813ac

cloud-platform-8454c1c0c274f47b

**Comment by vijay-veeranki-moj** [comment]
Also did for production, selecting option to reboot on next maintenance window.

cloud-platform-4aa269ce58b28e38
cloud-platform-c4dfb1807cccaa13
cloud-platform-dcaadb3ab42fb8f9
