### ISSUE TITLE
Feedback pipeline result to PR

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1411]
From a PR in the environment repository, there is no way of knowing if the pipeline has successfully applied the changed.  

It would be useful for concourse to feedback the build result to the PR.

Ideally, the flow would be : 

- A PR is merged & closed
- The apply pipeline runs
- if the pipeline fails, the PR is reopened
- the error message is posted in the PR as a comment

**Comment by AntonyBishop** [comment]
Would result in too many alerts.
