### ISSUE TITLE
RDS CA Replacements - DPS Team - All Development Environments

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1412]
This is a ticket for the RDS CA replacement for all the DPS Development enviornments

RDS instance(s):
cloud-platform-35989daa539e8351
cloud-platform-60b53562549eb2d2
cloud-platform-9715beccbb718d4b
cloud-platform-a75ed0cca96e6c72
cloud-platform-d8898a26211073bc
cloud-platform-307a469dea55139c
cloud-platform-58ca03d8cef2cd18
cloud-platform-aedbbe66e64b8443
cloud-platform-f4a54f395e1e5633

Environment Type: Dev

Forced Reboot?: Yes

Contact: @Peter Phillips in the #dps_tech_team channel. Contact him just prior to the change to let him know we are making that change.

**Comment by AntonyBishop** [comment]
This is a ticket for the RDS CA replacement for all the DPS Development enviornments

RDS instance(s): 
cloud-platform-35989daa539e8351
cloud-platform-60b53562549eb2d2
cloud-platform-9715beccbb718d4b
cloud-platform-a75ed0cca96e6c72
cloud-platform-d8898a26211073bc
cloud-platform-307a469dea55139c
cloud-platform-58ca03d8cef2cd18
cloud-platform-aedbbe66e64b8443
cloud-platform-f4a54f395e1e5633

Environment Type: Dev

Forced Reboot?: Yes

Contact: @Peter Phillips in the #dps_tech_team channel. Contact him just prior to the change to let him know we are making that change.

**Comment by vijay-veeranki-moj** [comment]
Updated Certificate authority to and applied immediately.
rds-ca-2019

**Comment by vijay-veeranki-moj** [comment]
Also updated the pre-prods, list below

cloud-platform-09feaed978653e19
cloud-platform-181a70806e1a85f5
cloud-platform-453f7148d27e7cd1
cloud-platform-49f2de1fed495464
cloud-platform-f01b050f0c0f82cb
cloud-platform-5c6377808488916a
cloud-platform-99060a47db567fc2
cloud-platform-ed3344ec7b21f599
cloud-platform-a99b40969f754f4c

**Comment by vijay-veeranki-moj** [comment]
Updated prod list as well and selected reboot for next maintenance window

cloud-platform-5dbdcc77ff9d954a
cloud-platform-7da276da34a30306
cloud-platform-a450784ed2b32c2e
cloud-platform-f571ef4833323931
cloud-platform-fa888e83362e61b1
cloud-platform-67257a8b15c64e7f
cloud-platform-1fb65a0439ba05e6
cloud-platform-b6244d8c893e1d12

**Comment by vijay-veeranki-moj** [comment]
Note:  that in terms of prod and staging users are not intending to do  below instances

cloud-platform-3be904e3e369a543
cloud-platform-cc9f17a39db1119f

since they are retiring the nomis-api-access service at the end of this year
