### ISSUE TITLE
A place to help with "who owns this service [URL]"

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#1413]
## Service name

All services.

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Not applicable.

## Problem description

We have a goal in the Legal Aid Agency:

> When a team is made responsible for a system,
> **everyone** in LAA digital should know and be able to find out

We started to resolve this by tagging GitHub repositories with topics, for example ["laa-get-access"](https://github.com/search?q=topic:laa-get-access+org:ministryofjustice).

However, [this thread in Slack](https://mojdt.slack.com/archives/C54PFB3NY/p1573490081069000) made me think it would be better if we could arrive at an owner team from a URL.

As the Cloud Platform
- has an authorisation model that works with GitHub teams
- allows teams to create namespaces
- allows namespaces to define an ingress with hostnames

It looks like the platform could expose hostname ownership information on demand. 🙌 

What do you think about making this ownership information publicly available?

Maybe something like this?

| URL | Namespace | Team | Repository |
| --- | --- | --- | --- |
| https://laa-legal-adviser-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk/ | [laa-legal-adviser-api-staging](https://github.com/ministryofjustice/cloud-platform-environments/tree/6eb26eec8cebf76934a6616c4801c2cc5445a853/namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-staging) | :family_man_woman_girl_boy: [laa-get-access](https://github.com/orgs/ministryofjustice/teams/laa-get-access/members) | :octocat: [laa-legal-adviser-api](https://github.com/ministryofjustice/laa-legal-adviser-api) |
| https://laa-legal-adviser-api-production.cloud-platform.service.justice.gov.uk/ | [laa-legal-adviser-api-production](https://github.com/ministryofjustice/cloud-platform-environments/tree/6eb26eec8cebf76934a6616c4801c2cc5445a853/namespaces/live-1.cloud-platform.service.justice.gov.uk/laa-legal-adviser-api-production) | :family_man_woman_girl_boy: [laa-get-access](https://github.com/orgs/ministryofjustice/teams/laa-get-access/members) | :octocat: [laa-legal-adviser-api](https://github.com/ministryofjustice/laa-legal-adviser-api) |

Or maybe as an [interactive graph](https://neo4j.com/blog/uncommon-use-cases-graph-databases/)?

![image](https://user-images.githubusercontent.com/1526295/68668126-65f73600-053f-11ea-88b7-05828b98edab.png)

## Contact person

@sldblog, [#laa-architects](https://mojdt.slack.com/archives/C5HV1FU4R) Slack channel

**Comment by sldblog** [comment]
I would favour the graph approach as it would allow us to attach more data to ownership. For example, linking to runbooks, etc.

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
