### ISSUE TITLE
RDS CA Replacement - Money to Prisoners - Test

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1418]
This is a ticket for the RDS CA replacement for MTP Test.

RDS instance: cloud-platform-6b9509a9d1edc330

Environment Type: Test

Forced Reboot?: Yes

Contact: @igor.ushkarev Contact him just prior to the change to let him know we are making that change.

**Comment by vijay-veeranki-moj** [comment]
Done cloud-platform-6b9509a9d1edc330 

Certificate authority
rds-ca-2019
Certificate authority date
Aug 22nd, 2024
