### ISSUE TITLE
Set up a test pagerduty team

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#142]
## Background

Part of Epic #139 - Monitor key cluster metrics

We need to have a test pagerduty team that we can send our test alerts to and check that the end to end alerting flow works. We don't want to do this with a live team as it may result in e.g. on call people being alerting out of hours. 

## Definition of done

- [x] There is a test team in our pagerduty 
- [x] It is clearly named so that it is recognised as a test team
- [x] It can alert a test person/number/email so we can check that the end to end testing flow works

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ollieanwyll** [comment]
ollie-test-group

**Comment by ollieanwyll** [comment]
Test Team ollie-test-team has been created with, myself Jason and Sablu added as users.

**Comment by sablumiah** [comment]
Team channel name changes to prometheus-test-service
Prometheus integration enabled and slack extension to cp-prometheus-test
