### ISSUE TITLE
Record the list of public S3 buckets in the lambda function repo.

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1425]
There is a lambda function created by security team using cloud-formation script, which will revoke the public access for s3 Buckets. which runs on a weekly schedule.

But there is an option to add an exception to it. 

Readme show how to run the lambda function.

https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/master/cloudformation/aws-account-baseline-templates/aws-s3-enable-encryption-block-public-access

Running this cloud-formation script with s3 bucket to be exempted to block public access`S3_EXCEPTION` parameter will add an exception list in the lambda function(which runs in a schedule every wednesday)

```aws cloudformation deploy --template-file aws-s3-enable-encryption-and-block-public-access-output.yaml --stack-name aws-s3-enable-encryption-and-block-public-access --parameter-overrides pCreateSnsTopic=false pExistingSnsTopic=$EXISTING_SNS_TOPIC_ARN pS3PublicAccessBlockPermissions=true pS3BucketsToSkipPublicAccessBlock=$S3_BUCKETS_TO_SKIP_PUBLIC_ACCESS_BLOCK pS3BucketEncryption=true pS3BucketsToSkipEncryption=$S3_BUCKETS_TO_SKIP_ENCRYPTION  --tags Owner=$ACCOUNT_EMAIL AgencyName=$AGENCY_NAME ApplicationID=aws-s3 Environment=Production --capabilities CAPABILITY_NAMED_IAM --profile $AWS_PROFILE```

https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/cloudformation/aws-account-baseline-templates/aws-s3-enable-encryption-block-public-access/lambda/s3-bucket-block-public-access.py#L20

When it is successfully run, verify the lambda function in Ireland, with name `S3BucketBlockPublicAccess`.
Lambda > Functions > S3BucketBlockPublicAccess

In the S3BucketBlockPublicAccess, under  Environment variables you will see 
S3_EXCEPTION: with the bucket name added.

We only have one bucket in the list at the moment.

Definition of Done:
- Create a runbook

**Comment by AntonyBishop** [comment]
Related to #1506

**Comment by digitalronin** [comment]
closed by https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/840
