### ISSUE TITLE
Enable ECR image scanning for all repos

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1429]
Placeholder ticket. Needs more details

See this slack thread: https://mojdt.slack.com/archives/C57UPMZLY/p1574070816175300

 - [ ] turn on image scanning on push for all existing ECR repos
 - [ ] alter our ECR module so that image scanning on push is enabled for all new ECRs
 - [ ] add documentation to the user guide for how to retrieve scan results https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html#describe-scan-findings
 - [ ] figure out how to send image scan alerts to Slack
 - [ ] figure out how to send image scan alerts to teams' Slack channels

**Comment by sldblog** [comment]
(Additional context, from our teams' perspective)

For our teams, it would be valuable for all members of the GitHub team to be able to:

- browse scan results for all image tags pushed so that we can find out what we have
- show scan results on our screen so that we have awareness
- kick-off a check CLI command after Docker build on CircleCI so that we can develop our pipeline around this

**Comment by robinsillem** [comment]
We (Probation Core Services) also have a similar backlog item, https://dsdmoj.atlassian.net/jira/software/projects/PCS/boards/375/backlog?selectedIssue=PCS-37 . We are planning to do this work in the next sprint (starting at the end of this week)

**Comment by sldblog** [comment]
💭 https://snyk.io/product/container-vulnerability-management/ may also be relevant

**Comment by sldblog** [comment]
https://github.com/aquasecurity/trivy is currently in "Trial" on the ThoughtWorks radar: https://www.thoughtworks.com/radar/tools?blipid=201911077

> Our teams particularly like Trivy, a vulnerability scanner for containers, because it's easier to set up than other tools, thanks to it shipping as a stand-alone binary.

**Comment by sldblog** [comment]
We implemented `trivy` here: https://github.com/ministryofjustice/laa-legal-adviser-api/pull/145

Before upgrading packages: https://app.circleci.com/jobs/github/ministryofjustice/laa-legal-adviser-api/1537
After: https://app.circleci.com/jobs/github/ministryofjustice/laa-legal-adviser-api/1541
