### ISSUE TITLE
Set up slack channel for test alerts

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#143]
## Background

Part of EPIC #139 

When setting up our monitoring on the `test-1` cluster we will need to have a slack channel that we can post test version of "low priority alerts" into. This will give us the ability to test the end to end process for alerting. 

## Definition of done

- [x] There is a test slack channel 
- [x] It has a name that inicates it is for testing alerts. 
- [x] The people working on creating the alerts know which channel this is

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
Test channel called cp-prometheus-test
