### ISSUE TITLE
Enhance migration section in the user-guide

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1430]
## Background

Service teams are having difficulties planning for migration and breaking down the work into small achievable tasks.

It would be good to complement our existing migration with an example roadmap, describing the main milestones of the process. 

## Approach

A graphical diagram would be better understood by the teams.

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/concepts.html#migrating-to-the-cloud-platform-from-template-deploy

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
