### ISSUE TITLE
RDS CA Replacement - Intranet - Development

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1431]
This is a ticket for the RDS CA replacement for Intranet Development.

RDS instance: ir7j01r0ep3mw2

Environment Type: Development

Forced Reboot?: Yes

Contact: @Damien Wilson. Contact him just prior to the change to let him know we are making that change.

**Comment by vijay-veeranki-moj** [comment]
Done migrating Certificate authority to rds-ca-2019
