### ISSUE TITLE
Spike test for our terraform modules

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1438]
This could be an extension of our cluster integration tests, which would
exercise our terraform modules to build and test AWS resources.

I'm not sure yet exactly how this could work, and we would need to
parallelize these tests somehow, or they will take forever.

**Comment by vijay-veeranki-moj** [comment]
Created a document for this ticket

https://docs.google.com/document/d/1kTx0GKbSLIWLKsDL9kuiXIuy8Lbkfx73Pim4SzJaeGY/edit#

**Comment by vijay-veeranki-moj** [comment]
Created a new ticket, from this fire-break ticket.

https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/1514

Closing this ticket, as raised a separate ticket
