### ISSUE TITLE
Automated installation of Prometheus on test cluster

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#144]
## Background

Part of Epic #139 

From the initial spikes that we did on Kubernetes we chose [Prometheus](https://prometheus.io/) as the tool that we wanted to use for monitoring and metrics management on our clusters. This story is to setup Prometheus on the test cluster and ensure we have an automated, repeatable way of deploying it.

## Proposed user journey

Cloud platform team members should be able to spin up a new Prometheus on a new cluster through an automated process. It might require a manual kick off, but something like the following would work:

Assumption: we have just built a new `test-13` cluster.

- Cloud platform team member wants to set up Prometheus on the cluster
- Cloud platform team member goes to documentation on how to setup prometheus
- They run the script or job that is specified in that documentation, providing any config that is specific to the `test-13` cluster (i.e. secrets, names etc)
- When the job is finished they can test that prometheus is up and running by e.g. navigating to a dashboard 

## Approach

We want to use the [CoreOS prometheus operator](https://github.com/coreos/prometheus-operator) to build prometheus instances.

This story will involve setting up the operator and then creating an instance of prometheus.

## Definition of done

- [x] There is a `monitoring` namespace.
- [x] The prometheus operator is deployed in the `monitoring` namespace.
- [x] An instance of prometheus has been created in the `monitoring` namespace, using the operator CRD. For the scraping configuration, use generic defaults.
- [x] The prometheus web ui is not exposed through the ingress controller. A user can reach the prometheus web ui using `kubectl port-forward`.
- [x] The resources created in the steps above are managed in the environments repo.
- [x] There is documentation that lists all the steps that a Cloud platform team member needs to go through in order to setup prometheus on a cluster.
- [x] Tested by installing on a cluster that has no existing prometheus resources defined on it (a new cluster or one where prometheus has been cleaned up) 

## Reference

https://github.com/coreos/prometheus-operator/blob/master/Documentation

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/commit/c228123c0906cc87da10b51a2c2e8f0bae7394e7

Namespace created.

**Comment by jasonBirchall** [comment]
values.yaml created for prometheus here: 
https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/helm/prometheus-operator/values.yaml

Have now installed the prometheus-operator on the test-1 cluster using:
`helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring -f values.yaml`

Pod now running in the `monitoring` namespace.

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/18

https://github.com/ministryofjustice/cloud-platform-environments/pull/19

**Comment by sablumiah** [comment]
PRs for new helm values files for exporter-node, grafana, alertmanager. ^^

To install kube-prometheus using upstream chart: `helm install coreos/kube-prometheus --name kube-prometheus --namespace monitoring -f values.yaml`

pre-req: `helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/`

**Comment by jasonBirchall** [comment]
Port forward command is:
`kubectl port-forward -n monitoring prometheus-kube-prometheus-0 9090`

**Comment by jasonBirchall** [comment]
After a chat with @kalbir, it has been decided documentation for Prometheus installation will exist in it's own repo with relevant config files.

This will sit here: 
https://github.com/ministryofjustice/cloud-platform-prometheus

**Comment by jasonBirchall** [comment]
There are two question that have been raised;
- Can kube-prometheus install prometheus-operator
- Can you install prometheus instances via prometheus-operator.
