### ISSUE TITLE
Rewrite the bootstrap pipeline

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1444]
The Bootstrap pipeline is relying on a complex Bash script to operate. 

To increase maintainability, this script should be **rewritten in Ruby**, and potentially simplified.

The files involved are : 
-  /cloud-platform-concourse/pipelines/live-1/main/bootstrap.yaml
- /cloud-platform-concourse/bin/force-pipeline-state

**Comment by AntonyBishop** [comment]
Closed due to age of story
