### ISSUE TITLE
Destroy our Jira instance

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1448]
Somehow, people can still create tickets for us on Jira

https://mojdt.slack.com/archives/C7LS87S8Z/p1574262378000100

Find the Jira instance and kill it with fire.

**Comment by AntonyBishop** [comment]
There are 4 board instances in JIRA

Cloud Platforms Firebreak
Cloud Platforms Sprint
Cloud Platforms Tickets
Cloud Platform Support

**Comment by AntonyBishop** [comment]
Boards and Project Deleted.
