### ISSUE TITLE
Create a runbook for how to recreate live-1 on a fresh AWS account

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1449]
At the moment, we don't (AFAIK) have a fully-documented procedure for
how to create a live-1 equivalent given nothing but access to github
and a new AWS account (BTW, when I say 'fully-documented', it would be
absolutely fine for the document to have steps like "Now install concourse,
follow this link to the concourse repo. README and do whatever it says.")

Having such a document would mean we always know all the bits of our
codebase and/or third-party integrations which we depend on, so it
helps to prevent us being blind-sided if, e.g. a component breaks and we'd
forgotten it was even there.

Raz/Jason may have some notes from the setup of live-1 which could form the
basis for this runbook.

**Comment by AntonyBishop** [comment]
Stale
