### ISSUE TITLE
Review metrics from cadvisor

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#145]
## Background

Part of Epic #139 

`cadvisor` provides container-related metrics and is embedded in the `kubelet` binary. We want prometheus to scrape the metrics.

## Proposed user journey

N/A

## Approach
Ensure that the metrics are being scraped.

The operator will handle (part of) it by creating a `Service` for the kubelets (https://github.com/coreos/prometheus-operator/blob/master/bundle.yaml#L99).

Prometheus needs to be configured to scrape the endpoint then. We want to configure the metrics endpoints using a `ServiceMonitor` CRD (examples [here](https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kubelets/templates/servicemonitor.yaml) and [here](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus-serviceMonitorKubelet.yaml
)).

## Questions / Assumptions

There is a prometheus instance running (depends on #144 )

## Definition of done

- [x] prometheus successfully scrapes `cadvisor` (potentially called `kubelet`) metrics (quickly verifiable on the targets list page)
- [x] any configuration required to achieve the above is managed in the environments repository
- [x] There is documentation that lists all the steps that a Cloud platform team member needs to go through in order to setup the above on a cluster (if any)

## Reference

- https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus-serviceMonitorKubelet.yaml
- https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kubelets/templates/servicemonitor.yaml
- https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L88-L129

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-prometheus/pull/4

https://github.com/ministryofjustice/cloud-platform-prometheus
