### ISSUE TITLE
Automate the setup of concourse on a test cluster

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1450]
The process of installing concourse is somewhat manual, but should be
fairly easy to automate.

Once it's automated, we should be able to add integration tests to a
pipeline, to ensure the code which maintains it is always in a good state.

**Comment by imranawan-moj** [comment]
reviewed as per:
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/758
