### ISSUE TITLE
Form Builder delete 2 namespaces

### ISSUE THREAD

**Issue by asmega** [ministryofjustice/cloud-platform#1456]
## Service name

Form Builder

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

n/a

## Problem description

Form Builder no longer needs 2 development namespaces and can be deleted. Please delete in `live-1`: `formbuilder-platform-test-staging`, `formbuilder-services-test-staging`

Most AWS resources and most resources from these namespace should have already been deleted

## Contact person

Phil Lee (me)

**Comment by razvan-moj** [comment]
done
