### ISSUE TITLE
Setup heartbeat for prometheus and alert manager

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#146]
## Background

Part of epic #139 
depends on #161
We need to monitor the monitoring system so that we get alerted if they stop working.

## Proposed user journey
N/A

## Approach

One approach to the problem is to have the two systems send "heartbeats" to an external monitoring system. If they stop sending this heartbeat, an alert is created.

## Definition of done

- [ ] `prometheus` and `alertmanager` are actively monitoring by an external system
- [ ] the Cloud platform team receives an alert if any of the two stops working

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Kube-prometheus comes with default alerts, of which, AlertManager being down and a deadmans switch are included.

**Comment by jasonBirchall** [comment]
![Screen Shot 2018-06-29 at 10.37.37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5af95b9bf7ba4500119c1fb5/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456fa6b7191a379ef0c2856415c49be5d4a1f06a3a3dc78e2a436628f0d5de883680d73c63f18acbb861fbf03bf76d84d83e0e99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb58f44de44c55a4113062f43b.png)

**Comment by alkar** [comment]
How does this work? If alertmanager goes down then we won't know unless we check prometheus itself?
