### ISSUE TITLE
Delete developer namespace

### ISSUE THREAD

**Issue by asmega** [ministryofjustice/cloud-platform#1462]
## Service name

n/a - Developer namespace

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

n/a

## Problem description

Regarding the PR https://github.com/ministryofjustice/cloud-platform-environments/pull/1618

Please delete the following namespace `emile-sample-app-dev` as it is no longer required

## Contact person

Phil Lee (me)

**Comment by razvan-moj** [comment]
done
