### ISSUE TITLE
change ingress redirect code

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#1469]
as described in https://mojdt.slack.com/archives/C57UPMZLY/p1574844095309800, IE doesn't implement HTTP 308, look into a workaround, either config change or user docs

**Comment by razvan-moj** [comment]
feature is supported in Win10/IE11, not on Win 7/8

**Comment by digitalronin** [comment]
No users have raised this as a problem, so we can probably forget about this.
