### ISSUE TITLE
Unable to ssh to dev & demo server.

### ISSUE THREAD

**Issue by misaka** [ministryofjustice/cloud-platform#147]
## Service name

Correspondence Tool Public

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X] Other - demo

## Impact on the service

Indirectly blocking work to fix a production outage: prod is not sending general enquiry emails out and we need these environments to try to replicate the issue to try to fix it.

## Problem description

Cannot ssh to one of the hosts on dev and prod:

dev: i-0829ea3cd98ec524dt2       34.244.126.177
demo: i-0dd23a08e6c6af408t2       52.48.249.96

I terminated a dev server that was exhibiting the same issue yesterday, but the new one that was respawned did not fix the issue. The server I terminated yesterday had no "Launch Configuration" listed for it, but the new one does. Regardless, though, I can't seem to ssh in.

## Contact person

Misha Gorodnitzky
misha.gorodnitzky@digital.justice.gov.uk
@misha

**Comment by razvan-moj** [comment]
fixed, had to ssh in the instance and fix salt first, Jenkins job is green now
