### ISSUE TITLE
Alerts for new namespaces go to a slack channel

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1473]
Related to https://github.com/ministryofjustice/cloud-platform/issues/1330

This commit has some alerts we might want to add, by default, to new namespaces

https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/f8b4b167f6c4642518250e2b805c5cd620f25bb9/terraform/cloud-platform-components/resources/prometheusrule-examples/application-alerts.yaml#L11

**Comment by poornima-moj** [comment]
Had a discussion with the team regarding the workflow for creating automated alertmanager routes for users slack webhook. The current setup of alertmanager has to be modified to accompany this feature. 

Team discussed and a EPIC ticket created. https://github.com/ministryofjustice/cloud-platform/issues/1509
