### ISSUE TITLE
Ensure we have control of DNS for https://checklegalaid.service.gov.uk/

### ISSUE THREAD

**Issue by exonian** [ministryofjustice/cloud-platform#1477]
## Service name

CLA

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We need to migrate CLA (the cla_public repo, laa-cla-public-staging and laa-cla-public-production namespaces) from live-0 to live-1 by Christmas.

## Problem description

We'll need to have control of the DNS zone. I don't know if this is already delegated to Cloud Platforms: if not, it will need requesting from GDS.

## Contact person

Michael Blatherwick
#laa-cla-fala on Slack

**Comment by exonian** [comment]
Given how long this is taking to resolve for FALA, and that we need this service fully migrated by Christmas for the certificates, I think we need to get started on this asap please

**Comment by AntonyBishop** [comment]
Hi,

I looks like the DNS zone has not yet been migrated to the Cloud Platform Account.

Guidance here - https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#using-a-custom-domain

As soon as you are set up we'll need your new ns records and a migration date so that we can schedule delegation in with GDS. Typical lead time is about a week.

Apologies on the delay in getting back to you.

**Comment by exonian** [comment]
Hi

Slightly confused I'm afraid. Do you mean creating a DNS zone resource in live-0 for the instance that is currently in production, so that you can point to that immediately? I don't think that's a thing we've done in `fala`, so didn't think it would need doing here.

We'll need to set up the live-1 DNS zone but I didn't think that blocked the delegation, cos for now the records will still need to point to live-0

Apologies if I'm missing something

**Comment by AntonyBishop** [comment]
This is about creating a new DNS zone resource in Live-1. The DNS zones associated with services running in Live-0 are in the mojdsd account, but for Live-1 you'll need new DNS resources that will reside in the Cloud Platform AWS account, which will have a new set of name servers.

As I understand it you can create the new zone in the Cloud Platform account and then we will liaise with yourselves and GDS for the cutover following delegation. Then everything will point to the new resources in the account for Live-1.

Does that clarify?

**Comment by exonian** [comment]
Thanks @AntonyBishop. Between this and @razvan-moj explaining it to me on Slack I finally got it :)
DNS zone now created!
