### ISSUE TITLE
Postgres upgrade for PQ - Determine how PQ can be backed up and restored in the event of an unsuccessful upgrade

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#148]
## Background

As part of a stories in the previous sprint we identified Products that were dependant on Postgres v9.3 for the purposed of upgrading them to a supported version. A list of products was identified (#85) and Product Teams were contacted (#92) to tell them about the need to upgrade and to ask what support might be required.

The Parliamentary Questions (PQ) Team confirmed that they would need assistance from Cloud Platform to carry out the upgrade on their behalf.

## Proposed user journey

This story is a pre-requisite to the actual upgrade. As neither team fully understands the infrastructure for PQ (as it was deployed prior to Template Deploy) there is significant risk in carrying out the upgrade. This story is to investigate how we can restore service to it's current state in the event of any issues following the upgrade.

## Approach

1. Determine back-up and restore processes for PQ
2. Test
3. Document

## Questions / Assumptions

1. PQ Team have identified a contact to work with us (confirmed as Daniel Penny in Tactical Products) 
2. We also need to determine how much effort we think is required from the PQ team to support the work so that they can factor this into their planning.

## Definition of done

- [x] we understand how to backup PQ
- [x] we understand how to restore PQ
- [ ] we have documented these processes
- [x] we have tested these processes

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[List of products using Postges 9.3](https://docs.google.com/spreadsheets/d/1iZUJ99tnPSH0SS4TE_JMNEigvjZWrMWNLgdoi8CrJ0E/edit?usp=sharing)

**Comment by lukaszraczylo** [comment]
The investigation is done, will focus on writing down the documentation.

**Comment by lukaszraczylo** [comment]
The process of restoring and managing backups is described in https://github.com/ministryofjustice/backupninja-formula 
After a quick word with @AntonyBishop came to the conclusion there's no need to duplicate the information.
