### ISSUE TITLE
RDS CA Replacement - Money to Prisoners - Production

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1482]
This is a ticket for the RDS CA replacement for MTP Production.

RDS instance: cloud-platform-ad84929cdc3ee730

Environment Type: Production

Forced Reboot?: Yes

Contact: @ igor.ushkarev . **Please note that the MTP Team would like to to inform users of the change and will put up a maintenance page while the changes are being made. The changes should be made in the afternoon to avoid peak times for the services. Please contact Igor at least two hours prior to make the changes so that comms can be issued and a maintenance page put up.**

**Comment by vijay-veeranki-moj** [comment]
Spoke to Igor, we are working on it 4th Dec Afternoon.

**Comment by vijay-veeranki-moj** [comment]
Completed cloud-platform-ad84929cdc3ee730
Certificate authority to rds-ca-2019
