### ISSUE TITLE
Let build-environments skip a locked namespace

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1483]
If the build-environments pipeline fails to acquire the lock on the terraform
statefile for a namespace, the whole pipeline stops.

This isn't useful - failing to acquire a lock is completely normal, so this
error (pipeline failed) is just noise.

Catch the specific failure and allow the pipeline to move on to the next
namespace.

Here is an example of the relevant error:

    executing: cd namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-core-services-tooling/resources; terraform apply -auto-approve
    Command: cd namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-core-services-tooling/resources; terraform apply -auto-approve failed.

    Error: Error locking state: Error acquiring the state lock: ConditionalCheckFailedException: The conditional request failed
      status code: 400, request id: GM5JFAP0GEE2UB0CC1QI6KK7MBVV4KQNSO5AEMVJF66Q9ASUAAJG
    Lock Info:
      ID:        d796d288-bad1-a6db-e6ff-4f964fbfe97e
      Path:      cloud-platform-terraform-state/cloud-platform-environments/live-1.cloud-platform.service.justice.gov.uk/probation-core-services-tooling/terraform.tfstate
      Operation: OperationTypeApply
      Who:       root@d07617be-2a33-458a-6035-44c770cb4ade
      Version:   0.12.13
      Created:   2019-12-02 14:44:06.388228637 +0000 UTC
      Info:

    Terraform acquires a state lock to protect the state from being written
    by multiple users at the same time. Please resolve the issue above and try
    again. For most commands, you can disable locking with the "-lock=false"
    flag, but this is not recommended.

    Traceback (most recent call last):
      9: from ./bin/apply:22:in `<main>'
      8: from ./bin/apply:10:in `main'
      7: from ./bin/apply:16:in `apply_namespaces'
      6: from ./bin/apply:16:in `each'
      5: from ./bin/apply:18:in `block in apply_namespaces'
      4: from /tmp/build/abd6a871/cloud-platform-environments-repo/bin/pipeline.rb:147:in `apply_namespace_dir'
      3: from /tmp/build/abd6a871/cloud-platform-environments-repo/bin/pipeline.rb:163:in `apply_terraform'
      2: from /tmp/build/abd6a871/cloud-platform-environments-repo/bin/pipeline.rb:50:in `apply'
      1: from /tmp/build/abd6a871/cloud-platform-environments-repo/bin/pipeline.rb:75:in `tf_apply'
    /tmp/build/abd6a871/cloud-platform-environments-repo/bin/pipeline.rb:173:in `execute': unhandled exception

**Comment by digitalronin** [comment]
Clearing up very old lock records should be a separate task - probably a concourse pipeline

**Comment by AntonyBishop** [comment]
Closed due to age of story
