### ISSUE TITLE
Clarify the zone names used in external DNS integration tests

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1487]
Sometimes the external DNS integration tests fail partway through, leaving
test zones which have to be manually deleted to get the tests to pass
again.

The names of the test zones do not make it clear that they belong to the
integration tests (parent.service.justice.gov.uk and child.service.justice.gov.uk)

Change the tests to use zone names which are more obviously part of the
integration tests (and therefore easier to search for), and clean up any
leftover zones with the "old" names.

**Comment by AntonyBishop** [comment]
Replace by new tests.
