### ISSUE TITLE
Refactor cloud-platform-environments-checker and merge to env. repo

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1491]
https://github.com/ministryofjustice/cloud-platform-environments-checker

This repo was written a while ago. A lot of the functions it requires are
now available from the shared libraries in the environments repository.

* Refactor the checker to use shared libraries
* relocate all its code to the environments repository
* Update the pipeline
* Deprecate the old repository

**Comment by davidread** [comment]
Maybe this functionality is better as a hoodaw/report?

**Comment by AntonyBishop** [comment]
Closed due to age of story
