### ISSUE TITLE
RDS CA Replacement - Prison Visits Booking - Staging

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1492]
This is a ticket for the RDS CA replacement for PVB Staging.

RDS instance: cloud-platform-586e58a24ac752f4

Environment Type: Staging

Forced Reboot?: Yes

Contact: #the_sassy_devs channel. Contact team to test that replacement was successful.

**Comment by vijay-veeranki-moj** [comment]
Done updating CA for cloud-platform-586e58a24ac752f4

to Certificate authority
rds-ca-2019
