### ISSUE TITLE
RDS CA Replacement - OMIC - Staging and Pre-production

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1493]
This is a ticket for the RDS CA replacement for OMIC Staging and Pre-production

RDS instance(s):
cloud-platform-75ec3c1f26a64520
cloud-platform-aaaaa93fa5e829b2

Environment Type: Non-production

Forced Reboot?: Yes

Contact: #the_sassy_devs channel. Contact team to test that replacement was successful.

**Comment by vijay-veeranki-moj** [comment]
Done updating 
cloud-platform-75ec3c1f26a64520
cloud-platform-aaaaa93fa5e829b2


to Certificate authority
rds-ca-2019
