### ISSUE TITLE
Get access to existing backups

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform#15]
These **may not** actually exist and the container/job **may not** be running anywhere.

The repo that suggests they do is here:

https://github.com/ministryofjustice/rattic-docker

## Done when

- [x] We know and have documented if, where and when this is running.

**IFF** is it running and creating backups:

- [x] GPG keys for users that are no longer authorised to access the backup have been removed from the job.
- [x] Expired GPG keys are removed from the repo.
- [x] Add GPG keys to cover the member of the cloud platform team that need access.
- [ ] Ensure the target backup S3 bucket is accessible the cloud platform team members who require it.

**Comment by pwyborn** [comment]
daily backup's to s3 bucket https://console.aws.amazon.com/s3/buckets/rattic.backup/?region=eu-west-1&tab=overview&currentmarker=1k8Gc3QX1E%2BJuqYuN3K2p6UROpgqeocvjJPxD%2BdWW4Cp%2BvoIGp5Uq33fCp0qrd1fhvSQkAeqolak%3D

**Comment by razvan-moj** [comment]
Rattic itself doesn't build anymore (has a reference to Django<1.7 in its requirements.txt) so we used a workaround with
```
# cat Dockerfile
FROM registry.service.dsd.io/rattic:latest
ADD rattic-conf /opt/rattic/conf/local.cfg
```
and restarted the service using that. Will close after we verify a backup decryption tomorrow.

**Comment by razvan-moj** [comment]
One more change was needed: Rattic doesn't import automatically the keys and root's ~/.gnupg is mounted from the host so had to run first
```root@rattic:~/tmp# gpg --recv-keys F7CA18D658B8C32D A6DE81BFB7429174 F7F7899AA435E44F EE6C0F470B083386 0A2BD3A56D3AEBED```
to get our keys in
Executed afterwards a ```# cd /opt/rattic ; env - `cat /dev/shm/env.txt` /usr/bin/python manage.py backup``` in the container, the file is uploaded to https://s3.console.aws.amazon.com/s3/buckets/rattic.backup/?region=eu-west-1&tab=overview and I can decrypt it
