### ISSUE TITLE
RDS CA Replacement - Book a Secure Move - Non-Production

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1500]
This is a ticket for the RDS CA replacement for Book a Secure Move Non-Production instances.

RDS instance(s): 
cloud-platform-1a4d75fee1618722
cloud-platform-e829e612552f9703

Environment Type: Non-Prod

Forced Reboot?: Yes

Contact: @ Ryan Brooks. Contact team to test that replacement was successful.

**Comment by vijay-veeranki-moj** [comment]
Done updating 
RDS instance(s):
cloud-platform-1a4d75fee1618722
cloud-platform-e829e612552f9703

To Certificate authority
rds-ca-2019

**Comment by vijay-veeranki-moj** [comment]
Done below prod RDS instance as well

cloud-platform-fb1739914b873b00
