### ISSUE TITLE
Copy DNS records to checklegalaid.service.gov.uk

### ISSUE THREAD

**Issue by exonian** [ministryofjustice/cloud-platform#1501]
## Service name

CLA

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

cla_public needs migrating from live_0 to live_1 before December 28th

## Problem description

We need GDS to delegate DNS to our new zone. Before they can do that, we need to copy all DNS records across to it.

## Contact person

Michael Blatherwick
#laa-cla-fala

**Comment by AntonyBishop** [comment]
Just need a date and time so that GDS can schedule in changes.

**Comment by exonian** [comment]
@razvan-moj had said Cloud Platforms would do the DNS copying as you are already familiar and the CLA team aren't. This ticket is so that it could be prioritised and we could be notified when it was done. And then we can schedule the delegation to the zone

**Comment by AntonyBishop** [comment]
Request submitted to GDS #3871404
