### ISSUE TITLE
RDS CA Replacement - Check My Diary - Non-Production

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1502]
This is a ticket for the RDS CA replacement for Check My Diary Non-Production instances.

RDS instance(s):
cloud-platform-13962204fd879828
cloud-platform-d07334102a08ef5d

Environment Type: Non-Prod

Forced Reboot?: Yes

Contact: @ Fareed Mohammed. Contact team to test that replacement was successful.

**Comment by vijay-veeranki-moj** [comment]
Updated 
RDS instance(s):
cloud-platform-13962204fd879828
cloud-platform-d07334102a08ef5d

to Certificate authority
rds-ca-2019
