### ISSUE TITLE
New Slack webhook integration for Pingdom for peoplefinder-production please

### ISSUE THREAD

**Issue by Polsonby** [ministryofjustice/cloud-platform#1505]
## Service name
Peoplefinder

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service
So that the team is notified when/if the service goes down

## Problem description
As per [cloud platform guide](https://github.com/ministryofjustice/cloud-platform-environments/pull/1741), please can you create a Pingdom integration for sending alerts to two slack channels and supply the integration ids to us? Relates to this PR https://github.com/ministryofjustice/cloud-platform-environments/pull/1741

Team: Staff Tools and services
Service: Peoplefinder
Channels: #peoplefinder and #staff-services-tech

## Contact person
Javid Ali or Ian Anderson

**Comment by vijay-veeranki-moj** [comment]
Hi Ian, 

This is done now

for #peoplefinder: 98671
for #staff-services-tech: 98672
