### ISSUE TITLE
EPIC: Rationalise alerts and send teams' alerts to their own Slack channels

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1509]
Problem:

* We use terraform to map team names to slack channels (this ties together terraform code and alertmanager in an awkward way)
* We use a different slack webhook per team to send alerts to teams' channels
* We don't have default alerts for teams namespaces (e.g. if a pod is crash-looping, the team should get a slack message)

Plan:

* Add default labels to prometheus operator helm chart (and apply it). This will allow us to create alertmanager routes which *only* match the default rules
* Add an alertmanager route which matches the additional labels we have added to the default rules, and sends the alerts to us as we do now
* Add an alertmanager route which matches alerts with additional metadata; "channel", (and perhaps "team", and "namespace"), and which expects "severity" to actually mean severity. This route will send a message to the slack channel specified in the alert, using the "master" slack webhook from concourse-main (which can post to any channel)
* Remove the "warning" and "critical" entries from the terraform.tfvars file (so that we get the "new" alerts and not the old ones)
* Create a prometheus rule template which, when applied, creates a set of default alert rules in a namespace, where channel, team and namespace are provided in the alert object
* Modify the build pipeline to apply the prometheus rule template to each namespace, adding the appropriate channel, team and namespace values
* Update the user guide and any runbooks relating to alerting, to include instructions on providing channel etc.
* Convert all existing team alerts to the new system

**Comment by AntonyBishop** [comment]
Some user feedback - https://mojdt.slack.com/archives/C57UPMZLY/p1616665950109900

**Comment by AntonyBishop** [comment]
This is a feature of managed prometheus. Revisit as part of that epic.
