### ISSUE TITLE
Deploy node_exporter

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#151]
## Background

Part of Epic #139 

We need to scrape a number of system / host level metrics. For this, we will use `node_exporter` which is the standard approach with prometheus and kubernetes.

## Proposed user journey

N/A

## Approach
We will deploy `node_exporter` as a DaemonSet on the kubernetes cluster. It needs to run on all nodes (masters and workers).

As a starting point, we can use the [node-exporter helm chart](https://github.com/coreos/prometheus-operator/tree/master/helm/exporter-node) provided in the `prometheus-operator` repository and `helm template` to render the templates locally. We might not need all of the produced files.

## Questions / Assumptions

N/A

## Definition of done

- [x] `node_exporter` is deployed as a `DaemonSet`
- [x] the configuration (manifest files) for `node_exporter` are managed in the environments repository
- [x] prometheus successfully scrapes metrics from `node_exporter`, easily verified by checking the list of targets in prometheus (this depends on https://github.com/ministryofjustice/cloud-platform/issues/144 being complete)
- [x] There is documentation that lists all the steps that a Cloud platform team member needs to go through in order to setup `node_exporter` on a cluster.

## Reference

- https://github.com/prometheus/node_exporter
- https://github.com/coreos/prometheus-operator/tree/master/helm/exporter-node
- https://github.com/kubernetes/charts/tree/master/stable/prometheus/templates

**Comment by jasonBirchall** [comment]
node_exporter DaemonSet deployed to test1 cluster under the monitoring ns.

**Comment by jasonBirchall** [comment]
Manifest files for node_exporter are held in the kube-prometheus values.yaml file. Which will be held the following repository:
https://github.com/ministryofjustice/cloud-platform-prometheus

**Comment by jasonBirchall** [comment]
All nodes are being monitored in Prometheus. Have browsed to the list of targets and nodes are there.

**Comment by jasonBirchall** [comment]
As the documentation to install node_exporter is the same as the kube-prometheus, it already exists here: https://github.com/ministryofjustice/cloud-platform-prometheus/blob/master/README.md
