### ISSUE TITLE
Add encryption at rest and daily snapshots to EBS-backed persistent volumes

### ISSUE THREAD

**Issue by robinsillem** [ministryofjustice/cloud-platform#1511]
## Service name

Probation Shared DevOps tooling

## Service environment

- [x ] Dev / Development
- [x ] Staging
- [x ] Prod / Production
- [ ] Other

N.B. While this is technically Dev, it's tooling that builds the docker images that run in production and other environments

## Impact on the service

Lack of encryption of persistent volumes is a blocker to deployment of the DevOps tooling to Dev teams, as details of application vulnerabilites may appear in persisted files. This is a request from our security architects.

## Problem description

We have Jenkins build logs and other things in mounted persistent volumes (that's the Jenkins architecture). We'd rather not lose those (though it wouldn't be the end of the world) and we can't guarantee that dev teams won't do something naughty and expose secrets in their pipelines. Results of vulnerability scans may also appear as files in there.

## Contact person

Robin Sillem
robin.sillem@digital.justice.gov.uk

**Comment by robinsillem** [comment]
Ideally we would like this done by mid-January, when we plan to start rolling it out to dev teams

**Comment by vijay-veeranki-moj** [comment]
Hi @robinsillem 

Summary of the "PVCs with encryption + daily snapshots" call
users can choose a StorageClass (what's the name?) for their PVCs which will encrypt the underlying EBS volume
users can add a tag (value TBC), which will result in a daily snapshot of the volume being stored for 30 days - the "daily" part and the "30 days" part are cluster-wide settings
If users want to restore their volume from a snapshot, they need to ask us to do this (and this will overwrite the PVC)
We will add documentation to the user guide explaining all of this

**Comment by vijay-veeranki-moj** [comment]
Will update you with the storageclass name and tag you should be using.

**Comment by robinsillem** [comment]
Sounds ideal, thanks.

**Comment by vijay-veeranki-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/183

**Comment by vijay-veeranki-moj** [comment]
Hi @robinsillem 

Please see the guidence here 

`https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/persistent-volume-encryption-snapshot.html#snapshots-to-back-up-persistent-volumes`
