### ISSUE TITLE
Apply Promethus 500 to 750 volume increase in live-1

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#1513]
We made the manual edit change, but need to apply the change to live-1

https://mojdt.slack.com/archives/C514ETYJX/p1575991079396000

But we may need to test it before we apply this change?

**Comment by mtrblmoj** [comment]
following this guide : https://runbooks.cloud-platform.service.justice.gov.uk/expand.html#expanding-persistent-volumes-created-using-statefulsets
