### ISSUE TITLE
Integration test for terraform modules

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#1514]
Background:
This is related to firebreak-ticket

https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/1438

Approach:

1) Use the existing “integration-tests” pipeline and create a new schedule to run every night, on certain days?
and separate job just for module-tests

`cd ./smoke-tests; rspec spec/module_tests.rb`

2) In the infrastructure repo, write the tests `module_tests.rb` to get triggered from the pipeline.

3) The tests written should cover all the  existing modules, and should pick the latest modules from the modules repo, and use as many variables defined in the module and save it as a secret.

Spike document link:
https://docs.google.com/document/d/1kTx0GKbSLIWLKsDL9kuiXIuy8Lbkfx73Pim4SzJaeGY/edit#

**Comment by digitalronin** [comment]
This should probably wait until our integration tests are a bit more reliable. Currently, we're having intermittent failures of the TZCronJob test, and all the error page specs have been disabled because they cause the KubeAPILatencyHigh alert to fire.

**Comment by vijay-veeranki-moj** [comment]
Created a new Issue for this, so closing this one as it is duplicate.

https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/1883
