### ISSUE TITLE
Upgrade metrics-server

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1515]
## Background

The metrics-server deployment that is currently running on live-1 seems to be hitting the API intensively, so much that it triggers a KubeAPILatencyHigh alarm.

We are currently using the chart version `2.0.4`, the latest is `2.8.8`. 
Even if the upgrade doesn't resolve the issue, it's best practice to stay up-to-date.

**Comment by digitalronin** [comment]
We've done this. We're now running 2.8.8
