### ISSUE TITLE
Enable cluster-autoscaler 

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#1520]
This ticket for actual implementation ticket for the cluster autoscaler (FB ticket #1445)

Firebreak work has been added to a branch called "autosc" with terraform install config as well as new priority class and pause pods to use scaler cluster without the need to user pods going into a pending state due to unavailable resources.

Things to think about:
Min and max number of nodes is ASG?
How many pause pods?
What resources will be 'held'  by pause pods? 
Do we use horizontal pod autoscaler for pause pods to dynamically increase number of pods as cluster increases? 
Set up alerts so we are notified when cluster increases or decreases? (there is a service-monitor for prometheus to scrape metrics enabled)

**Comment by sablumiah** [comment]
https://github.com/helm/charts/blob/master/stable/cluster-autoscaler/values.yaml

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-configure-overprovisioning-with-cluster-autoscaler

**Comment by AntonyBishop** [comment]
Closed due to age of story
