### ISSUE TITLE
RDS CA Replacement - Book a Secure Move - Production

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1522]
This is a ticket for the RDS CA replacement for Book a Secure Move Production instance.

RDS instance(s):
cloud-platform-fb1739914b873b00

Environment Type: Prod

Forced Reboot?: No

Contact: @ Ryan Brooks. Contact team to confirm when changes are made. Reboot will take place in next maintenance window.

**Comment by vijay-veeranki-moj** [comment]
This is already upgraded to 

Certificate authority
rds-ca-2019
