### ISSUE TITLE
Create a 'kops update' reporter pipeline

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1524]
We have no automated means of getting kops template changes deployed to
live-1. Any change we make has to be manually applied, followed by a
`kops rolling-update...` to actually alter the cluster.

It would be good to have a pipeline to do this for us, either manually
triggered, or running on a schedule.

As a first step, create a "reporter" pipeline which runs every morning,
and tells us if the state of the cluster is out of sync wrt the source
code in github. This pipeline could run on a schedule.

A pre-requisite for this might be a pipeline which regularly runs a
`terraform apply` from the infrastructure repo, and then runs
`kops replace...` to update the kops state from the generated kops
yaml file for the cluster.

**Comment by AntonyBishop** [comment]
Close. We intend to migrate to EKS before we will get to this.
