### ISSUE TITLE
Assistance with prometheus/alert manager

### ISSUE THREAD

**Issue by colinbruce** [ministryofjustice/cloud-platform#1527]
## Service name

LAA Apply

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production / private beta
- [ ] Other

## Impact on the service

Negligible on service, significant on team productivity!

## Problem description

The apply service has been configured to alert when it's sidekiq queues are not being reported on or too busy.  The cronjob that submits the metrics has stopped running on prod but continues to run successfully on staging.
A PR has been submitted to split the alert into two unique alerts.  This has been merged and deployed the cronjob still exits after 3 minutes despite a manual job creation and the original, removed, alert is still firing into the prod-alerts channel in slack.

## Contact person

Colin Bruce on slack or email

**Comment by AntonyBishop** [comment]
Done
