### ISSUE TITLE
Separate masters and workers in Grafana resource dashboard

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1528]
*Background*

It would be handy if we had the ability to check the usage on workers and masters seprately. Currently we have the ability to see cluster resource status using the following url:
https://grafana.cloud-platform.service.justice.gov.uk/d/efa86fd1d0c121a26444b636a3f509a8/k8s-compute-resources-cluster?refresh=10s&orgId=1

My suggestion would be to have a similar dashboard for provisionable resources on masters and workers.

**Comment by AntonyBishop** [comment]
Not required if move to EKS
