### ISSUE TITLE
Rename node-r52xl instance-group to something more reflective of state

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1529]
Currently the kops manifest contains our worker nodes in an instance group called `node-r52xl`. This made sense at the time as the node size was infact r52xls, but that has recently changed. 

Change the instance group name to something like `nodes`

**Comment by digitalronin** [comment]
Remember to update the `recycle-node.rb` script in the infrastructure repo. It uses the instancegroup name to confirm that it's replacing the correct EC2 instance.

**Comment by jasonBirchall** [comment]
This has changed under another ticket.
