### ISSUE TITLE
Postgres Upgrade for PQ from 9.3 to 9.6 - Development Environment

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#153]
## Background

As part of a stories in the previous sprint we identified Products that were dependant on Postgres v9.3 for the purposed of upgrading them to a supported version. A list of products was identified (#85) and Product Teams were contacted (#92) to tell them about the need to upgrade and to ask what support might be required.

The Parliamentary Questions (PQ) Team confirmed that they would need assistance from Cloud Platform to carry out the upgrade on their behalf.

## Proposed user journey and Approach

1. Depends on #148 being completed.
2. Agree with PQ when Dev can be upgraded
3. Carry out upgrade from 9.3 to 9.6 using AWS Postgres upgrade console
4. PQ Team test PQ Dev instance 
5. PQ Team sign-off on upgrade success and agree any monitoring period
6. If unsuccessful implement rollback procedure as be #148 
7. PQ and CP investigate any errors and agree to repeat upgrade if required

## Questions / Assumptions

1. Depends on #148 (Completed)
2. PQ Team have identified a contact to work with us (confirmed as Daniel Penny in Tactical Products) (Completed)
3. PQ Team have confirmed that Dev, Staging and Production are using the save version of Postgres (confirmed by Andy Robb) (Completed)
4. PQ application is compatible with Postgres 9.6 (confirmed by Andy Robb) (Completed)

## Definition of done

- [x] #148 completed
- [x] agreement for PQ Team to upgrade Dev instance of Postgres
- [x] upgrade implemented
- [x] upgrade documentation updated
- [x] PQ documentation updated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[List of products using Postges 9.3](https://docs.google.com/spreadsheets/d/1iZUJ99tnPSH0SS4TE_JMNEigvjZWrMWNLgdoi8CrJ0E/edit?usp=sharing)

**Comment by lukaszraczylo** [comment]
Upgrade has been performed.
The process itself required multiple steps to be applied:
- upgrade to 9.4.18
- change instance class to db.t2.small ( as the old type does not support versions 9.5+ )
- upgrade to 9.5.13
- upgrade to 9.6.9
- reboot to apply AWS parameter group changes.

Waiting for the confirmation from @danielatdigital side.
