### ISSUE TITLE
Live-0 - remove namespaces and terraform resources 

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#1532]
Remove live-0 namespaces and terraform resources  except FALA.

We have 53 namespaces and terraform resources for those namespaces.
It is running on a 15 node cluster.

To reduce the resources used for live-0 , we need to remove non-prod namespaces.

**Comment by digitalronin** [comment]
What's the exact name of the FALA namespace that we need to keep?

**Comment by digitalronin** [comment]
I've deleted all the namespaces which were obviously non-prod, except for two which had terraform problems:

* check-my-diary-dev
* laa-legal-adviser-api-staging

We can remove the remaining production namespaces w/c 06/01/20, when we can double-check with teams that it's safe to do so. At that point, we should be able to scale the cluster down to 3 nodes.

**Comment by digitalronin** [comment]
This is as done as it needs to be. The leftover awkward namespaces can just hang around until we can delete the entire AWS account, when we turn off live0
