### ISSUE TITLE
moj-laalaa aws account / resource removal

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#1533]
## Service name

Remove moj-laalaa aws account and it's resources
Remove https://ci.service.dsd.io/job/DEPLOY-laalaa/

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [x] Other

## Problem description
The moj-laalaa aws account was hosting the two applications FALA and LAALAA.
We have migrated both the FALA(currently live-0) and LAALAA(live-1) applications to the cloud platforms and no longer require the old aws account and it's resources

## Contact person
Slack channel: [hash]laa-cla-fala
Slack: [at]Said

**Comment by said-moj** [comment]
The aws account is: moj-laalaa

**Comment by AntonyBishop** [comment]
Jenkins job has been disabled. Unable to close AWS account as we do not have access to that account. Have reported back to requestor.

**Comment by said-moj** [comment]
Thanks @AntonyBishop 

Is it possible to remove the AWS resources then so we are not billed for them.

**Comment by AntonyBishop** [comment]
Hi @said-moj That is possible but would again need access to the AWS account, which we don't have.
