### ISSUE TITLE
Replace terraform data.template_file with templatefile function calls

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1534]
Now that we have upgraded to terraform 0.12, we should use some of its
capabilities to clean up our code.

In particular, the subnets for the kubernetes masters in the kops template
file should be provided in a single data structure that we iterate over in
the code, rather than being hard-coded as they are now.

**Comment by AntonyBishop** [comment]
This should be done before we upgrade to 0.13

**Comment by AntonyBishop** [comment]
Closed due to age of story
