### ISSUE TITLE
RDS CA Replacement - Check My Diary - Production

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1535]
This is a ticket for the RDS CA replacement for Check My Diary Production instance.

RDS instance(s):
cloud-platform-61e5a328954063a7

Environment Type: Prod

Forced Reboot?: No

Contact: @ Fareed Mohammed. Have agreed that changes can be made Friday 20th December so that restart can be scheduled for Friday maintenance window.

**Comment by vijay-veeranki-moj** [comment]
Done updating cloud-platform-61e5a328954063a7

It will get updated in the next maintenance window `fri:00:22-fri:00:52 UTC (GMT)`
