### ISSUE TITLE
Expore custom RDS backup/cleanup strategy

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1537]
## Background

We encourage teams to come up with their own strategy/script, if they need more than the daily automated RDS backup. 

Problem : There is a limited number of manual snapshot we can have in the CP account. 

## Approach

There is no retention period for RDS manual snapshot. The clean-up process has to be baked into the custom script.

I suggest we  figure out an example for the user-guide

**Comment by AntonyBishop** [comment]
Closed due to age of story
