### ISSUE TITLE
Set up end to end alerting: slack

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#154]
## Background

Part of epic #139 

We want to be able to alert from Prometheus into Slack -- particularly for low priority alerts. We have already set up a test slack channel (#143), this story is to connect Prometheus to Slack and make it so that a test alert from Promotheus sets off Slack.

## Proposed user journey

- Something happens on the cluster that sets off an alert (just do a test version in this case)
- The alert is generated in slack
- An engineer investigates and fixes it
- The alert stops firing

## Approach

This might be helpful: https://prometheus.io/blog/2016/03/03/custom-alertmanager-templates/

## Definition of done

- [x] Demonstrate that a test alert from prometheus generates an alert in the test slack channel
- [x] Demonstrate that fixing the alert stops it in slack
- [x] The prometheus to slack integration is defined in code 
- [x] Some documentation on how the integration is defined

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-prometheus/commit/66f2bdb019d9b2fb6a64b2e84632ec8aaaa453fb

Test slack channel: #cp-prometheus-test
