### ISSUE TITLE
Upgrade Prometheus Operator to the latest (8.X.X)

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#1553]
At the moment we are using [3.0.0 helm chart ](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/terraform/cloud-platform-components/prometheus.tf#L138) and the latest is [8.X.X](https://github.com/helm/charts/blob/master/stable/prometheus-operator/Chart.yaml#L15). We should avoid having a big divergence between them and do the upgrade. 

I would advise reducing the _values.yaml_, leaving only the values that change from the default values.yaml.

**Comment by vijay-veeranki-moj** [comment]
Promethus Operator is now upgraded to latest version 8.7.0

Cound't enable admissionWebhooks with this release as it is separate work, raised a ticket for it.
