### ISSUE TITLE
Automatically check module versions in namespace PRs

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1556]
When teams raise a PR with terraform code that uses our terraform modules,
one thing we need to do when reviewing the PR is to check that the module
version in the PR is the latest release of that terraform module

It should be straightforward to automate this check in a github action,
which would save us doing a manual check every time.

**Comment by mtrbls** [comment]
Stalled for two long - back in backlogs

**Comment by AntonyBishop** [comment]
Closed due to age of story
