### ISSUE TITLE
Dynamic capacity management 

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#1564]
Our cluster has a non-production environment which can be downscaled at night (or outside working hours). In order to achieve it, we'll have to scale down some deployments and reduce the cluster side dynamically.

Automatically scale down deployments/pods can be done using [kube_downscaller](https://github.com/hjacobs/kube-downscaler/tree/master/kube_downscaler) integrated with cluster-autocaller (stable helm chart works out of the box).
 
It would be good to have a spike about integrating these tools and verify how can we take advantage of them

**Comment by digitalronin** [comment]
NB: Any capacity scaling that we do really needs to be time based, rather than based on traffic/load to services.

The opportunity for cost-savings is in scaling down non-prod environments outside of working hours, and those environments will receive very little traffic/load anyway, so scaling up/down in response to traffic/load won't work (unless we say that *any* traffic is a reason to scale (back) up).

The AP team may have some code we can usefully borrow.

**Comment by sablumiah** [comment]
We need to link kube-downscaler with cluster-autoscaler to make savings. 

https://github.com/hjacobs/kube-downscaler
https://github.com/helm/charts/tree/master/incubator/kube-downscaler

helm chart:
# Default values for kube-downscaler.
# Declare variables to be passed into your templates.

# How many kube-downscaler pods should run in deployment
replicaCount: 1
name: kube-downscaler
debug:
  enable: false

# Namespace where kube-downscaler is going to be deployed.
namespace:
  # Deployment will query all namespaces if left empty:
  active_in: ''

# The resources kinds kube-downscaler is allowed to manage
downscaleResources:
  - deployments
  - statefulsets

# List of namespaces to be excluded from the downscaler
excludedNamespaces: []

# List of deployments to be excluded from the downscaler
excludedDeployments: []

# Default is 1 minute.
interval: 60

rbac:
  # If true, create & use RBAC resources
  create: true
  # Ignored if rbac.create is true
  serviceAccountName: default

image:
  repository: hjacobs/kube-downscaler
  tag: 19.10.1
  pullPolicy: IfNotPresent

resources:
  limits: {}
  requests: {}
  # limits:
  #   cpu: 50m
  #   memory: 200Mi
  # requests:
  #   cpu: 50m
  #   memory: 200Mi

securityContext:
  runAsUser: 1000

extraArgs:
  - --default-uptime=Mon-Fri 08:30-22:30 UTC
  - --downtime-replicas=1

nodeSelector: {}

tolerations: []

affinity: {}

podLabels: {}

podAnnotations: {}
