### ISSUE TITLE
RDS CA Replacement - PVB - Production

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1565]
This is a ticket for the RDS CA replacement for PVB production instance.

RDS instance(s):
cloud-platform-f3ff288a8d112951

Environment Type: Production

Forced Reboot?: No

Contact: @ Amit. Have agreed that changes can be made in next maintenance window (Sunday).

**Comment by poornima-moj** [comment]
DB Instance updated for CA 2019 and set to reboot on maintenance window 19th Sunday `sun:05:29-sun:05:59 UTC (GMT)`
