### ISSUE TITLE
RDS CA Replacement - MOiC - Production

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1566]
This is a ticket for the RDS CA replacement for MOiC production instance.

RDS instance(s):
cloud-platform-0fe5d72ea3e106e5

Environment Type: Production

Forced Reboot?: No

Contact: @ Amit. Have agreed that changes can be made in next maintenance window (Thursday 16th January).

**Comment by poornima-moj** [comment]
DB Instance updated for CA 2019 and set to reboot for Thursday 16th Jan `thu:03:26-thu:03:56 UTC (GMT)`
