### ISSUE TITLE
RDS CA Replacement - claim-criminal-injuries-compensation-uat

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1567]
This is a ticket for the RDS CA replacement for claim-criminal-injuries-compensation-uat instance.

RDS instance(s):
cloud-platform-cbd2d994e63c93f0

Environment Type: UAT

Forced Reboot?: Yes

Contact: @ Stephen Sinclair. Have agreed that changes can be made **Wednesday 15th January**. Please contact Stephen on the day to to confirm when changes will be made.

Rescheduled for Wednesday 22nd January.

Checked with Stephen and did the update on 20 January.

**Comment by poornima-moj** [comment]
Contacted Stephen. Seems they have other issues so scheduling for next week.
