### ISSUE TITLE
See if users can do something with RBAC that they shouldn't be able to do

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1568]
It's not 100% clear if our RBAC setup is doing exactly what we meant it to do.
For instance, this PR:

https://github.com/ministryofjustice/cloud-platform-environments/pull/1790

The user was able to use kubectl to change a rolebinding in the cluster to
use the default "edit" ClusterRole.

It may be that our rbac file is giving users overly broad permissions in the
cluster:

https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespace-resources/01-rbac.yaml

It's hard to be confident about this, because we don't have direct access to
user-level identities.

Tasks

* Create a new github user account, using the + feature of gmail
* Create a new team in the MoJ github organisation, and add the new user
account to it.
* Set up a namespace for the new team
* See if this user can do anything in the cluster that we would prefer normal users not be able to do

NB: If the github user account(s) belong to individuals, don't forget to update
our leaver's runbook so that any such github users are removed from the MoJ
organisation in the event that the relevant person leaves.

**Comment by AntonyBishop** [comment]
Too vague. Stale ticket.
