### ISSUE TITLE
Create an alert for node disk space running out

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#157]
## Background

Part of the monitoring epic #139.

We want to alert when disk space on our Kubernetes nodes is running low so that we can add disk space.  

## Proposed user journey

- Disk space goes above a certain threshold
- The cloud platform team receives an alert 
- A team member adds disk space
- The alert stops

## Approach

The person implementing will have to decide on a starting threshold and when/where it alerts. The aim would be to give the person who picks up the alert enough time to fix it before it becomes critical. It may need two thresholds -- one which makes it a low priority and one that makes it a high priority, in case the low priority was missed.

## Definition of done

- [x] When a threshold of disk space is passed (e.g. 80% or 5 days until it fills up) an alert goes off in the appropriate channel (slack or pagerduty)
- [x] There is documentation on how to fix the problem (ie. how to add disk space to the nodes)
- [x] Someone else has tested the end to end process (disk space fills up, alert goes off, they fix the disk space)

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
Keep in mind that Docker and OS use different allocation, both need to be monitored

**Comment by jasonBirchall** [comment]
This was A LOT more complicated than first anticipated and took me a full two days to complete. 

Optimal choice was to have a directory that would be polled for when a Helm update was performed. This is possible but I haven't had the time to implement. 

After a chat with Mitch and a few of the Analytics staff (who have installed Prom before), the best option for right now is to create either a config map or prometheus rule to create the alert. 

I have chosen to use the prometheus rules as submission and deletion was a lot quicker. Instructions have been created under #58.

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-prometheus/pull/8
https://github.com/ministryofjustice/cloud-platform-prometheus/pull/7
