### ISSUE TITLE
Create and schedule a script to remind us to delete test clusters

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1571]
We create test clusters, but sometimes we forget to delete them when we're
done with them, so they just sit there costing us money.

Create a script which runs periodically, and looks for both kops and EKS
clusters, filters out the production clusters (live-1 and the manager
cluster), and posts a reminder to our slack channel.

**Comment by AntonyBishop** [comment]
Closed due to age of story
