### ISSUE TITLE
Add support for Jenkins EC2 plugin

### ISSUE THREAD

**Issue by robinsillem** [ministryofjustice/cloud-platform#1573]
## Service name

Probation Core Services

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ x] Other

N.B. These tools build artefacts that run in all the above environment types

## Impact on the service

This change allows us to do processes requiring a higher level of privilege than would normally be prermitted in the kubernetes cluster - e.g. docker build - without relaxing the security of the cluster.

## Problem description

We want the capability to run jenkins agents on ephemeral EC2 instances outside the kubernetes cluster, using the Jenkins EC2 plugin [https://plugins.jenkins.io/ec2](https://plugins.jenkins.io/ec2) . This plugin automates the launch and termination of EC2 instances as required by the workload of the Jenkins installation. 

We currently have a Jenkins master on the Live1 cluster. We expect this to remain where it is. 

To implement this request we need the following features/resources from the cloud platform team

- An IAM user with access keys, or an instance role attached to the jenkins master
- An attached policy giving permissions needed to manage AWS resources. We have this policy from the plugin documentation (see https://github.com/jenkinsci/ec2-plugin#iam-setup), but it may want tweaking to fit the CP architecture
- A private key for an EC2 key pair to be used for SSH access to the ephemeral instances
- One or more named security groups allowing the jenkins master to SSH (22) to its agents, and for the agents to access the internet with HTTP/HTTPS/SSH and to access the sonarqube deployment in the Live1 cluster
- Stated limits in terms of EC2 instance size and number of instances.
- Identified subnet where instances are to be launched

I have all this running in a combination of local minikube for the master and AWS resources in a sandpit account belonging to the Delius migration team, provisioned with some terraform code. You can take a look, but it won't copy across directly as the networking setup will be different.

## Contact person

Robin Sillem, robin.sillem@digital.justice.gov.uk

**Comment by robinsillem** [comment]
We may also want to ensure that the relevant parts of the file system of the EC2 agents is running on encrypted volumes. We havge an outstanding work item to figure out how/whether to do this via the plugin, but it may need additional changes to the security policy mentioned above. TBD

**Comment by robinsillem** [comment]
Priority: 
While we can prototype this using resources from other AWS accounts, it's not ideal. We want to be operating fully within the Cloud Platform ecosystem as soon as possible

**Comment by digitalronin** [comment]
Re the security policy at https://github.com/jenkinsci/ec2-plugin#iam-setup, we should restrict this further so that the role can only create/terminate EC2 instances with a given tag (e.g. "jenkins-agent"), and whatever other restrictions we can think of.

**Comment by robinsillem** [comment]
@digitalronin We can configure the plugin to add whatever tags suits you. Currently we have
Name: Jenkins agent
and some stuff the plugin puts in, but is probably not stable enough if we have multiple agent AMIs

**Comment by digitalronin** [comment]
The HMPPS PCS team has been disbanded, so this is no longer required.
