### ISSUE TITLE
Add another worker to Concourse in live-1

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1575]
We have increased the load on concourse in live-1. This means we need to improve the number of workers.

**Comment by digitalronin** [comment]
A lot of pipelines sit in "checking max-in-flight is not reached" for a long time, while the two workers we have are tied up with long-running jobs such as "build environments" (around 46m) and "integration tests"  (approx. 27m)

I'd suggest adding at least 2 workers, if not 3. We may also need to check that we're not hitting any namespace limits.
