### ISSUE TITLE
Update Concourse Helm repository

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1576]
We currently get the concourse helm chart from the `stable` repository : 
https://github.com/helm/charts/tree/master/stable/concourse

```  
  repository    = "stable"
  chart         = "concourse"
```
However, this repo is deprecated, the official one should be used. 
See https://github.com/concourse/concourse-chart for more info

**Comment by mogaal** [comment]
This was already fixed by me, you can check it out [here](https://github.com/ministryofjustice/cloud-platform-concourse/blob/master/resources/main.tf#L190-L193)
