### ISSUE TITLE
Spike kube-proxy-oidc for K8S for EKS

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1580]
## Background

OIDC doesn't work well for EKS. We want to spike a suitable solution. Until we have a solution we can't more fully adopt EKS.

## Approach

TBC

## Which part of the user docs does this impact

TBC

## Questions / Assumptions

TBC

## Definition of done

TBC

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
kube-oidc-proxy is not supported behind Nginx

`https://github.com/jetstack/kube-oidc-proxy/issues/9#issuecomment-471479166`

**Comment by vijay-veeranki-moj** [comment]
https://docs.google.com/document/d/15j1ptMddI5om5AS2QuU3t4ZzGf8vo8PuRo2MbCqlnKM/edit?usp=sharing
