### ISSUE TITLE
SPIKE: Change Prometheus EBS volume for a postgres db running in RDS

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1581]
We have noticed Prometheus query time is taking a large hit. 
This is due to the amount of new data we are ingesting. 

This ticket is a placeholder for a spike into using postgres on RDS instead of an EBS volume.

**Comment by digitalronin** [comment]
We may not want to do this if we plan to use thanos as a way to unify data from multiple Prometheus instances. 

See this slack thread for more info: https://mojdt.slack.com/archives/C514ETYJX/p1580203908094800
