### ISSUE TITLE
Postgres Upgrade for PQ from 9.3 to 9.6 - Post upgrade remediation

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#159]
## Background

We have successfully upgrade the PQ instances of Postgres from 9.3 to 9.6. However, we want to ensure that if PQ needs a complete rebuild that it does not try to deploy with the old version of Postgres.

## Approach

1. Investigate how PQ build and deploy jobs work
2. Identify any changes that may be required to ensure PQ doesn't rebuild with old version of Postgres
3. Test changes
4. Apply changes
5. Update documentation

You may need assistance from Daniel Penny in the PQ Team.

## Definition of done

- [x] we make the necessary changes to build and deploy jobs to ensure that PQ will rebuild with the correct version of Postgres
- [x] documentation updated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by lukaszraczylo** [comment]
Changes applied in https://github.com/ministryofjustice/parliamentary-questions-deploy/commit/ab3c6bbe0c6fa19914d9f94c469e1a2a346d44cf
