### ISSUE TITLE
Add cloudwatch datasource to grafana

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1591]
This would allow teams to use off-the-shelf grafana dashboards for monitoring,
without having to translate them to work with prometheus queries

More details in this slack thread:
https://mojdt.slack.com/archives/C57UPMZLY/p1579275395021100

**Comment by vijay-veeranki-moj** [comment]
Applied datasource for cloudwatch and also created dashboard for sqs

https://grafana.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1
