### ISSUE TITLE
Upgrade cert-manager from 0.8 to 0.14 (breaking changes)

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1596]
The main breaking change is the CRD names. Please see here:
https://github.com/jetstack/cert-manager/releases/tag/v0.11.0

This means all current resources (which we don't deploy) will need to be changed. 

Upgrade to latest release
https://github.com/jetstack/cert-manager/releases/tag/v0.14.0

We may need to back up the existing certs and apply it again if we loose the certs because of the CRD's

**Comment by vijay-veeranki-moj** [comment]
https://docs.google.com/document/d/1aj_3OHxePFl2H8MXbNQ8eLW2ZTTfn-ZZeFj2Pow8hZI/edit

cert-manager upgraded to 0.14 version.
