### ISSUE TITLE
Create a local, full, up-to-date backup of the rattic DB

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform#16]
This should be created using the root login created in [issues/14].  It is intended to be used as the main source when creating the Keeper import scripts.  

It should always be stored securely.

**Comment by razvan-moj** [comment]
Through the available API ( accessible at https://rattic.service.dsd.io/api/v1/?format=json), we can read secrets, groups and tags, but not users nor the relationship between user->group->secret so a translation via the API is not possible; we will need to obtain at least read access to the SQL database.
