### ISSUE TITLE
Deploy alertmanager

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#160]
## Background

Part of Epic #139

In order to notify based on prometheus alerts, we will be deploying `alertmanager`.

## Proposed user journey

- Cloud platform team member wants to set up `alertmanager` on the cluster
- Cloud platform team member goes to documentation on how to setup `alertmanager`
- They run the script or job that is specified in that documentation, providing any config that is specific to the cluster (i.e. secrets, names etc)
- When the job is finished they can test that `alertmanager` is up and running by e.g. navigating to a dashboard

## Approach

We want to deploy an alertmanager instance using the prometheus operator. We will be using the prometheus-operator `Alertmanager` CRD.

## Questions / Assumptions

The prometheus operator has been deployed (part of #144)

## Definition of done

- [x] An instance of `alertmanager` has been created in the `monitoring` namespace, using the operator CRD.
- [x] `alertmanager` has been configured to integrate with the prometheus instance (configured on the prometheus side) and create alerts in PagerDuty (bonus: would be nice to use [this](https://www.terraform.io/docs/providers/pagerduty)).
- [x] The `alertmanager` web ui is not exposed through the ingress controller. A user can reach it using `kubectl port-forward`.
- [x] The resources created in the steps above are managed in the environments repo.
- [x] There is documentation that lists all the steps that a Cloud platform team member needs to go through in order to setup alertmanager on a cluster.
- [x] Tested by installing on a cluster that has no existing `alertmanager` resources defined on it (a new cluster or one where `alertmanager` has been cleaned up)

## Reference

https://github.com/coreos/prometheus-operator/blob/master/Documentation

**Comment by sablumiah** [comment]
Manifest files for alertmanager are held in the kube-prometheus values.yaml file. Which will be held the following repository:
https://github.com/ministryofjustice/cloud-platform-prometheus

**Comment by sablumiah** [comment]
alertmanager installed and can be access using kubectl port forward:
➤  kubectl port-forward -n monitoring alertmanager-kube-prometheus-0 9093

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-prometheus/pull/4

https://github.com/ministryofjustice/cloud-platform-prometheus
