### ISSUE TITLE
Create a runbook for applying terraform code to live-1

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#1600]
There are several placed of runbook we might have to say apply terraform code to live-1. 

Create a runbook documenting the steps required. Also check if the steps differ in anyway when applying to different folders of cloud-platform-infrastructure.

- [ ] readme has been updated
- [ ] runbook have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Closed due to age of story
