### ISSUE TITLE
Notify users for manually created resources instead of using the environment repository.

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#1604]
Create an automated task to scan for manually created resources with more than a week older. The task will run against live-1 and will also notify the users/teams with a reminder about best practices and keep in sync with the environment repository

* Certificates
* Prometheus rules

**Comment by AntonyBishop** [comment]
We encourage but don't enforce this. Close.

**Comment by davidread** [comment]
We advise these to be in environment repo, for DR. However now we have Velero, so it's not a big deal. Putting it in environment repo is not enforced, so can't really do these checks.
