### ISSUE TITLE
Add an article on jobs to the user guide

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1605]
Things to tell users, with examples and links to external documentation:

* Jobs can be interrupted at any time, and may be restarted on another node, so write them accordingly.
* How to configure a job so that its pod gets cleaned up after the job finishes.

**Comment by davidread** [comment]
Removed bit about poddisruptionbudgets - @jasonBirchall says that makes our life harder

**Comment by AntonyBishop** [comment]
Closed due to age of story
