### ISSUE TITLE
Modify the "orphan namespace" checker to ignore concourse namespaces

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1608]
The concourse namespaces are defined in the concourse repo, not the
infrastructure repo. So the checker (which looks through the infrastructure
repo source code) thinks they're orphans.

Modify the checker so that it also checks the concourse repo for namespace
definitions.

**Comment by davidread** [comment]
Concourse is now in manager, so it's not a problem any more
