### ISSUE TITLE
Create an "Unprivileged User" for the Cloud Platform testing

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1609]
## Background

In many stories we would benefit from having a "user account" that has the same characteristics and privilege as a normal user.

This will enable us to improve our ability to test new features and get the same outcomes as a normal user.

This is particularly useful in our GitOps work.

## Approach

Create a normal user account that we can use.

## Which part of the user docs does this impact

N/A - Maybe some detail in our Runbook?

## Definition of done

- [x] User created
- [ ] Add to MoJ github organisation
- [ ] Add to a github team within the org
- [ ] Test that user can only do things a normal user should be able to do

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
I've created a github user called `cloud-platform-dummy-user` (details in our password manager).
This user needs to be added to the MoJ organisation, and to a team, by someone with admin access to our github account.
