### ISSUE TITLE
Expose prometheus and alertmanager web ui

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#161]
## Background
Depends on #144 and #160

## Proposed user journey

- The user needs to use to the `prometheus` or `alertmanager` web ui.
- The web ui is available at a public, authenticated, TLS endpoint.

## Approach

Expose the web interfaces for both service by using one of the available OIDC auth proxys. We want to use OIDC and auth0 to keep it consistent with how we've implemented authentication in kubernetes.

The are some related projects in the References section below; this story will be partly discovery. We should choose the easiest solution to implement. 

## Questions / Assumptions

Both `prometheus` and `alertmanager` have been deployed and are accessible by `kubectl port-forward`.

There is an auth0 application for the cluster which we can re-use here.

## Definition of done

- [x] the web interface for both services is available on a public, secure endpoint (eg. `https://prometheus.cluster.domain.io`)
- [x] the web interface is only available to members of the WebOps team in the GitHub organisation.
- [x] any configuration for the above is managed in the environments repository.
- [x] there is documentation on how to setup the above on a new cluster. 

## Reference
- https://github.com/mozilla-iam/mozilla.oidc.accessproxy
- https://github.com/evry/docker-oidc-proxy
- https://github.com/Tecsisa/foulkon

**Comment by ollieanwyll** [comment]
https://coreos.com/operators/prometheus/docs/latest/user-guides/exposing-prometheus-and-alertmanager.html

**Comment by jasonBirchall** [comment]
This ticket has turned into discovery. After a chat with Kerin and Mitch it was agreed that auth doesn't exist natively for Prometheus and AlertManager. Will need to 'investigate' possible solutions only.

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-prometheus/pull/13
