### ISSUE TITLE
Create runbook for how to run a load test on a test cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1610]
## Background

As a pre-requisite #1593 we need to know how to run a load test on a test cluster. We have done this before but we have no documented runbook.

This story is for creation of a runbook.

## Approach

Create runbook.

## Which part of the user docs does this impact

N/A - Runbook site

## Definition of done

- [ ] Runbook created
- [ ] test the runbook

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
Ticket closed until we have a test case for how and when you need to load test cluster
