### ISSUE TITLE
Get teams to migrate build jobs off hosted Jenkins and kill it

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1615]
We have at least one instance of Jenkins running in the moj-dsd AWS account.

This hasn't been patched/upgraded for years, but we believe one or more teams
are still using it for their build pipelines.

We need a plan for getting teams to migrate their build jobs to some other
service (probably circleci, by default).

* Audit the jenkins instance, and find out who is using it, and for what
* Contact the relevant teams and help/encourage them to migrate elsewhere
* Pick and announce a shutdown date for the hosted instance
* Kill it

**Comment by pwyborn** [comment]
See [Jenkins template-deploy box seems to be not working#2038](

**Comment by pwyborn** [comment]
Remaining:

Ultimate decision as to whether to try to revive https://ci.service.dsd.io/ or not (think only cla were still using)?. I have given the cla team advise how to run a deploy themselves with a fab command - however I know from experience getting the right virtual environment - is notoriously difficult - and deployments will probably fall to me.

The hmcts jenkins jobs utilise template-deploy on their own https://ci-hmcts.service.dsd.io/. I believe that it is only a matter of time before the same fate awaits theirs. Should we issue a final warning and wash our hands of it?

**Comment by digitalronin** [comment]
> Should we issue a final warning and wash our hands of it?

Absolutely, yes IMO. We've given teams many, many warnings about this, and we can't go on patching up zombie technology - it's a distraction, and it's utterly wasted time. If this is the only way we can get teams to take this bit of technical debt seriously, I think that's exactly what we need to do.

**Comment by pwyborn** [comment]
This was all pre-empted by the instance for our ci-service - becoming unusable.
Unable to recover it.
AWS resources for our ci-service removed. If it needs to be revived -we will need to rebuild the stack
ci-hmcts-service remains - it is template-deploy. However we no longer support it (hmcts does). Their jobs were migrated over onto this.
Think that there were only cla jenkins jobs left. They are going to try to deploy themselves from the commandline

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/jenkins-jobs - archived
