### ISSUE TITLE
Shut down any instances of docker registry in the moj-dsd AWS account

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1616]
We have at least one docker registry instance running in the moj-dsd AWS
account, which some teams may be using as a part of their build pipelines.

We should shutdown any such instances, and get teams to use a managed service
to host their docker images (either ECR or Docker Hub).

* Find out which EC2 instances are being used as docker registries
* Audit the registry instances, and find out who is using them, and for what
* Contact the relevant teams and help/encourage them to migrate elsewhere
* Pick and announce a shutdown date for the hosted instances
* Kill them

**Comment by AntonyBishop** [comment]
Done
