### ISSUE TITLE
Fix the tzcronjob integration test, for test clusters

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1618]
The tzcronjob integration test works fine in live-1, but fails in any test
clusters (we tried three different test clusters on 28/01/20 - all had the
same problem).

AFAICT, everything looks like it should be working fine (the CRD is in place,
and the TZCronJob object is created), but the actual job never 'fires'

For now, this test has been tagged as 'live-1 only', but it ought to be
working. AFAIK, nobody is actually using tzcronjobs in live-1 right now, so
one possible workaround is just to remove the capability altogether.

However, it's probably worth putting in some (timeboxed) effort into
figuring it out, in case it's a symptom of something important.

```
Failures:
06:27:06
	
1) tzcronjobs job is scheduled
   Failure/Error: expect(pod).not_to be nil
   
     expected not #<NilClass:8> => nil
              got #<NilClass:8> => nil
   
     Compared using equal?, which compares object identity.
   # ./spec/tzcronjob_spec.rb:30:in `block (2 levels) in <top (required)>'
```

Potential solutions :

Increase the delay in the test.
See if Tzcronjob depend on anything

**Comment by AntonyBishop** [comment]
No longer used
