### ISSUE TITLE
Spike using AWS Secrets Manager with Concourse

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1619]
Currently, we use Kubernetes secrets to store our concourse credentials etc. I suggest we try and use AWS Secrets Manager as an alternative. 

https://github.com/helm/charts/blob/master/stable/concourse/values.yaml#L356
https://concourse-ci.org/aws-asm-credential-manager.html

**Comment by poornima-moj** [comment]
https://github.com/concourse/concourse/issues/3023
