### ISSUE TITLE
Create an automated process for enforcing Manual DB snapshot limits

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1628]
We have a limit on how many manual DB snapshots we can have in our AWS account
as a whole. We have asked AWS to raise this several times, but no matter what
the *value* of the limit is, manual DB snapshots are a limited, shared resource,
and so we need to manage them to ensure teams can take a snapshot when they
need to.

Automated snapshots are limited to one per day, with a fixed retention period,
so teams need to be able to take snapshots according to their own requirements,
but we need to know in advance what those requirements are, and take action
if they are exceeded.

* Define a config file in a source repo which contains the agreed limits on number of manual snapshots for each team
* Create a regular job which compares the config file to the manual snapshots which exist
* Post to #cloud-platform-notify if a teams is nearing/exceeding their limit

**Comment by imran-awan1** [comment]
The feature has been demonstrated to wider team. 
Refactoring the code to potentially converting from python to Ruby is a further enhancement which woud be a new ticket.
