### ISSUE TITLE
Enhance Horizontal Pod Autoscaler article in user guide

### ISSUE THREAD

**Issue by poornima-moj** [ministryofjustice/cloud-platform#1630]
Add more description about how HPA can be used to save us money by scaling down non-prod environments, and also to have examples of how to use custom metrics (especially traffic) as the basis for HPA to take action.

## Definition of done

- [x] user docs have been updated
- [x] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-moj** [comment]
This needs installing Prometheus Adapter for HPA to collect custom metrics from Prometheus. https://github.com/helm/charts/tree/master/stable/prometheus-adapter. But supported only after K8o version 1.14+. 

Will restart after the upgrade work is completed.

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/327
