### ISSUE TITLE
Create "Starter Pack"

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1631]
**should include:**

- Hello World App with an Ingres rule
- Two different versions of the multi-container app (one with RDS. one with Postgres container) (optional)
- Test data
- Add tests to validate that starter pack is functioning as expected.
- Enable multiple copies of apps

**Questions:**
Should Starter Pack should be a TF module?
Will need to break down further
What tests do we need?

**Comment by poornima-moj** [comment]
- deploy hello world app
- deploy multi container app

- smoke test for hello world app and multi container app
