### ISSUE TITLE
Enable admissionWebhooks for prometheusOperator 

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#1633]
We upgraded to latest Prometheus operator 8.7.0 , but coudn't endable the admissionWebhooks 

As it is failing with below error 

```Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prometheus-operator-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)```

This may be to do with the network policy we have in monitoring namespace.

Some issue related to this
https://github.com/coreos/prometheus-operator/issues/2711

**Comment by sablumiah** [comment]
After investigating this its been concluded that thos feature does not work for us as we have network policies being used in our namespaces, namely the monitoring namespace.

To test this, if all NP are removed from the monitoring namespace, the feature works fine and the install of Prom-operator also succeeds. If our default NP (no access from outside the namespace) is enabled the install fails. 

A new NP allowing kube-system namespace access makes the feature work intermittently. Installs still fail with a timeout of access to the validatingwebhook. However, if prom-operator is installed, and the new NP is enabled, if a new Prom rule is retired a number of times, it eventually succeeds. Trying the same on a different namespace again fails. unless you try a number of times until success. One successful that rule seems to work continuously.

Investigating this, there are a number of solutions for GKE where you need to add a firewall rule from the control pane to monitoring namespace, this is the same as I have done above. All other suggestions when having issues installing prom-operator is to just disable the webhook.
