### ISSUE TITLE
Fix broken unit tests in the Cloud-platform-env repository

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1634]
Currently the env repository has a number of ignored integration tests. Alot of these are from the gitops refactoring work but there may be others. 

Definition of done
- when all tests are working or deemed appropriate to remove.

**Comment by pwyborn** [comment]
<b>integration Tests currently running in pipeline:</b>

- <b>Kops:</b>

  - integrationtest-dns
  - integrationtest-kiam
  - integrationtest-modsec
  - integrationtest-psp

- <b>EKS:</b>

  -  integrationtest-psp

<b>Potential?:</b>
  - alertmanager_spec.rb
  - authorized_keys_spec.rb
  - cert_manager_spec.rb
  - certificates_spec.rb
  - concourse_spec.rb
  - crds_spec.rb
  - daemonsets_spec.rb
  - docker_registry_cache_spec.rb
  - external_dns_spec.rb
  - ingress_controller_spec.rb
  - ingress_spec.rb
  - issuers_spec.rb
  - kiam_annotations_spec.rb
  - kiam_spec.rb
  - logging_spec.rb
  - master_nodes_spec.rb
  - modsec_spec.rb
  - namespace_annotations_spec.rb
  - namespace_labels_spec.rb
  - namespace_spec.rb
  - prometheus_crd_spec.rb
  - prometheusrules_spec.rb
  - psp_spec.rb
  - servicemonitors_spec.rb
  - spec_helper.rb
  - starterpack_spec.rb
  - tzcronjob_spec.rb

**Comment by jasonBirchall** [comment]
Just for clarity, this issue refers to the tests in the cloud-platform-environments repository, not the cloud-platform-infrastructure.

**Comment by pwyborn** [comment]
Sorry started off by looking at integration tests:

Then looked at:
https://github.com/ministryofjustice/cloud-platform-environments/tree/main/spec

![Screen Shot 2021-06-02 at 10.47.31.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/b060db11-1f08-43d1-8bbf-3260a79a19e4)

![Screen Shot 2021-06-02 at 10.50.48.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/05f646b7-6b37-45f1-972c-f906e53ab1b7)

https://github.com/ministryofjustice/cloud-platform-environments/pull/4874

**Comment by pwyborn** [comment]
![Screen Shot 2021-06-02 at 12.19.48.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/4de6ad39-fb62-40aa-932c-9a6e0b5ad82b)

**Comment by pwyborn** [comment]
Will consult @jasonBirchall's after his A/L as tests seem to be passing for me (I may be interpreting the problem)

**Comment by pwyborn** [comment]
Checked whether any "x"'d out (pending/skipped) tests:
