### ISSUE TITLE
Upgrade `kube-state-metrics` to latest when kube_namespace_annotations is enabled

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#1637]
Now, Prometheus is upgraded to the latest version, but kube-state-metrics sub chart latest version removed  `kube_namespace_annotations` metrics. So we downgraded the version to v1.7.0 to use kube-state-metrics as some users and cloud-platform set up alerts using `kube_namespace_annotations`

```
kube-state-metrics:
  image:
    tag: v1.7.0
```

There is an issue raised to fix this
https://github.com/kubernetes/kube-state-metrics/issues/941

Once this is available, we need to upgrade to use the latest image.
Upgrade to v2.2.0

Definition of done:

Existing alerts work as expected and "kube_namespace_annotations" work as well, as our (cloud-platform) team is using it in application alerts.

**Comment by AntonyBishop** [comment]
Reviewed. Issue still unresolved so story is still blocked.

**Comment by AntonyBishop** [comment]
Reviewed. Issue still unresolved so story is still blocked.

**Comment by AntonyBishop** [comment]
Reviewed. Issue still unresolved so story is still blocked.

**Comment by AntonyBishop** [comment]
Reviewed. Issue still unresolved so story is still blocked.

**Comment by davidread** [comment]
Important not to forget to unpin this tag when the issue mentioned is resolved

**Comment by vijay-veeranki** [comment]
Comment here says this is not fixed in release v2.2.0

https://github.com/kubernetes/kube-state-metrics/issues/941#issuecomment-915880754

**Comment by vijay-veeranki** [comment]
kube-state-metrics is failing in "live" cluster as it is running on K8's 1.19.

Removed blocked on this issue and move to this sprint to work on this.

**Comment by vijay-veeranki** [comment]
Upgraded EKS Prometheus to latest version.
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1419
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/111
