### ISSUE TITLE
Add kibana auth to the cloud-platform-components

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1638]
This was previously in environments repo but this had to be removed. 

Please see https://mojdt.slack.com/archives/CH6D099DF/p1581087696026100 for background in why it needed to be removed.

**Comment by jasonBirchall** [comment]
This was removed from the env repo here: 
https://github.com/ministryofjustice/cloud-platform-environments/pull/1896

**Comment by AntonyBishop** [comment]
No longer required

**Comment by davidread** [comment]
It was added to infrastructure as a component
