### ISSUE TITLE
build-environments job: run on all environments and prune

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#164]
Depends on #180
Depends on #88

## Background
Currently, the `build-environments` job is triggered by webhook and applies only the changed files.

The pipeline should additionally run on schedule (eg. every 15m) and apply files on *all* environments across all managed clusters.

With this approach, the environments repository becomes the source of truth for the state of the cluster.

## Approach

Add a `time` resource in the pipeline that triggers the full run periodically. It goes through each environment (namespace) in each cluster and applies the managed resource files.

For `kubectl`, we should also use `--prune` which means it will clean up any resources not declared in the git repository. This makes its behaviour akin to `terraform`. This must be a behaviour that can be disabled by the owner of the environment, since they might be using external means of managing resources. Recommended approach: using an annotation on the namespace resource.

## Definition of done

- [x] The webhook runs against everything, not just changes
- [x] The pipeline is configured to run every 15 minutes, additionally to the webhook-triggered runs
- [x] The two different invocation types should not run in parallel to avoid conflicts
- [x] When the pipeline is invoked every 15 minutes, it should apply all the files from the master branch, across all namespaces and clusters

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tatyree** [comment]
After discussion, we've agreed that the webhook should run for everything, not just changed files.
