### ISSUE TITLE
Create a runbook on how to delete Elasticsearch log.

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1641]
In some situation, we want to be able to go through the ES logs and delete some data. 

There are two possible ways :
 - Curator job, with custom filter
 - An API call (`curl`) 

Figure out which way is simpler and document it in a runbook.

**Comment by digitalronin** [comment]
Given we have an index per day, and we (currently) keep 30 days, I'd probably look at doing this by building up a set of curl shell commands - one for each day.

Once we've got that, we can choose to automate further, or not.

**Comment by mtrbls** [comment]
Update : using curator is not possible. We have to delete through the API.
https://www.elastic.co/guide/en/elasticsearch/client/curator/current/faq_partial_delete.html
