### ISSUE TITLE
How to assume role with Kiam?

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1649]
We need a user-guider on how to use Kiam, from the perspective of service teams.

This needs to includes : 
 - Namespace annotations
 - Potentially the role creation with terraform 

Links :
https://www.terraform.io/docs/providers/aws/r/iam_role.html
https://github.com/uswitch/kiam#overview

**Comment by digitalronin** [comment]
@mtrbls Are any teams using kiam in this way?

**Comment by AntonyBishop** [comment]
Closed. Not used by anyone.
