### ISSUE TITLE
Should teams be able to create Roles and Policy?

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1652]
It is currently possible for teams to create roles in CP, via terraform. 
We have just enabled policy creation : https://github.com/ministryofjustice/cloud-platform-concourse/pull/193

In other words, PR reviews are the only things controlling access to AWS.
Example : https://github.com/ministryofjustice/cloud-platform-environments/pull/1912

There should be a discussion on the security implications of this.

**Comment by davidread** [comment]
We want to allow it, rather than restricting users to just our terraform modules

We need to make double sure that unneeded extra permissions are given e.g. to other tenants' resources. The review by CP team needs extra care. Suggest a GH Action that highlights the extra risk to the reviewer.
