### ISSUE TITLE
Update our User Guide Documentation around Logging to make sure that users understand that Kibana is open to all Service Teams

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1654]
## Background

Following a recent incident we have to make Kibana unavailable to all Cloud Platform User.

Following a retrospective of the incident I wanted to check that our documentation made clear that Kibana is a shared resource and that teams should be aware of this.

The guidance doesn't make that clear so teams may not be aware of this when making decisions around their logging.

## Approach

Add something to the existing guidance that states that Kibana provide access to logs for all teams and they they should be aware of this when determining what gets put into logs. 

Maybe we should include a link to any standards around what is appropriate to be logged (if that exists).

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/logging-an-app/access-logs.html#accessing-application-log-data

## Questions / Assumptions

Check to see if guidance exists about what data is appropriate for logs.

## Definition of done

- [ ] documentation is clear that Kibana is a shared resource.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
This is blocked as waiting for the Standards as it is still being agreed at the moment.

**Comment by digitalronin** [comment]
I think we can still write a general piece for the user guide, warning of the specific issue that other teams can see whatever you log. We can add a general point about being careful what you put in your logs, and we can update that as and when we have more specific guidance.

**Comment by AntonyBishop** [comment]
Done
