### ISSUE TITLE
SPIKE: Service Account Token Rotation Policy 

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#1662]
Matt Whittaker raised a question in ask regrading token rotation policy for service accounts.
This ticket is to look into a policy to auto rotate tokens for all service accounts at a set interval 

Currently the CircleCi SA is a manual step and we possibly need to look into a way to `fix` how these are created if we will have one solution for all SAs  

Definition of done:
- [ ] we understand what SAs exist
- [ ] We identified how those SAs would be rotated
- [ ] Can we cycle a token other than by deleting it

**Comment by vijay-veeranki-moj** [comment]
https://docs.google.com/document/d/1BhzUZieO835-YHjJC3se73mTR8vnM57TVqzRwUQBcjs/edit?usp=sharing
