### ISSUE TITLE
Form Builder Pingdom integration

### ISSUE THREAD

**Issue by asmega** [ministryofjustice/cloud-platform#1663]
## Service name

Form Builder

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

n/a

## Problem description

For Creating Pingdom checks we require an `integrationid` according to the docs https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#creating-pingdom-checks

Below is the requested info:

team name: `formbuilder`
application name: `Form Builder` (feel free to snake/camel/hyphenate if needed)
slack channel: `#form-builder-alerts`
slack webhook can be found at: https://mojdt.slack.com/services/BU35WSL20

## Contact person

Phil Lee (Me), Tomas Destefi, Brendan Butler

**Comment by pwyborn** [comment]
24/02/2020 paulwyborn  9:43 AM
Tomas - Regarding your ticket:
https://github.com/ministryofjustice/cloud-platform/issues/1663
id is
#integration=xxxxxx
is this ok? Think Phil Lee raised this ticket

Tomas Destefi:house_with_garden:  9:44 AM
Hi Paul, I think this is okay, I will confirm later today as we on the form builder have some questions regards to pingdom/form builder integration


paulwyborn  9:45 AM
ok - thanks Tomas
