### ISSUE TITLE
Investigate jetstack/preflight

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1664]
Preflight is a tool to validate a cluster, after its creation. 

https://github.com/jetstack/preflight  

Questions :
 - Could preflight benefits us ?
 - Does it overlap with our integration tests ? 
 - Can it work on both our Kops and EKS clusters ?

**Comment by jasonBirchall** [comment]
Report here: https://docs.google.com/document/d/1hYt9gWZh4j16dnk-OBmgqqD4NKiJkm8X-xjQiT6bZOY/edit?usp=sharing

At this present moment in time the application is in private beta so it would be wise to leave this for now.
