### ISSUE TITLE
Add a section to our user guide about RDS & GDPR

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1665]
See this slack thread: https://mojdt.slack.com/archives/C57UPMZLY/p1582020059355800?thread_ts=1582020036.355300&cid=C57UPMZLY

Most services will need to answer these questions at some point, so if we can
put together a document containing standard answers, we'll save a lot of their
and our time.

**Comment by AntonyBishop** [comment]
Closed due to age of story
