### ISSUE TITLE
Spike: Migration of HMCTS Jenkins jobs to ci-hmcts

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1667]
## Background

Paul is reviewing unused Jenkins jobs to determine what we can decommission.

We have identified some HMCTS CI jobs that may still be needed and could be migrated to their Jenkins instance.

![image.png](https://images.zenhubusercontent.com/5ca4cae5c8e4713758aa985f/3117b586-2730-4409-a786-605d35fcbe74)

We are unsure of how much effort might be required and whether it is worth doing that.

This story is to review that position and see whether it is worth migrating these jobs.

## Approach

TBC

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- [ ] How much effort is required for this activity
- [ ] What is the split in responsibility between CP and HMCTS for this task.

## Definition of done

- [ ] We have confirmed whether it is worth migrating the CI jobs.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
The Jenkins jobs - have been created. However there are wider ranging problems with python/pip installations - which I do not think is our job to support/fix. Therefore deploy jobs are failing.
It should also be noted that if this instance is switched off - then cron backup jobs will no longer run - which may have implications for hmcts
