### ISSUE TITLE
Hide Terraform logs for plan and apply pipeline, to add grep

### ISSUE THREAD

**Issue by pwyborn** [ministryofjustice/cloud-platform#1669]
## Service name

Terraform

## Service environment

- Live 1

## Problem description

It was found when working on ticket [Document use of the postgres_exporter#938](https://app.zenhub.com/workspaces/cloud-platform-team- 5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/938) that rds secrets/credentials were revealed in the terraform logs for rds test databases. 

Look into fixing this problem maybe with grep:
```
  def tf_plan
    cmd = tf_cmd(
      operation: "plan",
      last: %( | grep -vE '^(\\x1b\\[0m)?\\s{3,}'),
    )
```
## Contact person
Paul Wyborn

**Comment by AntonyBishop** [comment]
Spike tfmask

**Comment by pwyborn** [comment]
https://github.com/hashicorp/terraform/issues/516

**Comment by pwyborn** [comment]
The findings of this spike is that tfmask does not function as expected (it does not work)
