### ISSUE TITLE
Update Node runtime on Auth0

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform#167]
Our Rules setup on Auth0 uses the deprecated Node 4 runtime|:

https://manage.auth0.com/#/rules

It needs to be updated:

https://auth0.com/docs/migrations/guides/extensibility-node8

Done when:

* The updated is complete and the deprecation warning on the rules page goes away.

**Comment by tatyree** [comment]
Support for Node 4 ended on 2018-04-18

**Comment by AntonyBishop** [comment]
No able to action.
