### ISSUE TITLE
Create a module for creating IAM role for accessing cross account resources

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#1671]
Currently Cloud Platform has a file in infrastructure repository for roles which needs cross account access.
https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/master/terraform/cross-account-IAM

Create a module for this which can be called from the same folder.

## Which part of the user docs does this impact

Update user guide for how to use the module to create IAM roles.

## Questions / Assumptions
Pros and cons of creating this as a module
Is it worth creating this as a module as this will change list of files in a folder to list of folders each per namespace?

The policy statement which has required permissions for that role differ for each team. Should this be passed as a json?

## Definition of done

- [ ] module created as seperate repo
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Closed due to age of story
