### ISSUE TITLE
Move cross account IAM roles to environment repo

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#1672]
Cloud Platform has placed some IAM roles created for service teams which needed cross account access inside [infrastructure repo](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/master/terraform/cross-account-IAM)

Some other IAM roles and IAM users are created in the [environment repo](https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/live-1.cloud-platform.service.justice.gov.uk/probation-core-services-tooling/resources/cprole.tf)

[namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-data-compliance-preprod/resources/iam.tf](namespaces/live-1.cloud-platform.service.justice.gov.uk/prison-data-compliance-preprod/resources/iam.tf)

- List all the IAM roles and users created to support this cross account resource access and that are not linked to any of the cloud platform modules
- Discuss with team the best way to create these IAM users and roles.
- Move the IAM roles and users to the decided repo after confirming with users

Questions:
Does concourse need additional permissions to create the role/user?
Does concourse support the naming conventions used for IAM role and users? 

## Definition of done

- [ ] user able to perform the same actions after moving the role to env repo
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-moj** [comment]
This team has a IAM role created in CP which might not be needed and can be created in the target account. Check with team whether they have access to target AWS account to create an IAM role there and to assume Role to the target AWS resource.

**Comment by AntonyBishop** [comment]
Relates to #1671

**Comment by AntonyBishop** [comment]
Closed due to age of story
