### ISSUE TITLE
AWS Transit gateway

### ISSUE THREAD

**Issue by robinsillem** [ministryofjustice/cloud-platform#1675]
We would like the Cloud Platform team to build the following:

- A shared Transit Gateway accessible to a number of AWS accounts, together with routing to VPC CIDRs and attachment request acceptances
- A common pattern and process for application services to request IAM roles capable of cross-account role assumption

## Service name

Many. Services present and future that need to be connected  to Delius environments

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

HMPPS services hosted in Cloud Platform need direct network connectivity to Delius accounts/VPCs in AWS. Without this they cannot progress with extending and refactoring Delius towards a microservice architecture

## Problem description

See https://dsdmoj.atlassian.net/wiki/spaces/NDSS/pages/1708294244/Cloud+Platform+-+Delius+connectivity+proposal for details

The Delius AWS accounts to be connected are a subset (to be confirmed) of those listed in https://dsdmoj.atlassian.net/wiki/spaces/DAM/pages/721649719/Environments+VPCs+and+AWS+accounts 

## Contact person

Robin Sillem, robin.sillem@digital.justice.gov.uk

**Comment by digitalronin** [comment]
We have a new AWS account to host this transit gateway: 

aws+cloud-platform-transit-gateways@digital.justice.gov.uk

Details in Lastpass.
