### ISSUE TITLE
Create a runbook for manually creating new DB instance from a RDS snapshot 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#1680]
Users sometime ask to copy a prod/non-prod data to another RDS instance for testing. This involves creating a new db instance from another RDS db snapshot and matching all other parameters like vpc, network and security group.

Create a runbook explaining the steps needed to do manually.

## Definition of done

- [ ] runbook has been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Closed due to age of story
