### ISSUE TITLE
Confirm if guardduty is active in eu-west-2

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1683]
It's not completely clear whether guardduty is alerting us to incidents for
resources located in eu-west-2.

Test this by:

* creating an EC2 instance in eu-west-1
* running an attack toolkit on it to try to trigger the "ssh bruteforce" guardduty alert

Provided that works, and you can see the alert from guardduty, repeat in
eu-west-2 and see if we get the same alert

**Comment by pwyborn** [comment]
Could not actually get ssh-brute-force to work utilising various hacking packages
Therefore changed tack to manually implement GuardDuty in the London AWS region of our moj-cp AWS account (in addition to existing Ireland AWS region of our moj-cp account).

Confirmed that specific (non global) AWS resources were not being picked up

**Comment by pwyborn** [comment]
As a stretch 
Decided to implement GuardDuty via Terraform config:

Some problems re existing member accounts where actual AWS accounts had beed removed (credentials no longer valid - therefore could not remove the member in GuardDuty).
Had to do a "terraform state rm" for these

Config and apply complete - new alerts coming up

Config for pagerduty alerting implemented and tested  (high severity only will alert us in slack)

GuardDutyREADME.md removed runbook created - see https://github.com/ministryofjustice/cloud-platform/pull/1728

Actual Config changes - see https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/629
