### ISSUE TITLE
Add an integration test to check that necessary labels exist on system namespaces

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1684]
e.g. there is a label on kube-system which allows DaemonSet pods to be deployed. This label went missing, at some point, and we didn't notice. This seems to be the cause of this incident:
https://mojdt.slack.com/archives/C514ETYJX/p1582628309085600

    kubectl label ns kube-system openpolicyagent.org/webhook=ignore
    kubectl label ns opa openpolicyagent.org/webhook=ignore

**Comment by jasonBirchall** [comment]
Already complete.
