### ISSUE TITLE
Tagging Tidy Up

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#169]
## Background

Last sprint an issue was identified in that AWS Portal was missing some tagged items (MTP and PVB). It appears that this was the case as values it uses to search are case sensitive. This was resolved by changing the case. The portal then was able to identify the products based on the tags.

However, while investigating it was identified that the case used for tagging the list of values below was inconsistent i.e. a mix of cases.

We need to ensure tag format is consistent so that tagged items can be identified.

## Approach

We need to review existing tags, identify differences in case for the tagging values:

- business-unit
- component 
- infrastructure-support 

Determine the case the tag should be in (in line with standard).

Then update tags accordingly.

## Questions / Assumptions

We will use the MoJ Tagging policy - https://ministryofjustice.github.io/technical-guidance/standards/documenting-infrastructure-owners/#tagging-your-infrastructure

## Definition of done

- [x] existing tagging reviewed
- [x] tags updated and consistent

**Comment by pwyborn** [comment]
Done as at 20/06/2018
