### ISSUE TITLE
Close the AWS LAALAA account

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1691]
Obtain the AWS root credentials for moj-laalaa and close the account. 

TAM informs us this account can only be closed with root account.

Convo thread here:
[200~https://mojdt.slack.com/archives/C57UPMZLY/p1579097162096000]

**Comment by AntonyBishop** [comment]
Awaiting to hear back on options from AWS TAM

**Comment by AntonyBishop** [comment]
AWS Fixing MFA on the account so that we can reset the password.

**Comment by pwyborn** [comment]
Unable to delete the account myself - however was able to delete all resources within it

**Comment by AntonyBishop** [comment]
Issue stale. Account incurs no costs. Will revisit when reviewing account audit.
