### ISSUE TITLE
FIREBREAK Idea: Try out spinnaker

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1693]
Spinnaker is an open source, multi-cloud continuous delivery platform for releasing software changes with high velocity and confidence.

Build a pipeline that performs one of our concourse tasks in spinnaker and report back ease or trouble you experienced.

Perhaps try this:
- install spinnaker in a cluster
- have spinnaker implement an eks cluster with our current eks spec
- use spinnaker to deploy the helloworld application and try different deployment techniques such as canary.
- report back.

**Comment by vijay-veeranki-moj** [comment]
https://docs.google.com/document/d/1Q7aaM-BtHQfhjCly6Y5R8wFRCVrWU3nWPREnlNT2hgQ/edit#

Findings in this document
