### ISSUE TITLE
new alert route in Alertmanager

### ISSUE THREAD

**Issue by mattops** [ministryofjustice/cloud-platform#1694]
As per https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-slack-webhook-and-amend-alertmanager

Please setup:

namespace: check-my-diary-prod
team name: check-my-diary
application name: check-my-diary
slack channel: check-my-diary-alerts
kubernetes secret name where the webhook url is stored: slack-webhook
severity level: warning and information (one of each please).

**Comment by vijay-veeranki-moj** [comment]
Created slack-webhook for check-my-diary-alerts

severity level: 
   warning : check-my-diary
   information : info-check-my-diary
