### ISSUE TITLE
FIREBREAK idea: Create instance group of spot instances

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1699]
Create a kops instance group that only uses spot instances. Aleternately, create an instance group of spot and on-demand instances. 

https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#creating-a-instance-group-of-mixed-instances-types-aws-only

**Comment by sablumiah** [comment]
Spot instances are fully supported by kops and worls really well by creating a new instance group
https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#creating-a-instance-group-of-mixed-instances-types-aws-only

I would say the best use case for us is to use spot instances for all test clusters 

Things to think about:
What spot instance conditions will we use?
Lowest cost? - https://aws.amazon.com/ec2/spot/pricing/
which instance types?
capacity optimised?
highest price? - https://aws.amazon.com/ec2/spot/pricing/
Should we mix ig with on-demand and spot?
