### ISSUE TITLE
FIREBREAK Idea: Revist AWS Service Operator

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1700]
This was previously investigated a year ago and deemed too early for adoption. Please revist and create a demonstration to present back to the team. 

https://github.com/aws/aws-service-operator-k8s

**Comment by vijay-veeranki-moj** [comment]
https://docs.google.com/document/d/1zPl3WxQZWAuF4JhOmA_TijrBFNsRQ_Bm7MmQeNhWJ8k/edit?usp=sharing

**Comment by vijay-veeranki-moj** [comment]
https://docs.google.com/document/d/1zPl3WxQZWAuF4JhOmA_TijrBFNsRQ_Bm7MmQeNhWJ8k/edit?usp=sharing

**Comment by vijay-veeranki-moj** [comment]
It is still early to try this, as not much guidance and movement around it. So we can pick in the next firebreak.
