### ISSUE TITLE
User guide change: How to add my service to the pingdom dashboard

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1702]
This question came up about adding a service to the pingdom dashboard. There is a dashboard and you can add your service via terraform but that isn't clear from the current documentation. 

Amend the https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#create-a-pingdom-check page and make it clear that you need to add the below entry into your Terraform:

```
publicreport             = "true"
```
Also the dashboard link needs to be added to this doc:
http://pingdom.service.dsd.io/

Conversation: 
https://mojdt.slack.com/archives/C57UPMZLY/p1583229909135800

**Comment by AntonyBishop** [comment]
Already done.
