### ISSUE TITLE
Explore how to give parameters to a Pipeline in ConcourseCI

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#1705]
At the moment there is an issue related to the subject in the Concourse Repo: https://github.com/concourse/concourse/issues/783

We got the requirement to create a destroy-test-cluster pipeline which needs a parameter (cluster's name) and we need to find a solution to make it happen.

**Comment by AntonyBishop** [comment]
This ticket is about how we easily create and destroy test clusters.

**Comment by vijay-veeranki** [comment]
Concourse team confirmed that they are not going to implement manual parameters

If your workflow is inherently dependent on manual, human-provided parameters, then yes, you may want to use some other tool like Jenkins. User-provided input is antithetical to what Concourse is designed for, which is to be continuous, driven by a declarative configuration that runs in the background, triggered by external systems that act as the source of truth for all inputs.

https://github.com/concourse/concourse/issues/783#issuecomment-642204546

**Comment by vijay-veeranki** [comment]
Updated the runbook, where parameters can be added through fly

https://github.com/ministryofjustice/cloud-platform/pull/2049/files
