### ISSUE TITLE
Create a concourse pipeline or OPA policy to detect/prevent duplicate prometheus scrapes

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1719]
We have had situations where users accidentally created multiple servicemonitors which scraped the same endpoints. This causes PrometheusTargetScrapesDuplicate alerts.

Create either a pipeline to alert us about these, or an OPA policy to prevent them being deployed at all.

**Comment by AntonyBishop** [comment]
Closed to to age of ticket.
