### ISSUE TITLE
Periodically rotate all RDS credentials

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1725]
We have this script:
https://github.com/ministryofjustice/cloud-platform-environments/blob/master/bin/update-rds-module-version.rb

It would be quite easy to create a cut-down version that just:

  * rotated RDS credentials, and
  * recycled all the pods in the namespace

We could build this into a pipeline/cron job so that every RDS instance has its
credentials rotated every month (or however often).

Although it might seem disruptive, this shouldn't be any more so than the
node-recycler, and teams should have no problem writing their application code
in such a way that doing this causes no downtime of their services (e.g. rails
applications will be fine, straight out of the box).

Is this worth doing? Does it make the platform more robust?

**Comment by AntonyBishop** [comment]
Closed due to age of story
