### ISSUE TITLE
Use Slack Workflows to send messages to new channel joiners

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1727]
\#cloud-platform

Send a message explaining that this is the CP team's internal comms channel, which people are welcome to look at, but if they want help, to go join \#ask-cloud-platform

\#ask-cloud-platform

Send a message explaining what the channel is for, and to manage expectations

For an example of a slack workflow that does this kind of thing, see \#wfh-wellbeing

Slack workflow builder: https://slack.com/intl/en-gb/features/workflow-automation

**Comment by AntonyBishop** [comment]
Closed due to age of story
