### ISSUE TITLE
Create a pipeline which alerts us when terraform module versions go out of sync

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1729]
We have undertaken to keep all namespaces in the environments repo up to date wrt. terraform module versions.

Create a script which looks at all the terraform source files in all namespaces in the environments repo and checks that all instances of a given module are using the same release.

Create a concourse pipeline which alerts us whenever the script detects multiple versions of a terraform module.

This might be a starting point:
https://github.com/ministryofjustice/cloud-platform-environments/blob/master/bin/namespace-rds-report.rb

**Comment by AntonyBishop** [comment]
Already done in HOODAW
