### ISSUE TITLE
Update circle-ci tools image with helm3, after we upgrade all our components to helm3.

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#1745]
So as part of Updating our tools image, update the circleci image as well.

https://github.com/ministryofjustice/cloud-platform-tools-image/blob/master/Dockerfile#L12
https://github.com/ministryofjustice/cloud-platform-tools-image/blob/master/Dockerfile.circleci#L4

https://mojdt.slack.com/archives/C57UPMZLY/p1584966738361700

**Comment by AntonyBishop** [comment]
No longer required.
