### ISSUE TITLE
Implement AWS secret manager to GitOps pipeline 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#1747]
We have spiked to use AWS secret manager to use in Concourse pipeline. https://github.com/ministryofjustice/cloud-platform/issues/1619

Implement the changes to concourse so Gitops pipeline can use AWS secret manager to manage per namespace specific secrets.

## Approach

Activate AWS secret manager in concourse helm charts
IAM role with permissions restricted per namespace to access ASM 
Create AWS secrets using Terraform
Update config to retrieve secrets 

## Questions / Assumptions

How would you rotate the secrets? Is it a one click approach or manual update?

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Stale.
