### ISSUE TITLE
Increase disk size of worker nodes

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1751]
Our nodes are slowly filling up their disk space.

We should increase the `rootVolumeSize` from `256` to at least `500`.

This implies recycling all the nodes.

**Comment by AntonyBishop** [comment]
Include as part of 1.15 upgrade. Related to #1718

**Comment by vijay-veeranki-moj** [comment]
We now have node-recycler job running 3 times a day, this will sort the filling up disk space.

So we haven't increased the rootVolumeSize from 256 to 500  in the 1.15 upgrade.

Closing this ticket now, we can re-open this if node-recycler running 3 times, don't solve the filling up disk space issue.
