### ISSUE TITLE
Set up Hawkeye for operational security team

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#176]
**Background -**
Setup a git repo scanner to check for sensitive data and generate a report as output. Initial analysis was performed with Gitrob and realised the latest version does not support features which we require. Further analysis was performed with repo-supervisor, repo-security-scanner, truffleHog, gitleaks and found all of them lacking features like - scan file contents, scan for all git branches/commit history, web interface for the output report.

(output of #172) - Hawkeye as it borrows ideas from a lot of projects and fixes:
Scans for both file names and contents
Skips large files, git-crypt
Adds other security checks for Nodejs/Ruby/Python/Java
Has a more intuitive report format

The tool is not completely useable because-
- doesn't scan the entire org
- only scans HEAD of master (no history)
- no web interface
This story is to add needed functionality and document a workflow for the sec team

**Approach -**
- Create a docker image that a operational security team member can run
- User passes a credential that has read access for all repos
- Docker image will get a list of all repos in the MoJ org
- It will then iterate through each of those repos: cloning the repo and then runing hawkeye on it and adding the output to 1 long report
- It will then save the report locally

**Definition of Done -**
- [ ] An image that a user can download from e.g. dockerhub 
- [ ] When the user runs the image it scans all repos and creates a file with the potential secrets output
- [ ] Test it with one of the users

**Comment by kalbir** [comment]
Editing the approach after discussion with @sid234 and @razvan-moj

**Comment by razvan-moj** [comment]
Done in https://github.com/ministryofjustice/cloud-platform-hawkeye, waiting for feedback
