### ISSUE TITLE
Create terraform module for cert-manager

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#1763]
As a cloud platform engineer, I want to have a **terraform cert-manager module** for Kubernetes clusters so it can be reused in EKS clusters and kops clusters. 

Acceptance Criteria
- In our effort to make all test clusters as similar as possible to production, please check if there are any resources in our [environment repo](https://github.com/ministryofjustice/cloud-platform-environments/tree/master/namespaces/live-1.cloud-platform.service.justice.gov.uk) which can be migrated into this module. For instance: network policies, rbacs, etc
- Github repository for the module
- Ensure the module works for both EKS and KOPS
- Don't forget to add a README (a good example one can be found [here](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance))

**Comment by vijay-veeranki-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-certmanager
