### ISSUE TITLE
What services do we want to migrate to the Manager Cluster?

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1768]
## Background

We've created a Manager Cluster that runs our Concourse. We want to identify what other services/components/app we want to move to the manager cluster.

The purpose of this story is just to come up with the list. 

## Approach

Contribute to a list of items that we want to migrate.

## Which part of the user docs does this impact

N/A

## List of services for migration

- Example?

## Definition of done

- [ ] We have an agreed list of things to migrate so that we can create stories for the actual migrations.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
List that we can migrate to Manager cluster

cloud-platform-bots
