### ISSUE TITLE
Disable Pager Duty alerts for Accelerated Possession

### ISSUE THREAD

**Issue by leoapost** [ministryofjustice/cloud-platform#177]
## Service name

Accelerated Possession (a.k.a Civil Claims)

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production

## Impact on the service

There will be no impact on the service. Accelerated Possession was taken offline in January 2018 and will remain offline until decided otherwise (unlikely).

## Problem description

Pager Duty is creating false alarms and confusing people who don't know that the service was intentionally taken offline months ago.

## Contact person

Name: Leonidas Apostolidis
Slack: leoapost
Email: leonidas.apostolidis@hmcts.net

**Comment by pwyborn** [comment]
Pagerduty and Pingdom disabled - done
