### ISSUE TITLE
Workerless on EKS via Fargate

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1770]
Spike

**Comment by davidread** [comment]
* Check the benefits - less maintenance?
*    What are the implications?
*    How do we deal with the lack of DaemonSets for monitoring/logging etc?

**Comment by razvan-moj** [comment]
some meta-info I found interesting: https://aws.amazon.com/blogs/containers/saving-money-pod-at-time-with-eks-fargate-and-aws-compute-savings-plans/

**Comment by AntonyBishop** [comment]
Will revisit at a later stage.

**Comment by davidread** [comment]
Current barriers to Fargate discussed here: https://github.com/ministryofjustice/cloud-platform/blob/main/architecture-decision-record/022-EKS.md#future-fargate-considerations
