### ISSUE TITLE
Integration tests for the Manager Cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1771]
We need to replicate similar integration tests for the Manager Cluster.

Definition of Done

- [ ] Test and associated alerting created

**Comment by vijay-veeranki-moj** [comment]
Created Integration tests:

Changes made: 

https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/682
https://github.com/ministryofjustice/cloud-platform-concourse/pull/225
https://github.com/ministryofjustice/cloud-platform-concourse/pull/224
