### ISSUE TITLE
Spike: Teleport for EKS authentication

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1773]
We want to Spike use of Teleport for authentication using Github for the EKS Management Cluster.

https://aws.amazon.com/blogs/opensource/authenticating-eks-github-credentials-teleport/

We want to see whether this solves our problem for authentication, which is a blocker to wider EKS adoption.

**Comment by vijay-veeranki-moj** [comment]
Worked on the spike following this guidence

https://aws.amazon.com/blogs/opensource/authenticating-eks-github-credentials-teleport/.

https://gravitational.com/teleport/docs/kubernetes_ssh/#github-auth

The github-auth is not designed to work for our purpose. 

As a team had a call with Teleport and discussed about the requirement, they informed that they will look in to it get back to us.

**Comment by vijay-veeranki-moj** [comment]
Mail from Steven(Teleport team)

Thanks so much for joining us today.  I confirmed that you can set the Kubernetes groups as external lists or single metadata with other Identity Providers (IDP).  The same works for logins. 

Here is an example with Auth0.  The role will then get the k8sgroups and and logins from the IDP.  For using metadata (traits) from GitHub we have an open issue tracking that [here](https://github.com/gravitational/teleport/issues/3160).   Please review and we're happy to discuss further.

Auth0 snippet app metadata:
 "k8sgroups": [
    "developer-oncall-exec",
    "staging-oncall-exec"
  ],
   "logins": [
    "devuser",
    "devadminuser"
  ]


Role example:
kind: role
metadata:
  name: devrole
spec:
  allow:
    kubernetes_groups:
    - '{{external.k8sgroups}}'
    logins:
    - '{{external.logins}}'
...

**Comment by AntonyBishop** [comment]
Not going to pursue at this time.
