### ISSUE TITLE
Please can you reinstate my digital.justice.gov.uk google account

### ISSUE THREAD

**Issue by isherraikmo** [ministryofjustice/cloud-platform#1775]
## Service name opsmanual

 Isher Singh Raikmo

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Prod service will become unavailable

## Problem description
Unable to see ops manual to find out how a particular service's SSL cert needs to be renewed.

## Contact person

Isher Singh Raikmo (that is my name and my slack handle)

**Comment by AntonyBishop** [comment]
Ops Manual is no longer a service.
