### ISSUE TITLE
Analyse if/why we hit AWS API limits using CloudTrail and Athena queries

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#1783]
Sometimes we hit AWS API limits, especially with Route53. We start to see errors like

```
Aws::Route53::Errors::Throttling:
   Rate exceeded
``` 

Most of the times these limits are reached because of a problem in test clusters. We need to get good at using Amazon Athena with Cloudtrial in order to detect where all of this rate limits are coming from. 

Definition of done:
- Predefine some [Athena queries](https://docs.aws.amazon.com/athena/latest/ug/cloudtrail-logs.html) that can be used to identify which clusters are causing the problems

**Comment by AntonyBishop** [comment]
Closed due to age of story
