### ISSUE TITLE
Create a separate nginx ingress with support for older TLS versions

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1786]
Some services (e.g. prisoner money) have user groups who are constrained to use older browsers which cannot support modern TLS versions. For these services, we have [enabled TLS 1.0][commit] across the whole cluster.

This is not ideal. Services which don't need TLS 1.0 or 1.1 support should not be required to support it.

(any of these may be spun off into separate tickets)

- [ ] Create a user guide article explaining the issue and how to run an ingress in your namespace which supports older TLS versions
- [ ] Issue comms. pointing affected teams to the article, and explaining that cluster-wide support for TLS 1.0 will be removed on XX-XX-2020
- [ ] create an integration test that uses this mechanism, and confirm that HTTP requests using TLS 1.0 work successfully
- [ ] remove cluster-wide support for older TLS versions

[commit]: https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/commit/b7ba703987bc00151e9096ab1e9d9d7c245a0a0f

**Comment by AntonyBishop** [comment]
Duplicate. Close.
