### ISSUE TITLE
Identify all the service teams that need support for older TLS versions

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1792]
Some teams have user groups who are constrained to use old browser versions that don't support TLS 1.2.

We need to identify all such teams, so that we know who to talk to before making changes that might impact this (such as nginx upgrades).

**Comment by davidread** [comment]
Our ingress controller currently supports older TLS. The suggestion is that we should have two ingress controllers - one for teams that need older support, and one for teams that don't want it. Need to check whether even allowing any service to use older TLS affects other services too.

**Comment by AntonyBishop** [comment]
Created document to record services dependant on old TLS.

**Comment by AntonyBishop** [comment]
https://docs.google.com/spreadsheets/d/10tyCrkDWR-dzv8uob0Pc6ZRlpNAOZKu-37DcCzXkf-s/edit?usp=sharing
