### ISSUE TITLE
Get more information about our users when creating namespace

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#1794]
## Background

When creating the namespace, ask more information about users and any special restrictions/assumptions needed to made for their services. 
For example, Using quantum network, DOM machine users, Older TLS version support

The answers are recorded in a formatted way so easy to filter using a script or a text search in the repository.

Can be stored as annotations in users namespace. 

Inform in #ask-cloud-platform channel to update the users namespace with the answers recorded as annotations.

## Approach

Use "make namespace" script to ask more questions for a formatted answer and store them as annotations in their namespace.

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/env-create.html#pre-requisites

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Ticket has gone stale so has been closed due to age.

Ticket is nice to have and there is no research or needs in support of it.
