### ISSUE TITLE
Runbook for adding new zone for subdomain under "service.justice.gov.uk"

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#1796]
## Background

Add below instructions as runbook.

1 - create the zone in CP + get the NS
2 - create a new domain the main zone in DSD point to the one in CP

## Which part of the user docs does this impact

https://runbooks.cloud-platform.service.justice.gov.uk/#cloud-platform-runbooks

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Closed due to age of story
