### ISSUE TITLE
Revoke access to Github Organisation if users doesn't have a linked MoJ email address

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1798]
We have an issue with audit and management of Github accounts. To address this we have set a policy that all users of the MoJ Github organisation should link an MoJ email account - https://github.com/orgs/ministryofjustice/teams/no-verified-domain-email/discussions/2

This story is to remove everyone without @digital.justice.gov.uk, @justice.gov.uk, or @cica.gov.uk from our GitHub org, and make them all outside collaborators, but manage outside collaborators using Terraform.

**Comment by SteveMarshall** [comment]
To add a little detail to this, what I'm envisioning is that we have a repo (called `outside-collaborators`, say) that contains a bunch of [Terraform to manage outside collaborators' repo access](https://www.terraform.io/docs/providers/github/r/repository_collaborator.html).

Ideally we'd have something like one directory (or `.tf` file?) per “team” of collaborators, and have the repo be the source of truth for outside collaborators (so anyone not in the repo gets removed), and have people raise PRs to add new collaborators. That way, we can see who requested someone have access to what, and why. All of the state should be applied every time PRs are merged to master, thus updating the outside collaborators.

**Comment by SteveMarshall** [comment]
Also, once we have terraform management of outside collaborators, we can require SSO through Gmail for everyone. 🔒👌🏼

**Comment by SteveMarshall** [comment]
Sorry, accidentally closed this when *trying* to also mention that there’s a [team set up with all the users who have no valid MOJ email set up on their account](https://github.com/orgs/ministryofjustice/teams/no-verified-domain-email/discussions/2). The people in that group are all candidates for moving to outside collaborators.

**Comment by digitalronin** [comment]
I've done a tiny bit of work on this here: https://github.com/ministryofjustice/outside-collaborators

We are at the limit of the number of seats in our github subscription, so you get an error when trying to add outside collaborators to a repository. This makes it impossible to make progress on this, so I'm shelving this for now. We should revisit once we have more github capacity.

**Comment by AntonyBishop** [comment]
@digitalronin is this replaced by the work you are doing on external collaborators? - https://github.com/ministryofjustice/operations-engineering/issues/23

**Comment by digitalronin** [comment]
> @digitalronin is this replaced by the work you are doing on external collaborators? - [ministryofjustice/operations-engineering#23](https://github.com/ministryofjustice/operations-engineering/issues/23)

Sort of. The work I'm doing on external collaborators is absolutely what this ticket is about. But the Github APIs don't enable us to check wether or not users have a MoJ email address, so I'm not addressing that, at this stage. ISTR Steve wrote some code to get this information by scraping the github web interface, so I can try using that as a subsequent phase of the work I'm doing now.

**Comment by AntonyBishop** [comment]
Transfered to Ops Engineering backlog
