### ISSUE TITLE
[template-deploy] Jenkins pulling down wrong image tag

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#1813]
## Service name

Check legal aid

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Unable to deploy to any environment

## Problem description

Jenkins is not respecting the configuration supplied in the build parameters and instead pulling down a very old cla_backend:latest image for every build

## Contact person

[at]Said
[hash]laa-cla-fala

**Comment by AntonyBishop** [comment]
Unable to fix issue due to lack of support for Template Deploy Jenkins instance being used. Fix is to migrate to the Cloud Platform and replace Jenkins pipelines.
