### ISSUE TITLE
Explore hostnames in a multi-cluster platform

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1818]
Cluster-specific URLs for services (e.g. https://my-service.apps.live-1.cloud-platform.service.justice.gov.uk), will not work in a multi-cluster platform.

We can set up a cluster-agnostic wildcard certificate so that the default URL for services is something like "https://my-service.apps.internal.cloud-platform.service.justice.gov.uk", but for route53 traffic policies, every service must also have a cluster-specific FQDN.

This spike is to explore a deployment process that would allow users to deploy to "the cloud platform" - i.e. an endpoint which doesn't change, regardless of the cluster(s) active in the cloud platform at deployment time.

* What would be required for users to be able to address the cloud platform as a whole, when deploying/updating their applications?
* How could we add cluster-specific URLs to ingresses at deployment time?
* How would we setup/update default route53 traffic policies at deployment time?
* Would users have any control over the route53 traffic policies for their services? If so, what would that look like?

**Comment by vijay-veeranki-moj** [comment]
https://docs.google.com/document/d/105TidwFNE2P1AkDaS1Ql6Rcp5wM7gbH5mZzlQ4EEWXw/edit

This is the initial findings while working on the fire-break ticket.

This needs more discussion and need to visit again while working with traffic splitting tasks.
