### ISSUE TITLE
Enable one or more of "our" web applications to be moved seamlessly from one cluster to another

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1819]
e.g.

* https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk
* https://namespace-usage-report.apps.live-1.cloud-platform.service.justice.gov.uk

* Replace the "live-1" name with a cluster-agnostic name (e.g. "internal" in place of "live-1")
* Set up a route53 traffic policy for the application
* Move the application back and forth between a test cluster and live-1 (or between one test cluster and another)
* Document the process and any issues/pre-requisites

**Comment by mogaal** [comment]
This mainly involves Route53 traffic policy, terraform already supports it: https://www.terraform.io/docs/providers/aws/r/route53_record.html#weighted-routing-policy
