### ISSUE TITLE
Tidy up - Remove Alejandro from ssh/deploy repos

### ISSUE THREAD

**Issue by pwyborn** [ministryofjustice/cloud-platform#182]
My understanding is that Alejandro has been removed as a member  the Ministry of Justice Git Hub (check with Sablu what has/has not been done). Alejandro left MoJ 14/06/2018

**Comment by pwyborn** [comment]
## Approach

- check with Alex Clarke/Nathan that they have handled everything aws accounts etc (apart from ssh and other cloud platforms app i.e rattic, pagerduty, pingdom etc)
- ssh update github repos and run salt-keys where he had access 
- check other cloud-platforms apps  


## Definition of done

- [x] Alejandro removed from everything

**Comment by sablumiah** [comment]
All PRs have been reviewed and merged 

All access has been removed
