### ISSUE TITLE
Multi-cluster app. deployments

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1820]
How could we have a deployment process where users don't need to care which cluster(s) their application is going to be deployed onto?

Users shouldn't need to make any changes to their deployment processes/pipelines if we replace live-1 with live-2, etc.

How can we make this work?

**Comment by davidread** [comment]
Another way to look at this problem is: https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2557
