### ISSUE TITLE
Please create subdomain called contact-moj on service.justice.gov.uk

### ISSUE THREAD

**Issue by digitalali-moj** [ministryofjustice/cloud-platform#1825]
## Service name

Contact MOJK

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Will allow us to use the domains:
contact-moj.service.justice.gov.uk (prod namespace)
development.contact-moj.service.justice.gov.uk (dev namespace)
staging.contact-moj.service.justice.gov.uk (prod namespace)

## Problem description

Currently I can't view any of the apps on the real domain, but since the actual domain is changing I'd like to have the real domains ready including the new prod domain, which I'm planning to put HTTP Auth onto before the app goes on.

## Contact person

Javid Ali / javid.ali@digital.justice.gov.uk / Slack javidali

**Comment by mtrbls** [comment]
Done
