### ISSUE TITLE
Create a fallback process (inc. runbook) to authenticate devs. when github is down

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1826]
If github goes down, developers will be unable to authenticate to the cluster.

* Create a script which generates a suitable kubeconfig file, including the user's github team memberships, with a short expiration date.
* Create a runbook explaining how to use this, for the CP team
* Mention the procedure in the user guide page on authenticating to the CP

**Comment by AntonyBishop** [comment]
Decided low risk. Minimal value.
