### ISSUE TITLE
Update all the terraform modules to remove team_name in the path for creating iam_user

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#1829]
Update all the terraform modules, we use in environments repo, to remove team_name in the path for creating iam_user.

This is causing pipeline to apply the changes with this error:

Error creating IAM User cp-dynamo-xxxxxxxxx: ValidationError: The specified value for path is invalid. It must begin and end with / and contain only alphanumeric characters and/or / characters.

example:

```
resource "aws_iam_user" "user" {
  name = "cp-dynamo-${random_id.id.hex}"
  path = "/system/dynamo-user/${var.team_name}/"
}
```

**Comment by digitalronin** [comment]
Would another option be to pre-process the team name and remove any characters that weren't allowed, before creating the IAM user?

It's nice to be able to look at the name and figure out which team it belongs to.

**Comment by AntonyBishop** [comment]
Closed due to age of story
