### ISSUE TITLE
Create a list of repos relating to migrated template deploy services

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1831]
Security are looking at repos that can be archived.

In support of this activity we have been asked to identify potential repos relating to migrated Template Deploy services that can be archived.

Definition of done:
- [x] List of repos that we can share with security so that they can investigate if these can be archived.

**Comment by pwyborn** [comment]
https://docs.google.com/spreadsheets/d/14q_jArLtph4WuKuOgPMrOBMt6ouV-IV3tTtq5QTE7_M/edit#gid=0
