### ISSUE TITLE
Set up concourse pipelines for testing our terraform modules

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1838]
Right now, we have no automated tests for our terraform modules. Partly, this is because any such tests might take a very long time to run, since we would first need to build a test cluster before we could run the tests.

This ticket is to explore what such an automated test framework and pipeline(s) might look like. Ideally, anytime we push to a branch of one of our terraform modules, a background process would run our tests against a new test cluster, and would also test the change versus the latest release, to determine if it's safe (i.e. does it update the terraform resource in place, or recreate it?)

This ticket will probably need to be split into several smaller tickets.

**Comment by vijay-veeranki-moj** [comment]
exploring:

https://docs.google.com/document/d/1UgXM0uFyB9tJvZv-G5XQ0u1xiNVD2zZXfS9gmPKjwh8/edit?usp=sharing
