### ISSUE TITLE
Add module validation github actions to the env. repo.

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1842]
There are a few areas where the terraform dry-run doesn't find problems with the code that users submit in their PRs. One example is illegal RDS database names (e.g. hyphens are not allowed - you only find out when AWS rejects the API call).

Create a github action which intelligently applies such rules to users' PRs, and rejects them with a helpful error explaining how to fix the problem.

**Comment by AntonyBishop** [comment]
Closed due to age of story
