### ISSUE TITLE
Delete unnecessary route53 A & TXT records in the live-1 hosted zone

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1846]
We were nearing our limit of 10,000 records per zone

 - [x] Delete the bulk of unnecessary records leftover from automated tests
 - [ ] Compare route53 and ingress data, to identify records we don't need anymore
 - [ ] Create a concourse pipeline job to regularly clean out unnecessary records

**Comment by vijay-veeranki** [comment]
This work is done, we have a pipeline delete-excess-dns to clear the records.
--hosted-zone-id Z28AFU7GYHT7R4 --max-items 500  

Also we updated our external-dns to sync option which will clear the txt and A records, when the ingress is deleted.
