### ISSUE TITLE
Investigate the difference of config between test cluster and live-1

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#1847]
To add more information to the "Delete the whole cluster" DR plan, Investigate below and add to runbook section.

- What is the difference between live-1 to test cluster? 
- What other resources and configs has to be applied which are not in infrastructure code in order to recover live-1?

Related to: [Test " Delete the whole cluster" recovery plan](https://github.com/ministryofjustice/cloud-platform-user-guide/issues/208)

## Which part of the user docs does this impact

https://runbooks.cloud-platform.service.justice.gov.uk/disaster-recovery-scenarios.html#cloud-platform-disaster-recovery-scenarios

## Definition of done

- [ ] runbook has been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
This ticket became more of a how do we manage live-1 as opposed to what is missing from test clusters. 

Multiple smaller tickets created on how to manage resources applied via apply pipeline and documentation ticket on what gets installed only for live-1 using the create cluster tf modules.
