### ISSUE TITLE
Investigate how to install velero in a empty kops/eks cluster

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#1848]
## Background

Related to: Test " Delete the whole cluster" recovery plan

During the restore process of when the whole cluster is lost, the components are created from the infrastructure code. Restoring from velero will skip the resources already created for components using the cluster create script.

## Approach

Currently for installing velero to a kops cluster, it depends on prometheus for ServiceMonitor and helm serviceaccount to install using helm chart. Investigate whether velero can be installed on an empty kops cluster and restore the whole components from velero. 

## Questions / Assumptions

Are there any difference in config when creating components resources from infrastructure code and restoring from velero? 
Does skipping existing resources when restoring the velero bring all the things back in components into its expected state?

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Closed due to age of story
