### ISSUE TITLE
Thought: Can we add Kops and Kubernetes version to the HODAR app

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1856]
https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk/
This app does an excellent job of reporting out of date terraform modules, helm releases and docs. Can this be exapanded to Kubernetes versions in our ecosystem and potentially kops.

**Comment by digitalronin** [comment]
👍 excellent idea

**Comment by digitalronin** [comment]
I'm also now wishing I could come up with an acronym for the app which spells Hodor!

**Comment by AntonyBishop** [comment]
Closed due to age of story
