### ISSUE TITLE
Form Builder: Move non production alerts to low severity slack channel

### ISSUE THREAD

**Issue by brenetic** [ministryofjustice/cloud-platform#1858]
## Service name

Form Builder

## Service environment

- [x] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [x] Other

## Impact on the service

Should only impact no production environments and is primarily for people working on the Form Builder platform and services.

## Problem description

We need to move all the non production alert manager slack alerts to a low severity channel. This affects the following namespaces:
 
```
formbuilder-platform-live-dev
formbuilder-platform-test-dev
formbuilder-platform-test-production
formbuilder-publisher-test
formbuilder-repos
formbuilder-services-live-dev
formbuilder-services-test-dev
formbuilder-services-test-production
hmcts-complaints-formbuilder-adapter-staging
```

The kubernetes secret has been applied to all of the above namespaces.

The key inside the data part of the kubernetes secret is slack_webhook hope that’s ok?

```
namespace: all of the above mentioned namespaces
team name: Form Builder
application name: i guess use Form Builder again?
channel: #form-builder-alerts-low-severity
kubernetes secret name where the webhook url is stored: fb-low-severity-alerts-slack-webhook
severity level (warning/information): Low Severity (or does this get given to us?)
```

## Contact person

@brenetic

**Comment by vijay-veeranki-moj** [comment]
Hi @brenetic 

Applied the changes, please use severity = "form-builder-low-severity"
for channel  = "#form-builder-alerts-low-severity"

used the webhook you provided as secret

**Comment by brenetic** [comment]
Awesome, thanks @vijay-veeranki-moj 

I assume that any production `severity = form-builder` alerts will still be sent to the `#form-builder-alerts` channel?

**Comment by brenetic** [comment]
thanks @vijay-veeranki-moj this all works as expected 🚀
