### ISSUE TITLE
Add read-replica support to the RDS module

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1859]
There is a need to the RDS module to create Read Replica database.
A read replica is a read-only database maintained in sync with a source RDS. 

Terraform supports this : [replicate_source_db](https://www.terraform.io/docs/providers/aws/r/db_instance.html#replicate_source_db)

Having one normal RDS and a _read replica_ RDS would mean invoking the module twice, passing the `db_id` of the first one as the value to `replicate_source_db` field of the second one.

**Comment by digitalronin** [comment]
Why would we need to run the module twice? Couldn't you just define two RDS instances, one of which referred to the other, and have terraform figure out that there was a dependency?

**Comment by AntonyBishop** [comment]
Required for CLA migration from Template Deploy

**Comment by poornima-moj** [comment]
https://github.com/terraform-providers/terraform-provider-aws/issues/6749
