### ISSUE TITLE
Replace fluentd with fluentbit

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1867]
We've seen problem with fluentd pods crash-looping on the active master node.

For that reason, and because it's supposed to be less resource-hungry in
general, we should explore replacing fluentd with fluentbit (supposedly a
drop-in replacement, implemented in C).

Also explore if fluentbit can perform this request in the ask
https://mojdt.slack.com/archives/C57UPMZLY/p1593163327230800

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1UjAiSNMQF-t_k_j8xOrB7A5JAd76pwyFKzriVRsqLd0/edit

**Comment by vijay-veeranki** [comment]
Created a ticket to install fluent-bit in live-1

https://github.com/ministryofjustice/cloud-platform/issues/2041
