### ISSUE TITLE
Update the "authenticating" section of the user guide

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1881]
As per this conversation: https://mojdt.slack.com/archives/C57UPMZLY/p1589539798195300

It's possible for users to click the wrong button during the github oauth authentication process, and end up with a kubeconfig that does not list the github teams they are in.

Update the user guide with a warning and a screenshot of the relevant step, so that they always click on the correct button.

**Comment by AntonyBishop** [comment]
Done
