### ISSUE TITLE
Delete left-over VPC's in london and ireland region and terraform workspaces in cloud-platform-network

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#1890]
Delete left-over VPC's in london and ireland region and terraform workspaces in cloud-platform-network.

We have 26 VPC's in London region and 2 in Ireland region. also we have 46 workspaces in "cloud-platform-infrastructure/terraform/cloud-platform-network". This may be because leftovers from partially-deleted clusters.

This ticket is to work on deleting un-used/left-over VPC's and workspaces.

**Comment by AntonyBishop** [comment]
Done
