### ISSUE TITLE
Migrate cloud-platform-bots from live-1 to the Manager Cluster

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#1891]
This is related to: [1768](https://github.com/ministryofjustice/cloud-platform/issues/1768)

We've created a Manager Cluster that runs our Concourse. We want to move cloud-platform-bots from live-1 to the manager cluster.

cloud-platform-bots:
https://github.com/ministryofjustice/cloud-platform-environments/tree/master/namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-bots

Similar to live-1 create a namespace structure for manager cluster, and pipeline to run for manager cluster and apply these resources.

https://github.com/ministryofjustice/cloud-platform-environments/tree/master/namespaces/live-1.cloud-platform.service.justice.gov.uk

**Comment by AntonyBishop** [comment]
Closed due to age of story
