### ISSUE TITLE
Migrate authorized-keys-provider from live-1 to the Manager Cluster

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#1893]
This is related to: [1768](https://github.com/ministryofjustice/cloud-platform/issues/1768)

We've created a Manager Cluster that runs our Concourse. We want to move authorized-keys-provider to the manager cluster.

authorized-keys-provider:
https://github.com/ministryofjustice/cloud-platform-environments/tree/master/namespaces/live-1.cloud-platform.service.justice.gov.uk/authorized-keys-provider

Similar to live-1 create a namespace structure for manager cluster, and pipeline to run for manager cluster and apply these resources.

https://github.com/ministryofjustice/cloud-platform-environments/tree/master/namespaces/live-1.cloud-platform.service.justice.gov.uk

**Comment by AntonyBishop** [comment]
No longer has it's own namespace. Nothing to migrate
