### ISSUE TITLE
Improve user-guide for custom domains

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1896]
The user-guide to set up a new domain in the cloud platform could be clearer.
Though the documentation is not lacking any essential information, it should be restructured to be easier to understand. 

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/custom-domain-cert.html#using-a-custom-domain

**Comment by AntonyBishop** [comment]
Not well defined.
