### ISSUE TITLE
Review PodSecurityPolicy

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1907]
## Background

We've identified a few pods with misconfigured PSPs:

**Permission/Pod**
‘RunAsAny’/omic-restricted _(this was as a result of migration issues at the time)_
‘RunAsAny’/prometheus-operator-grafana-test
NET_RAW capability/omic-restricted _(this was as a result of migration issues at the time)_

## Approach

Review to see if these are appropriate. If not, change change the config in line with what is appropriate.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- Do we need to check anything with the OMIC Service Team before we make any changes?

## Definition of done

- [x] config reviewed
- [x] config corrected

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Removed prometheus-grafana-test as this wasn't being used.

**Comment by jasonBirchall** [comment]
omic-restricted is being used in prod.

**Comment by jasonBirchall** [comment]
With the help of the omic team, the omic-restricted psp and related clusterrolebindings have now been removed. This ticket can now close.
