### ISSUE TITLE
Reinstate IAM user access to the mojdsd AWS account

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#191]
Hello, this is not an issue with any service in particular.

I just need my IAM user access to the mojdsd AWS account reinstated. It was removed as part of the spring cleaning about 2 months ago.
We, Family Justice delivery team, are going to start working on several products that require AWS.

`arn:aws:iam::_____:user/JesusLaiz`

Please let me know if you need anything else.

Thank you.

**Comment by lukaszraczylo** [comment]
User password changed and provided. 
User confirmed successful login.
