### ISSUE TITLE
Investigate Role of kube-system-2

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1910]
Investigate why the asset `kube-system-2` has a role of `cluster-admin`.

Confirm if it should. If it shouldn't then change the role to something appropriate.

**Comment by jasonBirchall** [comment]
Removed the kube-system-2 service account. Whatever's using it will fail. There is also a clusterrolebinding with the same name. I will also remove this at a later date.

**Comment by jasonBirchall** [comment]
Removed all references to kube-system-2
