### ISSUE TITLE
Create a Github action that rejects PRs with inappropriate cluster-admin role requests

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1911]
We want to reject PRs that ask for `cluster-admin` role as this provides too much access.

Create a Github action that rejects PRs that includes requests for `cluster-admin`

**Comment by digitalronin** [comment]
This is already done:
https://github.com/ministryofjustice/cloud-platform-environments/blob/main/.github/workflows/conftest-yaml.yml
https://github.com/ministryofjustice/cloud-platform-environments/blob/main/policy/rolebinding.rego
