### ISSUE TITLE
Review S3 Bucket Settings

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1913]
We have a number of S3 buckets where the following settings are not enabled:

- Bucket access logging disabled
- Bucket allowing clear text (HTTP) communication
- Bucket without MFA delete
- Bucket without versioning

Review the list of S3 buckets to check if these settings are required.

**Comment by davidread** [comment]
Shouldn't the terraform module that manages these sort all this?

Encryption and public are checked by a lambda function. Maybe extend that to cover these other options? Or enforce with policy in another way? (OPA or AWS equiv?)

**Comment by AntonyBishop** [comment]
Close. Being replaced by new story following recent ITHC.
