### ISSUE TITLE
Changes to S3 Module to include additional settings by default

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1914]
We want to make changes to the S3 module to set the following to `ENABLE`.

- Bucket access logging disabled
- Bucket allowing clear text (HTTP) communication
- Bucket without MFA delete
- Bucket without versioning

Update the module.

**Comment by imranawan-moj** [comment]
* Logging capability has been applied. Details on it's usage can be viewed in README and example/s3.tf files 

* Versioning was already applied, but added further notes on what versioning is how to apply it in examples/s3.tf

* HTTP communication cannot be applied as AWS does not allow HTTP and only allows HTTPS as the S3 endpoint. 

* MFA was not implemented as this requires root keys to enable which poses a security risk. For data protection it is recommended to use 'versioning'

**Comment by imranawan-moj** [comment]
PR approved:
https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket/pull/25
