### ISSUE TITLE
Subnet flow logs

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1918]
We have no Subnet flow logs in place.

Investigate and implement what AWS provides "out of the box"

**Comment by davidread** [comment]
We should store the VPC flow logs to be available for forensic analysis. It's big, so ideally we'd simply store in S3 rather than put into Elastic.

**Comment by mtrbls** [comment]
S3 support needs to be added. 
We want to enable this asap to evaluate long term cost

**Comment by davidread** [comment]
What happened to this?

**Comment by AntonyBishop** [comment]
It was turned on for the CP account. Should be running.
