### ISSUE TITLE
Lock down ports in SGs

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1919]
Ports and services should adopt the principle of least privilege (POLP), in that ports and ranges as well as the networks and subnets they connect to should be restricted to the bare minimum need to function.

We have a number of rules we should review and restrict ports as appropriate.

**Comment by davidread** [comment]
Presumably there are some k8s best practices we can follow

**Comment by AntonyBishop** [comment]
Replace with new story following recent ITHC.
