### ISSUE TITLE
Use more powerful nodes in the manager cluster

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1923]
One of the nodes in the manager cluster has a flapping high CPU alert.

This may be due to Prometheus/Thanos. In live-1, we fixed this by creating a new node group, with two larger nodes, dedicated to running Prometheus and Thanos.

The manager cluster only has 4 nodes, so an additional node group is probably more complexity than necessary. Instead, we should increase the size/power of the nodes which comprise the manager cluster.

**Comment by AntonyBishop** [comment]
Issue seems to be resolved.
