### ISSUE TITLE
Automate creating a Cloud Platform AWS account from a "blank" AWS account

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1925]
## Background

At the moment we have decided that we don't want to build our automated cluster build pipeline with test on a separate AWS account. However we should be able to automatically create an AWS for use with the Cloud Platform that is set up in line with the usual Cloud Platform/MoJ requirements.

## Proposed user journey

Cloud Platform needs a new AWS Account. We have an automated process that creates a new AWS account configured correctly.

## Approach

Research how we use automation to create an account. We won't be using this immediately but there will be value longer term. 

related to #1865, #1425 

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- What should a CP AWS account look like and is this documented.

## Definition of done

- [ ] Research into how we automate process
- [ ] We have a definition for what is required of a "CP" AWS account
- [ ] Process tested
- [ ] Associated Runbook created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
We now have the cloud-platform-ephemeral-test AWS account, to use for this and other account-level tasks.

The root credentials are in lastpass, so please create an IAM user and credentials for yourself when working on this ticket.
