### ISSUE TITLE
Create new pipeline that runs automated pipeline with tests

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1926]
## Background

Creation of the pipeline that with run the 3 (or 4) jobs that will facilitate the automated cluster creation, tests and destruction.

We already have all the scripts to carry out the jobs and tests. This now just need to be automated.

## Questions / Assumptions

- What runbooks are required?
- What will this pipeline run?

## Definition of done

- [ ] Pipeline created
- [ ] Supporting documentation created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-concourse/pull/246
