### ISSUE TITLE
Automate reminders for review of a User Guide and Runbook content

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1928]
## Background

We already have the HOODAW app to identify documentation that requires review, however that's only useful if we look at it.

We should create an automated reminder in slack that notifies us when reviews are required.

Possibly related to: https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/issues/16

## Proposed user journey

We receive an automated notification to tell us when documentation requires review so that we can assign someone to carry out the review and keep out documentation useful and up to date.

## Approach

This will probably be a notification  via Slack. Whoever picks up this story can decide how they want this to work.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] Notifications set-up

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
I'm working on this with @pwyborn 

We've added a JSON endpoint, via https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/pull/36

Next stage is to get that running in production, and then consume the JSON in a daily concourse pipeline job, and post a formatted message to #cloud-platform if the "action_required" value is true.
