### ISSUE TITLE
Create an automated process that promts the team about open PRs and merges that are older than X days

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#1932]
We should look at some way of prompting the team about PRs and merges that are older than a certain number of days (TBD). This will improve workflow and ensure that PRs do not go stale and reduce merge conflicts.

This should ensure that the team members gets their PR reviewed or merged, or even closes the PR if no longer required. Perhaps we will go as far as automatically closing the PR?

**Comment by digitalronin** [comment]
github have a feature called "pull reminders" now, which they got as part of their acquisition of pullpanda. It might be worth looking into that.

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform/pull/2111
