### ISSUE TITLE
Automate injection of Slack creds to ECR scanning lambda function

### ISSUE THREAD

**Issue by imranawan-moj** [ministryofjustice/cloud-platform#1940]
## Background

Currently we have a lambda function that is executed by an event bridge. When a ECR scan is completed for a given ECR image, the event bridge captures the status of the image scan and targets this to the lambda function. The lambda function then forwards and notifies the status of the scan to the relevant slack channel as per the token it is using. 

## Proposed user journey

It is assumed that the teams have created a kubernetes secret that contains two keys: (1) ECR repo (2) Slack token. 

The objective of this ticket is to have an automated process that extracts the ECR repo and slack token from the kubernetes secret and inject them dynamically as environment variables to the lambda function during creation of the lambda

## Approach

The solution is partially complete in that there is a shell script that dynamically captures the ECR repo and token from a given kubernetes secret and dynamically amends the variables.tf file with the terraform values for 'var.ecr_repo' and 'var.slack_token'. Terrafrom 'apply' can then be run to create the lambda resource.

The shell script needs to run as part of 'terraform apply' instead of running it seperatly. Importantly terraform needs to run the before it attempts to create the lambda resource. In other words the lambda function is a dependency of this shell script

## Which part of the user docs does this impact

This will not affect any high level documenation as it is a low level implementation change.

## Questions / Assumptions

Below are the assumption for this ticket: 

* The kubernetes secret containing slack token already exists (creaed by team)

* The environment from where the terraform is running has the correct Kubernetes credentials to capture the team's kubernetes secret. As this will be run in pipeline then this should bd fine.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Slack thread - https://mojdt.slack.com/archives/C514ETYJX/p1591007653251300

**Comment by imranawan-moj** [comment]
PR approved:
https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials/pull/28
