### ISSUE TITLE
Upgrading kubernetes from 1.15 to 1.16

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1941]
This upgrade includes breaking changes to the following kubernetes APIs, meaning that users' YAML definitions will need to be updated. Objects which are specified using the deprecated API versions cannot be deployed to a 1.16 cluster, so we have to get all objects updated before we can upgrade the cluster.

In addition, helm charts which are deployed by helm versions up to 2.16.3 will create objects using the older APIs, so any teams which are still using older helm versions will need to upgrade (ideally to Helm 3).

More details in this [ibm article], and the [changelog]

## Plan

* Identify the list of all affected object types which are running in the cloud platform [DONE]
  * `NetworkPolicy`
  * `Deployment`
  * `PodSecurityPolicy`
  * `Ingress` (the API change to the ingresses is not strictly necessary until kubernetes 1.22, but we may as well get it done now, if we can)
* Create a run a script to catalogue objects in the cloud platform (both `live-1` and `manager` clusters) which use deprecated APIs (see #1942) [DONE]

This script will include something like this:
```
kubectl get NetworkPolicy,PodSecurityPolicy,DaemonSet,Deployment,ReplicaSet,Ingress --all-namespaces -o 'jsonpath={range .items[*]}{.metadata.annotations.kubectl\.kubernetes\.io/last-applied-configuration}{"\n"}{end}' | grep '"apiVersion":"extensions/v1beta1"'
```

Script output is in this [google sheet](https://docs.google.com/spreadsheets/u/1/d/1DY4PSZjmXqLcnqww0NetmIjMdw3p0hUqfv_ytJ304j4/edit#gid=1385161393)

* Update all our user-facing documentation and code examples to use the new APIs (see #1943)
  * User guide
  * Multi-container demo app
  * Hello world demo app
  * How out of date are we
  * Namespace reporter
  * All yaml files in the environments repository
  * TODO: identify any other code we have which needs to be updated
* Create a new page in the user guide "upgrading from kubernetes 1.15 to 1.16", including: (see #1944)
  * before & after examples for affected objects
  * explaining the problem with older Helm versions
  * examples of the error messages users might see if they try to use older APIs on kubernetes 1.16
* Inform users of the changes they need to make, and by when
* Monitor and assist teams to upgrade their code
* Upgrade our clusters once it is safe to do so
* Create a process to give us more warning of issues like this, for next time (see #1945)

[ibm article]: https://www.ibm.com/cloud/blog/announcements/kubernetes-version-1-16-removes-deprecated-apis
[changelog]: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#deprecations-and-removals

**Comment by poornima-moj** [comment]
@digitalronin , can we expand the script to find out the list of helm deployments done with older version of helm v2.16.0
