### ISSUE TITLE
Create an early-warning process for API changes

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1945]
related to #1941

Although the breaking API changes in kubernetes 1.16 have been planned for some time, we only noticed them when we tried the upgrade in test clusters.

This is a lot better than only finding out when a production service breaks, and we have to roll back live-1, but it could be better.

Come up with a way for us to be alerted earlier about upcoming breaking changes.

Note: Deciding that "someone should read the documentation every week" isn't going to work - with the best of intentions, we will just forget to do this, after a while. We need something a bit more pro-active. The ideal system would be a script that runs periodically (via concourse) which could raise github issues relating to each breaking change, and alert us in slack. This is probably not feasible right now, but we should keep those goals in mind - we need something that will kick us into action, even if we all forget about it.

https://www.ibm.com/cloud/blog/announcements/kubernetes-version-1-16-removes-deprecated-apis

**Comment by AntonyBishop** [comment]
Close due to age of story.
