### ISSUE TITLE
Upgrade concourse helm chart (in the manager cluster)

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1946]
According to [HOODAW], we're using concourse helm chart 9.0.0 and the latest version available is 11.x.x

There don't seem to be any significant changes in the helm chart (and there's no version 10), so we should probably just upgrade to stay current.

[HOODAW]: https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk/helm_whatup

**Comment by poornima-krishnasamy** [comment]
helm whatup -n concourse                                                                                                                                                                                                         <aws:moj-cp>
NAME	NAMESPACE	INSTALLED VERSION	LATEST VERSION	CHART


----
NAME                    concourse
NAMESPACE               concourse
INSTALLED VERSION       9.0.0

REPOSITORY	DEPRECATED	CHART VERSION	APP VERSION	UPDATED
concourse 	false     	13.0.0       	6.5.1      	2020-09-01 15:05:56.193186149 +0000 UTC
stable    	true      	8.3.7        	5.6.0      	2020-10-01 13:29:46.351960677 +0000 UTC
----
