### ISSUE TITLE
Check that all pingdom alerts are in terraform

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#195]
## Background

@lukaszraczylo did some work in https://github.com/ministryofjustice/cloudplatforms-terraform-ops/pull/18 to get pingdom back under terraform control but to complete it we need to:

1. Check that all of the current pingdom checks are defined in terraform
2. Add the missing ones

## Definition of done

- [x] All of the checks currently defined in pingdom are also defined in terraform
- [x] We can run terraform to manage the pingdom account and it does not remove any existing pingdom alerts

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by lukaszraczylo** [comment]
Connects to #197
