### ISSUE TITLE
Upgrade Grafana to at least v7.0.2

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1952]
We are running Grafana 6.7.3

There is a security vulnerability affecting versions 3.0.1 to 7.0.1:

https://grafana.com/blog/2020/06/03/grafana-6.7.4-and-7.0.2-released-with-important-security-fix/

**Comment by vijay-veeranki-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/34

Upgraded to 7.0.2
