### ISSUE TITLE
Enable dynamic whitelisting of cluster nat gateway IPs

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1953]
The cluster nat gateway IPs are whitelisted [here].

So, if we every move the cluster, and get new IPs, our logging would break until we updated our source code.

Come up with a way to find out what the cluster nat gateway IPs are programmatically (via the AWS API?), and update this terraform source code to populate this list automatically.

This is also relevant to this [slack thread].

[here]: https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/e17b585e7f658ece91f3c05326e14784acc7b2fe/terraform/global-resources/elasticsearch.tf#L4
[slack thread]: https://mojdt.slack.com/archives/C514ETYJX/p1591266754443500

**Comment by AntonyBishop** [comment]
Close due to age of story.
