### ISSUE TITLE
Upgrade kuberos for kubernetes 1.16

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#1955]
related to #1941 

## Proposed user journey

Before upgrading kubernetes version 1.16, all deprecated APIs used in the cluster manifest has to be replaced with the new one.

kuberos uses version **0.1.0** which has the Deployment apiVersions "apps/v1beta2" and Ingress "extensions/v1beta1". Upgrade the chart template to supports new apiVersion

## Approach
```
NAME              NAMESPACE   KIND         VERSION              REPLACEMENT                 DEPRECATED   DEPRECATED IN   REMOVED   REMOVED IN
kuberos/kuberos   kuberos     Deployment   apps/v1beta2         apps/v1                     true         v1.9.0          true      v1.16.0
kuberos/kuberos   kuberos     Ingress      extensions/v1beta1   networking.k8s.io/v1beta1   true         v1.14.0         false     v1.22.0
```
Install [pluto](https://github.com/FairwindsOps/pluto) to check what version is used 

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/771
https://github.com/ministryofjustice/cloud-platform-terraform-kuberos
https://github.com/ministryofjustice/cloud-platform-helm-charts/tree/master/kuberos
