### ISSUE TITLE
Upgrade AWS Elastic-Search cloud-platform-audit cluster to 7.4 version

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#1958]
For cloud-platform-audit AWS Amazon Elastic search, we are using version:6.4. Now amazon supports Elasticsearch version 7.4.

Upgrade Amazon Elastic search audit cluster to the latest version 7.4

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-version-migration.html

We upgraded cloud-platform-live to 7.4 already.

Fluentd in live-1 and manager cluster is sending logs to both cloud-platform-audit and cloud-platform-live cluster. So it is ideal to maintain both ES clusters to be on the same version.

https://console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=7053991501&language=en

**Comment by AntonyBishop** [comment]
Done
