### ISSUE TITLE
Enable slow logs on the AWS cloud-platform-live Elastic cluster

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#1959]
We faced AWS ES going down recently and we took aws support to debug the issue, aws team supported to enable slow logs to our ES clusters.

AWS support suggested to enable slow logs on the cluster as it helps to identify whether a performance issue on your cluster is being caused by particular queries or is due to changes in usage.

https://aws.amazon.com/blogs/database/viewing-amazon-elasticsearch-service-slow-logs/ 

This is related to 
https://github.com/ministryofjustice/cloud-platform/issues/1939

**Comment by AntonyBishop** [comment]
May not be required when Loki inplemented.

**Comment by AntonyBishop** [comment]
Close due to age of story.
