### ISSUE TITLE
Standardise cloud platform pingdom checks

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#196]
## Background

The pingdom checks that alert the cloud platform can be quite different in their definition -- they can vary in how often they run and how long before they send an alert. We want to make these consistent by having *one alert for each service we run* that has:

1. A consistent check interval (e.g. check every two minutes)
2. A consistent alert time (e.g. alert after 3 failures, after 5 mins)
3. Uses the webhook method to alert rather than email 

Also where possible we want each of the alerts to: 

4. Check the `/healthcheck.json` endpoint -- this isn't possible in every case as the endpoint isn't always defined, if that is the case then it checks the homepage of the app for a `HTTP 200` response. 

## Approach

- Use the terraform provider (see #195 )

## Questions / Assumptions

- For services that we do no manage, should we remove the cloud platform team as a recipient of alerts (I think yes) 

## Definition of done

- [ ] Each service that we run has 1 pingdom check that alerts our team
- [ ] Each pingdom check that alerts our team has the same check interval and alert time
- [ ] Each pingdom check we have defined uses the webhook method to pagerduty to alert us

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sid234** [comment]
Tasks -
Pingdom-
- List of managed services in pingdom
- Check the health check endpoints (Some systems have more than 1 alert)
- Web hook integration in pingdom to pager duty to SMS/HTTPS/email endpoints
- Create a new integration in pingdom for each service
- Create a new service for cloud platform
PagerDuty-
- Create service & web hook in pagerduty
- Create a new terraform template for pager duty
- Identify naming conventions for Tagging the service (eg- CP-service)

**Comment by sid234** [comment]
The work is continued with checking pingdom alerts are in the terraform
https://github.com/ministryofjustice/cloud-platform/issues/195
