### ISSUE TITLE
FIREBREAK IDEA: Create a cloud-platform cli

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1961]
The cli should allow the end user (developers using the platform) to create a resource. This could be something easy to start with, like query running pods in their namespace.

Like heroku, the cli should be called something short and easy to remember and eventually be able to perform all actions needed by a developer (although, this is out of scope for this ticket)

  ```
e.g. moj-cp create environment
  ```

**Comment by digitalronin** [comment]
Just a thought: if we're planning on using "create RDS" as an example, how about adding a standard set of prometheus alerts at the same time, like this one:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/alert-rds.html#rds-metrics

**Comment by poornima-krishnasamy** [comment]
CLI commands created in repo: https://github.com/ministryofjustice/cloud-platform-cli
