### ISSUE TITLE
Migrate Concourse authentication from Github OAuth to Auth0 

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#1964]
Concourse is using Github OAuth instead of Auth0 (as all our apps). We should migrate it to use Auth0 because of 1) consistency (all our apps using the same methodology 2) Test clusters can reuse their auth0 entries they create when they're bootstrapped

**Comment by poornima-krishnasamy** [comment]
If using Auth) as the OIDC provider, the RBAC roles : members(webops) and viewer(orgs) needs to be mapped to Auth0 users.

https://github.com/ministryofjustice/cloud-platform-terraform-concourse/blob/main/templates/values.yaml#L76-L81
```          - name: member
            github:
              teams: [ "${github_teams}" ]
          - name: viewer
            github:
              orgs: [ "${github_org}" ]
```
 Auth0 doesnot have similar mapping and treat everyone has the user with viewer mode when connecting to Github. Hence it was not possible to create OIDC connection between concourse - Auth0 - Github with different user roles permissions.
