### ISSUE TITLE
Enable a tag that users can set to allow a public s3 bucket

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1966]
Currently, any s3 buckets that users want to be public (usually because they're used to serve static assets for web applications), must be individually whitelisted so that the security lambda function doesn't make them private again.

It would be a lot nicer if there were a tag that users could apply via terraform - something like "allow-public-access" - which the lambda function could look at when it runs, and allow the bucket to remain public if the tag is set.

**Comment by AntonyBishop** [comment]
Close due to age of story.
