### ISSUE TITLE
Increase worker_groups type/size for EKS cluster.

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#1969]
We are getting CPU-HIGH Alert for EKS.
Alert: This device's CPU usage has exceeded the threshold with a value of 94.61666666669771. Instance XXXX CPU usage is dangerously high

Increase worker_groups type/size for EKS cluster to fix the Alert.

We are using a module for EKS.
https://github.com/terraform-aws-modules/terraform-aws-eks

Try it on a test EKS cluster with Increase worker_groups type/size and once happy, apply it to Manager cluster.

Add Run book on how to increase nodes or worker_node_machine_type for EKS

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/752
to increase the instance type size

https://github.com/ministryofjustice/cloud-platform/pull/1976
Runbook for future reference
