### ISSUE TITLE
Make sure pingdom and pagerduty are in sync

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#197]
## Background

Pingdom checks should alert us in #high-priority-alarms or #low-priority-alarms via pagerduty. However we suspect that the pingdom checks and the pagerduty alerts are out of sync. We want to: 

- check all of the pagerduty alerts to make sure that there are checks defined in pingdom to trigger them
- check all of the pingdom checks to make sure they are connected to a pagerduty alert

## Approach

- A pingdom alert should use a webhook to connect to pagerduty. 

## Definition of done

- [x] All of the pingdom check are connected to a pagerduty alert 
- [x] All of the pagerduty alerts have a pingdom check that sets them off

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by lukaszraczylo** [comment]
Connected to #195
