### ISSUE TITLE
Export log entries from Kibana/ES into a CSV

### ISSUE THREAD

**Issue by ollietreend** [ministryofjustice/cloud-platform#1970]
## Manage Offenders in Custody (MOIC)

Kubernetes namespace: offender-management-production

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

This will enable us to understand how to clean up some bad data contained within our service, which in turn is blocking us from releasing a new feature to our end users.

Without it, we won't be able to make decisions about how to proceed with the data clean-up.

## Problem description

We have a cron job which [runs every weeknight in production](https://github.com/ministryofjustice/offender-management-allocation-manager/blob/0b5441b328fbd009d0806c62a0f49159e4c564a2/deploy/production/cronjob.yaml#L50-L96). We've recently done some work to make that job log useful error messages which will help us fix some problems with bad data in our service.

There are two saved queries in the 'Discover' section of Kibana which return the error logs that we want to interrogate:

- [MOIC: Missing LDUs from Delius import](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover/94acdb00-8f85-11ea-8cf8-25523946b131?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-06-11T16:00:00.000Z',to:'2020-06-12T16:00:00.000Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d1d23280-fc8e-11e9-a859-bbe630739c91,key:kubernetes.namespace_name,negate:!f,params:(query:offender-management-production,type:phrase),type:phrase,value:offender-management-production),query:(match:(kubernetes.namespace_name:(query:offender-management-production,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d1d23280-fc8e-11e9-a859-bbe630739c91,key:kubernetes.container_name,negate:!f,params:(query:allocation-manager-sidekiq,type:phrase),type:phrase,value:allocation-manager-sidekiq),query:(match:(kubernetes.container_name:(query:allocation-manager-sidekiq,type:phrase))))),index:d1d23280-fc8e-11e9-a859-bbe630739c91,interval:auto,query:(language:lucene,query:'%22Couldn!'t%20find%20LDU%22'),sort:!(!('@timestamp',desc))))
- [MOIC: Missing teams from Delius import](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover/9c9b30a0-8f85-11ea-9ede-afc1bbc9207c?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-06-11T16:00:00.000Z',to:'2020-06-12T16:00:00.000Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d1d23280-fc8e-11e9-a859-bbe630739c91,key:kubernetes.namespace_name,negate:!f,params:(query:offender-management-production,type:phrase),type:phrase,value:offender-management-production),query:(match:(kubernetes.namespace_name:(query:offender-management-production,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d1d23280-fc8e-11e9-a859-bbe630739c91,key:kubernetes.container_name,negate:!f,params:(query:allocation-manager-sidekiq,type:phrase),type:phrase,value:allocation-manager-sidekiq),query:(match:(kubernetes.container_name:(query:allocation-manager-sidekiq,type:phrase))))),index:d1d23280-fc8e-11e9-a859-bbe630739c91,interval:auto,query:(language:lucene,query:'%22Couldn!'t%20find%20team%22'),sort:!(!('@timestamp',desc))))

We're want to see all log entries matching the above queries within the 24-hour period:
- 2020-06-11 17:00:00 to 2020-06-12 17:00:00

These queries return 2751 and 1704 results, respectively, for that date range. We need to see all of those log entries to get a complete picture of how our application is behaving, but Kibana's web interface limits us to only seeing 500 entries. There doesn't seem to be any way for us to access the rest of those results beyond the first 500.

I believe the Cloud Platform team have the required access permissions to run [es2csv](https://github.com/taraslayshchuk/es2csv) against the Elasticache cluster which contains this data.

Could you please export the complete result sets for the above two Kibana queries into two CSV files for us? We're asking for this as a one-off request, rather than a regular export.

Thanks

## Contact person

Ollie Treend
Slack: Ollie Treend
Email: ollie.treend@digital.justice.gov.uk

**Comment by vijay-veeranki-moj** [comment]
We raised a support request to AWS as we don’t have that option available even though we upgraded to ES 7.4. Response from AWS below.

Hello there,
I trust you are well. Thank you for contacting AWS Premium Support. Mikyle here and it will be my pleasure to assist with this case.
From the case notes, I gather that you have upgraded to your Elasticsearch (ES) Cluster 'cloud-platform-live' to AWS ES 7.4 to get a specific feature of Kibana which is to export to a CSV file, you however have noted that the option/button to 'Generate a CSV' on Kibana is missing and as such you would like some guidance on how to achieve this use case.
The CSV Export feature in Kibana is a proprietary feature of Elasticsearch that requires X-Pack to be configured and installed in your Elasticsearch cluster which is not provided and supported in the Open Source Elasticsearch or the Elasticsearch that is offered by AWS. X-Pack is proprietary software that requires a License that can be free or paid for through registration with Elasticsearch via Elastic co.
The guides that you mention on the case are all relating to the non-opened source version of ES provided by Elastic co.
Unfortunately this feature is not available on AWS Elasticsearch Clusters, and I apologize that AWS Elasticsearch does not have the functionality that you seek. As workaround, I have found the following possible solutions for you :
(1) Using AWS ElasticSearch, you can only export a non-string fields to CSV from Kibana using the below method: 
1. Save a search
2. Create a Visualization from the saved search: https://www.elastic.co/guide/en/kibana/6.8/createvis.html  
3. Click on caret symbol (^) which is present at the bottom of the visualization.
4. Then you will get an option of Export:Raw Formatted as the bottom of the page.
(2) The other workaround, is using "es2csv", which is a third party tool that saves the search result table as it is to a CSV file. Please refer this blog page for more information[1]. Please note, es2csv is a third party tool and thus is not within the scope of the support offered by AWS Support.
To install es2csv:
	pip install es2csv
Usage:
	es2csv -q 'price:>15' -u https://<ES_endpoint>:443 -i rollover-test-* -f ticker_symbol sector price -o kibanatest.csv
	Here, the parameters are :
		-q Query
		-u URL
		-i Indices
		-f Fields to be preserved
		-o Output file name
There is a standing feature request to export Kibana search results, dashboards and visualizations as CSV/PDF. I will go ahead and add this case as a +1 to the feature request.
I trust the above information finds you well and should you have any further queries, feel free to reach out and I will gladly assist.
Have a great day further!
References:
[1] https://www.skedler.com/blog/the-best-tools-for-exporting-elasticsearch-data-to-csv/

**Comment by vijay-veeranki-moj** [comment]
es2csv is not supported for ES 7.x

This tool supports only 2x and 5x versions of Elasticsearch. It does not support 6.x or 7.x
You need Python 2.7.x and pip. So you must install a python environment in your system.

https://github.com/taraslayshchuk/es2csv#requirements

**Comment by vijay-veeranki-moj** [comment]
Exported to CSV and shared it to Ollie.

python2.7 -m pip install git+https://github.com/gboddin/es2csv.git

es2csv -r -q @'./moic2.json'  -u https://search-cloud-platform-live-dibidbfud3uww3lpxnhj2jdws4.eu-west-2.es.amazonaws.com:443   -o moic2.csv --verify-certs
