### ISSUE TITLE
Firebreak: Experiment with kube-monkey

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1972]
Kube-monkey is an implementation of Netflix's Chaos Monkey for Kubernetes clusters. It randomly deletes Kubernetes (k8s) pods in the cluster encouraging and validating the development of failure-resilient services.

https://github.com/asobti/kube-monkey

Find a way we can offer this as a service to users, perhaps a Terraform module?

Trial using it on an application in our control.

**Comment by sablumiah** [comment]
Unfortunately its unlikely we can implement this for users to use in their namespaces (only)  easily.
Kube-Monkey and chaoskube are designed to be used at a cluster level. They require cluster level rbac and would require many changes to the point that it would be quite difficult to maintain for users to use and not accidently affect other user namespaces.
