### ISSUE TITLE
Add slack room name to create-namespace-files.rb

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1974]
It's frustrating and time consuming to find the name of the slack channel of a team. 

Our current process for creating a namespace is well established. This ticket proposes that we add the slack channel (name only) as an annotation in the namespace resource.

To achieve this you must do the following:
- amend the questions here: 
https://github.com/ministryofjustice/cloud-platform-environments/blob/master/bin/create-namespace-files.rb#L121
- add a line to the namespace templace to interplotate the answer here:
https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespace-resources/00-namespace.yaml
- amend the user-guide
- anything else you can think of.

**Comment by digitalronin** [comment]
Once we have a place to put the channel name in the namespace definition files, we could create a spreadsheet of namespace names and post in #developers and #ask-cloud-platform to ask users to fill in the channel names, where they're missing.
