### ISSUE TITLE
Transit Gateway VPN attachment

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1977]
As Transit Gateways are getting increasingly important for the MoJ and CP, we need to look at Cross Cloud connection.

Hypothetical  usecase : we want to enable connectivity from an Azure VNet to an AWS VPC.

Questions: 
Is it possible for the Transit Gateway to accept VPN connections  from within AWS? 
Is it possible for the Transit Gateway to accept VPN connections  from outside AWS?

**Comment by kcbotsh** [comment]
Azure account ready to use?

**Comment by sablumiah** [comment]
Spoke to Greg Bennet and in turn to Richard Baguley:

We will be connecting to the Digital Studios Azure tenants using IPsec Tunnels but… initially this is a tactical solution using Palo Alto Firewalls until we get sign off to do a landing zone under the many …. many vnets which are present. Ideally we would have used AWS IPsec GW and Azure VPN Gateway. But that would mean hundreds of those on each VNet in Azure.
So we will place two Palo Alto VM Firewalls each side and create a IPSec tunnel. The VMs on AWS side will be in a VPC attached to TGW
Moving forward we will have a IPsec tunnel from Transit GW to Azure landing zone GW or a Virtual WAN TBC…. while commercial do their thing.

We will be making those IPsec tunnels via terraform

On Azure side the DSO team will complete theirs.
