### ISSUE TITLE
Investigate Checkov

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#1978]
[https://github.com/bridgecrewio/checkov](https://github.com/bridgecrewio/checkov)

Chekov is a static code analysis tool  for _infrastructure as code_(terraform, kubernetes, etc.)

Could it be used to protect us for preventable mistake ? 
Could it help us ensure the namespace labels are valid (`owner` being a valid email address, etc.)

**Comment by vijay-veeranki** [comment]
Findings in the doc:

https://docs.google.com/document/d/1RVeJg4tVfdabbQRksweoMimK9stQC612FR8-skOGcjQ/edit#

**Comment by vijay-veeranki** [comment]
Created this ticket as part of this spike.

https://github.com/ministryofjustice/cloud-platform/issues/2033
