### ISSUE TITLE
Offer a recent version of Docker on https://ci.service.dsd.io/

### ISSUE THREAD

**Issue by rowlando** [ministryofjustice/cloud-platform#198]
## Service name

Civil Legal Advice

## Impact on the service

CLA's codebases and CI have been neglected over the years. Some of the tests do not pass and the end-to-end tests don't run on Jenkins. Plus the build takes longer than it should and the Docker image is massive 1.4gb, which makes it slow to push the image to the registry.

The main impact is a slow build and test cycle. We want a couple of minutes, rather 8 or 9 minutes.

## Problem description

I've spent some time re-working the Dockerfile locally to take advantage of [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds). This significantly speeds up builds, plus the final image is significantly smaller.

One of the other benefits is that I can set up one of the intermediate stages to include all the dependencies required to run headless chromium tests in, ensuring the final Docker image contains only what is need for production.

These are the details reported by `docker version`:

![screen shot 2018-06-26 at 16 19 40](https://user-images.githubusercontent.com/89347/41922358-d2b4b314-795c-11e8-9ed0-de02ddcb6afd.png)

## Contact person

Slack: @nick
Email: nick.rowlands@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
When we get to this: as discussed I'd recommend installing a separate slave VM with the needed release of Docker on it, not upgrading the master

**Comment by razvan-moj** [comment]
deploying a new slave, with latest Ubuntu LTS and Docker

**Comment by razvan-moj** [comment]
Done, see user data in launch template 'jenkins-docker-slave' https://eu-west-1.console.aws.amazon.com/ec2/v2/home?region=eu-west-1#LaunchTemplates:sort=launchTemplateId

The second part of the setup in is Jenkins' web interface: https://ci.service.dsd.io/computer/

**Comment by rowlando** [comment]
Just saw this @razvan-moj.

I cannot access the first link you posted. Do I need to know what's there?

**Comment by razvan-moj** [comment]
Hi @rowlando, it's the VM install script so only useful if we want to start over
