### ISSUE TITLE
Find a way to associate one IAM account with all AWS resources

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1981]
When a user has to create a number of AWS resources, they end up creating multiple IAM accounts and Kubernetes secrets (see below). This could be made easier by having one IAM user with access to all resources in a namespace (and subsequently one k8s secret).
https://github.com/ministryofjustice/cloud-platform-environments/pull/2579

Investigate a way to implement this.

**Comment by AntonyBishop** [comment]
Close due to age of story.
