### ISSUE TITLE
Create the NS records for manage-soc-cases-dev.service.justice.gov.uk please

### ISSUE THREAD

**Issue by timharrison-moj** [ministryofjustice/cloud-platform#1988]
## Service name
manage-soc-cases-dev

Manage Serious Organised Crime Cases

## Service environment

- [ X] Dev / Development

This service will be present in development for several weeks before we create a preprod or prod environment in Cloud Platform. At present we are going with the plan of having a separate DNS zone for each environment, but as a result of an ongoing conversation between the TAs, this might change if a suitable domain can be decided upon for services which span the prison and probation areas.

## Impact on the service

This is a new service created in development this week and requires its DNS zone setup to be completed.  I've created the route53 entry in the cloud-platform-environments repo, and the team now require access in development to see and demo the service.

## Problem description

This was the guidance from the link provided :

"Once the zone is created, you will need to setup the necessary name server (NS) records in the parent DNS zone, before you’re able to use it. For more information on how this delegation method works, you can read about authoritative name servers in this"

## Contact person

Email: tim.harrison@digitial.justice.gov.uk

Slack: timharrison114

**Comment by digitalronin** [comment]
Done.

**Comment by timharrison-moj** [comment]
Thanks, appreciate the quick turnaround.
