### ISSUE TITLE
Remediation for Auth0's limit reached

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#1995]
Due to auth0's new limitations (max 10 application), we are facing:

```
Error: 403 Forbidden: You reached the limit of entities of this type for this tenant.
  on main.tf line 158, in resource "auth0_client" "kubernetes":
 158: resource "auth0_client" "kubernetes" {
```

It means we can only have 5 clusters running (each cluster uses two applications). `manager` and `live-1` are a must so we only get remaining 3 test clusters to play with.

We have different choices to solve this problem:

## Option 1: Move Auth0 to its own terraform-state (discussed during our team's meeting)

Moving [auth0 resources](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/terraform/cloud-platform/main.tf#L158-L226) outside of `cloud-platform/` terraform state to its own folder (similar to what we have with networking). This will allow us to reuse auth0 components, we are not going to create each time. 

It will require from us to reference these resources using terraform remote states within cloud-platform/`. The reference should happen with conditionals: for live cluster we'll have its own auth0 applications and for test clusters, we'll reuse a common existing one.

## Option 2: Add conditional to deploy auth0 resources.

If we add a conditional to deploy auth0 resources we should be able to decide when to create or not the auth0 resources, for instance:

```
...
...
resource "auth0_client" "components" {
  count          = lookup(var.auth0_live_cluster, terraform.workspace, var.auth0_live_cluster["default"])

  name           = "${local.cluster_name}:components"
  description = "Cloud Platform components"
....
...
```

Once we have the condition we just need to set as an output base on: either in the ones we create (for live clusters one, for instance) or the one specified in the code for test clusters (can be a hardcoded one or one created just for test clusters).

With this approach, we don't need to split anything into different states and it is fewer changes.

**Comment by vijay-veeranki** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/compare/66fbdc98da2f...bcecd185b00f
