### ISSUE TITLE
Advise on tagging for Tactical Products 

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#200]
## Service name

Advice with tagging AWS resources for Tactical Products

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Non service impacting. Team might be unable to complete tagging of all resources

## Problem description

Request for some advise in identifying AWS resources that need to be tagged. Having carried out our own tagging we will have some insights which may help.

## Contact person

Contact is Matt Tei, matt.tei@digital.justice.gov.uk, @matttei

**Comment by nayoa** [comment]
Advice has been given to Matt on how our tagging process was setup i.e. used Tag Editor. 

The AWS account 'tacticalproducts' doesn't use template deploy or deploy it's AWS infrastructure through cloudformation so the method we have used may be suitable for Tactical Products. 

This ticket can now be closed and further advice can be given when needed.
