### ISSUE TITLE
Move Kibana oidc-proxy into cloud-platform-terraform-monitoring

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2006]
When we rotated our auth0 credentials we realised some components like [Kibana oidc-proxy](https://github.com/ministryofjustice/cloud-platform-environments/tree/master/namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring) are not aligned with our pattern of trying to group infrastructure components into terrafom modules.

The idea of this ticket is to migrate Kibana OIDC proxy into `cloud-platform-terraform-monitoring`

**Comment by AntonyBishop** [comment]
Close due to age of story.
