### ISSUE TITLE
Restrict who can raise PRs on specific env. repo. namespace folders

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2009]
Currently, any MoJ developer can raise a PR to make changes to *any* namespace
folder in the environments repo.

There is a risk that, e.g. someone could raise a PR to delete a production
namespace, by accident. We might not notice this, at the review stage, because
we (the CP team) wouldn't know that the person who raised the PR was not in the
github team which owned the namespace.

The [code owners] feature of github may enable us to automatically create
namespace folders such that only the relevant teams can raise PRs to change
them (or, at least, that members of the appropriate team(s) are notified
whenever someone else does).

[code owners]: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

**Comment by davidread** [comment]
Another option might be to add an automated check for the PR

**Comment by AntonyBishop** [comment]
Duplicate
