### ISSUE TITLE
Take on ownership and maintenance of kuberos

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2017]
https://github.com/negz/kuberos

We currently depend on kuberos, but it's abandonware.

Explore the repo and figure out how practical/desirable it would be to take
ownership of the project.

We also have no way of authenticating to our EKS cluster using github as the
identity provider. Would it be feasible to modify kuberos such that we could
use it for EKS as well?

We could try doing this, to get a good understanding of what would be involved, and if we're happy to do so a) feed back our EKS changes as a PR, and b) raise the possibility of taking on maintainer role for the project.

**Comment by jasonBirchall** [comment]
Forked
https://github.com/ministryofjustice/kuberos

**Comment by jasonBirchall** [comment]
I'm going to call time on the Kuberos take over ticket. Our intention is to make this work with EKS but Kuberos requires you to enable OIDC on the Kubernetes API, which you cannot do in EKS (you can in Kops).  EKS only supports a particular Kubernetes webhook token auth, backed by IAM. There are plenty of tools for creating webhook tokens, one of them is from the creator of Kuberos, which is probably why the project is stale. My suggestion is that we look at kubehook and re-open the investigation into kube-oidc-proxy.
https://github.com/negz/kubehook
https://github.com/jetstack/kube-oidc-proxy
