### ISSUE TITLE
Cluster Usage Report  - Monetary Value 

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2025]
https://github.com/hjacobs/kube-resource-report

Spike this to see if it will help us answer when teams ask "How much does it cost to run our service on CP?"

We would probably also need to break down shared resources cost to give a more accurate figure.

**Comment by digitalronin** [comment]
I'm trying https://infracost.io first, which seems like an interesting approach to get the AWS costs. I'll look at merging with data from kube-resource-report as a next step.

**Comment by digitalronin** [comment]
An initial version of this is up and running:
https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk/namespace_costs
