### ISSUE TITLE
Introduce a default PodSecurityPolicy

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#203]
## Background

For the cluster to be multi-tenant ready, we need to have an `PodSecurityPolicy` in place that prevents Pods from running with elevated permissions. This policy must be applied by default on all pods and a user should not be able to alter it.

## Proposed user journey

As a user, there should be a `PodSecurityPolicy` that prevents me from creating a `Pod` that requests elevated privileges.

As a Cloud Platform member, I need to have access to a secondary `PodSecurityPolicy` that I can use with `Pods` that require elevated privileges.
 
## Approach

Define the default, unprivileged `PodSecurityPolicy` to be used across all environments (namespaces) and apply it.

Additionally, define the default privileged `PodSecurityPolicy` to be used as an exception for cluster-level resources that might require this (eg. `node-exporter`, possibly `concourse`) and apply it.

These can both be quite generic for the scope of this ticket (ie. the privileged policy can simply allow everything).

Enable the admission controller for PSPs and make sure everything works.

## Questions / Assumptions
N/A

## Definition of done

- [x] There is a default unprivileged `PodSecurityPolicy` defined.
- [x] There is a default privileged `PodSecurityPolicy` defined.
- [x] All `Pods` use the unprivileged `PodSecurityPolicy` by default.
- [x] `Pods` that need elevated access are setup to use the privileged policy.
- [x] Users cannot alter the `PodSecurityPolicies`.
- [x] The relevant admission controller is enabled.
- [x] Any kubernetes configuration used to achieve the above (eg. `RBAC` and `PSP`) is managed in the environments repository (for non-namespaced resources like the PSP use the top level directory of the cluster).
- [x] Test that all the core services in the cluster work properly.
- [x] Test that a user can deploy an unprivileged `Pod` but is blocked from creating privileged `Pods`.

## Reference

https://kubernetes.io/docs/concepts/policy/pod-security-policy/

**Comment by jasonBirchall** [comment]
psp applied to the test cluster successfully. Live-0 will be a bit more tricky, so will need proper planning as there may potentially be an outage. Perhaps perform this OOH.

**Comment by jasonBirchall** [comment]
psp now in test-1 but will hold off putting into live-0. This will however be included in the new cluster creation pipeline. 

Work that still needs doing:
- install on a live cluster.

**Comment by AntonyBishop** [comment]
Decision made to not apply to Live-0. Will be picked up with migration of services to Live-1
