### ISSUE TITLE
Update the circleci stats collector

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2032]
We've changed our circleci plan, so we now have access to

https://circleci.com/docs/api/v2/#circleci-api-insights

Have a look at what's available and either update our existing stats collector job, or retire it and document its replacement (if we can get what we need more easily via the new API).

**Comment by davidread** [comment]
Arguably not this team's job

**Comment by AntonyBishop** [comment]
Moved to Ops Engineering
