### ISSUE TITLE
Standardising tags

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2034]
## Background

We still have resources that are not tagged or tagged inconsistently. This makes it hard to report on and assign costs to things.

`business-unit` is a prime example. For one Business Unit you can have a lot of variation e.g. `HMPPS`, `hmpps`, `Her Majesty's' Prison & Probation Service`. We should look to standardise tags if we can to ensure everything is tagged and tagged in a consistent way.

## Approach

This story is just to do some initial investigation into whether we can standardise tags. If we can we should look at possible solutions as part of this story. 

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

1. Can we standardise? 
2. What rules do we need? 
3. How to we enforce standards? 
4. Do we need to retro fit this change to existing tags?

## Definition of done

- [ ] Confirm that we can standardise tags
- [ ] Come up with a potential solution

We'll implement via another related story.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by kcbotsh** [comment]
This is now super-ceded by #2063

**Comment by AntonyBishop** [comment]
Done
