### ISSUE TITLE
Expand JSON log payloads

### ISSUE THREAD

**Issue by mafonso** [ministryofjustice/cloud-platform#2036]
## Service name

book-a-secure-move

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production

## Impact on the service

Improvement request

## Problem description

Currently fluentd is ingesting the raw container logs and making a JSON quoted object from pod log lines.  This is desirable for plain text logs in order to make them a json object to be included in the main ElasticSearch document.

But if the application is logging valid JSON, it is desirable to parse it as such and expand those fields into the main document (root level under `log.` is not relevant for us) 

There was a plugin for that that seems to be part of the core Fluentd parsers in current versions, so we likely just need to use the `json_in_json`parser, which tentatively tries to parse json before falling back to the `json` behaviour.

ref: https://github.com/fluent/fluentd-kubernetes-daemonset/pull/328/files/7aec1a7422dcbbe8c2e58cf583cbf6046550f756#diff-8fe7994999b89f07b72dfd08dccdb4c6R20

## Contact person

@mafonso
@willfish

**Comment by jhevans** [comment]
👍  probation-in-court team would really like to have this capability, I'm happy to help out if I can, we've already configured one of our apps to output json so can turn this on whenever.

**Comment by ushkarev** [comment]
when our service (money-to-prisoners) was still using the `template-deploy` mechanisms, we also had all logs output in JSON format. now we have a mixture because we haven't bothered to stick to json format :)

json-in-json is also useful for multiline log output to not get rearranged in kibana (which it does arbitrarily if the timestamp for several lines is the same). we toyed with using prometheus metrics instead of kibana fields for delivering custom variables into some monitoring platform, but don't actually monitor them!

anyway, this "issue" is not a big deal for us at all; – if it happens we'll probably use it, if not doesn't matter!

**Comment by mogaal** [comment]
@mafonso @ushkarev @jhevans we just deployed fluentbit in live-1 clusters. In theory, we should be able to use custom parsers as specified here: https://docs.fluentbit.io/manual/pipeline/filters/parser

They can be a regex or if the content inside `log` is just JSON we can use the generic JSON parser [using a pod annotation](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#annotation-examples-in-pod-definition). Who wants to be the first one giving a try? :-)

**Comment by digitalronin** [comment]
related to #2252

**Comment by vijay-veeranki** [comment]
Worked with Miguel, using the `generic-json` parser and annotating the pod as below with parser.

annotations:
    fluentbit.io/parser: generic-json

I think it may be to do with this “Merge_Log   On” and  “Merge_Log_Key   log_processed”.

We have disabled this for the logs sent to kubernetes_cluster index and parser is working fine.
https://github.com/ministryofjustice/cloud-platform-terraform-logging/blob/main/resources/filter-kubernetes.config#L20-L21

Need to find a better parser so we can change this “Merge_Log   On” and  “Merge_Log_Key   log_processed”.

**Comment by poornima-krishnasamy** [comment]
Tried "Merge_Log On" is set which gave errors 

```"status":429,"error":{"type":"es_rejected_execution_exception","reason":"rejected execution of processing of [378348972][indices:data/write/bulk[s][p]]: request: BulkShardRequest [[kubernetes_cluster-2020.09.10][4]] containing [107] requests, target allocation id: JcXtoC7PROeVYEQ5vkVjQA, primary term: 1 on EsThreadPoolExecutor[name = 3247d9c268eaf10c
[2020/09/10 17:45:39] [ warn] [engine] failed to flush chunk '1-1599759938.156302959.flb', retry in 10 seconds: task_id=2, input=tail.0 > output=es.0```
 
Some users suggested to increase the node to cope with the increasing shards request. But that lead to another issue

```
"status":400,"error":{"type":"illegal_argument_exception","reason":"Limit of total fields [1000] in index [kubernetes_cluster-2020.09.10] has been exceeded"}}},{"index":{"_index":"kubernetes_cluster-2020.09.10",
```
When the Merge_log turned on, all fields in the log are parsed with json format. Each key of json pair is a field  in the elasticsearch. That lead to increase of fields per indices if the logs has numerous key,value pairs. ES has the limit of 1000 fields per indices. 

https://www.graylog.org/post/what-to-do-when-you-have-1000-fields#:~:text=As%20mentioned%20above%2C%20Elasticsearch%20keeps,thus%20breaking%20the%201000%20limit.

 Hence convert users log directly into json format and to be consumed as fields in elasticsearch can work if each of the namespace is an index in elasticsearch. Thereby can reduce the number of fields per index to less than 1000.

**Comment by AntonyBishop** [comment]
At the moment we do not have a suitable way to do this. This is partly due to the way that the original logging solution was implemented. We are intending to resist our logging architecture and user needs. Until then we are unable to meet this specific need.
