### ISSUE TITLE
Cloud Platform got Auth0 enterprise account 

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2039]
Cloud Platform team got auth0's enterprise license! We can revert the auth0 changes done two weeks ago in order to use two auth0 applications per cluster (components & Kubernetes). 

This ticket involves creating a new release of [auth0's terraform module](https://github.com/ministryofjustice/cloud-platform-terraform-auth0) reverting the [last commit's changes](https://github.com/ministryofjustice/cloud-platform-terraform-auth0/commit/671914df5040fa163dc342e47208114f09e1f6cd)  and applying the changes to all our clusters

**Comment by digitalronin** [comment]
May also need an update to our kops template/commands
