### ISSUE TITLE
Fix global-resources terraform state

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2050]
Currently the global-resources terraform state doesn't apply without a number of AWS credentials. This is due to GuardDuty trying to apply in multiple accounts. 

I propose that we remove all GuardDuty entries bar the Cloud-platform account. Other AWS accounts will eventually cease to exist or can be managed elsewhere (non Cloud Platform accounts)

Definition of done:
- Global resources applies without multiple credentials.

**Comment by AntonyBishop** [comment]
Closed due to age of story
