### ISSUE TITLE
Replace Auth0 Documentation in the Infra repo

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2053]
There is an Auth0 dir in the [cloud-platform-infrastructure](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/new/auth0-provider/auth0). It is probably worth keeping hold of the knowledge, but perhaps updated and moved to the [runbooks](https://runbooks.cloud-platform.service.justice.gov.uk/) site.

**Comment by AntonyBishop** [comment]
Closed due to age of story
