### ISSUE TITLE
Improve the user guide entry on DNS & hosted zones

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2054]
The relationship between DNS, hosted zones, domain names, external-dns, and
cert-manager is quite complex, and it seems some of our users don't understand
clearly how they should structure that part of their service. In particular, we
often see people create hosted zones which are duplicates of existing hosted
zones, which don't need to exist and won't be used (because external-dns just
uses the first relevant zone that it finds).

Improve the user guide guidance in this area, ideally including some simple
diagram(s) explaining how this all fits together.

**Comment by AntonyBishop** [comment]
No longer required.
