### ISSUE TITLE
Create 'cloud-platform' cli for s3 bucket

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2058]
## Background

Create a cli command which will generate terraform files for creating the s3 bucket and relevent resource using the [s3 terraform module ](https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket) for the end user inside their namespace folder in [environment repo](https://github.com/ministryofjustice/cloud-platform-environments)

It can be `cloud-platform environment s3 create`

## Approach

Add cli command to [this repo](https://github.com/ministryofjustice/cloud-platform-moj-cp) 

Add tests to verify the cli command

## Definition of done

- [x] cli created and tested
- [x] readme has been updated
- [x] another team member has reviewed
- [x] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-cli/pull/33
