### ISSUE TITLE
Introduce a default NetworkPolicy

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#206]
## Background

For the cluster to be multi-tenant ready, we need to have a default `NetworkPolicy` for environments.

## Proposed user journey

As a user, when I create a new environment, it should come with a `NetworkPolicy` that blocks an inbound traffic except for traffic coming from the nginx ingress controller.

## Approach

Define the default `NetworkPolicy` and apply it to all existing namespaces.

## Questions / Assumptions

N/A

## Definition of done

- [x] the default `NetworkPolicy` is defined and it will block all inbound traffic except from that coming from the ingress controllers
- [x] the policy has been applied to all existing environments and its configuration has been added to the environment directories in the environments repository.
- [x] has been tested by trying to access a service from a pod running in another namespace

## Reference
https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by kalbir** [comment]
I removed the connection to #204 and added this to a milestone instead.

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/105
