### ISSUE TITLE
Cloud Platform Tagging

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2063]
## Background

MoJ already has a [tagging policy](https://ministryofjustice.github.io/technical-guidance/standards/documenting-infrastructure-owners/#documenting-owners-of-infrastructure) for infrastructure.

Unfortunately this policy is not applied consistently by all users of the platform. This is due to policy not being automatically enforced, and variation i.e. the same Business Area may be described on 4 or 5 different ways. This makes it difficult to be able to get any value from use of tagging.

If we can address this problem we can start to be able to use that information to do some valuable things: 
- better understanding of how much things cost
- better understanding of how resources are being consumed
- clearer ownership of services running on the platform
- share best practice across the platform

We can make that information visible to our users.

## Approach

Phase 1: Consistent tagging
1. We need to review what tags we currently use to ensure that those tags are useful
2. Define some standard conventions for tags
3. Enforce tagging so that new infrastructure can't be created without appropriate tags
4. Retro-fit new tagging standards to existing infrastructure

Phase 2: Introspect the Platform 
5. Costs
6. Resource utilisation
7. Best practice
8. Targeted user engagement/communications

**Comment by davidread** [comment]
Most AWS things are tagged, thanks to @digitalronin 's tagging for cost explorer.

k8s things need tagging too.

We should add a policy for AWS and k8s to ensure everything is tagged (enforcing).

**Comment by davidread** [comment]
Can't see big drivers for doing any more on this right now.
