### ISSUE TITLE
User Guide: Add advice on structuring a service for the Cloud Platform

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2064]
This would include general advice for developers/architects who might not be
familiar with kubernetes, and how to optimise application architecture for it.

Examples of topics that should be covered include:

* Using multiple, single-purpose containers rather than fewer containers running multiple components
* How to keep your docker containers light, and why that's important
* Design your application to tolerate pods being moved around
* Storing state in managed AWS services

Also, the advice [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/concepts/migrate-from-td.html#application-architecture)
should be included. Consider replacing that section with a link to the new document.

**Comment by AntonyBishop** [comment]
Closed due to age of story
