### ISSUE TITLE
Add tests to cloud-platform CLI

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2067]
## Background

cloud-platform CLI can run below commands.

Create tests for the commands
`cloud-platform environment create`
`cloud-platform environment rds create`

https://github.com/ministryofjustice/cloud-platform-cli

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
This is done.
