### ISSUE TITLE
Define default LimitRange for environments

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#207]
## Background

Currently, resource usage in the cluster is unrestricted. We want to set some (relatively high) default values for resource requests and limits.

## Proposed user journey

As a user, when I create a new environment, it should come with a pre-defined `LimitRange` defined in it. This will define default values for cluster resource management.

## Approach

We don't want to limit resource usage but we want to prevent situation where `Pods` can consume the resources of an entire node. We can start by setting default limits to 50% of a node's capacity and requests to considerably lower values (so that the scheduler can do its job).

discuss with @alkar 

## Questions / Assumptions

N/A

## Definition of done

- [x] the default `LimitRange` is defined
- [x] the `LimitRange` has been applied to all existing environments and its configuration has been added to the environment directories in the environments repository.
- [x] users cannot alter `LimitRange` resources
- [x] has been tested by creating a pod and checking its definition with `kubectl get pod -o yaml`

## Reference

https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace/

**Comment by kalbir** [comment]
Added this to a milestone and removed connection to #204

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/73
