### ISSUE TITLE
Automated reminders to review more of our documentation

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2075]
We already have reminders for our user guide and runbooks pages, but there are
other pieces of documentation that we should probably review on a regular
basis. These include:

* [ADRs]
* These [docs]
* The main [cp readme]
* README files for our terraform modules
* README files for other repositories

It should be possible to add a similar metadata header to many, if not all of
these, and have an automated process to scrape them to see what needs to be
reviewed.

An important consideration is to try to minimise the number of lists we have to
update when we, for example, add a new repository. Ideally, we should come up
with a way of trawling github to look for things, with minimal/no effort on our
part to update the "list of things".

[ADRs]: https://github.com/ministryofjustice/cloud-platform/tree/main/architecture-decision-record
[docs]: https://github.com/ministryofjustice/cloud-platform/tree/main/docs
[cp readme]: https://github.com/ministryofjustice/cloud-platform

**Comment by AntonyBishop** [comment]
Closed due to age of story
