### ISSUE TITLE
Update authorized_keys.txt everytime new member is added to the webops group

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2079]
[authorized_keys.txt file was moved to the bastion terraform module](https://github.com/ministryofjustice/cloud-platform-terraform-bastion/blob/main/files/authorized_keys.txt) in order to remove its dependency in S3 bucket. 

Still is pending to update the [authorized keys namespace (and script) ](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/authorized-keys-provider/provider.yaml)to create a PR against bastion terraform module when someone is added/removed from the webops github team. This can be solved within the same namespace or just moving all the logic to a concourse pipeline (seems better)

We should also update the existing integration tests [related to authorised keys](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/smoke-tests/spec/authorized_keys_spec.rb).

**Comment by vijay-veeranki** [comment]
Moved to this sprint as discussion in here

https://mojdt.slack.com/archives/C514ETYJX/p1595495411498200?thread_ts=1595494446.491900&cid=C514ETYJX
