### ISSUE TITLE
Define default ResourceQuota for environments

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#208]
## Background

Currently, resource usage in the cluster is unrestricted. We want to set some (relatively high) default quotas for environments (namespaces).

## Proposed user journey

As a user, when I create a new environment, it should come with a pre-defined `ResourceQuota` defined in it.

## Approach

We want to limit resource usage without blocking users. Therefore, initially the quota should be fairly high, perhaps 50% of a node's capacity or more.

discuss with @alkar 

## Questions / Assumptions

N/A

## Definition of done

- [x] the default `ResourceQuota` is defined
- [x] the `ResourceQuota` has been applied to all existing environments and its configuration has been added to the environment directories in the environments repository.
- [x] users cannot alter `ResourceQuota` resources
- [x] has been tested by creating one or more `Pods` that exceed the quota

## Reference

https://kubernetes.io/docs/concepts/policy/resource-quotas/#enabling-resource-quota

**Comment by kalbir** [comment]
Added this to a milestone and removed connection to #204

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/73
