### ISSUE TITLE
Add gpg keys to deploy repo

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#2080]
## Service name

Git-secrets

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Unable to access secrets https://github.com/ministryofjustice/cla_frontend-deploy
Unable to deploy https://github.com/ministryofjustice/cla_frontend-deploy

## Problem description

Add gpg keys to https://github.com/ministryofjustice/cla_frontend-deploy repo
keys will be provided in slack

## Contact person

[at]Said

**Comment by pwyborn** [comment]
Said  11:14 AM 20/07/2020
he has confirmed the key you have added for him is working
11:14
thanks paul
