### ISSUE TITLE
Kubernetes 1.17.x upgrade

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2089]
Kops have released 1.17.1 which means we can upgrade to any minor release of 1.17 Kubernetes. 

This will need to be tested and the release notes will need to be studied as there are a number of deprecations and required actions.
https://github.com/kubernetes/kops/releases/tag/v1.17.0

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1R6XF_Xvm0x-YlZkuNclZ_PgHmaOsBvsjOkSU3XID9KY/edit#

**Comment by jasonBirchall** [comment]
Adding this to blocked column until we complete the kops security group change and the firebreak sprint is finished. ETA 210920
