### ISSUE TITLE
Add SSH access to CLA Frontend, Public and Backend

### ISSUE THREAD

**Issue by aliuk2012** [ministryofjustice/cloud-platform#209]
## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [x] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

New developers on the project are unable to ssh to the box to debug issues

## Problem description

Please could you setup Nick Rowlands @rowlando  and David Lantos @sldblog to be able to ssh to CLA Public, Frontend and Backend ec2 instance. This needs to be done on Demo, training, staging, production

## Contact person

@AlistairLaing

**Comment by lukaszraczylo** [comment]
Changes released to production last evening. Users confirmed access.
