### ISSUE TITLE
Scope out the requirement for Kubernetes 1.17.x upgrade

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2090]
At this present moment in time we don't know how much work is involved to upgrade live-1 to Kubernetes 1.17.x and Kops 1.17.x. This ticket requires an engineer to investigate the changes and decide how much work is required to perform the upgrade. 

Please see the changelog for both Kubernetes and Kops below:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md
https://github.com/kubernetes/kops/releases/tag/v1.17.0

You may be required to run the pluto tool, which will report on any deprecated apis in 1.17.x.

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1R6XF_Xvm0x-YlZkuNclZ_PgHmaOsBvsjOkSU3XID9KY/edit#
