### ISSUE TITLE
One Product Team + Support team

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform#21]
Antony Bishop

**Comment by AntonyBishop** [comment]
What have we done so far:

**Comment by AntonyBishop** [comment]
Tony to work out a definition of done for this.

**Comment by AntonyBishop** [comment]
No further action at this time. Review impact of changes in two weeks (Retro)

**Comment by kcbotsh** [comment]
This was to be trialled for 1 sprint ending 25/05/18. At which stage decision to be made to a) extend trial b) return to sub teams c) become one team with no separate support sub team
