### ISSUE TITLE
Impact on renaming FALA repositories

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#210]
## Service name

https://github.com/ministryofjustice/fala
https://github.com/ministryofjustice/fala-deploy
https://github.com/ministryofjustice/laalaa-deploy

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [x] Other

## Impact on the service

I would like to rename these two repositories to

- https://github.com/ministryofjustice/fala &rarr; https://github.com/ministryofjustice/laa-fala
- https://github.com/ministryofjustice/fala-deploy &rarr; https://github.com/ministryofjustice/laa-fala-deploy
- https://github.com/ministryofjustice/laalaa-deploy &rarr; https://github.com/ministryofjustice/laa-legal-adviser-api-deploy

to keep them consistent with the Legal Aid Agency naming convention.

## Problem description

Is there any operation impact on this rename? What additional steps should I make (can I make) to ensure that the deployment pipeline still works after the rename?

## Contact person

@sldblog (Slack: `@David Lantos`)

**Comment by sldblog** [comment]
Update: also added https://github.com/ministryofjustice/laalaa-deploy &rarr; https://github.com/ministryofjustice/laa-legal-adviser-api-deploy to the list.

**Comment by lukaszraczylo** [comment]
Communicated to user:
The only obvious impact would be Jenkins build process - as containers _may_ use repository name to build and push docker images. Nothing within repositories is tied to the repository name itself.
