### ISSUE TITLE
Remove default pod security policy from EKS cluster

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2106]
Currently all EKS clusters come with a PSP called `EKS.privileged`. This PSP basically grants every pod full access to its environment. For example, it can run contains as root user. In a Kops cluster we only have two PSP's privileged and restricted. These also apply to an EKS cluster but are superseded by the `EKS.privileged` (I believe this is decided alphabetically). 

This ticket requires you to remove the default EKS psp from all new clusters. The action has been performed manually in the live(manager) cluster under https://github.com/ministryofjustice/cloud-platform/issues/2066.

either:
- look for ways to create the cluster without the default policy (perhaps a switch?)
- add a terraform local_exec to remove the default policy at cluster creation

**Comment by AntonyBishop** [comment]
Done
