### ISSUE TITLE
Install core-dns on kops clusters including live-1

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2107]
At the moment all clusters created with kops will install with kube-dns. The Kubernetes project [recommends](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#introduction) that as of 1.12, CoreDNS is the DNS server of choice replacing kube-dns.

Using the instructions below, add a stanza to define coredns as our dns server. 

https://coredns.io/2018/05/21/migration-from-kube-dns-to-coredns/#coredns-in-kops

There is an issue filed that explains that you'll need to manually remove the kube-dns deployment from a migrated cluster. 

https://github.com/kubernetes/kops/issues/6318

Relevant slack chat:
https://mojdt.slack.com/archives/C57UPMZLY/p1595512684204600

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/846
