### ISSUE TITLE
Reviving FALA & LAALAA

### ISSUE THREAD

**Issue by rowlando** [ministryofjustice/cloud-platform#211]
## Service name

Find A Legal Advisor (FALA) - https://find-legal-advice.justice.gov.uk/

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [x] Other

## Impact on the service

I am one of the developers in a service area called Get Access in the LAA. This service now comes under this service area. We need to start understanding how this service works so we can support the application should any incidents occur or new work be required.

At the moment, we have discovered there is a run book for the API that drives the public-facing application. This can be found https://opsmanual.dsd.io/run_books/laalaa.html.

However, there is **not a run book** for the public-facing application, so we don't know what environments exist, how to build and deploy. We've spotted two Jenkins jobs:

- https://ci.service.dsd.io/job/BUILD-fala/
- https://ci.service.dsd.io/job/DEPLOY-fala/

Legal Aid Agency Legal Advisor API (LAALAA) has two Jenkins jobs:

- https://ci.service.dsd.io/job/BUILD-laalaa/
- https://ci.service.dsd.io/job/DEPLOY-laalaa/

In order to support the service, we need the following:

**FALA**
- [x] A list of environments for FALA
- [x] SSH access to all FALA environments
- [x] Access to the AWS console for FALA
- [x] Access to any monitoring service you think we need, e.g. Sentry, PagerDuty
- [x] Who is responsible for putting together a run book? Can you help?
- [x] Admin or owner access to the (GitHub repo)[https://github.com/ministryofjustice/fala/] - Maybe just add the team: https://github.com/orgs/ministryofjustice/teams/laa-get-access/

**LAALAA**
- [x] Update the [run book](https://opsmanual.dsd.io/run_books/laalaa.html) with anything that looks like it's wrong  
- [x] SSH access for to all LAALAA environments
- [x] Access to the AWS console for LAALAA, e.g. Sentry, PagerDuty

Please give SSH, AWS and monitoring access to @rowlando and @sldblog for all of the above.

## Contact person

Slack: @nick
Email: nick.rowlands@digital.justice.gov.uk

**Comment by kalbir** [comment]
Hi @rowlando,

I sent you a message to set up some time to talk through this. Let me know when you are available.

Kalbir

**Comment by nayoa** [comment]
Access to the relevant AWS account has been given to @rowlando and @sldblog. A developer group did not exist in IAM. After discussion with @sid234 - we have chosen to use the policies from the mojdsd account. 

Environments for staging and prod exist in AWS for both FALA and LAALAA. However, monitoring such as CloudWatch and Grafana does not exist. The only alerting on the services is through Pingdom which are currently feeding through Pagerduty into the Cloud Platforms 'high-priority-alert' channel (including out of hours support). After discussion with Nick, he has decided to feed this also into 'find a legal advisor' slack channel. 

Pingdom checks are pointing to - http://find-legal-advice.justice.gov.uk/ and prod.laalaa.dsd.io/healthcheck.json

Sentry access has been given to David.

**Comment by rowlando** [comment]
@nayoa I've updated the ticket to ask for admin access for the FALA repo.

**Comment by nayoa** [comment]
SSH access for the laa-get-access (github) team has been given for both FALA and LAALAA - staging and prod. Nick has confirmed that he can SSH onto both. 

We have confirmed that we only have admin access or the **-deploy** repos so cannot add team to fala repo. Advised digital-service-desk.

Ticket can now be closed.
