### ISSUE TITLE
Remove ECR alerts routed to low-priority-alerts channel

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2112]
## Background

Teams Image count for the ECR repository alerts routed  to low-priority-alerts and it is causing to ignore other alerts. Remove this alerts.
 

https://mojdt.slack.com/archives/C8QR5FQRX/p1595495695008700

## Proposed user journey

Remove this prometheus-custom-alerts-ecr-exporter alerts, maintained from monitoring namespace in Environments repo.
https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/prometheus-ecr-alerts.yaml

## Approach

Remove this prometheus-custom-alerts-ecr-exporter alerts, maintained from monitoring namespace in Environments repo. 

https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/prometheus-ecr-alerts.yaml
And also do the kubectl delete after merging this PR as our pipeline will not delete the files removed.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

No more ECR alerts to low-priority-alerts channel

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
[Remove ECR alerts routed to low-priority-alerts #2845](https://github.com/ministryofjustice/cloud-platform-environments/pull/2845)
