### ISSUE TITLE
Completed jobs pods clean up on nodes

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2113]
We need to create a policy to clean out completed jobs pods from nodes.
These completed jobs pods are taking up pod counts on each node creating too many pods per node alerts (limit set by KOPS is 100 per node) 

We should also create documentation for users to use The .spec.successfulJobsHistoryLimit and .spec.failedJobsHistoryLimit fields in batch jobs so history pods are not sitting there taking up pod count.

**Comment by vijay-veeranki** [comment]
Created job which will run a script, which will delete completed jobs which are:

not part of a Cronjobs
( default .spec.successfulJobsHistoryLimit and .spec.failedJobsHistoryLimit set already)
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits

and job not set with ttlSecondsAfterFinished
https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/#ttl-controller
