### ISSUE TITLE
Create `cloud-platform` cli for validating the existing namespace

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2116]
## Background

Before we rollout the cloud-platform cli to the users, we need to find a way to retrofit the existing namespaces to have all metadata/annotations/variables if that namespace was to be created using cli.

There are some additional metadata added to the cli when creating namespace such as slack-channel on 00-namespace.yaml, team_name in  variables.tf etc. 

The cli command  can be `cloud-platform environment validate` should compare the namespace folder with existing template used for cli and create/amend corresponding metadata with respective values in their namespace. This may include prompting users for input for missing values.

Add a test to validate the new command.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
I think this is a good ticket to have, but I don't agree that it's a pre-requisite for rolling out the cli.

If the cli does exactly what "make namespace" does now, and no more, then it's fine to roll it out to users.

The issue of what other attributes we want namespaces to have, and whether existing namespaces have them or not, is important, but separate.

**Comment by AntonyBishop** [comment]
Closed due to age of story
