### ISSUE TITLE
KubeDeploymentReplicaMismatch

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2119]
https://mojdt.slack.com/archives/C8QR5FQRX/p1595812685005100

-----
[FIRING:1] :warning: KubeDeploymentReplicasMismatch
Alert: Deployment authorized-keys-provider/authorized-keys-provider has not matched the expected number of replicas for longer than an hour.
Details:
- alertname: KubeDeploymentReplicasMismatch
- clusterName: live-1
- deployment: authorized-keys-provider
- endpoint: http
- job: kube-state-metrics
- namespace: authorized-keys-provider
- pod: prometheus-operator-kube-state-metrics-55cf4fff84-7pdlp
- prometheus: monitoring/prometheus-operator-prometheus
- service: prometheus-operator-kube-state-metrics
- severity: warning
-----

**Comment by pwyborn** [comment]
```NAMESPACE                                         NAME                                                            READY   UP-TO-DATE   AVAILABLE   AGE
authorized-keys-provider                          authorized-keys-provider                                        0/1     1            0           272d```

So deployment is not ready

**Comment by pwyborn** [comment]
Pull request [silence alert until authorized-keys-provider procedure modified #2847](https://github.com/ministryofjustice/cloud-platform-environments/pull/2847)
