### ISSUE TITLE
Reduce cla-prod RDS instance class

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#212]
## Service name

https://eu-west-1.console.aws.amazon.com/rds/home?region=eu-west-1#dbinstance:id=cla-prod

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

The current instance size is not utilised. We would like to:

- Reduce available memory from 64 GiB to 16 GiB.
- Reduce available vCPUs from 16 to 4.

Allocated storage would not change.

## Problem description

The current production RDS instance is configured to be a `db.m4.4xlarge` instance class, with $3.22/hour cost. The real-world usage pattern does not seem to require such a big instance.

Could we decrease the instance to `db.m4.xlarge` size, please? It would reduce the hosting cost to $0.4/hour.

## Contact person

@sldblog, Slack: `@David Lantos`

**Comment by lukaszraczylo** [comment]
This can be done tonight together with running update on SSH users for CLA production. I have contacted CLA team asking if it's okay with them.

**Comment by sldblog** [comment]
Let's postpone this until we confirm the required performance is met. I'll reopen when we are ready.

Thank you for your help, @lukaszraczylo 🙇
