### ISSUE TITLE
Apply/create ES Terraform Module to Cloud Platform's Elasticsearch

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2122]
At the moment Cloud Platform's Elasticsearch is [here](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/global-resources/elasticsearch.tf). It is not using any terraform module and it should.

This ticket is about the creation of a terraform module for Cloud Platform Elasticsearch or the use of our [exciting team's ES TF module ](https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch)if it is possible.

**Comment by AntonyBishop** [comment]
Closed due to age of story
