### ISSUE TITLE
Move Elasticsearch definition from global-resources to cloud-platform-account

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2123]
Elasticsearch is not a global resource, it does actually depend on AWS Accounts and it is tied to one (CP Account in this case). We should move (using `terraform import` to avoid downtime) the existing definition from [global-resources folder](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/global-resources/elasticsearch.tf) to [cloud-platform-account folder](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform-account).

**Comment by AntonyBishop** [comment]
Closed due to age of story
