### ISSUE TITLE
SPIKE: Open Service Broker API

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#213]
## Background

Investigate whether it's a good fit for managing resources.
See references.

## Proposed user journey

N/A

## Approach

N/A

## Questions / Assumptions

- Is it easy to setup?
- How does it manage resources?
- Comparison to terraform approach we currently have.
- etc.

## Definition of done

- [x] must answer the questions above

## Reference
- https://www.openservicebrokerapi.org/
- https://github.com/openshift/ansible-service-broker
- https://aws.amazon.com/blogs/opensource/provision-aws-services-kubernetes-aws-service-broker/
- https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/

**Comment by tatyree** [comment]
Moving out of To Do for now - needs more detail, please.

**Comment by tatyree** [comment]
@alkar if you've already done it, or are doing it, just move it to the appropriate column, please.

**Comment by alkar** [comment]
Must have missed this one. I had a go at it for half a day, didn't get far, put it back in the queue. Hope to pick it up again this week.

**Comment by alkar** [comment]
To answer the questions of the ticket:

- It is very easy to setup.
- It manages resources using CloudFormation.
- Overall, the service catalog approach seems much better as there is a single place to manage all things, using a common configuration format, all driven on the kubernetes API. However, at the moment the implementation doesn't seem ready for production.

### Pros
- One way to manage kubernetes and AWS resources
- We won't have to build terraform modules
- It is API driven
- It's the official kubernetes approach to external resource management

### Cons
- Holds state in its own `etcd` instance (although it looks [they're moving to a different approach](https://trello.com/c/K6zUdfLZ/668-21-remove-etcd-from-broker-and-move-to-using-crds))
- RDS doesn't work, potentially other services too?
- Feels brittle: to provision a resource it spins up a container that runs ansible to spin up a cloudformation stack
- There is no obvious way to control access to specific services using RBAC, we would potentially have to drive resource creation using pull requests.
