### ISSUE TITLE
Upgrade Helm provider for our terraform codebase

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2132]
At the moment we are using`1.1.0` version and the latest is `1.2.4`.

**Comment by jasonBirchall** [comment]
Latest release without breaking changes is:
https://github.com/hashicorp/terraform-provider-helm/releases/tag/v1.3.2

**Comment by jasonBirchall** [comment]
Terraform Helm provider files to update:
ministryofjustice/cloud-platform-terraform-eks-components/main.tf **0.10.4**
ministryofjustice/cloud-platform-infrastructure/terraform/cloud-platform-components/main.tf **1.1.0**
ministryofjustice/cloud-platform-infrastructure/terraform/cloud-platform-eks/components/main.tf **1.0.0**
ministryofjustice/cloud-platform-terraform-rds-snapshot-limit-alert/example/main.tf **1.0.0**
ministryofjustice/cloud-platform-terraform-teams-ingress-controller/examples/main.tf **1.1.0**
ministryofjustice/cloud-platform-environments/namespaces/live-1.cloud-platform.service.justice.gov.uk/mogaal-test/resources/main.tf **1.1.0**
ministryofjustice/cloud-platform-terraform-pushgateway/example/main.tf **1.1.0**
ministryofjustice/cloud-platform-terraform-report-unused-sg/example/main.tf **1.0.0**
ministryofjustice/cloud-platform-terraform-concourse/example/main.tf **1.0.0**
ministryofjustice/cloud-platform-infrastructure/terraform/cross-account-IAM/main.tf **0.10.4**

**Comment by jasonBirchall** [comment]
Completed the update on all but one repository. The ministryofjustice/cloud-platform-terraform-report-unused-sg/example/main.tf is no longer used so I archived it.
