### ISSUE TITLE
Create Pingdom Slack notification integration for Prisoner Content Hub

### ISSUE THREAD

**Issue by spikeheap** [ministryofjustice/cloud-platform#2139]
## Service name

Prisoner Content Hub

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We need to monitor the availability of our production services and staging environment.

## Problem description

We would like to set up a number of Pingdom alerts following [the guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#adding-slack-notification). We have two applications: a CMS and the prisoner content hub frontend.

For production alerts we'd like to broadcast to four channels, so the full set of notifications is:
1. Prisoner Content Hub CMS -> [#pfs_hub](https://mojdt.slack.com/archives/C9EKLJ1QE)
2. Prisoner Content Hub CMS -> [#pfs_dev](https://mojdt.slack.com/archives/C013XH7TFV3)
3. Prisoner Content Hub CMS -> [#pfs-hub-private](https://mojdt.slack.com/archives/GNQK3S7GT)
3. Prisoner Content Hub CMS -> [#pfs-incidents](https://mojdt.slack.com/archives/CGMLXPT8X)
4. Prisoner Content Hub frontend -> [#pfs_hub](https://mojdt.slack.com/archives/C9EKLJ1QE)
5. Prisoner Content Hub frontend -> [#pfs_dev](https://mojdt.slack.com/archives/C013XH7TFV3)
6. Prisoner Content Hub frontend -> [#pfs-hub-private](https://mojdt.slack.com/archives/GNQK3S7GT)
3. Prisoner Content Hub frontend -> [#pfs-incidents](https://mojdt.slack.com/archives/CGMLXPT8X)

For staging alerts we just want to alert in a single channel:
1. Prisoner Content Hub CMS -> [#pfs_dev](https://mojdt.slack.com/archives/C013XH7TFV3)
2. Prisoner Content Hub frontend -> [#pfs_dev](https://mojdt.slack.com/archives/C013XH7TFV3)

There may be a smarter way of creating fewer integration IDs, as I'm not sure what information is displayed in the Slack alert.

## Contact person

Ryan Brooks (@spikeheap)

**Comment by spikeheap** [comment]
Argh, I'm really sorry about this, but I've just found out from our ops team that we can't post alerts into `#pfs-incidents`, we need to use `#pfs-alerts` instead. Is it too late to add that to this ticket.

Sorry!

**Comment by vijay-veeranki** [comment]
Name:  #pfs_dev slack 
integrationid: 106307

Name:  #pfs_incidents slack
integrationid: 106310

Name:  #pfs_hub slack
integrationid: 106311

**Comment by vijay-veeranki** [comment]
@spikeheap we couldn't create integration id (webhook) for #pfs-hub-private

As we are unable to create a new configuration and generate a webhook url i.e. https://hooks.slack.com/services/xxxxxx/xxxxxx/xxxxx for #pfs-hub-private

**Comment by vijay-veeranki** [comment]
@spikeheap updated #pfs-incidents to #pfs-alerts, please find the below integration id's to use as suggested [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#adding-slack-notification)

Name: #pfs_dev slack
integrationid: 106307

Name: #pfs_alerts slack
integrationid: 106310

Name: #pfs_hub slack
integrationid: 106311
