### ISSUE TITLE
Investigate Virtual Private Gateway (VPG) usage on AWS

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform#214]
## Background

When we commission a new cluster, we create a new VPG.  [AWS hard-limit these to five per region](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Appendix_Limits.html#vpc-limits-gateways).  The main MoJ AWS account in eu-west-1 is already at its limit and so we need to understand what to do about this.

## Approach

Investigate where and why the VPG is being created, decide next steps. 

## Definition of done

- [x] Discover what part of our stack is creating the VPG
- [x] Decide whether or not we need to create a VPG with each new cluster
- [x] Document the recommended course of action:
  * If the VPG can be removed, document the steps in a new ticket and coordinate to get it scheduled
  * If the VPG is necessary, document why it is need and where it is configured in the main documentation.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by alkar** [comment]
The VGW is created by the VPC module (`enable_vpn_gateway = true`).

We don't need a VGW as we don't have any VPN connections (easily verified by looking at  the route tables for the VPC).

VGWs that had already been created are now removed manually. In `kubernetes-investigations/terraform/cloud-platform`:
```
$ terraform workspace select <workspace>
$ terraform apply -target=module.cluster_vpc.aws_vpn_gateway.this
```
