### ISSUE TITLE
Investigate how we manage DNS

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform#215]
## Background

DNS is currently managed via Route 53 multiple AWS accounts depending on the domain.  For the purposes of this exercise/milestone, we need to decide how to best change the DNS to point at a new cluster when we have performed a disaster recovery.  

## Scope

This ticket is scoped to its milestone and should **only** involve **documenting** the steps needed to manage DNS. 

## Proposed user journey

The live cluster fails for some reason.  We start a new cluster and re-launch the LAA FC app.  Once the replacement is confirmed as working, we change the DNS

## Questions / Assumptions

* Do we create a new domain for use with platform apps? 

* Do we delegate a subdomain (`platform`?) to the existing DNS?

* Do we manage the existing DNS directly?

* Any experiments undertaken to test DNS integration/changeover will be done on test domains/subdomain and will not affect existing domains and services. 

## Definition of done

- [x] Decide and document our preferred approach for managing DNS for disaster recovery.
- [x] Ensure, via safe-to-fail experimentation, that the documented steps work. 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Having refleted on this ticket. Todd and I have decided to change the alias on the central wildcard record which will point all services on the aliases to the new cluster. The govuk CNMAE should just follow this. 

The reason we talked through this is because tying the LAA Fee Calculator to this ticket caused confusion.
