### ISSUE TITLE
Enable users to "describe" their RDS instances

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2157]
Our RDS module creates some AWS credentials so that users can manage their DB
snapshots.

We should amend the IAM policy so that users can also run:

```
aws rds describe-db-instances --db-instance-identifier [rds identifier]
```

This will allow users to check whether or not a change to their RDS instance
settings has been implemented successfully.

**Comment by AntonyBishop** [comment]
Closed due to age of story
