### ISSUE TITLE
Document creation of a new Auth0 app

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform#216]
## Background

We use [Auth0](https://auth0.com) to manage authentication and authorisation with Kube clusters using MoJ GitHub accounts.  If we add new clusters, we need add new apps to Auth0 to enable login.  We might also need to change existing, integrated Auth0 accounts in the even of Auth0 failures (unlikely), hostile action, or other unforeseen circumstances.

## Proposed user journey

A Platform team member start disaster recovery of a live cluster.  They log into Auth0, create a new app and attach it to the new cluster.  This allows members of the MoJ GitHub organisation to log in to the new cluster. 

## Questions/Assumptions

Assume that **anyone** on the Platform team might need to follow the playbook. 

You have a basic cluster/environment set up that you test this setup against.

Do we need to document the creation of a completely new tenant as well? 

## Definition of done

- [x ] A new Auth0 app has been added to ~~the existing~~ newly created tenant
- [x ] The new app is integrated with GitHub and the new cluster
- [x ] A member of the MoJ GitHub organisation can log in to the new cluster using Auth0 
- [x ] That member has the appropriate access for their given role (i.e. WebOps = admin/root, everyone else = ordinary user) - will be detailed in #220
- [x ] A GitHub user who is **not** a member of the MoJ GitHub organisation **cannot** log in.
- [ x] The full workflow for this activity is documented.
- [ x] #258 will deal with the cleanup

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
First draft: https://github.com/ministryofjustice/kubernetes-investigations/pull/47
(the README is the essential part)

**Comment by razvan-moj** [comment]
https://github.com/ministryofjustice/kubernetes-investigations/tree/master/auth0 documents the setup
