### ISSUE TITLE
Create documentation for sensible defaults in new Sentry

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2160]
We've made a decision to give every user admin priviliges to the new Sentry account. It would be a good idea to outline some important defaults like, "how do I name my service" and "how long should I keep data for".

As part of this guidance we should also make clear what is supported and how users access support for Sentry.io.

Some resources we can point users to can be found in #1614

**Comment by AntonyBishop** [comment]
Transfer to Ops Eng
