### ISSUE TITLE
Simplify creating a gov.uk prototype kit site on the cloud platform

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2173]
The [Gov.UK Prototype Kit] makes it easier for teams to [create prototypes] for their services.

Teams often host these on [heroku] so that they can be shared, e.g. for user research sessions.

We should add a feature to the [cloud platform cli] to make it easy to spin up prototype sites on the cloud platform.

We can assume that the user already has a github repository based on the prototype kit, so now they want a hosted version on the cloud platform.

After running a cli command like:

```
cloud-platform prototype create --name myapp --repo https://moj/myapp-prototype
```

...the following things should exist:

* A namespace
* An ingress using basic authentication (part of the cli output should include the credentials for this, which should be short, so easy to type and share)
* A deployment running the prototype kit node.js application on the cloud platform
* A CD pipeline so that changes to the underlying github repo automatically update the hosted prototype (github actions or circleci)

It is fine, at this point, that the user has to raise a PR against the env. repo, containing the files created. by the cli.

Setting up the CD pipeline is likely to require some additional work by the user, e.g. "create a .github/workflows/deploy.yml with this content, and add a secret to your github repository called XXX containing YYY).

[Gov.UK Prototype Kit]: https://govuk-prototype-kit.herokuapp.com/docs
[create prototypes]: https://www.gov.uk/service-manual/design/making-prototypes
[heroku]: https://heroku.com
[cloud platform cli]: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/cloud-platform-cli.html#the-cloud-platform-cli

**Comment by digitalronin** [comment]
Reaction to this idea among developers seems positive:
https://mojdt.slack.com/archives/C3F8L6XQU/p1596551625170400

**Comment by davidread** [comment]
Tony says Form Builder are looking to host prototype kit things on their platform, so might not be so valuable for us to do it too. Need to chat with them.

**Comment by davidread** [comment]
Form Builder team confirm that they are good for hosting prototypes that fit their model - forms, using GOV.UK styling, no custom HTML/JS, no custom server-side processing. For all other prototypes we should aim to host on CP.

**Comment by AntonyBishop** [comment]
The original target scope of this was the services that Formbuilder are now developing. 

Identifying what other types of prototyping goes on on MoJ will require much more detail research to see if there is a need for this.

**Comment by AntonyBishop** [comment]
Done
