### ISSUE TITLE
Update apiVersion rbac.authorization.k8s.io/v1beta1 to rbac.authorization.k8s.io/v1

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2175]
All resources within the rbac.authorization.k8s.io/v1alpha1 and rbac.authorization.k8s.io/v1beta1 API groups are deprecated in favor of rbac.authorization.k8s.io/v1, and will no longer be served in v1.20

https://github.com/kubernetes/kubernetes/pull/84758

We may use pluto to find the deprecated rbac resources.

This should be changed across all the live-1 and manager cluster:

- environments repo
- users managing their own rbac
- all helm chart's in components

**Comment by AntonyBishop** [comment]
Already done
