### ISSUE TITLE
Update circleci Elastic search index format to match with other index

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2176]
Circle CI stats are pushing to ES with index with  "timestring": "%Y%m%d" for example (circleci-20200719).

https://github.com/ministryofjustice/cloud-platform-circleci-stats/blob/main/es-fetch.rb#L89

All other index we have are using "timestring": "%Y.%m.%d" 
example:
kubernetes_cluster-2020.08.01
ingress-json-2020.07.09
logstash-2020.07.31

For the curator cronjob we are using below filter, which will exclude circle ci indexes.

```
  {
      "filtertype":"age",
      "source":"name",
      "direction":"older",
      "timestring": "%Y.%m.%d",
      "unit":"days",
      "unit_count":30
    }
```

Update the circleci index to match with others so we maintain consistency and don't need to maintain multiple filters.

https://github.com/ministryofjustice/cloud-platform-circleci-stats/blob/main/es-fetch.rb#L89

**Comment by AntonyBishop** [comment]
Closed due to age of story
