### ISSUE TITLE
FInd a process to delete and reapply any cluster components without CRDs

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2181]
This ticket is to find a way/process to delete and re-apply the cluster components without affecting their respective CRDs

For example, cert-manager has certain CRDs which are applied through null-resource. When deleting and re-installing the cert-manager helm chart, the CRDs have issues recreating and stops working.

**Comment by AntonyBishop** [comment]
Closed due to age of story
