### ISSUE TITLE
Spike to create a script to check whether terraform state and kubectl context matches

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2186]
When applying terraform resources to the cluster, if there is a mismatch in the terraform workspace and kubectl context, the changes can be applied to the wrong cluster.

Create a script to check the terraform state and the kubectl context and see if that matches. 
Create a null resource to run this script which can be set to be dependant on every resource created in the cluster. Thereby to ensure the terraform workspace and kubectl context are related to the same cluster

**Comment by davidread** [comment]
Maybe we just need a standard script to add this info into our command-prompts
