### ISSUE TITLE
Add list/show secrets to the cloud platform CLI

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2193]
Enable users to easily list the secrets in their namespace, and output a secret in cleartext.

```
cloud-platform environment secret list --namespace dstest
cloud-platform environment secret show --namespace dstest --name mysecret
```

These commands should run `kubectl -n namespace get secret mysecret -o yaml` behind the scenes, so that we don't have to bundle kubectl with the cli binary.

The `show` command should output the entire secret in cleartext, without requiring any base64 decoding.

Stretch goal: If there is a `00-namespace.yaml` file in the current directory, get the namespace name from there iff the user didn't supply the `--namespace` parameter.

**Comment by digitalronin** [comment]
closed by https://github.com/ministryofjustice/cloud-platform-cli/pull/62

**Comment by davidread** [comment]
We think the reason for providing this was:

* people found it hard to see secrets (e.g. postgres), with the extra base64 step, and it caused support requests
* people might not have base64 installed so use a public website?
