### ISSUE TITLE
Explore kube-score for live-1 - static code analysis tool

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2195]
[kube-score](https://github.com/zegl/kube-score) might be good to start enforcing best practices within live-1. It allows us a static code analysis validation (with different severities) 

Ideally, it would be cool to have a GitHub action to run this.

**Comment by vijay-veeranki** [comment]
Comparing to checkov to kube-score.

Checkov have more checks

https://github.com/zegl/kube-score/blob/master/README_CHECKS.md
https://github.com/bridgecrewio/checkov/blob/master/docs/3.Scans/resource-scans.md
