### ISSUE TITLE
Automate the "slow and safe" way of replacing a failed master node

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2198]
When we want to replace a master node, we usually just cordon, drain and terminate the node, and let kops replace it.

The officially recommended process also suggests removing the node from the etcd cluster and backing up its ebs volume before replacing.

Our runbook:
https://runbooks.cloud-platform.service.justice.gov.uk/replacing-master-node.html

Officially-recommended procedure:
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#replacing-a-failed-etcd-member

If we can automate the slow and safe process so that it doesn't take any more human time than the quick and dirty way, then we should have a safer way to carry out this procedure.

It would be good to understand what risks the slow and safe approach protects us against, over the quick and dirty approach. Under what circumstances would we need the EBS backups? What is the downside of not gracefully leaving the etcd cluster before terminating the node?

**Comment by jasonBirchall** [comment]
Having looked into this extensively, here is what I've observed.

**The "Slow and steady way" performs the following actions to recover from a failed etcd instance:**
- Gets the etcd member ID
- Removes failed member from the quorum.
- Perform backup of the EBS volume and create a built in snapshot.
- Adds a new member to the quorum. 
- Update its --etcd-servers flag to make Kubernetes aware of the configuration changes, then restart the Kubernetes API server.

**Our current documented procedure performs the following actions to recover from a failed etcd instance:**
- Identifies the failed master
- Removes failed member from the quorum.
- Perform backup of the EBS volume and create a built in snapshot.
- Create a new master and let kops add it back to the quorum.

The only difference between the two is how you add the new master and the restart of the API. As we use kops to provision our instances, I think we should keep this process as it is and let kops manage adding the new instance to the quorum. I tested the API cycle after the addition and it makes no difference whether you cycle the pods or not. In conclusion, I believe our documentation is providing the best path to recover from a failed etcd instance. 

To gather feedback from the community, I have [asked the  question](https://kubernetes.slack.com/archives/C3QUFP0QM/p1600338470060700) of best practice in the KOps slack channel. At the time of writing, I haven't received an answer.

Our document does however lack efficiency in removing members from etcd as this can be performed by one or two commands. This can be improved by following the steps outlined here:
https://kops.sigs.k8s.io/operations/etcd_administration/#direct-data-access

Source:
Our documentation, https://runbooks.cloud-platform.service.justice.gov.uk/replacing-master-node.html
Community documentation, https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#replacing-a-failed-etcd-member
