### ISSUE TITLE
Github for everything

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform#22]
As agreed in is retro we want to move to having one tool to manage our work. This is our chosen tool and we are working to exclusively use Github - Means retiring JIRA/ Confluence for day to day work management

**Comment by tariqmoj** [comment]
Actions 
Meeting with @tatyree to raised concerns about about the board being public and how to cut tickets for users. IP's are fine to be public. Team 3 to cut tickets/create user issues ***DONE***
To make sure everyone knows how to cut tickets, short walkthrough, led by todd describing best practice.
