### ISSUE TITLE
Generate an alert if an ASG fails to provision an instance

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2204]
We had an [incident] where an ASG failed to replace an EC2 instance.

In that case, we only found out that this was the issue by checking the ASG in the AWS console.

We should capture any such events (if possible) and create an alert as we do for other important failures.

[incident]: https://mojdt.slack.com/archives/C514ETYJX/p1596814746202600

**Comment by digitalronin** [comment]
From Jamie Trickey of AWS:

> To be notified of an EC2 instance not launching successfully within the scaling group you can create an event rule within CloudWatch, this would need to match the “Auto Scaling” service with an Event Type of “Instance Launch and Terminate” with a specific instance event of “EC2 Instance Launch Unsuccessful” please see the following link and also the attached screen shot.  When creating the rule you can set a Target to notify via SNS or send a message to one of the many other supported services.  https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/Create-CloudWatch-Events-Rule.html

**Comment by digitalronin** [comment]
![asg_event_rule](https://user-images.githubusercontent.com/2338/89922358-d4fcda80-dbf6-11ea-8b9c-229e5d200ea9.png)

**Comment by AntonyBishop** [comment]
Closed due to age of ticket
