### ISSUE TITLE
Use a mixedInstancePolicy for our master (& worker?) nodes

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2205]
We had an [incident] where we were unable to replace a master node.

One way to mitigate that kind of problem is to specify multiple options for the instance type in the ASG for each master node.

From Jamie Trickey of AWS:

> I’ve had a look at the Kops documentation and found you can specify additional instance types using the mixedInstancePolicy, my testing showed this would then create a Launch Template rather than a Launch Configuration which allows a choice of more than 1 EC2 instance type in the scaling group, example in this link https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#mixedinstancepolicy-aws-only

Investigate this option to see if it could work for us.

[incident]: https://mojdt.slack.com/archives/C514ETYJX/p1596814746202600

**Comment by digitalronin** [comment]
davidsalgado  4:04 PM
do you know what the strategy is for ASGs with multiple instance types? Does it start at the top of the list of instance types and keep trying until it gets an instance? (edited) 

Ross Boast  5:29 PM
Yes, that’s exactly how it works. You can set a default EC2 type in the launch template and then set a prioritised list of overrides as fallbacks. See https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-purchase-options.html#asg-allocation-strategies : The allocation strategy for On-Demand Instances is prioritized. Amazon EC2 Auto Scaling uses the order of instance types in the list of launch template overrides to determine which instance type to use first when fulfilling On-Demand capacity. For example, let’s say that you specified three launch template overrides in the following order: c5.large, c4.large, and c3.large. When your On-Demand Instances are launched, the Auto Scaling group fulfills On-Demand capacity by starting with c5.large, then c4.large, and then c3.large.
Jamie set up a test kops system and has just verified for me that kops generates a launch template with an ASG that has a list of instance types/sizes according to the list defined in mixedInstancesPolicy.instances. The onDemandAllocationStrategy is set by default to prioritised and so it should just work as you expect :thumbsup: (edited)

**Comment by vijay-veeranki** [comment]
PR for kops module:

https://github.com/ministryofjustice/cloud-platform-terraform-kops/compare/mixedInstancePolicy?expand=1


PR for infrastructure:

https://github.com/ministryofjustice/cloud-platform-infrastructure/compare/mixed-instance?expand=1

This will let to add mixedinstancespolicy `https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#mixedinstancespolicy-aws-only` on any node group.

We should be able to specify a prioritised list of On Demand instances whereby we can specify instance types in order of preference

Tested that we can set types/sizes according to the list defined in mixedInstancesPolicy.instances. The onDemandAllocationStrategy is set by default to prioritised and the result is as per https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-purchase-options.html#asg-allocation-strategies

**Comment by vijay-veeranki** [comment]
Spoke to Ale about this change, he is happy to apply it next week some time, when things are stable

Updated the PR to apply it to monitoring node.
