### ISSUE TITLE
Document setup of Kuberos

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform#221]
## Background

A new cluster needs a route for end users to authenticate using OIDC.  This requires that Kuberos is installed on the cluster. 

In order to ensure that anyone in Platform can install Kuberos–and thereby set up a new cluster for disaster recovery (DR)–we need this documented and that documentation included in an official disaster recover (DR) playbook. 

## Proposed user journey

The live cluster fails.  A Platform team member opens the playbook, reads the steps regarding Kuberos and then runs the necessary assets to install Kuberos. 

## Approach

Run the existing scripts in a new region environment, ensure they work and document the procedure in the playbook.  Fix the script(s) if necessary, but avoid a full refactor at this point.

## Questions/Assumptions 

Scripts and instructions for installing kuberos exist somewhere in draft form. 

You have a basic cluster/environment set up that you test this setup against.  

## Definition of done

- [ x] Test the existing Kuberos steps scripts in a safe-to-fail environment. 
- [ x] Fix any breaking issues
- [ x] Document **all** steps needed to make this run. 
- [ x] Ensure all steps of the user journey are addressed.
- [ x] Raise any non-breaking issues as new tickets 
- [ x] #258 will deal with the cleanup

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
https://github.com/ministryofjustice/kubernetes-investigations/tree/master/auth0 documents the setup
