### ISSUE TITLE
Make dedicated ingresses the default

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2212]
We have a plan to move to dedicated ingresses, because the current setup of
having a single nginx for all ingresses in live-1 is running into performance
problems.

As a first step, we should alter our documentation/templates so that any
ingresses we create from now on have their own ingress controller, rather than
using the shared one.

**Comment by mogaal** [comment]
This will means teams will have to implement their own ingress controller using terraform as described [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/your-own-ingress-controller.html#having-your-own-nginx-ingress-controller). 

As @digitalronin mention, maybe we can focus in update the default templates CP-CLI generates to include this terraform module by default.

**Comment by digitalronin** [comment]
This is closed by several PRs, including:
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/447
https://github.com/ministryofjustice/cloud-platform-environments/pull/2976
https://github.com/ministryofjustice/cloud-platform-cli/pull/44
