### ISSUE TITLE
Migrate more code to AWS Baselines Terrafom module.

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2220]
Recently we created our account [baselines terraform module](https://github.com/ministryofjustice/cloud-platform-terraform-awsaccounts-baselines) and we included the most frequently used components. 

We haven't included them all and we should in order to get rid of the cloudformation code. The components pending to be migrated are:
- aws-limit-monitor
- aws-config-cloudtrail-logging (only aws-config-enable-rules.yaml pending to migrate, the buckets are already within tf module)
- aws-iam-suspend-inactive-users (I personally don't think we need this but please explore and ask the team)
- aws-risk-credentials-exposed 
- aws-s3-object-auto-remediation

**Comment by AntonyBishop** [comment]
Story broken down. Replaced by #2247, #2248, #2249, #2250 and #2251
