### ISSUE TITLE
aws_db_parameter_group deletion issue when modifying aws_db_instance(db_engine_version) 

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2222]
At the moment when user try to change the "aws_db_instance(db_engine_version)"  from 10 to 11 for example they have to change the "rds_family" to postgres10 to postgres11.

rds family is defined with in the resource "aws_db_parameter_group"

https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/main/main.tf#L131-L142

To apply this change terraform is trying to delete and recreate the aws_db_parameter_group and failing with error.

```
Error: Error deleting DB parameter group: InvalidDBParameterGroupState: One or more database instances are still members of this parameter group cloud-platform-xxxxxxx, so the group cannot be deleted.
```
There is a open issue regarding this.
https://github.com/terraform-providers/terraform-provider-aws/issues/6448

The work around for this is:

Login to the AWS Console, modify the RDS and set Parameter group to the default.postgres10 group provided by AWS
re-run the terraform apply
The parameter group will get deleted and new one will be created and get assigned to the RDS. 
The RDS will now continue to change the db_engine_version to 11.

This involves manual steps, so identify a solution to find out a better solution.

May be users need to create 2 PR's one to set the parameter group to default one and later set it back to right ones?

**Comment by AntonyBishop** [comment]
Perhaps we should ask AWS for any recommendations?

**Comment by mtrbls** [comment]
Tested with manual change from the CLI, instead of  AWS console change.
This is only possible with the newly added permission.
