### ISSUE TITLE
Explore posibilities to implement pushgateway.

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2223]
Explore if we can offer [pushgateway](https://github.com/prometheus/pushgateway) for users. Some of them are asking for ways to push metrics to Prometheus. More info look at this [thread](https://mojdt.slack.com/archives/C57UPMZLY/p1597409957434600)

**Comment by imran-awan1** [comment]
Pushgateway module
https://github.com/ministryofjustice/cloud-platform-terraform-pushgateway

**Comment by AntonyBishop** [comment]
Needs to be reviewed by Ale and brought into the re-architecting prometheus discussion.

**Comment by AntonyBishop** [comment]
Duplicate
