### ISSUE TITLE
EPIC: Ingress controller Pools

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2224]
We need to migrate away from our current setup of a single ingress controller
for the whole cluster. This is not sustainable, and we are already starting to have incidents because of it.

The plan is to have an ingress controller per namespace. These ingress controllers will all run in a single "ingress-controllers" namespace.

This ticket is an anchor. Please add "related to #2224" to any other tickets which form a part of this work.

**Comment by digitalronin** [comment]
Copied from slack
> FYI for those not on the call: We're currently using a single security group to restrict traffic to the cluster from all our load-balancers.
This isn't going to work with dedicated ingress controllers, because the way we're doing it now, every new ingress controller adds a new rule to the existing security group, and there's a limit to the number of those rules we can have (default 60, AWS have raised ours to 310(?) but that's uncomfortably low).
Ale is investigating if we can add a new security group with each new ingress controller. The limit on security groups is 2500, which is plenty for our medium term needs.

**Comment by AntonyBishop** [comment]
Renamed following change in direction
