### ISSUE TITLE
Investigate Cortex 

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#2229]
https://cortexmetrics.io/

Cortex seems to be an alternative to Thanos. 
Just like Thanos, it is a Sandbox CNCF project. 

How does it compare to Thanos ?

**Comment by jasonBirchall** [comment]
This is a nice article that explains some of the key differences between the two projects. 
https://grafana.com/blog/2020/07/16/how-the-cortex-and-thanos-projects-collaborate-to-make-scaling-prometheus-better-for-all/
