### ISSUE TITLE
Use snake-case consistently, in variable names

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2230]
We are inconsistent in using `foo_bar` and `foo-bar` as variable names. This has caused problems in the past (e.g. when a template expects `repo_name` but only `repo-name` exists), and probably will in future. So, we need to transition all our code to use consistent variable names.

We have settled on snake-case (i.e. `foo_bar`) as our naming convention.

- [ ] Amend all our YAML and `*.tf` files to provide a snake case equivalent variable, wherever a hyphen-name variant exists
- [ ] Update all our pipeline code and scripts to use snake case variables throughout
- [ ] Remove all hyphen-name variables from our codebase

**Comment by AntonyBishop** [comment]
Closed due to age of ticket
