### ISSUE TITLE
Upgrade Ingress-controller to version v0.34.1

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2238]
Current:
Version: 1.35.0	
appVersion: 0.30.0

Latest:
version: 1.41.2
appVersion: v0.34.1

This change could possibly help with current pods crashlooping
https://github.com/kubernetes/ingress-nginx/pull/5832

**Comment by vijay-veeranki** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/pull/5

https://github.com/ministryofjustice/cloud-platform-terraform-teams-ingress-controller/pull/8

**Comment by vijay-veeranki** [comment]
Closed this ticket as we have [this](https://github.com/ministryofjustice/cloud-platform/issues/2339) ticket now.

Updated with comments on [2339](https://github.com/ministryofjustice/cloud-platform/issues/2339)
