### ISSUE TITLE
CLI: Enable users to name their S3 buckets

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2239]
Users can create an s3 bucket via the cloud platform cli.

The latest release (4.4) of the s3 module supports a "bucket_name" variable,
which will allow the users to specify a name for their bucket, instead of
getting the usual "cloud-platform-[random]" name.

Modify the CLI to take an optional --name parameter, when creating an s3 bucket
and, if provided, use that as `bucket_name`

**Comment by AntonyBishop** [comment]
Closed due to age of ticket
