### ISSUE TITLE
Investigate why the pipeline fails with error: "No provider exists"

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2241]
The full error and link to pipeline failure are here:
```
Provider "aws" not available for installation.

A provider named "aws" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/linux_amd64

    Terraform detects necessary plugins by inspecting the configuration and state.
    To view the provider versions requested by each module, run
    "terraform providers".


    Error: no provider exists with the given name
```

https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-terraform/jobs/apply-live-1/builds/738

**Comment by AntonyBishop** [comment]
Recent issue - https://concourse.cloud-platform.service.justice.gov.uk/sky/issuer/auth?access_type=offline&client_id=skymarshal&redirect_uri=https%3A%2F%2Fconcourse.cloud-platform.service.justice.gov.uk%2Fsky%2Fcallback&response_type=code&scope=openid+profile+email+federated%3Aid+groups&state=eyJyZWRpcmVjdF91cmkiOiIvdGVhbXMvbWFpbi9waXBlbGluZXMvZW52aXJvbm1lbnRzLXRlcnJhZm9ybS9qb2JzL2FwcGx5LWxpdmUtMS9idWlsZHMvNzM4IiwiZW50cm9weSI6IjI5YjAzNzE1ZjFjNzIwYjBlMzY2NjdjZjc5ZGRhMDE2MjgzMDU2ZmRjZjRjYmQwNTY1YzRhNDQ2NjYzNjU3MmYifQ%3D%3D

**Comment by digitalronin** [comment]
Add a catch and (single) retry, if terraform init fails in the apply pipeline.

**Comment by jasonBirchall** [comment]
This triggers almost daily now

**Comment by AntonyBishop** [comment]
https://mojdt.slack.com/archives/C514ETYJX/p1599480352256900?thread_ts=1599480248.256000&cid=C514ETYJX
