### ISSUE TITLE
Create OPA policy that forces users to add an annotation to their ingress rule

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2244]
As we've decided to split the ingress-controllers so each namespace has its own. It would be worth creating an OPA policy that forces the user to add an annotation to their ingress rule.

**Comment by vijay-veeranki** [comment]
Created a policy called ingress_nginx_class

This policy deny any ingress that don't have "kubernetes.io/ingress.class" annotation

Excludes above rule if "cloud-platform.justice.gov.uk/ignore-ingress-class" is used in the namespace(rule for cp team to use default ingress class)

https://github.com/ministryofjustice/cloud-platform-terraform-opa/compare/policy-ingress-class?expand=1

**Comment by vijay-veeranki** [comment]
As we have a issue with increasing our NLB limit in AWS, we are not going with the plan to have an individual NLB for a namespace

So this policy is not be necessary, but we can revisit-this if we come with a new rule and a policy for that.

communication related to it.
https://mojdt.slack.com/archives/CH6D099DF/p1599564594016000
