### ISSUE TITLE
Migrate more code to AWS Baselines Terrafom module - aws-config-cloudtrail-logging

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2248]
Recently we created our account [baselines terraform module](https://github.com/ministryofjustice/cloud-platform-terraform-awsaccounts-baselines) and we included the most frequently used components.

We haven't included them all and we should in order to get rid of the cloudformation code. This ticket is to migrate aws-config-cloudtrail-logging **(only aws-config-enable-rules.yaml pending to migrate, the buckets are already within tf module)**.

**Comment by sablumiah** [comment]
Mod Platform Config Module

https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/tree/main/modules/config
