### ISSUE TITLE
Add tags to our auth0 tenants

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2255]
Now that we have an enterprise account with auth0, we should add a "production"
tag to our main tenant, "justice-cloud-platform", and a "development" tag to
"moj-cloud-platforms-dev".

This will influence how auth0 the company responds if we need support.

This page describes tagging:
https://auth0.com/docs/dev-lifecycle/set-up-multiple-environments

...but we will need to do it via terraform.

**Comment by AntonyBishop** [comment]
Closed due to age of ticket
