### ISSUE TITLE
Communicate to users about why we are making these Ingress controller changes

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2257]
We need to put some comms to our users in #cloud-platform-update about our plans to create one Ingress controller per namespace.

The message should include the following:

- What we are doing?
- Why we are doing it?
- Impact to service teams?
- When we are going to be making changes?

**Comment by digitalronin** [comment]
Google doc with draft user comms:
https://docs.google.com/document/d/1t4s9xcKUYvBghwFEVC4q0BRWd-XHaDneB4rBherKH6o/edit#

**Comment by digitalronin** [comment]
This is done - comms went out via the usual slack channels last week.
