### ISSUE TITLE
Remove fluentd

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2260]
Now that we have fluentbit, which seems to run well and offer additional capabilities, we should remove fluentd.

Before we can do that, we need to:

* Start using fluentbit for the audit logs
* Teams might be using fluentd index to build their Dashboards(teams need to migrate to use fluent-bit logs to build their dashboards)
https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/dashboards?_g=()
* ???

This is a placeholder ticket. Please add more detail as we plan how to implement it.

**Comment by vijay-veeranki** [comment]
Teams might be using fluentd index to build their Dashboards

https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/dashboards?_g=()

So need to request teams to migrate them?
