### ISSUE TITLE
Create a OPA policy to reject cronjobs or jobs which don't use "ttlSecondsAfterFinished"

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2261]
Create a OPA policy to reject cronjobs or jobs which don't use "ttlSecondsAfterFinished".

Finished Jobs created by cronjobs are usually no longer needed in the system. Use the TTL mechanism for Cronjob or jobs by settting ttlSecondsAfterFinished, so that a Job can be cleaned up automatically some time after it finishes.

We have delete-completed-jobs setup to clean up all the completed jobs, which does not have ttlSecondsAfterFinished, deleting a completed Jobs will clean up the Pods it created. You can still see the logs of the deleted Pod in kibana

But is will be good to have a OPA policy to reject cronjobs or jobs which don't have "ttlSecondsAfterFinished"

**Comment by AntonyBishop** [comment]
Closed due to age of ticket
