### ISSUE TITLE
Use AWS Instance Scheduler to pause non-prod RDS out of hours

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2262]
AWS Instance Scheduler enables stopping/starting EC2 & RDS instances out of hours to save money:
https://aws.amazon.com/solutions/implementations/instance-scheduler/

The EC2 capability is not useful for us (we will eventually use auto-scaling
for that), but stopping non-prod RDS instances out of hours could be good way
of saving some money.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_StopInstance.html

RDS PostgresQL Pricing
https://aws.amazon.com/rds/postgresql/pricing/?pg=pr&loc=3

## Questions

It would be interesting to know what the potential savings are. i.e. add up all the non-prod RDS which exist, and work out the total instance-hour costs. The potential saving is around 50% of that (assuming we were to only run the RDS instances during working hours, plus a bit of leeway).

Can we identify non-prod RDS instances which have some activity overnight (e.g. scheduled batch jobs), so that we can workaround them?

Can we drive this with a tag? i.e. add a tag via our terraform module, which identifies the instance schedule which should apply to this RDS? We would want to set this by default for new, non-prod RDS instances, but ensure it did not affect production databases. How would we ensure that?

Stretch goal: Can we do something to make it easy for teams to start their RDS instances out of hours, if they need to do work at the weekend or overnight?

FYI: We are currently spending around $11,300/month on RDS - I don't know how that splits between prod & non-prod

**Comment by sablumiah** [comment]
Spike conducted. 

Conclusion is that we should implement this in out offering. 

Things to think about:

- How many scheduler-instances and per account/region
- How many schedules and periods. 
- Tagging naming policy for scheduler-instance and schedules
- Look into possibility of schedule not stopping a RDS if it is in the middle of a job
