### ISSUE TITLE
Investigate using terrascan for our source code

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2266]
Terrascan: https://github.com/accurics/terrascan

Looks like an interesting tool for us to apply to our terraform source code, including the code in the env. repo.

Have a play with it, and see if it adds value. If it does, create a github action to apply it to PRs and reject them if they're not compliant.

**Comment by pwyborn** [comment]
Conclusions here:
https://docs.google.com/document/d/1WmI6dQcQ2O7U8GsOFy4NlLHKsE5hx17aaSlj7bcpDqI/edit#

Summary Revisit when references to out of line modules sorted out (known issue):
