### ISSUE TITLE
Amend helloworld tutorial for dedicated ingress controllers

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2269]
Amend the [hello world tutorial] and source code files to use dedicated ingress controllers.

related to #2212

[hello world tutorial]: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/helloworld-app-deploy.html#deploying-a-39-hello-world-39-application-to-the-cloud-platform

**Comment by AntonyBishop** [comment]
Done
