### ISSUE TITLE
Create a 'cloud-platform-reference' namespace which users can read and use it as reference 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2270]
This ticket is to create a reference namespace which has real definitions of kubernetes resources which users can read and reuse for their namespaces.

A simple definition for deployment, service and ingress can be added to start with. But can be extended to have definition for mod-sec, prometheus-rules, circle-ci, etc

Update user guide referencing the code for real examples in places like

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/helloworld-app-deploy.html#deploying-a-39-hello-world-39-application-to-the-cloud-platform

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/using-circleci-for-continuous-deployment.html#continuous-deployment-of-an-application-using-circleci-and-helm

Questions:

Is it possible to have a namespace which will have read permissions of all users of MoJ. i.e. moj-developers group in github 

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

**Comment by AntonyBishop** [comment]
Closed due to age of ticket
