### ISSUE TITLE
Create dashboard to display how the pods are distributed across nodes

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2271]
We get a lot of the "Too many pods" error message on nodes in live-1. This is due to either capacity in the cluster or the scheduler favouring a single node. It would be nice to have a dashboard that showed visually how the pods were distributed across all of the estate. We used to have an app called kube-ops that performed this function but it was abandonware. Create a grafana dashboard to give the team this visibility to allow us to make decisions on scaling.

https://mojdt.slack.com/archives/C514ETYJX/p1598346714177000

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/3082
