### ISSUE TITLE
Define per-AZ instancegroups for worker nodes

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2272]
On 25/08/29 there was an issue affecting the AZ eu-west-2a which caused problems.

Slack threads:
https://mojdt.slack.com/archives/C514ETYJX/p1598351210195200
https://mojdt.slack.com/archives/C57UPMZLY/p1598349269058800

We have a single worker instancegroup in our kops config, which does not specify which AZ to create instances in. In contrast, we have 3 different instancegroups for our 3 master nodes, each of which specifies a different AZ.

We want to alter our kops config to control which AZ our worker nodes are created in, so that we can scale up in unaffected AZs if this happens again.

NB: This will require changes to the node recycler, which currently just looks at a single instancegroup when deciding which node to replace.

**Comment by vijay-veeranki** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/902
