### ISSUE TITLE
Enable teams to check their ingress-controllers exist

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2278]
The ingress-controller pods run in the ingress-controllers namespace. Teams
have no visibility of this namespace, so they have no way to confirm that their
dedicated ingress-controller exists before making changes to their ingress
definitions.

We need a solution for this, because if they change an ingress definition and,
for some reason, the ingress controller is not there, their service will break.

**Comment by jasonBirchall** [comment]
You could allow all authenticated users `get pods` access in the ingress-controller namespace.

**Comment by vijay-veeranki** [comment]
https://grafana.cloud-platform.service.justice.gov.uk/d/bbb2a765a623ae38130206c7d94a160f/kubernetes-networking-namespace-workload?orgId=1&refresh=10s&var-datasource=default&var-namespace=ingress-controllers&var-type=deployment&var-resolution=5m&var-interval=4h

**Comment by digitalronin** [comment]
Closing this, because we do have a way for teams to do this, as Vijay pointed out.
