### ISSUE TITLE
Investigate Auth0 alternatives

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform#228]
## Background 

On 2018-07-03 Raz and I discovered that it is possible for Auth0 Dashboard Admins to delete Auth0 tenants without confirmation.  Furthermore there is no easy way to restore them–paying Auth0 clients can request restoration, but Auth0's SLA on this is seven days.   

This, coupled with the fact that it is difficult to manage Dashboard Admins in any kind of automated way has led me to investigate alternatives. 

### Necessary

* Must **NOT** allow easy or unconfirmed deletion of **any** configuration 
* Must provide OIDC login integration to Kube so that end-users can authenticate to their apps on the cluster.
* Must be able to map GitHub OAuth via SAML or OIDC so that users can use GitHub as their IdP
* Must be able to apply rules/access controls to ensure that users logging in to clusters or services via GitHub are members of the MoJ org and also of specific teams within that org (i.e. WebOps = Admin, all other teams = ordinary users). 
* Must offer service login via GitHub (i.e. you can log in the main service via GitHub - as with Auth0)
* Must offer templating of service login users.  Ideally, admin users on the chosen service could be configured in such a way that they were only able to login if they were members of the MoJ GitHub org and the WebOps team.

## Definition of Done

- [ ] Explore Auth0 alternatives
- [ ] Document 
- [ ] Chose one as appropriate

**Comment by razvan-moj** [comment]
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml_3rd-party.html

**Comment by razvan-moj** [comment]
https://help.github.com/articles/about-authentication-with-saml-single-sign-on/ list providers supported by Github (with the note "We offer limited support for all identity providers that implement the SAML 2.0 standard")
