### ISSUE TITLE
Generate metrics on our response time

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2281]
Scrape the #ask-cloud-platform channel and look for new posts by people who are
not members of the CP team.

For such posts, find the first threaded reply from a member of the CP time, and
use that to figure out how long it took us to respond.

This is flaky, and misses lots of common edge cases (e.g. a non-CP team member
responds to a post, so we never need to respond), but it could be fun to report
on.

Average time to first review of an env repo PR would be good, too.

**Comment by poornima-krishnasamy** [comment]
First draft here: https://github.com/poornima-krishnasamy/cloud-platform-slack-metrics.

TODO: 
Find response time between time ranges. For example, monthly average

One of the edge case found during demo is, thread responded by other users and a message later acked by webops. This doesnot mean that webops hasnt responded early but it has been solved by other users of the platform.
