### ISSUE TITLE
Explore kubectl-prune

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#2287]
https://github.com/micnncim/kubectl-prune

```kubectl-prune is a kubectl plugin that prunes unused Kubernetes resources.```

Could this tool be useful to us ?

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1hO0v9Pg4HdCuHfZd_XvJfTDTq0fHUsAuYUZQYE5Th2Q/edit
