### ISSUE TITLE
Allow API access to alertmanager

### ISSUE THREAD

**Issue by mattops** [ministryofjustice/cloud-platform#2295]
Feature request.

Allow access to the alertmanager API, e.g.

https://alertmanager.cloud-platform.service.justice.gov.uk/api/v2/alerts 

This would allow teams to pull in info about currently firing alerts into their team dashboards.

Currently we have slack integration, which is ok for getting the odd alert message - however for many services and large volume of alerts it is not ideal as it is easy to miss messages.

To make this work I think you may need to reconfigure auth0  to allow access to that endpoint, and possible use a different auth mechanism.

**Comment by AntonyBishop** [comment]
Cluster-wide service. Need to ensure that it is limited to users namespaces.
