### ISSUE TITLE
Add support for typescript to sonarqube

### ISSUE THREAD

**Issue by andrewrlee** [ministryofjustice/cloud-platform#2296]
## Service name

use-of-force and licences 

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description

With the new sonarqube scanning, Is it possible to get support for typescript? our projects fail with:

<img width="487" alt="Screenshot 2020-09-04 at 09 46 45" src="https://user-images.githubusercontent.com/1517745/92221116-e30be700-ee94-11ea-8275-52e2b2a5e8a9.png">

## Contact person

@andrewrlee

**Comment by digitalronin** [comment]
It looks like Typescript is supported out of the box by SQ 2.1+

https://docs.sonarqube.org/latest/analysis/languages/typescript/

What version are we using?

**Comment by AntonyBishop** [comment]
Hi @andrewrlee 

Is this issue still required?
