### ISSUE TITLE
Provide users with administrative access to Grafana

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2299]
There are a variety of reasons for providing users with admin access to Grafana, which would improve user experience, allow teams a greater flexibility (self service) and reduce support overhead on the platform team.

So basically give all users admin access to Grafana.

Having said that, we need to ensure that in the event that Grafana gets broken that we can return it to a working state.

**Definition of done:**

- [ ] We have a tested runbook for recovery of the Grafana service
- [ ] All users have admin access to Grafana
- [ ] Update user guide
- [ ] Comms to users via #cloud-platform-update

**Comment by mikehalmamoj** [comment]
I assume that the enhanced access would continue to prevent saving the dashboard after manual edits - I think that's a really good principle to force people to maintain the JSON in their codebase.

Also - I might be reaching for the stars here - when editing the dashboard manually it would be nice if there was some visual indication that the dashboard no longer matches the JSON.
