### ISSUE TITLE
How to link Google Accounts to Keeper

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#23]
To be further specified

**Comment by AntonyBishop** [comment]
Online estimation: https://ticket-poker.herokuapp.com/tickets/166b833e-21ae-49d3-bde6-1e735fff2dae

**Comment by razvan-moj** [comment]
Documented in https://support.google.com/a/answer/7374103?hl=en, requires org 'super admin' privs; Keeper SSO architectural view documented in https://keepersecurity.com/assets/pdf/KeeperSSOConnect_v11.pdf
I have followed the steps and it does work, tested by creating accounts in my own "organization"
