### ISSUE TITLE
LAA Cluster Support Background Ticket

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform#230]
## Do not work on THIS ticket

It is for background only.  See [LAA Cluster Support](https://github.com/ministryofjustice/cloud-platform/milestone/11) for the associated tickets.

Background

We want to ensure we have necessary sign off to onboard LAA fee calculator to the platform. As a team we also want to ensure we have all the needed information to support the cluster

Proposed user journey

We know of necessary information/ process to follow to onboard live services into production. We have the needed information to support, respond to incidents and communicate out

Definition of Done

> Original Checklist - See "LAA Cluster Support" Milestone instead.
> - [ ] Whole team has access to SSH, Live0, AWS cluster
> - [ ] Install prometheus fo live
> - [ ] Alert(s) for unresponsive nodes
> - [ ] Alert(s) for unresponsive Kubernetes API
> - [ ] Alert(s) for resource utilisation
> - [ ] Alert(s) on specific containers running
> - [ ] Alert(s) outside of cluster (pingdom)
> - [ ] ~Alert(s) around~ Dashboard for application metrics (HTTP req, resource utilisation)
> - [ ] Runbook for alerts (created by person who created alert)
> - [ ] How and where we communicate incidents documented in runbook
> - [ ] Communication to users about how they contact us
> - [ ] Decision over support hours 
> - [ ] Support offering communicated to users

**Comment by kcbotsh** [comment]
@kalbir can you please create a separate ticket for Security Sign off, (Please remove from checklist after this)

**Comment by kalbir** [comment]
@kcbotsh it's https://github.com/ministryofjustice/cloud-platform/issues/240

**Comment by kcbotsh** [comment]
@alkar @sablumiah to review and write up the alerts/ runbook tickets please

**Comment by tatyree** [comment]
I've add a milestone, "LAA Cluster Support" because this style of metaticket is difficult to track.  It's fine for holding more information than the Milestone can, but it tends to make for sticky, HUGE tickets.
