### ISSUE TITLE
Find out how to trigger external-dns without deleting an ingress

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2301]
We have several situations where we need to switch web traffic from one endpoint to another, e.g.

* Moving hostnames from the default ingress controller to a dedicated one
* Upgrading from nginx-ingress to ingress-nginx helm chart
* Migrating between clusters

In all these cases, we have two valid endpoints, "old" and "new", both of which
can handle web traffic, when we want to switch from old to new, we delete the
ingress for "old", which triggers external-dns to update route53 and point the
domain name to "new".

But, this causes downtime, because many users will have cached DNS entries
pointing to "old". The "old" ingress is not there anymore, so any web requests
get a 404, even though the rest of the "old" stack is still in place - it's
just the ingress which is gone.

We need a way to trigger the route53 DNS change *without* removing the ability
for "old" to handle any web traffic that arrives after the DNS change has been
made.

**Comment by vijay-veeranki** [comment]
There is an article about "Kubernetes: Nginx and Zero Downtime in Production"

https://medium.com/codecademy-engineering/kubernetes-nginx-and-zero-downtime-in-production-2c910c6a5ed8

**Comment by vijay-veeranki** [comment]
The solution here is to have TWO load balancers and TWO nginx ingress controllers, and switch traffic between the two. Direct traffic to the temporary load balancer, update the original while there’s no traffic flowing through it, and then direct traffic back to the original ingress controller.

**Comment by vijay-veeranki** [comment]
Steps Nginx and Zero Downtime in Production : 

1) Create 2nd ingress-controller
2) Use that ingress controller class and create a new ingress.
3) In route53 identify the A and txt record, update the txt record with new ingress name.
4) external-dns will trigger and update the A record with NLB created by 2nd ingress-controller.
5) Traffic will be routed to new NLB.
6) Update are make necessary changes to the old ingress-controller
7) Switch it back by updating the txt record with old ingress name.
8) external-dns will trigger and update the A record with NLB created by 1st ingress-controller.
9) Delete the new ingress created.
