### ISSUE TITLE
Research "PrometheusMissingRuleEvaluations" alarm in low priority

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2308]
https://mojdt.slack.com/archives/C8QR5FQRX/p1599475955002700

**Comment by sablumiah** [comment]
PrometheusMissingRuleEvaluations
increase(prometheus_rule_group_iterations_missed_total{job="prometheus-operator-prometheus",namespace="monitoring"}[5m]) > 0

prometheus_rule_group_iterations_missed_total can indicate that some rule groups are taking too long to evaluate.
Compare:
prometheus_rule_group_last_duration_seconds 
against
prometheus_rule_group_interval_seconds
This can tell you which group is at fault and if the data goes back enough, when it started happening.

Useful doc:
https://inuits.eu/blog/prometheus-timeouts/
