### ISSUE TITLE
Terraform Module for AWS Aurora Serverless

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2314]
Create a TF module for AWS Aurora

NB: Aurora serverless (which is the one that could save us a lot of money) is not yet available in London.

If possible, it would be good if we could give teams the option of using traditional (i.e. with dedicated database servers), or serverless, whether that's simpler by having two different modules, or a single module with configuration options.

**Comment by poornima-krishnasamy** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-rds-aurora
