### ISSUE TITLE
Create a "namespace info" page in HOODAW

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2325]
We can gather a lot of information about namespaces from scanning the cluster
and our source code repos. It would be very nice to have a web page per
namespace which presented this information in a useful way. This could include
things like:

* Namespace name
* Production?
* Application & team name
* Domain name(s) (from scanning ingress & certificates)
* Slack channel to contact the team (from the namespace definition)
* Source code URL
* Cluster resource usage (pods, memory, CPU - as per the defunct "namespace usage report")
* Significant (or all) AWS resources used (from scanning the terraform code)
* Cost (details TBD)
* Any outstanding issues (e.g. namespace doesn't have a slack-channel annotation)

> Not all of this needs to be present in the first iteration of this ticket,
> but it would be great to have an initial page per namespace which we can
> iterate on.

**Comment by AntonyBishop** [comment]
@digitalronin is this still required?

**Comment by digitalronin** [comment]
@AntonyBishop All items in the list, except the last, are done. e.g. 
https://reports.cloud-platform.service.justice.gov.uk/namespace/c100-application-production

I'd call this one done, TBH - we can always raise a ticket whenever there's a specific feature we'd like to add to that page.
