### ISSUE TITLE
NS records for court-data-adaptor.service.justice.gov.uk

### ISSUE THREAD

**Issue by archferns** [ministryofjustice/cloud-platform#2329]
## Service name
[Court Data Adaptor](https://github.com/ministryofjustice/laa-court-data-adaptor/)

## Service environment

- [x] Dev
- [x] Test
- [x] UAT
- [x] Staging
- [x] Prod

## Impact on the service
No impact.

## Problem description
We would like to request new ns records for these environments please.

## Contact person
[Arlston Fernandes](https://mojdt.slack.com/archives/DNFSXB4AG)

**Comment by vijay-veeranki** [comment]
Spoke to Arlston Fernandes.

court-data-adaptor.service.justice.gov.uk is deligated to dsd account.

User can create the ingress using dev/staging or prod and external-dns will take care of adding records to the zone.
