### ISSUE TITLE
Configure alerts in pfs_dev slack channel 

### ISSUE THREAD

**Issue by davidthomas22** [ministryofjustice/cloud-platform#2333]
## Service name

Prisoner facing services Hub

## Service environment

- [ ] Prod / Production

## Impact on the service

Enables alerting in slack to improve production monitoring

## Problem description

Afternoon, We are attempting to configure prometheus alerts as highlighted in your guide https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts for the pfs_dev slack channel. I have been asked to raise a support ticket with the following details to allow the CP team to create the Alertmanager route for our alerts. 

namespace name - prisoner-content-hub-production
team name - pfs hub
application name - Prisoner Content Hub
slack channel - pfs_dev
kubernetes secret name where the webhook url is stored - slack-webhook
severity level (warning/information) - warning

Do we require a separate webhook for each severity type? 

## Contact person

pfs_dev channel on slack 

or 
@Ryan Brooks 
@davidthomas

**Comment by pwyborn** [comment]
Pull request[new slack-alert for #pfs_dev channel #904](https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/904)

**Comment by pwyborn** [comment]
davidthomas  11:44 AM 28/09/2010
Hi Paul,
Thanks for setting up the alert manger on our pfs_dev channel, Do you provide us the custom severity level as outlined in the cloud platform user guidance?
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-slack-webhook-and-amend-alertmanager

paulwyborn  11:48 AM  28/09/2010
Hi David thanks - just setting up the config now. Will let you know when all set up.
the severity will be “pfs-hub”.
You should be able to set up severity level for all types within your config (once I have set it up)

paulwyborn  1:19 PM  28/09/2010
Hi David - all set up. You should be able to set up your alert configs now?
1:20
as per here https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-prometheusrule
