### ISSUE TITLE
Investigate on issue separate ingress-controller for api and frontend

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2337]
When users starting using separate ingress controller for each namespace they started seeing some irregular errors.

In this case users are using separate ingress controller for their API namespace and Frontend namespace.

Changing it to use default ingress controller to both namespaces, they don't seem to have those issues.

So investigate if using separate ingress-controller for a namespace is the cause for this sporadic errors.

Conversation related to this
https://mojdt.slack.com/archives/C57UPMZLY/p1599821891478100

**Comment by AntonyBishop** [comment]
No longer needed as not moving to dedicated ingress controllers.
