### ISSUE TITLE
Upgrade Default Ingress Controller version

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2339]
We need to update the Default Ingress controller in line with other controllers.

We want to do this with no downtime to users.

There is a down time while upgrading our default ingress controller.
https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx#migrating-from-stablenginx-ingress

To avoid downtime.

Steps:

1) Create second Ingress controller
2) Create second ingress for all ingress using default ingress controller and change
their name and ingress class to use second ingress controller
3) Change all the txt records created by external-dns to point to new ingress name.
4) external-dns will trigger and update the new NLB information for the A records in the route53 zone
5) Upgrade default Ingress controller
6) Change all the txt records created by external-dns to point to old ingress name.
7) external-dns will trigger and update the old NLB information for the A records in the route53 zone
8) Delete new ingress created
9) Delete new ingress controller

Documented procedure we followed while trying to move some prod services using this procedure

https://docs.google.com/document/d/1hZzBkXB7_K0_NfYHX6enXFwp79MdHk_zRPYR3j9gVGk/edit

**Comment by vijay-veeranki** [comment]
This ticket is related to this [2238](https://github.com/ministryofjustice/cloud-platform/issues/2238)

When worked on 2238, we were planning to have default ingress controller just for cloud-platform and teams will have their own ingress controller.

But this is changed now, so most of the users will use this default ingress controller.

We will have a down time upgrading this ingress controller so we need to figure out how to handle it.
https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx#migrating-from-stablenginx-ingress

**Comment by digitalronin** [comment]
Can't we use the "zero downtime" process to upgrade the default ingress controller?

https://runbooks.cloud-platform.service.justice.gov.uk/zero-downtime-ingress-upgrade.html#zero-downtime-ingress-controller-upgrade

**Comment by imran-awan1** [comment]
https://github.com/ministryofjustice/cloud-platform/pull/2374

**Comment by vijay-veeranki** [comment]
[https://app.zenhub.com/files/126507503/d68d6da3-2dd6-40d2-8dd9-070b9d6a1477/download](https://app.zenhub.com/files/126507503/d68d6da3-2dd6-40d2-8dd9-070b9d6a1477/download)

This is comparing the two options.

One with multiple ingress and dns switch updating the txt record
Second updating ingress class and letting external-dns to take care of it
