### ISSUE TITLE
Tag all AWS resources with namespace name

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2348]
The cost reporter page of HOODAW:
https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk/namespace_costs

...works by running [infracost] on all namespaces' terraform code, and mixing in shared costs from
the [AWS cost explorer] API.

If all AWS resources in the environments repository were tagged with a namespace name, we wouldn't
need infracost - we could get all the costs from the cost explorer.

This would be an additional tag for AWS resources, I would suggest `Namespace` as the tag name (the
convention for AWS tags names seems to be capitalised string values).

It may be necessary to sub-divide this ticket into multiple, smaller tickets:

* Update all the modules to use namespace tag.
for example: this elasticache module don't have namespace tag
https://github.com/ministryofjustice/cloud-platform-terraform-elasticache-cluster/blob/main/main.tf#L71-L79

* Ensure every single namespace in the environments repository defines a `namespace` variable
* Update all of our terraform modules to tag all created resources with `Namespace=${var.namespace}`
* Modify the HOODAW [cost reporter] to get data via the Namespace tag, instead of infracost

[infracost]: https://infracost.io
[AWS cost explorer]: https://aws.amazon.com/aws-cost-management/aws-cost-explorer/
[cost reporter]: https://github.com/ministryofjustice/cloud-platform-cost-calculator

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/3559#pullrequestreview-506657748

https://github.com/ministryofjustice/cloud-platform-environments/pull/3613

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket/pull/32#pullrequestreview-511794145
https://github.com/ministryofjustice/cloud-platform-environments/pull/3632#pullrequestreview-511794501
https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket/pull/33#pullrequestreview-511875693
https://github.com/ministryofjustice/cloud-platform-environments/pull/3637

**Comment by pwyborn** [comment]
SQS:
https://github.com/ministryofjustice/cloud-platform-terraform-sqs/pull/21

DMS:
https://github.com/ministryofjustice/cloud-platform-terraform-dms/pull/3

**Comment by pwyborn** [comment]
DynamoDb:
https://github.com/ministryofjustice/cloud-platform-environments/pull/3689
