### ISSUE TITLE
Remove ex-staff access

### ISSUE THREAD

**Issue by KPobeeNorris** [ministryofjustice/cloud-platform#235]
## Service name

PVB

## Service environment

- [ X ] Dev / Development
- [X] Staging
- [ X ] Prod / Production
- [  ] Other

## Impact on the service

Yann Marquet (aka stupidcodefactory) no longer works for PVB and we are currently going through the process of removing his access to various services.  We would like to request that any access he has via Cloud Platform (e.g. AWS/SSH) also be revoked.

## Problem description

We want to ensure that only those employed, and have the correct permissions, have access.

## Contact person

Slack - @kath.pobee-norris

**Comment by nayoa** [comment]
Removed Yann from AWS MOJDSD and Sentry. 

SSH access has been removed for both staging and prod pvb2-deploy and pvbpublic-deploy.
