### ISSUE TITLE
Auto-delete out of date HOODAW data items

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2361]
If, e.g. a namespace is deleted, there is currently no automated process for removing the old namespace data from HOODAW for the namespace costs report.

All HOODAW data should be updated daily, at worst. We could modify the storage classes to delete any data which is more than say, 3 days old.

This could be a very simple way to ensure that namespaces which have been removed from the cluster are also removed from HOODAW.

**Comment by AntonyBishop** [comment]
@digitalronin have we done this?

**Comment by digitalronin** [comment]
No, it still needs doing.
