### ISSUE TITLE
Requesting Integration ID for Pingdom Slack notification

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#2364]
## Service name

Pingdom Slack integration

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Problem description

I am following this guide and it says to create a ticket to get an integration ID for pingdom/slack integration https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#adding-slack-notification

Team name: CLA/FALA
Application name: CLA Backend
Slack channel: [hash]cla-alerts

## Contact person

Slack: [hash]Said

**Comment by pwyborn** [comment]
Pull request [new slack-alert for #cla-alerts channel #905](https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/905)

**Comment by pwyborn** [comment]
Said  4:02 PM 28/09/2020
hi paul, i think that's for the fala application
4:03  28/09/2020
The new one is for cla_backend

Said  9:46 AM  29/09/2020
Hi paul, any update on the PR as we need it for the cla_backend application

paulwyborn  10:55 AM   29/09/2020
Hi Said - sorry to which PR are you referring? Is it the alert channel one?

Said  10:56 AM   29/09/2020
The one you commented on this issue https://github.com/ministryofjustice/cloud-platform/issues/2364#issuecomment-699979186
pwybornpwyborn
Comment on #2364 Requesting Integration ID for Pingdom Slack notification
Pull request new slack-alert for #cla-alerts channel #905
<https://github.com/ministryofjustice/cloud-platform|ministryofjustice/cloud-platform>ministryofjustice/cloud-platform | Yesterday at 1:36 PM | Added by GitHub

paulwyborn  10:59 AM   29/09/2020
ok - to differentiate between the 2 - I may change the severity from “CLA/FALA” to just “CLA” - it normally follows the team name - but have a feeling it needs to be unique

Said  11:00 AM   29/09/2020
If it needs to be unique can we suffix it with the Application name?

paulwyborn  11:02 AM   29/09/2020
So what would the full severity be best?
laa-cla or laa-cla-backend
11:02
or whatever is best for you?

Said  11:04 AM   29/09/2020
Just to be clear, you need to have this value to be unique. And if we add another app it needs to have a new unique severity value?
11:05
if that's the case then please go ahead with laa-cla-backend

paulwyborn  11:12 AM   29/09/2020
I think we will go ahead with laa-cla-backend 
in that case
:thank_you:
1
:+1:
1

11:13
In a meeting at the moment - will do after meeting

**Comment by pwyborn** [comment]
Pr updated

**Comment by pwyborn** [comment]
I think we will go ahead with laa-cla-backend 
in that case
:thank_you:
1
:+1:
1

11:13
In a meeting at the moment - will do after meeting

paulwyborn  1:21 PM
Hi Said - should all be in place now (severity:laa-cla-backend)

Said  3:39 PM
Thanks paul, so in the end of this, I think I was expecting to get an integration id which I can use with the pingdom terraform resource

paulwyborn  4:22 PM
Ah - sorry - think I had got the wrong end of the stick. Setting up an integration id now
4:27
integration=107761
4:27
Hope this is ok Said?
New

Said  4:31 PM
Thank you

paulwyborn  4:32 PM
Ah Said - I see there is already one set up in 2019 - would you rather keep it separate?:
#cla-alerts Slack (Get Access CLA/FALA team)
4:34
that might be being used for template-deploy? (edited) 
4:35
Think we will leave it - having given you a new integration id?

Said  4:36 PM
Hey Paul, yeah lets keep it separate.

paulwyborn  4:36 PM
:+1:
