### ISSUE TITLE
Apply pipeline dependency removal - Resources applied from Environments repository into live-1

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2371]
Linked tickets: 
1. Networkpolicies https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2369

2. limitranges and resourcequotas https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2370

The following namespaces have resources applied via the apply pipeline in the live-1 cluster.

The apply pipeline applies these resources for a number of namespaces.
These resources are re-applied if the NS is lost for any reason, but would be missing if the apply pipeline does not run or there is an issue with concourse.

These resources are also not getting applied in any test cluster.

kube-system
kuberos
logging
monitoring
opa

The resource types vary depending on the namespace.

There is also  user roles file in the root of the namespace folder (user-roles.yaml) Look into taking this out of the repo, and also applied in test clusters

**Comment by mogaal** [comment]
The components for all these modules were moved inside the terraform module. It is the divergence pipeline the one who catches any drift.
