### ISSUE TITLE
*cla.dsd.io SSL Certificate Renewal

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2372]
Generation of CSR and SSL Cert installation.

**Comment by pwyborn** [comment]
ssl cert renewed and uploaded to aws

**Comment by pwyborn** [comment]
Future ref re Gandi:
Procedure:

- Command line

`openssl req -nodes -newkey rsa:2048 -sha256 \   -keyout  cases.civillegaladvice.service.gov.uk.key \  -out  cases.civillegaladvice.service.gov.uk.csr`

- send csr file to Gandi

- from this an intermediary and a crt file are generated (download from Gandi)

-  Build a cases.civillegaladvice.service.gov.uk.chain file (this is just the intermediary file)

- Create a cname (Tony or whoever regenerated Gandi cert should have details) to get approval on AWS

-  upload the cert:

`aws iam upload-server-certificate --server-certificate-name new-06-10-2020cases.civillegaladvice.service.gov.uk --certificate-body file:///Users/paulwyborn/projects/cla_frontend-deploy/cases.civillegaladvice.service.gov.uk.crt  --certificate-chain file:///Users/paulwyborn/projects/cla_frontend-deploy/cases.civillegaladvice.service.gov.uk.chain --private-key file:///Users/paulwyborn/projects/cla_frontend-deploy/cases.civillegaladvice.service.gov.uk.key`

-  Change the certificate on the AWS console (loadbalancer listener) to the new certificate

Note for cla-frontend where websockets are involved (the 'Load Balancer Protocol' is 'TCP' and not 'HTTPS':

- ssh onto instance as root

- cd into /etc/nginx/ssl

- `ls-lah`

- `chattr -i crt`

- `cp crt crt.bu`

- `cp key key.bu`

- `rm crt`

- `rm key`

- `vi key` insert contents of the local 'cases.civillegaladvice.service.gov.uk.key'

- `vi crt' insert contents of the local 'cases.civillegaladvice.service.gov.uk.crt'

- `service nginx stop`

- `service nginx start`

- `service nginx status`

-  Check actual webpage certificate
