### ISSUE TITLE
Documentation - Write a run book for all the components that only get installed for live-1

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2373]
Write a run book entry for all the components that only get installed for live-1 clusters and not for test clusters
Most of these resources have a `count` flag 

This will enable team member who creates a test cluster to see what is missing and how to install it for testing if required.

**Comment by poornima-krishnasamy** [comment]
Currently in the Firebreak sprint and will look into it after the 2 week firebreak sprint.
