### ISSUE TITLE
Configure GuardDuty to alert us if IAM users are created manually

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2375]
We currently have 570 IAM users, the overwhelming majority of which are created via code in the environments repository on github.

We should have a security tool scanning for IAM users which were created manually, so that a successful attacker cannot hide a malicious IAM user amongst all the legitimate, automatically-generated ones.

**Comment by AntonyBishop** [comment]
Need to discuss with Jake

**Comment by AntonyBishop** [comment]
Discussed with Jake. Is not a Master Account feature. If we want this we would enable at CP account level.
