### ISSUE TITLE
Automate copying of secrets to CI/CD pipelines

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2377]
For their CI/CD pipelines, teams:

1. create ServiceAccounts via YAML files in the env. repo, which stores credentials in kubernetes secrets in their namespaces
2. hand-copy the credentials from the kubernetes secrets into their CI/CD pipelines (usually circleci, sometimes github actions)

These credentials are one of the reasons it would be harder to replace live-1 if there is a problem - all the teams would have to repeat step 2 to get their CI/CD pipelines working again.

We should automate step 2.

The `source-code` annotation provides the github repository/repositories which correspond to a namespace, and we can look at the repository to see if there is a `.circleci/config.yml` file or a `.github/workflows/whatever.yml` file.

For github actions, we can push a secret directly into those repositories, so that the action has the credential available. For circleci we can identify the project(s) from the github repositories, and push the secret into the circleci project (I'm not clear if it is possible to generate an organisation-wide circleci API key with privileges to add environment variables to any project within the organisation. If not, we may need to jump through some hoops to make this work).

For this to be useful, the secret in the CI/CD pipeline must be recreated automatically if the apply pipeline regenerates the kubernetes secret.

We will also need user comms around this, and ideally a CLI feature to automate it, from the user's POV. These could be separate tickets.

**Comment by AntonyBishop** [comment]
Change of direction. Closed.
