### ISSUE TITLE
Double replicas of proxy pods

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2378]
We have a number of proxy pods that live on Cloud Platform. Currently there is only one replica per proxy. Due to the nature of Kubernetes all services that require high availability should have a minimum of two replias.

Bump the number of replicas for the following proxies:
- Prometheus
- AlertManager
- Kibana

This should be tested and approved before applying to live.

**Comment by AntonyBishop** [comment]
Done
