### ISSUE TITLE
Fix labelling issue for new support issues on GitHub

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform#238]
## Background

In order to label an issue, a user must have `write` permission on a repo.  The default permission for members of the the MoJ github organisation is `read` and it is not practical to change this.  As a result, when someone who is not on the `WebOps` github team–who have `write` permissions–raises an issue, it does not get labelled properly.  This means that it does not automatically appear on waffle in the 'Support To Do' column. 

There are three possible fixes.  These are:

Change the default user permissions for the MoJ organisation to `write`.  This option has been discussed with Kerin, and rejected on the grounds that the GitHub permissions system would make this a very problematic change.  The reasons are complicated and beyond the scope of this summary–talk to Kerin if you need more information.

Create a team consisting of everyone in the organisation.  This was rejected because it requires additional work at the time a user joins (they would be removed automatically when they are removed from the organisation).  

Add a webhook to automatically label new issues that use the `Cloud Platform Support Request` template with the correct label.

## Proposed user journey

Someone who is NOT a member of the `WebOps` team creates a new issue using the `Cloud Platform Support Request` template.  Their issue is automatically labelled for the support team.

## Approach

Fork and adapt [this node script](https://github.com/sfbrigade/github-auto-label) or one like it to check the template (or some other data/metadata in the issue) and apply the the `support team` label if needed.  

## Questions / Assumptions

The [example node script](https://github.com/sfbrigade/github-auto-label) is shown running on heroku.  Would it be better to run it as a lambda? 

## Definition of done

- [x] Decide what the script needs to look for in order to correctly label new support tickets (template name, boilerplate copy, etc).  
- [x] Change the script to write the correct label. 
- [x] Deploy the script as an AWS lambda or on heroku, as appropriate 
- [x] Test manually with some new issue 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tatyree** [comment]
I've removed the lowest-level step for forking the example node script.   It was really too low level to be in the checklist and it can probably be done better with the Serverless Framework's Components.

**Comment by tatyree** [comment]
I had to do a lot of system-level yak shaving on Thursday as there were issues with xcode and serverless-components (I've commented on my fix here https://github.com/serverless/components/issues/172.  TL;DR - make sure your xcode is up-to-date and its CLI is correctly linked before you install serverless components).

**Comment by tatyree** [comment]
Friday didn't get a chance to do anything with this owing to JAC, retro and PRs.  Picked up again in spare time on Sunday only to discover my permissions on the mojdsd AWS account had been downgraded and I couldn't get to Lambda, IAM or the API gateway.  Resolved this morning.

**Comment by tatyree** [comment]
I'm putting this on hold for now while I work on documenting what a good PR looks like.   Will pick it up again on Thursday.

**Comment by kcbotsh** [comment]
could you quick estimate this @tatyree?

**Comment by tatyree** [comment]
This is done and deployed as a working prototype on my MoJ digital Heroku account.  I'm going to raise a new ticket to get it moved to the departmental account, add some tests and document it properly.
