### ISSUE TITLE
Upgrade grafana to use the latest version

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2384]
Upgrade grafana to use the latest version.

User trying  transforms in Grafana getting error "TypeError: Cannot read property 'data' of null" when selecting the outer-join transform.

communication in ask related to this
https://mojdt.slack.com/archives/C57UPMZLY/p1601386552085700

This is been fixed in the latest release. Upgrade grafana to latest version, test to see if this issue is resolved in the latest version before applying to live-1.
https://github.com/grafana/helm-charts/blob/main/charts/grafana/Chart.yaml

**Comment by AntonyBishop** [comment]
Close
