### ISSUE TITLE
Create NS Records for HMPPS EMS Prod Zone in DSD Account

### ISSUE THREAD

**Issue by jacobleonwoffenden** [ministryofjustice/cloud-platform#2390]
## Service name

HMPPS EMS

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

None

## Problem description

Create NS records for zone (electronic-monitoring.service.justice.gov.uk) in DSD account

## Contact person

Jacob Woffenden - jacob.woffenden@digital.justice.gov.uk

**Comment by jacobleonwoffenden** [comment]
Awaiting approval/deployment of https://github.com/ministryofjustice/cloud-platform-environments/pull/3234

**Comment by vijay-veeranki** [comment]
Added the NS records under 
"Route 53/Hosted zones/service.justice.gov.uk" in DSD account
