### ISSUE TITLE
Look into AWS Perspective

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2391]
https://aws.amazon.com/about-aws/whats-new/2020/09/introducing-aws-perspective/

AWS Perspective maintains an inventory of AWS resources from the accounts and AWS Regions that you import. It derives relationships between discovered resources and presents them in a web application. You get a breakdown of your AWS resources grouped by type from across your AWS accounts and Regions. You can search for existing resources of interest and start creating architecture diagrams that represent a workload.  

Each architecture diagram includes data relating to historic costs and other metadata for the resources it contains

**Comment by pwyborn** [comment]
See:
[AWS Perspective](https://docs.google.com/document/d/1obX2Tmubq9Zzxs5pHnS-KG3bsParr6mw/edit#heading=h.gjdgxs)

Conclusion:
This product is in it’s infancy (less than 2 months old). I think that for the cost - at the moment (unless we identify a real need for this) type of information - it is not worth it. 
At the moment it is installation by template only (I can find no terraform provider for it so far)
The dashboard is a little clunky and slow
Revisit in a year's time when it is more established.
