### ISSUE TITLE
Redirect DNS traffic from the new controller to the default controller

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2400]
This is related to [2339](https://github.com/ministryofjustice/cloud-platform/issues/2339)

There is a down time while upgrading our default ingress controller.
https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx#migrating-from-stablenginx-ingress

To avoid downtime.

Steps: 

1) Create second Ingress controller
2) Create second ingress for all ingress using default ingress controller and change 
their name and ingress class to use second ingress controller
3) Change all the txt records created by external-dns to point to new ingress name.
4) external-dns will trigger and update the new NLB information for the A records in the route53 zone
5) Upgrade default Ingress controller
**6) Change all the txt records created by external-dns to point to old/default ingress name.**
**7) external-dns will trigger and update the old NLB information for the A records in the route53 zone**
8) Delete new ingress created
9) Delete new ingress controller

Redirect DNS traffic from the new controller to the default controller, by changing all the txt records created by external-dns to point to old/default ingress name. External-dns will trigger and update the default NLB information for the A records in the route53 zone

prerequisite:
1) Second ingress controller is created successfully
2) Create second ingress for all ingress using default ingress controller and change 
their name and ingress class to use second ingress controller
3) Change all the txt records created by external-dns to point to new ingress name.
4) external-dns will trigger and update the new NLB information for the A records in the route53 zone
5) Upgrade default Ingress controller

Approach:

Change the txt records created by external-dns to point to old/default ingress name.

When we create a ingress, external dns will create a "A" record and associated TXT record for it.

```
A Record:
helloworld-app-starter-pack.apps.mogaal.cloud-platform.service.justice.gov.uk.
A
ALIAS a424ae3f355a148bbb5c8ed21c91d23d-0e00aad8de3af6f3.elb.eu-west-2.amazonaws.com. 

TXT record:

_external_dns.helloworld-app-starter-pack.apps.mogaal.cloud-platform.service.justice.gov.uk.
TXT 
"heritage=external-dns,external-dns/owner=mogaal,external-dns/resource=ingress/starter-pack/helloworld"
```
TXT record explination:
external-dns/owner=mogaal (clustername)
external-dns/resource=ingress/starter-pack/helloworld(namespace/ingress name)

Make sure the default ingress-controller is upgraded and all prerequisite are met.

To redirect DNS traffic from the new controller to the default controller, we can directly update the LB information in the A record, but external-dns will match with the ingress name and replace the LB information associated with the new ingress.

So Update the "external-dns/resource" with the old/default ingress name. External-dns will update the A record by getting the LB information associated with the old/default ingress.

Try this on couple of test namespaces, this should redirect DNS traffic from the new controller to the default controller.
When we are confident, create a script to update ingress name on all the TXT record to use the new NLB. 

Do it for non-prod namespaces first and once no issues identified, update the prod namespaces.

**Comment by poornima-krishnasamy** [comment]
Code related to this: https://github.com/ministryofjustice/cloud-platform-ingress-migrator/commit/bf218ec5085b638d37640753fa0ec82fb4cff613

**Comment by digitalronin** [comment]
Completed by https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1004
