### ISSUE TITLE
Delete new ingress controller and new ingress.

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2401]
This is related to [2339](https://github.com/ministryofjustice/cloud-platform/issues/2339)

There is a down time while upgrading our default ingress controller.
https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx#migrating-from-stablenginx-ingress

To avoid downtime.

Steps: 

1) Create second Ingress controller
2) Create second ingress for all ingress using default ingress controller and change 
their name and ingress class to use second ingress controller
3) Change all the txt records created by external-dns to point to new ingress name.
4) external-dns will trigger and update the new NLB information for the A records in the route53 zone
5) Upgrade default Ingress controller
6) Change all the txt records created by external-dns to point to old/default ingress name.
7) external-dns will trigger and update the old NLB information for the A records in the route53 zone
**8) Delete new ingress created**
**9) Delete new ingress controller**

Once the traffic is routed through the default ingress controller. Delete the second ingress-controller created and also delete the second ingress created

prerequisite:
1) Second ingress controller is created successfully
2) Create second ingress for all ingress using default ingress controller and change 
their name and ingress class to use second ingress controller
3) Change all the txt records created by external-dns to point to new ingress name.
4) external-dns will trigger and update the new NLB information for the A records in the route53 zone
5) Upgrade default Ingress controller
6) Change all the txt records created by external-dns to point to old/default ingress name.
7) external-dns will trigger and update the old NLB information for the A records in the route53 zone

Approach:

Make sure all the prerequisite are met, once the traffic is routed through the default ingress controller. Delete the second ingress-controller created and also delete the second ingress created

**Comment by poornima-krishnasamy** [comment]
Code commit related to this: https://github.com/ministryofjustice/cloud-platform-ingress-migrator/blob/main/bin/delete-k8snginx-class-ingresses.rb

**Comment by digitalronin** [comment]
Completed by https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1006
