### ISSUE TITLE
cases.civillegaladvice.service.gov.uk SSL Certificate Renewal

### ISSUE THREAD

**Issue by exonian** [ministryofjustice/cloud-platform#2402]
## Service name
CLA Frontend

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service
Production domain's cert was expiring 10 days from now. Service still on TD so not able to benefit from certmanager yet

## Problem description
Paul has now issued and installed the new certificate, valid for another year, so we are all set but this is to record the work.

## Contact person
Michael Blatherwick
laa-cla-fala slack channel

**Comment by AntonyBishop** [comment]
Certificate renewed and installed.
