### ISSUE TITLE
Modify RDS module re. minor versions

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2404]
If users have "auto upgrade minor versions" enabled for their RDS instances, they should not specify a minor version in their terraform code. If they do, our apply pipeline breaks after the RDS instance has been upgraded.

Modify the RDS module so that:

* Auto upgrade minor versions is configurable (if it isn't already) and defaults to true
* If auto upgrade minor versions is enabled, disallow specifying a minor DB version in db_engine_version

If the second point is not possible in terraform, create an automated enforcement mechanism for it (rego policy?)

**Comment by AntonyBishop** [comment]
Aged out
