### ISSUE TITLE
Replace many, specific security group rules with a fewer, generic ones

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2407]
This issue:
https://github.com/kubernetes/kubernetes/issues/93514

...caused the [incident on 2020-10-06]

This is a fix:
https://github.com/kubernetes/kubernetes/pull/93515

Apply this to live-1 (after sufficient testing, of course)

[incident on 2020-10-06]: https://runbooks.cloud-platform.service.justice.gov.uk/incident-log.html#incident-on-2020-10-06-09-07-intermittent-quot-micro-downtimes-quot-on-various-services-using-dedicated-ingress-controllers

**Comment by AntonyBishop** [comment]
Aged out
