### ISSUE TITLE
live-1 ingress controllers are unstable

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2416]
We are seeing ingress controller pods restarting frequently (currently 2 of our 6 pods have 52 restarts, and a third is crash-looping).

This issue is a reference point for our ongoing efforts to resolve this.

**Comment by digitalronin** [comment]
I've asked teams to remove mod-sec annotations from their ingresses. Currently, 24 ingresses have these.

**Comment by digitalronin** [comment]
One strand of work: Moving ingress controller to dedicated node test
https://mojdt.slack.com/archives/C514ETYJX/p1602499367224000

**Comment by digitalronin** [comment]
Another strand of work: Create fallback ingress controller
https://mojdt.slack.com/archives/C514ETYJX/p1602499903227000

**Comment by jasonBirchall** [comment]
We found a way to roll the ingress controllers onto new (dedicated) nodes without downtime.

**Comment by jasonBirchall** [comment]
Three new nodes added to the cluster in anticipation of ingress-controllers dedication.

**Comment by vijay-veeranki** [comment]
Created new module using the latest [chart version](https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/Chart.yaml)

Module:
https://github.com/ministryofjustice/cloud-platform-terraform-k8s-ingress-controller.

WIP to test Tolerations and affinity rules to get this new ingress-controller pods running on the new dedicated node group for ingress-controller.

**Comment by digitalronin** [comment]
> I've asked teams to remove mod-sec annotations from their ingresses. Currently, 24 ingresses have these.

I've removed all the mod-sec annotations via `kubectl edit ingress` for the remaining ingresses which had them. We'll need to keep an eye on this, in case teams redeploy with mod-sec annotations in place.

Next step on this strand of work is to deploy an OPA policy that prevents ingresses being deployed to the default ingress controller if they have mod-security annotations

**Comment by jasonBirchall** [comment]
A new modsec enabled ingress controller now exists in live. Service teams with a requirement for WAF can change the annotations on their ingress rules and use this controller.

**Comment by vijay-veeranki** [comment]
Applied fallback ingress controller in live-1.

https://github.com/ministryofjustice/cloud-platform-terraform-k8s-ingress-controller

**Comment by jasonBirchall** [comment]
Live-1 ingress controllers have been stable for over a week. I will close this call and outline the current status:
- Live-1 now has two ingress controller types, one with ModSec enabled and one without.
- The original controller (called nginx) is now stable and doesn't take an age to re-load config.
- The modsec controllers now have OWASP settings pre-loaded. This lightens the burden on the controller when an ingress rule requires it.

Despite closing this ticket, we will keep a close eye on performance of the Ingress Controllers in live-1.
