### ISSUE TITLE
Which Infrastructure integration tests needs to be fixed?

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2417]
So many tests have been "temporarily" disabled that they're practically useless now.

This story is to write a list of which tests are paused and some triage on why these are broken.

Fix tests comes next.

**Comment by sablumiah** [comment]
Paused Jobs

1) cert-manager when a certificate resource is created returns valid certificate from an openssl call
     # Temporarily skipped with xdescribe
     # ./spec/cert_manager_spec.rb:18

  2) external DNS when zone matches ingress domain and an ingress is created it creates an A record
     # Temporarily skipped with xdescribe
     # ./spec/external_dns_spec.rb:42

  3) external DNS when zone matches ingress domain and an ingress is deleted it deletes an A record
     # Temporarily skipped with xdescribe
     # ./spec/external_dns_spec.rb:57

  4) nginx ingress when ingress is not deployed fails http get
     # Temporarily skipped with xdescribe
     # ./spec/ingress_spec.rb:23

  5) nginx ingress when ingress is deployed using 'nginx' ingress controller returns 200 for http get
     # Temporarily skipped with xdescribe
     # ./spec/ingress_spec.rb:47

  6) nginx ingress when ingress is deployed using 'integration-test' ingress controller responds to http get
     # Temporarily skipped with xdescribe
     # ./spec/ingress_spec.rb:70

  7) nginx ingress when ingress is deployed with invalid syntax is rejected by the admission webhook
     # Temporarily skipped with xdescribe
     # ./spec/ingress_spec.rb:80

  8) Testing modsec on ingress class: 'integration-test' when modsec is deployed when the url is benign request succeeds
     # Temporarily skipped with xdescribe
     # ./spec/modsec_spec.rb:45

  9) Testing modsec on ingress class: 'integration-test' when modsec is deployed when the url is malicious request is blocked
     # Temporarily skipped with xdescribe
     # ./spec/modsec_spec.rb:53

  10) Testing modsec on ingress class: 'integration-test' when modsec is disabled when the url is benign request succeeds
     # Temporarily skipped with xdescribe
     # ./spec/modsec_spec.rb:69

  11) Testing modsec on ingress class: 'integration-test' when modsec is disabled when the url is malicious request succeeds
     # Temporarily skipped with xdescribe
     # ./spec/modsec_spec.rb:77

  12) tzcronjobs job is scheduled
     # Temporarily skipped with xdescribe
     # ./spec/tzcronjob_spec.rb:17

**Comment by sablumiah** [comment]
First set of tests to look into are nginx tests as it seems some of the other tests are failing also due to the same reason of ingresses taking too long to create

https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2788

**Comment by davidread** [comment]
@sablumiah says this list is out of date. Some have been migrated to Go.
