### ISSUE TITLE
Set up AWS ServiceQuota and/or Trusted Advisor to alert us when we approach quota limits

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2418]
As per these links and advice from Ross Boast of AWS:

* using Trusted Advisor to notify on service limits: https://aws.amazon.com/blogs/mt/monitoring-service-limits-with-trusted-advisor-and-amazon-cloudwatch/
* https://aws.amazon.com/solutions/implementations/limit-monitor/
* https://docs.aws.amazon.com/servicequotas/latest/userguide/configure-cloudwatch.html

> The Service Quota console and API should show both limits and usage, so it would be worth periodically checking that through manual or automated means using the links above. We also talk about managing service quotas as part of the reliability pillar of the Well Architected review when designing a workload and the guidance for that question may help: https://wa.aws.amazon.com/wat.question.REL_1.en.html. Based on my personal experience though and if I were to generalise, it tends to always be limits related to networking, whether it’s numbers of EIPs, VPCs, etc. I know that’s no helpful retrospectively and you have hit some of the more unusual limits, when you get a chance could you confirm whether the limits you hit are listed in the Service Quota console? If they are not, I’ll raise internally and I’ll also see if I can find you more guidance but I think unfortunately, it’s one of those ‘it depends’ answers.

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/cloudformation/aws-limit-monitor
