### ISSUE TITLE
A way for users to contact the on-call person

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2420]
## Background

There is no way for users to contact the On Call person. We want to provide a route for users to contact the on-call person.

## Proposed user journey

A user has a way to contact the on-call person in the event of an incident.

## Approach

Pagerduty can create an email address that forwards an email to the person currently on call, according to the schedule. We may need some flexibility on the config, so if the email address might change due to config changes, then maybe we need an `cloud-platform-on-call@digital.justice.gov.uk` alias or something.

We also need to be sure that we can destroy that email channel if we need to.

Update user guide to advertise how to contact the team member who is on-call.

In the instructions we need to be clear (if not already done) that this is not support, it is for critical incidents. We promise best endeavour response.

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/reference/operational-processes.html#cloud-platform-operational-processes

## Definition of done

- [ ] Pagerduty email created
- [ ] Confirm we can destroy that email channel
- [ ] Update guidance to confirm how users can contact the team 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveMarshall** [comment]
👋 To whoever picks this up: PagerDuty has a way for us to set up [email integrations](https://www.pagerduty.com/docs/guides/email-integration-guide/) so PagerDuty gives us an email address we can send emails to… We could set up a Google Group that forwards to that, perhaps?

**Comment by pwyborn** [comment]
Awaiting service desk - to create google group  (request 16/12/2020 INC0935201 BAU)

**Comment by pwyborn** [comment]
04/01/2020

*************************************************************************************************************************
SERVICE DESK
INC0935201 BAU - Request - Software - G-Suite - Google Groups / Mailbox - Paul Leslie Wyborn -
To: Paul Wyborn <paul.wyborn@digital.justice.gov.uk>

Hi Paul
I have no update as yet but i have chased Digital engineer to provide an update  hope to get response soon.
Regards,

Digital Service Desk
servicedesk@digital.justice.gov.uk
Slack: #digitalservicedesk

How are we doing? Please use this link to give us feedback.
*************************************************************************************************************************

**Comment by pwyborn** [comment]
paulwyborn  9:50 AM 18/01/2021
Good morning - just wondered if there is any update on this service Desk request to create a google group for me please?
Re: INC0935201 BAU 16/12/2020

**Comment by pwyborn** [comment]
10/02/2021 09:58
https://mojdt.slack.com/archives/C59CX1RHN/p1612950988060300?thread_ts=1608110543.423600&cid=C59CX1RHN

Hi (digitalservicedesk) - is there anyway I can escalate this please? Just that it affects our on-call rota (has been 2 months).
 If I have completed something wrong - could they let me know please (or should I re-submit a new form?

**Comment by pwyborn** [comment]
[A way for users to contact the on-call person#2420 #596](https://github.com/ministryofjustice/cloud-platform-user-guide/pull/596)
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/596
