### ISSUE TITLE
Explore Splunk

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2421]
As part of our re-architecture of the monitoring platform, we want to explore if Splunk might help us to scale our monitoring infrastructure

**Comment by pwyborn** [comment]
https://registry.terraform.io/providers/splunk/splunk/latest/docs#argument-reference

https://docs.splunk.com/Documentation/Splunk/latest/Security/Setupauthenticationwithtokens

https://auth0.com/blog/auth0-and-splunk-provide-enhanced-security-and-operational-monitoring-and-insights/

**Comment by pwyborn** [comment]
https://docs.google.com/document/d/13_pKRiKdSfaaTL61Ek7LGPWFKaJHxj4_21HE1aFuSog/edit#

Conclusion (see document):
In my opinion the cost of running splunk (£160,591.63 a year) is too exorbitant. However it will have to be weighed up against other alternatives.

Although “Splunk Connect for K8s” does exist, reading the general Splunk chats Kubernetes support doesn’t seem to be there just yet.

I have managed to get Splunk running locally, Terraform config seems fine, running “Splunk Connect for K8s” chart is causing me some problems at the moment - however I have no doubt that in it will run
