### ISSUE TITLE
Cloudwatch exporter scaling problems

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2424]
We're facing scaling having problems with cloudwatch exporter because it's pulling too much data (?) and the HTTP query takes more than 1.5 mins to happens. 

We have been mitigating the problem [increasing the timeout and the interval](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/blob/main/templates/cloudwatch-exporter.yaml#L269) of the serviceMonitor. 

It might be a good time to find other ways to get the metrics? Maybe we can split into different exporters (One for RDS, SQS, DynamoDB)?

**Comment by sablumiah** [comment]
There was no easy conclusion to this ticket as all resolutions created different issues or did not resolve the primary problem stated above. 

Having multiple cloudwatch-exporters pulling different metrics still caused the same amount of API calls to aws and was still ingesting the same amount of data. 

Possible long solutions is look into YACE which is still in alpha and let users create cw-alarms directly on prometheus.
