### ISSUE TITLE
Thanos Rule deployment

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2426]
We are using Thanos sidecar with the [Prometheus deployment](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/blob/main/templates/prometheus-operator.yaml.tpl#L460-L465). Having all data in S3 allow us to query, compact and define rules (alerts).

This ticket is to deploy [Thanos Rule component](https://thanos.io/tip/components/rule.md/) in live-1 cluster in order to provide alerts for these metrics stored in S3.

**Comment by razvan-moj** [comment]
If managed Prometheus works, this won't be needed

**Comment by AntonyBishop** [comment]
Managed services is a long way off. We should proceed with original plans

**Comment by razvan-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/79
