### ISSUE TITLE
Thanos Compact - downsample/compact S3 data

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2427]
We are using Thanos sidecar with the [Prometheus deployment](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/blob/main/templates/prometheus-operator.yaml.tpl#L460-L465). Having all data in S3 allow us to query, compact and define rules (alerts).

This ticket is to deploy [Thanos Compact component](https://thanos.io/tip/components/compact.md/) in live-1 cluster in order to downsample/compact the data stored in S3.

**Comment by poornima-krishnasamy** [comment]
Details of the implementation in the doc: https://docs.google.com/document/d/17p0HfIXChX3MZvudCe7nPvBlzoHXJhuZK098_ftmka4/edit?usp=sharing
