### ISSUE TITLE
RDS Postgres connection error 

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#243]
## Service name

PVB2 (Prison Visits Booking)

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

We cannot deploy to staging (this is therefore blocking deploys to production)

## Problem description

Since 9am this morning we have not been able to deploy PVB2 on staging.
See Jenkins failed build - https://ci.service.dsd.io/view/PVB2/job/deploy-pvb2-staging/89/console

This is because of Postgres connection issue:
```
fe_sendauth: no password supplied 
```
See more here - https://sentry.service.dsd.io/mojds/pvb2-staging/issues/32828/

No changes have been made to the code base that impact Postgres configuration. Same error occurs if we re-deploy an older commit

We are aware that pvb2-deploy repoy contains credentials for RDS Postgres and these have not been changed.

```
#pvb2-secrets.yaml
prod:
  rds:
    db-master-username: pvb2
    db-master-password: XXXXX
```

## Contact person

@TobyRetallick | toby.retallick@digital.justice.gov.uk

**Comment by nayoa** [comment]
A fab update has fixed the above issue.
