### ISSUE TITLE
Replace our hand cranked PSP manifests with Terraform resources

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2434]
We currently have PSP applied here: https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/cloud-platform-components/k8s-resources.tf#L46-L66

We should replace these with actual Terraform resources, using:
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/cloud-platform-components/k8s-resources.tf#L46-L6://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/cloud-platform-components/k8s-resources.tf#L46-L66

**Comment by AntonyBishop** [comment]
No longer required. PSP will be deprecated in 1.22. New ticket to look at replacement of PSP with OPA.
