### ISSUE TITLE
EPIC: Pipelines for terraform deployment

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2446]
## What
Create deployment pipelines for all our infrastructure, so that we never run ‘terraform apply’ manually (and maybe a few other non-terraform things too).

We already have a pipeline for teams' k8s namespaces and AWS resources `environments-terraform`, but all the other terraform need pipelines:
* Terraform state S3 bucket creation: 'cloud-platform-terraform-state'
* [terraform-awsaccounts-iam](https://github.com/ministryofjustice/cloud-platform-terraform-awsaccounts-iam) - IAM Users
* [terraform/cloud-platform-account](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform-account) - cloudtrail, velero, buckets, roles
* [terraform/cloud-platform-network](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform-network) - VPC
* [terraform/global-resources](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/global-resources) - AWS account, S3 buckets - kops state, Auth0 context?
* [terraform/cloud-platform](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform) - bastion, kops manifest, DLM
* [terraform/cloud-platform-components](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform-components) - cert manager, external-dns, kiam, prometheus, ingress controllers, opa, velero, Auth0 application (per cluster)
* [terraform/cloud-platform-eks](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform-eks) - used for the manager cluster
* [terraform/cloud-platform-eks-components](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform-eks/components) - manager cluster components (concourse)
* [terraform/cloud-platform-cross-account-IAM](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cross-account-IAM)

We won't automated the **kops** kubernetes cluster, because that would be hard and we plan to be on eks soon.

## Plan of attack
We will start with creating pipelines for these:
* [terraform/cloud-platform](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform) - bastion, kops manifest, DLM
* [terraform/cloud-platform-components](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform-components) - cert manager, external-dns, kiam, prometheus, ingress controllers, opa, velero, Auth0 application (per cluster)

## Motivations
* The key motivation for this is because automated/continuous deployment is a best practice for DevOps, because it means reduces the risk of deploying this infrastructure, and therefore means we are more comfortable changing it. It also helps us avoid config drift, which is another risk and causes toil.
* Disaster recovery - there's a risk things get broken or deleted (cli tools pointed at wrong cluster) and we need to rectify quickly
* It's a step towards multi-cluster, which needs the stack that involves the cluster, at the very least, to have automated deploy.

## Reference
Our discussion: https://docs.google.com/document/d/1_0u2y67yt6CPMa4phm6xqV-qrvV5CULT89NciAcBwqQ/edit#

**Comment by AntonyBishop** [comment]
Decision: We will user Concourse and Go to build pipelines.
