### ISSUE TITLE
Pipeline for 'cloud-platform' terraform for Manager cluster

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2447]
Part of Epic: [Pipelines for terraform deployment](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2446)

Pipeline for this repo: [terraform/cloud-platform](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform) - bastion, kops manifest, DLM

Every git branch needs a ‘tf plan’. When merged it runs ‘tf apply’.

In concourse. Base it on existing divergence pipeline, which already does terraform plan. It uses cli tool, so maybe build on that and add 'tf plan' to the cli?

Deploying live1. (Deploying test clusters is separate to this ticket)

**Comment by AntonyBishop** [comment]
Make sure this work doesn't leak any secrets.

**Comment by jasonBirchall** [comment]
Notes will be collected in this ticket:
TODO

- [ ] Fix concourse main module by removing the provider

**Comment by jasonBirchall** [comment]
Work will be completed under branch `bulk-plan`
https://github.com/ministryofjustice/cloud-platform-cli/compare/bulk-plan#diff-7aa4f817cb0b307408dce751ed9f87dc6b8e5f777e2bc0a0f21473893d0c46c1R35

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/970
