### ISSUE TITLE
Pipeline for 'components' terraform for Manager cluster

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2448]
Part of Epic: [Pipelines for terraform deployment](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2446)

Pipeline for this repo: [terraform/cloud-platform-components](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform-components) - cert manager, external-dns, kiam, prometheus, ingress controllers, opa, velero, Auth0 application (per cluster)

Every git branch needs a ‘tf plan’. When merged it runs ‘tf apply’.

In concourse. Base it on existing divergence pipeline, which already does terraform plan. It uses cli tool, so maybe build on that and add 'tf plan' to the cli?

Deploying live1. (Deploying test clusters is separate to this ticket)

**Comment by AntonyBishop** [comment]
Make sure this work doesn't leak any secrets.

**Comment by jasonBirchall** [comment]
Please see https://github.com/ministryofjustice/cloud-platform/issues/2447 for notes on ticket.
