### ISSUE TITLE
Scale Testing for Cloud Platform

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2449]
**Background**

We currently don't have any scaling (stress) tests for the Cloud Platform. The Cloud Platform continues to acquire tenants and there is a risk to continued delivery of services by the growth of the platform. We are somewhat in the dark about the limits of how far we can push the platform.

We should have some test and some baselines to determine how far we can push the platform and a way of identifying when we need to scale in different ways to continue to support a growing platform. We also need a way of determining impact of certain types of changes that may have an impact on performance.

At our workshop on [Resiliency against AWS service issues](https://docs.google.com/document/d/13iN6ZOoK7R89NtAsccKoum7tOMAbMn3LwmQePn74Vqk/edit#) we re-affirmed this needs doing as a way to get fore-warning of hard AWS limits, so that we don't suddenly hit them.

**Approach**

- Define what are the components are that we need to test (_may be some assumptions here that we would need to test_)
- What tools do we need to support performance testing? (e.g. https://github.com/aquasecurity/kube-bench - for security, https://kubestone.io/en/latest/
- Confirm where we do scaling tests
- Confirm when we do scaling tests
- What observability do we need?
- Conduct tests to determine a baseline

**Definition of done**

The Cloud Platform is able to grow and changes can be made without an impact of performance for tenants of the platform.

**Comment by AntonyBishop** [comment]
And we'd need something to test scaling up too e.g.:

lots of pods
lots of namespaces
hammer pods with traffic
hammer k8s with traffic

**Comment by davidread** [comment]
Suggestion that we try 2x what we have now, not 1000s until it breaks.
Can test in terms of ingresses, pods, nodes, namespaces etc

**Comment by AntonyBishop** [comment]
Agreed to age this out. Nice to have and we may never get to it.
