### ISSUE TITLE
Set up an ingress controller for services needing old TLS versions

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2451]
We have a few applications which have to support deprecated TLS versions because their users are unable to use modern browsers. To support these applications, we have enabled support for old versions of TLS on the default ingress controller. But this means *all* hosted services can now be accessed using deprecated TLS versions. This is an unnecessary security risk.

1. Create a dedicated ingress controller with these TLS versions enabled
2. migrate all such services to that controller
3. Disable deprecated TLS versions on the default ingress controller
4. Update the user guide explaining how to support deprecated TLS versions in your application

This slack thread has additional context: https://mojdt.slack.com/archives/C514ETYJX/p1603207884158900

**Comment by AntonyBishop** [comment]
Need to find out more about what is blocking teams migration away from older TLS.

**Comment by AntonyBishop** [comment]
Stale. Roadmap for this theme needs to be revisited.
