### ISSUE TITLE
Review and Improve Elasticsearch module 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2456]
-  Elasticsearch module has `db_subnet_group` resource which looks not used and unwanted.
- elasticsearch_role_policy has permissions for `AssumeRole` where there is a seperate role for performing Assumerole. Check if that is still needed
- Many resources created in the module has a count to check `var.enabled`. Check if this is required. If there is no requirement for users to create the resource using the module and disable it?

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch/blob/main/README.md

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Aged out
