### ISSUE TITLE
Plan pipeline trigger on every PR in environments repo

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2460]
We have plan pipeline run as a required check to merge the PR in environments repo.

But in the plan pipeline we have set up to only trigger the pipeline if there are changes in Path: "namespaces/live-1.cloud-platform.service.justice.gov.uk"
https://github.com/ministryofjustice/cloud-platform-concourse/blob/main/pipelines/manager/main/environments-terraform.yaml#L29-L30

This is causing trouble when cloud-platform team make changes out side the "namespaces/live-1.cloud-platform.service.justice.gov.uk" repo and plan not getting trigger, where we have to manually disable the plan pipeline check and merge the PR.

To avoid this we can remove that Path: "namespaces/live-1.cloud-platform.service.justice.gov.uk" check and update our script to handle the pipleine run out side the namespaces repo, some thing like giving a message "No namespace changes in this PR"

**Comment by AntonyBishop** [comment]
Done
