### ISSUE TITLE
New automated way ( NS annotation) to monitor CP Namespaces that do not require out of hours alarms

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2461]
We currently have a NS annotation of `cloud-platform-out-of-hours-alert:true` for all system namespaces and a list of alarms (eg pod crashlooping) that automatically pick up the namespace to monitor based on the annotation. 

We have to set up specific alarms to all other namespaces if we want to monitor them (i.e. NS of how-out-of-date-are-we)

This ticket is to create a bunch of standard alerts and appropriate namespace annotations so any new namespace is automatically monitored as long as the annotation is there.

**Comment by AntonyBishop** [comment]
Aged out
