### ISSUE TITLE
Conftest to make sure monitoring NS Annotations are added to all new namespaces 

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2462]
Create a conftest github action to make sure any namespace owned by cloud platform (business-unit:Platforms) also has a monitoring annotation so it is automatically picked up by prometheus alarms. 

There is currently a system namespace annotation for out of hours alarms for all critical namespaces: `cloud-platform-out-of-hours-alarms:true` 

This ticket is to make sure the above annotation has to be added to any new critical namespace.

There is a ticket for a similar annotation for non-critical namespaces owned by the cloud-platform team

**Comment by AntonyBishop** [comment]
Aged out
