### ISSUE TITLE
Enable managing slack webhooks via terraform

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2468]
We currently create slack webhooks for teams' alerts [via clickops](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-slack-webhook-and-amend-alertmanager).

This is bad because a) clickops, and b) webhooks will be deleted if/when the team member who created them leaves, and their slack account is deleted.

We should be managing this via code, as we do with other important integrations like pingdom.

This issue is on the critical path for this, so fixing it might be a good first step:
https://github.com/TimDurward/terraform-provider-slack/issues/17

**Comment by sablumiah** [comment]
https://slack.com/intl/en-gb/help/articles/115005265703-Create-a-bot-for-your-workspace

**Comment by digitalronin** [comment]
I don't think a bot user will work. Bots don't seem to have access to the webhooks API:
https://api.slack.com/bot-users#methods

**Comment by davidread** [comment]
Suggested plan:

1. Automate creation of slack webhooks for teams' alerts 
2. Contribute this to the unofficial slack terraform module
3. Automate process of alerting teams' slack channels when there's a problem

**Comment by digitalronin** [comment]
I've done a bit of digging in to this, and I'm not sure whether or not it's going to be feasible as planned.

It's hard to say - slack changed the way they handle apps. & authentication (possibly multiple times) which means their own documentation is confusing, and a lot of the blog posts and other information on the web is outdated and inaccurate.

I couldn't figure out a programmatic way of creating webhooks (which doesn't mean it can't be done), but there is a way to use a single authentication token to post to any **public** slack channel.

Currently, when you create an app. in the "OAuth & Permissions" section, you can request "bot token scopes" - if you request `channels:read, chat:write, chat:write.public` then the "Bot User OAuth Access Token" can be used to post messages to any public channel:
```
curl -F token=${token} -F channel=${channelid} -F text="Wibble" https://slack.com/api/chat.postMessage
```

**Comment by davidread** [comment]
Another reason - when someone leaves MOJ the Slack integrations they setup disappear

**Comment by AntonyBishop** [comment]
Stale story.
