### ISSUE TITLE
Feature: cloud-platform-cli should be able to redact secrets in terraform outputs.

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2470]
It is very useful for divergence pipelines. At the moment the components divergence for the kops side is hiding the terrafom output because we are afraid of printing in the concourse logs any sensitive information.

Similar to what we did in the environment repo with the logger: https://github.com/ministryofjustice/cloud-platform-environments/blob/main/lib/cp_env/logger.rb

**Comment by AntonyBishop** [comment]
Done
