### ISSUE TITLE
Pipeline/process to ensure terraform modules are up to date

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2473]
When new terraform modules get released, we usually forget to upgrade manager cluster (we mainly focus on live-1).

We need to create a pipeline or process which tells us if modules are in the latest version releases or no.

**Comment by digitalronin** [comment]
There is code in HOODAW that does this for modules in the env. repo. We should be able to tweak and resuse that.

**Comment by AntonyBishop** [comment]
Aged out
