### ISSUE TITLE
Update documentation to set up a maintenance page

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#2474]
The user-guide to [set up a maintenance page](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/maintenance-page.html) is obsolete

It should include both ways to create and run a maintenance page:
[https://github.com/ministryofjustice/cloud-platform-maintenance-page](https://github.com/ministryofjustice/cloud-platform-maintenance-page)
[https://github.com/ministryofjustice/cloud-platform-maintenance-pages](https://github.com/ministryofjustice/cloud-platform-maintenance-pages)

**Comment by AntonyBishop** [comment]
No longer required.
