### ISSUE TITLE
Check all custom Prometheus Rules 

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2475]
Check all our custom prometheus rules to see if they are all fit for purpose and all servicemonitor data is there on the prometheus-infra app. All infra alarms are only set on the prometheus-infra instance.

Also check to see if we are missing monitoring any new components created or changes to components that require a recalibration of the alarm

**Comment by pwyborn** [comment]
Pull request:
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/59/files

**Comment by pwyborn** [comment]
Pull request:
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/60#pullrequestreview-527235259

**Comment by pwyborn** [comment]
Check all our custom prometheus rules to see if they are all fit for purpose and all servicemonitor data is there on the prometheus-infra app. All infra alarms are only set on the prometheus-infra instance. - DONE 

Also check to see if we are missing monitoring any new components created or changes to components that require a recalibration of the alarm:

The following components do not appear to have any prometheus custom alerts:

- cert-manager service - ticket https://github.com/ministryofjustice/cloud-platform/issues/2536

- kiam service - ticket https://github.com/ministryofjustice/cloud-platform/issues/2537

- kuberos service - ticket  https://github.com/ministryofjustice/cloud-platform/issues/2538

- opa service - ticket https://github.com/ministryofjustice/cloud-platform/issues/2539

**Comment by pwyborn** [comment]
pull request https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/984
