### ISSUE TITLE
Upgrade dms module to terraform 0.12 

### ISSUE THREAD

**Issue by pwyborn** [ministryofjustice/cloud-platform#2476]
## Service name
cloud-platform-terraform-dms

## Problem description

 is using Terraform 0.11,
Upgrade to Terraform 0.12

## Contact person

Paul Wyborn

**Comment by pwyborn** [comment]
See:
https://www.terraform.io/upgrade-guides/0-12.html

Example:
https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/commit/dade31d23c9c3464eb1c803b166519636334d656

**Comment by davidread** [comment]
DMS is only currently used by the CP team for occasionally migrating services, so this upgrade can be done when we next need it

**Comment by AntonyBishop** [comment]
Closed. Module archived.

**Comment by davidread** [comment]
We decided to archive this repo. We can unarchive if we use it again.
