### ISSUE TITLE
Automate process to upgrade ingress-controllers with zero downtime

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2477]

**Comment by digitalronin** [comment]
Some progress: This is a script which, given a domain name, namespace and ingress name, will update the external-dns TXT record for that domain such that external-dns will send traffic for the domain to that ingress:

https://gist.github.com/dd8748d0b7517513e572bf65a2dab31b

It still needs a bit of polishing, but that part works.

**Comment by digitalronin** [comment]
I've moved the code to a more "official" repo, and added a README

https://github.com/ministryofjustice/cloud-platform-ingress-migrator

**Comment by poornima-krishnasamy** [comment]
Related to: https://github.com/ministryofjustice/cloud-platform/issues/2398

**Comment by poornima-krishnasamy** [comment]
Script updated for:
https://github.com/ministryofjustice/cloud-platform/issues/2398
https://github.com/ministryofjustice/cloud-platform/issues/2400
https://github.com/ministryofjustice/cloud-platform/issues/2401
