### ISSUE TITLE
Remove the `ingress-nodes` live-1 instance groups

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2488]
While we were going through the ingress-controller problems, we created dedicated node groups for nodes to run the ingress controllers:

```
ingress-nodes-1.17.12-eu-west-2a
ingress-nodes-1.17.12-eu-west-2b
ingress-nodes-1.17.12-eu-west-2c
```

These should no longer be necessary. Remove any code that makes ingress-controllers run on nodes in these groups, and remove the instance groups themselves.

**Comment by AntonyBishop** [comment]
Aged out
