### ISSUE TITLE
Create steps for upgrading aurora RDS db engine version

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2497]
Automatic major version upgrades are not possible using Aurora RDS module. For example upgrading postgres 9.6.9 to 10.7.

Terraform throws an error `InvalidParameterCombination: Cannot upgrade aurora-postgresql from 9.6.9 to 10.7`

Follow the steps for the major version upgrade provided by AWS and create steps to do to apply them using terraform.
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_UpgradeDBInstance.PostgreSQL.html

Create a user guide article explaining the steps that users and Cloud platform team needs to perform. 

Questions:
Check whether the user will need additional permissions for the IAM user created as part of module to change the database parameters using the CLI.

## Definition of done

- [ ] User guide article created
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Aged out
