### ISSUE TITLE
Explore exporting Pingdom metrics to Prometheus

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2500]
At the moment blackbox monitoring solutions like Pingdom only report to tools when there is a problem. We should provide the users with the ability to scrape their Pingdom response times and such, allowing them to both alert and form dashboards in Grafana. The following metrics exporter will allow you to perform the scrape, although there is no Kubernetes deploy option so you may need to create a Helm chart etc.

https://github.com/jusbrasil/pingdom-exporter

**Comment by sablumiah** [comment]
This works and does deliver a subset of metrics we would ideally want. However it would still be useful for users.

We will need to helmify the deployment add either add to a tf module or create its own.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdom-exporter
  namespace: pingdom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingdom-exp
  template:
    metadata:
      labels:
        app: pingdom-exp
    spec:
      containers:
        - name: pingdom-exp
          image: jusbrasil/pingdom-exporter
          ports:
            - containerPort: 9158
          env:
          - name: PINGDOM_API_TOKEN
            value: <apikey>
---
kind: Service
apiVersion: v1
metadata:
  name: pingdom-exp-svc
  namespace: pingdom
  labels:
    app: pingdom-exp
spec:
  ports:
  - port: 9158
    name: http
    targetPort: 9158
  selector:
    app: pingdom-exp

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pingdom-exp-sm
  namespace: pingdom
spec:
  selector:
    matchLabels:
      app: pingdom-exp
  endpoints:
  - port: http
    interval: 15s
