### ISSUE TITLE
Form Builder alert manager for new namespace

### ISSUE THREAD

**Issue by brenetic** [ministryofjustice/cloud-platform#2509]
## Service name

Form Builder

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Should only impact our new saas environment.

## Problem description

We would like to add some monitoring for our formbuilder-saas-test environment.
 
```
namespace: formbuilder-saas-test
team name: Form Builder
application name: Form Builder
channel: #form-builder-alerts-low-severity
kubernetes secret name where the webhook url is stored: fb-low-severity-alerts-slack-webhook in the formbuilder-saas-test namespace
severity level (warning/information): Low Severity
```

## Contact person

@brenetic or @tomas-stefano

**Comment by digitalronin** [comment]
@brenetic I've created this alertmanager route with  severity `form-builder-saas-test`

**Comment by brenetic** [comment]
awesome! thanks 🚀
