### ISSUE TITLE
Alert on external-dns not running

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#252]
## Background
See #230 

We use `kube-prometheus` to deploy monitoring on a cluster. It comes with a number of built-in alerts (they are defined in the charts [here](https://github.com/coreos/prometheus-operator/tree/master/helm) but it's easier to see on the prometheus [rules](https://prometheus.apps.cloud-platform-test-1.k8s.integration.dsd.io/rules) or [alerts](https://prometheus.apps.cloud-platform-test-1.k8s.integration.dsd.io/alerts) pages). We can also [add our own](https://github.com/ministryofjustice/cloud-platform-prometheus/tree/master/custom-alerts)

## Proposed user journey
N/A

## Approach

1. Determine whether the behaviour we want to alert on is covered by the existing rules.
1. If not, create a custom rule.
1. If it's included with `kube-prometheus`, are there multiple alerts that cover the same behaviour? Do we need all of them to alert?
1. Is this a `critical` or `warning` alert?

Write a runbook (see this [example](https://github.com/ministryofjustice/cloud-platform-prometheus/blob/master/runbook/Node-Disk-Space-Low.md)). Keep it short and simple; we want the runbook to point the on-call engineer to the right direction, not to cover all possible causes and paths.

## Questions / Assumptions

N/A

## Definition of done

- [x] There is a alert defined and version controlled in https://github.com/ministryofjustice/cloud-platform-prometheus
- [x] The alert is applied on the `test-1` cluster and version controlled in https://github.com/ministryofjustice/cloud-platform-environments
- [x] There is a runbook for the alert in https://github.com/ministryofjustice/cloud-platform-prometheus

## Reference
N/A

**Comment by nayoa** [comment]
https://github.com/ministryofjustice/cloud-platform-prometheus/pull/22
