### ISSUE TITLE
SPIKE: Gatekeeper

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2527]
Spike into https://github.com/open-policy-agent/gatekeeper

**Comment by davidread** [comment]
Understand, evaluate it and see if it's useful to add it to our stack.

**Comment by AntonyBishop** [comment]
Dependance for secrets management.

_"Vault's use of service account is great - easier than Secrets Manager's multiple controllers - one per namespace. Although Vault is one more layer.

GOOD Only need one instance of the controller. With Vault used with the controller we could use one instance of the controller, and restrict secret access via k8s RBAC. Each namespace has a service-account, used to access controller?. Use OPA to block users adding annotation on their service account that gives them more Vault access. (Need new version of OPA with Gatekeeper)"_

**Comment by davidread** [comment]
@sablumiah suggested Gatekeeper might be bundled with newer OPA anyway, so maybe we can just upgrade?

**Comment by razvan-moj** [comment]
Done in https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/pull/1
