### ISSUE TITLE
Prevent version mismatches for the CLI tool

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2529]
The CLI tool's auto-upgrade feature relies on the version set in the source code matching the tag of the latest release.

It is very easy to make a mistake, and forget to ensure that these values match. This renders the CLI useless for all users, because it goes into an endless auto-update loop.

Add a github action which is triggered whenever a release is created. The action should check that the release tag matches the value in the `version.go` file.

I'm not sure what action can be taken if the values **don't** match. Maybe the release can be withdrawn, or an alert posted to slack or some other action.

> Alternatively, maybe the github action **sets** the value in `version.go`, and then recreates the release with the same tag value?

**Comment by AntonyBishop** [comment]
Stale story
