### ISSUE TITLE
Explore secret management tools

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2531]
e.g. AWS Secrets Manager, AWS Parameter Store, Vault

> If we go for Vault, Maybe wait for "managed Vault on AWS" to be generally available.

Priorities:

* Use ephemeral secrets, rather than long-lived ones that we need to (but probably won't) rotate manually.
* We don't want to have to manage a vault cluster, or other piece of critical infrastructure
* Good audit logging
* Fine-grained RBAC (e.g. members of this team can access any of this collection of secrets, but not these other ones)

**Comment by poornima-krishnasamy** [comment]
Requirement came up from users in #ask-cloud-platform channel https://mojdt.slack.com/archives/C57UPMZLY/p1609338953062300

**Comment by AntonyBishop** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1611056113071200
