### ISSUE TITLE
Parallelise the environments "apply" pipeline

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2535]
The apply pipeline takes almost 90 minutes to run, but since each environment has its own terraform state, we could apply them in parallel.

This would require the "main" pipeline to just create a job per namespace which a different pipeline would consume, letting each concourse worker do the work.

> How would this setup feed back to us that there was a problem in a namespace which we need to fix?

**Comment by AntonyBishop** [comment]
Build on findings from #2514

**Comment by AntonyBishop** [comment]
Stale story
