### ISSUE TITLE
Create custom Prometheus Rule/Alert for OPA (Open Policy Agent) component/service

### ISSUE THREAD

**Issue by pwyborn** [ministryofjustice/cloud-platform#2539]
## Service name

custom Prometheus Rule/Alert for **OPA (Open Policy Agent)** component/service

## Problem description
Create custom Prometheus Rule/Alert for **OPA (Open Policy Agent)** component/service (service is up and running, latency, http error 500s)
To improve prometheus custom alerting
See [Check all custom Prometheus Rules #2475](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2475)

## Contact person

Paul Wyborn

**Comment by AntonyBishop** [comment]
Stale story
