### ISSUE TITLE
Monitor the monitoring tools

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#254]
## Background
See #230 
Depends on #161 

We need to be alerted if prometheus or alertmanager stop working.

## Proposed user journey
N/A

## Approach

Use the prometheus and alertmanager health endpoints (`/-/healthy`) to setup pingdom alerts. 

These endpoints should circumvent the authentication placed in front of prometheus so that pingdom can reach them (speak with @alkar if unsure how to go about this).

Write a runbook (see this [example](https://github.com/ministryofjustice/cloud-platform-prometheus/blob/master/runbook/Node-Disk-Space-Low.md)). Keep it short and simple; we want the runbook to point the on-call engineer to the right direction, not to cover all possible causes and paths.

## Questions / Assumptions

N/A

## Definition of done

- [x] There is a alert defined and version controlled in ???
- [x] There is a runbook for the alert in https://github.com/ministryofjustice/cloud-platform-prometheus

## Reference
N/A

**Comment by sablumiah** [comment]
../-/healthy has been exposed outside of the auth 
https://github.com/ministryofjustice/cloud-platform-environments/pull/40/commits/b032be6f5b66ac48fb33f5a7cc9fb22f8244685e

This will be part of the auth install for prom and am

**Comment by sablumiah** [comment]
Endpoints for test-1 cluster:
https://alertmanager.apps.cloud-platform-test-1.k8s.integration.dsd.io/-/healthy
https://prometheus.apps.cloud-platform-test-1.k8s.integration.dsd.io/-/healthy

**Comment by sablumiah** [comment]
Description of how to add alert added to the main Prometheus readme

https://github.com/ministryofjustice/cloud-platform-prometheus/pull/16/files
