### ISSUE TITLE
Investigate connection timeouts when Ingress Controller pods restarts/terminates

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2540]
More info on slack conversations:

https://mojdt.slack.com/archives/C57UPMZLY/p1604482776372900
https://mojdt.slack.com/archives/C57UPMZLY/p1602057717309100

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Similar issues found in this thread:
https://kubernetes.slack.com/archives/C09QYUH5W/p1566766523377200

https://kubernetes.slack.com/archives/C8SH2GSL9/p1580786112242900

Fix on kube-proxy https://github.com/kubernetes/kubernetes/pull/96371

**Comment by AntonyBishop** [comment]
Related tread in #2389

**Comment by poornima-krishnasamy** [comment]
Some findings: The  "connect ETIMEDOUT" happens for many namespaces whenever the recycling node happens

https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-12-09T07:30:00.000Z',to:now))&_a=(columns:!(_source),filters:!(),index:'89ddb820-d648-11ea-a3d9-7f47a73dbcba',interval:m,query:(language:kuery,query:'%20%22connect%20ETIMEDOUT%22'),sort:!(!('@timestamp',desc)))

**Comment by poornima-krishnasamy** [comment]
Upon further investigation, we found that the "connect ETIMEDOUT" happens whenever a new node joins the cluster. It also doesnot relate to when ingress-controller pods or the relavant application pods gets drained and scheduled to new node. Even if a new node with a different instancegroup(e.g. monitoring-node) get registered to the NLB, the timeout happens.

Raised a ticket with AWS to investigate further.

This seems to be happening for packets where one service reach another service within the cluster via the internet. For example, bookasecuremove.service.justice.gov.uk reaching api.bookasecuremove.service.justice.gov.uk but both services are in different namespaces trying to access each other via internet. Similar behaviour is happening when digital.prison.service.justice.gov.uk reaching once of its sub-urls that are hosted in different namespace within the cluster.

Advised the application team who face the timeout issue to create network policies between the frontend and backend to allow the pods to take internally instead of request from frontend to api reaching the nlb and then coming back to the cluster.

Simulate the issue in test cluster by deploying a pod which would curl other urls(like prometheus, grafana, alertmanager, helloworld) of the cluster continuously and do the recycling of the node. Investigate any packet capturing tools that can be installed in the cluster to check the logs coming in and out of all the nodes.

**Comment by poornima-krishnasamy** [comment]
It looks there are exactly 2 scenarios when the connection timeout happens.

1. When a new node register to NLB 
2. When a node change from healthy to unhealthy. i.e. ingress pods get moved to different node.

From the AWS response(support ticket: 7745825271), this seems like a know issue and a design decision. Hence, reduce the recycling node pipeline run to out of hours.
