### ISSUE TITLE
Upgrade the pingdom provider

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2542]
We're using v1.1.1 of the pingdom provider, but the latest version is 1.1.3, which has [some changes](https://github.com/russellcardullo/terraform-provider-pingdom/releases/tag/v1.1.3)

Upgrade all our code, and all instances of the provider in the environments repo, to use the latest version.

**Comment by poornima-krishnasamy** [comment]
Changes reg API:

removal of  
```
  -var 'pingdom_user=YOUR_USERNAME' \	  
  -var 'pingdom_api_token=YOUR_API_TOKEN'
  -var 'pingdom_password=YOUR_PASSWORD' 
```

Add
-var 'pingdom_api_token=YOUR_API_TOKEN'
