### ISSUE TITLE
Move some global-resources to cloud-platform-account

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2544]
There are things inside `global-resources/` that shouldn't be global:

- SAML: It belongs to an account, our cloud-platform-account.
- DNS: cloud-platform.service.justice.gov.uk hostzone. It belongs to an account cloud-platform-account -> Route53)
- [S3 bucket](https://github.com/mogaal/cloud-platform-infrastructure/blob/main/terraform/global-resources/s3.tf)

**Comment by AntonyBishop** [comment]
Stale story
