### ISSUE TITLE
Reevaluate our terraform code structure

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#2545]
It would be interesting to go over our infrastructure code structure, to spot the the potential limitations.

Could it be improved or be an obstacle to : 
 -  Go multi clusters ?
 -  Go multi accounts ?

What are alternative structures that could benefit the above use-cases ?

Are things like `global-resources` `cloud-platform-account` named properly ?

**Comment by AntonyBishop** [comment]
Duplicate.
