### ISSUE TITLE
Create a default set of alerts with every RDS instance

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2547]
This may be blocked, until we can automatically route alerts to a specific target for teams.

Whenever we create an RDS instance, by default we should also create alerts for common error conditions such as "about to run out of space" (at least until storage autoscaling is available).

**Comment by AntonyBishop** [comment]
Alarms should be "opt in" for users so that they can choose the alarms relevant to them.

**Comment by AntonyBishop** [comment]
Stale story
