### ISSUE TITLE
Use the infra. plan/apply pipeline code for the env. repo plan/apply pipelines

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2548]
We wrote a lot of ruby code for the environments repository, to run `terraform plan` when a PR is raised, and `terraform apply` when it is merged.

We have a similar task in the infrastructure repository, and we are using a different (and better) technique there.

Replace the environments repository pipelines with ones based on the same code as the infrastructure repository pipelines. This will probably require modifying the cloud-platform CLI tool.

**Comment by AntonyBishop** [comment]
Stale story
