### ISSUE TITLE
Use YAML anchors and aliases to reduce code duplication in our pipelines

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2549]
The infrastructure concourse pipelines use almost identical YAML code for the `plan` and `apply` jobs.

See if it is possible and desirable to use YAML anchors and aliases to reduce repetition for this (and other?) pipelines.

This article has more information about YAML anchors and aliases: https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd

**Comment by AntonyBishop** [comment]
Stale story
