### ISSUE TITLE
Deploy prometheus on live-0

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#255]
## Background
See #230 

## Proposed user journey
N/A

## Approach
Start with https://github.com/ministryofjustice/cloud-platform-prometheus/ and deploy the whole suite to `cloud-platform-live-0`.

## Questions / Assumptions

N/A

## Definition of done

- [x] The whole monitoring ecosystem is deployed on `live-0` and version controlled in https://github.com/ministryofjustice/cloud-platform-environments/

## Reference
N/A

**Comment by tatyree** [comment]
Is 'the whole suite' different from cloud-platform-prometheus?

**Comment by alkar** [comment]
That repo is a collection of all resources needed + docs. It is (or should be) the 'whole suite'.

**Comment by jasonBirchall** [comment]
Prometheus and AlertManager deployed on Live0. 
prometheus.apps.cloud-platform-live-0.k8s.integration.dsd.io
alertmanager.apps.cloud-platform-live-0.k8s.integration.dsd.io
