### ISSUE TITLE
Request for a new alertmanager for Court Data Adaptor Dev namespace

### ISSUE THREAD

**Issue by archferns** [ministryofjustice/cloud-platform#2553]
## Service name
LAA Court data adaptor

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Trying out in Dev environment.

## Problem description
We would like to add alertmanager support to our application
```
namespace name: laa-court-data-adaptor-dev
team name: Crime Apps Team
application name: LAA Court Data Adaptor
slack channel: #laa-court-data-adaptor-dev
kubernetes secret name where the webhook url: webhook-secret#slack_webhook
severity level: warning
```

**Comment by pwyborn** [comment]
Pull request https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/990
