### ISSUE TITLE
A way to do non-functional testing (scaling)

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2556]
This ticket to create the framework for this testing. The implementation is quite a large story and will require further breaking down following this ticket.

**Comment by davidread** [comment]
So we can understand the limits of the cluster. So we can forsee when we will hit problems. It might make us change our architecture

e.g. load testing the k8s API

e.g. scale in load balancers, number of namespaces, number of pods, number/size of the worker nodes, number of master nodes. Lots of dependencies between these things.

**Comment by davidread** [comment]
@razvan-moj suggested tools:
* https://github.com/aquasecurity/kube-bench - for security
* https://kubestone.io/en/latest/

And we'd need something to test scaling up too e.g.:
* lots of pods
* lots of namespaces
* hammer pods with traffic
* hammer k8s with traffic

**Comment by AntonyBishop** [comment]
Actions will be picked up in #2449 (Performance Testing)
