### ISSUE TITLE
Multi-cluster router for K8s API calls

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2557]

**Comment by davidread** [comment]
This is a router sitting on top of multiple k8s clusters, proxying API requests to them. This is to shield developers from using the different hostnames and credentials of multiple clusters, that CP want to change under their feet. With this router, service teams using kubectl or setting up CircleCI app deployments can simply authenticate once, against this fixed endpoint, and their requests are forwarded to whichever actual k8s cluster that their namespace is attached to.

How it works:
* receives k8s API calls from service teams' kubectl and their app CI/CD
* authenticates them
* forwards those API calls to whichever cluster is currently 'live' - initially this is just during migration to a fresh cluster ("Stage 0" in the Multi-cluster strategy https://docs.google.com/document/d/1-1dXD0a50MZiQUcm4fIIO1ySVQHA_D2-UMIti-oBVNc/edit# )

Implementation options ideas:
* a mini k8s cluster itself?
* is there something in kubefed we can use?
* Should we write a bit of Go?

During upgrade, CI/CD needs to be paused during the copying of the k8s resources, because otherwise we may lose the writes to k8s when we switch to the new cluster. To do this, how about we make the k8s API read-only to CI/CD user, but not the applications themselves?

Authentication/authorization
* Each cluster should probably have a unique private key. Otherwise an attacker to one cluster could use the same authentication to move to another cluster, and isolation is lost. EKS may not give us control over what private key is used anyway.
* This means the router has to repackage requests for the destination cluster's auth, but keeping the username as whatever was supplied. I think this means it would need the each cluster's private key to sign requests. So this obviously needs careful security consideration.

**Comment by davidread** [comment]
@razvan-moj says https://github.com/jetstack/kube-oidc-proxy looks useful for this!

**Comment by razvan-moj** [comment]
there is a mini-tutorial at https://aws.amazon.com/blogs/opensource/consistent-oidc-authentication-across-multiple-eks-clusters-using-kube-oidc-proxy/ which mentions all the tools needed besides this proxy (Dex and Gangway) to get Github auth

**Comment by AntonyBishop** [comment]
Stale story
