### ISSUE TITLE
Multi-cluster HTTP routing

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2558]
Route HTTP traffic to the correct cluster using a load balancer, rather than DNS.

This is because DNS's TTL makes it hard to do a clean switch-over - devices will use a mixture of IP addresses during the TTL period, and some mobile networks ignore the TTL and cache the IP for a longer period anyway...

If we use a load balancer then we can direct people to a new cluster immediately, do canarying, and switch back quickly in the event of difficulty.

We need to store somewhere a mapping of namespaces to clusters, so that this load balancer can point to the right place, and also the [k8s API router](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2557) can route k8s calls correctly.

**Comment by mtrbls** [comment]
The solution chosen for this ticket was external-dns + Route53 routing policies. 

### External-dns + Route53 routing policies 
It is indeed possible to work with Route53 routing policies straight from a kubernetes ingress, with the right annotations. 

In our case, I used weighted policies: [Example ingress](https://gist.github.com/mtrbls/7ee74ceaeb0375beec21740cdbfe9301)

Using the annotations below, external-dns allows us to point the same domain(created multiple times) to multiple different targets.
If two ingresses were created for the same domain, each with a `aws-weight` and a unique `set-identifier`, AWS would automatically handle the routing according to their respective weight.
```
annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "50"
    external-dns.alpha.kubernetes.io/set-identifier: my-cluster-1
```

Using weighted policies with external-dns/route53 would allow us to route traffic to multiple clusters (scaling) and to gradually shift traffic (blue/green, canary, etc.) from one cluster to another by modifying the weight of the ingress resources.

Another unexplored policy type is the failover one, which is healthcheck and could be used for an active-passive setup.

#### Source : https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md#routing-policies 

### To-do
- More permissions may need to be given to cluster's ext-dns iam role to access the right R53 zone.
- If working on a single cluster, the OPA and Nginx validation webhook need to be disabled/tweak ( multiple imgress with the same host)
- With the current setup, where certificate secrets are only on the cluster that created them, the other ingresses on the other clusters won't be able to use them, and will use the default cluster's cert. **Having a way to share that certificate secret is essential before being able to leverage this solution.**

**Comment by AntonyBishop** [comment]
Follow up story created.
