### ISSUE TITLE
Multi-cluster - Copy k8s resources to new cluster with Velero

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2559]

**Comment by davidread** [comment]
Let's use Velero, because we have it now. And we could potentially improve in future by going to GitOps with a Komposer.

Can we get Velero to restore into a cluster with a different name? A challenge

**Comment by sablumiah** [comment]
Velero can be used as DR for a cluster and/or moving a cluster to a new location keeping the cluster name.
It will not work well for migrating to a new cluster with a new name/domain i.e. from live1 to live2
