### ISSUE TITLE
Smoke tests for a cluster, to be run before it is made live

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2562]

**Comment by davidread** [comment]
This is for [multi-cluster](https://docs.google.com/document/d/1-1dXD0a50MZiQUcm4fIIO1ySVQHA_D2-UMIti-oBVNc/edit#), so that when we create a new cluster and migrate real services onto it, we can run these smoke tests to check it is healthy, before we direct traffic onto it.

**Comment by AntonyBishop** [comment]
Stale story
