### ISSUE TITLE
Re-add the DockerHub credentials to the pipelines for new plan

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2566]
We have moved to a new DockerHub plan to address limits on image pulls.

To start using the new plan we need to replace credential is our pipelines.

We also need to also add this - https://github.com/kubernetes/kops/blob/master/docs/cli/kops_create_secret_dockerconfig.md to kops. So the Kuberneetes cluster start using the credentials to pull images.

**Comment by jasonBirchall** [comment]
Going to use these instructions.
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by jasonBirchall** [comment]
I have now added the bot user credentials as a Kops secret using
