### ISSUE TITLE
access request

### ISSUE THREAD

**Issue by sid-secops** [ministryofjustice/cloud-platform#2567]
## Service name
Access to the AWS accounts managed by CP team, & AWS Master account

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service
this is Access Request. No impact known.

## Problem description
this is Access Request.

## Contact person
slack - sid
email - siddharthan.elangovan@digital.justice.gov.uk

**Comment by AntonyBishop** [comment]
Hi @sid234,

Grateful if you could confirm what access is required for? Many thanks

**Comment by sid234** [comment]
Hi Antony, 
please could I be provided admin access. Thank you

**Comment by AntonyBishop** [comment]
Hi @sid234,

Why do you need access to these accounts?

**Comment by sid234** [comment]
Hi Antony, this is for the analytics work as part of security & privacy team.
cp managed aws accounts - to review the existing alerts setup for sec events mgmt, direct some of the alerts to security slack channel etc
aws master account - review and configure aws org & service control policies etc

**Comment by AntonyBishop** [comment]
Hi @sid234.

With regards to the Master Account please can you contact #ask-modernisation-platform.

With regards to the CP account I'll raise a ticket to prioritise some joint working on this as part of an upcoming sprint.

**Comment by AntonyBishop** [comment]
Or would it just be sufficient for your to review with read-only access and then make recommendations for us to implement? Would that be easier?

**Comment by sid234** [comment]
Hi Antony,
Sure, read-only access is fine. thank you
