### ISSUE TITLE
Dashboard for application metrics

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#257]
## Background
See #230 

## Proposed user journey
N/A

## Approach
TBD
 (HTTP req, resource utilisation)

## Definition of done

- [ ] must compile
- [ ] must pass tests
- [ ] must address all the steps of user journey

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
No user need.
