### ISSUE TITLE
Exporting Pingdom metrics to Prometheus

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2581]
Related to #2500

https://github.com/jusbrasil/pingdom-exporter

Implement pingdom exporter for prometheus to our stack. 
The example deployment will need a helm chart into our helm repo and create/add to a tf module. 
Requires a read-only api key from Pingdom  

We should update any user docs to point users at this if they want this data.

**Comment by pwyborn** [comment]
Please see:
https://mojdt.slack.com/archives/C8QR5FQRX/p1617711898002400
and documentation regarding usage limits https://www.pingdom.com/api/2.1/#limits
I set up the exporter in a test cluster. Unfortunately Pingdom API Usage resourse limits appear to have been reached after only a week  stats every 90 seconds - causing the apply-live1 pipeline to fail. 
We therefore need to investigate another exporter
