### ISSUE TITLE
Deploy loki to live-1

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2584]
## Background

As part of firebreak ticket, the team investigated how loki can be used as the CP logging stack. And decided to use the loki stack (loki + promtail) to collect api-server logs.

Currently the api-server logs are scrapped using fluent-bit and pushed to audit-elasticsearch cluster.

Create a terraform module to install the loki-stack helm chart, a s3 bucket and dynamodb for storage and IAM user to access the same.

Apply loki stack and use promtail to collect api-server logs and push it to s3+ dynamodb

Draft PR: https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/61
Current api-server filters: https://github.com/ministryofjustice/cloud-platform-terraform-logging/blob/main/resources/input-kubernetes.config#L25-L30

## Definition of done
- [ ] terraform module created and readme updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Kops specific work. May no longer be required when migrated to EKS.

**Comment by AntonyBishop** [comment]
Stale story
