### ISSUE TITLE
Investigate error: "MountVolume.SetUp failed for volume \"default-token-\" : failed to sync secret cache: timed out waiting for the condition"

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2589]
This appears to be happening on a number of pods in the cluster. During a recent major incident it was noticed and caused delays in deploy scheduling of over ten minutes.

Investigate the cause of this message.

**Comment by sablumiah** [comment]
The delay containerCreating was found to be caused the a delay is pulling multiple images on a new node, the MountVolume error was a secondary issue caused. 

The following tickets have been created to resolve the delay in pods being created:

https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2612

https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2613
