### ISSUE TITLE
Make changes to alerting for MoJ Single SignOn so that notifications go directly to product team's Slack channel 

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#259]
## Background

Back in December 2017 an agreement was made between Single SignOn team and Cloud Platforms that we would receive alerts for Single SignOn and forward them to that teams group mailbox. This was as a result of SSO not having a full support team. The Cloud Platform team only forwards notifications from #high-priority-alarms and doesn't take any action other than that.

We had a recent alarm come in on Friday and followed the process as agreed. However, we were concerned that as these are not frequent and as the SSSO team has changed were they aware that we were only forwarding the notifications.

We have not visibility of what SSO does and it is hosted in a Heroku account which we do not support.

As we are adding very little value in this process we have suggested to the SSO team that we re-route alerts directly to their team. The PM for SSO (Alex Nash) has agreed that this is a good idea.

We need to contact Alex to identify who from his team can help us with this work.

## Proposed user journey

As a developer I am able to received notification of alerts so that I am aware of potential issues and am able to respond to operational issues as quickly as possible.

## Approach

We will need to work with the Single SignOn team to understand how alerts have been configured. Based on this we will be able to re-route alerts to the appropriate Slack channel.

## Questions / Assumptions

We do not understand how alerts have been set up. We will need to understand this by working with the Single SignOn Team.

Assumption - We can access someone from the Single SignOn team to understand how alerts work and to test that alerts are working. 

## Definition of done

- [x] Confirm how alerts are set up with MoJ Single SignOn team
- [x] Identify and access requirements needed by the team to configure alerts
- [x] Slack channel for notifications confirmed
- [x] Re-route alert notifications from #high-priority-alarms to alternative Slack channel
- [x] Test that alerts are now going to Slack channel
- [ ] sign-off from Single SignOn Team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by kcbotsh** [comment]
@AntonyBishop following on from the email from Jenny, can we kill this ticket?

Hi Antony,

Thanks, but we already have PagerDuty alerts coming through to the #moj-sign-on slack channel. So as long as that continues to work, I don't think there's a need for you to forward the alerts on to us via email as well. We'd only be responding via either route during working hours anyway.

Thanks,
Jenny

**Comment by AntonyBishop** [comment]
Have discussed and we still need to ticket as we need to set up the product team for alerts and remove the alerts that we get.

**Comment by pwyborn** [comment]
Have changed things manually in Pagerduty (not terraform - as it is not a service that we are responsible for)
