### ISSUE TITLE
Explore how to add more tags to cloudwatch exporter

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2591]
**Background:**
This story is a spike into how/if we can add more AWS tags/label inside the cloudwatch exporter.

This story should identify what additional tags we can add and the process for adding them. 

Some users are asking if we can have more AWS tags/label inside the cloudwatch exporter. More information in [this thread](https://mojdt.slack.com/archives/C57UPMZLY/p1606989394301700)

**Comment by AntonyBishop** [comment]
We are going to look into offering users ability to create their own CloudWatch alarms using Terraform. Ticket to be linked.

**Comment by sablumiah** [comment]
After investigation, it does not look like cw-exporter is able to export any additional tags based on the aws resources metrics are exported from. It looks most likely that cw does not allow this as opposed to cw-exporter not being able to do this. 
This information will fed back into the monitoring epic in the possibility is enabling cw monitoring alarm for users.
