### ISSUE TITLE
new alertmanager receiver 

### ISSUE THREAD

**Issue by mattops** [ministryofjustice/cloud-platform#2592]
Please configure a new new alertmanager receiver with label: digital-prison-service-dev

namespace: dps-management-dev
team name: DPS 
application name: digital-prison-service-dev
slack channel: #dps_alerts_non_prod
severity level: warning

**Comment by poornima-krishnasamy** [comment]
@mattops , the alertmanager receiver has been created with severity `dps_alerts_non_prod`
