### ISSUE TITLE
Improve the Grafana documentation for iterating on your Grafana dashboard

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2596]
The userguide isn't explicit enough around iterating on your own dashboard. The blank dashboard is the only dashboard you can change and then export json data from. Either, you should be able to amend/iterate on your own dashboard or the documentation should be explicit for users to use the blank dashboard only!

**Comment by mikehalmamoj** [comment]
This restriction appears to apply mainly to adding new elements to an existing dashboard - I think you can edit existing elements ok.  So it might be worth mentioning that if you can get the panel structure in place up front then that makes life easier.
