### ISSUE TITLE
Decommission Legacy Sentry

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2599]
Decommission Legacy Sentry

**Comment by AntonyBishop** [comment]
Blocked by #1392

**Comment by AntonyBishop** [comment]
No longer blocked. Decommissioning scheduled for w/c 15th Feb

**Comment by davidread** [comment]
Rather than just destroy it, let's make it inaccessible to start with. Suggest a 'brown out' for a day, a few days in advance, to see if anyone shouts.

**Comment by pwyborn** [comment]
09/02/2021 - 13:11 - AWS mojdsd account autoscaling - instance set to standby, staging stack deleted, prod monitoring deleted
Pagerduty - Sentry service disabled
Pingdom - Healthcheck put on "pause"

Will wait a few days before deleting prod stack

**Comment by pwyborn** [comment]
***AWS mojdsd account autoscaling - instance set to standby, staging stack deleted, prod monitoring deleted
Pagerduty - Sentry service disabled
Pingdom - Healthcheck put on "pause"
Will wait a few days before deleting prod stack

Correction - set the instance back to "in service" - as I see it is scheduled for decommission on week commencing: 15/02/2020

**Comment by pwyborn** [comment]
Instance in standby 15/02/2021 17:05

**Comment by pwyborn** [comment]
If no-one shouts by Friday 19th February will finally delete the stack
