### ISSUE TITLE
Move laa-court-data-ui alerts from #laa-court-data-ui-dev to  #laa-get-paid-alerts slack channel

### ISSUE THREAD

**Issue by kmahern** [ministryofjustice/cloud-platform#2604]
## Service name

LAA Court Data UI

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] UAT
- [X] Prod / Production
- [X] Other

## Impact on the service

Alerts will be moved from the #laa-court-data-ui-dev slack channel to the #laa-get-paid-alerts slack channel.

## Problem description

Currently alerts for laa-court-data-ui appear in the #laa-court-data-ui-dev slack channel. We have had a request to move these to the #laa-get-paid-alerts slack channel. I have created a new slack webhook and updated the secret containing this lcdui-secrets#slack_alerts_webhook **(NB currently the updated secret has only been applied to the laa-court-data-ui-dev environment. Please can we use the new value from the secret in this namespace)**

namespace name: laa-court-data-ui-dev
team name: GetPaid
application name: LAA Court Data UI
slack channel: #laa-court-data-ui-dev
kubernetes secret name where the webhook url: lcdui-secrets#slack_alerts_webhook
severity level: warning

## Contact person

Katharine Ahern

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1031
