### ISSUE TITLE
Delete unused Template Deploy Stacks

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2608]
## Service name

Template Deploy

## Service environment

- [ x] Dev / Development
- [ x] Staging
- [ x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

We have a number of stacks of unused resources related to Template Deploy which are costing us money and should be decommissioned.

## Problem description

Resources are no longer required, as confirmed by the Service Teams We can go ahead and decommission the following:

correspondence-tool-staging-monitoring
correspondence-tool-prod-monitoring
correspondence-tool-demo-13f678c5	
correspondence-tool-staging-1da82e0c	
correspondence-tool-prod-7cdc790f
correspondence-tool-dev-152fad81
elasticsearch-monitoring
opsmanual-prod-d70f9032

## Contact person

Tony Bishop

**Comment by pwyborn** [comment]
All above resources deleted
