### ISSUE TITLE
Request AWS access

### ISSUE THREAD

**Issue by axemonkey** [ministryofjustice/cloud-platform#261]
## Service name

Amazon AWS account `mojdsd`

## Impact on the service

I need access to the `mojdsd` account, specifically whatever is used by the Moving People Safely (HMPPS) team so that I can upload files required by the service. 

## Problem description

I don't seem to have any login details for AWS

## Contact person

Clive Murray
clive.murray@digital.justice.gov.uk
@clive on Slack

**Comment by axemonkey** [comment]
Thanks to Sid and Raz, all sorted. 👍

**Comment by sid234** [comment]
thanks for closing the request :-)
