### ISSUE TITLE
Request for new alert route

### ISSUE THREAD

**Issue by jhevans** [ministryofjustice/cloud-platform#2615]
## Service name

Prepare-a-case

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We need a new alert route in Alertmanager to support production deployment.

Raising this ticket as specified in docs [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#overview)

## Problem description

Namespace: court-probation-prod
Team: Probation in Court
application: prepare-a-case
slack channel: probation_in_court_alerts
kubernetes secret name where the webhook url is stored: Secret name is `slack-webhook` structure is:
```apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
type: Opaque
data:
  url: <url-here>
```
severity level: warning

FYI draft PR to add alerts is [here](https://github.com/ministryofjustice/cloud-platform-environments/pull/3971)

## Contact person

John Evans - john.evans@digital.justice.gov.uk

**Comment by digitalronin** [comment]
@jhevans I've added the alert route. It will be ready as soon as this PR is merged:
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1042

The severity is: "prepare-a-case"

**Comment by pwyborn** [comment]
paulwyborn  04/01/2020 2:50 PM
Hi John - re ticket
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2615
Are you all set up re this (I know David did some work on this)?






John Evans:house_with_garden:  04/01/2020 2:52 PM
Hi Paul, yeah that all looks to be working now, thanks!

paulwyborn  2:52 PM
Ok thanks John
