### ISSUE TITLE
Create and use a fork of the pingdom terraform provider

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2616]
We use this for all our pingdom checks:
https://github.com/russellcardullo/terraform-provider-pingdom

It seems like a decent open source project, but it's not officially supported by pingdom or hashicorp, so there are no guarantees about the integrity of the code.

Rather than using the module directly, it would be safer to create our own fork and use that as the source for our terraform code.

We would need to regularly check and merge upstream changes, but overall this is safer than running random code in our pipeline.

**Comment by AntonyBishop** [comment]
No longer required.
