### ISSUE TITLE
Set up dockerhub auth for alertmanager-proxy, prometheus-operator and prometheus-proxy Helm Chart

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2627]
As agreed [here](https://docs.google.com/document/d/1oimRoJmci5v4KRye5TZE_Nb3TvrkKk2uwJWVlJxurkU/edit), we need to implement authentication to Dockerhub in order to avoid API rate limits. This story involves the following actions:

1) Add Dockerhub credentials as Kubernetes Secret. Credentials are going to be passed as terraform variables and they are conditioned to only EKS (this shouldn't happen in kops)
2) Update the Helm Chart to use the Credentials previously created as `imagePullSecrets`. Again this should only happen in EKS side.

**Comment by AntonyBishop** [comment]
Hi @razvan-moj,

Is this issue to be closed as completed?
