### ISSUE TITLE
Pingdom slack integration for Court Case Service

### ISSUE THREAD

**Issue by katie-cawthorne** [ministryofjustice/cloud-platform#2633]
## Service name
Prepare a case

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service
None

## Problem description

Following the cloud platform guide, please can you create a Pingdom integration for sending alerts to a slack channel and supply the integration ids to us? 
I added a new configuration and generated a webhook url through the mojds slack pingdom app but I don't have access to Pingdom so can't access the integration id to then add to pingdom.tf

Team: Probation In Court
Service: Prepare a case
Channels: #probation_in_court_alerts
## Contact person

Katie Cawthorne @Katie Cawthorne

**Comment by jasonBirchall** [comment]
Issue resolved here:
https://github.com/ministryofjustice/cloud-platform-environments/pull/4028#discussion_r555527020
