### ISSUE TITLE
KOPS and EKS Upgrade 1.18

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2636]
We invested the upgrade path in #2577.

We believe this is a fairly straight forward and we are ready to progress with the upgrade.

This story is to implement the upgrade for both KOPS and EKS.

**Comment by jasonBirchall** [comment]
https://docs.google.com/document/d/1HzmTk0IvuW1XsXmVJEsSOzB4jkiMpjwZWlUwIF7P9Gc/edit?usp=sharing

**Comment by jasonBirchall** [comment]
Kops upgrade complete. Still need to do k8s on manager and live. Now in a firebreak sprint so this will go into the blocked column until we return to a normal sprint (2 weeks from now)

**Comment by jasonBirchall** [comment]
kOps, Kubernetes and EKS upgraded to 1.18.x
