### ISSUE TITLE
Investigate costs for alternative monitoring options

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2638]
In previous sprints we looked at Datadog, Honeycomb and Splunk.

We didn't look at the costs in detail.

This story is to compile some information on costs to help with the decision making process.

**Comment by digitalronin** [comment]
Someone from DataDog got in touch with me on LinkedIn. I explained that I was leaving shortly, and said I would pass their details on to the team, in case anyone wanted to talk to them.

> David,
> Ryan Brooks suggested you would be the best person to speak with regarding the Central Cloud Platform at MoJ. I understand this to be a managed Kubernetes cluster, with Terraform-managed AWS resources, and some supporting services around that.
> How can I get 30 minutes with you to talk about the observability of this please?
> Sam Jefferies
> sam.jefferies@datadoghq.com
> 07984 030364

**Comment by AntonyBishop** [comment]
No longer required.
