### ISSUE TITLE
FIREBREAK: Look at Kotary for managing resource quotas

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2646]
The resource management in Kubernetes is confusing at the best of times. This leads to end users just copying and pasting a default resource quota for their namespace. In an attempt to make this easier we should investigate Kotary, which is an operator that also brings a layer of verification to resource management:

Compare Kotary to our current resource management setup.

Source: https://github.com/ca-gip/kotary?utm_sq=glmzi9roiu#what-is-it-
```
It is an operator that brings a layer of verification and policy to the native ResourceQuotas mechanism. It introduced a new resource call a ResourceQuotaClaims that will let users ask to modify the specification of their quota. The verification includes :

There are enough resources (CPU and Memory) on the cluster to allocate the claim which will look at the total amount of resources of the cluster (worker node) and the sum of all the other ResourceQuotas
(Optional) It respects the maximum bound value express as a ratio of the cluster resource, ex: a namespace cannot claim more that a 1/3 of the cluster
(Optional) In order to have some flexibility it is possible to set an over-commit or under-commit ratio to set what is claimable compared to the actual resources. ex: In a development environment you could choose to allow reserving more resources than what is actually usable in reality.
In order to facilitate the adaption of ResourceQuotaClaims it is possible to enforce a default claim for namespaces. The feature will be activated on namespace that contains the label quota=managed.
```

**Comment by vijay-veeranki** [comment]
kotary need a CRD 
kubectl apply -f https://raw.githubusercontent.com/ca-gip/kotary/master/artifacts/crd.yml

And deploy of controller
kubectl apply -f https://raw.githubusercontent.com/ca-gip/kotary/master/artifacts/deployment.yml

Set the configuration with these options:
https://github.com/ca-gip/kotary?utm_sq=glmzi9roiu#options

To update a ResourceQuotas create kind: ResourceQuotaClaim, which will be accepted or rejected after verification.

Implementing ResourceQuota when you already have a running workload can use cli kotaplan, to test various scenarios. 

`+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Namespaces Details                                                                                                                                                                         |
+---------------------+------+----------+-----------------+---------------+---------+-----------------+---------------+-------------+---------------------------+----------------------------+
| NAMESPACE           | PODS | MEM REQ  | CURRENT MEM USE | MEM REQ USAGE | CPU REQ | CURRENT CPU USE | CPU REQ USAGE | FIT DEFAULT | RESPECT MAX ALLOCATION NS | SPEC                       |
+---------------------+------+----------+-----------------+---------------+---------+-----------------+---------------+-------------+---------------------------+----------------------------+
| cert-manager        |    3 | 0B       | 103.2MiB        | 0 %           |       0 |               6 | 0 %           | true        | false                     | CPU : 1000m    MEM: 6GiB   |
| default             |    0 | 0B       | 0B              | 0 %           |       0 |               0 | 0 %           | true        | false                     | CPU : 1000m    MEM: 6GiB   |
| demo-ns             |    0 | 0B       | 0B              | 0 %           |       0 |               0 | 0 %           | true        | false                     | CPU : 1000m    MEM: 6GiB   |
| ingress-controllers |   12 | 900MiB   | 1.396GiB        | 158.7791 %    |    1000 |              32 | 3.2000 %      | false       | false                     | CPU : 1000m    MEM: 6GiB   |
| kube-node-lease     |    0 | 0B       | 0B              | 0 %           |       0 |               0 | 0 %           | true        | false                     | CPU : 1000m    MEM: 6GiB   |
| kube-public         |    0 | 0B       | 0B              | 0 %           |       0 |               0 | 0 %           | true        | false                     | CPU : 1000m    MEM: 6GiB   |
| kube-system         |   16 | 220MiB   | 302.3MiB        | 137.3935 %    |     700 |              44 | 6.2857 %      | true        | false                     | CPU : 1000m    MEM: 6GiB   |
| kuberos             |    2 | 64MiB    | 18.25MiB        | 28.5095 %     |       2 |               2 | 100.0000 %    | true        | false                     | CPU : 1000m    MEM: 6GiB   |
| logging             |    5 | 1.953GiB | 103.1MiB        | 5.1553 %      |      50 |               8 | 16.0000 %     | true        | false                     | CPU : 1000m    MEM: 6GiB   |
| monitoring          |   15 | 1.758GiB | 909.1MiB        | 50.5080 %     |     360 |              46 | 12.7778 %     | true        | false                     | CPU : 1000m    MEM: 6GiB   |
| opa                 |    2 | 200MiB   | 31.5MiB         | 15.7520 %     |      16 |               7 | 43.7500 %     | true        | false                     | CPU : 1000m    MEM: 6GiB   |
| test                |    0 | 0B       | 0B              | 0 %           |       0 |               0 | 0 %           | true        | false                     | CPU : 1000m    MEM: 6GiB   |
| velero              |    1 | 0B       | 19.97MiB        | 0 %           |       0 |               2 | 0 %           | true        | false                     | CPU : 1000m    MEM: 6GiB   |
| vijay-modsec        |    1 | 0B       | 3.395MiB        | 0 %           |       0 |               0 | 0 %           | true        | false                     | CPU : 1000m    MEM: 6GiB   |
+---------------------+------+----------+-----------------+---------------+---------+-----------------+---------------+-------------+---------------------------+----------------------------+
| 14                  |   57 |          |                 |               |         |                 |               |             |                           | CPU : 14000M    MEM: 84GIB |
+---------------------+------+----------+-----------------+---------------+---------+-----------------+---------------+-------------+---------------------------+----------------------------+
+-------------------------------------------------------+
| Summary                                               |
+-------------------------------------------------------+
| Number of nodes               0                       |
| Available resources (real)    CPU : 0m    MEM: 0B     |
| Available resources (commit)  CPU : 0m    MEM: 0B     |
| Max per NS                    CPU : 0m    MEM: 0B     |
+-------------------------------------------------------+
| RESULT                        NOT FEASIBLE            |
|                               MISSING 84GIB OF MEMORY |
|                               MISSING 14000M OF CPU   |
+-------------------------------------------------------+`
