### ISSUE TITLE
FIREBREAK: Use SOPS instead of git-crypt

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2648]
We currently use git-crypt to encrypt secrets in Git repos. Could we use something a little more fit for purpose. Mozilla’s SOPS. SOPS has support for multiple sources for key material, including AWS KMS, GCE, Vault, PGP and more. It provides the ability to use external key material from AWS KMS to encrypt and decrypt secrets but it also supports Shamir’s Secret Sharing and key groups, essentially allowing policies on what keys are required and in what quantity those keys are required to decrypt.

Since SOPS gives us the ability to use a service like AWS KMS we can control who has access to encrypt and decrypt but it also means we can leverage AWS’ instance profiles to allow machines to do what they were design to do best, make our lives easier through automation.

The last feature I want to draw attention to is that once a file is encrypted all the metadata about how it was encrypted is part of the file itself, there is no 3rd party service, database, hidden directory or secondary file needed to know how to decrypt the file.

Source: 
https://itnext.io/managing-kubernetes-secrets-securely-with-gitops-b8174b4f4d30
https://github.com/mozilla/sops

**Comment by pwyborn** [comment]
Findings/Conclusion document:
https://docs.google.com/document/d/1uyJgyzH65hVg8oDtfDSmu1xjNSZuQOeMm0ORRH8H8O8/edit#heading=h.jlljjtjl0uzr

**Comment by AntonyBishop** [comment]
Nice summary @pwyborn
