### ISSUE TITLE
FIREBREAK: Local GitHub action

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2649]
It would be great if we could run a local GitHub action from a Kubernetes pods inside our EKS cluster. The AP team are running local runners but I'm not sure if they host them in K8s. There are a few articles online that suggest this is possible. Use the environments apply pipeline as an example of a local runner.

Source:
https://sanderknape.com/2020/03/self-hosted-github-actions-runner-kubernetes/
https://github.com/ministryofjustice/analytical-platform-iam/pull/244/files

**Comment by AntonyBishop** [comment]
https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#differences-between-github-hosted-and-self-hosted-runners

**Comment by davidread** [comment]
* Means you don't have to give GitHub various secrets - security benefit
* And you avoid paying for GitHub Actions.
* We could look at / reuse what @damacus did with AP. It's effort to setup
* You basically can't build public repos, because of security - could well be an issue

**Comment by davidread** [comment]
Would be good to try AP's experience/work on this, and understand if it would be easy or hard for CP to run our own self-hosted runners on a separate CP 'build' EKS cluster. @neillturner can advise on AP's work.

**Comment by damacus** [comment]
> * Means you don't have to give GitHub various secrets - security benefit
> * And you avoid paying for GitHub Actions.
> * We could look at / reuse what @damacus did with AP. It's effort to setup
> * You basically can't build public repos, because of security - could well be an issue

GitHub have recently brought out [Approve and Run for first time contributors](https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/). This might help with the security somewhat.

**Comment by razvan-moj** [comment]
Conclusions:

Works, can be checked using
https://github.com/ministryofjustice/cloud-platform-github-runner
and
https://hub.docker.com/repository/docker/ministryofjustice/cloud-platform-github-runner

Requires quite a lot of privileges to be useful (privileged PSP, access to docker.sock)

The new "Require approval for first-time contributors" setting in the Github repos is a must to prevent malicious resource consumption via PRs

Seems to be most useful for very secure deployments, not useful for our team as all our code is public and we are happy with the GH-provided runners for now.

**Comment by davidread** [comment]
👍 and hosting a GHA Runner vs hosting Concourse is similar effort, and so we might as well keep things together on Concourse
