### ISSUE TITLE
FIREBREAK: Can we use OPG's Incident Response tool

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2651]
OPG have re-skinned the Monzo Response tool that allows you to deal with incidents in Slack. The Response tool says the following:
Dealing with incidents can be stressful. On top of dealing with the issue at hand, responders are often responsible for handling comms, coordinating the efforts of other engineers, and reporting what happened after the fact. Monzo built Response to help reduce the pressure and cognitive burden on engineers during an incident, and to make it easy to create information rich reports for others to learn from.

We already have a process that allows us to do this, by using this tool we can standardize how we assign roles, such as incident lead. 

Source:
https://github.com/monzo/response
https://github.com/ministryofjustice/opg-incident-response

**Comment by jasonBirchall** [comment]
OPG have also created a status page off the back of the data collected. This can be viewed here: https://incident.opg.service.justice.gov.uk/

**Comment by davidread** [comment]
Of interest - looks like some Monzo folks have commercialized their thing https://twitter.com/sjwhitworth/status/1351904378622521344

**Comment by AntonyBishop** [comment]
No longer required
