### ISSUE TITLE
Enable creating github secrets from namespace resources

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2654]
There is a [terraform provider](https://www.terraform.io/docs/providers/github/r/actions_secret.html) for github action secrets.

e.g. we could define something like this (I think):

```hcl
resource "github_actions_secret" "aws_access_key" {
  repository       = "ministryofjustice/github-collaborators"
  secret_name      = "AWS_ACCESS_KEY_ID"
  plaintext_value  = kubernetes_secret.terraform_user_secret.data.access_key_id
}
```

This would mean people don't have to manually copy/paste kubernetes secrets into github secrets, and wouldn't have to rotate values if we needed to rotate a secret.

related to #2377

**Comment by AntonyBishop** [comment]
Example: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/secret
