### ISSUE TITLE
Dynamodb throttling

### ISSUE THREAD

**Issue by mikehalmamoj** [ministryofjustice/cloud-platform#2664]
## Service name

prison-to-probation-update

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Some reads from dynamodb are being throttled - but we are not being notified.

## Problem description

We received 3 ProvisionedThroughputExceededExceptions from dynamodb:

```log
1/19/2021, 2:26:39.692 AM	com.amazonaws.services.dynamodbv2.model.ProvisionedThroughputExceededException at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse	com.amazonaws.services.dynamodbv2.model.ProvisionedThroughputExceededException
1/19/2021, 2:29:37.547 AM	com.amazonaws.services.dynamodbv2.model.ProvisionedThroughputExceededException at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse	com.amazonaws.services.dynamodbv2.model.ProvisionedThroughputExceededException
1/19/2021, 2:28:05.261 AM	com.amazonaws.services.dynamodbv2.model.ProvisionedThroughputExceededException at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse	com.amazonaws.services.dynamodbv2.model.ProvisionedThroughputExceededException
```
When checking the table with command `aws dynamodb describe-table --table-name cp-cd977838a30dd97b` we found that the throughput had been decreased directly before the exceptions:
```
"ProvisionedThroughput": {
            "NumberOfDecreasesToday": 1, 
            "WriteCapacityUnits": 1, 
            "LastIncreaseDateTime": 1611023751.293, (19 January 2021 02:35:51.293)
            "ReadCapacityUnits": 10, 
            "LastDecreaseDateTime": 1611022937.972  (19 January 2021 02:22:17.972)
        }
```
While investigating the Cloudwatch graphs indicated that we are consistently consuming more throughput than we have provisioned:

![read_capacity](https://user-images.githubusercontent.com/58170926/105146588-12e02200-5af8-11eb-9c80-8dc0a031f28c.png)
<img width="914" alt="throttled_read_requests" src="https://user-images.githubusercontent.com/58170926/105146599-1673a900-5af8-11eb-9df2-109b49f740a6.png">

Which leads to the following questions:
* What happened with the exceptions we received - why did the autoscaling reduce throughput?
* If we are being consistently throttled, why aren't we receiving more exceptions? **UPDATE:  Interestingly we see some 400s for long running queries that have been throttled, but not consistently**
* How are we supposed to know that we are being throttled? - we have no accecss to Cloudwatch and the data is not available in Prometheus.
* _I thought the Cloud Platform dynamodb terraform module provided provisioned throughput with autoscaling set to increase on 50% provision - why didn't the autoscaling kick in?_ **Worked this one out - it's because the default provision is 10 units and we need to increase that**
* Please can you recommend the correct settings for the dynamodb terraform?

## Contact person

Slack: Mike Halma
Email: mike.halma@digital.justice.gov.uk

**Comment by AntonyBishop** [comment]
Hi @mikehalmamoj,

Did this issue get resolved?

**Comment by mikehalmamoj** [comment]
Kind of.  We increased the number of units until the autoscaler stopped maxing out and settled on that value.  So we're hoping that we can just trust the autoscaler to do the right thing...

However the lack of visibility we have in this area means that we don't really know if trusting the autoscaler is the right thing to do.   So it does feel like we need some kind of notification when we are being throttled.

**Comment by AntonyBishop** [comment]
Thanks @mikehalmamoj will discuss with the team and see what we can do.

**Comment by AntonyBishop** [comment]
See if we can add metric to CloudWatch Exporter.

**Comment by razvan-moj** [comment]
hi @mikehalmamoj ! we now have 2 new metrics in Prometheus that will help you watch for such issues: `aws_dynamodb_successful_request_latency` and `aws_dynamodb_throttled_requests`; with these you can predict when autoscaling is needed, and detect when it triggered

**Comment by mikehalmamoj** [comment]
Excellent.  I'll raise a ticket to have a play with those.  Thanks!
