### ISSUE TITLE
Fix logging for FALA and LAALAA

### ISSUE THREAD

**Issue by rowlando** [ministryofjustice/cloud-platform#267]
## Service name

Find A Legal Adviser (FALA)
Legal Aid Agency Legal Advisor API (LAALAA)

I asked @nayoa about application logs for the above applications and her reply was:

> It appears the log agent and monitoring has not been installed for fala or laalaa. usually you can see the logs in cloudwatch and then it streams into elasticsearch.

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Developers cannot view the application logs.

## Contact person

Slack: @nick
Email: nick.rowlands@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
docker and syslog logs for both fala and laalaa are (finally) available in http://elasticsearch.dsd.io/_plugin/kibana, search for "@owner is 563179612266" to see them all
