### ISSUE TITLE
Create a process for acting on security issues that arise

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2670]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Might be of relevance - https://intranet.justice.gov.uk/guidance/security/it-computer-security/ict-security-policy-framework/it-incident-management-policy/

**Comment by AntonyBishop** [comment]
Aged out
