### ISSUE TITLE
Look for workarounds to ensure pipelines don't fail when new cloud-platform-cli is released

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2671]
When someone releases new version of cloud-platform-cli it causes:

- All divergence pipelines to fail
- All cloud-platform-infrastructure to tail (plan/apply)

The reason behind that is the binary force you to be in the latest version.

We need to look for possible solutions to it, ideas:
- Special flag only for the pipelines where it doesn't force you to be in latest
- Maybe a GH action which creates a PR the concourse pipelines with the latest release version.

**Comment by AntonyBishop** [comment]
Not required
