### ISSUE TITLE
Discuss Multicluster phase 2 and rejigging cloud-platform-infrastructure to define multiple clusters

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2672]
They will have same VPC, share a R53 zone, etc

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
@davidread can this issue be closed based on the session last week?

**Comment by AntonyBishop** [comment]
No longer required.
