### ISSUE TITLE
Tidy the 'MoJDSD' AWS account

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2674]
* Audit user accounts manually
* Deactivate IAM users + keys who've not accessed it >6 months
* Ensure there's a policy of MFA being required for login
* Ensure GuardDuty is setup (ops-eng should be able to do this centrally)

This story derives from an item on the risk register:
https://docs.google.com/spreadsheets/d/1jZo-HM76yPLOA5Hudw2BP3EpGYgr8dI2blpPZVS4SRE/edit#gid=0

Discussion: https://mojdt.slack.com/archives/C514ETYJX/p1611594261194800

**Comment by pwyborn** [comment]
- Audit user accounts manually - Have been through users manually.
- - Anyone  not on here https://github.com/orgs/ministryofjustice/people. I have deleted.
- - All accounts where last activity over 180 days have (except any of cloud-platforms, 
- - - Disabled Access keys
- - - Disabled console access

-

**Comment by AntonyBishop** [comment]
Thanks @pwyborn

**Comment by AntonyBishop** [comment]
When it comes to enabling MFA please can someone liaise with me as we need to ensure that I can still access the account. Historically I have has little success with MFS and AWS accounts. Locking me out of the account will be a problem for management of domains and certificates.

**Comment by pwyborn** [comment]
Guardduty is centrally managed:

![Screen Shot 2021-02-08 at 12.11.10.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/e2826ee6-0f84-4e8a-9ce2-0c3af483c7af)

**Comment by AntonyBishop** [comment]
So it's now just a case of turning on the MFA. Please speak to me when doing this to check I can access the account still.

**Comment by pwyborn** [comment]
See (re SSO): 
https://mojdt.slack.com/archives/C514ETYJX/p1612794038198700

**Comment by pwyborn** [comment]
All users are now either mfa - or group/policy "MFA-enforce" attached to their user account.

**Comment by pwyborn** [comment]
Also looked at 'moj-cla-dev'
Deleted users I know have left 
Deleted users where last activity over 1 year ago
All told removed about 20 users

**Comment by pwyborn** [comment]
Also:
moj-manchester-traffic-dev
Users over 365 days removed.
MFA-enforce policy attached to 1 user (others have it)

**Comment by pwyborn** [comment]
Also:
moj-tphmcts
Users over 365 days removed.
MFA-enforce policy attached to 1 user
