### ISSUE TITLE
Remove unnecesary tags for the VPCs

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2676]
Since we are using EKS > 1.15 we don't require [these tags anymore](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/cloud-platform-network/main.tf#L30-L35). More information in https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html

**Comment by AntonyBishop** [comment]
Aged out
