### ISSUE TITLE
Request to automate and document Point in Time RDS Restores

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2679]
## Background

After a conversation with Jav and Ian on slack ([source](https://mojdt.slack.com/archives/C57UPMZLY/p1611579150082900)) it was mentioned that restoring an RDS instance to a Point in Time would be a really nice feature to have. 

PIT is a fairly new option in RDS and is outlined in this [blog](https://mojdt.slack.com/archives/C57UPMZLY/p1611579150082900). As an addition the AWS [Terraform resource ](https://github.com/hashicorp/terraform-provider-aws/issues/5286#issuecomment-726256717) now allows you to restore to a point in time. It should be noted however, I haven't tried this myself so this is partly conjecture.

## Proposed user journey

As a Developer I want to be able to utilise the AWS RDS Point in Time restores, ideally using the current workflow via the environments pipeline.

## Approach

Recommended approach is to spin up a test RDS instance (in a test namespace) and attempt to restore to a point in time using the AWS Terraform resource.

## Which part of the user docs does this impact

A new user document should be created, outlining the process of restoring in as few steps as possible.

## Questions / Assumptions

- That all RDS instances have the Point in Time restore option.
- The AWS Terraform resource is easy to implement in a declarative fashion.

## Definition of done

- [ ] users are able to restore to a point in time with little or no cp team intervention
- [ ] user docs are created outlining steps
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Aged out
