### ISSUE TITLE
Upgrade Terraform Providers

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2697]
We'll be upgrading the TF version for the platform. We should also ensure we have upgrade the providers we are using.

**Comment by pwyborn** [comment]
https://docs.google.com/spreadsheets/d/1yxhPOleWU5Vmk1AvPGExabfTx4EQvohEPZfedOKXcj4/edit#gid=0

MODULES
AWS-PROVIDER
ag -l iam-assumable-role-with-oidc
cloud-platform-terraform-certmanager/irsa.tf
cloud-platform-terraform-prometheus/cloudwatch-exporter.tf
cloud-platform-terraform-prometheus/ecr-exporter.tf
cloud-platform-terraform-monitoring/ecr-exporter.tf
cloud-platform-terraform-monitoring/thanos.tf
cloud-platform-terraform-prometheus/thanos.tf
cloud-platform-terraform-monitoring/cloudwatch-exporter.tf
cloud-platform-terraform-external-dns/irsa.tf

ag -l iam-user
cloud-platform-terraform-awsaccounts-iam/main.tf

ag -l iam-policies
cloud-platform-terraform-awsaccounts-iam/main.tf

ag -l iam-assumable-role
cloud-platform-terraform-certmanager/irsa.tf
cloud-platform-terraform-prometheus/cloudwatch-exporter.tf
cloud-platform-terraform-prometheus/ecr-exporter.tf
cloud-platform-terraform-prometheus/thanos.tf
cloud-platform-terraform-monitoring/ecr-exporter.tf
cloud-platform-terraform-monitoring/thanos.tf
cloud-platform-terraform-monitoring/cloudwatch-exporter.tf
cloud-platform-terraform-external-dns/irsa.tf

ag -l iam-account
cloud-platform-terraform-awsaccounts-iam/main.tf

Branches (not to merge yet):
https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/update-terraform-providers-cross-account-IAM
https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/update-terraform-providers-cloud-platform-components
https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/update-terraform-providers-cloud-platform-eks
https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/update-terraform-providers-cloud-platform
https://github.com/ministryofjustice/cloud-platform-terraform-auth0/tree/update-terraform-providers-module-auth0

**Comment by pwyborn** [comment]
Think we need to revisit this post upgrade to t13/t14  to see where we are at with pinned provider versions:

My findings here re where things are pinned (highlighted) (may or maybe useful @razvan-moj @mogaal) :

- [Terraform Provider Info](https://docs.google.com/spreadsheets/d/1yxhPOleWU5Vmk1AvPGExabfTx4EQvohEPZfedOKXcj4/edit#gid=0)

The main ones that are pinned are here (showing versions behind, together with breaking changes). Maybe @AntonyBishop these should be broken down into separate tickets as there are breaking changes?:

- [Provider AWS](https://docs.google.com/spreadsheets/d/1yxhPOleWU5Vmk1AvPGExabfTx4EQvohEPZfedOKXcj4/edit#gid=1028768494)
- [Provider Helm](https://docs.google.com/spreadsheets/d/1yxhPOleWU5Vmk1AvPGExabfTx4EQvohEPZfedOKXcj4/edit#gid=774913595)
- [Provider Kubernetes](https://docs.google.com/spreadsheets/d/1yxhPOleWU5Vmk1AvPGExabfTx4EQvohEPZfedOKXcj4/edit#gid=1384354319)
- [Provider Auth0](https://docs.google.com/spreadsheets/d/1yxhPOleWU5Vmk1AvPGExabfTx4EQvohEPZfedOKXcj4/edit#gid=408880329)

Main infrastructure changes (ignore modules referencing my local setup), JUST FOR REFERENCE - NOT TO BE MERGED:
[cross-account-IAM](https://github.com/ministryofjustice/cloud-platform-infrastructure/compare/update-terraform-providers-cross-account-IAM) ** except helm up to 2.0.3
[cloud-platform-eks](https://github.com/ministryofjustice/cloud-platform-infrastructure/compare/update-terraform-providers-cloud-platform-eks) ** except helm up to 2.0.3
[cloud-platform](https://github.com/ministryofjustice/cloud-platform-infrastructure/compare/update-terraform-providers-cloud-platform)
[cloud-platform-components](https://github.com/ministryofjustice/cloud-platform-infrastructure/compare/update-terraform-providers-cloud-platform-components)  ** except helm up to 2.0.3

**Comment by pwyborn** [comment]
Information supplied.
Terraform providers updated as part of the terraform upgrade to Terraform 14.7
