### ISSUE TITLE
Purchase new Domain name for the GTL Live Video Link Booking Service

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#270]
## Service name

GTL Video Link Booking System. (New video service)

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

New domain required for service to go live. Can't go live without new domain name.

## Problem description

We would like to purchase the following domain name "PVLBookingSystem.service.justice.gov.uk" for the new GTL Video Link Booking System that is currently being developed. This new system, although currently planned to be Piloted, is expected to be rolled out to multiple other prisons and courts across the country in the next two weeks.

Tony Bishop has DNS Server name details.
 
## Contact person

For questions or confirmation that work is completed please contact Shivir Sharma (shivir.sharma@digital.justice.gov.uk) or @Shivir Sharma

**Comment by kcbotsh** [comment]
Spoke to @SteveMarshall this task is not currently in our scope will for Cloud Platform will forward onto Trent
