### ISSUE TITLE
Create environments pipelines for the manager cluster

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#2700]
For cloud-platform reports, the web application is deployed to live-1 via the
environments repository, but the cron jobs which populate the app. with data
run in the concourse-main namespace on the manager cluster (because there are
already admin-level secrets in there, and this way we don't have to duplicate
those).

To support this, it would be nice if we could create resources on the manager
cluster via the environments repo, in the same way as we do for service teams.

Set up the same environments pipelines for the manager cluster as we have for
live-1.

**Comment by AntonyBishop** [comment]
Done
