### ISSUE TITLE
New Custom Alert

### ISSUE THREAD

**Issue by reallydontask** [ministryofjustice/cloud-platform#2704]
## Service name

DSO External Monitoring

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

This is a new custom alert to allow external (from studio-hosting's POV) monitoring of endpoints in studio-hosting.

## Problem description

Could I have a custom alert created please?

I'm trying to follow the process outlined [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts)

namespace name: dso-monitoring-prod 
team name: dso
application name: offender assessment
slack channel: #hmpps-assessments-dev
kubernetes secret name where the webhook url is stored: 
assessment-slack-webhook 
severity level (warning/information): warning

## Contact person

Agoney Garcia Deniz

**Comment by pwyborn** [comment]
09/02/2021 17:22
Hi Agoney - regarding your ticket “New Custom Alert#2704” - “DSO External Monitoring” - The config should be there now (severity = ‘dso’). Let me know if there are any problems please?
