### ISSUE TITLE
SPIKE: driftctl

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2709]
Look into driftctl for infrastructure as code drift - https://github.com/cloudskiff/driftctl

Whilst the divergence pipelines look for AWS resources that have been changed or deleted, it does not flag resources that are created, because they are not under the control of terraform.

Questions to answer:
* Does driftctl successfully check for manually created resources?
* Should we use driftctl in our divergence pipeline? Would that be instead of or in addition to the existing 'terraform plan' functionality?

**Comment by vijay-veeranki** [comment]
Tried running driftctl scan using local state and also the state in s3

local:

```
driftctl scan --from tfstate://terraform.tfstate
WARNING: terraform.tfstate was generated using Terraform 0.0.0 which is currently not supported by driftctl. Please read documentation at https://docs.driftctl.com/limitations
Scanned states (1)
Throttling: urces
```

Using state in s3:

`AWS_PROFILE=moj-cp driftctl scan --from tfstate+s3://cloud-platform-terraform-state/aws-accounts/cloud-platform-aws/vpc/eks/**/*.tfstate --filter "Type=='aws_s3_bucket'"
Scanned states (12)
Throttling: urces`


Another limitation is :
https://docs.driftctl.com/0.11.0/limitations#aws-regions--credentials-limits

The user needs to use the same AWS region and credentials for both the scanned infrastructure and the S3 bucket where the Terraform state is stored

error as we have the state in eu-west-1

`BucketRegionError: incorrect region, the bucket is not in 'eu-west-2' region at endpoint ''`

We cannot use this with replacing our divergence pipeline as this don't support Kubernetes resources.

I considered it to get the report and update it in our reports, but it is not working as expecting and throwing throttling error.
https://reports.cloud-platform.service.justice.gov.uk/orphaned_resources



Result: Not useful for us now, we may consider this later if this supports kubernetes resources as well.
