### ISSUE TITLE
Fix legacy Jenkins jobs

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#271]
## Service name

Jenkins, LaaLaa, PostCodeInfo

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

LaaLaa, PostCodeInfo updates cannot be deployed

## Problem description

Python dependencies for https://ci.service.dsd.io/view/LaaLaa/job/DEPLOY-laalaa/ and https://ci.service.dsd.io/view/PostcodeInfo/job/DEPLOY-postcodeinfo/ (may be others) require the Debian Jessie openssl_1.0.1 while the current Jenkins Stretch image is openssl_1.1

Two possible solution proposals (to be discussed):
1. Change the jobs to remove the versioning requirement
2. Create a Jessie Jenkins slave and tag the jobs to run on it

## Contact person

Lukasz

**Comment by lukaszraczylo** [comment]
There's no need for spinning slave jenkins.
I have added following to the deploy-laalaa job and it made it run just fine:

`SOEXT_CRYPTO=so.2`

https://ci.service.dsd.io/view/LaaLaa/job/DEPLOY-laalaa/84/console

**Comment by lukaszraczylo** [comment]
I presume we can close this issue and paste the export line within the Jenkins jobs when the problem reappears?
