### ISSUE TITLE
Request for hmpps-user-preferences alert route

### ISSUE THREAD

**Issue by jhevans** [ministryofjustice/cloud-platform#2712]
## Service name

hmpps-user-preferences

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We need a new alert route in Alertmanager to support production deployment.

## Problem description

Namespace: hmpps-user-preferences-prod
Team: Probation in Court
application: hmpps-user-preferences
slack channel: probation_in_court_alerts
severity: hmpps-user-preferences (if available, our config is [here](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-user-preferences-prod/09-prometheus-k8s.yaml) and can be changed if needed)

Note that we could use the route `prepare-a-case` for this as it alerts to the same channel -  I've raised it as a separate request as `hmpps-user-preferences` will be a shared service so creating a new route seemed appropriate. Please advise if you'd prefer we use the existing route.

## Contact person

@ministryofjustice/probation-in-court 
John Evans - john.evans@digital.justice.gov.uk

**Comment by pwyborn** [comment]
[new-slack-alert-hmpps-user-preferences #1085](https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1085)

**Comment by pwyborn** [comment]
15/02/2021
paulwyborn  4:56 PM
Hi John - re your request for hmpps-user-preferences alert route#2712 - config should be there now (or will be shortly) - severity “hmpps-user-preferences”

**Comment by pwyborn** [comment]
10:42 16/02/2021:
thanks Paul, that’s working great now. Cheers!
