### ISSUE TITLE
SPIKE AWS Managed Ingress (for Kops)

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2715]

**Comment by sablumiah** [comment]
https://github.com/kubernetes-sigs/aws-load-balancer-controller
https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/

This does work after reconfiguring IRSA and using KIAM instead on the kOps cluster.
Path based routing worked. 

Did not have time to fully test the CertManger feature within the helm chart and auto assigning certificates. Auto Discover certs via ingress host will require a bit of config to make work as it does not our the box as the Helm chart is primarily designed for EKS.
