### ISSUE TITLE
SPIKE kube-oidc-proxy

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2716]
In Multicluster Phase 2 we want to migrate clusters and not annoy all our service teams' by them having to create new kubectl config for it. Can we use kube-oidc-proxy to provide a layer of indirection, so that it is seamless for them?

https://github.com/jetstack/kube-oidc-proxy

**Comment by razvan-moj** [comment]
waiting for AWS feedback on https://auth0.com/docs/tokens/create-namespaced-custom-claims (ask Ross)

**Comment by AntonyBishop** [comment]
No longer required. Wrong solution.
