### ISSUE TITLE
Allow sonar cloud to analyse PUI code repository (Not hosted on Cloud Platform)

### ISSUE THREAD

**Issue by forceedge01** [ministryofjustice/cloud-platform#2724]
## Service name

SonarQube (https://sonarqube.cloud-platform.service.justice.gov.uk/)

## Service environment

- [ ] Dev / Development

## Impact on the service

Allow statistics to be generated for the code in the repository and visualise test coverage. The project is not hosted on the cloud, but the analysis is done on the repository level or on the CI level which can be achieved with the SonarQube instance hosted in the cloud. If this is not accessible, we'll have to resort to an alternative measure which will come in competition of this service and variance in tooling which can lead to more confusion which is not ideal.

## Problem description

At present we don't have enough metrics to start unit testing and refactoring efforts with efficiency. Whilst we can start somewhere it would be good to have a sense of direction and a constant visual reminder of where we stand with this. Whilst we may solve this specific problem, the actual problem is access. Should people who own the repositories also be able to configure SonarQube for themselves? Should this be made easier to promote adoption?

Repository: https://github.com/ministryofjustice/laa-ccms-pui

## Contact person

Slack: @test-automation-guild-support

**Comment by AntonyBishop** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1613650631058700

**Comment by forceedge01** [comment]
Hello @AntonyBishop , it would really help to know what kind of timeline we're looking at here for this to be actioned? We have got a ticket on our board which represents the work here so would be good for our own updates when discussing that ticket.

**Comment by forceedge01** [comment]
@AntonyBishop any news?

**Comment by AntonyBishop** [comment]
Hi @forceedge01. Story is part of current sprint.

**Comment by AntonyBishop** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1614071616011400
