### ISSUE TITLE
Firebreak idea: Run an Autopilot provisioned GKE cluster

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2734]
Overview
---

Autopilot is a new mode of operation in Google Kubernetes Engine (GKE) that is designed to reduce the operational cost of managing clusters, optimize your clusters for production, and yield higher workload availability. The mode of operation refers to the level of flexibility, responsibility, and control that you have over your cluster. In addition to the benefits of a fully managed control plane and node automations, GKE offers two modes of operation:

Autopilot: GKE provisions and manages the cluster's underlying infrastructure, including nodes and node pools, giving you an optimized cluster with a hands-off experience.
Standard: You manage the cluster's underlying infrastructure, giving you node configuration flexibility.

Source: https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview

Intention of this ticket
---

- Spin up a cluster using Autopilot
- Create a number of namespaces and pods using something like Kboom.
- Install key components we use like Cert-manager and prometheus.

Definition of done
---

- Report back to the team:
  - how easy was the installation
  - how did it compare to our current implementations, pros and cons.
  - what's missing?

**Comment by AntonyBishop** [comment]
Still funds in the GKE account.

**Comment by davidread** [comment]
Still no money in our GCP account to try this

**Comment by pwyborn** [comment]
Move ticket to "blocked" section.

see:
[Ignore the Google Cloud Tickets Paul. We need to sort the pay plans before we can do any valid work on those]
(https://mojdt.slack.com/archives/C514ETYJX/p1625505093096000)

**Comment by razvan-moj** [comment]
https://www.hashicorp.com/blog/terraform-adds-support-for-gke-autopilot might make it even easier

**Comment by jaskaransarkaria** [comment]
@AntonyBishop @jakemulley Do we have any money to try this out?
