### ISSUE TITLE
Authorisation to Scan images from AWS CLI and return results

### ISSUE THREAD

**Issue by digitalali-moj** [ministryofjustice/cloud-platform#2742]
## Service name

track-a-query, contact-moj, parliamentary-questions and peoplefinder

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other
- [x] (all namespaces)

## Impact on the service

Security issues present on images - needs remediation and automatic alerts - so need to have this in place

I would like to be able to run this:
aws ecr describe-image-scan-findings --region eu-west-2 --repository-name correspondence/track-a-query-ecr --image-id imageDigest=sha256:anything

and get the results. Also would like to be able to do it by image tag (as the python interface does in this script https://github.com/ministryofjustice/correspondence_tool_staff/pull/1484/files#diff-73832c984bc19ff75ac07864ecec2102c811ec7c9d22cff1de17f62d866184c8).

Working on a spike to keep us posted about any issues in our ECR images - so we can resolve them sooner.

## Contact person

Javid Ali - Staff Tools & Services Slack - @Jav  (he/him)

**Comment by razvan-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials/releases/tag/4.5
