### ISSUE TITLE
End to end check to ensure EKS is still an option

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2750]
OIDC has been resolved for adoption of EKS.

Before we get underway with migration we need to do a quick shakedown to ensure that there are no hidden issues that now appear as a result of authentication being resolved.

**Comment by poornima-krishnasamy** [comment]
https://docs.google.com/document/d/1zYa1gS6vrBXZ0A3AhNUeU5YzTiyQBThMLvtp3DVi41k/edit?usp=sharing.
