### ISSUE TITLE
Can we adopt managed Prometheus?

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2751]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Revisit in 6 months

**Comment by razvan-moj** [comment]
demo in https://github.com/ministryofjustice/cloud-platform-terraform-amp, looks promising
