### ISSUE TITLE
Enable Performance monitoring in Sentry

### ISSUE THREAD

**Issue by Nimphal** [ministryofjustice/cloud-platform#2754]
## Service name

Book a Secure Move 

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [x] Other (Pre-production)

## Impact on the service

We regularly see timeout errors coming in from Sentry and have spent considerable time trying to tally these with application and ingress logs in Kibana without much success. We are looking for something that can provide us with APM capability.

Enabling the Performance functionality forSentry will allow all teams that already use it for error monitoring to also use it to track down performance issues without needing to integrate with a new service or significantly change their configurations.

## Problem description

The Book a Secure Move service contains applications written in Rails, Node and Springboot. We would like to be able to monitor the performance of each of these applications, and ideally would like to be able to do it in the same place. HMPPS uses Azure AppInsights for most of its applications, however, the Rails gem for this is no longer supported by Microsoft so as a team we are reluctant to rely on it.

All of our applications are integrated with Sentry for error monitoring, and Sentry have released a new SDK for Rails which allows us to enable tracing. This functionality is also available for the other languages.

We have enabled this for our Node applications, and will shortly do the same for the Rails one. However, it looks like there's a need for a change of plan to let us actually make use of this https://sentry.io/organizations/ministryofjustice/performance/

## Contact person

Nev Aleksandrova, nevelina.aleksandrova@digital.justice.gov.uk, slack: Nev

**Comment by jasonBirchall** [comment]
@AntonyBishop just to make you aware for future discussion.

**Comment by AntonyBishop** [comment]
Dependant on Annual Sentry renewal.

**Comment by AntonyBishop** [comment]
Starting renewal process with Sentry. Will discuss incorporating features with new licence.

**Comment by AntonyBishop** [comment]
Confirmed new licence costs. Going to be organising a trial of features in May.

**Comment by AntonyBishop** [comment]
@Nimphal Am setting a trial for new Sentry.io performance features. Would you be interested in taking part?

**Comment by Nimphal** [comment]
We would! Our node application is already set up so it should "just work" when enabled.

**Comment by AntonyBishop** [comment]
Trail starts w/c 17th May

**Comment by AntonyBishop** [comment]
Trial started. Ends 19th June.

**Comment by AntonyBishop** [comment]
Moving to blocked (in lieu of an "on-hold" pipeline.

Trial is underway. Awaiting feedback from trial and estimations around transaction volumes.

**Comment by AntonyBishop** [comment]
Progressing with renewal with inclusion of Performance Monitoring. Renewal process now underway.
