### ISSUE TITLE
Explore symlink for terraform files 

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2757]
In order to avoid version drifts from terraform files (especially `components.tf`) we need to explore if symlinks are something that can work for us. If not explore other tools in place.

See for example: components for [kops ephemeral test](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/proposal-aws-structure/terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-components/components.tf) and [components for kops live-1](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/proposal-aws-structure/terraform/cloud-platform-components/components.tf).

**Comment by poornima-krishnasamy** [comment]
The symlinks has to be created from the folder it sits in. 

For example, for the cloud-platform-infrastructre repo, if the target folder is `terraform/cloud-platform/variables.tf` and you want to create a symlink inside `terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform`, then 

`cd terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform`
and do 
`ln -s ../../../cloud-platform/variables.tf`
  
After you created the symlink, push the changes to the github.
