### ISSUE TITLE
Create a runbook to bootstrap an AWS Accounts.

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2758]
When we bootstrap a new AWS Account we need resources to store out terraform state (S3 bucket & DynamoDB table). This process should be done manually using AWS CLI and has to be documented in a Runbook.

The runbook should include: 
 - Using AWS CLI to create S3 bucket (with encryption on and this other checks)
- Using AWS CLI to create DynamoDB table used for state locking.
- An example of a simple terraform apply using the remote state created.

**Comment by leoncarrington** [comment]
Reconsidering after current sprint ends (EKS work) for relative priority.
