### ISSUE TITLE
Explore how to unify module definitions for our KOPS and EKS clusters

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2763]
At the moment we have different definitions for [Kops components](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cloud-platform-components) and [EKS components](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/cloud-platform-eks/components). With terraform 0.13 upgrade we are able to use module conditionals which might allow us to unify these two folders into one (via variables). 

This ticket consists of identifying the changes required to keep just one definition for both places.

**Comment by AntonyBishop** [comment]
No longer required
