### ISSUE TITLE
Upgrade Cert Manager

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2771]
## Background

Our Cert Manager should be upgraded. 

We will upgrade to [v1.1.1](https://github.com/jetstack/cert-manager/releases/tag/v1.1.1)

## Approach

- Plan
- Test
- Implement
- Create Runbook

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- Verify that v1.1.1 is the right upgrade
- What is the upgrade path?
- Are there any breaking changes?
- Does work require downtime?

## Definition of done

- [ ] Confirm plan for upgrade
- [ ] Upgrade Cert Manager to v1.1.1

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
This is wanted in relation to the terraform upgrade work.

**Comment by poornima-krishnasamy** [comment]
The version suitable for upgrade is v1.2.0
