### ISSUE TITLE
metrics issue

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2778]
See: https://github.com/ministryofjustice/cloud-platform-sensitive/issues/1

**Comment by sablumiah** [comment]
Update added to the ticket

**Comment by davidread** [comment]
Have deprioritized this - will come back to it after the EKS work

**Comment by HappyLeaks** [comment]
#Security are chasing for an update on this incident please.  When is this scheduled for completion?

**Comment by davidread** [comment]
@John-Happy-Gilmour prioritization discussion continued in slack https://mojdt.slack.com/archives/C57UPMZLY/p1625562804009300?thread_ts=1615294405.185800&cid=C57UPMZLY

**Comment by vijay-veeranki** [comment]
metrics end point is removed from default backend and applied now to all clusters
