### ISSUE TITLE
FIREBREAK: AWS Fault Injection Simulator

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2781]
## Background

AWS Chaos Engineering - https://aws.amazon.com/blogs/aws/aws-fault-injection-simulator-use-controlled-experiments-to-boost-resilience/

## Questions / Assumptions

TBC

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by pwyborn** [comment]
Not actually sure that this is of any use to us at the moment https://aws.amazon.com/fis/. Maybe revisit in a years time.
I was able to get terminating of nodes/instances etc to work. 
However the CPU stress test work that I was more interested in was not compatible with either eks nodes nor our existing live-1 nodes (tested on test clusters). 
The nodes required installation of an SSM  (AWS System Manager) agent, that are not currently installed and would be subject of a ticket in it's own right. https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/install-ssm-agent-on-amazon-eks-worker-nodes-by-using-kubernetes-daemonset.html,   https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent-status-and-restart.html.
