### ISSUE TITLE
Request for a new alert route in Alertmanager

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#2786]
* namespace name: `c100-application-production`
* team name: HMCTS PET - Product Enhancement Team
* application name: Apply to court about child arrangements (C100)
* slack channel: #hmcts-sustain-alerts
* kubernetes secret name where the webhook url is stored: `kubectl get secrets -n c100-application-production -o yaml | grep prometheus_slack_webhook`
* severity level (warning/information): warning

Thank you.

**Comment by zheileman** [comment]
@AntonyBishop hello, this ticket was closed, but I don't have the new severity level? Was it sent by slack/email? Thanks!

**Comment by jasonBirchall** [comment]
Severity for this is: `c100-application`. I'll drop @zheileman a line in slack.
