### ISSUE TITLE
Update guide to clarify position on supported TLS

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2794]
Currently the user guide says - https://user-guide.cloud-platform.service.justice.gov.uk/documentation/concepts/migrate-from-td.html#ssl:

`TLS version: By default, Kubernetes supports a minimum TLS version of 1.2 If you have users with browsers that do not support TLS 1.2, they will not be able to access your service.`

This isn't strictly true.

We should update the guide accordingly.

**Comment by AntonyBishop** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1603205916133700

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/701
