### ISSUE TITLE
Create route53 stuff for hmpps-tier

### ISSUE THREAD

**Issue by nickmcmahon01** [ministryofjustice/cloud-platform#2797]
## Service name
hmpps-tier
https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-tier-prod

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

We would like a Route53 Entry please :)

## Problem description

```If your zone is for a subdomain of service.justice.gov.uk (eg.: https://myapp.service.justice.gov.uk), the Cloud Platform team can help you set it up; please create a support ticket.```

We have set this up, but apparently there is a manual step for this to be set up properly
https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/hmpps-tier-prod/resources/route53.tf

## Contact person

Nick McMahon (slack)

**Comment by razvan-moj** [comment]
done
```
$ dig NS +short hmpps-tier.hmpps.service.justice.gov.uk
ns-1404.awsdns-47.org.
ns-1665.awsdns-16.co.uk.
ns-260.awsdns-32.com.
ns-556.awsdns-05.net.
```
