### ISSUE TITLE
Create NS Records for HMPPS EMS Short Zone in DSD Account

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/cloud-platform#2798]
## Service name

HMPPS EMS AC

## Service environment

- [x] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

None

## Problem description

Create NS records for zone (em.service.justice.gov.uk) in DSD account. Relates to https://github.com/ministryofjustice/cloud-platform-environments/pull/4532

## Contact person

Jacob Woffenden - jacob.woffenden@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
The domain needs changing.
Slack thread for more details: https://mojdt.slack.com/archives/C57UPMZLY/p1616686215130500?thread_ts=1616668891.112400&cid=C57UPMZLY

**Comment by jacobwoffenden** [comment]
Closing as no longer requuired
