### ISSUE TITLE
FIREBREAK: Investigate Fleet for multi-clusters

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2803]
## Background

In a multi-cluster environment, it would be great if users had a way to Deploy to one endpoint and have it deployed to multiple clusters. Looking around it appears Fleet might be able to serve this purpose.
source: https://github.com/rancher/fleet

_Fleet is GitOps at scale. Fleet is designed to manage up to a million clusters. It's also lightweight enough that it works great for a single cluster too, but it really shines when you get to a large scale. By large scale we mean either a lot of clusters, a lot of deployments, or a lot of teams in a single organization._

_Fleet can manage deployments from git of raw Kubernetes YAML, Helm charts, or Kustomize or any combination of the three. Regardless of the source all resources are dynamically turned into Helm charts and Helm is used as the engine to deploy everything in the cluster. This gives a high degree of control, consistency, and auditability. Fleet focuses not only on the ability to scale, but to give one a high degree of control and visibility to exactly what is installed on the cluster._

## Questions / Assumptions

- That we can deploy this in a kOps or EKS cluster. 
- That this would solve the deployment question of multi-cluster.
- Is this easy to install and maintain?

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by jasonBirchall** [comment]
Ran out of time to investigate this. Returning back to firebreak column.

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1oatMxzg8ICQ2vbnk4h77-KZQfKV5xNCoytYdohDXCvs/edit
