### ISSUE TITLE
FIREBREAK: Investigate Nova to replace Helm Whatup 

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2804]
## Background

We currently use Helm whatup to manually cross reference all of our Helm charts against known repositories. We should use less code to do this and more config. Look into whether we can plug and play Nova in a test cluster. Is it usable.
Source: https://github.com/FairwindsOps/nova

_Nova scans your cluster for installed Helm charts, then cross-checks them against all known Helm repositories. If it finds an updated version of the chart you're using, or notices your current version is deprecated, it will let you know._

## Questions / Assumptions

- That Nova is fully open source.
- That we can just plug Nova into our current setup.
- Does Nova replace Helm Whatup?
- Can we grab the data output from Nova and insert it into Hodor? https://reports.cloud-platform.service.justice.gov.uk/helm_whatup

## Definition of done

- [x] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by poornima-krishnasamy** [comment]
Nova is a simple binary that needs to be installed. It serve the same purpose of helm whatup. 

Nova can be configured to output directly to json which can be pushed to the HOODAW report. 
Pros:
- Doesnot need the repo added. It fetches the repo details remotely
- Simple command to fetch all namespaces
- Checks directly using helmClient and have better check than helm whatup. Current helm whatup doesnot check fluent-bit, eventrouter, external-dns charts correctly

Cons:
- Doesnot have a namespace filter so the output input all namespaces that uses helm
- Doesnot display only the repos that needs checking. Hence all helm installs are listed including users charts

Spike code changes here: https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/tree/nova-spike
