### ISSUE TITLE
FIREBREAK: Add fault injection into our clusters with PowerfulSeal

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2809]
## Background

We've been interested in chaos engineering for a while. We should look at fault injection in a Kubernetes clusters. Add PowerfulSeal to a test cluster and run through some of their Hello World scenarios.
Source: https://github.com/powerfulseal/powerfulseal?utm_sq=gnnbrplloc
_PowerfulSeal injects failure into your Kubernetes clusters, so that you can detect problems as early as possible. It allows for writing scenarios describing complete chaos experiments._

## Questions / Assumptions

- How can this help the Cloud Platform team?
- How easy is it to install and maintain?

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by pwyborn** [comment]
Summary:
Not sure that it offers too much of use to us.
Scenarios are fairly limited.
Not keen on failure messages.
Documentation is complete.
Maybe one to keep our eye on for the future (still fairly new)?
