### ISSUE TITLE
Kiam installed on test-1

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#281]
## Background

```
$ kubectl --context cloud-platform-live-0.k8s.integration.dsd.io run --rm -it --image=alpine dk
If you don't see a command prompt, try pressing enter.
/ # apk add --no-cache ca-certificates curl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/5) Installing ca-certificates (20171114-r3)
(2/5) Installing nghttp2-libs (1.32.0-r0)
(3/5) Installing libssh2 (1.8.0-r3)
(4/5) Installing libcurl (7.61.0-r0)
(5/5) Installing curl (7.61.0-r0)
Executing busybox-1.28.4-r0.trigger
Executing ca-certificates-20171114-r3.trigger
OK: 6 MiB in 18 packages
/ # curl http://169.254.169.254/latest/meta-data/
ami-id
ami-launch-index
ami-manifest-path
block-device-mapping/
hostname
iam/
instance-action
instance-id
instance-type
local-hostname
local-ipv4
mac
metrics/
network/
placement/
profile
public-keys/
reservation-id
security-groups
services// #
```

## Proposed user journey

https://github.com/jtblin/kube2iam
https://github.com/uswitch/kiam
https://github.com/freach/kubernetes-security-best-practice

## Definition of done

- [ ] must compile
- [ ] must pass tests
- [ ] must address all the steps of user journey

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ollieanwyll** [comment]
`The kube2iam daemon and iptables rule (see below) need to run before all other pods that would require access to AWS resources.`
I assume this means that all the pods on a cluster will need to be brought down before implementation.

**Comment by ollieanwyll** [comment]
After evaluating both repos, it seems https://github.com/uswitch/kiam is the best one.
I've got to say that the task on properly implementing kiam looks to be quite a task and in my opinion, more than a 3.
Also, I think this is a task that should be worked on by more than one person.

**Comment by ollieanwyll** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/tree/add-kiam

**Comment by kcbotsh** [comment]
@alkar @ollieanwyll is this ready to be closed?
