### ISSUE TITLE
FIREBREAK: Investigate Karpenter node scaling

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2810]
## Background

We've looked at node lifecycle management software and there were various issues with the metric driven nature. Karpenter is a specification driven autoscaler. Spinup a test cluster and look at Karpenter.
Source: https://github.com/awslabs/karpenter?utm_sq=gnmnxia5kh
_Karpenter is a node lifecycle management solution. It observes incoming pods and launches the right instances for the situation. Instance selection decisions are intent based and driven by the specification of incoming pods, including resource requests and scheduling constraints._

## Questions / Assumptions

- This can be used in EKS and or kOps.
- Test how this works and ensure you understand how the autoscaling is triggered.

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by razvan-moj** [comment]
Project is quite early days 
 - only autoscaling supported is the one we already have with cluster-autoscaler (trigger on pod creation resource insufficient event)
 - Helm chart is very simple, everything hardcoded, no IAM SA
 - Roadmap (https://github.com/awslabs/karpenter/blob/main/docs/ROADMAP.md) says we should revisit around Q3, 2021
