### ISSUE TITLE
CVE Patching

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2812]
https://github.com/ministryofjustice/cloud-platform-sensitive/issues/2

**Comment by jasonBirchall** [comment]
We weren't affected directly by the CVE in question. I did however notice we were lagging behind the latest versions on a number of gems. To rectify this I performed a bundle update, which subsequently patched kramdown anyway (via techdocs). https://github.com/ministryofjustice/cloud-platform-user-guide/pull/639
