### ISSUE TITLE
Use SSO for AWS auth

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2813]
## Background

For our team to authenticate in AWS Console etc, we're keen to move from SAML to AWS SSO.

The plan/reasoning is 75% done in an ADR: https://github.com/ministryofjustice/cloud-platform/pull/2811. That needs the detail working through, such as:

* 2FA for command-line - is this possible? is it useful?
* how convenient it is that the creds are temporary?
* a readonly role to be able to do 'terraform plan' (12h timeout, instead of 1h?)
* address Jake's useful comments

Let's update the ADR and get the team to agree it (or not).

Assuming we're all good, this ticket includes implementation:

* configuration of the role(s) e.g. `readonly`
* get team to adopt this method of logging into AWS Console and for running `terraform plan`
* delete SAML auth

## Definition of done

- [ ] ADR accepted
- [ ] readonly role works
- [ ] team is using SSO, not SAML
- [ ] SAML Auth0 rule deleted
- [ ] Any other SAML setup bits deleted

**Comment by AntonyBishop** [comment]
Covered under another story.
