### ISSUE TITLE
Create CLI for 'cloud-platform starter-pack create'

### ISSUE THREAD

**Issue by leoncarrington** [ministryofjustice/cloud-platform#2815]
Users of Cloud Platform will be able to generate deployment manifest for a hello world app using `cloud platform starter-pack create`

This will create a folder 'starter-pack' in the current working directory and generate the deployment.yaml, service.yaml and ingress.yaml file. 

The input for the command should have a namespace 

The ingress should be generated based on the current cluster config and the namespace given.

## Definition of done

CLI created and new release made

Update the user guide: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/helloworld-app-deploy.html#step-2-deploy-the-quot-hello-world-quot-application

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
@poornima-krishnasamy grateful if you could add some details. Many thanks.
