### ISSUE TITLE
New format for Github tokens

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2816]
**Background**
To improve security Github have recently introduced a [new format for access tokens](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/).

We have a number of couple of tokens (currently owned by Tony) that we should amend in line with the new format.

- `CP_GITHUB_ACTIONS_SECRETS_WRITER`
- `ADMIN_GITHUB_TOKEN`

The new format would mean new keys with be something along the lines of:

- `ghp_CP_GITHUB_ACTIONS_SECRETS_WRITER`
- `ghp_ADMIN_GITHUB_TOKEN`

**Approach**
- Identify where tokens are in use
- Confirm if we will rename or regenerate new tokens
- Identify when changes will need to be made (**it's possible that some of these are in use on Ops Engineering so will need to work with that team to assess full impact before changes made)** 
- make changes
- Test everything works as expected

Definition of Done
- [ ] New tokens created
- [ ] We understand impact of changes
- [ ] We can safely replace tokens

**Comment by AntonyBishop** [comment]
Email from Auth0 reminding us of GitHub's changes. We should fix this.

**Comment by davidread** [comment]
Related PR from @vijay-veeranki: https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1455

**Comment by vijay-veeranki** [comment]
All these tokens were re-created in the new format.

cloud-platform-review-docs
cloud-platform-infrastructure-plan-pipeline
operations-engineering-project-automation
cloud-platform-runbooks PUBLISHING_GIT_TOKEN
cloud-platform-user-guide PUBLISHING_GIT_TOKEN
https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk
concourse-pr-plan-pipeline
authorized-keys-provider

Updated them, where ever it is used.

**Comment by vijay-veeranki** [comment]
Revoked all user tokens for github Auth0.
All users of this application will be forced back through the authorization flow before they can use your application again.
