### ISSUE TITLE
Update "Add variables to CircleCI" guidance

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2820]
Feedback/Problem on page: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/using-circleci-for-continuous-deployment.html#retrieving-the-service-account-credentials

**Add variables to CircleCI**

> It could be clarified that a ‘Context’ should be an environment, so you have one context for dev, one for staging and one for prod. This allows you to reuse environment variables such as K8S_NAMESPACE and use the contexts to switch between them.
> 
> Also the screenshot is out of date, the current screenshot that is being used looks like the Environment Variables page each project has on circle ci, in this situation you have to use K8S_UAT_NAMESPACE/K8S_STAGING_NAMESPACE etc to differentiate between these values.

**Definition of Done**

- [ ] Guidance reviewed and updated

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/650
