### ISSUE TITLE
Bump concourse helm chart version to latest

### ISSUE THREAD

**Issue by pwyborn** [ministryofjustice/cloud-platform#2826]
## Service name

Concourse helm chart 

## Problem description

Helm Chart version is out of date (13.0.0). Update to the latest (15.0,2).

See https://reports.cloud-platform.service.justice.gov.uk/helm_whatup

**Note v15 introduces a change that breaks older Concourse so basically to roll back you probably need to use Velero and restore a backup: https://github.com/concourse/concourse-chart/blob/master/CHANGELOG.md#v1500

See https://mojdt.slack.com/archives/C514ETYJX/p1618234188106300?thread_ts=1618232476.103500&cid=C514ETYJX

## Contact person

Paul Wyborn

**Comment by AntonyBishop** [comment]
Aged out.
