### ISSUE TITLE
FIREBREAK: pre-commit and terraform-docs

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2832]
## Background

Most of the time, when we do terraform modules changes we forget to update the README and documentation. There are some tools that help us to deal with these situations: terraform-docs combined with the pre-commit framework.

Explore how we can benefit from these tools and build a use case with one of our terraform modules

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by AntonyBishop** [comment]
No longer required.

**Comment by davidread** [comment]
We have an GH action to do this in 60% of repos. This is better than doing it client side.
