### ISSUE TITLE
Provision AWS Elasticsearch clusters

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#284]
## Background

We want to pipe the logs from kubernetes nodes, namespaces and pods to elasticsearch. For our initial setup we want *one* elasticsearch cluster for our `test-1` cluster and *one* elasticsearch cluster for our `live-0` cluster. 

This story is to create each of those clusters using terraform. 

------

*As a* development team member
*I need* to search logs for my application(s) in a central place
*So that* I can debug issues with my service

We are going to use the Elasticsearch, Fluentd, Kibana stack for our logging infrastructure. This is largely familiar to us from the existing setup and from the spike that @ollieanwyll, @pwyborn and Serj did earlier in the year. 

## Approach

If possible we want to use terraform to provision the elasticsearch clusters. We have to decide whether to make this part of the cluster creation process (I'm thinking: probably yes, an optional part of that process). 

## Questions / Assumptions

We want to provision *super small clusters* to begin with. Let's start with e.g. 2 node clusters, in 2 separate availability zones with 8GB RAM, 1TB storage. 

* We are using AWS managed elasticsearch

## Definition of done

- [ ] AWS elasticsearch provisioned for test 
- [ ] AWS elasticsearch provisioned for live
- [ ] Provisioning is done through terraform
- [ ] Instructions on how to do it are part of the cluster setup documentation

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
Done in https://github.com/ministryofjustice/cloud-platform-aws-meta-configuration/pull/3
