### ISSUE TITLE
pushgateway and network policy

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2842]
## Background

pushgateway requires to have a networkpolicy rule allowing traffic from the monitoring namespace. Check https://mojdt.slack.com/archives/C57UPMZLY/p1618837250149800 as a reference

## Approach

Document in the user-guide the steps to add the network policy 

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/prometheus.html#pushgateway

## Definition of done

- [ ] user docs have been updated

**Comment by AntonyBishop** [comment]
Aged-Out
