### ISSUE TITLE
Fix cert-manager issue in EKS

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2843]
## Background

The default ingress-controller certificate has issue renewing. The cert-manager logs throw error
```
Failed to determine Route 53 hosted zone ID: WebIdentityErr: failed fetching WebIdentity token:
``` 
More details on the slack channel. https://mojdt.slack.com/archives/C8QR5FQRX/p1618917846002200

- Investigate the permission denied issue. 
- Could this issue happen in live-1 kops cluster or is it specific to IRSA and EKS. 
- Check why adding securityContext as mentioned here: https://github.com/jetstack/cert-manager/issues/2147 fixes it

## Definition of done

- [ ] cert-manager module and READme updated if fix has code changes
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Add security context with fsgroup for eks
    
    This is to modify the cert-manager deployment with the correct
    filesystem permissions, so the serviceaccount token can be read.
    
    Information related to it:
    https://github.com/cert-manager/website/pull/456/
