### ISSUE TITLE
Prevent users from creating certificates with dnsNames under *.apps.live-1

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2844]
## Background

When users of Cloud Platform create certificates with dnsnames XXXX.apps.live-1.cloud-platform.service.justice.gov.uk, this sometimes throw an error when creating certs with name is >64 chars. Also, these certificates if left not validating, we get an lower-priority-alarms about "Certificate expiring soon"

Moreover, users donot need to create such certificates as the default wildcard certificate covers this.

More details in the slack thread: https://mojdt.slack.com/archives/C514ETYJX/p1619001273321300

Find a way to prevent users from creating one.
Could OPA policy help here?

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Aged-Out
