### ISSUE TITLE
Opting your Website out of Google's FLoC Network

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2845]
An interesting topic regarding Googles new FloC network has been discussed on the Architecture channel: 
https://mojdt.slack.com/archives/C3DMEE4N9/p1619095856037700

Question raised is do we by default block this for the CP directly on nginx? 
Is there a way to allow users to do this by individual teams/application/ingress?

More info : https://www.eff.org/deeplinks/2021/03/google-testing-its-controversial-new-ad-targeting-tech-millions-browsers-heres
Nginx change info: https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network

**Comment by AntonyBishop** [comment]
Aged Out
