### ISSUE TITLE
Improving RDS Snapshot guidance

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2846]
Following a recent incident we have had some feedback on some improvements to our [RDS Snapshot guidance](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/rds-snapshots.html#rds-snapshots).

Here is the [tread](https://mojdt.slack.com/archives/C57UPMZLY/p1619127617221400) from #ask-cloud-platform.

It's especially important in a incident situation that users can rely on our guidance to help them quickly resolve an issue.

In this instance the `AWS_DEFAULT_REGION` was not exported to an env var. We should review our documentation to ensure that that this is mush clearer. Also see thread for other improvements/clarifications that can be made.

**Comment by leoncarrington** [comment]
EKS priority work at the moment, moved to backlog for reconsideration

**Comment by AntonyBishop** [comment]
Aged out
