### ISSUE TITLE
Test eks-privileged PSP

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2851]
When creating EKS cluster, it adds a PSP eks.privileged by default. This is a privileged PSP and needs to be removed before using the Cluster for Production

Investigate 
- which pods uses this PSP
- how this affect those pods if the PSP is removed?

**Comment by davidread** [comment]
Is this now fixed by: https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1172 ?

**Comment by jasonBirchall** [comment]
Resolved by the following:
- created a unique psp for aws-node that enables net_raw
- amended the create-cluster script to contain method for removing eks.priv and installing our own psps.
