### ISSUE TITLE
Test how the current opa policies work in EKS

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2852]
We have [these](https://github.com/ministryofjustice/cloud-platform-terraform-opa/tree/main/resources/policies) OPA policies in EKS cluster.

Do a end to end testing of each policy and check they work as expected

**Comment by jasonBirchall** [comment]
Confirmed all 14 rego tests work in an EKS test cluster. Closing ticket.
