### ISSUE TITLE
Check and add integration tests needed for EKS

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2853]
There are 76 integration tests running for live-1 whereas there are only 39 tests are running for EKS.

Compare the tests, check if any tests specific to EKS needs to added or existing test modified

**Comment by jasonBirchall** [comment]
Tests in live-1 only:
kiam
externaldns
namespace annotations
tzcronjob
logging
authorised keys
servicemonitor

Tests in kops only:
daemonset
master_nodes
ingress_spec
modsec_spec
servicemonitor

**Comment by jasonBirchall** [comment]
Tests needed in EKS and live:
ingress
modsec
servicemonitor
daemonset
namespace_annotations
externaldns
authorised keys

**Comment by jasonBirchall** [comment]
Written up tickets that are now in the backlog. Closing this issue.
