### ISSUE TITLE
Create “live” EKS cluster and add OIDC authentication for webops

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2854]

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/compare/create-live?expand=1

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/commit/cbbc40f8cb31cdd3171542042ef38ccdab755684
