### ISSUE TITLE
Migrate HOODAW app to new “live” cluster

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2857]
depends on: https://github.com/ministryofjustice/cloud-platform/issues/2854 

Migrate the reports app: https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we to the "live" eks cluster.

**Comment by razvan-moj** [comment]
needs more clarification on how we handle 2 ingresses

**Comment by jasonBirchall** [comment]
There are two parts to the reports/hodor page the frontend with displays the data in a db in a nice format, and the middleware component that performs the collection. For clarification, this issue will focus on moving the frontend migration.

**Comment by jasonBirchall** [comment]
Closing issue. Migration complete.
