### ISSUE TITLE
Update Elasticsearch module for EKS

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2858]
Elasticsearch module uses aws_es_proxy in order to access the Elasticsearch and kibana. An IAM role with assumeRole permissions is annotated to aws_es_proxy pod to work with Kiam. 

https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch

Update the module so the es_proxy works with IRSA.

**Comment by razvan-moj** [comment]
blocked until we have a working pipeline
