### ISSUE TITLE
Users can access Kibana

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#286]
## Background

We want users of the cloud platform to be able to access Kibana so that they can see the logs for their applications. AWS Elasticsearch does not provide super easy ways for users to authenticate. We need to put a proxy in front of Kibana so that users can authenticate with Github and then get access to their logs. 

The approach will be similar to that taken for prometheus (#161). 

------

*As a* development team member
*I need* to search logs for my application(s) in a central place
*So that* I can debug issues with my service

We are going to use the Elasticsearch, Fluentd, Kibana stack for our logging infrastructure. This is largely familiar to us from the existing setup and from the spike that Ollie, Paul and Serj did earlier in the year. 

## Proposed user journey

* User clicks on a link to access Kibana
* They go through a github auth flow
* User can see the Kibana UI and complete searches

## Approach

Our current assumption is that we need to put a proxy in front of Kibana so that users can authenticate with github and then be redirected to the kibana UI. @jasonBirchall did this for prometheus so probably best to reuse as much of his work as possible.

## Questions / Assumptions

* We can put a proxy in front of AWS Kibana
* We want users to login with their github credentials
* We are *NOT* doing any namespacing on kibana -- users will be able to see everything for now

## Definition of done

- [x] A user can log in with their github credential to Kibana
- [x] This has been tested with someone outside of cloud platform team
- [ ] The setup for this is documented in the cluster creation guide (a section on logging that includes all about getting the log stuff set up)
- [x] Any applications that we have to run or configuration we need to put in is defined in code

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by kerin** [comment]
I noticed yesterday that Elasticsearch 6 now supports [SAML authentication](https://www.elastic.co/guide/en/x-pack/current/saml-realm.html), which might be an option.

**Comment by kalbir** [comment]
@kerin nice, that's one to investigate.

**Comment by jasonBirchall** [comment]
It has been decided, we will put the configuration in the cloud-platform-environments repo.

**Comment by jasonBirchall** [comment]
test1 cluster:
https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/cloud-platform-test-1.k8s.integration.dsd.io/monitoring/kibana-proxy.yaml

**Comment by jasonBirchall** [comment]
Access restricted to the MoJ level. All users with MoJ GH access can access Kibana.

**Comment by jasonBirchall** [comment]
Live:
https://kibana.apps.cloud-platform-live-0.k8s.integration.dsd.io/_plugin/kibana

Test:
https://kibana.apps.cloud-platform-test-1.k8s.integration.dsd.io/_plugin/kibana
