### ISSUE TITLE
Logging of EKS control plane needs enabling

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2860]
Control plane audit logs can be enabled and can be viewed through cloudwatch console. 

Configure through teraform to setup streaming audit logs into Elasticsearch cluster.

More details in the doc: https://docs.google.com/document/d/1zYa1gS6vrBXZ0A3AhNUeU5YzTiyQBThMLvtp3DVi41k/edit?usp=sharing

**Comment by razvan-moj** [comment]
- check retention

**Comment by davidread** [comment]
> Configure through teraform to setup streaming audit logs into Elasticsearch cluster.

We agreed today we can just leave the logs in Cloudwatch for now - no need for ES cluster. Our team can access them there for debug, and security can do audit there, (unless we are notified otherwise - MLAP is a possibility).

Retention probably needs to be 13 months.

**Comment by razvan-moj** [comment]
this can be - and I think must be - terraformed so that it is switched on if we get a DR scenario (cluster rebuild)

if terraformed, we must also make sure audit logs are not wiped/recreated in the process (this would now happen now with Kops+ES, but will with EKS+CW)

**Comment by davidread** [comment]
Agreed, we TF everything. Good thinking about working to avoid wiping CW logs on rebuilt.

**Comment by jasonBirchall** [comment]
Logging enabled and sent to CloudWatch Logs. I question the need to retain logs for 13 months. It seems a little high. The default retention period is 3 months and is easily changable, would that suffice?

**Comment by jasonBirchall** [comment]
Had a chat with the team about this. It's part of security guidance so will change it posthaste.
