### ISSUE TITLE
Implement security.txt

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2862]
## Background

Whilst on support, an interesting conversation point was raised: Should we be following the best practice outlined in the below article. The article states "Domains where the Ministry of Justice (MoJ) is primarily responsible for cyber security must redirect the /.well-known/security.txt location to the central security.txt file." (MoJ security guidance). 

If this is the case then it should be managed centrally via the main ingress controllers.

MoJ security guidance: https://ministryofjustice.github.io/security-guidance/implement-security-txt/#implementing-securitytxt
Conversation: https://mojdt.slack.com/archives/C57UPMZLY/p1620144197363200

## Proposed user journey

Users should not have to worry about implementing this, if it's required by security. Cloud Platform should manage this setting globally.

## Approach

- Check this requirement. This is the first we're hearing about it and we consulted the security team upon implementation of the Cloud Platform.
- Check whether we can manage this globally, somewhere like the ingress-controller module would be ideal. 
- Test, test, test.
- Implement in live clusters.

## Which part of the user docs does this impact

New documentation or an ADR will have to be created.

## Questions / Assumptions

- This is even required by security.
- This can be centrally managed by Cloud Platform.

## Definition of done

- [ ] Security have confirmed either way
- [ ] This has been tested in a live like environment
- [ ] This has been reviewed by a team member
- [ ] A unit test is written 
- [ ] Implemented in live
- [ ] An ADR or appropriate has been written.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
MoJ security guidance: https://ministryofjustice.github.io/security-guidance/implement-security-txt/#implementing-securitytxt
Conversation: https://mojdt.slack.com/archives/C57UPMZLY/p1620144197363200

**Comment by AntonyBishop** [comment]
Replaced by #3192
