### ISSUE TITLE
Set up log rotation and backup on Elasticsearch

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#287]
## Background

We want to keep logs live in Elasticsearch for 30 days in the first instance. If development teams ask for more we'll change the settings. 

We also want Elasticsearch to back up nightly at a quiet time, e.g. 2am. We want to keep the backups for a while, say 1 year to begin with. 

------

*As a* development team member
*I need* to search logs for my application(s) in a central place
*So that* I can debug issues with my service

We are going to use the Elasticsearch, Fluentd, Kibana stack for our logging infrastructure. This is largely familiar to us from the existing setup and from the spike that @ollieanwyll, @pwyborn and Serj did earlier in the year. 

## Approach

I imagine this is configuration of Elasticsearch that we can do with terraform. 

## Questions / Assumptions

* 30 days of live data in elasticsearch
* 1 year of daily backups 
* All done auto-magically by AWS -- let's talk about it if this isn't possible.

## Definition of done

- [x] Backups set up for live elasticsearch cluster
- [x] Backups set up for test elasticsearch cluster
- [x] Only 30 days of data held in live elasticsearch cluster
- [x] Only 30 days of data held in test elasticsearch cluster

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by nayoa** [comment]
Having an 'automated_snapshot' is a requirement to building an elasticsearch cluster. The terraform for creating an elasticsearch cluster has a backup of everyday at 11pm for both the live and test cluster - https://github.com/ministryofjustice/cloud-platform-aws-meta-configuration/pull/3

**Comment by nayoa** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/74

**Comment by nayoa** [comment]
Pods were erroring due to the fact that there weren't any logs to delete. An exception has been added to the code to ignore when this happens.

**Comment by nayoa** [comment]
Note: Due to kiam deployed in the test-1 cluster, the cronjob is failing due to not having the correct iam role to the elasticsearch cluster.
