### ISSUE TITLE
Set correct CPU/memory Requests for Ingress controller namespace

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2876]
Ingress Controller namespace doesnot have a resource requests set. 

The ingress-nginx chart has requests set for the nginx pods through the chart here: https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml#L285-L291. But, on an average the nginx pods require 700-900 MiB memory to run in live-1. 

https://grafana.cloud-platform.service.justice.gov.uk/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&refresh=10s&from=now-24h&to=now&var-datasource=default&var-cluster=&var-namespace=ingress-controllers

 
## Approach

- Increase the requests for nginx pods to the value required. Check for right value for all ingress controllers (default, modsec, integration-tests)

- set the limitRange for namespace ingress-controllers. defaultlimits and defaultRequests

 This is to ensure the nginx pods are scheduled on the correct node and protects against a resource shortage on a node when resource usage later increases during the peak.

## Which part of the user docs does this impact
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller
https://github.com/ministryofjustice/cloud-platform-terraform-modsec-ingress-controller

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Aged-out
