### ISSUE TITLE
Update guide to reflect new EKS cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2878]
We'll need to update our user guide to reflect the new EKS cluster e.g. references to "Live 1".

This story may require breaking down further.

**Comment by davidread** [comment]
This exercise will be really useful to spot gaps in the new cluster. e.g. template files used by the CLI reference the old cluster

**Comment by vijay-veeranki** [comment]
Things need changing:
https://github.com/ministryofjustice/cloud-platform-helloworld-ruby-app

**Comment by vijay-veeranki** [comment]
Updated user-guide to reflect "live-1"

https://github.com/ministryofjustice/cloud-platform-user-guide/pull/1000

This needs revisiting as a clean up task. Once the migration is completed .
