### ISSUE TITLE
Migrate Reference App to new “live” cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2880]
Migrate Reference App to new “live” cluster

Approach:
- Migrate the app
- Test that it is working correctly
- Document as issues with migration that may need to be fixed for user migrations, or may influence migration approach and documentation

**Comment by vijay-veeranki** [comment]
Migrated the cloud-platform reference app to live now

https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-reference-app

Deployed the app through the circleci

https://github.com/ministryofjustice/cloud-platform-reference-app/tree/main/deploy/kubectl/production


In circle ci updated the below VAR, this let the deployment of app through the circleci.
K8S_CLUSTER_CERT: To the new cert for eks-live
K8S_CLUSTER_NAME: to live.cloud-platform.service.justice.gov.uk
K8S_TOKEN: New token created by the circleci sa in eks-live
EKS_API: To the API of eks-live

Updated the ingress to add aws-weight
https://github.com/ministryofjustice/cloud-platform-reference-app/blob/main/deploy/kubectl/production/ingress.yaml#L6-L7
