### ISSUE TITLE
Create testbed for terraform modules

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#2886]
## Background
 - We want unit tests for our modules, running in a reasonable time, but VPC&RDS creation takes a long time
 - Localstack doesn't cover all the options we want (MySQL, MS-SQL)
 - Localstack did not communicate a price

## Approach
 - Create a persistent VPC in the ephemeral account
 - Create a persistent EKS cluster in said VPC; keep that cluster as small as possible and with minimal configuration

## Definition of done
 - terraform code that creates the above
 - runbooks edited to describe how the resources will be used by terratest

**Comment by razvan-moj** [comment]
trying localstack for now

**Comment by razvan-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-testbed if we change our mind

**Comment by AntonyBishop** [comment]
Unblocked now that we have access to localstack

**Comment by AntonyBishop** [comment]
Aged-out
