### ISSUE TITLE
Split Infrastructure plan & apply pipelines 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2887]
## Background

We have a Plan and Apply pipeline running for Infrastructure code changes. The CLI do a bulk apply on `live` and `manager` cluster together in one pipeline.
https://github.com/ministryofjustice/cloud-platform-concourse/blob/main/pipelines/manager/main/cloud-platform-infrastructure.yaml

We want to see the plan/apply of a PR change in manager and live seperately. This will be helpful when we want to test a change in `manager` and then apply in `live` cluster.

## Approach

Split the pipeline either through concourse or with cli code to get cluster name and apply only on the given  cluster.

## Which part of the user docs does this impact
https://github.com/ministryofjustice/cloud-platform-cli
https://github.com/ministryofjustice/cloud-platform-concourse

## Definition of done

- [x] Plan and Apply infrastructure Pipeline triggered for each cluster seperately
- [x] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Aged-out
