### ISSUE TITLE
Test logging setup with laa-fee-calculator team

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#289]
## Background

To see how well the logging pipeline works we want to sit with a member of the laa-fee-calculator team and make sure that: 

* they understand the documentation
* they can get logs from their application to Kibana
* they can log into Kibana

------

*As a* development team member
*I need* to search logs for my application(s) in a central place
*So that* I can debug issues with my service

We are going to use the Elasticsearch, Fluentd, Kibana stack for our logging infrastructure. This is largely familiar to us from the existing setup and from the spike that @ollieanwyll, @pwyborn and Serj did earlier in the year. 

## Approach

If you can't get laa-fee-calculator team, see if you can work with one of the other users, e.g. other laa team or OPG. 

## Definition of done

- [ ] We've worked through the process with a user
- [ ] The user understands the flow to get logs set up

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
After a discussion with some of the team, I have been informed that the LAA Fee Calculator api doesn't write to stdout.

**Comment by jasonBirchall** [comment]
I've posted this message in the #laa_fee_calculator slack room:
jasonb [10:49]
Hi @here - last week a new EFK stack was provisioned on the Cloud Platform live cluster (where the LAA-Fee-Calculator sits). This utilises Fluentd on the k8s nodes to collect all container and system log data. I just thought I'd drop a line in this channel to let you know the URL:
https://kibana.apps.cloud-platform-live-0.k8s.integration.dsd.io/_plugin/kibana
You can use the selected fields `kubernetes.namespace_name:laa-fee-calculator-production` to see what's going on inside your namespace. Let me know if you have any questions.

**Comment by jasonBirchall** [comment]
Documentation has been published and url given to LAA-Fee-Calc devs with instructions. I've left a note with them to say that I'm available if anyone gets stuck.
