### ISSUE TITLE
Test users terraform modules with EKS cluster - dynamodb-autoscaler

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2891]
Test end to end whether they work as expected in EKS.

**Comment by vijay-veeranki** [comment]
Users are not using this module and we haven't updated it for nearly 3 years other than updating our terraform version.
https://github.com/ministryofjustice/cloud-platform-terraform-dynamodb-autoscaler

Question is shall we still maintain this or archive it?
