### ISSUE TITLE
Test users terraform modules with EKS cluster - amq-broker

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2892]
Test end to end whether they work as expected in EKS.

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/4827
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/plan-live/builds/35

**Comment by pwyborn** [comment]
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/86

https://github.com/ministryofjustice/cloud-platform-environments/commit/1dc448c09ff4a48f7b2c09ccfac317c94bacfc09
