### ISSUE TITLE
Matching NS record in the DSD account for interventions service

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#2912]
## Service name

Refer and monitor an intervention (HMPPS)

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Setting up the production domain

## Problem description

I'm following the process outlined on [the user guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/custom-domain-cert.html#using-a-custom-domain).

I have created the Route53 zone, pending merge in https://github.com/ministryofjustice/cloud-platform-environments/pull/4823.
~~Once it's merged~~ It is now merged, could you create the matching NS record in the DSD account, please?

Domain: `refer-monitor-intervention.service.justice.gov.uk`

## Contact person

David Lantos - `@David Lantos` on Slack

**Comment by sablumiah** [comment]
New NS records have been created on DSD account
