### ISSUE TITLE
FIREBREAK: test EBS GP3

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#2914]
## Background

You'll need to install the CSI driver and it would be worth testing your applications against GP3 but it should deliver better performance for lower cost seeing as one of the biggest AWS costs for MoJ is EBS

CSI = https://github.com/kubernetes-sigs/aws-ebs-csi-driver

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by davidread** [comment]
Let's understand where we use this, and how hard/easy implementing it would be

**Comment by razvan-moj** [comment]
Seems to work fine, to be implemented in https://github.com/ministryofjustice/cloud-platform/issues/3043
