### ISSUE TITLE
Create a page to point users to some basic reference for getting started with Kubernetes

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#292]
## Background

We are going to have new users who have a very low level of knowledge about Kubernetes or never used it at all. Users might want to find some starting material. We have had a few questions in #cloud-platform-users asking for this sort of info and have found some materials that we think are good to help with this.  

We should include this in our guide.

## Proposed user journey

As user wants to find out more about Kubernetes.

A user can go to our user guide and find a section with some useful reference resources.

If we have questions in the user channel we can send them a link to this page within the guide. 

## Approach

Create a page within the guide that gives users some useful references about Kubernetes.

The page should include links to the following:
Kubernetes Concepts - https://kubernetes.io/docs/concepts/
Pluralsight, theres an introduction course to kubernetes https://www.pluralsight.com/courses/getting-started-kubernetes
Udacity - Course that uses Google Cloud but content is transferrable and free!- https://eu.udacity.com/course/scalable-microservices-with-kubernetes--ud615

## Definition of done

- [ ] page create in our user guide

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by alkar** [comment]
https://ministryofjustice.github.io/cloud-platform-user-docs/03-other-topics/003-quick-reference/#kubernetes-quick-reference could be part of this?
