### ISSUE TITLE
Request for Pingdom integration ID

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#2925]
## Service name

Refer and monitor an intervention

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Monitoring

## Problem description

I have added a Pingdom integration to Slack that goes to `#interventions-alerts`: https://mojdt.slack.com/services/B023L7QFJ80 

Could we ask for an integration ID for this notification method, please?

## Contact person

`@David Lantos` on Slack

**Comment by mogaal** [comment]
Done, and the integration ID is 114225
