### ISSUE TITLE
Route prometheus alerting in slack for ppud-replacement-dev

### ISSUE THREAD

**Issue by dazoakley** [ministryofjustice/cloud-platform#2926]
## Service name

PPUD Replacement

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

We'd like to route the alerts to the service/application team so they don't end up as noise in #dps_alerts_non_prod

## Problem description

Here's the information needed for the routing:

**namespace name:** `ppud-replacement-dev`
**team name:** PPUD Replacement
**application name:** `manage-recalls-ui` and `manage-recalls-api`
**slack channel:** `#ppud-replacement-alerts-nonprod`
**kubernetes secret name where the webhook url is stored:** `alerting`
**severity level (warning/information):** warning

## Contact person

`@Darren Oakley`

**Comment by vijay-veeranki** [comment]
severity = "ppud-replacement-alerts"

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-prometheusrule

**Comment by dazoakley** [comment]
Thanks @vijay-veeranki! 😄
