### ISSUE TITLE
Route prometheus alerting in slack for ppud-replacement-preprod

### ISSUE THREAD

**Issue by dazoakley** [ministryofjustice/cloud-platform#2938]
## Service name

PPUD Replacement

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

We'd like to route the alerts to the service/application team so they don't end up as noise in #dps_alerts_non_prod

## Problem description

Here's the information needed for the routing:

**namespace name:** `ppud-replacement-preprod`
**team name:** PPUD Replacement
**application name:** `manage-recalls-ui` and `manage-recalls-api`
**slack channel:** `#ppud-replacement-alerts-nonprod`
**kubernetes secret name where the webhook url is stored:** `alerting`
**severity level (warning/information):** warning

## Contact person

`@Darren Oakley`

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1210

**Comment by pwyborn** [comment]
paulwyborn  3:06 PM
Hi Daren - ticket:
Route prometheus alerting in slack for ppud-replacement-prod#2940 should be in place now
Done:
Severity: “ppud-replacement-prod”

Darren Oakley  3:07 PM
Awesome, thank you. I'm off today but will check it all out and confirm tomorrow :)

paulwyborn  3:07 PM
Also ticket:
Route prometheus alerting in slack for ppud-replacement-preprod#2938
Done:
Severity: “ppud-replacement-preprod”
3:07
Ok thanks Darren
