### ISSUE TITLE
AlertManager route for interventions-prod

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#2941]
## Service name

Refer and monitor an intervention (HMPPS)

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We'd like to route the alerts to the team channel so that it's visible without visiting the dashboard

## Problem description

Information [requested](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-slack-webhook-and-amend-alertmanager):

**namespace name**: `hmpps-interventions-prod`
**team name**: HMPPS interventions
**application name**: `hmpps-interventions-ui` and `hmpps-interventions-api`
**slack channel**: `#interventions-alerts`
**kubernetes secret name where the webhook url is stored**: `alertmanager-slack`
**severity level (warning/information)**: warning

Could this have `severity: interventions-prod`, please?

## Contact person

`@David Lantos` on Slack

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1212

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1213

**Comment by sldblog** [comment]
Thank you! :)
