### ISSUE TITLE
Block access to instance metadata in 'live' cluster

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#2942]
Acceptance criteria:
 - chart deployed
 - default deny access to metadata

**Comment by davidread** [comment]
Reasoning: we want to block instance metadata to reduce breach blast radius, as agreed in our ADR: https://github.com/ministryofjustice/cloud-platform/pull/2931/files#diff-ae354d90844167143ed3a40d408fedaf4d44d28dd826c3b1d9ffe25d7a773098R213-R215

Options of how to do this:

* "by requiring the instance to use IMDSv2 only and updating the hop count to 1" - [ref](https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node)
* add iptables rule - [ref](https://docs.aws.amazon.com/eks/latest/userguide/best-practices-security.html#restrict-ec2-credential-access)
* Installing kube2iam to add the iptables rule (@poornima-krishnasamy suggested it)

**Comment by razvan-moj** [comment]
The GlobalNetworkPolicy used in https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1262 breaks networking in namespaces where it is enforced - no hostnames are resolved.
Also, in excluded namespaces, the default SA still inherits the node role, which may be undesirable.
Will revisit kube2iam next sprint

**Comment by razvan-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1262/files
