### ISSUE TITLE
figure out / document cross-account IAM

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#2943]
This will use the  IRSA module with the needed policy to access S3 buckets

used in https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cross-account-IAM

A/C:
make it work in live (not 1)

**Comment by pwyborn** [comment]
xref https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2944 ?

**Comment by pwyborn** [comment]
Use Case?
Developer needs to access s3 bucket in account 2 (the shared account):
1/ Associate OpenIDConnect for the EKS cluster in account 1 (the developers account)
2/ Create an OIDC provider in account 2 (the shared account):
	The provider url corresponds/comes from the EKS cluster in account 1 and is set to audience "sts.amazonaws.com"
3/ Create a role in account 2 (the shared account) that provides read only access (or whatever) to all objects in the S3 bucket for:
	The user federated by the OIDC provider - allowing it to assume the role.
4/ Create a service account in the development-cluster and annotate it with the ARN for the role created in step 3/ above.
5/ Specify that service account in the pod specification

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/738 pull request 20/07/2021
