### ISSUE TITLE
Change order of links deployment using Helm and Kubectl in the user guide

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#295]
## Background

User feedback based on use of the guide. A new user with little experience of Kubernetes has been using the guide to deploy the test app but ran into difficulties with deploying with Helm. He tried Helm first as it was the first link in the guide and he was following the guide in a logical order.

For users with less Kubernetes knowledge it would be easier for them to try with Kubectl first. In that case it would seem logical to put that first in the guidance if users are following it in a logical order.

## Proposed user journey

User working through guide to deploy app will try via Kubectl (which is easier, especially for users with less familiarity with Kubernetes) before trying deployment via Helm

## Approach

Change the ordering of the links in the guide.

## Definition of done

- [x] ordering of links changed in user guide

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-user-docs/pull/71
