### ISSUE TITLE
Investigate Pod - automatic even distribution on nodes (KubeletTooManyPods)

### ISSUE THREAD

**Issue by pwyborn** [ministryofjustice/cloud-platform#2951]
## Service name

Pod Distribution on nodes - Monitoring

## Impact on the service

![Screen Shot 2021-06-08 at 09 21 46](https://user-images.githubusercontent.com/6805936/121150010-107a2c80-c83b-11eb-8e5e-bdab165e2767.png)

Related https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2441

## Problem description
When the above alert fires - the solution is normally to delete some pods from the offending node.
The pods should shuffle to another node when they are created, this should be done automatically.

- It was found that sometimes the pods would be re-created on the same node
-  or all of the pods would be created on another node - thereby shifting the problem to the other node.
![Screen Shot 2021-06-07 at 18.14.51.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/652a10ba-88f0-4f32-83a3-8d2b494a7771)

Investigation required - Is there a way of an even distribution across the nodes - automatically?

## Contact person

Paul Wyborn

**Comment by jasonBirchall** [comment]
closes https://github.com/ministryofjustice/cloud-platform/issues/2960

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1252
