### ISSUE TITLE
Requesting Integration ID for Pingdom Slack notification

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#2953]
## Service name

CLA/FALA

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Problem description

I am following this guide and it says to create a ticket to get an integration ID for pingdom/slack integration https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#adding-slack-notification

Team name: CLA/FALA
Application name: CLA Frontend
Slack channel: [hash]cla-alerts

## Contact person

[at]Said
[hash]laa-cla-fala

**Comment by pwyborn** [comment]
Integration id and added given to user
