### ISSUE TITLE
Dry run of migration doc with a user

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2957]
## Background

We have created a draft migration plan for user apps - https://github.com/ministryofjustice/cloud-platform-user-guide/blob/main/source/documentation/other-topics/migrate-to-live.html.md.erb 

(was https://docs.google.com/document/d/1kU5xOvl00QXtcak-qQONstXcMAJWvTduYH4cG_IyEbc/edit?ts=60c20a79#)

We will now ask about 5 real users to trial a test migration.

This will enable us to refine the plan document.

## Approach

Have a real user test our migration plan. Gain feedback and improve the migration plan.

Test service will be decommissioned after trial

Update the plan.

## Questions / Assumptions

Identify a user(s) to carry out the dry run.

## Definition of done

- [ ] Dry run of migration document with user test app
- [ ] Update document

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Testing underway

**Comment by davidread** [comment]
Broken up into 5 tickets
