### ISSUE TITLE
Get rid of integration ingress

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#2958]
## Background

As part of getting EKS cluster ready for migration we need to address an issue with an "integration ingress". This is causing complexity with the creation of the new live cluster. We do not believe that is is needed.

## Approach

1. Investigate the purpose of the integration ingress
2. Confirm if whatever it is doing is still required.
3. If not required we should remove it.
4. If function still required plan how we replace that function in the context of the new cluster

## Which part of the user docs does this impact

Identify any changes to guide or runbooks as part of story.

## Questions / Assumptions

Assumption that ingress if not required.

if it is we will need to revisit.

## Definition of done

- [ ] confirm if ingress is required
- [ ] decommission if not
- [ ] raised story for any activities to replace functionality.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Can you please explain why we would want to do this, please?

**Comment by AntonyBishop** [comment]
Content added.

**Comment by leoncarrington** [comment]
@sablumiah @jasonBirchall @poornima-krishnasamy  Hi All, we got a mixture of estimates for this one. Any unseen complexities why this would be a 5, or opportunities for ease why this would be a 3?

**Comment by poornima-krishnasamy** [comment]
> @sablumiah @jasonBirchall @poornima-krishnasamy Hi All, we got a mixture of estimates for this one. Any unseen complexities why this would be a 5, or opportunities for ease why this would be a 3?

I have estimated 2 because its the smoke test which uses the "integration ingress controller". so change the smoke test to point to modsec-01 ingress controller, test the modsec tests and remove the "integration ingress controller". I am happy to move to 3 since it involves changing ruby and also removing something from live-1 cluster.

**Comment by davidread** [comment]
Thanks for the explainer @poornima-krishnasamy 👍 Just adding a link to the test that you mentioned: https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/smoke-tests/spec/modsec_spec.rb

**Comment by razvan-moj** [comment]
done in https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1240
