### ISSUE TITLE
Add create permissions for Helm into the namespace creation part of the guide

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#296]
## Background

Feedback on user guide. A new user tried to deploy the test app using Helm. However this failed as the user had not created permissions for Helm when creating the namespace.

Reference should be made to this in the namespace creation guidance to ensure that permissions are set up correctly.

## Proposed user journey

A user needs to create permissions for Helm when creating the namespace so that Helm works correctly when they try to deploy with Helm.

## Approach

Add Tiller documentation to `cloud-platform-user-docs`

## Definition of done

- [ ] Add Tiller documentation to `cloud-platform-user-docs`
- [ ] guide updated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by kalbir** [comment]
@AbdirizakObsiye2018 if you want to add any more comments on this that would be great

**Comment by AntonyBishop** [comment]
Story includes - Guide is missing tiller rbac configurations to make changes to the namespace when using Helm.
