### ISSUE TITLE
Install AWS Systems Manager

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2962]
## Background

[AWS Systems Manager Session Manager](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html) provides a good way to open a shell on a k8s node. (As a better alternative to bastion nodes and ssh.)
See ADR: https://github.com/ministryofjustice/cloud-platform/pull/2931/files#diff-ae354d90844167143ed3a40d408fedaf4d44d28dd826c3b1d9ffe25d7a773098R166

## Approach

Suggest we install the daemonset to install the SSM Agent needed for Systems Manager.

Note:
* requires permissions `hostNetwork: true` and `privileged: true` so may need its own PSP
* it's no use if the node is failing to boot or join the cluster properly, but we can live with that - it's likely that it's the pods we want to characterize, not the node, because the node is managed

## Definition of done

- [x] installed with infrastructure as code
- [x] CP team can open a shell on any node
- [ ] docs written for CP team to do this

**Comment by razvan-moj** [comment]
https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210621

**Comment by davidread** [comment]
@razvan-moj says the agent is already in the AWS AMI, but there's setup to do. If there's a lot of setup then let's reconsider putting worker ssh keys onto the bastion.

**Comment by poornima-krishnasamy** [comment]
https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started.html

Option 1: Attach AmazonSSMManagedInstanceCore to the node role

To terraform it: add policy by setting this variable: workers_additional_policies
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/02c9a52f3b728e86bdb7feb537ee4e849f55efe2/variables.tf

Using AWS System Manager, setup Quick Setup -> 

From session manager: start session and choose the instance. 
The default user is ssm-user
to switch to root do 
sudo -s

To check the status of the ssm : sudo systemctl status amazon-ssm-agent
