### ISSUE TITLE
Plan URLs for Prometheus etc, in light of the EKS migration

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2964]
## Background

Plan URLs for the instances of Prometheus, AlertManager and Thanos on the two clusters. Check this migration makes sense for users and all software interactions with these components.

(Grafana is dealt with in a separate ticket: https://github.com/ministryofjustice/cloud-platform/issues/2963 )

## Considerations

So what URL will they get? Currently we have:
* prometheus.cloud-platform.service.justice.gov.uk
* alertmanager.cloud-platform.service.justice.gov.uk

Do we temporarily create?:
* prometheus.live.cloud-platform.service.justice.gov.uk
* alertmanager.live.cloud-platform.service.justice.gov.uk
And at some point repoint the original names at this instance?

Also, consider how we will write the terraform to achieve this.

**The reasoning for per-cluster instances of Prometheus, Alertmanager and Thanos** For a while we're going to have two clusters - 'live-1' and 'live' - and plan to have an instance of Prometheus/Alertmanager/Thanos on each cluster, each collecting/processing metrics on their own clusters. The alternative would be to have a combined Prometheus instance across both clusters. We'd need a double sized Prometheus instance created on live, migrate the PersistentVolume containing the Prometheus data across to live, and give it access to all pods on both clusters, so that it can poll the metrics end-points there. Thanos and Alertmanager would be easier because they store no state in the cluster. But moving Prometheus doesn't like easy engineering. It's only for a relatively short transition period, and only to avoid the user confusion of having 2 URLs.

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/prometheus.html#using-the-cloud-platform-monitoring-and-alerting-stack

## Definition of done

- [ ] write a workable plan, linked to this ticket

**Comment by vijay-veeranki** [comment]
Moving back to This Sprint, as I picked it thinking cert-manager upgrade will be on hold.

**Comment by vijay-veeranki** [comment]
https://docs.google.com/presentation/d/1CDgTE9qQpwXlNxsG7ITixI0eFNOLG_SoALQVDilvj38/edit#slide=id.p
