### ISSUE TITLE
Suggestion: We reject any issue that hasn't followed the template structure

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2966]
## Background

Coming back from annual leave I noticed we have an abundance of issues that contain single word issues. They might make sense to people in the know, but the rest of us are left confused.

## Proposed user journey

We should create an automated process that rejects any issue that doesn't follow the templated user story.

## Approach

This is personal choice but I would write a script/process that looks for the existence of key words in an issue body. If the issue doesn't contain these key words, it should be closed and a message should be sent to the slack channel #cloud-platform-notify.

Obviously there is some artistic licence to how this is achieved, but as long as the end result is: we no longer allow single word issues, I'll be a happy bunny. 

## Which part of the user docs does this impact

Maybe just a README on how it works and how to contribute.

## Questions / Assumptions

There isn't a tool already out there that performs this task.

## Definition of done

- [ ] Any script/process that is written is fully documented
- [ ] This work is presented back to the team
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Aged out
