### ISSUE TITLE
Please make myself and Ben Neill contributors of the ci-deploy git repo and add our GPG keys to the .git-crypt for that repo

### ISSUE THREAD

**Issue by isherraikmo** [ministryofjustice/cloud-platform#297]
## Service name Jenkins

Isher Singh Raikmo and Ben Neill 

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [x] Other

## Impact on the service

would you mind please making @bneill_hmcts and me contributors of the ci-deploy repo and add our GPG keys to the git-crypt for the repo?

## Problem description

This is needed in order to be able to manage the HMCTS Jenkins instance and troubleshoot any issues.

## Contact person

@Isher Singh Raikmo and @bnneill hmcts

Our git usernames are isherraikmo and cakeben

**Comment by lukaszraczylo** [comment]
I have added mentioned users to the SSH access and repo management.

**Comment by isherraikmo** [comment]
Our GPG keys have not been added to the git-crypt of this repo. Can somebody please do this?

**Comment by pwyborn** [comment]
Added Isher's gpg key to the repos - Asked Isher to add Ben's gpg key to the repos ci-deploy

**Comment by pwyborn** [comment]
Complete
