### ISSUE TITLE
Investigate bad modsec ingress controller upgrade - why didn't smoke tests fail?

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2972]
## Background

Reproduce the bad upgrade to the modsec ingress controller on test kops cluster, and investigate why the smoke/integration tests didn't fail.

This is an action following the recent incident: [Incident: 2021-06-09 - ModSec Ingress-controller upgrade blocked k8s changes](https://docs.google.com/document/d/1s5pos29Gcq0ssVnpf0biqG2aE-Kt2PtyxEcpjG88rdc/edit#)

## Definition of done

- [ ] record in this ticket the reason the smoke tests didn't go red during test
- [ ] create a ticket explaining how to fix the problem
- [ ] discuss with the team

**Comment by davidread** [comment]
@razvan-moj didn't you get to the bottom of this?

**Comment by razvan-moj** [comment]
@davidread did fix yes, the reason was smoke test were running on another ingress controller named integration-controller, which we have now deleted so this can be closed

**Comment by davidread** [comment]
👍
