### ISSUE TITLE
Add smoke test for modsec ingress controller

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2974]
We want to a smoke test that checks the modsec ingress controller is working, forwarding traffic to services.

Because in a recent incident, we replaced a ingress controller instance, forgetting that DNS was going to point at the previous instance that was now deleted, for up to 5 minutes.

To flag this problem in the smoke tests, let's add a helloworld app that uses modsec controller, for the smoke tests to check traffic works, when we run them straight after the upgrade.

This is an action agreed in the review into the recent incident: [Incident: 2021-06-09 - ModSec Ingress-controller upgrade blocked k8s changes](https://docs.google.com/document/d/1s5pos29Gcq0ssVnpf0biqG2aE-Kt2PtyxEcpjG88rdc/edit#)

## Definition of done

- [ ] smoke test added, that would have alerted us to the downtime when replacing the modsec ingress controller
- [ ] another team member has reviewed
- [ ] smoke tests are green

**Comment by AntonyBishop** [comment]
Aged out
