### ISSUE TITLE
Create or integrate "live" cluster divergence pipeline

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2977]
## Background

We have a pipeline for Manager and live-1 that checks to see if what's in git matches what's deployed in the cluster. This is useful as it keeps us from diverging from our source of truth.

## Proposed user journey

We should create the same setup for the new "live" cluster. 

## Approach

Either duplicate the pipeline for the new "live" cluster, or we can amend the current iteration and remove the if condition that sets the cluster variable to a switch statement.

## Which part of the user docs does this impact

Check the runbooks page for references on this running on manager and live-1 only. Make this documentation cluster agnostic.

## Questions / Assumptions

That we can just replace the if condition with a switch statement. That "live" is a similar setup to "manager".

## Definition of done

- There is a pipeline that fails if the cluster contains Terraform code that isn't in git i.e. fails an attempt at a clean `terraform plan`.
- Documentation has been updated in the runbook (if there is any).

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Done
