### ISSUE TITLE
Create or amend the "plan and apply infrastructure" pipelines for new "live" cluster

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2978]
## Background

We have pipelines for "manager" and "live-1" versions of our Kubernetes clusters that plan and apply infrastructure changes that have been PR'd or merged to main respectively.

## Proposed user journey

We need to create an equivalent pipeline for the "live" cluster.

## Approach

Either to amend the current infrastructure package that performs the `terraform apply/plan` or create a new one.

## Which part of the user docs does this impact

Any README's or runbooks that refer to live-1 or manager and this pipeline. We should make this documentation cluster agnostic to avoid this in the future.

## Questions / Assumptions

Can we just change the current function for plan/apply?

## Definition of done

That changes to the cloud-platform-infrastructure first plan and then apply.
That documentation has been updated and is easy to understand.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
We think this could be added as an option in the module, which would create ${bucket}-logs where the bucket object logs get put
