### ISSUE TITLE
New Pingdom integrationid

### ISSUE THREAD

**Issue by sivafirst** [ministryofjustice/cloud-platform#2981]
## Service name
Pingdom checks

## Service environment
Prod / Production
NS:justicedata-prod
Staging
NS: justicedata-staging

* team name : Justicedata
* application name: Justice Data: https://data.justice.gov.uk/ 
* slack channel:performance-hub-dev

## Contact person

Siva Sighakolli
siva.sighakolli@digital.justice.gov.uk

**Comment by jasonBirchall** [comment]
`114774`

**Comment by jasonBirchall** [comment]
Integration id created.
