### ISSUE TITLE
FIREBREAK: Think through CP using IAM auth for EKS

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#2982]
Let's try using IAM auth for the CP team to authenticate. The reasoning is that we can protect AWS credentials in keychain (or equivalents for non-macs) using [AWS Vault](https://github.com/99designs/aws-vault).

## Background

How do you protect kubectl creds from being accessed by malware executing on the team member's machine? Could ensure:
* creds are not powerful
* creds are not long lived
* token is not held in plain text   <--- this is what this ticket aims to look at

Plain text:
* kubectl accepts either kubeconfig file or a token in the `--token` param
* kubeconfig contains a plain text token if you use: OIDC, but not if you use some sort of authenticating proxy, like AWS's IAM.

[AWS Vault](https://github.com/99designs/aws-vault) enables you to store AWS creds in Apple's keychain, accessible each time with a password prompt.

## Definition of done

- [x] Write up what you did, whether it worked, and next steps for using it for the CP team
- [x] Demo to the team
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by davidread** [comment]
How do you manage users - JML. Need to create new users quickly. Ease of getting refreshed tokens. Leavers.

**Comment by poornima-krishnasamy** [comment]
https://github.com/99designs/aws-vault

**What is aws-vault:**

aws-vault stores IAM credentials in your operating system's secure keystore and then generates temporary credentials from those to expose to your shell and applications.

**Installation:**
On Mac: 
brew install --cask aws-vault

To add new profiles
aws-vault add moj-cp
This will ask for access_key_id and secret_access

To list profiles
aws-vault list
Profile                  Credentials              Sessions
=======                  ===========              ========
moj-pi                   -                        -
moj-cp                   moj-cp                   sts.GetSessionToken:59m49s
default                  -                        -

**How to use:**
To use for CLI:
aws-vault exec moj-cp -- aws s3 ls

To use with terraform:
aws-vault exec moj-cp -- terraform workspace list

**how does it fit for cloud-platform team?**

Once aws-vault is configured, you dont need to store your credentials in the file ~/.aws/credentials. Hence, there is less possibility of exposing it in raw format on your machine. 

Cloud Platform team have administrative access to the cloud-platform AWS account. Hence, using temporary credentials to access API seems a reasonable and secure approach

what went well
installation of binary was quick
setup with keychain was easy

what didnot go well
You have to key in additional words to execute cli or terraform.

Conclusion:
