### ISSUE TITLE
FIREBREAK: Investigate kuberhealthy

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2985]
https://github.com/kuberhealthy/kuberhealthy
https://github.com/kuberhealthy/kuberhealthy/blob/master/docs/EXTERNAL_CHECKS_REGISTRY.md

We have integration tests which checks for certain daemonsets, crds and namespace annotations availability.

Investigate kuberhealthy and see if that can be used to replace above integration tests.

This will be useful and will be alerted if any of the expected resources are missing in the cluster.

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by AntonyBishop** [comment]
Duplicate
