### ISSUE TITLE
Investigate-Ingress-controller- using Route53 weight policies

### ISSUE THREAD

**Issue by mogaal** [ministryofjustice/cloud-platform#2987]
5. Create a second ingress with the same annotation (different NS) see if that is possible so there will be no need to make sweeping changes to user ingress manifests. Then we can see if we can control the traffic

**Comment by mogaal** [comment]
All successful. Having two ingress controllers and also two ingresses entries:
``` 
$ kubectl -n mogaal get ingress
NAME             CLASS    HOSTS                                                 ADDRESS                                                                         PORTS     AGE
hello-wold       <none>   mogaal.mogaal.cloud-platform.service.justice.gov.uk   ad60238540b4d4875953373788f8d7d9-61fb72135f11c12a.elb.eu-west-2.amazonaws.com   80, 443   18h
hello-wold-new   <none>   mogaal.mogaal.cloud-platform.service.justice.gov.uk   a16e0f30b8922408d9fa60ccbd80f2d1-253b861469605458.elb.eu-west-2.amazonaws.com   80, 443   18h
```

as you see both of them have the same `host` and different `address` (NLBs from the different ingress controllers).
Each of the ingresses entries are using `external-dns.alpha.kubernetes.io/aws-weight: 50` as a weight A record and we see that is reflected in Route53

In conclusion, we can use weight policies to migrate users from different ingress controllers without downtime/

**Comment by AntonyBishop** [comment]
@mogaal is this done?

**Comment by mogaal** [comment]
@AntonyBishop yes. I'll close it now.
