### ISSUE TITLE
kuberhealthy for Testing 

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2991]
Can this help with our testing?

https://github.com/kuberhealthy/kuberhealthy

Kuberhealthy is an operator for running synthetic checks. By creating a custom resource (a khcheck) in your cluster, you can easily enable various synthetic test containers. Kuberhealthy does all the work of scheduling your checks on an interval you specify (like a CronJob), ensuring they run properly within an allotted timeout, maintaining the current up/down state with durability, and producing metrics. There are lots of useful checks already available to ensure the core functionality of Kubernetes, but checks can be used to test anything you like. We encourage you to write your own check container in any language to test your own applications!

**Comment by AntonyBishop** [comment]
https://github.com/kuberhealthy/kuberhealthy
https://github.com/kuberhealthy/kuberhealthy/blob/master/docs/EXTERNAL_CHECKS_REGISTRY.md

We have integration tests which checks for certain daemonsets, crds and namespace annotations availability.

Investigate kuberhealthy and see if that can be used to replace above integration tests.

This will be useful and will be alerted if any of the expected resources are missing in the cluster.

**Comment by sablumiah** [comment]
https://www.infracloud.io/blogs/avoiding-kubernetes-cluster-outages-synthetic-monitoring/

**Comment by sablumiah** [comment]
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/3044
