### ISSUE TITLE
Namespace & Virtual Cluster Manager for Kubernetes

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#2992]
https://github.com/loft-sh/loft

Lightweight Virtual Clusters that are flexible like namespaces but much more powerful
Sleep Mode to put idle namespaces and virtual clusters asleep and saves up to 70% cloud costs
Accounts & Account Users to separate tenants in a shared Kubernetes cluster
Self-Service Namespace Provisioning for account users
Account Limits to ensure quality of service and fairness when sharing a cluster
Namespace Templates for secure tenant isolation and self-service namespace initialization
Multi-Cluster Tenant Management for sharing a pool of clusters
GitOps-Ready: Custom Resource Definitions for everything loft does

**Comment by razvan-moj** [comment]
Conclusions:

Nice project, many interesting concepts we can learn from especially the API gateway and the secrets storage.

Looks like dev teams would like it a lot as a sandbox.

Not ready for production use, big chunks of functionality are not written yet.

The lack of a fully open-source option and the cost per seat doesn't make it an appealing option for our team yet.
