### ISSUE TITLE
Template deploy fails as bootstrap_cfn package removed from pypi

### ISSUE THREAD

**Issue by ibrechin** [ministryofjustice/cloud-platform#300]
## Service name

Money to prisoners

## Service environment

- [x] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Can't deploy using jenkins at all, and can only continue to deploy from my local machine because I already have the packages installed. Could change requirements file to install from github repo to fix, but would prefer if the package was on pypi.

## Problem description

bootstrap_cfn (https://github.com/ministryofjustice/bootstrap-cfn) is a required library for template deploy. It used to be available on pypi, but for some reason appears to have been deleted recently
(some time between 03/08 and 06/08). Would be interested in knowing why it was removed, and perhaps someone could re-upload it?

## Contact person

Ian Brechin

**Comment by ushkarev** [comment]
any progress with getting `bootstrap-cfn` back on pypi.org? shall i try to? though i was never an admin of it on pypi

**Comment by ushkarev** [comment]
ok this issue can be closed. i just bumped the version number and uploaded it back to pypi.

users may need to update pinned versions in `template-deploy` repos
