### ISSUE TITLE
Create Github Action to identify PRs that contain IAM Role and Policy changes

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3015]
## Background

There is a risk that any changes to IAM Roles or Policies made my users may not be picked up by the team and those changes may give users escalated privileges. 

To mitigate this risk we want to create a GH Action that flags these changes during review.

## Proposed user journey

When a users raises a change that contains changes to Roles or Policies a GH Action will flag to the CP team that changes to these have been made so that CP Team can check and ensure that changes do not provide escalated permissions within the platform.

## Approach

Create a GH Action that checks for Role and Policy changes. Flag is there are changes so that team can review.

## Definition of done

- [x] GH Action created
- [x] Test GH Action

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
https://docs.github.com/en/actions/guides/adding-labels-to-issues

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/github-actions/tree/iam-role-policy-changes-check

**Comment by pwyborn** [comment]
Testing the go code seems to work ok locally.
08/09/2021 Need now to test in a branch as to how/whether this github-action is functioning

**Comment by leoncarrington** [comment]
Paul on leave - moving out of WIP backlog and will resume once he is back
