### ISSUE TITLE
Sendgrid account 

### ISSUE THREAD

**Issue by KPobeeNorris** [ministryofjustice/cloud-platform#302]
## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

We are struggling to properly investigate whether there are issues with visitors not receiving confirmation emails.  Without knowing if it's an issue in the first place we are unable to determine if we need to work on fixing something or not. 

## Problem description

We have been contacted by a member of staff at a prison saying that a couple of visitors have been in touch saying they haven't been getting their prison visit confirmation emails, so have not been turning up and missing out on visits.  They have provided us with some examples of visitors experiencing this issue in the past week or so, but we are unable to search back any further than 3 days in Sendgrid to see if the visitor was sent an email.  We used to be able to view the past 30 days, but this is no longer the case.  Is it possible to find out whether our subscription/plan to Sendgrid has changed that means we can no longer see this data?

## Contact person

Slack - kath.pobee-norris

**Comment by jojuolape** [comment]
Issue resolved, advised to contact service desk and servicedesk have provided payment issues with account
