### ISSUE TITLE
Resolve outstanding questions in migration plan document

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3029]
There are still a number of outstanding questions in the migration plan.

We need a discussion to resolve these questions.

Definition of done:
- [ ] Discussion held
- [ ] Questions resolved
- [ ] Document updated
- [ ] Any new stories created

**Comment by razvan-moj** [comment]
https://docs.google.com/document/d/1xnFEIGnxmtfbl7dOygsdb18Zhv0yXSqfQ7MDK9s2E7Y/edit

**Comment by davidread** [comment]
"The Domain Question" is discussed and covered in ADR: https://github.com/ministryofjustice/cloud-platform/pull/3114
