### ISSUE TITLE
Review migration plan and make it readable for users

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3030]
We have drafted a migration plan for users.

We have tested it via a number of dry-run migrations.

We need to review the plan and ensure that it is simple and ready to put into the hands of users.

Definition of Done:

- [ ] Migration Plan document can be given to users

**Comment by jasonBirchall** [comment]
Created a number of tickets to fill in gaps of the document.

**Comment by jasonBirchall** [comment]
Created a document for team to fill in.
