### ISSUE TITLE
Add section to migration plan document on setting up parallel pipeline to deploy ‘dev’ in live

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3031]
Add section to migration plan document on setting up parallel pipeline to deploy ‘dev’ in live

Definition of Done:

- [ ] section added to migration document

**Comment by poornima-krishnasamy** [comment]
Added section to the migration plan document.

Pipeline changes (if setting parallel pipelines for live-1 and live)

If you want your CD pipeline to deploy to the “live” EKS cluster without changing the existing pipeline deploying int “live-1”, create a separate pipeline, retrieve the serviceaccount credentials from the “live” cluster and add new environment variables to the CD tool. 

The environment variable referring the cluster name e.g. KUBE_CONTEXT, K8S_CLUSTER_NAME,KUBE_ENV_API maybe shared between dev and prod pipelines. So make sure you create separate environment variables to deploy only in “live” cluster.

For teams which deploy using Github Actions, the secrets will be pushed to the repository. Hence update your serviceaccount module in “cloud-platform-environments” repo to push secrets with different names. e.g. 
https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/justicedata-prod/resources/serviceaccount.tf#L4-L7
