### ISSUE TITLE
Removed Auto-Scaler

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3033]
**Background**

During migration we want more control around how the cluster scales rather than having Auto-scaler automate this.

**Approach**

- Disable Auto-scaler
- Check cluster scales up to default number of nodes (2?)

**Definition of Done**

- [ ] Auto-scaler disabled
- [ ] Cluster scaled up

**Comment by davidread** [comment]
We have benefited from basic configured auto-scaler during setup, giving us a cheap+small cluster during setup. Eventually we want to have a well-configured auto-scaler. But for the time being we'll use manual scaling, as on live-1. See: https://github.com/ministryofjustice/cloud-platform/blob/main/architecture-decision-record/022-EKS.md#cluster-scaling
