### ISSUE TITLE
Upgrade EKS clusters to Kubernetes 1.19

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3034]
## Background

We want to upgrade the 'live' and 'manager' EKS clusters to Kubernetes 1.19.

We are aware that the version of Kubernetes we are using will be deprecated in the coming months. There are also breaking changes in upcoming upgrade to Ingress.

We have decided that it is low risk to upgrade the EKS cluster as part of migration as we will get early indication from test migrations as to whether this will impact migration of services. With teams testing their apps as part of migration it will also confirm success of the upgrade.

## Approach

Upgrade EKS cluster

## Questions / Assumptions

Assumption - We will not upgrade ingress

## Definition of done

- [x] New cluster running Kubernetes 1.19

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Current runbook for upgrading the cluster: https://runbooks.cloud-platform.service.justice.gov.uk/upgrade-cluster.html#upgrade-a-cluster.
Will need changing for EKS

**Comment by AntonyBishop** [comment]
Additional context - https://mojdt.slack.com/archives/C514ETYJX/p1625664978175900

**Comment by sablumiah** [comment]
live cluster updated to 1.19

**Comment by AntonyBishop** [comment]
Include Manager upgrade under this ticket
