### ISSUE TITLE
Create a terraform module for creating ElastiCache

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#304]
## Background

We need a terraform module that users can use to create an ElastiCache cluster. This module will be called in the pipeline that creates the resources.

This resource is related to Epic - Moving Correspondence Staff Tool to Kubernetes #299 

The [S3 module](https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket) is an excellent example of how to do this.

## Proposed user journey

- User goes to the environment creation repo
- User adds to a file in that repo to request an ElastiCache
- A terraform pipeline runs to create that ElastiCache
- ElastiCache is created and the secrets for connecting to it and put into a Kubernetes secret

## Questions / Assumptions

A lot of this should be based on the way that the previous modules were done:

What should the ElastiCache be called (sensible naming convention)?
What tags do we need to add and how do we add them?
What inputs do the users need to provide?
What outputs should the module provide (e.g. secrets that can be put into Kubernetes)?

## Definition of done

- [x] There is a new repo for the module called `cloud-platform-terraform-elasticache-cluster`
- [x] Tag resources according to the tag guidance
- [x] Work out what the user input needs to be (e.g. team name, ElastiCache name, tags)
- [x] Use a randomly generated name for resources in AWS to overcome name clashes and name length limitations (see the s3 bucket module).
- [x] Suggest any other options we could give a user
- [x] Create IAM user credentials for accessing the ElastiCache (in this iteration it should be based on access keys not IAM roles for simplicity) - Need to check if this is relevant?
- [x] Add the readme like in the S3 bucket module
- [x] Update user guide

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ollieanwyll** [comment]
Need to check I can access created Redis EC on live-0

**Comment by ollieanwyll** [comment]
Work in progress:
https://github.com/ministryofjustice/cloud-platform-terraform-elasticache-cluster/tree/add/ec-terra

**Comment by alkar** [comment]
@razvan-moj is this now complete wrt the AC? Can we close?
