### ISSUE TITLE
FIREBREAK: Think through CP using IAM auth for EKS

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3042]
The goal is to be able to run kubectl, without needing long-term creds on our drives, either for AWS or k8s.

* Can we use EKS's default auth - using IAM - and get a temporary kubecfg? (Rather than our current way of getting kubecfg: GitHub OIDC -> Auth0 -> kuberos)
* Can we ensure it is convenient for our team to refresh the creds?
* How can we make sure the authorized list of users is kept up to date?

## Background

The reasoning for wanting to authenticate k8s without a long term kubecfg, is for security if the file is somehow stolen. So we'll try to leverage our AWS creds, which we can more easily avoid having long term creds in a file on disk - we can either:
* protect the long-term AWS credentials in keychain (or equivalents for non-macs) using [AWS Vault](https://github.com/99designs/aws-vault) (and demoed here: https://github.com/ministryofjustice/cloud-platform/issues/2982) which makes it easy to get a temporary token
* use SSO AWS login, which again gives us a temporary access token

## Definition of done

- [ ] Write up what you did, whether it worked, answer the questions, and next steps for using it for the CP team
- [ ] Demo to the team
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by vijay-veeranki** [comment]
CP get config using iam 
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf#L136

Using this approach
https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html
https://www.eksworkshop.com/beginner/091_iam-groups/configure-aws-auth/
