### ISSUE TITLE
change default K8s storage to GP3

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#3043]
tested during firebreak, seems to work fine and is supported without any change needed on EKS since https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG-0.x.md#v080

Data migration is done transparently by changing volume type via API / web console so terraform PR should be a noop

**Comment by davidread** [comment]
👍sounds like a no-brainer

**Comment by razvan-moj** [comment]
left gp2 as default because k8s allows 2 storageclasses to be flagged as "default" so when creating the gp3 one we're confusingly left with 2 defaults; for now we will need to specify gp3 in pvcs
