### ISSUE TITLE
Implement KuberHealthy on Cloud Platform 

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#3044]
https://github.com/kuberhealthy/kuberhealthy/tree/master/cmd

helm chart

https://github.com/kuberhealthy/kuberhealthy/tree/master/deploy/helm/kuberhealthy

**Comment by sablumiah** [comment]
A spike on Kuberhealthy wad completed to conclude if this would add value to the cluster. 
My opinion is that this does a very good job at proactive (synthetic) monitoring testing some things we do as part of out smoke tests and somethings we are yet to monitor. There will be a task to identify what to use our custom smoke tests for and what to use kuberhealthy for. 

The application is an operator and monitors for CRDs which are used to create tests/checks.
It also connects to Prometheus natively so alarms can be set based on the metrics of the application itself as well as the tests created.  

There are [default alarms](https://github.com/kuberhealthy/kuberhealthy/tree/master/cmd) as well as a [go package](https://github.com/kuberhealthy/kuberhealthy/tree/master/pkg) to create custom checks.

**Comment by davidread** [comment]
Let's try to use this to monitor the cert - see https://runbooks.cloud-platform.service.justice.gov.uk/incident-log.html#incident-on-2021-07-12-15-24-all-ingress-resources-using-apps-live-1-domain-names-stop-working

**Comment by jasonBirchall** [comment]
Please see https://github.com/ministryofjustice/cloud-platform/issues/3386
