### ISSUE TITLE
Use of AWS Snow Ball/Cone

### ISSUE THREAD

**Issue by dazoakley** [ministryofjustice/cloud-platform#3047]
## PPUD Replacement

Following on from this slack thread: https://mojdt.slack.com/archives/C57UPMZLY/p1626105340051100

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Problem description

We have a need to import a rather large amount of data from the current hosts of PPUD (around 6-7Tb) that is just not sensible to attempt over the internet...  It looks like AWS Snow Ball/Cone could be suitable for this task - is this something we can use?

It looks like you can setup a transfer request via the AWS Console or CLI, but there isn't a terraform module for it.

Also can we check from the Infosec perspective - this is production data - is AWS Snow Ball/Cone cleared/suitable for this kind of data?

## Contact person

Me - @Darren Oakley on slack

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1626105340051100

**Comment by pwyborn** [comment]
1. Confirm security have no issues. 
2. Is it worth creating a module?

**Comment by AntonyBishop** [comment]
Security tread - https://mojdt.slack.com/archives/C52LPHPK8/p1626167073105400

**Comment by AntonyBishop** [comment]
Security have confirmed that AWS Snowball can be used for migration as previously used on the MoJ estate.

**Comment by AntonyBishop** [comment]
Hi @dazoakley,

Any updates on when you may be needing this? We don't believe we need to build anything new in support of this, however we may need to provide some support for requesting Snowball device.

**Comment by AntonyBishop** [comment]
Will revisit nearer the time.
