### ISSUE TITLE
Cannot deploy laalaa application to staging environment

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#305]
## Service name

https://staging.laalaa.dsd.io/

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Cannot deploy the application to staging server(s), cannot test the functionality.

## Problem description

https://ci.service.dsd.io/view/LaaLaa/job/DEPLOY-laalaa/87/

## Contact person

`@David Lantos` on Slack, @sldblog here

**Comment by sldblog** [comment]
I assume the problem prevents the application to be deployed to production as well.
Related ticket: #318.

**Comment by ushkarev** [comment]
i suspect it's the same issue as https://github.com/ministryofjustice/cloud-platform/issues/300
