### ISSUE TITLE
Update User guide to use template-documentation site repo

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3059]
Cloud Platform user-guide uses the tech-docs-publisher image as a base image to publish the pages to the github. Whenever the Gemfile.lock is updated, the tech-docs image needs amending. This is maintained as part of [tech-docs repo](https://github.com/ministryofjustice/tech-docs-github-pages-publisher) and hence Gemfile.lock in that repo needs amending. 

Use [template-documentation-site](https://github.com/ministryofjustice/template-documentation-site) to build the runbook so Cloud-platform doesnot need to maintain a seperate Gemfile.lock

## Definition of done

- [ ] Update the runbooks repo (https://github.com/ministryofjustice/cloud-platform)
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jakemulley** [comment]
Closed by ministryofjustice/cloud-platform-user-guide#1210 👍🏼
