### ISSUE TITLE
CloudTrail for all regions

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#307]
## Background

We need to have AWS CloudTrail enabled for security reasons.

## Proposed user journey

N/A

## Approach

Setup cloudtrail for all regions, for both the integration and cloud-platform accounts.

(don't forget to enable log file validation!)

## Questions / Assumptions

N/A

## Definition of done

As described above.

## Reference

- https://www.terraform.io/docs/providers/aws/r/cloudtrail.html

**Comment by jasonBirchall** [comment]
Do we have more than one account we use for the cloud-platform?

**Comment by jasonBirchall** [comment]
Applied to the intergrations account.

**Comment by alkar** [comment]
@jasonBirchall We'd want this applied both on the integration and cloud-plaform accounts.
