### ISSUE TITLE
New domain: restricted-patients-api-preprod.hmpps.service.justice.gov.uk

### ISSUE THREAD

**Issue by sp-watson** [ministryofjustice/cloud-platform#3078]
## Service name

hmpps-restricted-patients-api

## Service environment

Pre-prod

## Problem description

We need a new domain adding please, restricted-patients-api-preprod.hmpps.service.justice.gov.uk

## Contact person

Slack: Steve Watson

**Comment by vijay-veeranki** [comment]
hmpps.service.justice.gov.uk is already exists
