### ISSUE TITLE
New domain: manage-restricted-patients-preprod.hmpps.service.justice.gov.uk

### ISSUE THREAD

**Issue by sp-watson** [ministryofjustice/cloud-platform#3079]
## Service name

hmpps-restricted-patients

## Service environment

Pre-prod

## Problem description

Need a new domain adding please: manage-restricted-patients-preprod.hmpps.service.justice.gov.uk

## Contact person

Slack: Steve Watson

**Comment by vijay-veeranki** [comment]
hmpps.service.justice.gov.uk
