### ISSUE TITLE
Setup a new ElasticSearch cluster for audit logs

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#308]
## Background

We need a new, dedicated ES cluster to hold audit logs. This will be a locked down version similar to the cluster we use for application logs.

## Proposed user journey

N/A

## Approach

Follow the documentation to setup a new elasticsearch cluster that should only be accessible to Cloud Platform members.

We do not want to expire logs on this particular cluster.

If disabling index deletion is straightforward, do that as well, otherwise raise a ticket to address in the next sprint.

## Questions / Assumptions

N/A

## Definition of done

As described above.

## Reference

N/A

**Comment by jasonBirchall** [comment]
Cluster created.

**Comment by jasonBirchall** [comment]
URL for new cluster:
https://kibana-audit.apps.cloud-platform-live-0.k8s.integration.dsd.io/_plugin/kibana

**Comment by jasonBirchall** [comment]
Haven't included log rotation.

**Comment by jasonBirchall** [comment]
Raised `#340 Investigate how to prevent index deletion on AWS ES Audit cluster`
