### ISSUE TITLE
Prepare tech-focused Show and Tell about Cloud Platform

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3081]
## Background

We need to explain Cloud Platform, with a bit of technical depth. This is kicked off by needing to explain it to Dave and Modernization Platform folks, so they can benefit from our learnings and align their platform with ours. In addition, we should also be explaining it to new tech archs so they can push it for their teams. And more generally, developers will also be interested in what it is and how they should work with it.

## Approach

Run up some slides:
* product context - hosting strategy, who is CP for
* bit of history of template deploy
* key tech design decisions - k8s, AWS
* tech architecture
* how to setup a simple site
* support given

Schedule a time to give the talk to MP folks and tech archs.

## Definition of done

- [x] product slides
- [x] tech slides
- [x] schedule MP talk
- [x] schedule tech archs talk

**Comment by leoncarrington** [comment]
David on leave, will move to blocked until back from leave

**Comment by davidread** [comment]
Presentation done for MP and P&A & Central Digital tech archs.

**Comment by davidread** [comment]
Presentation: https://docs.google.com/presentation/d/1XVRbgJXb5Ehd8EgJ1e4uUw5wEJQlG54WpRIHaTbZZ8I/edit#slide=id.gea5fbe5450_0_619
