### ISSUE TITLE
Clearer guidance about namespace-to-namespace traffic

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3082]
## Background

In recent incident we thought we should provide clearer guidance on namespace to namespace traffic - encourage people to use network policy rather than going via the public ingress. And let's advertise this new clearer guidance on on #cloud-platform-update

We already have https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/network-policy.html#network-policies but that assumes you know that the user knows they want something called a Network Policy. So maybe that can be renamed or we need a separate doc that explains, and links to that one.

## Definition of done

- [ ] clear docs on this
- [ ] reviewed
- [ ] advertise it to users

**Comment by AntonyBishop** [comment]
Duplicate
