### ISSUE TITLE
Test serviceaccount module enabling github_repositories to push secrets

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3085]
During migrating namespaces, if the namespaces has github actions setup for the deployment and uses the [terraform serviceaccount](https://github.com/ministryofjustice/cloud-platform-terraform-serviceaccount), the api for live EKS cluster is different from live-1 cluster and not able to pass/change this variable using this module.

Update the module to have another variable for api url and make a new release.

Also, if the users need to create a seperate cd pipeline to just deploy in "live" cluster, when moving the namespace, the github secrets are overwritten. Update the migration guide to list what variables needs to be passed so it doesnot overwrite the existing one.

Definition of done:
- [ ] terraform module updated to support the api as variable
- [ ] Migration guide updated for variables passed when creating new dev pipeline

**Comment by razvan-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/5374
