### ISSUE TITLE
Enable "IP prefixes", for more efficient use of nodes in EKS

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3086]
## Background

We think we should enable the "IP prefixes" feature.

An concern about migrating to EKS and using the AWS CNI is that the number of pods per node is [limited by the IP addresses](https://github.com/ministryofjustice/cloud-platform/blob/main/architecture-decision-record/022-EKS.md#node-instance-types). However this limit is overcome by the new "IP prefixes" feature.

[IP prefixes announcement](https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-virtual-private-cloud-vpc-customers-can-assign-ip-prefixes-ec2-instances/):
> To get started, use the AWS CLI, SDK or Console to assign prefixes to EC2 instance. There is no additional charge to use this feature. For more information about this feature, visit the [VPC documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-prefix-eni.html).

## Definition of done

- [ ] enabled in PR
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] mention our use of this feature in the [ADR](https://github.com/ministryofjustice/cloud-platform/blob/main/architecture-decision-record/022-EKS.md#node-instance-types)

**Comment by davidread** [comment]
> VPC CNI plugin update that takes advantage of EC2 IP Prefixes to increase pods per node limits: https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-vpc-cni-plugin-increases-pods-per-node-limits/

**Comment by AntonyBishop** [comment]
We think this may already be enabled. Check if this is already in place.

**Comment by vijay-veeranki** [comment]
Already done, can be closed
