### ISSUE TITLE
Test new OPA release/fix in EKS cluster 1.19

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3090]
## Background

A new release exists that fixes a number of OPA issues we'd seen in EKS upgrade to 1.19. This should be tested in a new cluster and tested thoroughly. 

## Proposed user journey

Create a new test cluster using EKS 1.19 or upgrade 1.18 to 1.19, then add this [release](https://github.com/ministryofjustice/cloud-platform-terraform-opa/releases) and test, test, TEST!

## Which part of the user docs does this impact

Please ensure the new release contains tests up to or around 100% code coverage.

## Questions / Assumptions

That EKS 1.19 is in working condition before this ticket is attempted.

## Definition of done

- [ ] OPA release is tested and confirmed working
- [ ] All integration tests pass with the new OPA release
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
This is applied in the live EKS cluster, and working without any failures in tests.
