### ISSUE TITLE
Release new version of OPA

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3091]
## Background

There is a fix for OPA in EKS 1.19 that has a new tag and release but is not yet tested. When testing is complete we should create a new release of OPA and ensure the latest tag is used in our live and live-1 infrastructure.

## Approach

Create a new release of OPA, ensure live, manager and live-1 infrastructure are using this version.

## Questions / Assumptions

The new release has been tested in live, live-1 and manager.

## Definition of done

- [ ] new opa release created
- [ ] all live infra is pointing to and using the new release
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
Still to do:
> ensure the latest tag is used in our live and live-1 infrastructure

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1318

**Comment by pwyborn** [comment]
tests on kops test cluster:
```
~/projects/cloud-platform-infrastructure/smoke-tests
```
![Screen Shot 2021-08-09 at 15.30.28.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/c70aae70-8a5f-4f7b-b495-271272c384bb)
