### ISSUE TITLE
Upgrade live EKS cluster to 1.19

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3094]
## Background

We're currently using 1.18 and have identified that we need to upgrade to 1.19 before performing the user migration.

## Proposed user journey

Using the technique outlined in this [document](https://runbooks.cloud-platform.service.justice.gov.uk/upgrade-eks-cluster.html#upgrade-eks-cluster-s), upgrade the cluster to the latest version of 1.19.x.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Done
