### ISSUE TITLE
Test upgrade of release 1.0 ingress controller

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3095]
## Background

We will eventually require nginx ingress controller 1.0 in EKS and should make effort to test the release (which warns of breaking changes).

## Proposed user journey

Use release 1.0 [here](https://github.com/kubernetes/ingress-nginx/releases) to upgrade a separate ingress controller in live. 

A chart is also available at https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx

Observe and report:
- how difficult this was
- what breaks
- if there are any changes required pre and post install.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
waiting for a working chart, draft PR in https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/pull/22/files

**Comment by razvan-moj** [comment]
chart is now available in the upstream repo, closed PR mentioned above

**Comment by AntonyBishop** [comment]
Stale story.
