### ISSUE TITLE
Host SSH session audit logs

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#310]
## Background

Depends on #308 

## Proposed user journey

We need to have a record of what a user does on an SSH session on the hosts of a cluster (including the bastion).

## Approach

Investigate ways to achieve this, preferably using existing Linux capabilities.
The audit logs should end up in the audit log ElasticSearch cluster.

## Questions / Assumptions

N/A

## Definition of done

As described above.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Are we saying we want to record users bash sessions on either the bastion or nodes?

**Comment by jasonBirchall** [comment]
If that is the case then we can amend the /etc/bashrc file with ` PROMPT_COMMAND='history -a >(logger -t "$USER[$PWD] $SSH_CONNECTION")'`

Please see this document for further info:
http://ashok-linux-tips.blogspot.com/2012/04/log-commands-executed-by-all-users.html

**Comment by jasonBirchall** [comment]
`grep 'sshd.' /var/log/auth.log` lets you view all stdout events from sshd.

**Comment by alkar** [comment]
@jasonBirchall this issue totally fell through the cracks. I think we definitely want to log when users ssh on a node, IIRC from our discussions, log the entire session too. And yes, we'd need to setup fluentd on the bastion as well. Do we want to re-open this issue?

**Comment by lukaszraczylo** [comment]
I can suggest going the teleport way ( https://github.com/gravitational/teleport ) and record all the SSH sessions together with kubectl execution which seems to be a reasonable feature.

**Comment by digitalronin** [comment]
Audit logs came up yesterday when I was talking to the security team.

Something like teleport definitely seems worth a spike, to see if we like it.

**Comment by AntonyBishop** [comment]
Include this story in security orientated sprint.

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
