### ISSUE TITLE
Longer host names - add guidance on how to register (64+ chars)

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3109]
Some users have had trouble with custom domains that are over 63 or 64 characters long, seeing an error at the point where the certificate is generated by Lets Encrypt. It seems you can get longer domain names, but the thing you differently is to put the long name in the SAN field, and in the usual CN field you need to put a dummy value (something is required). We should document how to achieve this in CP, perhaps in the [Custom Domain guide](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/custom-domain-cert.html#obtaining-a-certificate). This would reduce questions from users, and support our policy against using abbreviations in (domain) names.

## Examples of questions on this

The question was asked in April 2019, and @razvan-moj worked on a solution: https://mojdt.slack.com/archives/C57UPMZLY/p1556109219005600

There was a question March 2020 about it: https://mojdt.slack.com/archives/C57UPMZLY/p1589196150137400

There was another user trying to work around in March 2021:
> The original non production domains of acquisitive-crime.(dev|test|preprod).electronic-monitoring.service.justice.gov.uk were too long for AWS ACM, see AWS [ACM Docs](https://docs.aws.amazon.com/acm/latest/APIReference/API_RequestCertificate.html#API_RequestCertificate_RequestParameters) 
[PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/4532)

## Background

@jakemulley explained the use of Subject Alternate Names field and CN field::
> [RFC2818](https://tools.ietf.org/html/rfc2818#section-3.1) deprecated CommonName in SSL certs back in May 2000, but required it as a fallback for Subject Alternate Names. In 2011, [RFC6125](https://tools.ietf.org/html/rfc6125#section-6.4.4) removed that requirement. However, it wasn’t until April 2017 that a major browser (Chrome) stopped using Common Name for validation :sweat_smile: So, you can legitimately use SAN to get around the 64 character requirement… if you also set a CommonName to something like cloud-platform.service.justice.gov.uk :sweat_smile:

**Comment by davidread** [comment]
See related work for MP: https://github.com/ministryofjustice/modernisation-platform/issues/767

**Comment by AntonyBishop** [comment]
Done
