### ISSUE TITLE
Investigate why S3 changes result in a policy change

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3111]
## Background

While approving PR's I noticed that a trivial S3 bucket change resulted in a large terraform plan whereby multiple S3 bucket policies were amended. After digging into a few more PR's it became evident that this was occurring on all S3 changes and has been for some time.

## Proposed user journey

Investigate the cause of the policy changes.

## Approach

This may have to be a trial and error approach as I don't know where to start. I did notice that the tools image does pin the AWS provider but this seems to be ignored in the plan pipeline.

**Comment by vijay-veeranki** [comment]
Fixed both s3 and RDS policy changes on every run using local.
