### ISSUE TITLE
Request a new alert route in Alertmanager

### ISSUE THREAD

**Issue by mayowaadeniyi** [ministryofjustice/cloud-platform#3112]
## Service name

CLA Backend

## Service environment

- [x] Staging
- [x] Prod / Production
- [x] Training

## Contact person

Mayowa, @Mayowa Adeniyi, mayowa.adeniyi@digital.justice.gov.uk

## Reason for creating ticket

I created this issue in response to following the cloud platforms user guide for [creating your own custom alerts](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#prerequisites). Step 3 instructed I create this ticket to `request a new alert route in Alertmanager`.

Here is the required information:

**Namespace**: laa-cla-backend-staging, laa-cla-backend-training, laa-cla-backend-production
**Team name**: laa-get-access
**Application name**: Civil Legal Advice Case Handling System
**Slack channel**: cla-alerts
**Kubernetes secret name where the webhook url is stored**: slack-webhook 
**Severity level (warning/information)**: Warning

**Comment by vijay-veeranki** [comment]
severity = "laa-get-access"
