### ISSUE TITLE
Make a decision on how we will manage old TLS

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3115]
**Background**

We have a few applications which have to support deprecated TLS versions because their users are unable to use modern browsers. To support these applications, we have enabled support for old versions of TLS on the default ingress controller. But this means all hosted services can now be accessed using deprecated TLS versions. This is an unnecessary security risk.

We have had many thoughts on whether we should or shouldn't support old TLS versions. We need to do something that will reduce this risk.

**Approach**

We need to agree on our roadmap for deprecating old TLS. Last time we discussed the possibility of creating a new default ingress and migration users to it. The new ingress will not support old TLS and any services dependant on legacy TLS will need to remain on the "legacy" ingress. 

How will we make this happen?

**Definition of Done**

- [ ] We have an agreed plan for how we will deal with this risk.
- [ ] Decision documented in an ADR.

**Comment by jasonBirchall** [comment]
Also raised here.
https://mojdt.slack.com/archives/C57UPMZLY/p1636013424184100

**Comment by AntonyBishop** [comment]
Covered by move to Ingress v1
