### ISSUE TITLE
FIREBREAK: run tfsec in environments repo

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3119]
Let's try running tfsec, checkov and tflint on the environments repo, and see if it is helpful. Maybe we or teams can learn something about terraform best practices and spot issues. Consider whether we should roll it out as an advisor or requirement for merging environment PRs.

## Background

tfsec, checkov and tflint do static analysis of terraform.

MOJ now has a GitHub Action that can run tfsec and checkov and tflint across multiple terraform folders in a repo, and provide results only for the folders that are changed in the PR, so errors in one team's terraform would not show up in other teams' PRs. https://github.com/ministryofjustice/github-actions/pull/59

This work follows on from @jasonBirchall 's [exploration of tfsec on the infrastructure repo](https://github.com/ministryofjustice/cloud-platform/issues/2502), where he decided it might be more helpful for environments repo.

## Definition of done

- [x] Firebreak finding documented appropriately
- [x] Demo completed
- [x] Decision made on whether to progress Firebreak work
- [x] Firebreak next step Issues created
- [x] New Issues referenced in this story before closure

**Comment by pwyborn** [comment]
https://docs.google.com/presentation/d/1-uo9RHSrCBGMM6F-aaBShvJw9jXzLdI3/edit#slide=id.p1

**Comment by pwyborn** [comment]
Decision made at demo to:

- fix or look at our "High" and "Critical" severity issues in our modules first (may well fix anything it would raise for the users). Please see [my findings spreadsheet](https://docs.google.com/spreadsheets/d/1cwzJczyu0WrmUpLozSfEZa2rj3PUUoRrayU2msZiz50/edit#gid=1088265046&fvid=138610442) and filter for the "High" and Critical" ones

- Once this is complete:

- - 
```
Brew install tfsec
```

- - rerun tfsec in cloud-platform-enviroments/namespaces/live.cloud-platform.service.justice.gov.uk to see potential results for users after our one looked at
```
tfsec -m CRITICAL  --force-all-dirs  --concise-output -f csv
```

-  - then to create an github action based on cloud-platform-environments:

[the github action](https://github.com/ministryofjustice/github-actions/tree/main/terraform-static-analysis)
and with reference to:
[how it has been put into action by the modernisation platform](https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/.github/workflows/format-code.yml)
