### ISSUE TITLE
Fix sqs module Maximum policy size of 2048 bytes exceeded error

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3121]
Users are facing the below error, when they use the same I am user for multiple queues, this will create an inline policy for each sqs module and use the single I am user.

Error: Error putting IAM user policy xxxxx: LimitExceeded: Maximum policy size of 2048 bytes exceeded for user xxxxxx

https://github.com/ministryofjustice/cloud-platform-terraform-sqs/blob/main/main.tf#L118-L134

One option you may want to consider is to combine inline policies, instead of creating multiple policies, when user use single user for all the queues, this will reduce the char bytes used but still be a problem when they use 20+ queues.
```
 {
  "Version": "2012-10-17",
  "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "sqs:*",
            "Resource": [
                "arn:aws:sqs:eu-west-2:754256621582:x",
                "arn:aws:sqs:eu-west-2:754256621582:y",
                "arn:aws:sqs:eu-west-2:754256621582:z"
             ]
        }
  ]
}
```

Iam support team suggestion:
consider creating more granular roles or combining permissions in fewer IAM policies to meet your requirements!

**Comment by AntonyBishop** [comment]
Closed due to age of story
