### ISSUE TITLE
Make authentication to the Cloud Platform effortless

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3127]
## Background

Authentication the the cluster is difficult. Rotation of credentials is difficult (and disruptive). 

To address this problems we want to make authentication to the cluster as effortless as possible.

This may mean that users have short-lived credentials, however re-authentication should be trivial.

## Proposed user journey

One-click authentication to the platform or auth via the CLI

## Approach

TBC

## Which part of the user docs does this impact

Replace - https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/kubectl-config.html#how-to-use-kubectl-to-connect-to-the-cluster

## Questions / Assumptions

- Is this an EPIC?
- How do we do this?
- Where are we already doing this?

## Definition of done

TBC

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
We should just reduce it from 30 days to 1 day. I think there is a misunderstanding that users had to relogin via kuberos after 30 days, but the refresh token renews the kubeconfig seamlessly, if the GitHub user is still in the org.

**Comment by davidread** [comment]
Maybe we can use AWS SSO to get authenticated too?

**Comment by razvan-moj** [comment]
tried 
https://openunison.github.io/ - complex and docs too poor, solution doesn't seem ready for prime time yet
and
https://goteleport.com/ - complex, good docs, looks promising but the open source version only allows Github SSO with static mappings, dynamic OIDC mappings are a paid feature with undisclosed price
this topic deserves re-visiting

**Comment by jasonBirchall** [comment]
Another product. CAVEAT: I've only read the blurb here and should be investigated further.

https://infrahq.com/
