### ISSUE TITLE
Request new integration ID for Pingdom Slack notification for CCCD

### ISSUE THREAD

**Issue by jrmhaig** [ministryofjustice/cloud-platform#3136]
## Service name

Claim for Crime Court Defence (CCCD)

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

I am following this guide and it says to create a ticket to get an integration ID for pingdom/slack integration https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#adding-slack-notification

Team name: Claim for Payment
Application name: CCCD
Slack channel: `laa-cccd-alerts`

## Problem description

Pingdom currently sends alerts for CCCD to the `laa-get-paid-alerts` channel (integration ID 94703). The Get Paid team has split and so the alerts for different apps need to go to separate channels. Can we please have a new integration ID for the new alert channel `laa-cccd-alerts`.

## Contact person

* Joe Haig
* `@Joe Haig` on slack
* joseph.haig@digital.justice.gov.uk

**Comment by vijay-veeranki** [comment]
integration=116115
