### ISSUE TITLE
Spike blackbox exporter

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#3142]
The blackbox exporter allows blackbox probing of endpoints over HTTP, HTTPS, DNS, TCP and ICMP.

Use Cases:
Detecting certificate expiration.
Analyzing the latency of specific targets and paths of services running in the same cluster.
Detecting endpoint failures.
Monitoring latency and reachability of an external endpoint like third services.

https://github.com/prometheus/blackbox_exporter

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/16G-TLgYSdFEbxx2iZSQNqYBcVVdgyG70XClwtYDkD6g/edit#heading=h.csnn46q0o8i6

**Comment by vijay-veeranki** [comment]
Created this ticket
https://github.com/ministryofjustice/cloud-platform/issues/3554
