### ISSUE TITLE
Look for alternative to github.com/dgrijalva/jwt-go

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3143]
The package has github.com/dgrijalva/jwt-go has issues and hence need to move away from using the package. Look for alternatives

More details in here: https://github.com/ministryofjustice/cloud-platform-sensitive/issues/4

## Definition of done

- [ ] cli amended to use alternative solution for the package 
- [ ] readme has been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-cli/pull/107
