### ISSUE TITLE
Monitor the Elasticsearch cluster in live and test.

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#315]
Now the test, audit and prod elasticsearch cluster exist, they need to be monitored. This ticket is to create a triggered alert for cluster metrics like `cluster = red`.

As a starting point, use the aws metrics guide but implement it in prometheus:  https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/es-metricscollected.html

**Comment by sablumiah** [comment]
Monitoring has been added to all 3 ES clusters in Cloudwatch on platform-intergrations account. 
 Live has high and low priority alarms, test and audit alarms are all low priority

**Comment by sablumiah** [comment]
cloud-platform-test | nodes-minimum<2-for-one-day
Nodes < 2 for 120 datapoints within 2 hours

cloud-platform-test | cluster-status-is-YELLOW
ClusterStatus.yellow >= 1 for 1 datapoints within 1 minute

cloud-platform-test | cluster-status-is-RED
ClusterStatus.red >= 1 for 1 datapoints within 1 minute

cloud-platform-test | free-storage-space<10GB
FreeStorageSpace <= 10,000 for 1 datapoints within 1 minute

cloud-platform-test | write-requests-being-blocked
ClusterIndexWritesBlocked >= 1 for 1 datapoints within 1 minute

cloud-platform-test | cpu-util-high
CPUUtilization >= 80 for 3 datapoints within 45 minutes
