### ISSUE TITLE
Add encryption to the S3 bucket terraform script

### ISSUE THREAD

**Issue by colinbruce** [ministryofjustice/cloud-platform#3150]
## Service name

LAA HMRC Interface

## Service environment

- [x] Dev / Development - for now
- [x] Staging - for now
- [ ] Prod / Production
- [ ] Other

## Impact on the service

We are unable to deliver this service without encryption being enabled on the s3 buckets

We are aiming for a go-live in January and this will impact our ability to make that, externally set, deadline

## Problem description

The service will be executing long-running API queries against HMRC endpoints, because it is a HATEOS system we cannot guarantee response times and therefore we will have to store documents containing PII until the requesting service obtains the final output

One of the requirements from the assurance team is that the data is encrypted at rest to prevent browsing of data 

The files will be expired after a day to ensure that they are not left on the S3 bucket indefinitely

Currently we are unable to set encryption via the terraform module provided

## Contact person

Colin Bruce / @colinbruce / colin.bruce@digital.justice.gov.uk

**Comment by vijay-veeranki** [comment]
Our s3  module is encrypted at rest by default using AES256. https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket/blob/main/main.tf#L103-L109
All our s3 buckets are encrypted with that method. SSE-s3. The objects are encrypted using server-side encryption using Amazon S3-managed keys (SSE-S3)
