### ISSUE TITLE
Post HOODAW data to Elasticsearch 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3152]
## Background

Currently the data needed for the HOODAW reports page are posted via the API from a set of cronjobs. Each cronjobs run the app, use certain format of json and post to the API. This is consumed by the frontend which stores the data in dynamoDB and also fetched for displaying with sinatra erb templates.
This is time consuming when a new report page needs adding to the HOODAW. 

As part of the finding alternative for frontend, 
https://docs.google.com/document/d/1htIguNth7NRFwgdt8oD1jrQsRwEf-0DZJA4g-Gs14HA/edit?usp=sharing

Investigate if the data be posted to elasticsearch and get the data be searchable with separate index
Configure ES to build a dashboard for each page of the HOODAW report.

## Questions / Assumptions
Does it have to be on seperate elasticsearch or create another index on cluster wide ES?

Can the app display this information as logs and be scrapped by fluentbit?

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by AntonyBishop** [comment]
Aged out
