### ISSUE TITLE
FIREBREAK: Spike using Hugo Site Generator Instead of Sinatra

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3155]
## Background

We currently use the Sinatra framework to display data from the Hoodaw reports. The team have raised some concerns regarding the maintenance and sustainability of supporting things in Ruby. 

Create a Hugo frontend that will take json data and display it in a nice format. Pick a report to and create a prood of concept in Hugo to display the data.

## Questions / Assumptions

- That Hugo can populate something like a table from json data.

## Definition of done

- [x] Firebreak finding documented appropriately
- [x] Demo completed
- [x] Decision made on whether to progress Firebreak work
- [x] Firebreak next step Issues created
- [x] New Issues referenced in this story before closure

**Comment by poornima-krishnasamy** [comment]
https://docs.google.com/document/d/1-__EErF6v0sQyNuapRhLT5sUXhW2PiaanXWBEW3NReM/edit?usp=sharing

**Comment by poornima-krishnasamy** [comment]
Ticket for next steps: https://github.com/ministryofjustice/cloud-platform/issues/3355
