### ISSUE TITLE
Kops update monitoring group node to use the latest monitoring module

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3156]
This is related to [ticket](https://github.com/ministryofjustice/cloud-platform/issues/2979) 

This [change](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/blob/main/templates/prometheus-operator.yaml.tpl#L473-L476) created an affinity key to use for both EKS and KOPS.

For kops to use the latest monitoring module(1.7.6), kops monitoring node group should have a new tag created [here](https://github.com/ministryofjustice/cloud-platform-terraform-kops/blob/main/templates/kops.yaml.tpl#L407-L410) 

tag to be added:
cloud-platform.justice.gov.uk/monitoring-ng: true.

Once the tag is applied to kops, apply the latest module(1.7.6) of monitoring to kops components.

This will enable affinity.

    ## Assign custom affinity rules to the prometheus instance
    ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

AC:

New tags were created to kops and the latest monitoring module applied to kops.
Promotheus still shows up in monitoring node group

**Comment by poornima-krishnasamy** [comment]
There is one more release made for the monitoring module. https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/1.7.7. This ticket needs to be completed before 1.7.7 can go on the kops clusters.

**Comment by davidread** [comment]
This is about making live-1 consistent with live.
