### ISSUE TITLE
Convert Auth0 "rules" to "actions" add-github-teams-to-oidc-group-claim

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3157]
We have 3 little [Auth0 "rules"](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/global-resources/resources/auth0-rules) that need converting to "actions". The driver for this is the deprecation of the NodeJS version, and switch-off by Auth0 on **22 Feb 2022** - see Auth0 guide [Migrate Rules and Hooks to Actions](https://auth0.com/docs/product-lifecycle/deprecations-and-migrations/migrate-to-actions).

Convert add-github-teams-to-oidc-group-claim rule to action

## Background

These Auth0 rules are used when a tenant authenticates with the cluster (Kuberos). They are needed to link up [GitHub, which we use as our Identity Provider](https://github.com/ministryofjustice/cloud-platform/blob/main/architecture-decision-record/006-Use-github-as-user-directory.md) to Kubernetes RBAC.
* allow-github-orgs - ensures the user is part of our GitHub org, otherwise they are prevented from authenticated
* add-github-teams-to-oidc-group-claim - the OIDC group claim is [used by RBAC to grant authz to namespaces](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/check-id-token.html#checking-the-github-groups-in-your-id-token)
* add-github-teams-to-saml-mappings - allows CP team to log in to AWS with their Github identity - Actually this probably isn't needed, as [we're moving to SSO instead](https://github.com/ministryofjustice/cloud-platform/blob/main/architecture-decision-record/024-SSO-for-CP-Team-to-access-AWS.md)

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Needs to be brought into sprint as this is happening in the next couple of weeks.

**Comment by vijay-veeranki** [comment]
From this message, it shows that it is not getting depreciated as yet
https://community.auth0.com/t/guide-migrate-your-custom-rules-to-auth0-actions/68915/4

**Comment by vijay-veeranki** [comment]
WIP branch:
https://github.com/ministryofjustice/cloud-platform-infrastructure/compare/auth0-actions?expand=1

Rule to action conversion for "dd-github-teams-to-oidc-group-claim" is working as expected. This is still a work in progress to convert all the required filed though code.

**Comment by vijay-veeranki** [comment]
Moved back to This sprint, will work on it when I am back from leave.
