### ISSUE TITLE
Create CLI 'migrate' command

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3158]
Create CLI 'migrate' command that makes changes to environments repo for a namespace:
* copy namespace dir
* Elasticsearch module
* Cross account IAM roles

Create CLI 'migrate-check' command. Checks on the k8s cluster:
* warn if the ingress resource (on the cluster) is not fixed.
* warn if the S3 change? is not applied

## Definition of done

- [x] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
@mogaal I think you started this?

**Comment by mogaal** [comment]
@davidread yes I did, but this ticket is massive. What I did/started was just with the first item: "copy namespace dir". This ticket has to be split

**Comment by davidread** [comment]
Mostly done now. All points are covered, apart from implementing "Cross account IAM roles"
