### ISSUE TITLE
Update documentation for ingress api change (v1beta1 - Networking) and annotation

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3161]
## Background

We are improving the migration plan.

Update documentation for ingress api change (v1beta1 - Networking) and annotation

## Approach

Update in runbooks, CLI template, and User guide

Update 

## Which part of the user docs does this impact

Various

## Definition of done

- [ ] runbooks updated
- [ ] CLI template updated
- [ ] User Guide updated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
We don't have cli template for ingress, user guide and run-book updated.
