### ISSUE TITLE
Investigate ttlSecondsAfterFinished

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3168]
## Background

- How many users use the flag?
- What is the maximum limit which we need to set for failedJobHistoryLimit and SuccessfulJobHistoryLimit so the users pods related to successful and failed jobs are not deleted earlier that ttlSecondsAfterFinished time

## Approach

Figure out answers to these questions so that we can make a decision about what to do about ttlSecondsAfterFinished 

## Definition of done

- [ ] We have answers to all the questions
- [ ] Findings discussed
- [ ] Decision on how to proceed made

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
Needed for the few teams using Jobs, e.g. Money for Prisoners

**Comment by poornima-krishnasamy** [comment]
40 namespaces use this flag
`kubectl get cronjob -A -ojson | jq -r '.items[] | "\(.metadata.name),\(.metadata.namespace),\(.spec.jobTemplate.spec.template.spec.containers[0].name),\(.spec.jobTemplate.spec.ttlSecondsAfterFinished)"'`

The maximum duration that was set is 2.8 days

**Comment by poornima-krishnasamy** [comment]
2. There is no settings to increase the cluster default values of failedJobHistoryLimit and SuccessfulJobHistoryLimit.

Ideas: 
Create github-action to check if a namespace has job which has ttlSecondsAfterFinished set. Alert when migrating namespace
Add Cli command to check the same and give instructions on how to modify
