### ISSUE TITLE
FIREBREAK: test Stackdriver

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#3169]
## Background

ES is painful to work with for logs, the topic has been discussed many times.

## Questions / Assumptions

We have a trial GCP account and some ballpark figure of how much we can spend

## Definition of done

run a plausible test with a separate cluster
 - ingest logs from both ingress and apps
 - try to estimate the cost
 - bonus points: alerts?

**Comment by AntonyBishop** [comment]
Duplicate
