### ISSUE TITLE
etcd v3

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#317]
## Proposed user journey

migrate to `etcd` v3

## Definition of done

- [ ] must compile
- [ ] must pass tests
- [ ] must address all the steps of user journey

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
From https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md, seems this only makes sense for new clusters, as "no upgrade path exists for migrating from v2 to v3 so DO NOT try to enable this on a v2 running cluster"

**Comment by jasonBirchall** [comment]
As discussed moving this to backlog to be done when live-1 is ready.
