### ISSUE TITLE
Upgrade prometheus-operator component to 18.0.5

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3171]
## Background

The hoodaw application has identified this component as out of date.

src: https://reports.cloud-platform.service.justice.gov.uk/helm_whatup

## Proposed user journey

Identify which upgrade path to take, test it using a test cluster and environment.

## Which part of the user docs does this impact

If the install requires extreme work, ensure the user documentation is still relevant.

## Questions / Assumptions

The upgrade path is smooth and doesn't require a complete rework.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

**Comment by AntonyBishop** [comment]
Check that this is latest version.

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1461
