### ISSUE TITLE
Upgrade thanos component to latest

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3172]
## Background

The hoodaw application has identified this component as out of date.

src: https://reports.cloud-platform.service.justice.gov.uk/helm_whatup

We are getting alerts related to volume filling up, look into increasing the volume
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/blob/main/templates/thanos-values.yaml.tpl#L48

## Proposed user journey

Identify which upgrade path to take, test it using a test cluster and environment.

## Which part of the user docs does this impact

If the install requires extreme work, ensure the user documentation is still relevant.

## Questions / Assumptions

The upgrade path is smooth and doesn't require a complete rework.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

**Comment by vijay-veeranki** [comment]
This is related:
https://github.com/ministryofjustice/cloud-platform/issues/3438

**Comment by razvan-moj** [comment]
done
