### ISSUE TITLE
FIREBREAK: KubeLinter

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3177]
* Does it offer useful alerts or is it just noise?
* Can we use KubeLinter to scan YAML/Helm charts in CP?
* Can we get service teams to use it too?

## Background

In a [RedHat survey](https://cloud.redhat.com/blog/top-open-source-kubernetes-security-tools-of-2021), KubeLinter was the top security tool for k8s, but I don't think we've evaluated it before. It came above OPA, kube-bench and kube-hunter, which we've already adopted or at least tried.

>  KubeLinter is a static analysis tool that scans YAML files and Helm charts. KubeLinter analyzes Kubernetes YAML files and Helm charts and checks them against a variety of best practices, with a focus on production readiness and security.
> 
> KubeLinter ships with default checks, designed to give you useful information about your Kubernetes YAML files and Helm charts. This helps teams check early and often for security misconfigurations and DevOps best practices. Some common examples of these include running containers as a non-root user, enforcing least privilege, and storing sensitive information only in secrets.

## Definition of done

- [ ] Firebreak finding documented in this ticket or linked from here
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by sablumiah** [comment]
I think this would be a good addition to our offering, we can use it with GHA for users to make the PRs are to a minimum standard. 

However, due to the project being quite early, there is a warning `KubeLinter is at an early stage of development. There may be breaking changes in the future to the command usage, flags, and configuration file formats`
We should look back at this project when its more stable .

**Comment by davidread** [comment]
I agree about being cautious, seeing this message, although I'd just balance it against it being the most used tool in the RedHat survey, suggesting it has adoption. If the message is just about the risk of breaking changes in the usage, then that doesn't seem like a big deal, but maybe there are other things that make it unsuitable for our use. Maybe still worth evaluating, but with caution.
