### ISSUE TITLE
Run Kube-bench security check on new cluster

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3178]
Let's run kube-bench on our new EKS cluster, to check for any config gotchas, now we're readying it for production envirionments.

Note kube-bench has specific settings for EKS: [Running kube-bench in an EKS cluster](https://github.com/aquasecurity/kube-bench/blob/main/docs/running.md#running-in-an-eks-cluster)

Please put a copy of the report in our security folder: https://drive.google.com/drive/u/0/folders/1VKjkbOutRihyhIMvbLTAm5L7ERS7yFo6 and with any comments on the findings, and let me know, so I can review any concerns.

**FYI - https://docs.google.com/document/d/1aB0rwj7lYw1pB_f0rZZK8KxXkcgAyBtkmM4Ld2Aqx2U/edit?usp=sharing**

## Definition of done

- [ ] kube-bench report stored in Security folder
- [ ] initial comments on findings written and included with the report
- [ ] @davidread reviews findings

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1DGJlf-AU3UKMeHL7E27Et7pLwaZRWQPyvKz3WBapQJc/edit

**Comment by davidread** [comment]
Thanks @vijay-veeranki. I've reviewed the findings too, added some comments in the doc, and there are no concerns.
