### ISSUE TITLE
Cannot deploy fala application to staging environment

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#318]
## Service name

https://staging.fala.dsd.io/

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Cannot deploy the application to staging server(s), cannot test the functionality. I assume the problem prevents the application to be deployed to production as well.

Related to #305.

## Problem description

https://ci.service.dsd.io/job/DEPLOY-fala/45/

## Contact person

`@David Lantos` on Slack, @sldblog here

**Comment by ushkarev** [comment]
i suspect it's the same issue as https://github.com/ministryofjustice/cloud-platform/issues/300

**Comment by sldblog** [comment]
Yes, it seems #300 was the initial cause.
Now it seems that `pip install -r ./requirements-deploy.txt --upgrade` is not sufficient to install all dependencies. (https://ci.service.dsd.io/job/DEPLOY-fala/46/console)

**Comment by ushkarev** [comment]
there's a mismatch in `botocore` dependencies. one option is to try specifying an older `awscli`

**Comment by sldblog** [comment]
It seems `awscli` is not specified at all in https://github.com/ministryofjustice/fala-deploy/blob/master/requirements-deploy.txt

**Comment by ushkarev** [comment]
yeah, but you can see from your deploy job log that it's an _unpinned_ dependency of `bootstrap-salt`. if you specify an older version directly in your requirements, you should be ok

**Comment by sldblog** [comment]
I am happy to do that, but I would like to understand the knock-on effect. Do we need to pin it in every deploy repo now?

**Comment by ushkarev** [comment]
no idea :)
in my local template deploy repo for mtp, i've got this installed and it all works happily
```
botocore                           1.10.32
awscli                             1.15.32
bootstrap-cfn                      1.5.3 (no longer exists, but 1.5.4 has the same dependencies)
bootstrap-salt                     1.3.6 
```
…your situation might be different!

**Comment by sldblog** [comment]
https://ci.service.dsd.io/job/DEPLOY-fala/50/ is 🍏 with https://github.com/ministryofjustice/fala-deploy/pull/27 🎉 

I'll keep an eye if we need to do the same for other deployments.
