### ISSUE TITLE
Run Kube-hunter security check on new cluster

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3180]
Let's run kube-hunter on our new EKS cluster, to check for any security config gotchas, now we're readying it for production environments.

I've got some ideas of what sort of tests we might run with it, in: [Kube-hunter security scanning doc](https://docs.google.com/document/d/1KPtpR4UL-4ZHjfm9rMKMK4M3z3BO6c6zGejJrgPIxTQ/edit#heading=h.gi5x61i99ggo) But use your judgement as you learn what's feasible and useful.

Please record in that same doc:
* what tests you do
* test results
* any comments on the findings

Then let @davidread know, to review any concerns.

## Definition of done

- [ ] Google doc shows the tests done
- [ ] Google doc shows the test results
- [ ] Google doc shows initial comments on findings
- [ ] @davidread reviews findings

**Comment by davidread** [comment]
This is a one-off run

**Comment by razvan-moj** [comment]
updated doc with scan results and comments; created https://github.com/ministryofjustice/cloud-platform/issues/3489 as follow-up
