### ISSUE TITLE
Tidy docs

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3182]
We can make some useful improvements to our User Guidance. Hopefully we can make some basic improvements in lieu of a tech writer / content designer.

Here are some ideas. Worth looking for opportunities to make similar improvements during the course of this work.

## Information Architecture
The [index page](https://user-guide.cloud-platform.service.justice.gov.uk/) could be tidied into clearer sections. I quite like this model: https://documentation.divio.com/ (and see [discussion](https://news.ycombinator.com/item?id=26002656))

Also the names of pages could be improved. e.g. I'm looking for a page on how to deploy my app. Three candidates:
* [Deploying to the Cloud Platform](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/concepts/deploying.html) looks promising. I miss that it is in the 'concept' section - headline blindness is a thing. Then I read it and it's much higher level than the title suggests. Maybe it needs a name like "Deployment concepts on the Cloud Platform"?
* [Deploy your first Hello World application](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/helloworld-app-deploy.html#deploying-a-39-hello-world-39-application-to-the-cloud-platform) is what I was looking for.
* [Deploying with Helm and CircleCI](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/using-circleci-for-continuous-deployment.html#setting-up-circleci) is much narrower (and deeper) in topic than the previous article. The page title rather needs to reflect that somehow. Maybe the previous one needs to be called a 'tutorial in deployment' and this more of a 'Using Helm and CircleCI in your deployment'.

## Consistency

e.g. how we indicate bits we want the user to substitute for their own values. Let's agree on your/my/name e.g. https://github.com/ministryofjustice/cloud-platform-user-guide/pull/796/files and whether it is formatted $namespace, NAMESPACE, <namespace> or [namespace]

- [ ] IA - Review and improve
- [ ] Consistency - Review and improve

**Comment by AntonyBishop** [comment]
Some restructuring completed. Will carry out some further UR following these changes.
