### ISSUE TITLE
Investigate how thanos querier can be made available to query metric for longer period

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3185]
## Background
Currently thanos query was able to query 1w before data. This is due to the configuration here:
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/blob/main/templates/thanos-values.yaml.tpl#L21

Update the values so thanos querier can be used to query longer period data. i.e. 6 months

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/prometheus.html#thanos

## Questions / Assumptions

Will the storegateway need more memory and how much?
https://mojdt.slack.com/archives/C514ETYJX/p1631018566234900?thread_ts=1631018404.234800&cid=C514ETYJX

## Definition of done

- [ ] Thanos queries can display data when quering for longer period data
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
It's some config thing. When @poornima-krishnasamy ran it locally it worked for longer periods.

We used Thanos when we investigated the Prometheus incident.
