### ISSUE TITLE
Add an alert when prometheus container memory usage reaches 90% of memory limit 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3186]
## Background

The prometheus container has a resource limit set here: https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/blob/main/templates/prometheus-operator.yaml.tpl#L406.
Set an alert when the usage reaches 90% of the limit

## Definition of done

- [ ] Alert set and tested for prometheus memory usage
- [ ] readme has been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
After incident https://runbooks.cloud-platform.service.justice.gov.uk/incident-log.html#incident-on-2021-09-04-22-05-pingdom-check-prometheus-cloud-platform-healthcheck-is-down
