### ISSUE TITLE
User guide to access Elastic Search cloud-watch logs from log group 

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3187]
The elastic search module has an option to enable logs where logs are captured in CloudWatch Logs under the log group.

```
Set up Search slow logs
Search slow logs provide insights into how fast or slow queries and fetches are performing. Once enabled, your logs are captured in CloudWatch Logs under the log group you specify. Standard CloudWatch charges will apply.

Set up Index slow logs
Index slow logs provide insights into the indexing process. Once enabled, your logs are captured in CloudWatch Logs under the log group you specify. Standard CloudWatch charges will apply.

Set up Error logs
Elasticsearch error logs provide access to information about errors and warnings raised during the operation of the service and can be useful for troubleshooting. Once enabled, your logs are captured in CloudWatch Logs under the log group you specify. Standard CloudWatch charges will apply.
```

Update user guide on how users can access cloud-watch logs using awscli. This may need to update our ES module to provide access to query cloud-watch.
https://docs.aws.amazon.com/cli/latest/reference/logs/get-log-events.html

Another option is to export log data to Amazon S3.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/S3ExportTasks.html.

Figure out the best option for users to access logs and update the user guide.
https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-logs-retrieve-data/

**Comment by pwyborn** [comment]
Please see question to AWS:
https://mojdt.slack.com/archives/C7ZUPR91R/p1638352168014900

**Comment by pwyborn** [comment]
The command:
```
aws logs describe-log-groups
```
Will list log-groups
```
aws logs describe-log-streams --log-group-name
```
Will give a list of log-streams

```
aws logs get-log-events --log-group-name  --log-stream-name 
```
Will  list log-events

**Comment by pwyborn** [comment]
Examples here:
[Using identity-based policies (IAM policies) for CloudWatch Logs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-identity-based-access-control-cwl.html):

Possibly example 3]-ALLOW ACCESS TO ONE LOG GROUP (but with read-only):
Something like
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "logs:Describe*",
                "logs:Get*",
                "logs:List*",
                "logs:StartQuery",
                "logs:StopQuery",
                "logs:TestMetricFilter",
                "logs:FilterLogEvents"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:logs:us-west-2:123456789012:log-group:SampleLogGroupName:*"
        }
    ]
}
```
