### ISSUE TITLE
AWS DMS migration

### ISSUE THREAD

**Issue by markreesmoj** [ministryofjustice/cloud-platform#3188]
## Service name

Workload measurement

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We cannot go live without migrating data

## Problem description

We are bringing a third party app in house.

First problem

We have two databases to migrate from Azure SQL to Postgres RDS. We have created the schemas in RDS so need to move the data as a one-off operation. We have access to the Azure databases which contain archived data. The data will not change in the coming weeks so this is not time critical and can be done once

Second problem

A third database needs to be replicated from Azure SQL to Postgres RDS (at least) daily. This is live data which is updating during the working day. We want to run our app side by side with the live app and verify that the in house app is working in exactly the same way. In order to do this we need the latest data to be imported. It would be sufficient for this to happen every day before 5am, but if more frequent replication is possible that would be better.

We would like to see if AWS DMS meets our needs

## Contact person

Mark Rees
Carlo Veo
Mark Berridge
https://mojdt.slack.com/archives/C01B2AY8HLZ

**Comment by AntonyBishop** [comment]
Slack Tread - https://mojdt.slack.com/archives/C57UPMZLY/p1631189431162200

We have an old DMS module but it is seriously our of date. We should review/fix our module with a view to enabling support of DB migration.

**Comment by AntonyBishop** [comment]
Needs Triage

**Comment by AntonyBishop** [comment]
@markreesmoj what is your ETA in terms of starting migration activities?

**Comment by markreesmoj** [comment]
We have already started! We plan to go live in early October but need to complete migration within the next ten days

**Comment by AntonyBishop** [comment]
Thanks for clarifying

**Comment by davidread** [comment]
@razvan-moj says the DMS module is now done, enabling teams to do self-service migrations

**Comment by razvan-moj** [comment]
done in https://github.com/ministryofjustice/cloud-platform-terraform-dms
