### ISSUE TITLE
Cannot deploy fala application to production

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#319]
## Service name

Find a Legal Adviser (FALA)

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Changes cannot be fully deployed to production.

## Problem description

https://ci.service.dsd.io/job/DEPLOY-fala/54/consoleFull

The following two instances (out of four) seem to have problems:

```
[54.229.226.190] Executing task 'run_deploy'
SSHException: Timeout openning channel.
```

```
[54.246.194.14] out: Summary
[54.246.194.14] out: -------------
[54.246.194.14] out: Succeeded: 58 (changed=6)
[54.246.194.14] out: Failed:     2
```
## Contact person

`@David Lantos` on Slack

**Comment by sldblog** [comment]
The issue has been resolved by @pwyborn.
Two new instances were created and the old 4 were shut down.

**Comment by pwyborn** [comment]
paulwyborn [1 hour ago]
David - it looks a bit strange - with the 2 that are failing are on the load-balancer and the 2 that are succeeding are “on- standby” on the auto-scaling group. Does this actually need 4 instances? The norm is 2 (laalaa has 2)


paulwyborn [1 hour ago]
prod that is


David Lantos [1 hour ago]
I have no clue


paulwyborn [1 hour ago]
@David Lantos ^^


David Lantos [1 hour ago]
I don't think we need 4


David Lantos [1 hour ago]
We inherited the whole setup without much explanation


paulwyborn [1 hour ago]
Ah ok - will try to get it consistent


David Lantos [1 hour ago]
But 2 instances seem more than enough to be honest


paulwyborn [43 minutes ago]
@David Lantos - should be ok now? https://ci.service.dsd.io/job/DEPLOY-fala/55/console


David Lantos [43 minutes ago]
Yes, it works perfectly


David Lantos [43 minutes ago]
Thank you!


David Lantos [42 minutes ago]
Should we remove the terminated instances at some point? (I'm not sure how it works)

I guess I should rephrase the question to: do we need to do anything with terminated instances? (edited)


paulwyborn [1 minute ago]
Hi @David Lantos - they should disappear from the dashboard automatically within the next few hours


David Lantos [1 minute ago]
Cool, thank you
