### ISSUE TITLE
Ingress rule to redirect to central security.txt

### ISSUE THREAD

**Issue by Nimphal** [ministryofjustice/cloud-platform#3192]
## Service name

All services

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Every service hosted on Cloud Platform points to the central `security.txt`

## Problem description

MoJ has a central `security.txt` file that all services should redirect to. Would it be possible to add a general rule at ingress/load balancer level that implements this so all services on Cloud Platform get the redirect for free? https://security-guidance.service.justice.gov.uk/implement-security-txt/#implementing-securitytxt

## Contact person

Nev, @Nimphal

**Comment by poornima-krishnasamy** [comment]
There is no specific settings in ingress controller to setup a redirect globally. But Ingress definition allows to create a permanent redirect for a certain path mentioned. This can be done via the ingress.yaml which users manage and apply.
Have to add guidance in user guide on how to define this ingress
Change all demo apps e.g hello-world, multi container app to include this ingress

**Comment by AntonyBishop** [comment]
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/redirect-security-txt.html#setup-ingress-to-redirect-security-txt
