### ISSUE TITLE
Are we at a point where we can be opinionated about how users should deploy to the Cloud Platform?

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3197]
## Background

Are we at a point where we can be opinionated about how users should deploy to the Cloud Platform?

## Proposed user journey

A users understands the recommended way to deploy their environments to the Cloud Platform.

## Approach

- Review our options
- Do we have a view of what is best?

## Which part of the user docs does this impact

Various

## Questions / Assumptions

Are we ready to be opinionated about deployment?
What is the impact of we go for one approach?
How flexible can we be?

## Definition of done

- [ ] Decision on whether we can be opinionated
- [ ] Overview of what we need to do next

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
We're considering:
* kubectl vs helm
* GHA vs circleci
* or just GitOps

**Comment by davidread** [comment]
We see gitops as an option for teams. If teams want to transfer some responsibiltiy of deployment to us. "Easy mode"

**Comment by davidread** [comment]
Closed in favour of #2349
