### ISSUE TITLE
Can I get some slack integrations set up for Pingdom please

### ISSUE THREAD

**Issue by dazoakley** [ministryofjustice/cloud-platform#3200]
Hi,

Could I get two slack integrations for Pingdom set up please?

```
Team Name: ppud-replacement
Application Name: manage-recalls (dev and preprod)
Slack Channel: #ppud-replacement-alerts-nonprod
```

```
Team Name: ppud-replacement
Application Name: manage-recalls (prod)
Slack Channel: #ppud-replacement-alerts-prod
```

Thanks! :)

**Comment by vijay-veeranki** [comment]
Integration Id for : #ppud-replacement-alerts-prod
116724


Integration Id for : #ppud-replacement-alerts-nonprod
116726

**Comment by dazoakley** [comment]
Brilliant, thank you @vijay-veeranki 😄

**Comment by dazoakley** [comment]
I've applied the ID's in https://github.com/ministryofjustice/cloud-platform-environments/pull/5613
