### ISSUE TITLE
New Alertmanager route for ‘Manage my prison’ on `live`

### ISSUE THREAD

**Issue by ushkarev** [ministryofjustice/cloud-platform#3201]
Please could we get a new "severity level" set up for `live` for use with Prometheus/Alertmanager?

- namespace name: `manage-my-prison-dev`
- team name: `Manage my prison`
- application name: `Manage my prison`
- slack channel: `manage-my-prison-alerts` (https://mojdt.slack.com/archives/C02E7L7LD71)
- kubernetes secret name where the webhook url is stored: `slack` (secret's key is `webhook`)
- severity level: `warning`

**Comment by poornima-krishnasamy** [comment]
@ushkarev , the new alertmanager route is setup for "Manage my  prison dev".
The severity to use in the rules is `manage-my-prison-dev`

**Comment by ushkarev** [comment]
Thank you @poornima-krishnasamy!
