### ISSUE TITLE
Prepare Demo on Prototype Service for Design Team Meeting

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3204]
## Background

We'd like to move users from the Heroku account to the Cloud Platform Prototype site. The Design Team have asked if we would like a slot at an upcoming CoP to demo the Prototype Kit.

## Approach

Prepare a demo for Design Meeting on 2nd December

## Questions / Assumptions

- Define Problem Statement
- What can we demo in the timeslot?

## Definition of done

- [ ] Demo prepared

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
Great! Let's ensure we get the feedback they promised and use it to work on it a bit.

**Comment by AntonyBishop** [comment]
Presentation delivered.
