### ISSUE TITLE
Expose Thanos to users

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3209]
Thanos is deployed but not made available to users yet. Would have to add an ingress.

Prometheus only offers 1d. No users have asked for it yet. Thanos would be needed for long term KPI dashboards.

**Comment by AntonyBishop** [comment]
Completed last month - https://thanos.live.cloud-platform.service.justice.gov.uk/graph?g0.expr=&g0.tab=1&g0.stacked=0&g0.range_input=1h&g0.max_source_resolution=0s&g0.deduplicate=1&g0.partial_response=0&g0.store_matches=%5B%5D
