### ISSUE TITLE
Migration test: SPIKE Alias the Kube API in live

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3210]
## Background

This conversation came from the test migration ([src](https://mojdt.slack.com/archives/C02EJL4TUQ3/p1632150657005200))

Should we alias the KubeAPI address. The address for live  is:

```
https://DF366E49809688A3B16EEC29707D8C09.gr7.eu-west-2.eks.amazonaws.com
```

This is isn't very human friendly and is potentially subject to change. Should we create an alias to something vague and easy to remember. Like `https://api.live.service.justice.gov.uk`.

Perform a spike whether this can be done?

There is no need to implement at this point.

**Comment by poornima-krishnasamy** [comment]
There is similar request on AWS roadmap:
https://github.com/aws/containers-roadmap/issues/283

**Comment by vijay-veeranki** [comment]
Raised a support request for aws, requesting guidance on how this can be done
https://console.aws.amazon.com/support/home#/case/?displayId=8934160101&language=en

**Comment by vijay-veeranki** [comment]
reply from aws support:

As can be seen from the roadmap issue[1], it's not possible at the moment and is an open feature request. We don't have an ETA for this and you would either have to wait for this or keep using kops as it provides you this feature. 

Issue referred:
https://github.com/aws/containers-roadmap/issues/283

**Comment by vijay-veeranki** [comment]
Error:

> Unable to connect to the server: x509: certificate is valid for xxxxxxxxxxxxxxxxxxxxx.gr7.eu-west-2.eks.amazonaws.com, ip-xx-x-xxx-xx.eu-west-2.compute.internal, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, not api.live.cloud-platform.service.justice.gov.uk

**Comment by vijay-veeranki** [comment]
Using CNAME and setting up insecure-skip-tls-verify: true, and not using "certificate-authority-data' in the kubeconfig as below, can access the cluster, but it is not recommended approach to access a cluster.

`  insecure-skip-tls-verify: true
    server: https://api.live.cloud-platform.service.justice.gov.uk`

**Comment by vijay-veeranki** [comment]
Closing this spike ticket:
Created a separate [ticket](https://github.com/ministryofjustice/cloud-platform/issues/3228) to address this, when AWS fix this issue
https://github.com/aws/containers-roadmap/issues/283
