### ISSUE TITLE
EKS Test Migration - jakemulley-cloud-platform-dev

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3211]
## Background

Test migration of jakemulley-cloud-platform-dev namespace to `Live`

## Questions / Assumptions

Contact: @jakemulley 
Namespace: jakemulley-cloud-platform-dev
CI/CD: Manual
Deployment: kubectl

## Definition of done

- [ ] testing complete
- [ ] feedback stories created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Done

**Comment by jakemulley** [comment]
Completed it! 👍🏼
