### ISSUE TITLE
EKS Migration Feedback - Intro length

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3231]
A few times it has been mentioned that the intro to the plan is quite long (at least 3 times). A users has to read a lot of background before they they get to the implementation that they are interested/concerned about.

Consider splitting the why/differences and the Implementation into two pages?

**Comment by davidread** [comment]
Let's collapse by default some of the intro Q&A answers using the style in https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/access-cross-aws-resources-kops.html

**Comment by davidread** [comment]
We also think the contents makes it easy to skip to the steps. Let's ask users if this would cover it or if they have another point.
