### ISSUE TITLE
EKS Migration Feedback - KIAM and TTL Controller

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3232]
Feedback:

"kiam -> IRSA difference a new heading (“If you use kiam.“).

People who don’t use it won’t care (but will still have to read the section to see if it affects them), same with TTL Controller."

Split out sections that may bot apply to all teams so that they can skip content that may not be relevant. Users can get to what they need to know quicker.

**Comment by poornima-krishnasamy** [comment]
Update the TTL section with a command to see if the user namespace has the field enabled?

**Comment by davidread** [comment]
Agreed to make two changes:

"If you use Kiam for cross account IAM roles":
* mention the two teams in the linked repo

"If you use Kubernetes Jobs"
* provide command to check this, and this field. `kubectl get jobs | grep`?
