### ISSUE TITLE
EKS Migration Feedback - To be more clear on "blue" for live-1 and "green for "live"

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3239]
Slack Thread: https://mojdt.slack.com/archives/C02EJL4TUQ3/p1632918178034300

Suggestions on standup: Instead of having it as a Note: maybe a highlighted text box.

## Definition of done

- [ ] Migration page in User guide has been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/850
