### ISSUE TITLE
Missing tagging in mojdsd account

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#324]
## Background

Had a meeting earlier with Steve Marshall and Alex Clark around tagging. Only 70% of stuff appears to be tagged in the AWS `mojdsd`. We would like to improve that figure.

AWS mojdsd account. Search in EC2 console - `is production` and `not tagged`.
Tag:
- Correspondence-staff
- Correspondence-tool
- Instances without a name. These instances are in the security group of mps, pvb, pvbpublic and postcodeinfo

Includes the following resources
`i-0d1cc9fe103a41695`
`i-0c964c29271e7342e`
`i-06f2826547c06b06c`
`i-0a2024b3082dee54c`
`i-02d1eadef66ccc94e`
`i-0809837cda639c2fa`
`i-0043f604511c934f1`
`i-04214b649337a6f42`
`i-046e4a2eea6109681`
`i-0681fbda17b318db5`
`i-08cc31d452593010d`
`i-0ad419d26de0951d1`
`i-0e154ed7b27cf3bda`
`i-0ed2ba0e0098eac6e`
`i-0f527eacd9567fd05`

Some are tagged but missing things like `is-production`.

## Approach

Tag the items with missing tags in line with tagging policy. 

## Questions / Assumptions

Assumed that remaining untagged items can be tagged.

## Definition of done

- [x] Missing tags added
- [x] Re-run search in EC2 console - `is production` and `not tagged` and no results returned.
- [x] Agreed any exceptions with Tony for feedback to Steve.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
Note for me PW Report - tags - all resources - application "not tagged" up to graphite (graphite to do) - sort the id column

**Comment by pwyborn** [comment]
Complete - subject to agreement with Steve/Alex

**Comment by AntonyBishop** [comment]
Shared detail with Steve and Alex. Business areas will be contacted directly. No further action required.
