### ISSUE TITLE
Check Monitoring Related Webhooks

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3240]
## Background

As part of getting EKS cluster ready for live we are checking the monitoring set up is ready to go. This includes checking that webhooks are set up correctly so that alarms are routed to the correct user channels.

## Proposed user journey

When alerts are triggered they are routed to the correct user channels.

## Approach

Check set up is the same between "Live-1" and "Live"

## Which part of the user docs does this impact

N/A

## Definition of done

- [ ] we are confident that webhooks are set up correctly for "Live"

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Added "live-1" teams webhooks to live cluster.
