### ISSUE TITLE
Check Tools Image works for "Live"

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3243]
## Background

In getting "Live" ready for production services we need to check that the Tools Image works for "Live".

## Questions / Assumptions

How do we check this?

## Definition of done

- [ ] Confident Tools Image works for "Live"

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
I am still working on the "alerts" ticket, moving this back to This Sprint.

**Comment by vijay-veeranki** [comment]
Closing this ticket as "Check Tools Image works for "Live" is done.

ACW CLI v2 install on our tools image is a separate task, will open a new ticket for it.
