### ISSUE TITLE
SPIKE: Branch based deployments

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3247]
## Background

We would like all prototyping of services to take place on the Cloud Platform.

To make this possible we need to be able to offer similar features as the current solution. One such feature is branch based deployment.

## Proposed user journey

As a designer I want to be able to deploy changes based on individual branches as part of the prototyping process so that I can test different versions of an app.

## Approach

- Understand how users are using current solutions for Branch based deployments (Research).
- Spike into how we can offer this feature for Cloud Platform.
- Be ready to trial with users.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- Do we just offer this for prototypes?
- How does this feature apply to the current prototype kit?
- What are the implications of making this widely available?
- Do we have access to users who can help us understand the jobs to be done?

## Definition of done

- [ ] We have determined how we can offer branch based deployment
- [ ] We know what we need to do to make this available as a trial

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
Tenants are able to set this up themselves - it's not really in our scope. We could usefully point to a good pattern in our docs, though - @jasonBirchall what was the one you mentioned?

For designers who use the Prototype Kit, we might want to setup this automatically, as they have less capability to set it up themselves.

**Comment by poornima-krishnasamy** [comment]
https://docs.google.com/document/d/1fC4k1H9PqO2TsrtdrU-iti85S4Cg1Zfk42i54SvRAQo/edit?usp=sharing

Trying Option 2 for demo
