### ISSUE TITLE
FIREBREAK: Notary - image signing

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3249]
## Background

Try using Notary, to sign images that we decide are ok. See if this could be part of our vulnerability scanning solution. https://siegert-maximilian.medium.com/ensure-content-trust-on-kubernetes-using-notary-and-open-policy-agent-485ab3a9423c 

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by vijay-veeranki** [comment]
Helm repo is not updated from last 2 years
https://github.com/k8s-gadgets/k8s-content-trust/tree/master/notary-k8s

helm install notary is not working as expected.

Ran through the steps here and it is a complicated setup.
https://siegert-maximilian.medium.com/ensure-content-trust-on-kubernetes-using-notary-and-open-policy-agent-485ab3a9423c
