### ISSUE TITLE
Add prometheus alert for elasticsearch-curator cronjob

### ISSUE THREAD

**Issue by nayoa** [ministryofjustice/cloud-platform#325]
## Background

After completing #287, @pwyborn suggested that there should be an alert on the elasticsearch-curator cronjob in case it fails.

https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/cloud-platform-test-1.k8s.integration.dsd.io/logging/elasticsearch-curator.yaml

## Proposed user journey

N/A

## Approach 

Add an additional custom alert and apply to prometheus test-1 and live-0. 

https://github.com/ministryofjustice/cloud-platform-prometheus/blob/master/custom-alerts/custom-alerts.yaml

https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/cloud-platform-live-0.k8s.integration.dsd.io/logging/elasticsearch-curator.yaml

## Definition of done

- [x] Create a warning alert on prometheus test-1 and live-0 that alerts when the elasticsearch-curator cronjob fails.
- [x] Test the alerts work by ensuring the elasticsearch-curator fails.

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-prometheus/commit/1c9b51d99226785de1477333e960b62cc3e034b1
