### ISSUE TITLE
RabbitMQ is not running on laalaa staging instances

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#326]
## Service name

LAALAA, as known as LAA Legal Adviser API

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Parts of the application do not work.

## Problem description

Application cannot upload legal adviser data files.

https://sentry.service.dsd.io/mojds/laalaastaging/issues/2965/: `consumer: Cannot connect to 'amqp://rabbit:**@172.17.42.1:5672//': error(error(113, 'No route to host'),).`

Judging from `/var/log/rabbitmq/startup_*`, it seems the RabbitMQ service cannot boot up, possibly due to instances not having enough memory.

## Contact person

`@David Lantos` on Slack

**Comment by sldblog** [comment]
📝 I don't have rights to change the instance type myself to see if that allows Erlang/RabbitMQ to boot up.

**Comment by lukaszraczylo** [comment]
Connects to my last comment on https://github.com/ministryofjustice/cloud-platform/issues/178
Working on solution.

**Comment by lukaszraczylo** [comment]
Issue with RMQ solved by updating rabbitmq-formula and few other packages.

**Comment by pwyborn** [comment]
Whilst Rabbitmq is running. Other issues with staging in that docker containers are not coming up - since instance size increased to T2 micro.

To unlock specific  docker version: https://github.com/ministryofjustice/laalaa-deploy/pull/38

**Comment by pwyborn** [comment]
lukasz [3 days ago]
please note - you require docker-formula v 2.2.1 ( https://github.com/ministryofjustice/docker-formula/releases/tag/v2.2.1 ) to fix docker installation issues

lukasz [3 days ago]
tip - if containers don’t want to get back up:
```stop laalaa_container; start laalaa_container```

lukasz [3 days ago]
as per my last commit - https://github.com/ministryofjustice/laalaa-deploy/commit/81ef78c64c7018f62ea4ef5030791e77359cc7df

**Comment by pwyborn** [comment]
paulwyborn [3 days ago]
@nick - I cannot claim the credit - but think your laalaa staging deploy is fixed - thank @lukasz

**Comment by pwyborn** [comment]
Complete

**Comment by pwyborn** [comment]
Related ticket 335 https://waffle.io/ministryofjustice/cloud-platform/cards/5b7a83d4e6d4c3002982d736

**Comment by rowlando** [comment]
Hello again,

RabbitMQ is still playing up on staging. It seems one of the staging instances isn't behaving.

https://staging.laalaa.dsd.io/healthcheck.json

RabbitMQ works fine on 34.241.201.40 but not 54.154.142.113.

Please help!

**Comment by pwyborn** [comment]
See new ticket #373
