### ISSUE TITLE
How to get latest announcements/ releases of components used in CP stack

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3262]
## Background

One of the point raised during incident review of SSL certificates issues with browsers because of letencrypt root CA expiry,  is to get updated with the latest announcements/releases of the technical stack used in cloud platform. 

Choose 5 most obscure components of our stack and find a place where we can get releases/announcements and high level news related to them. 

Can those be added as a news feed to #cloud-platform-rss?

## Definition of done

- [ ] websites or urls found to get latest information of the components used 
- [ ] RSS feed added or alternative way to get the team updated regularly
- [ ] runbook have been updated (if applicable)
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
Our thoughts from discussion:

#cloud-platform-rss

* every item needs review for actionable content - breaking changes, security issues, update we should do
* write down our policy for doing this, to make sure we miss stuff
* weed out RSS feeds like CNCF which are just of general interest
