### ISSUE TITLE
Can we use ACM instead of Letsencrypt

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3263]
This is an action item from incident review of SSL certificates issues with browsers because of letencrypt root CA expiry.

Letsencrypt is used to issue and renew certificates for websites hosted in Cloud Platform. 

Can we use AWS Certificate manager instead?
Does it use ACME and can act as a provider for ClusterIssuer?
Does it need cert-manager or work on its own
Is it worth moving away from LetEncrypt to ACM?

## Definition of done

- [ ] ACM investigated and documented
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
We originally used ACM, but we switched to LE because it is free. ACM is more managed, but vendor lock-in.

**Comment by AntonyBishop** [comment]
Aged Out
