### ISSUE TITLE
How we can get visibility of ServiceNow service issues for CP-hosted services

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3264]
One of the point raised during incident review of SSL certificates issues with browsers because of letencrypt root CA expiry, is to get more visibility of ServiceNow service issues related to CP-Hosted services. 

This will give more insight on whom to contact, where to look into and update when resolving incidents.

Can Cloud Platform services be listed/filtered in the ServiceNow Incident management tool?

## Definition of done
- [x] Issue investigated and answer documented
- [x] runbook updated (if needed)
- [x] another team member has reviewed
- [x] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Had initial chat with Service Operations. Arranging follow up session with the Incident Management Team.

**Comment by AntonyBishop** [comment]
Awaiting input from Service Ops

**Comment by AntonyBishop** [comment]
Awaiting dates for catch-up with Major Incident Team and Change Management.

**Comment by AntonyBishop** [comment]
Meeting with Incident Management. Actions to be published.

**Comment by AntonyBishop** [comment]
No significant changes to processes. I have asked for platforms mailbox to receive Sev1 incident reports.
