### ISSUE TITLE
Create a slack slash command to inform the user of an approved PR

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3270]
## Background

Currently, a user submits a PR and enters it into the #ask-cloud-platform channel for review. When reviewed the team put a little reaction onto the comment to suggest it's been approved.

I feel like we can do better than this. We should create an automated slashbot command that, when approved, creates a comment on the users thread and points them to the correct concourse pipeline job.

## Proposed user journey

For example:

> Can I get a review on the PRs for manage adjudications api preprod and prod please:
https://github.com/ministryofjustice/cloud-platform-environments/pull/5788
and
https://github.com/ministryofjustice/cloud-platform-environments/pull/5789/
Thank you! (edited) 

(CLOUD PLATFORM THEN APPROVES THE PR IN GITHUB)

> > Your PR has been approved by \<user\>, you can view the progress here: \<concourse url\>

## Approach

Utilise slack slash commands and GitHub's API.

## Questions / Assumptions

Is this even possible? It's purely conceptional and in my head at the moment.

## Definition of done

- [ ] this has been checked and will/will not work
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
Why add a Slack reply?
* GitHub sends an email to the PR author, but maybe that's not enough
* A emoji check mark doesn't alert the PR author in Slack, and it doesn't have a timestamp so we can't calculate response time metrics

**Comment by davidread** [comment]
We're not convinced it is valuable enough. Maybe for firebreak
