### ISSUE TITLE
Schedule some "migration explainer" meetings

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3278]
Let's schedule a couple of sessions, perhaps a few days after the announcement that dev environments should be migrated, and one 10 days later, for those that are slower off the mark, or miss the first one.

It's a chance to explain the migration, what teams need to do, and answer questions. Yes we have [docs saying all this already](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrate-to-live.html#introduction), but holding these sessions is us being helpful. And some people prefer verbal over written. Communication is always good.

## Definition of done

- [ ] schedule talks
- [ ] create a follow-on ticket to plan the talk/session

**Comment by davidread** [comment]
Tony is going through the teams and asking if they need a session

**Comment by AntonyBishop** [comment]
This is now just an ongoing activity.
