### ISSUE TITLE
Write announcement that dev namespaces should be migrated to 'live'

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3279]
We think this should go out next week.

Key points to the announcement:

* explain the ask, similar to the [annotation request](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrate-to-live-ingress-annotation.html#add-external-dns-annotations-to-your-ingress-resource-in-live-1)
* link to the guidance
* expectation is that a developer will be able to do this migration in 2 hours.
* teams will need to schedule a day during the migration period (e.g. now until mid Nov) (use a shared Google sheet?) so that CP team member is on hand to answer any questions during the migration.
* this is only for dev environments. An announcement will be made, probably in mid-November, when the staging and prod environments can be deployed. We are doing this staged roll-out to build confidence in the new cluster, once critical mass of dev environments are on there and tested. In the meantime, the new cluster is in good shape, but the Cloud Platform team reserve the right to make significant changes, so don't want prod environments on there.
* teams are invited to a [couple of meetings where it is all explained verbally and they can ask questions](https://github.com/ministryofjustice/cloud-platform/issues/3278) - provide dates

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
https://docs.google.com/document/d/1sKPCkobji9Hcit9jJb7A3OZ1Dt4-KtOs8QmAP_UOwvw/edit?usp=sharing
