### ISSUE TITLE
Ensure we get higher pod density on EKS nodes

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#3282]
## Background

Since https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.9.0, the EKS CNI allows for more than x-pods-per-network-interface, with a list of caveats 

## Approach

Identify how to update the needed CNI (new AMI available?)

Create a test cluster, identify the new max pods an instance can run

## Definition of done

 - update infra repo to use the new feature
 - deploy the change in live (will require a cycle of all nodes)

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1dNdDFXWhRcgtoMcZyZl0oNXz5MxU3slvZXmicouk3Fg/edit

**Comment by vijay-veeranki** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1424/files

https://github.com/ministryofjustice/cloud-platform-terraform-vpc-cni

# This is to adopt the resources into a release as guided in helm chart
# https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni#adopting-the-existing-aws-node-resources-in-an-eks-cluster

**Comment by vijay-veeranki** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1424/commits/97c8979ecc2426b6d4bd296ac1b805f9bca99944

this is with using addon instead of using helm chart as above comment

**Comment by vijay-veeranki** [comment]
Both options (addon and helchart) applying cni need null resource to do local-exec.

for addon :
      kubectl set env daemonset aws-node -n kube-system ENABLE_PREFIX_DELEGATION=true
      kubectl set env daemonset aws-node -n kube-system WARM_PREFIX_TARGET=1

for helm chart:

for kind in daemonSet clusterRole clusterRoleBinding serviceAccount; do
  echo "setting annotations and labels on $kind/aws-node"
  kubectl -n kube-system annotate --overwrite $kind aws-node meta.helm.sh/release-name=${helm_release_name}
  kubectl -n kube-system annotate --overwrite $kind aws-node meta.helm.sh/release-namespace=${namespace_name}
  kubectl -n kube-system label --overwrite $kind aws-node app.kubernetes.io/managed-by=Helm
done

**Comment by vijay-veeranki** [comment]
We can wait for this addons supported through eks module:
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1443

**Comment by vijay-veeranki** [comment]
Closing this issue as we have new issue for it https://github.com/ministryofjustice/cloud-platform-user-guide/issues/956
