### ISSUE TITLE
Add Banner to User Guide to advise about ongoing "Live-1" to "Live" 

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3287]
## Background

It will take a while to update all our guide to reflect to migration to EKS. There are lots of references to "Live-1".

We want users to be aware.

## Approach

Update pages with a header to make clear that references to "Live-1" are being updated to "Live" and they may need to bear that in mind. 

## Which part of the user docs does this impact

The whole guide.

## Definition of done

- [x] Banner exists

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/886
