### ISSUE TITLE
Review Elasticsearch Module to ensure docs reflect changes with KIAM

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3288]
## Background

The ES module uses KIAM which is impacted by the move the EKS.

## Approach

Review docs/readme to ensure that documentation reflects changes.

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch

## Definition of done

- [ ] docs reviewed and updated.
- [ ] ES module will work for "Live"

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
created ES instances in both live-1 and live, all works fine, the only setting needed was https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch/blob/main/example/elasticsearch.tf#L35
