### ISSUE TITLE
Fix Prometheus/AlertManager links on Slack

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#329]
## Background

Fix Prometheus/AlertManager links on Slack
The links on alerts in Slack point to a default URL, this needs to be amended to point to actual URL:
AM URL:
https://alertmanager.apps.cloud-platform-live-0.k8s.integration.dsd.io/#/alerts 

Currently points to 
http://kube-prometheus-alertmanager.monitoring:9093/#/alerts

**Comment by alkar** [comment]
Setting `--web.external-url` for both kube and prom *should* fix this

**Comment by nayoa** [comment]
https://github.com/ministryofjustice/cloud-platform-prometheus/pull/30 - Applied change on live-0. Difficulty applying change to `test-1`.

**Comment by alkar** [comment]
Seems to be complete, closing this
