### ISSUE TITLE
Increase log retention period

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3292]
## Background

At present we retain application logs for 30 days. The policy for log retention is changing to align application logs to security logs:

- 90 days for public facing services
- 13 months for internal/staff services

## Approach

Increase log retention in line with policy changes.

## Which part of the user docs does this impact

[Application Log Collection and Storage](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/logging-an-app/log-collection-and-storage.html#application-log-collection-and-storage)

## Questions / Assumptions

- We will store date for 13 months (double check there aren't rules about this?)
- What is the impact on storage and performance?
- Is there any benefit in looking at Opensearch in support of this.

## Definition of done

- [ ] We retain logs for 90 days/13 months

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
How do we know a service is internal or public? Let the user add an annotation? Or maybe we can simply store it all for 13 months, and eat the storage cost.

**Comment by AntonyBishop** [comment]
Done
