### ISSUE TITLE
Check detail for releases from Kubernetes 18.2 to 18.20

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3293]
We should check details of releases between 18.2 and 18.20.

Check if there is anything breaking.

**Definition of Done**

- [ ] Identify any breaking changes

**Comment by razvan-moj** [comment]
After reading https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md and with EKS in the works, I think we can keep the existing setup.
