### ISSUE TITLE
Concourse Reporting and Maintenance pipelines for "live" cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3294]
## Background

Check Concourse Reporting and Maintenance works for "Live"

- We have reporting pipeline and maintenance pipelines running for "live-1", verify if they are needed for "live" cluster, Identify the list and create separate tickets to implement it.

- Verify https://reports.cloud-platform.service.justice.gov.uk/dashboard needed for "live", identify the list and create separate tickets to work on them.

## Definition of done

- [x] Reporting and Maintenance works 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
"live" needs the following concourse pipelines:
**maintenance**

- Recycle nodes: this might be a little tricky as we're using EKS.

- Delete manually created pods

- Delete completed jobs.

**reporting**

<none>
