### ISSUE TITLE
FIREBREAK: Can user login via AWS SSO and get authenticated to the EKS cluster

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3296]
Currently, users authenticate to the cluster via kuberos using a webUI. This has few drawbacks like kuberos code maintaintance, kubeconfig rotation etc.

Investigate whether enabling SSO access to AWS console help in authenticate to EKS live cluster.

Slack discussion thread: https://mojdt.slack.com/archives/C514ETYJX/p1634295710287700

Questions to answer:
How to enable SSO access to the user for Cloud Paltform AWS account?
Does this enabling SSO access outside of Cloud Platform team control? if so, What are the steps involved?
What are the access levels does the user has from the console? 
Do they have enough permissions to do access their namespace?
Do they have any escalated permissions in the console?
Is it possible to enable or disable accessing certain services from the console?

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by davidread** [comment]
Sounds great.

Some of the security questions I'd like this work to bottom out are listed in the ADR here: https://github.com/ministryofjustice/cloud-platform/blob/main/architecture-decision-record/024-SSO-for-CP-Team-to-access-AWS.md#security

**Comment by poornima-krishnasamy** [comment]
Made little progress on adding a non-admin github team to the root-account which gives a read-only access to the cloud-platform-aws AWS account.
https://github.com/ministryofjustice/aws-root-account/commit/a3b288cc736f57d1ec686e6f5925071e0c95622e

Using the dummy-user who is part of the non-admin github team was able to login to AWS using SSO. The read-only access to console means that user can read all the contents of all aws resources including other users s3 bucket data.

Look into whether it is possible to modify the read-only policy to add condition 
```
    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/Owner"
      values   = [var.team_name]
    }
```

**Comment by AntonyBishop** [comment]
Covered in another story.
