### ISSUE TITLE
FIREBREAK: Hashicorp Waypoint

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3297]
## Background

https://www.hashicorp.com/blog/announcing-hashicorp-waypoint-0-6

Like Heroku in k8s.

H/T @jasonBirchall for the suggestion

## Definition of done

- [x] Firebreak finding documented appropriately
- [ ] Demo completed
- [x] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by jasonBirchall** [comment]
Review documentation:
https://docs.google.com/document/d/17mdCjzRK75wLOHlqyenfITUcgcRvik496_Ko0I9nrnw/edit?usp=sharing

**Comment by jasonBirchall** [comment]
Conclusion: Too early to decide if this will be useful. Docs leave something to be desired. Please read review.
