### ISSUE TITLE
Migration to live - annotation guide for users who maintain ingress in environment repo

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3301]
If users maintain ingress in environments repo, cloud-platform cli migrate command copies the ingress from "live-1" repo to "live" repo. 

The annotation for ingress in "live" should be changed to 
    external-dns.alpha.kubernetes.io/set-identifier: "ingress-name-namespace-name-green"
    external-dns.alpha.kubernetes.io/aws-weight: "0"

Conversation related to it:
https://mojdt.slack.com/archives/C02EJL4TUQ3/p1634638167000300

There are not many users who do have ingress in env repo. Options to address this: 

1) Either we amend the guide to make it clear for users to update the annotation who maintain ingress in environments repo.
2) Fix the cli to address ingress annotation

**Comment by AntonyBishop** [comment]
No longer required. Rare cases that can be picked up as we go.
