### ISSUE TITLE
Create a Python version of the Helloworld to help on-board Data Scientists

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3308]
## Background

We had a really good piece of feedback to improve on-boarding new developers/data scientists onto Cloud Platform. When running through the Helloworld deployment application you should be presented with multiple choices for a helloworld app, like how Heroku does on their [homepage](https://www.heroku.com/):

![Screenshot 2021-10-28 at 10.16.39.png](https://images.zenhubusercontent.com/5c9397ffbb416905afa23685/33d40d3e-fa67-409a-8446-b37ba252dc2a)

We already have a Ruby version of this page, it would be great and make people feel more at home by onboarding a helloworld in a language they feel more comfortable.

## Proposed user journey

When a user hits the helloworld page of our documentation, they should be presented with a helloworld language of choice (please see how Heroku have done it above). 

To improve the on-board of Analytical Platform users onto Cloud Platform we should create a helloworld repository and instructions

## Approach

Create a repository exampling how to setup a [streamlit](https://streamlit.io/) application on the cluster (this is what AP users use) and add to the documentation.

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/helloworld-app-deploy.html#deploying-a-39-hello-world-39-application-to-the-cloud-platform

## Questions / Assumptions

That it's actually possible to containerise and deploy streamlit apps on Kubernetes.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
that's really nice, we should do this
