### ISSUE TITLE
Update migration to live guide about warning to use "networking.k8s.io/v1 Ingress"

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3309]
Update migration to live guide about warning "networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress" in "live" cluster

`W1028 11:24:31.862338     187 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1028 11:24:32.616819     187 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`

some conversation to it:
https://mojdt.slack.com/archives/C02EJL4TUQ3/p1635420454003200?thread_ts=1635419500.001400&cid=C02EJL4TUQ3

**Comment by davidread** [comment]
we're telling the user they can ignore it
