### ISSUE TITLE
Firebreak: Secure cloud deployments with OpenID Connect

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#3310]
GitHub Actions now supports OpenID Connect (OIDC) for secure deployments to cloud, which uses short-lived tokens that are automatically rotated for each deployment.
This enables:

Seamless authentication between Cloud Providers and GitHub without the need for storing any long-lived cloud secrets in GitHub
Cloud Admins can rely on the security mechanisms of their cloud provider to ensure that GitHub Actions workflows get the minimal access for cloud resources. There is no duplication of secret management in GitHub and the cloud.
How this works:

Developers set up OIDC trust on their cloud roles to manage access between their deployment workflows and cloud resources.
In each deployment, GitHub Actions workflow presents an autogenerated OIDC JWT token to the cloud provider
Cloud provider validates the claims in the OIDC token against the cloud role definition and provides a cloud access token to connect and deploy to the Cloud only during the workflow run.

https://github.blog/changelog/2021-10-27-github-actions-secure-cloud-deployments-with-openid-connect/

**Comment by vijay-veeranki** [comment]
Followed this guide and configured OpenID connect in AWS.

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

Step 1:  Added the github identity provider to AWS

For the provider URL: Use https://token.actions.githubusercontent.com
For the "Audience": Use sts.amazonaws.com

Step 2: Configured the role and trust policy, with validation conditions to test repo.
https://console.aws.amazon.com/iamv2/home?#/roles/details/test-github-oidc?section=trust_relationships

Step 3: Updated GitHub Actions workflow using role-to-assume created in step 2.
https://github.com/ministryofjustice/vijay-test-prototype/blob/main/.github/workflows/cd2.yaml

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/19cwlFuM5b7Dn0B9c2V9jAJJSKIFDXiksjbptl9yes5Q/edit
