### ISSUE TITLE
Guide to deploying into Kubernetes with AWS is missing ECR configurations file to create a repository

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#332]
## Background

User feedback via feedback form.

"the guide to deploying into kubernetes with AWS is missing ECR configurations file to create a repository because I don't have the permissions to create a repository on the mojdt cloud console"

The guide does contain relevant guidance (https://ministryofjustice.github.io/cloud-platform-user-docs/01-getting-started/003-ecr-setup/#creating-an-ecr-repository), however the the documentation is missing how to make a PR and deploy it into Kubernetes. Example of better explanation can be found in the document for creating an S3 bucket (https://ministryofjustice.github.io/cloud-platform-user-docs/02-deploying-an-app/005-add-s3-bucket-to-your-application/#adding-s3-bucket-for-your-application).

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
https://ministryofjustice.github.io/cloud-platform-user-docs/#getting-started
