### ISSUE TITLE
Do we need to connect "live" cluster to The Transit Gateway

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3331]
## Background

As far as I know, there is some Terraform code required to setup TGW to the cluster. This should be investiagted further.

**See additional comments.**

**Comment by davidread** [comment]
The TG is connected to the VPC, rather than the cluster, so maybe nothing to do here?

**Comment by davidread** [comment]
It's probably worth us checking that the CIDR blocks in the [TGW config](https://github.com/ministryofjustice/transit-gateways/) include the live cluster

**Comment by AntonyBishop** [comment]
As we are not changing VPC is this already set up?

**Comment by davidread** [comment]
We should document that TGW users sending traffic to a service on Cloud Platform, that they need to re-point to the new cluster's IP addresses, when the particular service migrates live-1 to live.

**Comment by vijay-veeranki** [comment]
Gone through the module there is no effect of migration to "live" cluster.

This is now managed by #techops-team 

Had a chat with 
Calum BarnettHead of Data Engineering (Prisons & Probation)
**They are using transit gate-way but effected by migration as they are not using cp to host**

Neill Turner WebOps Engineer (Analytical platform)
They are not using transit-gateway

**Comment by vijay-veeranki** [comment]
Spoke to Andy Cohen from techops-team/cloud-ops team, they are managing the transit-gateway now
