### ISSUE TITLE
Create new alerts receiver 

### ISSUE THREAD

**Issue by andrewrlee** [ministryofjustice/cloud-platform#3339]
Information as requested here: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-slack-webhook-and-amend-alertmanager:

namespace name: (multiple)
team name: Prisoner Content Hub team.
application name: (multiple)
slack channel: #hub_alerts_non_prod
kubernetes secret name where the webhook url is stored: please DM me via slack for webhook. `@Andrew Lee`
severity level (warning/information): hub_alerts_non_prod

**Comment by vijay-veeranki** [comment]
Done now, severity level : hub_alerts_non_prod
