### ISSUE TITLE
Namespace Concourse Pipeline not deleting Namespace

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#334]
The laa-fee-calc-dev NS folder was deleted from non-prod cluster on the cloud-platform-environment repo, however the NS did not get deleted from cluster

Need to investigate why the pipeline did not do this

Job 3597
https://concourse.apps.cloud-platform-live-0.k8s.integration.dsd.io/teams/main/pipelines/build-environments/jobs/apply/builds/3597

The above job was the NS delete PR
https://github.com/ministryofjustice/cloud-platform-environments/commit/0d6e7a08bd51e5f955976ba536c1ec39b58a148d

**Comment by alkar** [comment]
As discussed, for now we want the pipeline to *notify* us of discrepancies between git and kube so that we can manually cleanup.

**Comment by alkar** [comment]
Also see #370. As part of this ticket, we would like to have a document that lists the steps we need to take in order to fully cleanup a deleted namespace (cleanup kubernetes and AWS resources)

**Comment by ollieanwyll** [comment]
Struggling to make some progress on my own. Underestimated the complexity and would like  to pair up on this.

**Comment by jasonBirchall** [comment]
PR raised here:
https://github.com/ministryofjustice/cloud-platform-concourse/pull/40

Once merged, I'll apply this in the live concourse pipeline and prove reporting works as expected.

**Comment by jasonBirchall** [comment]
PR merged and now in live-0 concourse. Output checked and verified.
