### ISSUE TITLE
'Location' in ingress - plan a path away from this practice

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3349]
## Background

[We are concerned about the use of 'Location' in ingress configurations](https://docs.google.com/document/d/1CJ5mJG1h19FKyMDOvXKMmUYEE9XKhelXCMNTyzeDRkw/edit#heading=h.8u4dz66tjnza) and would rather users didn't use it.

## Definition of done

- [ ] find out what users use it, and why
- [ ] plan an alternative 
- [ ] create tickets for migrating users away from using Location and then creating an OPA rule to stop its use

**Comment by vijay-veeranki** [comment]
Comment from ingress-nginx team regarding the words considering to be blocked
https://github.com/kubernetes/ingress-nginx/issues/7837#issuecomment-958059167

**Comment by vijay-veeranki** [comment]
This is the PR that Nginx people are working on: https://github.com/kubernetes/ingress-nginx/compare/main...rikatz:annotation-string-sanitization

**Comment by razvan-moj** [comment]
https://github.com/kubernetes/ingress-nginx/issues/7937

**Comment by razvan-moj** [comment]
https://github.com/kubernetes/ingress-nginx/issues/7837 no upstram solution yet

**Comment by AntonyBishop** [comment]
Risk accepted.
