### ISSUE TITLE
FIREBREAK: Spike HUGO static page generator to replace user guide

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3350]
As part of previous firebreak, HUGO templates were spiked to replace HOODAW frontend.

Check if the user guide and runbook can be replaced with hugo static page generator

## Questions / Assumptions

How does the search works?
How to get the gov.uk look and feel as a custom theme?

more details in doc: https://docs.google.com/document/d/1-__EErF6v0sQyNuapRhLT5sUXhW2PiaanXWBEW3NReM/edit?usp=sharing 

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by davidread** [comment]
I'm not clear the advantage of moving to Hugo. The User Guide already is a static site, so maybe there is a misunderstanding that this was not the case? Or maybe there is another motivation.

The current Tech Docs Template is the standard template for technical docs shared by over a hundred sites across government. So there's a consistency for users, and consistency for editors, and we share the development of the template with many others.

For Hugo we'd probably need to convert the template to Hugo's format.

My understanding is that Hugo is more oriented to blogs where content is structured by date, whereas we currently order things into logical chapters and have a hierarchy of pages below them.

**Comment by AntonyBishop** [comment]
Story is to look at how we can link HUGO up with TechDocs Template.

**Comment by AntonyBishop** [comment]
Insufficient value.
