### ISSUE TITLE
Verify Elasticsearch module able to use it across clusters

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3353]
A user has migrated and correctly added the [two settings](https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch/blob/main/example/elasticsearch.tf#L35-L36) IRSA and ASSUME but this means they won’t be able to use it across clusters as the old (KIAM) role is removed.

Kiam or irsa is for proxy, so we can try "assume_enabled = true" for live-1 and " irsa_enabled = true" for "live" cluster

This way users may use assume in "live-1" and irsa in "live" if user intend to use it from both clusters.

Try the approach and see if it is working in both clusters.

Thread related to it:
https://mojdt.slack.com/archives/C514ETYJX/p1636644932077300

May be we need to use join [here](https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch/blob/d1c5b86ad378ee43d92bbdcf052c7ba3a6ee0127/main.tf#L42) 

So both identifiers can be used In the iam_role_policy  policy
https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch/blob/d1c5b86ad378ee43d92bbdcf052c7ba3a6ee0127/main.tf#L259

**Comment by poornima-krishnasamy** [comment]
The new release https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch/releases/tag/3.9.2 has changes which will allow namespace from both the clusters to access the Elasticsearch. All namespaces upgraded to new release.
