### ISSUE TITLE
New Prometheus/Alertmanager "severity" for ‘Manage my prison’ on `live`

### ISSUE THREAD

**Issue by ushkarev** [ministryofjustice/cloud-platform#3354]
Please could we get a new "severity level" set up for the `live` cluster for use with Prometheus/Alertmanager?

- namespace name: `manage-my-prison-dev` (but there will be others)
- team name: “Manage my prison”
- application name: “Manage my prison”
- slack channel: `manage-my-prison-alerts` (https://mojdt.slack.com/archives/C02E7L7LD71)
- kubernetes secret name where the webhook url is stored: `slack` (secret’s key is `webhook`)
- severity level: `warning`
- severity name: `manage-my-prison` (no need for `-dev` suffix because we’ll use it for other namespaces too)

Please not that there is _already_ a severity level called `manage-my-prison-dev` – I’d like to _replace_ that one so you can delete it.

Also note that there’s another key in the `slack` secret called `token` – I’m not sure what it’s for, but it got spat out when I made the webhook.

The previous severity level reference: https://github.com/ministryofjustice/cloud-platform/issues/3201

**Comment by jasonBirchall** [comment]
This should've flagged to support but hasn't. Moving manually.

**Comment by ushkarev** [comment]
thanks @jasonBirchall – there’s no rush

**Comment by vijay-veeranki** [comment]
Configured severity as "manage-my-prison"

PR:
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1430

**Comment by vijay-veeranki** [comment]
It is applied now, 
severity : "manage-my-prison"

**Comment by ushkarev** [comment]
thanks @vijay-veeranki !
