### ISSUE TITLE
Concourse slack notifications stopped working

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#336]
*Background*

The notifications to slack have stopped for Concourse. Please investigate and resolve.

Users will not receive notifications so won't know if what they are building/deploying has worked.

*Definition of done*
- [x] identify why slack notifications have stoped
- [ ] fix the problem
- [x] notifications correctly appearing in Slack

**Comment by razvan-moj** [comment]
Found several errors in both Concourse and the pipeline starting from Jul 7, fixing these first
```NAME                             READY     STATUS             RESTARTS   AGE
concourse-worker-0               0/1       CrashLoopBackOff   5131       13d```
and
```$ fly -t live ws
name                containers  platform  tags  team  state    version
concourse-worker-1  9           linux     none  none  running  2.1
the following workers have not checked in recently:
name                containers  platform  tags  team  state    version
concourse-worker-0  11          linux     none  none  stalled  2.1```
a `fly prune` and `delete pod` fixed this one
Checking now the steps of https://concourse.apps.cloud-platform-live-0.k8s.integration.dsd.io/teams/main/pipelines/build-environments/jobs/apply/builds/4944

**Comment by razvan-moj** [comment]
there was no actual problem to fix, notifications on success were disabled on purpose, see https://github.com/ministryofjustice/cloud-platform-concourse/commit/2b301c479d417c2a9da1912e91de8c0bbf106455#diff-72337ff696f4df3c21ba9e2bd2cfb2ca
