### ISSUE TITLE
Create a "Delete completed jobs" pipeline

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3362]
## Background

Connects to https://github.com/ministryofjustice/cloud-platform/issues/3294

With the lack of job cleanup we should duplicate the concourse job that deletes jobs after n.

https://github.com/ministryofjustice/cloud-platform-terraform-concourse/blob/main/pipelines/manager/main/maintenance.yaml#L119-L155

## Approach

Duplicate the concourse pipeline, test, test, test.

## Questions / Assumptions

- The codebase can be copied and re-pointed.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Will revisit if still required post EKS migration complete.
