### ISSUE TITLE
Allow 'How out of date are we' report access to the "live" cluster

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3363]
## Background

This connects to https://github.com/ministryofjustice/cloud-platform/issues/3294

At the point of writing this ticket 'how out of date are we' (HOODAW) reports only inspect and report the `live-1` cluster.

Due to the recent migrations, we should now inspect both `live` and `live-1`. This will give us a greater understanding of what's in the estate, rather than just `live-1` i.e. production.

## Proposed user journey

Amend the cron-job reporting to look in both clusters.

## Questions / Assumptions

This is a rather large amount of work, that may need splitting into multiple tickets.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Closed this ticket, as raised separate issues referenced in this ticket.
