### ISSUE TITLE
Upgrade all roles and rolebindings API's to latest

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3371]
## Background

`rbac.authorization.k8s.io/v1beta1` is deprecated and should be replaced with `rbac.authorization.k8s.io/v1`
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122

## Proposed user journey

All roles and rolebindings should be maintained in the cloud-platform-environments repository. We should perform a single sweep to upgrade all.

## Approach

1. Determine impact of changes on cluster
2. Determine any user impacts (rolebindings are all managed in Environments)
3. Plan upgrade

Upgrade all role and rolebindings in the environments repository, including the cli-templates.

## Which part of the user docs does this impact

None

## Questions / Assumptions

That we don't maintain anything out of the environments repo.

## Definition of done

- [ ] Impact understood
- [ ] Plan implementation
- [ ] Create story for implementing the upgrade.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Done
