### ISSUE TITLE
Investigate why concourse volume is filling up

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3374]
## Background

After the recent upgrade, concourse worker volume is filling up in the directory  /concourse-worker-dir and not auto cleaning. Most of the folders container copy of environments repo. 

Can the scenario be recreated in test cluster with pipelines using tools image and cloning env repo. Will that help in finding the root cause of the issue?

## Definition of done

- [ ] scenario recreated and document findings
- [ ] root cause identified
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Moved back to "This Spirint" to focus on two upgrade paths.

**Comment by vijay-veeranki** [comment]
1) Noticed containers still running even when no jobs are running.

fly -t manager workers --details

2) Noticed many active volumes as well, not sure why they are active containers and volumes. 

`    "addr": "172.20.48.129:46167",
    "baggageclaim_url": "http://172.20.48.129:43603",
    "active_containers": 6,
    "active_volumes": 316,
    "active_tasks": 0,`

fly -t manager  workers --verbose --json

    "addr": "172.20.48.129:46167",
    "baggageclaim_url": "http://172.20.48.129:43603",
    "active_containers": 6,
    "active_volumes": 316,
    "active_tasks": 0,

**Comment by AntonyBishop** [comment]
Root cause still be be determined.

**Comment by poornima-krishnasamy** [comment]
When investigating, the volumes table and the containers table was not in sync. Hence, whenever the containers got cleaned up, the corresponding volumes wasnt marked for clean. Looekd similar to the issue https://github.com/concourse/concourse/issues/1745#issuecomment-339984667. The foreign_key was missing in the volumes table and that was the reason the volumes were not cleanup.

The postgres database was deleted and re-created with new schema and after applying the pipelines freshly, the voulmes started to cleanup ok. 

The volume stayed the same level for several days at 3.5%
