### ISSUE TITLE
Create a job to cleanup concourse worker volumes

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3375]
## Background

Concourse worker volumes keep filling up in the directory /concourse-work-dir. We have a ticket to investigate why this is filling up

meanwhile, create a regular job to cleanup the worker volumes.

Information on commands to do cleanup: https://mojdt.slack.com/archives/C514ETYJX/p1637232427234300

## Which part of the user docs does this impact

https://runbooks.cloud-platform.service.justice.gov.uk/destroy-concourse-build-data.html#steps-to-remove-the-build-data

## Questions / Assumptions

Should this need to pause all the jobs?
Should this be run during office hours to check the outcome

## Definition of done

- [ ] job to cleanup the volumes created
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
current workaround:
```
kubectl --context manager -n concourse scale sts concourse-worker --replicas 0 ; for c in {0..3} ; do kubectl --context manager -n concourse delete pvc concourse-work-dir-concourse-worker-$c ; done ; kubectl --context manager -n concourse scale sts concourse-worker --replicas 4
```

**Comment by jasonBirchall** [comment]
Moved back to "This Spirint" to focus on two upgrade paths.

**Comment by vijay-veeranki** [comment]
https://concourse-ci.org/administration.html#fly-land-worker

Instead of killing all pods together and deleting volumes, this land-worker does do the graceful evicting containers.

land-worker calls ATC api to land a worker.

Worker lifecycle:
running --> landing --> landed -->(heartbeat again) --> running.

We can have a job to land one concourse worker pod every 6 hrs?

**Comment by poornima-krishnasamy** [comment]
This ticket is not needed as the actual issue of volumes filling up is resolved.
https://github.com/ministryofjustice/cloud-platform/issues/3374
