### ISSUE TITLE
Create Kuberhealthy Synthetic Checks

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3386]
## Background

After putting our testing requirements to the Kubernetes user channel, they came back with a suggestion that we use a tool called Kuberhealthy that essentially allows you to run tests in a pod.

>Kuberhealthy is an operator for running synthetic checks. By creating a custom resource (a khcheck) in your cluster, you can easily enable various synthetic test containers. Kuberhealthy does all the work of scheduling your checks on an interval you specify (like a CronJob), ensuring they run properly within an allotted timeout, maintaining the current up/down state with durability, and producing metrics. There are lots of useful checks already available to ensure the core functionality of Kubernetes, but checks can be used to test anything you like. We encourage you to write your own check container in any language to test your own applications!
>
>Kuberhealthy serves a simple JSON status page, a Prometheus metrics endpoint (at /metrics), and supports InfluxDB metric forwarding for integration into your choice of alerting solution.
>

## Proposed user journey

I propose we use this tool to tick off a lot of our testing requirements. Anything that requires more in-depth testing should be written in Go.

## Approach

Write up to five of the easiest tests either using the "set menu" [here](https://github.com/kuberhealthy/kuberhealthy/blob/master/docs/CHECKS_REGISTRY.md) or writing them yourself. Report back to the team and start discussion around potential adoption.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidread** [comment]
Would be for the integration tests that are about what "healthy" k8s resources look like, instead of using Go/terratest. Because kube-healthy is more 'native' for this. It's bit of YAML, describing a healthy pod, rather than lots of Go code. And it's quicker - runs inside the cluster.

**Comment by sablumiah** [comment]
Closed ticket with some info from Spike https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/3044
