### ISSUE TITLE
Change the OPA message for "set-identifier" annotation

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3387]
## Background

Please see the slack channel for more info:
https://mojdt.slack.com/archives/C514ETYJX/p1638199158007900

Quick summary:
Users are finding the message below confusing. It should specify exactly what needs changing. For example, if on the live cluster it should specify that it needs to say "blue" rather than "green"

```bash
cannot patch "hmpps-interventions-service" with kind Ingress: admission webhook "webhook.openpolicyagent.org" denied the request: Please add valid external-dns set-identifier annotation for ingress, remember: <ingress-name>-<ns>-<color>. Color is either blue or green
```

## Proposed user journey

Change this message and make it very obvious what to do.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
No longer required.
