### ISSUE TITLE
Decommission non-production cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#339]
## Background

We are no longer using the non-production cluster and we don't want users to use it either. The guide is being updated to remove all reference to the non-production cluster #327 

We need to do away with the non-production cluster.

## Approach

Get rid of the cluster.

## Questions / Assumptions

Check we are not using it very anything before we do away with it.

## Definition of done

- [x] non-production cluster no longer exists

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Messaged the cloud-platform-users slack channel with the following:
jasonb [14:05]
Hi all @here. The Cloud Platform team will be removing the non-production.k8s.integration.dsd.io cluster. This cluster was the precursor to cloud-platform-live.k8s.integration.dsd.io and cloud-platform-test-0.k8s.integration.dsd.io and is now considered redundant. For those of you who require your apps to run on this cluster, please let me know asap and we can look at migrating you off. If you never heard of the non-production.k8s.integration.dsd.io cluster the chances are you've never used it and you can ignore me. :slightly_smiling_face:
If you wish to confirm the cluster name you're working on, you can use `kubectl config get-contexts`.
Thanks.
