### ISSUE TITLE
Use bitnami helm chart for metrics_server

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3411]
As of Nov 13, 2020, charts in this repo will no longer be updated. For more information, see the Helm Charts Deprecation and Archive Notice, and Update.
https://github.com/helm/charts/tree/master/stable/metrics-server

Use bitnami chart for metrics-server
https://github.com/bitnami/charts/tree/master/bitnami/metrics-server

**Comment by pwyborn** [comment]
annotations:
  category: Analytics
apiVersion: v2
appVersion: 0.5.2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Metrics Server is a cluster-wide aggregator of resource usage data. Metrics
  Server collects metrics from the Summary API, exposed by Kubelet on each node.
home: https://github.com/bitnami/charts/tree/master/bitnami/metrics-server
icon: https://bitnami.com/assets/stacks/metrics-server/img/metrics-server-stack-220x234.png
keywords:
- metrics-server
- cluster
- metrics
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: metrics-server
sources:
- https://github.com/bitnami/bitnami-docker-metrics-server
- https://github.com/kubernetes-incubator/metrics-server
version: 5.10.14

**Comment by pwyborn** [comment]
Possible changes:
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring

/metrics-server.tf


namespace =     kube-system 
  repository = "https://charts.bitnami.com/bitnami"
  chart     = "metrics-server"
  version   = "5.10.14"


******************************************************

where metric-server referenced

https://github.com/ministryofjustice/cloud-platform-infrastructure:

terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/README.md

terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/resources/psp/pod-security-policy.yaml

terraform/aws-accounts/cloud-platform-aws/vpc/eks/psp.tf

https://github.com/ministryofjustice/cloud-platform-environments

namespaces/live.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app-eks/resources/values.yaml

namespaces/live-1.cloud-platform.service.justice.gov.uk/cloud-platform-canary-app/resources/values.yaml

**Comment by pwyborn** [comment]
Done - ("manager" and "live"):
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1477
