### ISSUE TITLE
Auth0: Node8 deprecation

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3417]
## Background

The third party provider is deprecating this version in Auth0.

We should check is it's in use or whether any changes are required.

## Definition of done

- [ ] impact of any changes understood
- [ ] stories can be raised for any remediation work

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
Upgraded both prod and dev tennant to use node12 for auth0 rules.
