### ISSUE TITLE
Apply default network policy to live-0 cluster

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#342]
## Background

Creation of default network policy #206 

## Approach

Apply network policy to all namespaces on live-0 by creating a PR and letting pipeline apply
(currently breaks Kiam on test-1 cluster on kube-system namespace)

## Questions / Assumptions

Has been tested on test-1 cluster
Check with teams if some applications need access between namespaces, if so additional access will be required between those namespaces

## Definition of done

- [x] Applies to all namespaces

**Comment by jasonBirchall** [comment]
My understanding is, applying this policy breaks Kiam. I will the install of both on test-1

**Comment by jasonBirchall** [comment]
Will avoid placing a default network policy on the kube-system ns due to it's nature of having to speak to a number of pods (scheduler etc).

**Comment by jasonBirchall** [comment]
PR's are in and merged and network policies have been created in each namespace. Two namespaces have been avoided, ingress-controllers and kube-system. A ticket will need to be created to size up what's required for a default network policy to be applied.

**Comment by jasonBirchall** [comment]
Created ticket: #371
