### ISSUE TITLE
Upgrade CNI to 1.9 on live (on k8s 1.20)

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3420]
This work is split off from #3282 

> We decided to go with addon for cni.

**Comment by vijay-veeranki** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1445
https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/pull/7

**Comment by vijay-veeranki** [comment]
This is applied now on live and manager cluster

https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1445
