### ISSUE TITLE
Investigate alertname="KubeAPIErrorBudgetBurn" in "live" cluster 

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3429]
Investigate and figure out the cause of the alert.

https://mojdt.slack.com/archives/C8QR5FQRX/p1639459995173500

After understanding the issue, amend the alert if needed.

Open issue:
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/615

Some links related to the issue
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/464
https://github.com/prometheus-operator/kube-prometheus/wiki/KubeAPIErrorBudgetBurn
https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeapierrorbudgetburn/

**Comment by razvan-moj** [comment]
reading through the recommendations in https://console.aws.amazon.com/support/home#/case/?displayId=9326408331&language=en

**Comment by razvan-moj** [comment]
Alert is defined in https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kubernetesControlPlane-prometheusRule.yaml#L767

As per EKS best practices (https://aws.github.io/aws-eks-best-practices/reliability/docs/controlplane/#monitor-control-plane-metrics), to debug we need to check these metrics in Prometheus:
apiserver_request_duration_seconds_count
apiserver_request_duration_seconds_bucket
apiserver_request_total
and dig into the API logs (in Cloudwatch -> Log Groups, kube-apiserver trail in /aws/eks/cluster-name) arund the time of the error to see what particular type of request spiked

https://github.com/ministryofjustice/cloud-platform/issues/3493 is an example of debugging
