### ISSUE TITLE
EKS upgrade, rolling upgrade  with pod disruption budget issue

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3432]
While upgrading "live" eks cluster, we had issues where rolling updates stopped in between as there are pod disruption budgets on nodes.

This happened when the Update strategy is selected as "rolling update"
This option respects pod disruption budgets for your cluster. The update fails if Amazon EKS is unable to gracefully drain the pods that are running on this Node Group due to a pod disruption budget issue.

The cause for this failure of the rolling update is that we have poddisruptionbudgets in our "live" cluster.
kubectl get poddisruptionbudgets.policy -A

This ticket is to test rolling update with poddisruptionbudgets, and test why EKS is unable to gracefully drain the pods.

It may be that users use poddisruptionbudgets with min-available as 1 and only running 1 replica.

Also, test if post-forward pod cause this issue as well during a rolling update.

Definition of done:

Figure out the cause of node-recycle issue

**Comment by AntonyBishop** [comment]
Do before next EKS upgrade

**Comment by vijay-veeranki** [comment]
Having Pod disruption budget and port-forward pod, will give below error.

PodEvictionFailure	Reached max retries while trying to evict pods from nodes in node group tenant-vj-default_ng20220208183138166800000019

We need to use Update strategy to force-update
