### ISSUE TITLE
Create a two new alert receivers

### ISSUE THREAD

**Issue by andrewrlee** [ministryofjustice/cloud-platform#3436]
Information as requested here: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-slack-webhook-and-amend-alertmanager:

namespace name: (multiple)
team name: Entering and leaving prison
application name: (multiple)
kubernetes secret name where the webhook url is stored: please DM me via slack for webhook. @Andrew Lee

severity level/channels: 

level: elp_alerts_security
slack channel: #elp_alerts_security

level: elp_alerts
slack channel: #elp_alerts

**Comment by vijay-veeranki** [comment]
Created alert receivers for 

level: elp_alerts_security
slack channel: #elp_alerts_security

level: elp_alerts
slack channel: #elp_alerts
