### ISSUE TITLE
Pingdom Integration Ids for evidencelibrary-prod namespace

### ISSUE THREAD

**Issue by sivafirst** [ministryofjustice/cloud-platform#3449]
1)
## Service name
evidence-library-ui

## Service environment
- [ ] Prod / Production

## Impact on the service
The evidence-library front-end  site ping is unsuccessful and may be returning errors. 

## Problem description
The evidence-library front-end  site is returning non OK status code and may not be usable.

## Contact person
slacK : #performance-hub-dev

## Host uri
evidence-library-prod.apps.live.cloud-platform.service.justice.gov.uk
PR file changes: https://github.com/ministryofjustice/cloud-platform-environments/pull/6466/files

2)
## Service name
evidence-library-api

## Service environment
- [ ] Prod / Production

## Impact on the service
The evidence-library back-end api health ping is unsuccessful and may be returning errors. 

## Problem description
The evidence-library front-end  site is may not be usable.

## Contact person
slacK : #performance-hub-dev

## Host uri
evidence-library-api-prod.apps.live.cloud-platform.service.justice.gov.uk/health
PR file changes: https://github.com/ministryofjustice/cloud-platform-environments/pull/6466/files

**Comment by sivafirst** [comment]
please provide the new integration ids on the slack(#performance-hub-dev or @Sivaprasad Sighakolli ) when this is completed.

**Comment by vijay-veeranki** [comment]
Integration id already available for  #performance-hub-dev which is “114774”

Can be used for multiple applications.
