### ISSUE TITLE
Instructions for setting up kubectl appear to be  incomplete

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#345]
## Background

Issue highlighted from user feedback.

![image](https://user-images.githubusercontent.com/36888942/44783625-d6a47380-ab82-11e8-8ef4-3d2e151f287b.png)

Reference in guide - https://ministryofjustice.github.io/cloud-platform-user-docs/01-getting-started/001-kubectl-config/#multiple-clusters

## Proposed user journey

Guide will enable user to set up kubectl without issues.

## Approach

Update the guidance improve users ability to set up kubectl first time. Measured by reduction in users raising issues with this part of the guide.

## Questions / Assumptions

Error identified can be investigated and missing information can be added/guidance can be improved. We have a user we can test this with.

## Definition of done

- [x] Reason for users issue identified
- [x] User guide updated
- [x] Tested with a user (speak to Tony about identifying a user)

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Error in user feedback. See below

**Comment by AntonyBishop** [comment]
![Screen Shot 2018-08-30 at 15.34.49.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5af99512f7ba4500119c1fce/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6457f36b7191a379ea0c2855415b47be5d4a1f06a3a3dc78e2a436628f0d5de883680d73c63f18acbb861fbf03bf76d84d83e0e99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecb5df048e84a56a0113366f43b.png)

**Comment by razvan-moj** [comment]
user fixed! https://github.com/ministryofjustice/cloud-platform-user-docs/pull/62
