### ISSUE TITLE
Enable Couldwatch logs for Users Elasticsearch as part of tf module

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3452]
## Background

Users want to enable cloudwatch logs for elasticsearch service domains and be available in the console for emergency access.

Previous approach here: https://github.com/ministryofjustice/cloud-platform-environments/commit/d2d0e1669c25c827b58eafe14325a3f43a3d9b90#diff-e322455f14f4dfc22be2ea78c351f186b166427770b7073b050afd6fd4a662ac

This approach will create resource Policy per log group. But there is a hard limit of 10 per account. 

Hence, Create log group for each of elasticsearch inside the terraform module and attach it to a shared policy created already.
More details in slack thread: https://mojdt.slack.com/archives/C514ETYJX/p1641550748049100

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch/blob/main/README.md

## Questions / Assumptions

Where do the shared resource policy will be created?

## Definition of done

- [ ] cloudwatch log group created and enabled for users ES
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
This is blocking:
[](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/3187)
