### ISSUE TITLE
AWS console Read-Only Access 

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3453]
## Background

Based on user feedback, users would like Read-Only AWS console access. This will help teams to understand how what they describe as IAC behaves in AWS. It will aid troubleshooting and help with access for ITHCs.

## Proposed user journey

A users will be able to access the Cloud Platform AWS account via SSO and be able to see information about their AWS resources.

Relevant: [ADR07 Console access for users](https://github.com/ministryofjustice/cloud-platform/blob/main/architecture-decision-record/027-AWS-Console-access-for-users.md)

## Approach

TBC

## User Stories from Round one of UR

As A ??? 
I Need to learn how the AWS resources is configured 
So that I understand why it operates in this way

As A 3rd party health check user 
I Need read only access 
So that I can ensure that MOJ is compliant with the ITHC

As A MOJ TA 
I Need to have read only access to AWS and the CP infrastructure 
So that I can ensure that MOJ is compliant with the ITHC

As A Service Team Developer 
I Need read only to AWS access 
So that I can view my teams resources

As A developer or Web ops 
I Need read only to AWS access 
So that I can help the team quicker than using IAC

As A Developer 
I Need to learn how the AWS resources is configured 
So that I understand why it operates in this way

As A cloud platform team 
We need to ensure read only to AWS access is at the right level for each user 
So that devs do not have access to infrastructure they don't need

As A cloud platform user 
I need read only access to the AWS console 
So that I do not have to ask the Cloud Platform for their help as often

As A cloud platform user 
I need read only access to the AWS console 
So that I can debug issues and fix them

As A cloud platform user 
I need read only access to the AWS console 
So that I can investigate when an issue has occurred

As A technical architect  
I need read only access to the AWS console 
So that I can assess the impact of my teams work, gather insight and check performance

As A cloud platform user 
I need read only access to the AWS console 
So that I can see background information and carry out an audit

As A cloud platform user 
I need read only access to the AWS console to explore it 
So that I can view possible new elements of AWS that may be used by my team

## Which part of the user docs does this impact

New section.

## Questions / Assumptions

Questions raised for Round 2 of UR by team

Would you be ok for other users to have read access to your resources?
What sort of savings do you envisage?
Where would you go to learn about AWS Console?
What benefit would you get from having a sandbox environment?
What makes it difficult to experiment on CP?
Would a self managed app with the same functionality of same redis vs elasticache solve your problem?

TBC

## Definition of done

- [ ] TBC
- [x] Canvas team to create UR approach
- [x] Initial round of UR to gather feedback from users (6 users)
- [x] Follow on Canvas using outputs fromRound one UR analysis
- [x] Starter user stories from round one UR
- [x] Workshop with users and Cp team to share thoughts and ideas
- [x] outputs from workshop shared with PM https://docs.google.com/document/d/1L_NSLKpq19YzjLgnDWP7n8zoCNs9e4pTgz47HlKdzD8/edit?usp=sharing 

## Learning from Mod Plat Team
AWS comes with read only policies which are easy to use
Use RBACK (?) - attribute based access control, allows you to tag users to determine what they can see
Jake M will need to approve PRs

## Reference 

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
@razvan-moj:
From Jake re their SSO (may or maynot be relevant):
https://github.com/ministryofjustice/aws-root-account/blob/main/terraform/sso-admin-account-assignments.tf

**Comment by razvan-moj** [comment]
will resume after FB

**Comment by ScottSeaward** [comment]
Added UR aspects to ticket

**Comment by AntonyBishop** [comment]
Revisit when EKS and ingress upgrade completed

**Comment by vijay-veeranki** [comment]
revisit once live-1 clean up complete

**Comment by razvan-moj** [comment]
Went through the steps described in https://dev.classmethod.jp/articles/session-tag-auth0/
still stuck at "Your request included an invalid SAML response. to logout, click here."

**Comment by AntonyBishop** [comment]
New tickets raised for next steps.
