### ISSUE TITLE
(Re)create cluster with a MOJ-unique IP range

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3454]
This is to enable the Tech Ops to run their DHCP+DNS service on Cloud Platform (instead of maintaining their own EKS cluster, which is an aim of Hosting). They need traffic to communicate via Transit Gateways with the prison sites, but they use IP ranges that fully clash with Cloud Platform's VPC CIDR of 172.20.0.0/16 (used by `live`). And we just aren't going to get them to change, so we need to.

We should get an IP range allocated in the MOJ master list: https://github.com/ministryofjustice/transit-gateways#cidr-blocks

Then we need a cluster with this new range that Tech Ops can deploy onto. This is likely to need [Multi-Cluster work](https://docs.google.com/document/d/1-1dXD0a50MZiQUcm4fIIO1ySVQHA_D2-UMIti-oBVNc/edit#) one way or the other - either a new cluster with all the tooling for us to easily transition existing work loads to it (Stage 2), or an additional cluster (Stage 3).

**Comment by jakemulley** [comment]
CIDR range has been repurposed for our use. See [Slack thread](https://mojdt.slack.com/archives/C514ETYJX/p1666952433214819?thread_ts=1665581872.894299&cid=C514ETYJX).

**Comment by AntonyBishop** [comment]
Superseded
