### ISSUE TITLE
Request to amend the existing SQS module to support FIFO

### ISSUE THREAD

**Issue by arthurashman** [ministryofjustice/cloud-platform#3456]
## Service name

ministryofjustice/cloud-platform-terraform-sqs

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

[LAA Court Data Adaptor ](https://github.com/ministryofjustice/laa-court-data-adaptor/) (CDA) has a requirement for SQS queue items to be remain in a guaranteed order and so wants to implement a First In First Out (FIFO) SQS queue instead of a standard SQS queue. 

## Problem description

Request to amend the existing module to support FIFO https://github.com/ministryofjustice/cloud-platform-terraform-sqs/blob/main/main.tf

## Contact person

Arthur Ashman
arthur.ashman@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
done
