### ISSUE TITLE
Alert Manager slack channel webhook

### ISSUE THREAD

**Issue by brenetic** [ministryofjustice/cloud-platform#3458]
We would like to have an alert manager alert for slack please.

namespace name: formbuilder-services-live-production

team name: MoJ Forms / Form Builder

application name: N/A

slack channel: #form-builder-alerts-400s

kubernetes secret name where the webhook url is stored: 
  this can be found in:
    namespace: formbuilder-repos
    secret name: slack-webhooks
    property key: 400s

severity level (warning/information): high

**Comment by poornima-krishnasamy** [comment]
Hi @brenetic , the severity label to use for the alerts is `form-builder-400s`
