### ISSUE TITLE
Correct code type on "Tear it all down"

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#347]
## Background

Feedback from user.

![image](https://user-images.githubusercontent.com/36888942/44784190-afe73c80-ab84-11e8-8147-8b277a6bb966.png)

Reference in guide - https://ministryofjustice.github.io/cloud-platform-user-docs/02-deploying-an-app/001-app-deploy-helm/#scale-the-application

Typo user **"Tear it all down"**

## Approach

Correct typo in guide.

## Definition of done

- [x] Guide updated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-user-docs/pull/72
