### ISSUE TITLE
Spike: kuberhealthy

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3481]
## Background

See #3359 - "There are tools that we've spiked during firebreaks that enable us to run synthetic tests against Kubernetes components. One that I'd like to mention here is kuberhealthy. This would allow use to other tools recommended by other Kubernetes users, maintained by other people, to tell us the same thing we're wasting time re-inventing.

Advantages:
- We don't have to maintain any code.
- If we choose Kuberhealthy, we could contribute to the already large community of users.

Disadvantages:
- If we choose Kuberhealthy, we have to install a controller in the cluster.
- YAML ;)

## Questions / Assumptions

TBC

## Definition of done

- [ ] We can make a decision on how to implement kubehealthy.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
https://docs.google.com/presentation/d/1pedJHeQ4FJ7mSEX-R7pYIXiq6jrNHlE7udj1ckXGcms/edit#slide=id.g12402e02225_0_73

**Comment by pwyborn** [comment]
Slide conclusion:
https://docs.google.com/presentation/d/1wP8zsllI-tDIAJw6NIgqDS_H8CsFCJ_QjHdALTwRcFo/edit#slide=id.p
