### ISSUE TITLE
Create guidance about internal traffic and domain names, and advertise to users in slack

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3497]
## Background

This came after the incident review
Currently, users who have apps/services running on different namespaces (e.g. frontend , backend ) create domain url to communicate between the services. 

Most of the cases they use `live-1` urls. Write a guidance on how the can use NetworkPolicies and use the svc.name to connect between the namespaces. 

## Which part of the user docs does this impact
https://user-guide.cloud-platform.service.justice.gov.uk/#cloud-platform-user-guide
Could be a new page Under Concepts, but leave this to whoever picks the ticket to decide

## Definition of done

- [ ] user guide page created
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] Slack message posted to users about this

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Duplicate
