### ISSUE TITLE
Create pingdom alerts for test helloworld apps

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3498]
## Background

We should monitor the domains supported by Cloud Platform. Create pingdom alerts to a url under 
'apps.live-1' , and 'apps.live' on live cluster as well as 'apps.live-1' on live-1 cluster. 

Can use canary app to create those ingresses on live cluster. But need deploying another one on `live-1` cluster.

Question:
Should this go to high priority or low priority channel?

## Definition of done

- [ ] Pingdom alert created for all the domains mentioned
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
No longer required. We should prioritise moving users off "Live-1" domains
