### ISSUE TITLE
Change the ErrorsInExternalDNS alarm to high priority

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3500]
## Background
During migration, users has to update their ingress with 2 external-dns annotations. If the ingress is created in live-1 cluster without the annotation, external-dns throw error. and a alert is triggered on lower-priority channel.

This error stops external-dns from writing anymore records to that zone and hence users cannot deploy new ingresses. 

Change the alert to high-priority channel
https://mojdt.slack.com/archives/C8QR5FQRX/p1642825047045400

## Definition of done

- [ ] high priority alarm created for the error
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
No longer required.
