### ISSUE TITLE
DSD Kibana Authentication

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#352]
**Background**

The security team have made us aware of a flaw in our elasticsearch/kibana setup. 

Currently, kibana is accessible via the MoJ digital IP range only but the is no authentication on this. Meaning anyone on the network has access without audit trail.

The Cloud-Platform team are required to place authentication on the kibana front end and force https.  

**Approach**

Research how AWS recommend addressing this issue. Depending on the solution we will need to create some smaller stories to implement a solution.

**Definition of Done**

- [x] We understand how to resolve the issue
- [x] We have identified the steps required to mitigate the risk
- [x] We can create a number of further stories to deliver the work
- [x] Implement the changes required
- [ ] Update documentation
- [x] Test with Security

**Comment by razvan-moj** [comment]
https://dsd-kibana.apps.cloud-platform-live-0.k8s.integration.dsd.io is available to test, config in https://github.com/ministryofjustice/cloud-platform-environments/pull/161
Also added live-0 IPs to DSD ElasticSearch policy so that the proxy itself can reach Kibana.

**Comment by razvan-moj** [comment]
Switched the redirect:
```$ AWS_PROFILE=dsd aws s3api get-bucket-website --bucket kibana.service.dsd.io
```
before
```
{
    "RedirectAllRequestsTo": {
        "HostName": "elasticsearch.dsd.io/_plugin/kibana"
    }
}
```
after
```
{
    "RedirectAllRequestsTo": {
        "HostName": "dsd-kibana.apps.cloud-platform-live-0.k8s.integration.dsd.io/_plugin/kibana"
    }
}
```

**Comment by razvan-moj** [comment]
Removed office IP from ES access policy, the cluster can only be accessed now after authentication.
