### ISSUE TITLE
Upgrade prometheus pushgateway chart 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3522]
Pushgateway feature is available for users through terraform module. https://github.com/ministryofjustice/cloud-platform-terraform-pushgateway. The HOODAW reports shows the helm chart version is outdated.

```
installed: 1.5.0
latest: 1.15.0
```

- Upgrade the push gateway version to latest.
- Bump the module version of all users

## Definition of done
- [ ] pushgateway upgraded
- [ ] Users module updated
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Looks like this was done. No longer appears in reports. Closed.
