### ISSUE TITLE
Ingress golang test is failing in "live" cluster

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3538]
We noticed that Ingress golang test is failing in the "live" cluster.
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/live-integration-tests/builds/763
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/live-integration-tests/builds/750

Maybe it is due to load is increased in the "live" cluster and ingress creation is taking time to resolve.

Investigate the issue and update the golang tests.

Conversation related to it:
https://mojdt.slack.com/archives/C514ETYJX/p1643285666497909

**Comment by AntonyBishop** [comment]
No longer an issue. Test running successfully.
