### ISSUE TITLE
Leavers - Suha Akyuz

### ISSUE THREAD

**Issue by sid234** [ministryofjustice/cloud-platform#354]
To Follow leavers process

https://dsdmoj.atlassian.net/wiki/spaces/PLAT/pages/324076142/Leavers

**Comment by pwyborn** [comment]
See https://docs.google.com/document/d/1U2e96wQCNR1Y9a_ocgwh2QmDBvZSLvmntSqeIKW85Ak/edit?ts=5b979ad9#

**Comment by pwyborn** [comment]
Done - subject to pull-request reviews
caveat - done subject to digitalservicedesk having carried out leavers procedure as requested
