### ISSUE TITLE
Request for matching NS record for new hosted zone

### ISSUE THREAD

**Issue by mxco86** [ministryofjustice/cloud-platform#3545]
## Service name

Probation Integration

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

New hosted zone mapping required so we can use it

## Problem description

Please could you create a matching NS record in the DSD account for a new domain

`probation-integration.service.justice.gov.uk`

The hosted zone is defined in this PR: https://github.com/ministryofjustice/cloud-platform-environments/pull/7080

## Contact person

Slack: @Matt Ryall
Email: matthew.ryall@digital.justice.gov.uk

**Comment by vijay-veeranki** [comment]
NS records added to dsd account for probation-integration.service.justice.gov.uk
