### ISSUE TITLE
Update Transit Gateway Doc

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#3546]
The Transit gateway documentation was written for the use of live-1 only

Update the docs to either add cater for both clusters, or change to read for the use of live cluster

https://github.com/ministryofjustice/transit-gateways/tree/master/terraform/cloud-platform

**Comment by AntonyBishop** [comment]
Runbook appears to have been updated.

**Comment by AntonyBishop** [comment]
Runbook appears to have been updated.
