### ISSUE TITLE
Moving People Safely System Down for GeoAmey users

### ISSUE THREAD

**Issue by pazinlondon** [ministryofjustice/cloud-platform#355]
## Service name
Moving People Safely
<!Moving People Safely>

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

System Down for court users on the GeoAmey network

## Problem description

GeoAmey have changed IT supplier and as a result their external IP address has changed. We need to add the new IP range 80.86.46.16 - 80.86.46.18 to our IP whitelist

## Contact person

paul.smith@digital.justice.gov.uk

**Comment by nayoa** [comment]
https://github.com/ministryofjustice/moving-people-safely-deploy/pull/70

**Comment by nayoa** [comment]
IP range has been whitelisted on Production. After conversation with Paul Smith, he has confirmed users are now have access to the system.
