### ISSUE TITLE
NS record for SOC namespaces

### ISSUE THREAD

**Issue by carlosMoJ** [ministryofjustice/cloud-platform#3557]
## Service name

HMCTS Risk Assurance Operating Controls

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other: this will apply to all namespaces/environments

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

hopefully no real impact...

## Problem description

We are migrating 2 products from a different AWS account (tacticalproducts) to Cloud Platforms. We have the namespaces ready in CP and we want to start migrating Dev & Staging domains. The domain is: 

hmcts-risk-assurance-operating-controls.service.justice.gov.uk

and These are the 1st subdomains/CNAMES I will create:

dev.entry.hmcts-risk-assurance-operating-controls.service.justice.gov.uk
dev.reporting.hmcts-risk-assurance-operating-controls.service.justice.gov.uk
staging.entry.hmcts-risk-assurance-operating-controls.service.justice.gov.uk
staging.reporting.hmcts-risk-assurance-operating-controls.service.justice.gov.uk

Those are already in use on the tacticalproducts account, so I will remove them from that account as I start migrating.

Please, can you confirm that this change will not affect the current PRODUCTION domains:

https://entry.hmcts-risk-assurance-operating-controls.service.justice.gov.uk
https://reporting.hmcts-risk-assurance-operating-controls.service.justice.gov.uk

I still want those domains to point to the tacticalproducts AWS account (Elastic Beanstalk)

Many thanks

## Contact person

Carlos Fernandez
carlos.fernandez@digital.justice.gov.uk

**Comment by carlosMoJ** [comment]
The current 'value/route traffic to' for hmcts-risk-assurance-operating-controls.service.justice.gov.uk  is:

ns-624.awsdns-14.net.
ns-49.awsdns-06.com.
ns-1506.awsdns-60.org.
ns-1624.awsdns-11.co.uk.

But I just want to confirm/triple check that this change will not affect the current production URLs:

https://entry.hmcts-risk-assurance-operating-controls.service.justice.gov.uk/
https://reporting.hmcts-risk-assurance-operating-controls.service.justice.gov.uk/

which are still pointing to AWS Elastic Beanstalk in the tacticalproducts account.

Thanks

**Comment by vijay-veeranki** [comment]
Hi Carlos,
Discussed with the team, and like to use the below approach as we did for other users

- Convert all the DNS entries currently have in your account to terraform.
- Once it is created in CP route 53, compare that it and check all is in place.
- Switch the NS in the DSD(This won't have any downtime). Existing records should not removed from the one in your AWS account until the propagation is complete(prob a day or more).

**Comment by vijay-veeranki** [comment]
Guidance on how to add existing records CP using terraform
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/route53-zone.html#add-dns-records-to-a-route53-zone

**Comment by carlosMoJ** [comment]
Hi Vijay, does this mean we cannot do this until we are ready to switch over all the domains to point to our new cloud platform namespaces? I don't fully understand

**Comment by carlosMoJ** [comment]
or is the suggestion that I move the Route 53 from my current account (tacticalproducts) to the Cloud Platform account and have our production records/URLs pointing to Elastic Beanstalk (in tacticalproducts account) and have dev & staging records/URLs pointing to the cloud platform namespaces?

**Comment by vijay-veeranki** [comment]
NS records added to dsd.

**Comment by carlosMoJ** [comment]
Thanks. The dev & staging domains are now pointing to Cloud Platform. Only Production is pending - should we keep this ticket open till we go live? or should we close it now?

Thanks
C
