### ISSUE TITLE
Add windows tests for cloud-platform-cli

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3558]
Windows version of the Cloud Platform CLI is available with this [PR](https://github.com/ministryofjustice/cloud-platform-cli/pull/65), but there doesn't appear to be any tests running against it as this has been removed [here](https://github.com/ministryofjustice/cloud-platform-cli/pull/28/files)

Add those tests back
https://github.com/ministryofjustice/cloud-platform-cli/pull/28/files

**Comment by jasonBirchall** [comment]
We've since removed the widows binary build.

**Comment by jasonBirchall** [comment]
We've since removed the widows binary build.

**Comment by jasonBirchall** [comment]
... this is because of the directory structure assumptions we've made.
