### ISSUE TITLE
DNS migration for Find Unclaimed Court Money.

### ISSUE THREAD

**Issue by rohanssalunkhe** [ministryofjustice/cloud-platform#3562]
Find unclaimed court money

 Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [x] Other - this will apply to all namespaces/environments

Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Current live domain pointing to cloud platform hosted service.

Problem description

We want the current DNS (which is in tacticalproducts account) to be pointing to CP production namespace record so that we can move away from current hosting to cloud Platform.
We have the namespaces ready in CP and we want to start migrating production domain. 

The domain is as below
https://find-unclaimed-court-money.service.justice.gov.uk/
Can you please give me an estimate of how long it will take and also let me know before actually switching the DNS.
Thanks.

Contact person

Rohan Salunkhe
rohan.salunkhe@digital.justice.gov.uk

**Comment by vijay-veeranki** [comment]
This is migrated to cp now
