### ISSUE TITLE
New AlertManager route for SendLegalMail

### ISSUE THREAD

**Issue by nathanrussell-moj-digital** [ministryofjustice/cloud-platform#3564]
## Service name

send-legal-mail-to-prisons

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description

Please can you create a new alert route in AlertManager for:

- Namespace: send-legal-mail-to-prisons-dev
- Team name: Farsight Developers
- Application Name: send-legal-mail-to-prisons
- Slack channel: #farsight-alerts
- Kubes secret: ALERTMANAGER_WEBHOOK
- Severity Level: warning

## Contact person

Nathan Russell, nathan.russell@digital.justice.gov.uk,

**Comment by vijay-veeranki** [comment]
severity = "farsight-alerts"
