### ISSUE TITLE
Namespace deleting

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3573]
## Background

We have confirmed that a number of namespaces on `Live-1` can now be deleted. The list as follows:

```
sm-dev
sheffield-demo
shared-test-zone
ryanforsyth-dev
rja-sandbox
raz-test-one
proffeapp-dev
probation-prod
poornima-staging
poornima-demo
probation-case-sampler-dev
offender-categorisation-prod
offender-categorisation-preprod
mryall-dev
moj-ds-accessibility-audit
mayowa-hello-world-test-dev
markberridge-dev
manage-soc-cases-prod
learning-cloud-deployments-dev
laa-get-access-service-improvement
laa-court-data-adaptor-prod/resources
laa-aws-dev
jason-lab
jason-demo
jacob-hello-world-dev
helloworldapp-dev
estatesdb-dev
prison-data-compliance-prod
c100-application-metabase
abundant-namespace-dev
offender-management-production
```

We have permission from teams to delete these namespaces.

## Approach

Delete all the namespaces from Live-1

## Which part of the user docs does this impact

N/A

## Definition of done

- [ ] Namespaces deleted from Live-1

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Removed namespaces and cleared terraform resoruces
