### ISSUE TITLE
Increase ingress limits

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#358]
## Background

@aldavidson noticed header size limit is too low at the default 4k, causing 502 errors on POST; @kerin also suggests increasing the default 2m body size

## Approach

The config currently in use (`$ kubectl -n ingress-controllers edit configmap nginx-ingress-controller`) needs to be edited and documented to make future adjustments easy

## Definition of done

- [ ] must compile
- [ ] configmap edited to have proxy-buffer-size 16k and client_max_body_size 16m
- [ ] config applied to test-1 and live-0

## Reference

https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization
https://www.nginx.com/resources/wiki/start/topics/examples/full/

**Comment by alkar** [comment]
I'll also leave this here http://danielfm.me/posts/painless-nginx-ingress.html

We deploy the controller with helm so the correct approach would be to update the [`values.yaml` file](https://github.com/ministryofjustice/kubernetes-investigations/blob/master/cluster-components/nginx-ingress/cloud-platform-live-0-helm-values.yaml)
