### ISSUE TITLE
Investigate what those 900k ec2 snapshots are for?

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3584]
## Background

CP account has nearly 900k snapshots which can be listed here:
aws ec2 describe-snapshots --no-paginate --output text | wc -l

Investigate whether CP needs all of them.

## Questions / Assumptions

What form part of these snapshots?
Is any regular cleanup activity needed ?

## Definition of done
- [ ] identified the reason for those many snapshots
- [ ] written tickets if any regular cleanup activity needed
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
old and dupe, should be closed
