### ISSUE TITLE
Review "Deleted terraform state" Runbook

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3599]
## Background

Review of runbooks as a result of migration to EKS

Review [Deleted terraform state](https://runbooks.cloud-platform.service.justice.gov.uk/disaster-recovery-scenarios.html#deleted-terraform-state)

Review runbook. Is Runbook still relevant. Update as required.

Story may require testing of process.

## Definition of done

- [ ] Recovery plan tested (optional)
- [ ] Runbook updated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Review completed as part of disaster recovery scenarios review:
https://github.com/ministryofjustice/cloud-platform/commit/351692dbcc6c549b630a868bf93869a29b0b5fab
