### ISSUE TITLE
Serverless Research

### ISSUE THREAD

**Issue by ScottSeaward** [ministryofjustice/cloud-platform#3605]
## Background

From a survey sent from the Cloud Platform team, users highlighted Serverless as something they were interested in.

## Proposed user journey

Find out more about Serverless and gather a team understanding of what it entails. 

## User Stories

As a Cloud Platform team
We need to understand what new approaches or technologies our users are interested in
So that we can ensure we are meeting users needs

## Approach

Desk research to gather information followed by a team workshop to discuss the findings.

## Which part of the user docs does this impact

TBD

## Questions / Assumptions

What does it mean to be Serverless?
How would this benefit MoJ?
How would this impact the CP offering?

## Outputs from workshop 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-7651ebf2-7fff-7137-ac22-e23de8f46d13"><div dir="ltr" style="margin-left:0pt;" align="left">

Research Assumption | Team Comments
-- | --
Serverless is anything that executes business logic that does not require any Server. | We still have infrastructure. Our whole cluster is serverless, we manage everything. We already provide these services for our users, what else do they need?
Serverless removes the Operation aspect of DevOps. | In isolation yes, but this still needs to be done (CP) still need Dev Ops
No-Ops. No infrastructure or OS to maintain! | Not true in the MoJ and Gov structure
Easy to use and easy to learn, you just write small functions! | Whats the capability level of MOJ users An expectation for everyone to adopt that style Creates a management overhead, more support needed.
We use one of the main supported languages such Python, JavaScript, Go, Java... | How many users know how to add a Lambda layer? What does this solve for users?
We've migrated to the cloud and use containers so what's the point of Serverless? | What is this going to solve for us? How? Are there teams that are not using containers that could use serverless?
Easy to manage just set the RAM, integrate with IAM and set the triggers. | You can't do anything you want, these need to be managed by the CP team.

</div></b>

## Definition of done

- [x] desk research collated
- [x] team workshop
- [x] outputs recorded
- [x] create follow on research and add to UR plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Highlighted need for further research. ADR to be created.
