### ISSUE TITLE
Implement a script to check terraform workspace == cluster before doing plan/apply

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3612]
## Background

When applying cluster and components, there might be a time when terraform workspace point to the wrong cluster. This ticket is to work on a script can be run before plan/apply is done to check the workspace==cluster. 

This will avoid applying to wrong cluster because of wrong environment variables set where it is run.

## Definition of done

- [ ] script implemented and executed to run before terraform plan and apply
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
Working on select-cluster-config on the https://github.com/ministryofjustice/cloud-platform-cli repository, I have created a new command called terminal which when used will setup a terminal that sets up the kubeconfig as well as setting the tf workspace to match the cluster name

**Comment by jackstockley89** [comment]
https://github.com/ministryofjustice/cloud-platform-cli/pull/170

**Comment by jackstockley89** [comment]
not going ahead with change
