### ISSUE TITLE
Ramp up the new ingresses

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#3619]
As we're ready to migrate users, we'll also set the number of controllers in https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf from 2 to 6

**Comment by vijay-veeranki** [comment]
This is completed now
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf#L85-L115
