### ISSUE TITLE
Test user PDB configs that caused EKS upgrade failure 

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#3622]
There were a number of deployments thats used PDB that caused the EKS upgrade to fail. 

Create deployments using similar/same PDBs from the following pods/deployments and initiate a node group update.  

hmpps-book-secure-move-api-deployment-dev-69c675f5ff-4r584	        
hmpps-workload-987465dcd-h44gk	                                      
wmt-worker-fcb94bd9d-9v4t2	                                          
send-legal-mail-to-prisons-gotenberg-5675648cfc-cpxtz	                
create-and-vary-a-licence-gotenberg-5955698c87-g5k2d	                
offender-events-ui-7cc7586b9c-8mq6g

**Comment by AntonyBishop** [comment]
To do prior to next k8s upgrade

**Comment by AntonyBishop** [comment]
Superseded
