### ISSUE TITLE
Create user guide for "migrating ingress to v1 ingress controllers"

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3626]
Add user guide for changes to the ingress definitions to move from nginx & modsec01 ingress controller to `default` & modsec v1 ingress controller. This is prerequisite for k8s 1.22 upgrade

Find out the steps for users how the need to move the ingress controller
This includes default steps to migrate with accepting the dns propagation and optional seamless migration using route53 weighted. 

https://mojdt.slack.com/archives/C514ETYJX/p1645700886686269
https://mojdt.slack.com/archives/C514ETYJX/p1646045785926059

Update the existing user guide https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/apiversion-changes-ingress-k8s-1-22.html#removing-deprecated-ingress-apis-for-k8s-1-22 to include this

Guide should cover,
- why they have to make it
- before and after code examples
- how can they test it
- how do they rollback(if needed)

## Definition of done

- [ ] User guide entry created 
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Created run-book.
https://runbooks.cloud-platform.service.justice.gov.uk/Switch-ingress-to-v1-ingress-controller.html#switch-ingress-to-v1-supported-ingress-controller

This needs to be converted to a user guide, this can be done once we try a couple of our apps switching to the new ingress controller and make any changes to the runbook if we come across anything during switching over our apps.

Will create a new Story to convert that to userguide and comms to be sent related to it.
