### ISSUE TITLE
Update our code examples w.r.t v1 ingress Class changes

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3627]
Follow the user guide for the changes to migrating ingress to v1 ingress controllers and update the user-guide, runbooks and other code examples to use v1 default/modsec ingress controller

user guide examples
reference app code
any ingress definitions in environments

## Definition of done

- [ ] All code examples updated
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
Blocked by: https://github.com/ministryofjustice/cloud-platform/issues/3626

**Comment by vijay-veeranki** [comment]
![Screenshot 2022-06-13 at 16.13.02.png](https://images.zenhubusercontent.com/5cd14e5c7c13c23a96974cd6/8e0cddd2-46ca-4120-babd-d8e61baaa62c)

During switch over to new v1 ingress controller following the runbook

**Comment by vijay-veeranki** [comment]
user guide examples can only be updated before sending the comms out.

**Comment by vijay-veeranki** [comment]
CP ingress definitions in environments is updated
