### ISSUE TITLE
Create a route from live.cloud-platform.service.justice.gov.uk to TGW

### ISSUE THREAD

**Issue by anildhiman-laa** [ministryofjustice/cloud-platform#3637]
Create a route from live.cloud-platform.service.justice.gov.uk to TGW

## Service environment
- [ ] Dev 
- [ ] UAT
- [ ] Staging
- [ ] Other

## Impact on the service

Without it, we cannot have our CI pipeline completed. At the moment we get our test results full of connection errors.

## Problem description

We need connectivity from live.cloud-platform.service.justice.gov.uk cluster to the OPS cluster, without it we cannot have our CI pipeline completed. At the moment we get our test results full of connection errors.

## Contact person

Anil Dhiman, https://mojdt.slack.com/archives/D02EWDWKE2U, anil.dhiman@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
Updating the slack thread: https://mojdt.slack.com/archives/C57UPMZLY/p1647946197609789

**Comment by vijay-veeranki** [comment]
Hi @anildhiman-laa

We hold off applying the below change, as we are not sure if this is your requirement? , also adding this CIDR to the routing table will create a new route to our VPC, so the cloud-platform team want to understand if applying this is what you need to get it connected to OPS?


https://github.com/ministryofjustice/transit-gateways/blob/3606b35a98ec3954351bd0c457dd49159ba7cce5/terraform/cloud-platform/routes.tf#L55-L60

**Comment by oliverweighell** [comment]
To update on this....

As we understand it, the destination CIDR block in the [current entry](https://github.com/ministryofjustice/transit-gateways/blob/3606b35a98ec3954351bd0c457dd49159ba7cce5/terraform/cloud-platform/routes.tf#L55-L60) is to the 'test' environment in LAA zone only. @anildhiman-laa needs to connect to other non-prod envs however (stage, uat, dev). We have requested that LAA ops create a PR to update the route entry accordingly - ticket here https://dsdmoj.atlassian.net/browse/LAWS-2154

**Comment by vijay-veeranki** [comment]
Hi @anildhiman-laa @oliverweighell 

This is been applied now on cloud-platform
https://github.com/ministryofjustice/transit-gateways/blob/3606b35a98ec3954351bd0c457dd49159ba7cce5/terraform/cloud-platform/routes.tf#L55-L60
