### ISSUE TITLE
Add NS record to DND account for courts-local-scorecard

### ISSUE THREAD

**Issue by willmcb** [ministryofjustice/cloud-platform#3638]
## Service name

Crown Court Local Scorecard

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

This service acts as a landing page for the criminal justice score card statistics.

## Problem description

We need a custom domain for production to be: 

https://criminal-justice-scorecard.justice.gov.uk/ 

## Contact person

@ministryofjustice/local-scorecard

**Comment by vijay-veeranki** [comment]
NS records added to justice.gov.uk in dsd account
