### ISSUE TITLE
Upgrade managed EKS CNI Add-ons for v1.21

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3640]
Upgrade managed EKS CNI Add-ons for v1.21

VPC CNI
https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html

**Comment by vijay-veeranki** [comment]
Blocked until these get resolved:

aws/amazon-vpc-cni-k8s#1930
aws/amazon-vpc-cni-k8s#1425

**Comment by AntonyBishop** [comment]
Check current status of blockers

**Comment by AntonyBishop** [comment]
No longer required. Replaced by newer story.
