### ISSUE TITLE
Victim Information Service down - invalid certificate

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/cloud-platform#365]
## Service name
Victims Information Service

VIS

## Service environment
Prod  and staging

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production

## Impact on the service
Down/Inaccessible

Invalid/out-of-date certificate - no access

## Problem description
Invalid/out-of-date certificate - no access

see [production site](https://www.victimsinformationservice.org.uk/)
[confluence](https://dsdmoj.atlassian.net/wiki/spaces/PLAT/pages/324043410/Victims+Information+Service+HMCTS+Supported)

## Contact person

@jsugarman, alex morris

**Comment by kalbir** [comment]
Hi @jsugarman -- Alex Clark has been working on this for a few days trying to find the right contacts to help solve it. He is very close, I believe it is an issue with getting a new cert. He has been talking about it in the #hosting channel in MoJ Slack.
