### ISSUE TITLE
Update the CP code examples for v1 manifest changes for apiVersion

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3650]
Follow the user guide for the changes to apiVersion changes and update the code examples.

User guide
Multi-container demo app
Hello world demo app
How out of date are we
cloud platform canary app
integration tests
prototype template
All yaml files in the environments repository

And any other code which needs to be updated

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
User guide: done
Multi-container demo app: done
Hello world demo app: done
How out of date are we: done
cloud platform canary app: done
integration tests: 
prototype template: done
All yaml files in the environments repository: done
