### ISSUE TITLE
live-1 clean-up components: Delete cert-manger- phase-1

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3654]
Delete cert-manager in live-1

Steps to follow:
1) scale down pods to 0, and verify no impact on live
2) Verify cert-manger module and check to destroy this in live-1 will not cause any issues to live cluster
3) Remove cert-manger tests running in live-1
4) Destroy cert-manger

**Comment by poornima-krishnasamy** [comment]
Step 1: scaling down the cert-manger deployment done

**Comment by poornima-krishnasamy** [comment]
Step 2: terraform module checked for an issues with `live` and did a terraform destroy targeting `live-1`
