### ISSUE TITLE
live-1 clean-up update components module: cert-manager- phase-3

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3663]
live-1 clean-up update components module: cert-manager

Steps to follow:

Create a new branch from live-1 module version used, and name it live-1-<module-name>
Update the module to remove any references to live-1
Test and make sure that updating the module does not shown any changes and deletions in live
Create a new module version

**Comment by jackstockley89** [comment]
Changes have been merged into main and committed into manager and live 

PR for changes
https://github.com/ministryofjustice/cloud-platform-terraform-certmanager/pull/29
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1527
