### ISSUE TITLE
live-1 clean-up update components module: ingress-controllers  phase-3

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3664]
live-1 clean-up update components module: ingress-controllers

Steps to follow:

Create a new branch from live-1 module version used, and name it live-1-<module-name>
Update the module to remove any references to live-1
Test and make sure that updating the module does not shown any changes and deletions in live
Create a new module version

**Comment by jackstockley89** [comment]
Added release for the last kops release to the module repository. After reviewing the module there was no changes needed to remove live1 as there wasn't any reference to the eks or kops. There was a variable for 'live1_cert_dns_name' but this relates to the to following ticket and should be done as part of that ticket

https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/3674
