### ISSUE TITLE
Update RDS version to use major version

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3669]
We have issues when users pin the RDS version to the minor version

For example, if they set it  to 13.3, was upgraded to a minor version during the maintenance window to something like 13.4

This will cause terraform apply pipeline to fail.

https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live/builds/852

Test it to see if users are updated to major version like "13", with out any issues

**Comment by poornima-krishnasamy** [comment]
if the db_engine_version is updated to just `13` before aws did the upgrade to e.g. `13.4`, then the upgrade to 13.4 happens when applying the PR. And not holding hte upgrade on the maintainance window. 

Hence, update all the db_engine_version to 13 for instances which are already upgraded.
