### ISSUE TITLE
A user needs to know where to find resource credentials

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#367]
## Background

We have had some feedback from users that they are unable to find credentials for resources that they add to their application.

Credentials are stored as a Kubernetes secret within the environment and can retrieved by `kubectl -n <environment_name> get secret ecr-repo-my-app-name -o yaml`

This should be clear in the user guide.

## Proposed user journey

A user can follow the guidance to create a resources. The guidance also tells them where to find credentials for their resource.

## Approach

We have some good wording in the Create an ECR repository guide:

<img width="740" alt="screen shot 2018-09-05 at 13 02 54" src="https://user-images.githubusercontent.com/36888942/45093339-010ca880-b110-11e8-9bf7-09b771730ba5.png">

We should add a section like this for each resource in the guide.

## Definition of done

- [x] User guide updated with relevant instructions

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-user-docs/pull/72
