### ISSUE TITLE
live-1 clean-up:  remove live-1 related pipelines in concourse - phase-1

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3677]
live-1 clean-up:  remove live-1 related pipelines in concourse

Pipelines to be deleted:

kops build-test-cluster
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/blob/main/pipelines/manager/main/build-test-cluster.yaml

Divergence for kops and kops components
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/blob/main/pipelines/manager/main/divergence.yaml

Apply pipeline for live-1, which includes, apply, plan and apply namespace changes.
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/blob/main/pipelines/manager/main/environments-terraform.yaml

Maintenance jobs related to live-1
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/blob/main/pipelines/manager/main/maintenance.yaml

Reporting jobs related to live-1
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/blob/main/pipelines/manager/main/reporting.yaml

**Comment by poornima-krishnasamy** [comment]
Should we create delete_manually_create_pods and delete_completed_jobs job for live?

**Comment by poornima-krishnasamy** [comment]
Created tickets to investigate the jobs which are not created for live
https://github.com/ministryofjustice/cloud-platform/issues/3708
https://github.com/ministryofjustice/cloud-platform/issues/3709
https://github.com/ministryofjustice/cloud-platform/issues/3710
