### ISSUE TITLE
spike EventBridge

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#3679]
## Background

We had several requests for Lambda or a similar event-driven solution; this is to check if the AWS service is useful for our tenants.

## Approach

Create tf module to create EventBridge bus/rule/target, define and send some sample events.

## Definition of done

Demo findings

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1vsrQjSQYIK9VZiDGoTnFcuPxoyiDvxCeEdGSOGShD8o/edit
