### ISSUE TITLE
live-1 clean up:  flowlogs in VPC repo  - phase-3

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3686]
live-1 clean up:  flowlogs in VPC repo 
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/main.tf#L73-L78

Verify if any things else can be removed in live-1

Make sure VPC is not effected as this is shared VPC for live

**Comment by sablumiah** [comment]
Closing this ticket as we will keep the live-1 VOC flow logs as the live cluster lives in this VOC
