### ISSUE TITLE
Add CloudWatch alarms into prisoner-money-alerts slack channel

### ISSUE THREAD

**Issue by nayoa** [ministryofjustice/cloud-platform#369]
## Background

After a discussion with the money-to-prisoners team, the team were unaware on the replacement of Sensu. The team are interested in having CloudWatch alarms alerting their channel `prisoner-money-alerts` so they have full visibility of their applications.

The team made us aware that an application is missing from the log-agent. Best way to find it: 
`money-to-prisoners-transaction-uploader-test-32a0e658-ScalingGroup-QTNIXM08P4S0`

**Note: After conversation with the team, we cannot highstate any MTP application.** 

## Approach

- Add Money to Prisoners transaction uploader application to the log agent for monitoring
- Replicate the CloudWatch alarms going into `high-priority-alarms` for the channel `prisoner-money-alerts`.

## Definition of done

- [ ] Log agent added to `transaction uploader` application
- [x] CloudWatch alarms for all Money to Prisoner applications going into `prisoner-money-alerts` slack channel. 

## Reference

Slack Channel - #prisoner-money

Contacts: @ibrechin and @ushkarev

**Comment by ushkarev** [comment]
regarding

> we cannot highstate any MTP application

this is because the service would be temporarily unavailable and we need to avoid downtime as much as possible. our service involves people paying money and downtime could lead to the money getting lost. we've a process for performing updates more safely

**Comment by ushkarev** [comment]
also, the `prod` autoscaling group is `money-to-prisoners-transaction-uploader-prod-15cdf470-ScalingGroup-6M24X0BXL1UA` which i believe is also not in cloudwatch

**Comment by pwyborn** [comment]
10/10/2018 Hi Igor regarding your ticket “Add CloudWatch alarms into prisoner-money-alerts slack channel” I have added the following alarms (all auto-scaling related).
I have also made it so that all production alerts should notify #prisoner-money-alerts
for all mtp products
You will have seen a test this morning

paulwyborn [9:27 AM]
Note that the following alarms are related to loadbalancers - as there are no elb’s for ‘transaction-uploader’ (unless I am missing it) I was not able to set them up
#  UnHealthyHosts:

#  HighLatency:

#  http5xxError:

#  ELB5xxError:

#  http4xxError:```

**Comment by pwyborn** [comment]
Hi Igor is there anything else that you need for this ticket? You mention that the log-agent is missing. Think it was logging - but the alarms for transaction-uploader had not been configured (let me know if you think this is not the case please? - I may have misunderstood - I will then look further)

**Comment by pwyborn** [comment]
hi paul. the quick background to this ticket is that i was asking where the old sensu/uchiwa/grafana/ELK logs and alarms were going and found out that at some point they were moved to cloudwatch (of which i wasn’t aware). then having looked in cloud watch, i could see no mention of our “transaction-uploader” app. it’s a bit like a glorified cron job and exposes nothing to the web (therefore no ELBs)

now, i presume, all 6 money-to-prisoners apps (in 2 environments: test and prod) should be shipping logs to cloudwatch (edited)

paulwyborn [11:01 AM]
Yes - you should find that everything is shipping logs to cloudwatch. Only sending out notifications to the slack channel for production - as may be overkill?

igor.ushkarev [11:02 AM]
oh yeah, we wouldn’t want the logs in slack 

paulwyborn [11:07 AM]
Have a look in AWS and see if its what you want Igor. In cloudwatch logs filter by “money-to-prisoners-trans” in cloudwatch alarms filter by “MTP-transaction-uploader”
