### ISSUE TITLE
Feedback on "How to use kubectl to connect to the cluster" User Guide

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3696]
## Background

User feedback on user guide:

> Hi 
> 
> I had an issue following the instructions here
> https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/kubectl-config.html#get-a-kubeconfig-file
> 
> step 7
> Move the downloaded file to ~/.kube/config:
> 
> mv kubecfg.yaml ~/.kube/config
> After I did this and tried to run the next step I kept getting an error complaining .kube/config is a directory - which indeed it is
> 
> 
> The instructions on Kuberos below specify to save the config file as .kube/config not in .kube/config, then the next steps worked.
> 
> https://login.cloud-platform.service.justice.gov.uk/ui?code=7qDSaiwGlSMiJXVrj5pTLFlm-8_-bOi_2s-QT64OkbI2B&state=15029d23273fdd3d3a05b5b6b3780d49ed3fa0d696230b6ead8aaded050733a8
> 
> Save the file below as ~/.kube/config to enable OIDC based kubectl authentication.
> 
> Download Config File
> 
> Perhaps the user guide needs updating?
> 

## Approach

Review feedback. Update guide accordingly.

## Which part of the user docs does this impact

[How to use kubectl to connect to the cluster](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/kubectl-config.html#how-to-use-kubectl-to-connect-to-the-cluster_

## Definition of done

- [ ] Guide updated as appropriate

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
I have re-worded step 7 to make it more clear that the config is the yaml file name and not a directory where the yaml file should go  

PR: https://github.com/ministryofjustice/cloud-platform-user-guide/pull/1105

This has been merged into main, pipeline has run and user guide has been updated 

user guide link:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/kubectl-config.html#get-a-kubeconfig-file
