### ISSUE TITLE
Merge the two environment creation repos

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#37]
## Background 

We currently have 2 environment creation repos:

  * https://github.com/ministryofjustice/cloud-platform-test-cluster-env
  * https://github.com/ministryofjustice/k8s-nonprod-environments

One of these makes environments on the test cluster, the other makes environments on the non-prod cluster.

We want to combine these two repos so that we have a single repo which has the environment definition for any clusters that we make.

## Done When

- [x] Decide whether whether `test`, `non-prod`, etc. All environments are managed as branches of the repo or they live in different subdirectories (@kerin, @kalbir  to decide).  See comments, below.
- [x] A single repo for namespace creation exists: `cloud-platform-environments`
- [x] ministryofjustice/cloud-platform-test-cluster-env is merged into `cloud-platform-environments` **preserving it's original history**.
- [x] ministryofjustice/k8s-nonprod-environments is merged into `cloud-platform-environments` **preserving it's original history**.
- [x] The two original repos are removed from github.
- [x] You can create an environment in this repo that is successfully built on the `non-production` cluster
- [x] You can create an environment in this repo that is successfully built on the `test` cluster
- [x] The documentation on [how to create namespaces](https://ministryofjustice.github.io/cloud-platform-user-docs/01-getting-started/003-env-create/#creating-a-cloud-platform-environment) is updated to use the `cloud-platform-environments`repository.

## Notes

Merging two repos can be tricky.  This might be helpful: 

https://saintgimp.org/2013/01/22/merging-two-git-repositories-into-one-repository-without-losing-file-history/

**Comment by kalbir** [comment]
We currently have 2 environment creation repos:

    https://github.com/ministryofjustice/cloud-platform-test-cluster-env

    https://github.com/ministryofjustice/k8s-nonprod-environments

One of these makes environments on the test cluster, the other makes environments on the non-prod cluster.

We want to combine these two repos so that we have a single repo which has the environment definition for any clusters that we make.

**Comment by kalbir** [comment]
Yep +1 for subdirectories

**Comment by ale-novo** [comment]
Edited the tkt description and fixed repo name, decided with @kalbir `cloud-platform-environments` and also fixed typos on the text.

**Comment by kalbir** [comment]
🤦🏽‍♂️👍🏽

**Comment by ale-novo** [comment]
reminder for myself, this work is being done against the repo_merge branch, after the pr is merged into master a new pr must be raised to change and apply the terraform.tfvars files inside the terraform directory to point to the master branch.

**Comment by ale-novo** [comment]
test-cluster configurations were created to trigger the pipeline and create new namespaces in both clusters. this worked.
proof:
cluster non-production.k8s.integration.dsd.io
(...)
kubectl create namespace test-namespace
b'namespace "test-namespace" created\n'
kubectl apply namespace test-namespace
b'namespace "test-namespace" configured\n'
helm init test-namespace
b"$HELM_HOME has been configured at /root/.helm.\n\nTiller (the Helm server-side component) has been installed into your Kubernetes Cluster.\n\nPlease note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.\nFor more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation\nHappy Helming!\n"

this covers bullet point `You can create an environment in this repo that is successfully built on the non-production cluster`

**Comment by ale-novo** [comment]
test-cluster configurations were created to trigger the pipeline and create new namespaces in both clusters. this worked.
proof:

cluster cloud-platforms-test.k8s.integration.dsd.io
(...)
kubectl create namespace test-namespace
b'namespace "test-namespace" created\n'
kubectl apply namespace test-namespace
b'namespace "test-namespace" configured\n'
helm init test-namespace

this covers bullet point ` You can create an environment in this repo that is successfully built on the test cluster`

**Comment by ale-novo** [comment]
also now these namespaces definitions were removed to test the deletion functionality and it worked.

kubectl delete namespaces test-namespace
b'namespace "test-namespace" deleted\n'

in both clusters

**Comment by ale-novo** [comment]
both codebuild pipelines were updated and now running against this repo

**Comment by ale-novo** [comment]
pr https://github.com/ministryofjustice/cloud-platform-environments/pull/1 was raised to address 

`ministryofjustice/cloud-platform-test-cluster-env is merged into cloud-platform-environments preserving it's original history.
  ministryofjustice/k8s-nonprod-environments is merged into cloud-platform-environments preserving it's original history.
  You can create an environment in this repo that is successfully built on the non-production cluster
  You can create an environment in this repo that is successfully built on the test cluster`

**Comment by ale-novo** [comment]
a better readme was pushed to this repo

**Comment by ale-novo** [comment]
pr ministryofjustice/cloud-platform-environments#1 was approved covering items:

```ministryofjustice/cloud-platform-test-cluster-env is merged into cloud-platform-environments preserving it's original history. ministryofjustice/k8s-nonprod-environments is merged into cloud-platform-environments preserving it's original history. You can create an environment in this repo that is successfully built on the non-production cluster You can create an environment in this repo that is successfully built on the test cluster```

**Comment by ale-novo** [comment]
pipelines were updated to run against the master branch 
pr raised
https://github.com/ministryofjustice/cloud-platform-environments/pull/2

**Comment by ale-novo** [comment]
the link to the cloudplatforms document was updated to 
https://ministryofjustice.github.io/cloud-platform-user-docs/01-getting-started/003-env-create/#creating-a-cloud-platform-environment

as it was incorrect in the original description.

**Comment by ale-novo** [comment]
the document was updated

**Comment by ale-novo** [comment]
this tkt is complete now.
