### ISSUE TITLE
Define how we destroy resources

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#370]
## Background

As we add available resource types (S3, ECR, etc) for the cloud platform users, it would be useful to also define a cleanup process.

## Proposed user journey

Permanent AWS resources like buckets or Docker images are stored for a project; if such a project becomes obsolete or gets migrated, they also need to be freed. Deleting the k8s namespace does not handle this right now.

## Approach

TBD

## Questions / Assumptions

Resources are created strictly via the environments repo, and Concourse pipeline.
 
## Definition of done

- [ ] must compile
- [ ] documented decision and workflow
- [ ] cloud platform users informed, feedback addressed
- [ ] a new story created for the implementation

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Duplicate ticket. The decision was made to write a script that does a direct comparison of what's in git and what's on the cluster. This script is now in place and looks like the following:

```
2m>>> found cluster cloud-platform-live-0.k8s.integration.dsd.io
Switched to context "cloud-platform-live-0.k8s.integration.dsd.io".
1m>>> The following namespaces are not in git anymore: andalusia-dev, andalusia-live, jenny-myapp-dev, kiam, myapp-dev, pr-test-app
1m>>> The following terraform states do not have configuration in git anymore: jenny-myapp-dev, myapp-dev, support-labelling-webhook-dev
name                           namespace  terraform state
andalusia-dev                  ✓          
andalusia-live                 ✓          
jenny-myapp-dev                ✓          ✓
kiam                           ✓          
myapp-dev                      ✓          ✓
support-labelling-webhook-dev             ✓
```
