### ISSUE TITLE
Update Runbook - Auth0 Credential Rotation 

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#3701]
Look at the current auth0 steps including updating the rolling update for kOps step. 
As we do not use kOps anymore. do we need new steps or remove this step?

https://runbooks.cloud-platform.service.justice.gov.uk/auth0-rotation.html#2-rolling-update-of-cluster-kops

**Comment by vijay-veeranki** [comment]
Completed 
https://github.com/ministryofjustice/cloud-platform/commit/2a3bc6604a556785fd2ad85af637dfed7d4f16c5
