### ISSUE TITLE
Create delete_manually_created_pods pipeline for live

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3708]
We have a cleanup concourse job to delete all manually created pods from live-1. We will need one for `live` cluster

Create a job to do the same for `live` cluster

Refer this PR for similar job in live-1 : https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/93

## Definition of done

- [ ] concourse job created
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
To be replace by comms re manual pod creation risks
