### ISSUE TITLE
Create delete completed concourse job for live

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3709]
We have a cleanup concourse job to delete all pods created by completed jobs from live-1. This job look for jobs which doesnot have the ttlSecondsAfterFinished and delete the pods. 

This was not created for live as `ttlSecondsAfterFinished` feature wasnot supported in EKS until 1.21. Now  the`live` EKS cluster is in 1.21, create this job as a cleanup for `live`

Refer this PR for similar job in live-1 : https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/93

## Questions / Assumptions

Should we update the users before we trigger this job. If they have not updated the cronjobs to have ttlSecondsAfterFinished, then this would delete the pods based on the default successfulJobsHistoryLimit and failedJobsHistoryLimit set for  the cluster
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits

## Definition of done

- [x] Update users on update channel about this job
- [x] Concourse job created 
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
Hi @AntonyBishop - we are about to enable this pipeline - do we need to do any kind of communication with the users please?

**Comment by AntonyBishop** [comment]
Hi @pwyborn We should communicate changes out to users. We should include why we are doing this and instruction (or a link to the guide) on what they need to do. We should also give them a period of time to do it. Do we know how many users this might impact? If it's a small group a targeted comms might be more appropriate.
