### ISSUE TITLE
Delete sonarqube scanning concourse job for live

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3710]
## Background

We have a concourse job scanning all repository for vulnerabilities.

Currently the job errors when running the script.

https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/scanning/jobs/sonar-scan-all-repos/builds/88#L621764d6:541

 -  Investigate if there is a need for it. (**Nope**)
 - If yes, fix the script
 - Create a concourse job to run against repos in live

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
This is completed now
