### ISSUE TITLE
RabbitMQ is not running on laalaa staging instance

### ISSUE THREAD

**Issue by rowlando** [ministryofjustice/cloud-platform#373]
## Service name

LAALAA, as known as LAA Legal Adviser API

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Parts of the application do not work.

## Problem description

Application cannot upload legal adviser data files. (A similar issue may have fixed as part of #326.)

There are two staging EC2 instances:

- 34.241.201.40 <- RabbitMQ works
- 54.154.142.113 <- RabbitMQ connection fails

You can see in this [error log](https://github.com/ministryofjustice/cloud-platform/files/2367237/error.txt) that connection is made:

```bash
Connected to amqp://rabbit:**@172.17.0.1:5672//
```
and moments later the connection is lost:

```bash
consumer: Connection to broker lost. Trying to re-establish the connection...
```
and a timeout occurs:

```bash
Unrecoverable error: NotFound(404, u"NOT_FOUND - failed to perform operation on queue '33d7ab9d-4d21-33d5-aa8d-c56f2fad7b76.reply.celery.pidbox' in vhost '/' due to timeout", (50, 10), 'Queue.declare')
```

This repeats itself.

## Contact person

Slack: @nick

**Comment by pwyborn** [comment]
paulwyborn [10 minutes ago]
Hi @nick restarted both rabbitmq and the container -are you still getting problems?


nick [1 minute ago]
that seems to have done the job.


nick [< 1 minute ago]
I'll let you know if the problem reoccurs


nick [< 1 minute ago]
thanks


paulwyborn [< 1 minute ago]
Thanks @nick

**Comment by pwyborn** [comment]
paulwyborn [< 1 minute ago]
Hi Nick - just sent to you the rabbitmq crash reports for yesterday and day before on that instance (may have had a bearing on rabbitmq problems?). None on other instance  - well 1 crash report on 24th of August
