### ISSUE TITLE
Slack integrations for Pingdom request Legal Framework API staging

### ISSUE THREAD

**Issue by kmahern** [ministryofjustice/cloud-platform#3757]
## Service name

legal-framework-api

## Service environment

- [ ] Dev / Development
- [X] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Enable pingdom alerts to #applyprivatebeta slack channel

## Problem description

Please could I get a slack integrations for Pingdom set up please?

Application Name: legal-framework-api
Team Name: laa-apply-for-legal-aid
Slack Channel: #applyprivatebeta

Thank you!

## Contact person

Katharine Ahern

**Comment by vijay-veeranki** [comment]
integration id=121629
