### ISSUE TITLE
Move the permissions checker to its own repository

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3767]
## Background

The [Permissions Check Github Action](https://github.com/ministryofjustice/cloud-platform-environments/tree/main/cmd) awkwardly sits in the [cloud-platform-environments](https://github.com/ministryofjustice/cloud-platform-environments/) repository. This should live in its own repo, using the moj template and dependabot GitHub Actions.

## Proposed user journey

Create a new repository, add the required static checks and pipeline actions. Copy the codebase into the repository. Add it to the #cloud-platform-notify channel.

## Questions / Assumptions

Many repositories are better than a monorepo.

## Definition of done

- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
This has hit a snag and needs to be moved after fixing the broken tests in this repository.

**Comment by AntonyBishop** [comment]
Aged out
