### ISSUE TITLE
Fix aws provider version conflicts on account/ folder

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3773]
## Background

When applying `https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/aws-accounts/cloud-platform-aws/account` folder, terraform init failed with below error

```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/aws:
locked provider registry.terraform.io/hashicorp/aws 4.13.0 does not match
configured version constraint >= 2.23.0, >= 2.50.0, >= 3.0.0, >= 3.61.0, ~>
3.68.0, >= 4.5.0; must use terraform init -upgrade to allow selection of new
versions

```

After removing the version pinning here, https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/account/versions.tf#L5, the apply worked.

Investigate whether the pin can be removed in the account/folder.

The reason for pinning the aws provider is mentioned in the PR:
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1456

## Definition of done

- [ ] terraform apply works fine with the correct aws provider version
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jakemulley** [comment]
Resolved by ministryofjustice/cloud-platform-infrastructure#1536.
