### ISSUE TITLE
Investigate and fix cert-manager golang test

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3779]
Investigate and fix cert-manager golang test

cert-manager live-integration-tests fail randomly on some runs.

Investigate the cause of it and fix the test.

Some failure examples:
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/live-integration-tests/builds/2980
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/live-integration-tests/builds/2977

**Comment by jasonBirchall** [comment]
I added the `flaky` test Ginkgo feature, which re-runs three times. The failure rate is now much lower.
