### ISSUE TITLE
build a library of modsecurity hints

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#3794]
Background: modsecurity is hard to debug

After the discussion in https://mojdt.slack.com/archives/C57UPMZLY/p1652792483163259 and similar threads in the past: dev teams around us have learned a lot of useful ingress modsec optimisations and caveats so sharing them in a collaborative space might save significant time for everyone.

Such a space would probably need to be internal, from a quick check in the cluster almost all users encrypt their ingress values.

A/C:
 - make a decision on how we could do this
 - communicate with the teams to populate said knowledge base
 - promote the link

**Comment by razvan-moj** [comment]
> The userguide is public, would a contribution there make more sense?

I don't know if any of that information is considered sensitive by the teams defining it; would they be worried that a list of disabled rules is visible in git? OTOH, if we only make the space available, each editor would decide what goes in the page, and it wouldn't be us adding content.

**Comment by AntonyBishop** [comment]
Replaced by #4010
