### ISSUE TITLE
Move the environment creation jobs from code pipeline to concourse

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#38]
## Background

Depends on #37 and (to a lesser extent) #71. 

Currently the pipelines to build environments from the environment creation repos are defined in AWS code pipeline. We want to move them to concourseCI. 

This is probably best to do *after* #37 so that we are building from one repo and the concourse pipelines are able to determine which cluster to create environments against.

## Done when

- [x] Decide where to run the concourseCI instance that holds these pipelines (@kerin, @alkar and @kalbir) [See #71, it will run on that concourse]
- [x] When a user adds an environment to the test cluster directory in the `cloud-platform-environments` repo it triggers a pipeline on concourseCI which builds the envrionment on the test cluster
- [x]  When a user adds an environment to the non-production cluster directory in the `cloud-platform-environments` repo it triggers a pipeline on concourseCI which builds the envrionment on the non-production cluster
- [x] The concourse pipelines are pushed to a repo and concourse builds the pipelines from that repo
- [x] The concourse pipeline issues a slack notification to the `#cp-build-notifications` channel when the pipeline is kicked off
- [x] The concourse pipeline issues a slack notification to the `#cp-build-notifications` channel when the pipeline fails/succeeds

**Comment by tatyree** [comment]
I'm flagging this one as blocked pending completion of #37 as per @kalbir's comment in the description.

**Comment by lukaszraczylo** [comment]
Connects to https://github.com/ministryofjustice/cloud-platform-environments/pull/4

**Comment by lukaszraczylo** [comment]
@kalbir cp-build-notifications exceeds the limit of 22 characters for slack channel name.

**Comment by lukaszraczylo** [comment]
@alkar after adding webhook - https://github.com/ministryofjustice/cloud-platform-environments/settings/hooks - we get 401. Is there any sort of authentication / basic auth we can use to trigger the job remotely?

**Comment by kalbir** [comment]
It should have been whatever the channel is currently called, which it
turns out is `cp-build-notification`!

**Comment by lukaszraczylo** [comment]
Okay, my bad - I tried to create that channel and it threw mentioned error. I’ll correct it to the desired value.

**Comment by kalbir** [comment]
No worries, I should have been clearer!

**Comment by lukaszraczylo** [comment]
Ready for review.

**Comment by alkar** [comment]
@lukaszraczylo have you removed the codepipeline job & its config?

**Comment by lukaszraczylo** [comment]
Hi, nope, last time I’ve checked it’s there - pipeline.yaml

**Comment by alkar** [comment]
This is the concourse job, I thought we had a codepipeline job before that?

**Comment by lukaszraczylo** [comment]
cloud-platform-test-cluster-env-creation pipeline was deleted. All the cluster changes are applied by concourse only.
