### ISSUE TITLE
Enable X-Request-ID on nginx-ingress

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#381]
## Background

User request from the OMiC team.

## Proposed user journey

As a user, I want HTTP requests reaching my service to include an `X-Request-Id` header.
## Approach

https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#generate-request-id

It might be helpful to deploy something like [httpbin](https://github.com/requests/httpbin) on the cluster for testing this.

## Questions / Assumptions

This will be useful for other applications as well and there's no obvious reason why we shouldn't enable it cluster-wide.

## Definition of done

- [x] requests reaching a Pod should include the `X-Request-ID` header

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/kubernetes-investigations/pull/79
