### ISSUE TITLE
Allow Grafana Dashboards to be shared with users who are not part of development teams

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3812]
## Background

Based on user feedback:

> Currently the only way to edit and add to dashboards is through code, and click-ops are restricted. This means that having ad hoc, short lived dashboards for assisting debugging incidents isn’t as fast and easy to do, but also our product managers can’t use grafana effectively without developer help when wanting to have dashboards to help track performance of KPIs.

> Also with the current single sign-on setup in Grafana, access is restricted to only those with a GitHub account. The Ministry of Justice has limited accounts which are currently only available to engineering. For a multidisciplinary team, our observability tools should be accessible for any profession that requires use.

> If version control is a concern, this is a capability that is built into Grafana itself if we wanted to use it.

> Examples
> For the View Court Data project moving to using a new API and versioned endpoints, the team, lead by product, wants to demonstrate measures of success using KPIS. This includes increased speed on features from the front end, through to the error rates on the API. Some of these measures wouldn’t be needed long term and are only needed for the length of this project.
> Grafana has the feature of snapshot dashboards, which can be expired. These are useful for incident reports for stakeholders or even for demonstrations of the impacts of the work the team has done. As these are often short lived, driving the dashboard through code adds unnecessary effort for this purpose.
> The product manager in the team would use dashboards to display the impact of the teams work and the data driven decisions they’ve made towards solutions to our stakeholders, if they had the access (non-GitHub sign in) and tooling (non-code based solutions to dashboards) available to them.

## Proposed user journey

As a Service Team I can share "snapshots" of my dashboards with other stakeholders outside of the development teams so that we can better share information with those who are interested in our service.

## Approach

Spike - Look at options available to share unauthenticated views of dashboards with users. We have a test group available to trial some solutions.

## Which part of the user docs does this impact

Documentation is not part of this story.

## Questions / Assumptions

TBC

## Definition of done

- [ ] We have one of more options to demo/trial with a user. 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/grafana-snapshots.html#publish-a-grafana-dashboard-snapshot
