### ISSUE TITLE
Open up Prometheus, Alertmanager and Grafana to the org

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#382]
## Background

We've initially decided to restrict access to the cloud-platform team only. However, in order to allow users to get useful metrics for the applications, we will open up access to the entire org, similar to kibana.

## Proposed user journey

As a user, I need to access the prometheus, alertmanager and grafana web interfaces.

## Approach

Modify the OIDC proxy to allow any member of the ministryofjustice org to access these services.

The check happens [here](https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/oidc-proxy.yaml#L28-L36) - also see  [this comment](https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/cloud-platform-live-0.k8s.integration.dsd.io/monitoring/oidc-proxy.yaml#L7-L9).

## Questions / Assumptions

N/A

## Definition of done

- [x] all members of the ministryofjustice github org are allowed to access these services

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/176#pullrequestreview-159420978
