### ISSUE TITLE
Make additional datasources available for Grafana

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3833]
## Background

Users would like to add additional datasources to Grafana:

> Part of the power of Grafana is its many associated data sources which enables you to use multiple sources of information and do comparisons and trends across them to help with analysing service health and incidents.

> We are currently limited to the data sources we can use on our graphs because of the current implementation.

> Examples 
> - Using event triggers from our deployment tools (such as CircleCI) would enable us to show on graphs where deployments have occurred and easily visualise impacts of those deployments.
> - Being able to pull in data from Google Analytics, Survey Monkey and other data sources outside of Thanos, Cloudwatch and Prometheus would enable us to compare and contrast data more effectively and get the full picture we need for incident management, checking service health and checking the effectiveness of our changes against KPIs.

## Proposed user journey

As a developer I can add an additional datasource to my Grafana dashboards so that I have all the information relevant to running my service in one place. 

## Approach

TBC. This may depend on the datasource chosen to explore this story.

## Which part of the user docs does this impact

New section in user guide. User documentation will be captured in another story.

## Questions / Assumptions

1. Which datasource?

## Definition of done

- [ ] datasource agreed
- [ ] new datasource available in Grafana

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
First iteration is to try adding Sentry as a datasource.

**Comment by AntonyBishop** [comment]
Closing story. From the spike it's clear that the Sentry data source isn't quite there yet. There are issues raised to fix a none bug, and there are no obvious plans to fix. Dashboards are non existant.

Also explored Prometheus Exporter, but Sentry significant rate limits this which means that solution for all projects is not feasible.
