### ISSUE TITLE
Create report that shows what is running on the non-v1 ingress

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3835]
## Background

It would be good to have visibility of what is running on pre-v1 ingress. 

## Approach

Create a report. Add it to CP reports site.

## Which part of the user docs does this impact

N/A

## Definition of done

- [ ] Report created
- [ ] Report is updated periodically (frequency TBD)

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
found a tool called pluto, this will gather versions for anything deployed with helm, will have to find another method of gathering anything deployed using kubectl

**Comment by jackstockley89** [comment]
Used a tool called kubent this gathered all the data needed. Created a spreadsheet with the necessary information 
https://drive.google.com/drive/u/1/folders/1avFxUdDP2tUljsg69gYjmO6I4CajN-_w
