### ISSUE TITLE
New URL -criminal-justice-delivery-data-dashboards.justice.gov.uk/

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/cloud-platform#3839]
## Service name

criminal-justice-delivery-data-dashboards.justice.gov.uk
## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

<This is a new url to point to the environment - criminal-justice-scorecard.justice.gov.uk/. We will then want to remove access via https://criminal-justice-scorecard.justice.gov.uk/>

## Problem description

There is a requirement to rename the current scorecard to dashboard - all needs to be in place by 8:30 on 13/6

## Contact person

<Damien Wilson and Simon Pledger

**Comment by razvan-moj** [comment]
done

```
$ dig +short NS criminal-justice-delivery-data-dashboards.justice.gov.uk
ns-111.awsdns-13.com.
ns-1144.awsdns-15.org.
ns-2040.awsdns-63.co.uk.
ns-830.awsdns-39.net.
```

**Comment by wilson1000-MoJ** [comment]
Hi, can we please confirm that the previous domain ([https://criminal-justice-scorecard.justice.gov.uk/>](https://criminal-justice-scorecard.justice.gov.uk/%3E)) is still active? We will need this to be available for at least 30 days after the publication of the new domain. Thank you!
