### ISSUE TITLE
firebreak: kube-ops-view

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3848]
kubeops view
https://codeberg.org/hjacobs/kube-ops-view

It can give you a nice operational picture of your Kubernetes clusters — the different nodes deployed and their status, as well as the different pods running on the nodes.

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by AntonyBishop** [comment]
Team agreed to close.
