### ISSUE TITLE
firebreak: loghouse

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3850]
loghouse is an excellent log management solution for Kubernetes with an intuitive web UI. loghouse was created to collect Kubernetes logs, store them in the ClickHouse database and allow you to query and monitor your logs in a web interface. 

https://github.com/flant/loghouse

Possible replacement for FluentBit

Questions:
- How does it compare to FluentBit?
- What does it do in addition to current tool?

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by AntonyBishop** [comment]
No longer supported. Close
