### ISSUE TITLE
FIREBREAK: Make terraform plan faster when creating infrastructure

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3851]
## Background

The terraform plan and apply for infrastructure takes long time to execute. Find way to make it faster so we can apply specific components faster.

- One way to do is to split the components into multiple folders so the state has few things when doing plan.

- There are parellelism options when running plan and apply. 

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by razvan-moj** [comment]
https://medium.com/@anton.babenko/make-terraform-faster-skip-unnecessary-checks-aws-and-s3-3ab00df9c3a9 never tried it, 20% sounds nice!

**Comment by vijay-veeranki** [comment]
Tried splitting components 
Ingress related module in the main components
Other in sub-components, but still facing the same issue in local

Need to look at other options in next firebreak
