### ISSUE TITLE
Evidencelibrary Domain name request

### ISSUE THREAD

**Issue by sivafirst** [ministryofjustice/cloud-platform#3854]
## Service name
EvidenceLibrary

Domain name: https://analytical-evidence-library.service.justice.gov.uk/

## Service environment

- [ ] Prod / Production

## Impact on the service

none

## Problem description

Adding a new domain for the service

## Contact person

Sivaprasad Sighakolli

**Comment by vijay-veeranki** [comment]
Cerated NS record in dsd for zone

analytical-evidence-library.service.justice.gov.uk
