### ISSUE TITLE
Add user-guide for migrating over from using the live-1 domain

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3856]
Some users are still using the live-1 domain name in their ingress.

Add user guide for migrating over from using the live-1 domain

List of users still using live-1 domain
https://reports.cloud-platform.service.justice.gov.uk/live_1_domains

Users need to update their ingress and change the hostname to live from live-1

from:
court-prison.apps.live-1.cloud-platform.service.justice.gov.uk
to:
court-prison.apps.live.cloud-platform.service.justice.gov.uk

**Comment by sj-williams** [comment]
Page has been added here:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrating-from-live-1-domain-name.html#migrating-your-application-url-from-live-1-to-live-domain

**Comment by AntonyBishop** [comment]
Ready for comms.
