### ISSUE TITLE
Smoke tests for Test-2 cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#386]
## Background
Depends on #291 
Depends on #399 
Depends on #400

Automate the execution of the above tests.

## Approach

Think about where the tests run, how often to run them etc.
Implement the above for test-2.

## Definition of done

- [ ] must compile
- [ ] must pass tests
- [ ] must address all the steps of user journey

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-concourse/blob/add/test-2-pipeline/pipelines/test-2/main/smoketest.yaml

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-concourse/blob/add/test-2-pipeline/pipelines/test-2/main/smoketest.yaml

**Comment by jasonBirchall** [comment]
All tests automated - currently waiting on the completion of #291

**Comment by jasonBirchall** [comment]
https://concourse.apps.test-2.k8s.cloud-platform.dsd.io/teams/main/pipelines/smoketest

**Comment by jasonBirchall** [comment]
Now added remaining namespace test. Ticket complete.

**Comment by jasonBirchall** [comment]
Now added remaining namespace test. Ticket complete.
