### ISSUE TITLE
New AlertManager route for Syscon owned services

### ISSUE THREAD

**Issue by lbennett-moj** [ministryofjustice/cloud-platform#3864]
As discussed with @vijay-veeranki 

We would like to move all the Syscon-owned services away from a default DPS alert channel to use our syscon-alerts slack channel. Initially this channel will handle all environments, we may separate into prod and non-prod at a later date

namespace name: (multiple)
team name: Syscon digital initiatives team
application name: (multiple)
slack channel: #syscon-alerts. (https://mojdt.slack.com/archives/C02SXMHJENP)
kubernetes secret name where the webhook url is stored: please DM me via slack for webhook.
severity level (warning): syscon

**Comment by vijay-veeranki** [comment]
This is applied now with:
severity level: syscon
