### ISSUE TITLE
Hosting Design Histories of the Cloud Platform

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3867]
## Background

We've recently created a feature that allows users to host prototypes on the platform. However, we have a few examples where users are trying to host a "Design History" on the platform using the prototype feature.

It's becoming clear that this is a very different type of app, and following the prototype process is leading to confusion and problems for users, as well as confusion for the CP Team.

## Proposed user journey

As a designer/developer I want to be able to host my Design History on the Cloud Platform so that.......

## User Stories

NB - Our key users are actually Devs. The CP requires a certain knowledge that non Dev roles would struggle with.

As an interaction designer
I need to know what is expected of me and my team
So that I have the confidence to use CP to store my Design History

As an interaction designer
I need to be able to store my 11ty based design history 
So that I can show changes the team have made throughout the products lifecycle.

As an interaction designer
I need to have the support of a dev on my team 
So that they can help me set up the initial onboarding.

As an interaction designer
I need to be able to share my design history gov wide
So that the cross gov community can learn from what we've done

As an interaction designer
I need to have a record of my design iterations
So that assessment panels are aware of my process.

As a Developer
I need to be able to view issues
So that I can correct errors that may occur 

## Approach

This work will initially require some research. It's not clear how this differs from other applications being hosted on the platform.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- What is a Design History?
- Who works with a design history?
- Who are the users in this context?
- How does a design history differ?
- Are we hosting any other similar apps on the platform?

## Definition of done

- [x] We have a better understand of the user need and how this differs from prototypes.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ScottSeaward** [comment]
One user interview arranged 28/06 @1400
One more pending
will keep looking for more

**Comment by ScottSeaward** [comment]
Have a meet planned with a dev user hopefully this week

**Comment by ScottSeaward** [comment]
Added user stories from first session

**Comment by ScottSeaward** [comment]
Conducted an interview with a dev assisting a team using a DH

**Comment by AntonyBishop** [comment]
Research completed
