### ISSUE TITLE
Move Court Data UI Slack Alerts from laa-get-paid-alerts to laa-court-data-ui-alerts (production)

### ISSUE THREAD

**Issue by ivanELEC** [ministryofjustice/cloud-platform#3877]
## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service
Production alerts will be moved from laa-get-paid-alerts (will no longer show here) to laa-court-data-ui-alerts.

## Problem description
The LAA - Access a Claim team have decided against using a shared channel for all of our alerts because it is hard to process the alerts when everything is in one place. Instead, we have production and non-production alert channels for each of our services. For our View-Court-Data service, we have some alerts in the laa-get-paid-alerts channel that we want to move to laa-court-data-ui-alerts

Please note we ONLY want to move the production alerts, not alerts for all environments

## Contact person
Ivan Yohuno

namespace name: laa-court-data-ui-production
team name: GetPaid
application name: LAA Court Data UI
slack channel: #laa-court-data-ui-alerts
kubernetes secret name where the webhook url: lcdui-secrets#slack_ui_alert_webhook
severity level: warning

**Comment by vijay-veeranki** [comment]
Hi Ivan,

Webhook here is not in the right format
kubernetes secret name where the webhook url: lcdui-secrets#slack_alerts_webhook

**Comment by ivanELEC** [comment]
I've updated the PR to use a new secret which is the correct format (not encoded)
