### ISSUE TITLE
Metric - Failed Deployments

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3879]
## Background

MoJ is looking at metrics for the top 45 critical services, of which Cloud Platform is one.

In support of this work we need to be able to report on number of [deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) per month and number of failed deployments per month. 

We need to automate generation of those numbers and display them somewhere for reporting purposes.

If we can show an historic figure that would be useful.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

Assumption - Every merge to `main` is a deployment
Assumption - Completed tests is not a deployment

## Definition of done

- [ ] We are able to contribute figures to monthly MoJ reporting

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Report available in: https://reports.cloud-platform.service.justice.gov.uk/infrastructure_deployments
