### ISSUE TITLE
upgrade & pin Helm provider for Infrastructure

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#3882]
we have references to it in infrastructure with just `source = "hashicorp/helm"` no version info, this leads to differences in terraform applies based on whether we have a copy of it in the local cache or not

A/C:

pin to the latest release from https://registry.terraform.io/providers/hashicorp/helm

**Comment by pwyborn** [comment]
Ah brought to my attention that I should be looking at all the terraform modules (and possible re-location of helm in the infrastructure

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1694

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1744

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1750
