### ISSUE TITLE
upgrade terraform EKS module

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#3884]
We have it pinned at v17 (https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf#L114) because v18 introduces breaking changes (https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v18.0.0) that basically require a cluster rebuild
We need at least release v18.0.6 to try Graviton CPUs

A/C:
 - figure out a way to upgrade without rebuilding live
 - try to get as close to latest upstream (v18.23.0 at the time of writing) as possible without major component edits

**Comment by razvan-moj** [comment]
waiting for https://us-east-1.console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=10332130631&language=en

**Comment by jakemulley** [comment]
I've told [Dependabot to ignore major version 18](https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1687).

**Comment by razvan-moj** [comment]
blocked by https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1744 (closed without a solution)

**Comment by vijay-veeranki** [comment]
I worked on these changes following this info 
https://github.com/clowdhaus/eks-v17-v18-migrate

https://github.com/ministryofjustice/cloud-platform-infrastructure/compare/test-upgrade-eks-module?expand=1

This caused cluster not to be reachable with this issue:
Your worker nodes do not have access to the cluster. Verify if the node instance role is present and correctly configured in the aws-auth ConfigMap.

We need to look for solution of cluster access using suggestions from here:
https://github.com/bryantbiggs/terraform-aws-eks/blob/master/docs/UPGRADE-18.0.md
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1744

**Comment by jakemulley** [comment]
[v19.0.0](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/CHANGELOG.md#1900-2022-12-05) is also out now, which includes potential breaking changes.

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1Nv1WsqdYMBzjpO8jfmXEqjAY5nZ9GYWUpNNaMJVJyaw/edit#

**Comment by vijay-veeranki** [comment]
Closing this as we have multiple ticktets to test it before applying to live
