### ISSUE TITLE
Update tools image for AWS CLI version 2

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3886]
## Background

Current tools image has AWS CLI Version 1 installed using boto3. But in order to get the latest kubecfg with v1beta1 and to run aws command inside tools image, we need AWS cli version 2.

## Proposed user journey

Current Tools image are build upon the ruby alpine image: https://github.com/ministryofjustice/cloud-platform-tools-image/blob/main/Dockerfile#L1

The tools image are used in several pipelines like:
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/search?q=tools-image
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/blob/76f843da55e35f30bf13fa7ea3b2a818f5948939/pipelines/manager/main/environments-live.yaml#L29

To get the AWS CLI version 2 to the alpine image, previous workaround is here: https://github.com/ministryofjustice/cloud-platform-cli/blob/main/Dockerfile#L56-L76
But this was build on top of golang alpine.

Look into options of 

Can we fix the existing tools image to include AWS CLI V2?

Can we build the image with base Alpine image and adding ruby and AWS CLI to it?

## Definition of done

- [ ] Tools image build to include AWS CLI V2
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
Testing if its possible to build the cli in a builder image and then copy the necessary files across to the tools image.

**Comment by jackstockley89** [comment]
Pull Request: https://github.com/ministryofjustice/cloud-platform-tools-image/pull/98
