### ISSUE TITLE
Terraform Upgrade Planning

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3888]
**Background**

We need to upgrade our version of TF. This story is an initial planning story.

**Approach**

- Confirm version of TF we are moving to.
- Confirm update path i.e. can we jump straight to version or do we need to update incrementally. 
- Identify any breaking changes
- What else to we need to upgrade to carry out this upgrade?
- Outline an approach to the upgrade i.e. order we upgrade things in.

**Definition of Done**

- [ ] We are able to break down overall plan into implementation stories.

**Comment by AntonyBishop** [comment]
**Background**

We need to upgrade our version of TF. This story is an initial planning story.

**Approach**

**Comment by vijay-veeranki** [comment]
https://support.hashicorp.com/hc/en-us/articles/6302733655315-Terraform-Upgrade-Best-Practices

**Comment by vijay-veeranki** [comment]
https://www.terraform.io/language/upgrade-guides/1-0

**Comment by vijay-veeranki** [comment]
Recommended Upgrade Paths
If we were to break the terraform versions into sections, we have:

0.14 - 1.0
1.0 to currently 1.2.x
