### ISSUE TITLE
Firebreak: Kubernetes Dashboard Skooner

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3889]
Investigate good Kubernetes Dashboard 

Which cover things similar to those below
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

Investigate https://skooner.io/ and compare it with above

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by sj-williams** [comment]
Findings:
https://docs.google.com/document/d/1SR-ify3SUqa1Q-tAmj8XtXvH_1MWd3orzk46byGiwkw/edit
