### ISSUE TITLE
Upgrade Test-2 Cluster to Kube v1.10.3 with same config as Live-0

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#389]
## Definition of done

- [ ] must compile
- [ ] must pass tests
- [ ] must address all the steps of user journey

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by alkar** [comment]
This is actually captured in #388
