### ISSUE TITLE
Firebreak: Kubernetes Dashboard Kubevious

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3890]
Investigate good Kubernetes Dashboard 

Which cover things similar to those below
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

Investigate https://kubevious.io/ and compare it with above

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by razvan-moj** [comment]
Pros:
 - interesting, lots of info presented in a single app
 - easy to understand at any level of K8s knowledge
 - can be useful to tune cluster configuration for best practices
 - can replace complex apps like Prometheus, OPA, Velero with simpler and user-friendly equivalents

Cons:
 - project is very early days, bits missing, crude chart
 - features we might consider essential (multi-cluster, RBAC, SSO) are not available in the open source release
 - price of pro versions is "call us"
