### ISSUE TITLE
Upgrade velero to 2.30.0

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3899]
Velero sometimes doesnot complete the backup run and stuck in status "InProgress". However the next run is successful.
It could possibly with current version of velero ( 1.7.1) as mentioned in this issue: https://github.com/vmware-tanzu/velero/issues/4503. The fix is in v1.9.0 which needs upgrading chart to 2.30.0.

Test and Upgrade velero to latest version and deploy in manager and live cluster.

## Definition of done

- [ ] Velero upgraded in manager and live cluster
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Aged out
