### ISSUE TITLE
Check IAM/SSO works for Test-2 cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#391]
## Background

Users need to be able to access the platform using the existing model for IAM/SSO.

## Proposed user journey

As user is able to access the cluster using IAM/SSO.

## Approach

Test that we are able to access the Test-2 cluster using existing model for IAM/SSO.
If not, see https://github.com/ministryofjustice/cloud-platform-aws-meta-configuration on how to set it up.

## Definition of done

- [x] We are able to authenticate against the new cluster.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
https://moj-cloud-platform-test-2.eu.auth0.com/samlp/WAgw4FygIHs1Vny6whAjfnem6BiUr4qv
