### ISSUE TITLE
How do we keep providers up to date?

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3913]
## Background

We have decided to [pin providers for our Infrastructure repo](https://github.com/ministryofjustice/cloud-platform/issues/3882). This means we need to bet better at being aware of updates and implementing them accordingly. 

## Proposed user journey

As a Cloud Platform Team we need to be aware of updates for providers and TF modules so that we can keep our software up to date and avoid falling too far behind and/or break something that we or users rely upon.

## Approach

We have discussed trialing Dependabot to help with this. Jake has started adding Dependabot alerts. What else should be try? Do we need anything else for now?

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- Will Dependabot cover all our needs?
- What other alerting do we need?
- Will Dependabot be too noisy?
- What process do we need to manage these changes?
- What testing approach do we need?

## Definition of done

- [ ] We have a way of being notified of updates and changes so that we can plan updates into upcoming sprints

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
terrraform cli option is not available yet to display outdated providers
https://github.com/hashicorp/terraform/issues/26920

**Comment by vijay-veeranki** [comment]
- Dependabot covers our needs.
It identifies the provider versions and also raises a PR to upgrade it.
We have option to upgrade it looking at plan or skip the version with bot commands

- Will Dependabot be too noisy?
We want to watch it for a couple of weeks to see how noisy it is, as it is running only once a week, if it is too noisy we may update the schedule
