### ISSUE TITLE
Improve cli for BulkPlan to return Fatal/Error 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3914]
## Background

Cloud Platform cli does BulkPlan on pipeline on cloud-platform-infrastructure -> plan. The code is written in a way it continue to run plan on all folders  does-not returns failure. Hence, the pipelines are always green even if  the plan fails.

## Proposed user journey

Cloud-platform-infrastructure plan pipeline doesnot turn red if plan fails with error

Example pipeine: https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/cloud-platform-infrastructure/jobs/plan-cloud-platform-infrastructure/builds/232

## Approach

Code reference where the return is ignored: https://github.com/ministryofjustice/cloud-platform-cli/blob/main/pkg/terraform/cloud-platform.go#L87-L93

Update the code to capture the error return and send it back to caller so the pipeline treat it as error and turn red

## Which part of the user docs does this impact
https://github.com/ministryofjustice/cloud-platform-cli

## Questions / Assumptions

could it run plan on all workspaces, capture all errors and return finally OR
break if one of the plan fails?

## Definition of done

- [ ] Plan pipeline turns red if terraform plan on any folders fail
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
No longer required
