### ISSUE TITLE
Write user guide page for communication across namespaces

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#3917]
## Background

We've had questions several times from users asking if apps can communicate across namespaces, and what are the implications of bypassing the ingress

## Approach

 - test in a couple namespaces
 - write user guide page, detailing name resolution (svc.cluster.local), NetworkPolicies, labels, where to find the traffic logs

## Definition of done

- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] post in #cloud-platform-update

**Comment by AntonyBishop** [comment]
Duplicate
