### ISSUE TITLE
Delete cross-account-IAM repo in Infrastructure

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3918]
## Background

Delete [cross-account-IAM](https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/cross-account-IAM) as it is not used anymore in EKS

## Proposed user journey

We have this [guidance](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/access-cross-aws-resources-irsa-eks.html#use-iam-roles-for-service-accounts-to-access-resources-in-a-different-aws-account) for users to use IRSA for EKS, all users should have moved to IRSA when they migrated to EKS, so this cross-account-IAM can be deleted.

## Approach

- Check users already moved to IRSA and destroy resources in cross-account-IAM  repo

-Delete cross-account-IAM repo in the infrastructure repo.
 
## Questions / Assumptions

All users migrated to IRSA

## Definition of done

-Delete cross-account-IAM repo in the infrastructure repo.

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Done already
