### ISSUE TITLE
Node recycling: OPA policy for PDB  "ALLOWED DISRUPTIONS” = 0

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3926]
## Background

When we update the node group version or change the launch template version, we have the error “Reached max retries while trying to evict pods from nodes in node group live-default_ng_xxxx”, even using force which does not respect pod disruption budgets and it forces node restarts. The force drain mode can fail to evict pods when there are pods in CrashLoopBack state and PDB is in effect or PDB “ALLOWED DISRUPTIONS” = 0

## Proposed user journey

Create an OPA Policy to restrict deployments if the replica count is not greater than PDB min available

## Approach

OPA policy to look for PDB min available and compare it with deployment replicas and block if the replica is less than or equal to min availability.

## Definition of done

- New OPA policy 
- Tests for OPA policy
- No more PDB with ALLOWED DISRUPTIONS = 0

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
see https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/3927
Most users have or will update

**Comment by poornima-krishnasamy** [comment]
WIP PR: https://github.com/ministryofjustice/cloud-platform-terraform-opa/pull/31

**Comment by poornima-krishnasamy** [comment]
Discussed with the team on the changes needed if this policy is implemented. The effort to change the pdb to restrict with % value of users and cluster pdbs will be more and need to redo once moved to gatekeeper. Hence, it is decided to hold this until we move to gatekeeper and implement the same with Gatekeeper.

Slack thread: https://mojdt.slack.com/archives/C514ETYJX/p1659957107626949
