### ISSUE TITLE
Node recycling: work with users to update incorrect(ALLOWED DISRUPTIONS = 0) PDB

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3927]
## Background

When we update the node group version or change the launch template version, we have the error “Reached max retries while trying to evict pods from nodes in node group live-default_ng_xxxx”, even using force which does not respect pod disruption budgets and it forces node restarts. The force drain mode can fail to evict pods when there are pods in CrashLoopBack state and PDB is in effect or PDB “ALLOWED DISRUPTIONS” = 0

Existing guidance on PDB:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/pod-distruption-budgets-cluster-maintenance.html#poddisruptionbudgets-and-cluster-maintenance

## Proposed user journey

Work with users to update PDB who have PDB “ALLOWED DISRUPTIONS” = 0

## Approach

This is by increasing the replica count for their deployment

To get the list of users who have “ALLOWED DISRUPTIONS” = 0

$ kubectl get pdb -A -ojson | jq -r '.items[] | select(.status.disruptionsAllowed == 0) | .metadata.namespace + " max " + (.status.disruptionsAllowed | tostring)'

## Definition of done

- No more PDB “ALLOWED DISRUPTIONS” = 0 in the cluster

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
https://docs.google.com/spreadsheets/d/1wuuO-Tz1c4GmCPB-OHrUCz-RpXwmbDeSF4clgdj5DOs/edit#gid=413513718
