### ISSUE TITLE
Node recycling: Test new node group process

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3928]
## Background

When we update the node group version or change the launch template version, we have the error “Reached max retries while trying to evict pods from nodes in node group live-default_ng_xxxx”, even using force which does not respect pod disruption budgets and it forces node restarts. The force drain mode can fail to evict pods when there are pods in CrashLoopBack state and PDB is in effect or PDB “ALLOWED DISRUPTIONS” = 0

## Proposed user journey

Test new node group process(create a new node group and slowly reduce the node no in the old node group before killing the old one)

## Approach

Create a new node group, same as the [current node group](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf#L46-L70)

Slowly reduce the nodes on the current node group, once all pods are migrated to new node group
Delete the current node group.

## Definition of done

- Check if the PDB budget issue is not affected by node recycling
- No downtime
- Terraform apply showing no changes

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
works, demoed
