### ISSUE TITLE
Set up PagerDuty for Test-2

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#393]
## Definition of done

- [ ] must compile
- [ ] must pass tests
- [ ] must address all the steps of user journey

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
trial account created to allow me to hook up prometheus:
https://ministry-of-chaos.pagerduty.com

**Comment by jasonBirchall** [comment]
Only one master account created for now.
