### ISSUE TITLE
Demo of Hashicorp Waypoint as an alternative for prototype kit

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3932]
## Background

We did a spike into Hashicorp Waypoint a while back (#3297). We would like to see if this product is a good alternative to the current prototype service.

Waypoint offers a UI that users may find useful. Waypoint also offers a closer experience to what users were previously used to. These are hypotheses that need to be tested.

However from research we have learned:
- Prototype kit users are not technical
- Cloud Platform can sometimes be confusing for non-Dev users
- Users like to have a UI as they are less familiar with "infrastructure as code"
- User can host prototypes using our current process

## Proposed user journey

As a Designer I can host my prototype kit on the Cloud Platform so that I can conduct research with my users.

## Approach

- Install Waypoint on a test cluster
- Create demo of deploying a prototype using Waypoint
- Do the demo to users and get some feedback.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

Assumption - We won't need to carry out a new spike into this product.
Assumption - Demo doesn't require guide material
Assumption - We won't look at how we support this offering (we are just seeing if this solution resonates with users).

## Definition of done

- [ ] We have a demo of the prototype kit using Waypoint that we can demo to users to see if it's a good alternative.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
Demoed, see https://github.com/razvan-moj/waypoint-examples-raz

**Comment by AntonyBishop** [comment]
Is the intention to raise another story for the last two parts of the work?

**Comment by AntonyBishop** [comment]
Additional stores to be created.
