### ISSUE TITLE
Delete EBS snapshots older than 1 year

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3943]
## Background

We received an alert related to EBS Active snapshots, where the limit is 100000 and the current usage is 80205.

Looking further noticed that we have snapshots from “2019/05/28”

https://mojdt.slack.com/archives/C8QR5FQRX/p1658228620025229

## Proposed user journey

Agree with the team and delete snapshots older than 1 year

## Approach

Create a new lifecycle EBS snapshot policy to delete snapshots older than 1 year

## Which part of the user docs does this impact

Update ADR with this decision.

## Questions / Assumptions

We don't need snapshots older than 1 year

## Definition of done

- [ ] ADR updated
- [ ] lifecycle EBS snapshot policy created
- [x] Alert is resolved for EBS snapsort limit

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/C514ETYJX/p1661179221527129
Decision re retention.
anything older than 2 years, then 18 months, then 13
To see how much each frees up?

**Comment by pwyborn** [comment]
Over 13  months (using 1st August 2022 as starting point to go back)
```
aws ec2 describe-snapshots \                                   ✔  10064  09:45:06
    --owner-ids 754256621582 \
    --region=eu-west-2  \
    --query "Snapshots[?(StartTime <'2021-07-01')].[SnapshotId,StartTime,OwnerId,VolumeSize,Description,Size]" --output text >>over13months.csv
```
[Over 13 months results](https://docs.google.com/spreadsheets/d/1FCk8Q2hcp2gap71JtL65Rlv8oOBgwHuUuPSmiLF_Lwo/edit#gid=594382521)
Over 18 months (using 1st August 2022 as starting point to go back)
```
aws ec2 describe-snapshots \                                   ✔  10064  09:45:06
    --owner-ids 754256621582 \
    --region=eu-west-2  \
    --query "Snapshots[?(StartTime <'2021-02-01')].[SnapshotId,StartTime,OwnerId,VolumeSize,Description,Size]" --output text >>over18months.csv
```
[Over 18 months results](https://docs.google.com/spreadsheets/d/1BDhXgtStNZq1eqeU0vljPL1ELlA2vPf6xqXWk2QO4YU/edit#gid=467207613) 
Over 2 years (using 1st August 2022 as starting point to go back)
```
aws ec2 describe-snapshots \                                   ✔  10064  09:45:06
    --owner-ids 754256621582 \
    --region=eu-west-2  \
    --query "Snapshots[?(StartTime <'2020-08-01')].[SnapshotId,StartTime,OwnerId,VolumeSize,Description,Size]" --output text >>over2years.csv
```
[Over 2 years results](https://docs.google.com/spreadsheets/d/1VO8rYP5UjrS8vzIR48p32fkiI_FI1gEnyLRGtNxCsXY/edit#gid=367076836)

**Comment by pwyborn** [comment]
all snapshots < 01.07.2021 whether us or users are deleted now

**Comment by pwyborn** [comment]
"We need automation take to clean that up regularly" will be another ticket
