### ISSUE TITLE
Update OpenSearch Service domain

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3946]
## Background

A software update is required for your Amazon OpenSearch Service domain. The service software R20220323-P4 contains important updates and we recommend updating your domain as soon as possible to the latest service software update. OpenSearch Service domains not updated to R20220323-P4 or a later version by **July 31, 2022** will be automatically updated.

The following are your domain(s) that must be updated:
cloud-platform-audit-live
cloud-platform-live
cloud-platform-audit

For more information on updating the service software of your domains, please see the documentation [1].

[1] https://docs.aws.amazon.com/opensearch-service/latest/developerguide/service-software.html

## Approach

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/service-software.html

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] Update completed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Updated to R20220323-P5 (latest)
