### ISSUE TITLE
Fix Memory-High Alert

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3949]
## Background

We are frequently getting Memory-High Alert. This alert is triggered when the memory usage is at or over the limit for 5 minutes

https://mojdt.slack.com/archives/C8QR5FQRX/p1658234086169499

## Approach

Investigate if we need to increase our node size as we are getting more users on board. 

- Increase size of the nodes
- You can set [Memory limits](https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/) to pods and containers, as by default - pods run with unbounded memory limits.
- Concourse recycle node run multiple times a day

## Questions / Assumptions

**Why are we seeing more alerts?**

## Definition of done

- [x] We have a theory about why we are seeing more alerts
- [ ] No more memory high alert

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
We have previously changes the node memory alerts thresholds, we will also up the memory on the cluster by using a larger node size for the default nodes
