### ISSUE TITLE
Test our workloads using containerd during the 1.21 lifecycle 

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#3951]
## Background

In the next release of EKS with Kubernetes 1.22 we will be changing the default runtime from Docker to containerd. This means EKS 1.21 will be the last release with Docker container runtime support. It is recommended that you test your workloads using containerd during the 1.21 lifecycle so you can make sure you don't depend on any Docker specific features such as mounting the Docker socket or using docker-in-docker for container builds.

## Proposed user journey

Before upgrading to 1.22
Test our workloads using containerd during the 1.21 lifecycle so you can make sure you don't depend on any Docker specific features such as mounting the Docker socket or using docker-in-docker for container builds.

## Approach

If it is affected, create separate tickets to work on it.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Supported until Kubernetes 1.24 - https://mojdt.slack.com/archives/C514ETYJX/p1666790035327659
