### ISSUE TITLE
Spike: Create a single load balancer for each Availability Zone

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3955]
## Background

> On 11th July 2022, users start reporting a portion of their traffic is not responding or timing out. The previous day (10/07/22) saw AWS restart a large number of nodes due to a “thermal incident” (TAM). This new report resulted from a network interface in the live-1 VPC responding successfully to around 75% of traffic (rough estimate). This caused a degradation for all services in the Cloud Platform for approximately 6 hours and 37 minutes. 

We must find a way to mitigate this in the future.

Source: https://docs.google.com/document/d/1QR31_9Ga_LdXSzgoFjiemE-jxq5sf59rKj5gAoNTU9E/edit#

Following a post-incident review, the team came up with the following action:

We currently have one ingress controller that spans multiple availability zones (AZ; eu-west-2 a, b and c). To mitigate the failure of an AZ it was recommended that we create a single load balancer for each AZ.

## Proposed user journey

As a Cloud Platform developer, we can create and maintain three new ingress controllers/load balancers (LB), each in their own AZ. The load-balancer should only know about the interface in its own AZ respectively. An ingress rule annotation should then split 1/3 of an application's traffic between each of the LB's.

As a developer/user of the Cloud Platform, I want to have zero impact on my application when a load balancer fails.

## Approach

- [ ] Create three load balancers in a test cluster, each in its own AZ.
- [ ] Balance traffic using Nginx annotations in an ingress rule.
- [ ] Perform failure scenarios, such as deleting a controller, and confirm the impact on an application.
- [ ] Document any code and explain its purpose.
- [ ] Demonstrate back to the team in the form of a presentation.
- [ ] Recommend future action.

## Which part of the user docs does this impact

Document the process of installation and maintenance.

## Questions / Assumptions

[assumption] that losing one of the three ingress controllers would result in normal (uninterrupted) traffic flow.

[question] how would you split the annotation weighting, 33.3%?

## Definition of done

- [ ] Three controllers exist in the cluster
- [ ] Annotation weighting distributes the traffic across all three controllers
- [ ] The process of losing a controller has proved to be seamless (not interrupting end-user traffic)
- [ ] The process is demonstrated to the team and a decision is made on whether to continue.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
One way of creating a nlb with single AZ is to have all targets(ingress-controller pods) in one az(nodes in single az) and disable cross-load-balancing.

**Comment by sablumiah** [comment]
It is possible to create and install 3 different nginx-ingress-controllers in a different subnet each using the following annotation:

service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xxxx, mySubnet

for the nginx service which already has annotations such as 

service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

We would lose automated AZ failover if there was an issue in that AZ and failed its healthcheck.

As there are 3 individual ingress-controllers, they each require a unique ingress class and there is no native load balancing between the 3 different ingress-controllers if the same ingress class was used in all 3
