### ISSUE TITLE
Spike: Is it possible to create an ingress controller without an interface/zone?

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3957]
## Background

On 11th July 2022, users start reporting a portion of their traffic is not responding or timing out. The previous day (10/07/22) saw AWS restart a large number of nodes due to a “thermal incident” (TAM). This new report resulted from a network interface in the live-1 VPC responding successfully to around 75% of traffic (rough estimate). This caused a degradation for all services in the Cloud Platform for approximately 6 hours and 37 minutes.

We must find a way to mitigate this in the future.

Source: https://docs.google.com/document/d/1QR31_9Ga_LdXSzgoFjiemE-jxq5sf59rKj5gAoNTU9E/edit#

Following a post-incident review, the team came up with the following action:

Investigate if it's possible to create an ingress controller omitting either a zone or an interface.

## Proposed user journey

As a Cloud Platform developer, I can create a new load balancer and select to omit a specific zone or an interface IP. In the event of an interface failure, I'm able to eject it from the list of "targets".

## Approach

- [ ] In a test cluster, create a new ingress controller with two out of three zones selected
- [ ] Confirm having a reduced number of zones doesn't impact the performance of apps in the cluster.
- [ ] Demonstrate this to the team and wider stakeholders through a presentation.
- [ ] Present your opinion on whether to go forward with the approach.

## Which part of the user docs does this impact

None that I'm aware of.

## Questions / Assumptions

[question] is this even possible?

## Definition of done

- [ ] Confirmed if we can create a controller with selective zones/interfaces
- [ ] Demonstrated to the team
- [ ] Decision has been made on the next steps.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Helm chat doesn't have an option around creating without an interface.
It is all controlled subnets with in the VPC
https://aws.amazon.com/blogs/opensource/network-load-balancer-nginx-ingress-controller-eks/
https://aws.amazon.com/blogs/aws/new-network-load-balancer-effortless-scaling-to-millions-of-requests-per-second/
