### ISSUE TITLE
Set up Slack Channel for Test-2 notifications

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#396]
## Background

As part of chaos engineering tests we want any notifications to go to a channel where they can be identified that is not in the main production channels.

We will create a new channel for notifications to go to.

## Proposed user journey

Notifications for the Test-2 Cluster go to the correct Slack channel.

## Approach

Create a new Slack Channel (Name to be agreed).
Configure monitoring to send alerts to new Slack channel.
Test that alerts to the the new Slack Channel.

## Definition of done

- [x] Slack channel created for Test-2 notifications
- [x] Test notifications are going to the new channel.
- [x] Notifications go to the newly created Slack channel 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
#coud-platfoprm-chaos

**Comment by sablumiah** [comment]
#cloud-platform-choas
