### ISSUE TITLE
User Research - Standard Log Templates

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3964]
## Background

We have loads of feedback that the current logging solution isn't great for application logs. The output that teams get isn't usable.

We've had a review of our ElasticSearch and one of the recommendation that will help address this need to to have a template for logs. This will ensure there is a defined way in which users output their logs.

## Approach

We need to reach out to users to understand more about who they are currently using their logs.

- We need to understand how they are outputting logs now.
- How and when are they using logs?
- What output/results are they expecting to see

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

TBC

## Definition of done

- [x] We have feedback/research on logs that will help define an appropriate template

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
@ScottSeaward FYI

**Comment by ScottSeaward** [comment]
Have posted an initial survey today (01/08/22) and reached out to start a conversation. 
https://forms.gle/xyqDJc2ydNsFPHgLA

**Comment by ScottSeaward** [comment]
poor response so far (5) have reposted wider

**Comment by ScottSeaward** [comment]
No further feedback from users. We held a feedback session with the team. Doc here - https://docs.google.com/document/d/1evWoXQ7v7pihuGZikSRG7rxtcfUJjwr7l8uy6zEVdRA/edit?usp=sharing
