### ISSUE TITLE
ElasticSearch upgrade to 7.10

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3967]
## Background

As a platform we aim to keep our various components up to date.  This story is for implementation of the ElasticSearch upgrade to 7.10.

The benefit of this upgrade is that it introduces cold storage features that will enable us to optimise some of our AWS costs on ElasticSearch (which is our most expensive resource.

## Approach

Carry out minor upgrade to 7.10.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] ElasticSearch upgraded to 7.10

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
Waitinf on https://github.com/hashicorp/terraform-provider-aws/issues/26045

**Comment by razvan-moj** [comment]
done in https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1781
