### ISSUE TITLE
Smoke test: Ingress works

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#399]
## Background

We need to test that when a user creates an `Ingress`, traffic can actually reach a `Pod`.

## Approach

Setup a test that creates a temporary namespace, launches a service in it (it doesn't necessarily have to be a `Deployment`,  a simple `Pod` can suffice) with an HTTP listener, a `Service` and an `Ingress` and test that you can hit the URL and get a 200 OK.

Keep it as minimal as possible, eg:

- `kubectl apply resources.yaml` (where you have defined the above)
- wait until the pod status is `Completed` (eg:. you can use `kubectl describe pod` and `grep`/`jq` the output)
- send the HTTP request to the Ingress hostname and check the output
- clean up: `kubectl delete <namespace>`

Hint: you can put a python script in a `Configmap` and mount that into a generic docker container (perhaps alpine?) to avoid having to build an image. See [here](https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/cloud-platform-live-0.k8s.integration.dsd.io/authorized-keys-provider/provider.yaml) for an example.

## Questions / Assumptions

N/A

## Definition of done

- [x] Have a script (shell/python) that runs this test. Call it `test`.
- [x] Demonstrate that you can run the above on your laptop
- [x] Commit the code to https://github.com/ministryofjustice/cloud-platform-smoke-tests (put all relevant resources under a directory like `tests/01-ingress-http-traffic/`). 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-smoke-tests/pull/2
