### ISSUE TITLE
Clean up unused CloudWatch logs for Clusters that no longer exist

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#3992]
## Background

We have some logs that are no longer required and clusters have been deleted. We should tidy these up and save some money.

Slack thread [here](https://mojdt.slack.com/archives/C514ETYJX/p1658850704644099).

## Approach

Remove unwanted logs.

## Definition of done

- [ ] Unused logs cleaned up.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/920

**Comment by vijay-veeranki** [comment]
Deleted un-used cluster log groups

Also raised this ticket
https://github.com/ministryofjustice/cloud-platform/issues/4061
