### ISSUE TITLE
AWS EFS file system support

### ISSUE THREAD

**Issue by adeweetman-al** [ministryofjustice/cloud-platform#3994]
## Service name

HMPPS - VCMS

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service
Follows slack thread https://mojdt.slack.com/archives/C57UPMZLY/p1658826186205039

We are wanting to migrate an existing containerised application from its current AWS account to the Cloud Platform.
It has some dependencies that are covered by existing features and terraform modules but one such dependency is AWS EFS. (The current prod environment for this app contains ~450GB in an EFS file system). Without support for this dependency, we would be unable to migrate the app in its present form.

## Problem description

There is no cloud platform terraform module for creating an EFS file system, including configuration for mount points, access points and file system policy. Happy to create one ourselves but I understand you normally curate these kinds of modules.
In addition to the EFS module, in order to be able to create a static k8s PV referencing the EFS file system please can you perform the EFS CSI installation into the cluster (AWS EKS doc link - https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html)

## Contact person

Raised by Adrian Weetman, HMPPS probation webops lead
email [adrian.weetman@digital.justice.gov.uk](mailto:adrian.weetman@digital.justice.gov.uk)
team slack (please use this for any comms) #ask-probation-webops

**Comment by adeweetman-al** [comment]
Hi, in addition to the above that mentions configurable attributes related to EFS, it'd be great if we had
- control over backup and retention - e.g. per environment to set appropriate restore points and manage costs. I anticipate to do this we'd by provisioning AWS backup vaults, plans etc. and associating to the EFS file system? Would we need an cloud platform AWS backup vault terraform module for this (I don't think one exists)
- control over life cycle policies and storage classes - there are some good cost savings to be had with being able to store infrequently accessed files in the IA storage class
- support for encryption (may be an obvious one but worth stating)

Please feel free to come back with any qus.

**Comment by razvan-moj** [comment]
Waiting for https://support.console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=10591647471&language=en

**Comment by razvan-moj** [comment]
https://docs.aws.amazon.com/efs/latest/ug/logging-using-cloudtrail.html says logs are different if encrypted, checking.. so far Cloudtrail has shown only 
```
    "userIdentity": {
        "type": "AWSAccount",
        "principalId": "",
        "accountId": "ANONYMOUS_PRINCIPAL"
    },
```
no matter what I tried

**Comment by razvan-moj** [comment]
After a conversation with AWS support, we are waiting for https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/280

Still blocked.

**Comment by adeweetman-al** [comment]
Looks like the above dependent PR was merged - good news! Are you able to pick up your planned changes again?

**Comment by razvan-moj** [comment]
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/777 release was broken :(
