### ISSUE TITLE
Test and update user guide related to SecAuditLogParts

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4002]
## Background

Modsec v1 ingress controller global config has set  to "SecAuditLogParts AEFHKZ" in except the body (I) as this is exposing "Compact request body alternative (to part C)" 

Some users may want to include (I), this may be achieved by adding modsec SecAuditLogParts annotation in the ingress. 

## Proposed user journey

Test this process to see if adding (I) to SecAuditLogParts at the ingress level will show the "Compact request body alternative (to part C)"  logs in kibana for that particular ingress

## Approach

Test and update the user guide.

## Which part of the user docs does this impact

User guide

## Definition of done

- [ ] Test complete
- [ ] user docs have been updated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Included in #4003
