### ISSUE TITLE
Leaver - Chris Hanes

### ISSUE THREAD

**Issue by KPobeeNorris** [ministryofjustice/cloud-platform#401]
## Service name

Prison Visits Booking (PVB)

## Service environment

- [ ] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Chris Hanes (aka chrishanes) no longer works for PVB and we are currently going through the process of removing his access to various services. We would like to request that any access he has via Cloud Platform (e.g. AWS/SSH, Sentry, Rattic) also be revoked.

## Problem description

We want to ensure that only those employed, and have the correct permissions, have access.

## Contact person

Slack - kath.pobee-norris

**Comment by sablumiah** [comment]
https://dsdmoj.atlassian.net/wiki/spaces/PLAT/pages/324076142/Leavers

**Comment by sablumiah** [comment]
Everything within CP remit has been deactivated
