### ISSUE TITLE
Clean up unused VPC endpoints

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4016]
## Background

Clean up unused VPC endpoints. Will reduce cost and improve security.

## Approach

Identify and clean-up unused VPC endpoints.

## Which part of the user docs does this impact

N/A

## Definition of done

- [ ] Unused endpoints removed.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
No un-used VPC endpoints
