### ISSUE TITLE
Remove unused RDS instances

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4018]
## Background

Clean-up and unused RDS instances

## Approach

Clean-up and unused RDS instances

## Definition of done

- [ ] Unused RDS instances removed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
https://docs.google.com/spreadsheets/d/1yF4sdsvuygvo1V7s5Btkt-OxmwcwhZbBOKEj7Q33Wuw/edit#gid=0

**Comment by vijay-veeranki** [comment]
Sent comms to delete unused RDS or stop and start during non-business hours
https://mojdt.slack.com/archives/CH6D099DF/p1661873190548329
