### ISSUE TITLE
Clean up unused EIPs

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4019]
## Background

Identified 6 EIPs that are not attached to an instance. These should be cleaned up.

## Approach

Verify EIPs are not needed and remove them.

## Definition of done

- [ ] Unused EIPs cleaned up

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Released un-used EIP
