### ISSUE TITLE
Demo Waypoint web interface outside the team

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#4022]
## Background

Continuation of https://github.com/ministryofjustice/cloud-platform/issues/3932

## Approach

Polish a deployment to match the functionality of the current prototype kit; ensure users do not need to touch the waypoint CLI - this is just a GUI demo.

## Definition of done

- [ ] demo done
- [ ] feedback collected
- [ ] follow-up story written

**Comment by AntonyBishop** [comment]
Paused.

**Comment by AntonyBishop** [comment]
Abandoned
