### ISSUE TITLE
Document changes need in CLI and runbooks for Waypoint

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#4023]
## Background

Continuation of https://github.com/ministryofjustice/cloud-platform/issues/3932

## Approach

Describe (stretch goal - mock) changes in cloud-platform-cli

Describe changes needed in runbooks

Describe changes needed in user-guide

## Definition of done

- [ ] draft for CLI discussed with them
- [ ] draft PRs for docs and runbooks

**Comment by AntonyBishop** [comment]
Abandoned
