### ISSUE TITLE
Spike: Investigate using Secrets Manager 

### ISSUE THREAD

**Issue by jackstockley89** [ministryofjustice/cloud-platform#4024]
## Background

Question out of using Secrets Manager with Concourse, was best way to deploy Secrets Manager.
- Should they just be part of the Infrastructure Repo
- Or could they be separated into there own Repo and managed all secrets from here 
- Also could we create a module that can be offered to the users in the future
- Should we integrate secrets manager into the cluster

## Approach

- Need to look to see if using terraform can create a module that can create secrets
- Can secrets be populated from code or manually managing these secrets a better option
- Is integrating Secrets Manager with Kubernetes cluster the. best approach for future use
https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html

## Which part of the user docs does this impact

Create a run-book to document the process

## Definition of done

- [ ] readme has been updated
- [ ] run-book has been created
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Aged out
