### ISSUE TITLE
Fix destroy cluster failure

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4026]
Destroy cluster pipeline is failing to delete components, which may be due to ingress controller module dependency added in other modules, [here](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf#L126) and [here](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf#L179-L180)

Every weekday, create a test destroy cluster pipeline run and failing at destroying pipeline with error:

Error: uninstall: Release not loaded: nginx-ingress-default: release: not found
Error: uninstall: Release not loaded: nginx-ingress-modsec: release: not found

Investigate the cause of the failure and fix it

**Comment by pwyborn** [comment]
First failure of that type:
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/eks-create-test-destroy/jobs/destroy-cluster/builds/127.1
started	Jul 20 2022 10:23:39 AM
I wonder what changed?
[Uploading... Screen Shot 2022-08-09 at 09.26.25.png]

**Comment by vijay-veeranki** [comment]
Destroy cluster is running successfully now.
