### ISSUE TITLE
Implement creating secrets in GitHub environments

### ISSUE THREAD

**Issue by makl3** [ministryofjustice/cloud-platform#4039]
## Service name

analytical-platform-uploader

## Service environment

- [ ] Staging
- [ ] Prod / Production

## Impact on the service

Potential blocker for automating our deployment

## Problem description

We use GitHub Environments to deploy the application in preprod and prod environments. It would be good if KUBE and ECR secrets could be created as Environment secrets (and not just as repo secrets).
This issue started from https://mojdt.slack.com/archives/C57UPMZLY/p1658301926823289
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

## Contact person

prisonprobationdataengineering@digital.justice.gov.uk

**Comment by vijay-veeranki** [comment]
Updated SA and ECR module, where users can use "github_environments" to provide env names to get the secrets added

https://github.com/ministryofjustice/cloud-platform-terraform-serviceaccount/blob/main/examples/serviceaccount.tf#L15
