### ISSUE TITLE
CCR and CCLF domain changes

### ISSUE THREAD

**Issue by mkal-digital** [ministryofjustice/cloud-platform#4049]
## Service name

CCR and CCLF

## Service environment

- DEV
- TEST
- UAT
- STAGING
## Problem description

https://dsdmoj.atlassian.net/browse/LAWS-2763?atlOrigin=eyJpIjoiMjczNjEwYzBiOGJjNDIyNWE5MmJhYjM4NWM2NzEzZGUiLCJwIjoiaiJ9 
This is part of the new DNS names for both CCR and CCLF  

## Contact person

Malaz Khalil, malaz.khalil@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
Changed from

development.crown-court-remuneration.service.justice.gov.uk CNAME ccr.aws.dev.legalservices.gov.uk
uat.crown-court-remuneration.service.justice.gov.uk CNAME ccr.aws.uat.legalservices.gov.uk
test.crown-court-remuneration.service.justice.gov.uk CNAME ccr.aws.tst.legalservices.gov.uk
staging.crown-court-remuneration.service.justice.gov.uk CNAME ccr.aws.stg.legalservices.gov.uk

to

development.crown-court-remuneration.service.justice.gov.uk = CCR-LoadBalancer-1091037848.eu-west-2.elb.amazonaws.com
uat.crown-court-remuneration.service.justice.gov.uk = CCR-LoadBalancer-1571015314.eu-west-2.elb.amazonaws.com
test.crown-court-remuneration.service.justice.gov.uk = CCR-LoadBalancer-318993240.eu-west-2.elb.amazonaws.com
staging.crown-court-remuneration.service.justice.gov.uk = CCR-LoadBalancer-558150826.eu-west-2.elb.amazonaws.com

**Comment by razvan-moj** [comment]
also done
development.crown-court-litigator-fees.service.justice.gov.uk/ = CCLF-LoadBalancer-1777163539.eu-west-2.elb.amazonaws.com
test.crown-court-litigator-fees.service.justice.gov.uk/ = CCLF-LoadBalancer-1185505617.eu-west-2.elb.amazonaws.com
staging.crown-court-litigator-fees.service.justice.gov.uk/ = CCLF-LoadBalancer-1848582602.eu-west-2.elb.amazonaws.com
uat.crown-court-litigator-fees.service.justice.gov.uk/ = CCLF-LoadBalancer-1234551591.eu-west-2.elb.amazonaws.com

**Comment by mkal-digital** [comment]
Hi Razvan could you change them the following

CCLF
development.crown-court-litigator-fees.service.justice.gov.uk/ = d2iyfe7wqvs1jt.cloudfront.net.
test.crown-court-litigator-fees.service.justice.gov.uk/ = d1cju52nxd42uw.cloudfront.net.
staging.crown-court-litigator-fees.service.justice.gov.uk/ = d1ektl2nv8gnnw.cloudfront.net.
uat.crown-court-litigator-fees.service.justice.gov.uk/ = d16uew0t6womwl.cloudfront.net.

CCR
development.crown-court-remuneration.service.justice.gov.uk = d1wrwrchbburlp.cloudfront.net.
uat.crown-court-remuneration.service.justice.gov.uk = d8p2dvh7d1ke4.cloudfront.net.
test.crown-court-remuneration.service.justice.gov.uk = d1zsr4drpww1mm.cloudfront.net.
staging.crown-court-remuneration.service.justice.gov.uk = d1maqn0gxjtkgl.cloudfront.net.

**Comment by razvan-moj** [comment]
done

**Comment by mkal-digital** [comment]
Hi Razvan, could you please make the following change? Apologies there's a lot of testing going on 
CCR
development.crown-court-remuneration.service.justice.gov.uk = d1nbqcpbw7j0nx.cloudfront.net

**Comment by razvan-moj** [comment]
done

**Comment by mkal-digital** [comment]
Thank you
