### ISSUE TITLE
Find a way to list all the aws resources created when creating a cluster

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4051]
## Background

When a test cluster is created, there are a number of aws resources created i.e. vpc, subnets, EIP, snapshots etc. Find a way to list all the resources that will be created as part of cluster creation

This will be useful to cross-check when deleting the cluster to see if all the aws resources are removed.

The goal is to not leave any leftovers in the aws account after the cluster is deleted.

This could be a big epic and involve several tasks:
In the ephemeral account run the script to create the cluster
- Using Tag editor to list the resources
- Check if all resources are tags with the cluster name. This will be useful when to list all resources by tag
- Delete the cluster
- Either through sdk or from UI search for all resources listing the tag : cluster-name

If there are any left overs, check why it has not deleted i.e. is the destroy not successful, or include deleting the resources as part of destroy script

## Definition of done

- [ ] There are no left overs after cluster deletion
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
![Screenshot 2022-08-23 at 11.28.54.png](https://images.zenhubusercontent.com/5c9397ffbb416905afa23685/a99d63a5-2dbc-4655-92e3-e8031f88d21d)

**Comment by jasonBirchall** [comment]
Following a delete, all resources deleted, bar:

**Comment by jasonBirchall** [comment]
8 snapshot volumes
