### ISSUE TITLE
Storing Metrics

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#406]
## Service name

Prison Visits Booking

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

GDPR compliance 

## Problem description

We currently store a range of metrics about the Prison Visits Booking service which are accessed through metrics dashboard at https://staff.prisonvisits.service.gov.uk/en/metrics. A range of stakeholders access this data.

Currently we generate charts by running SQL queries on our data. Metrics are presented from the inception of the service (5 + years ago). As a result, time to load the page is often slow and we suspect it may crash if multiple people try to access the page at the same time.

As part of GDPR compliance, we will be required to delete data in our database that is older than twelve months. This will therefore prevent us from show metrics prior to twelve months.

As part of a spike, we are looking at what options are available moving forwards for storing and presenting metrics. One option would be to store aggregate data in new tables on Postgres, another could be to use a managed service that specialises in storing and presenting metrics.

We would like to know whether MOJ has access to a managed service for storing metrics (i.e. by firing events) such as Influx DB, or there are alternative solutions (provided through Cloud Platform) that could be considered.

## Contact person

Toby / @Toby Retallick

**Comment by AntonyBishop** [comment]
![Screen Shot 2018-09-27 at 15.30.34.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5af99512f7ba4500119c1fce/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f46b7191a379ea0c2851415c4abe5d4a1f06a3a3dc78e2a436628f0d5de883680d73c63f18acbb861fbf03bf76d84d83e0e99850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecb50f64ee94b52a7173e66f43b.png)
