### ISSUE TITLE
Improve unit test coverage: cloud-platform-cli

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#4062]
## Background

We recently created a GitHub Action in our cloud-platform-cli application that reports the unit test coverage in our repository. It sadly reported a miserly 28% coverage. While this isn't a true indication of code quality or how well the Cli performs, we should aim for at least 50% coverage. This brings confidence to develop new features without breaking current functionality.

## Proposed user journey

As a developer of the Cli application, I want confidence that adding new features won't break current functionality. A good starting point is to aim for 50% test coverage.

## Approach

Using the link below, identify packages that have the lowest test coverage, and look for the most effective tests to implement.

https://app.codecov.io/gh/ministryofjustice/cloud-platform-cli

## Which part of the user docs does this impact

Perhaps place an entry in the README stating the minimum unit test coverage expectation.

## Questions / Assumptions

An assumption that is often challenged is the requirement to measure test coverage.

## Definition of done

- [ ] we have at least 50% test coverage
- [ ] readme has been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
Tests added to improve. coverage. 
https://github.com/ministryofjustice/cloud-platform-cli/pull/243
https://github.com/ministryofjustice/cloud-platform-cli/pull/244
