### ISSUE TITLE
Figure out a way to create Index State Management policies using terraform

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#4068]
## Background

To save costs but store more data, we removed the curator (https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1843) and used a policy similar to https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch/blob/cold/ism-policy.tpl.json
The policy is now applied manually and only visible by going to Kibana.

## Approach

Test a provider like https://registry.terraform.io/providers/disaster37/elasticsearch/latest/docs/resources/elasticsearch_index_lifecycle_policy; others are available, none "official".

If nothing works, update the runbooks to mention a workaround.

## Definition of done

- [ ] runbook updated
- [ ] tf code in infrastructure updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

**Comment by sj-williams** [comment]
Tested provider:
https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs

This requires configuring provider to interact via elasticsearch endpoint, so terraform executor must have route (tested using port-forward `aws-es-proxy-service`

Adding and applying of ISM policies to indices working.

https://github.com/ministryofjustice/cloud-platform-terraform-elasticsearch/tree/ism-policy-tf/example/ism_testing

**Comment by vijay-veeranki** [comment]
This is completed, separate ticket raised for user ES module
https://github.com/ministryofjustice/cloud-platform/issues/4088
