### ISSUE TITLE
Review and update velero backup config and get removal of expired backups working

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4072]
## Background

Currently, velero is backing up all namespaces and volumes, revisit the velero and update the configuration to back up only as required.

## Proposed user journey

Review of schedules
https://github.com/ministryofjustice/cloud-platform-terraform-velero/blob/main/templates/velero.yaml.tpl#L114

Upgrade to the latest version as we have a fix Removal of expired backups does not work

https://github.com/vmware-tanzu/velero/issues/3094#issuecomment-1064938950

Review usage of Velero ConfigMaps to restic
https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml#L433-L442

## Approach

Review of schedules and update as relavent
https://github.com/ministryofjustice/cloud-platform-terraform-velero/blob/main/templates/velero.yaml.tpl#L114

Upgrade to the latest version as we have a fix Removal of expired backups does not work

https://github.com/vmware-tanzu/velero/issues/3094#issuecomment-1064938950

## Definition of done

- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] Velero only takes backup as required 
- [ ] Velero backup clean up work as expected

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
No longer required
