### ISSUE TITLE
Check EBS snapshots are encrypted

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4075]
## Background

It's best practice to have snapshots encrypted. We have recently tied up some old snapshots and we should check that what we have is encrypted by default.

## Approach

Check that EBS snapshots are created with encryption by default. If not, enable encryption as the default.

## Definition of done

- [ ] We have EBS snapshots encrypted.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
After testing unable to do a in place update due to the kind being statefulset that doesnt allow this type of update. Best action would be to delete the current volumes and allow them to create with the new default which is using gp3 and this is encrypted as default.
