### ISSUE TITLE
Review Amazon EC2 Availability Zone Balance

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4076]
## Background

Trusted Advisor has pointed out that we have an uneven balance of EC2 across availability zones. 

We just want to check that that is as expected. Is there are particular reason why a specific zone is favoured over others? Are we concerned about that?

This story is to investigate the behaviour and determine if further action is required.

## Definition of done

- [x] We understand why the EC2 balance across AZs is the way it is.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
The monitoring node is created in eu-west-2b AZ by default. Currently there are 16 extra monitoring nodes in the CP account

Current in eu-west-2a there are 26, eu-west-2b - 43 and eu-west-2c - 25 instances
There are 16 monitoring node instances which makes the eu-west-2b AZ higher than the other 2 AZ.

**Comment by poornima-krishnasamy** [comment]
The monitoring nodes has to be in one particular zone where the volume that attached to it. In case of a failure on that zone, the prometheus module will be changed to use different AZ zone. However, this will need re-creating prometheus and we will lose prometheus data. We know the consequence and how to recover from a failed az.
