### ISSUE TITLE
Exporting ElastiCache metrics to Prometheus

### ISSUE THREAD

**Issue by vc13837** [ministryofjustice/cloud-platform#4078]
## Service name

hmpps-victim-case-management-system-dev

## Service environment

Dev

## Impact on the service
 
As part of migration for the victim-case-management-system application, at the moment I cannot create alarms to monitor my ElastiCache Redis cluster. This alarms will need to be implemented in the Dev env, before proceeding onto higher envs. Note that there are currently no users yet and this is being implemented for the first time.

## Problem description

Currently, the metrics for aws_elasticache* in Prometheus are only cumulated and is not per cluster. 

## Contact person

Slack @ Vincent Cheung, Email - [vincent.cheung@digital.justice.gov.uk](mailto:vincent.cheung@digital.justice.gov.uk)
Team email - probation-webops@digital.justice.gov.uk
Team channel - #probation-webops

**Comment by razvan-moj** [comment]
done in https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1878
