### ISSUE TITLE
Update RoleBinding API versions from v1beta1 to v1

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4079]
## Background

The RoleBinding API version v1beta1 is deprecated and removed from kubernetes 1.22. Update the RoleBinding version to v1 before the 1.22 upgrade.

The Users namespace RoleBindings are defined in the environment repo. The deprecation guide mentions no notable changes and all existing persisted objects are accessible. 
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22.

## Definition of done

- [ ] Update RoleBindings versions from v1beta1 to v1
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Suggested we are not going to do this before 1.22 upgrade
