### ISSUE TITLE
Resize live-0 nodes to better fit our resource requirements

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#408]
## Background

We currently seem to have more capacity than we need. Investigate whether it would make sense to change the instance sizes for the worker nodes and what instance would be a better choice. Ideally, we want to be scaling horizontally in the future while maintaining the same instance size for nodes.

## Proposed user journey

N/A

## Approach

1. Investigate how much resource we are using and confirm any delta between actual usage and what has been provisioned.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

1. Do we actually need to resize nodes?
2. What else related to Availability Zones should we look at?

## Definition of done

- [x] Answer whether we need to resize the nodes?
- [ ] if so, raise a PR with the proposed changes and perform a rolling-update

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Instance size list:
https://aws.amazon.com/ec2/instance-types/
```
Model	        vCPU    Mem (GiB) Storage
c4.large 	2 	3.75 	EBS-Only 	500
c4.xlarge 	4 	7.5 	EBS-Only 	750
c4.2xlarge 	8 	15 	EBS-Only 	1,000
c4.4xlarge 	16 	30 	EBS-Only 	2,000
c4.8xlarge 	36 	60 	EBS-Only 	4,000
```

**Comment by jasonBirchall** [comment]
According to our Grafana metrics, we're using 41% memory, 27% disk and at any given time only 30% CPU utilisation.

**Comment by jasonBirchall** [comment]
https://grafana.apps.cloud-platform-live-0.k8s.integration.dsd.io/d/JVR9vzxmz/kubernetes-capacity-planning?orgId=1

**Comment by jasonBirchall** [comment]
After a long chat with @alkar it was decided that we will drop the worker node instance to c4.xlarge and re-assess in one months time.

**Comment by jasonBirchall** [comment]
New node size applied to live-0 and changes commited to repo. Closing ticket.
