### ISSUE TITLE
Update Calico CRDs API version from v1beta1 to v1

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4080]
The Calico CRDs API version v1beta1 is deprecated and removed from kubernetes 1.22. Check the upstream for latest CRD versions and update the same.

The Calico CRDs are defined here: https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/resources/calico-crds.yaml

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22.
https://github.com/aws/eks-charts/tree/master/stable/aws-calico

## Questions / Assumptions

The current calico chart is not maintained. Should we look into alternative suggested?
https://github.com/aws/eks-charts/tree/master/stable/aws-calico#calico-on-aws

## Definition of done

- [ ] Calico CRDs updated with v1 API versions
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Done
