### ISSUE TITLE
Upgrade thanos component to latest

### ISSUE THREAD

**Issue by pwyborn** [ministryofjustice/cloud-platform#4083]
## Service name
Thanos

## Background

The hoodaw application has identified this component as out of date.
installed: 8.3.0
latest: 10.5.5

src: https://reports.cloud-platform.service.justice.gov.uk/helm_whatup

## Proposed user journey

Identify which upgrade path to take, test it using a test cluster and environment.

## Which part of the user docs does this impact

If the install requires extreme work, ensure the user documentation is still relevant.

## Questions / Assumptions

The upgrade path is smooth and doesn't require a complete rework.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

**Comment by AntonyBishop** [comment]
Done
