### ISSUE TITLE
Test KMS/SQS additions to cloud-platform-terraform-aws-sso

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/cloud-platform#4089]
## Background

A user has requested extended permissions for KMS and SQS access through the console and has [opened a PR](https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/pull/8/files).

## Approach

Test that the PR provides sufficiently scaled-down permissions to follow the principal of least privilege for the task.

## Definition of done

- [ ] PR merged
- [ ] Manual testing completed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
KMS is fine, but unfortunately  https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html states SQS is a "no" for ABAC, so send/recv does not work. Opened https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=10778485391&language=en to chase with AWS.

In the meantime, we can only offer CW metrics, see https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/pull/9

**Comment by jakemulley** [comment]
Reopening due to - https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-sqs-attribute-based-access-control-abac-flexible-scalable-access-permissions/
