### ISSUE TITLE
Spike-Split infrastructure components

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4092]
## Background

Creating and destroying infrastructure components causing issues, Spike on tiered components layer.

Check if we need to remove the dependencies on each thing, to make it much clearer as to what the actual dependencies are and whether things can be created in parallel or not.

Some errors:

Error: could not download chart: failed to download
Error: Kubernetes cluster unreachable:
Error: unable to build kubernetes objects from release manifest:
dial tcp: lookup no such host
socket: too many open files

## Proposed user journey

 Spike on tiered components layer.

## Approach

Some threads related to it:
https://mojdt.slack.com/archives/C514ETYJX/p1661519592030389

https://mojdt.slack.com/archives/C514ETYJX/p1660749745209949

## Definition of done

- [ ] Spike results in options to fix issues and dependencies around infrastructure components

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Aged out
