### ISSUE TITLE
Use Trivy Operator for container scanning

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#4093]
## Background

Trivy-Operator leverage the trivy security tools by incorporating it outputs into Kubernetes CRDs (Custom Resource Definitions) and from there, making security reports accessible through the Kubernetes API. This way users can find and view the risks that relate to different resources in what we call a Kubernetes-native way.

src: https://github.com/aquasecurity/trivy-operator

## Proposed user journey

Implement in a test cluster and demo.

## Definition of done

- [x] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by prakash-moj** [comment]
Trivy operator already implemented

https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf#L243-262


User guide updated here - https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/trivy-image-scanning.html
