### ISSUE TITLE
Decide on new cluster name

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4095]
## Background

Naming things is hard.

We need to decide on a name for the cluster. We have an ADR for [naming clusters](https://github.com/ministryofjustice/cloud-platform/blob/main/architecture-decision-record/009-Naming-convention-for-clusters.md) but it's possible that this approach has been superseded.

There is a principle in the ADR:

> To make this easier we propose having a naming scheme that makes it easy to understand whether users are on that cluster but makes no other assumptions about what it is used for.

That still stands.

Someone needs to own the discussion. Remember the naming can be changed at any time and we'll continue to review how we name clusters. 

## Approach

Lock ourselves in a room until we agree on a name, or better still start a thread in the team channel for discussion.

## Definition of done

- [ ] We agree on a name for the new cluster
- [ ] If applicable we'll need a new ADR. If we need one create a story for a new ADR.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
live-2

https://mojdt.slack.com/archives/C514ETYJX/p1663751152489139?thread_ts=1663688739.419169&cid=C514ETYJX
