### ISSUE TITLE
Set-up alerts for new cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4098]
## Background

Set-up alerts for new cluster. These will be similar to alerts for `Live`

## Approach

Set-up alerts for new cluster. We should use what we use for `Live`

## Definition of done

- [ ] Alerting is set up and tested so that we know alerts will be raised in the normal channels.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
[Alerts comparison "live-2" to "manager"(https://docs.google.com/spreadsheets/d/1SnRJtme_QuDxW7j13tUprgBS-3Q7TbYS/edit#gid=561344450)

**Comment by pwyborn** [comment]
Alerts already triggered:

- Low Priority

[ErrorsInExternalDNS](https://mojdt.slack.com/archives/C8QR5FQRX/p1664488064250939)
[VeleroBackupPartialFailure](https://mojdt.slack.com/archives/C8QR5FQRX/p1663945379681449)
[VeleroBackupPartialFailure-velero-allnamespacebackup](https://mojdt.slack.com/archives/C8QR5FQRX/p1663956479947889)
[VeleroBackupNotSuccessfulForOverFourHours-velero-allnamespacebackup](https://mojdt.slack.com/archives/C8QR5FQRX/p1663997099674039)

**Comment by pwyborn** [comment]
Alerts present and correct
