### ISSUE TITLE
User support requests redirected to github from JIRA

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform#41]
@lukaszraczylo to create a github template instead of the google form

https://gist.github.com/bmcbride/62600e48274961819084

details above on how to direct our google form user support request into our github board

issues to be automatically created in the cloud platform board (support to do column)

**Comment by lukaszraczylo** [comment]
I have created separate issue template - https://github.com/ministryofjustice/cloud-platform/pull/46

**Comment by tatyree** [comment]
Sorry @kcbotsh accidentally removed the label.   

You need help outline the next steps?  Getting the email redirected from JIRA to github?  Documenting the new process?
