### ISSUE TITLE
Who is using postcodeinfo?

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#410]
## Service name

Postcodeinfo

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

No impact. This is a ticket to work out who is using postcodeinfo

## Problem description

We are looking at decommissioning the postcodeinfo service and need to work out who is using it so that we can engagement them and form a plan for next steps.

## Contact person

 
Contact: Tony Bishop

**Comment by pwyborn** [comment]
https://docs.google.com/spreadsheets/d/1NJrgCp1xXR4Er4kJwiGRjHbiqX5fD6Kc_y_iBHeomlY/edit#gid=0 list of potential users and contact details - from postcode django admin api

**Comment by pwyborn** [comment]
Done
