### ISSUE TITLE
Ensure the new cluster can write to the service.justice... hosted zone

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4100]
## Background

Ensure the new cluster can write to the service.justice... hosted zone

## Approach

TBC

## Definition of done

- [ ] We have verified that the new cluster can write to the service.justice hosted zone

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Need to have this for new cluster similar to the manager 

https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf#L102-L107

Also, set this to true for new cluster:
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf#L82-L87
