### ISSUE TITLE
Build a production standard cluster for non-production workload

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4101]
## Background

Build a production standard cluster for non-production workload.

## Definition of done

- [x] New cluster built

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
This is completed now, live-2 is up and running.

Separate tickets to be created for cert-manager, ingress-controller, external-dns
