### ISSUE TITLE
Which config needs to span both clusters? 

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4102]
## Background

Which config needs to span both clusters? e.g. Slack Webhooks, OPA rules. 

This story is to figure stuff out. This story will document the finding and then enable us to create further stories to fix things.

## Definition of done

- [ ] We understand which config needs to span both clusters and we are able to create stories for next steps.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
During the cluster creation process, the following items are figured out that it needs to be spans across both clusters

- Force external-dns to create hosts under *.cloud-platform.service. This is already available in live and manager. So  need to add to live-2
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/blob/b2cc59323afe1772817e8acab88368277fbe5bf7/main.tf#L6  

- certmanager to be able to solve ACME challenges on all zone. https://github.com/ministryofjustice/cloud-platform-terraform-certmanager

- external-dns to be able to add records to all domains in all hostzone of the cp account. https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/blob/70cbbd6c8af90e8a7bd4e33926961df0a40f73ec/main.tf#L2-L6

- Disabled invalid hostname OPA policy to check if hostnames other than under the cluster domain name can be created. DONE

- Alertmanager slack webhooks used in live has been applied to live-2 - DONE
