### ISSUE TITLE
Create the same blackbox (pingdom?) alerts as live and manager

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4107]
## Background

Create same pingdom alerts as we have for the live cluster.

## Definition of done

- [ ] Pingdom alerts created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
![Screenshot 2022-09-26 at 17.24.46.png](https://images.zenhubusercontent.com/5cd14e5c7c13c23a96974cd6/9f1ae6a2-2f04-40eb-95b3-6fe49b4f8ca7)
