### ISSUE TITLE
Create divergence pipeline for new cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4108]
## Background

Create divergence pipeline for new cluster

## Definition of done

- [x] Divergence pipeline created.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
`divergence-live-2` pipeline PR here for ref:
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/155
