### ISSUE TITLE
Create CI/CD pipeline to ensure all changes to main are applied to the new cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4109]
## Background

Create CI/CD pipeline to ensure all changes to main are applied to the new cluster

## Definition of done

- [ ] Pipeline created.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Created environments pipeline for live-1

This is for plan, apply and apply namespace pipeline
