### ISSUE TITLE
Change the ECR user auth

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#411]
BACKGROUND: 
One of the Cloud-Platform users has pointed out an issue with the creation of an ECR user account per repository (01/10):
`AlD [11:49]
morning all. I have a question on the ECR terraform module (https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials) - our system consists of a growing number of containers (5 so far, 2 more coming soon, maybe more later). If I’m reading the TF code correctly, the module will create a distinct user with new credentials for each one (so 7 sets of credentials to manage in our case). Is that right? Is there a way to use the same credentials across a set of repos?`

This is a very good point. If you split your application into micro-services you may have to handle multiple user-accounts. This is less than ideal. Should we have an ecr-user created per repository that has access to project/*.

PROPOSED USER JOURNEY:
As a user I need to provision ECR for a user at team level so I only need to manage one set of credentials for multiple images.

APPROACH:

**We can test with Al Davidson who has identified this user need.**

WHICH PART OF THE USER DOCS DOES THIS IMPACT:

This will require a new section in the user guide in line with other Terraform Modules. **However, note that there is another story in this sprint (#insert ref) to revisit where we keep guidance for Terraform Modules. You may want to hold off on documents until that work is completed.** 

QUESTIONS/ASSUMPTIONS:

DEFINITION OF DONE:
- [ ] Module created
- [ ] Test with user
- [ ] There is a new repo for the module called with a sensible name in line with our naming conventions.
- [ ] Any tags applied according to the tag guidance
- [ ] Add the readme like in the S3 bucket module
- [ ] Updated user guide

**Comment by razvan-moj** [comment]
Fixed in release 2 https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials/releases
