### ISSUE TITLE
Ensure all user Terraform modules used in environments module are cluster agnostic

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4111]
## Background

Ensure all user Terraform modules are cluster agnostic i.e. they don't expect live or manager

## Definition of done

- [ ] Modules don't expect live or manager

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Except for ES, all modules are cluster agnostic.
ES will need aws provider 4, we can pick that once that is done
