### ISSUE TITLE
live-2 certmanager to be able to solve ACME challenges on all zone

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4118]
## Background

live-2 cluster will host apps all hostzone managed under CP account. Hence the cert-manager has to resolve hosts and create certificatesof those hostzone. Add configuration to manage this for live-2.

## Proposed user journey

Add live-2 in this list below:
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf#L111-L122

https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf#L48

## Questions / Assumptions

Will there be a conflict if same hostname is resolved from both the clusters?

## Definition of done

- [ ] Hostnames able to resolve ACME challenge and create certificates for all hostzones in live-2
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Stale. We are also decommission Live-2. Revisit if/when we get to multi-cluster
