### ISSUE TITLE
Ingress Controller memory leaks investigation

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4119]
## Background

It appears that there was a bug that resulted in a slow memory leak in our Modsec ingress. As usage has increased the leak became more apparent.

2 weeks ago we capped its RAM to prevent it killing the node entirely, but it seems users monitor very carefully any connection reset. So the 4 gigs we set to first were too noisy. This has been double as a workaround.

We want to spend more time to investigate a fix for this issue.

## Definition of done

- [ ] We have an understanding of the root cause and potential fix.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
Upstream tracked in https://github.com/kubernetes/ingress-nginx/issues/8166

**Comment by razvan-moj** [comment]
Because https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.4.0 deprecates support for 1.21, and linked to https://github.com/ministryofjustice/cloud-platform/issues/4128 - should we use controller v1.4 on live-2?

**Comment by AntonyBishop** [comment]
Fixed by #4132
