### ISSUE TITLE
Update external-dns to resolve hosts for all zones

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4120]
## Background

Update external-dns to resolve hosts for all zones. Also cert-manager as they are tightly coupled.

## Approach

TBC

## Definition of done

- [ ] External DNS can resolve host for all zones.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
done in https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/pull/28 and https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1897
