### ISSUE TITLE
Remove old ingress controllers in live-2

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4124]
## Background

Remove old ingress controllers in live-2. There is no need to support deprecated ingress versions on the new cluster.

## Definition of done

- [ ] Only latest ingress controller versions available on Live-2

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Removing old ingress in just live-2 need multiple changes
1) Update old ingress controller used version needs to be updated to remove namespace creation and default certificate in it and create a new tag version and use the new tag version for old ingress controller
"github.com/ministryofjustice/cloud-platform-terraform-ingress-controller?ref=0.3.5"

2) Update the new ingress controller module version to have namespace creation and default certificate creation in it
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/compare/main...remove-old-ic

3) To have the old ingress controller just removed in the new live-2 cluster, we need to write multiple conditions apply old ingress controller module only on "live" cluster

Considering all these changes, team decided to do these changes both for live and live-2 together

**Comment by vijay-veeranki** [comment]
This change is tested in test cluster
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/compare/main...remove-old-ic

We noticed that applying this will delete the ingress controller namespace and apply it again, which causes downtime.

So while applying it, we need to remove terraform state related to namespace creation from the old module and terraform import kubernetes_namespace from the new module, same with default certificate.

**Comment by vijay-veeranki** [comment]
completed
