### ISSUE TITLE
Create new OS (Open search) cluster for Live-2 Beta

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4125]
## Background

We now have live-2 beta close to completion. We require a way to aggregate logs for users to search and identify indices relating to their namespace.

We already have this in live, but the team has decided it would be best to aggregate away from live/production.

## Definition of done

We have a place to store log files in an aggregated way.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Created OS using template
