### ISSUE TITLE
SPIKE - OPA policy running on multiple clusters

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4127]
## Background

We're not entirely sure of the behaviour of OPA running on multiple clusters. This is a spike to investigate and see if there are any issue in trying to do this. 

Depending on the findings we'll create new stories to address any issues, or implement OPA.

## Questions / Assumptions

What's going to break?

## Definition of done

- [ ] Confirmed behaviour of OPA running on multiple clusters
- [ ] Stories for next steps have been created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Started a thread in OPA slack channel to see if it is possible to access multiple clusters

https://openpolicyagent.slack.com/archives/CDTN970AX/p1665480032801789

**Comment by vijay-veeranki** [comment]
Reply in OPA slack channel:

You can feed OPA with whatever data it needs, via bundles or the REST API. You’d probably want to have a service running on the outside that fetched this data from across your clusters and then would have your OPAs pull bundles produced by that service.

You could probably have something simple like a cron job periodically querying each cluster for the data you need, and then just package the data into a bundle, and push to S3 or what have you

**Comment by vijay-veeranki** [comment]
OPA policy cannot run on multiple clusters, instead, we need to look at the below options if we need to implement policy to look at data for both the clusters

1) cron job periodically querying each cluster for the ingress host data, and then just package the data into a bundle, and push to S3. And then would have OPAs pull data from the s3 to get existing hostnames and block them if they already exist.
2) We could get data from https://reports.cloud-platform.service.justice.gov.uk/hosted_services and use OPA to query the data before creating the ingress
3) As suggested by @razvan-moj , we can have some sort of alert set up if we have same host name in here
https://reports.cloud-platform.service.justice.gov.uk/hosted_services
