### ISSUE TITLE
Create Beta test documentation

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4129]
## Background

This story is for creating user docs for beta. Docs need to cover the following:

- Details of what we want users to test
- How to build an environment on Live-2
- Details of how to authenticate to Live-2
- How to switch context
- Reminder to not reuse resources from Live

## Questions / Assumptions

- What is the scope of the Beta? What do we want users to do?

## Definition of done

- [x] We have documentation ready for Beta testers

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Beta documentation: https://docs.google.com/document/d/1Zr38G84mqeJX2CqljT3ih5XeG5q9l7FvatSJ_P_Srrw/edit?usp=sharing

**Comment by poornima-krishnasamy** [comment]
Beta testing will be done after the rebuild of live-2 with the new ip ranges.

**Comment by poornima-krishnasamy** [comment]
Rebuild of live-2 completed.
Final doc for beta testing: https://docs.google.com/document/d/1Zr38G84mqeJX2CqljT3ih5XeG5q9l7FvatSJ_P_Srrw/edit?usp=sharing
