### ISSUE TITLE
Moving People Safely - add IP addresses for Kent & Essex police forces

### ISSUE THREAD

**Issue by pazinlondon** [ministryofjustice/cloud-platform#413]
## Service name
Moving People Safely

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Delay in rollout by preventing us testing the live service in these 2 areas

## Problem description

We need to add the following 2 IP addresses to our IP whitelist on production. The IP details in the document below
https://docs.google.com/document/d/1gvxodKty-5mYdm1wlSxAk40iNzF4aPw2GuU4xvUTCfs/edit

## Contact person
Paul Smith, @psmiddy, paul.smith@digital.justice.gov.uk

**Comment by pwyborn** [comment]
paulwyborn [6 hours ago]
@psmiddy - Hi Paul Ips added - can someone please check that they are able to connect please?

**Comment by pwyborn** [comment]
Done/complete - awaiting user confirmation

**Comment by pwyborn** [comment]
psmiddy [12:16 AM] 03/10/2018
Cheers Paul. Unfortunately they have a network issue preventi g any access to the Amazon cloud at the moment but will get them to test as soon as that's sorted


paulwyborn [9:29 AM] 05/10/2018
Sorry Paul - was off Wednesday/Thursday - ok thanks - let me know when they have tested please?

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/moving-people-safely-deploy/pull/74
