### ISSUE TITLE
upgrade ingress to newest available release

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#4132]
## Background

We have a memory leak (https://github.com/kubernetes/ingress-nginx/issues/8166) that is hard to debug. Two new releases are available, 1.3 and 1.4
 - 1.3 is the safest choice, should be easy to install, only concern is to make sure it doesn't attempt to recreate the Load Balancers
 - 1.4 docs say upstream has deprecated K8s 1.21 (https://github.com/kubernetes/ingress-nginx/releases); test that assertion, suggest further path

## Approach

Change in https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/blob/main/main.tf#L45
 
## Definition of done

- [ ] new release in live
- [ ] another team member has reviewed
- [ ] smoke tests are green

**Comment by AntonyBishop** [comment]
Superseded
