### ISSUE TITLE
Create OPA policy to restrict live-2 users to use old ingress controllers

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4136]
## Background

Currently, live-2 have both old and new ingress controllers, we want to restrict users from using old ingress-controllers in live-2

Create an OPA policy to restrict users from using ingress class as "nginx" and "modsec01"

## Proposed user journey

OPA policy should check for below

```
spec:
  ingressClassName: <is not nginx or modsec>
```

Also ingress class annotation is not used

`kubernetes.io/ingress.class: "nginx"`

## Approach

This OPA policy should restrict users to create ingress using old ingress class

## Definition of done

- [ ] OPA policy created
- [ ] OPA test updated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
No longer required
