### ISSUE TITLE
Review process and runbook: Manually Delete Namespace Resources 

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4141]
## Background

We should rewrite the current ruby script into a cli command.

We should then update the runbook to align to the new process.

Runbook - https://github.com/ministryofjustice/cloud-platform-environments/blob/main/bin/delete-namespace.rb

## Definition of done

- [ ] Manual delete now a CLI commande
- [ ] runbook process has been tested/followed
- [ ] Runbook updated
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
The cli command to delete namespace is Done as of 29 Jan 2024.
