### ISSUE TITLE
Implement Sysdig Falco

### ISSUE THREAD

**Issue by sid234** [ministryofjustice/cloud-platform#415]
*Background*
We need a tool that performs live monitoring of the behavior of the Docker containers and Kubernetes pods at runtime

*Description*
Using Falco, we can create a Docker runtime security policy to detect attacks and anomalous activity on production environments, in real-time, so we can react to unknown and 0-day vulnerabilities, attacks caused by weak or leaked credentials or compliance breaches
https://sysdig.com/blog/docker-runtime-security/

*Approach*
Implement the tool in the Test Cluster 
https://github.com/draios/falco
https://github.com/draios/falco-extras

*Definition of Done*
- Check if the tool needs to run as root privilege in the container
- What would be the disadvantages of running this tool
- Check if we can detect things like:
A shell is run inside a container
A container is running in privileged mode, or is mounting a sensitive path like /proc from the host.
A server process spawns a child process of an unexpected type
Unexpected read of a sensitive file (like /etc/shadow)
A non-device file is written to /dev
A standard system binary (like ls) makes an outbound network connection

**Comment by jasonBirchall** [comment]
+1 for this

**Comment by AntonyBishop** [comment]
Felt that this tool requires too much privilege. If there is value in doing this we would look at an alternative.
