### ISSUE TITLE
Update rbac files in environments repo to use rbac.authorization.k8s.io/v1

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4154]
Update environments repo rbac files to use rbac.authorization.k8s.io/v1

Update environments repo to use rbac.authorization.k8s.io/v1 is depreciated in 1.22

We have many users still using this rbac.authorization.k8s.io/v1beta1, update all of them to rbac.authorization.k8s.io/v1

Example:

`
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: activities-api-dev
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: activities-api-dev
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: activities-api-dev
rules:
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - "prometheusrules"
    verbs:
      - "*"

`

**Comment by jasonBirchall** [comment]
All RBAC resources upgraded.
