### ISSUE TITLE
New alert route in Alert Manager for hmpps-approved-premises-api

### ISSUE THREAD

**Issue by brownbearsoftware** [ministryofjustice/cloud-platform#4156]
## Service name

HMPPS Approved Premises API

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Problem description

Please could you setup a new alert route in Alert Manager:
- Namespace: hmpps-approved-premises-dev
- Team Name: HMPPS Approved Premises team
- Application Name: hmpps-approved-premises-api
- Slack Channel: approved-premises-team-events
- Kubernetes Secret: slack-web-hook -> url
- Severity Level: warning

## Contact person

Joseph Hollinshead on slack or joseph.hollinshead@digital.justice.gov.uk

**Comment by vijay-veeranki** [comment]
severity = "hmpps-approved-premises"
