### ISSUE TITLE
Add additional ciphers to ingress new ingress controllers

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4159]
## Background

Some teams reported issues with ingress controller switches as a result of downstream users on tech that supports older ciphers. We've reviewed what these users are using and have identified some ciphers that it is appropriate to add.

This will enable switch to new controllers to continue.

Add additional ciphers to ingress new ingress controllers:

```
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
```

## Definition of done

- [ ] Additional support for ciphers added.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Added below for v1 ingress controllers

`ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA" 
`


https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/blob/main/templates/values.yaml.tpl#L78
