### ISSUE TITLE
Prototype Ingress Switches

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4162]
## Background

We've agreed to implement switches for Prototypes. Story is to switch all remaining prototypes to the new ingress controller and replace with v1 APIs.

## Approach

**List of namespaces in scope:**
hmpps-prisoner-education
hmpps-prepare-a-case-prototype
apply-for-compensation-prototype
apply-for-compensation-prototype-dev
apply-for-legal-aid-prototype
book-a-prison-visit-prototype
laa-crime-apply-prototype
hmpps-manage-supervisions-prototype
laa-view-court-data-prototype
jason-design-demo
hmpps-licenses-prototype
hmpps-interventions-prototype
makerecall-prototype
hmpps-incentives-tool
manage-supervisions-design-history
opg-lpa-fd-prototype
opg-sirius-prototypes
hmpps-assess-risks-and-needs-prototypes
cloud-platform-prototype-demo
cloud-platform-prototype-demo
cloud-platform-prototype-demo
cloud-platform-prototype-demo
cloud-platform-prototype-demo
interventions-design-history
send-legal-mail-prototype
request-info-from-moj
dex-ia-proto
eligibility-estimate

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

TBC

## Definition of done

- [ ] Prototypes are all running on the new ingress controllers.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
List of prototypes - https://docs.google.com/spreadsheets/d/1Pmbn7LjhOa_AgJ435NfpN9pBi8xD-DUI_2S6uGCPVcA/edit?usp=sharing

**Comment by jasonBirchall** [comment]
All prototypes were upgraded.
