### ISSUE TITLE
New alert routes for create-and-vary-a-licence non production

### ISSUE THREAD

**Issue by andrewrlee** [ministryofjustice/cloud-platform#4164]
## Service name

Create and vary a licence

## Service environment

- [x] Dev / Development
- [x] Preprod
- [x] Prod / Production
- [ ] Other

## Impact on the service

We need a new alert route for CVL

namespaces:
* create-and-vary-a-licence-dev
* create-and-vary-a-licence-api-dev
* create-and-vary-a-licence-preprod
* create-and-vary-a-licence-api-preprod
* create-and-vary-a-licence-prod
* create-and-vary-a-licence-api-prod
 
team name: the elephants
application name: create and vary a licence
slack channels: 
* cvl_alerts_non_prod
* cvl_alerts

kubernetes secret name where the webhook url is stored: please contact me directly

## Contact person
`@Andrew Lee`

**Comment by vijay-veeranki** [comment]
severity = "cvl-alerts-non-prod"
    channel  = "#cvl_alerts_non_prod"

    severity = "cvl-alerts"
    channel  = "#cvl_alerts"
