### ISSUE TITLE
Template the terraform files when using in CLI

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4167]
## Background

The cloud-platform cli creates ecr, s3 and serviceaccount terraform files as part of `cloud-platform environment <resource> create command. But when there is a new terraform module release,  the release number in the /template file or /example file needed amending in its module to get the latest module to be used by cli

## Proposed user journey
CLI doesnot get the latest version when uses generate the terraform files using the command

## Approach

- Template the release number in the /template file and when running the command
- Either fetch the latest release from the module in git and amend the local copy OR 
- Maintain the latest semver tag in HOODAW and publish the tags. Then, fetch the latest tag from the HOODAW page to fill in the template

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/cloud-platform-cli.html

## Questions / Assumptions

Assume, the users can access git when running the command.

## Definition of done

- [ ] CLI always fetches the latest terraform module release
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by Matt-Alinosn** [comment]
Linked to the following ticket - https://github.com/ministryofjustice/cloud-platform/issues/4830
