### ISSUE TITLE
Prometheus Upgrade

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4172]
## Background

Upgrade Prometheus to latest version.

## Questions / Assumptions

- We should probably send some comms to tell users we are upgrading.
- Will there be downtime?
- Are there any new features that users will benefit from?

## Definition of done

- [ ] Prometheus upgraded and working as expected.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
![Screenshot 2022-11-01 at 10.05.02.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/cb102762-125f-48c0-bac1-a0c79c98bec2)

**Comment by pwyborn** [comment]
prometheus-operator
chart: kube-prometheus-stack
namespace: monitoring
installed: 30.0.1
latest: 36.6.2

**Comment by pwyborn** [comment]
prometheus-blackbox-exporter
chart: prometheus-blackbox-exporter
namespace: dso-monitoring-prod
installed: 4.11.0
latest: 7.1.3

**Comment by pwyborn** [comment]
See https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/4084

**Comment by pwyborn** [comment]
- Will there be downtime?

If we are talking prometheus-operator here - very small down time whilst daemonset being deleted and recreated (less than 4 minutes on test cluster)

- We should probably send some comms to tell users we are upgrading.
Yes we can do that

- Are there any new features that users will benefit from?
Will check
