### ISSUE TITLE
Review all cloud-platform used helm charts for use of deprecated API versions

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4175]
## Background

Review all cloud-platform used helm charts for use of deprecated API versions. We can use the [list](https://docs.google.com/spreadsheets/d/1LUzlfRpIa3G7ok83lx3b8vtwqkuPc6zVRgxFAS6PPyg/edit?usp=sharing) to identify which charts are impacted.

This is just CP Team used helm charts.

This story is just to identify the charts. Add details to #4176 for charts that need to be updated.

## Definition of done

- [ ] We understand which helm charts need to be updated,

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
[https://app.zenhub.com/files/126507503/3fbc0184-c1a6-43d0-9c35-653073d15dc6/download](https://app.zenhub.com/files/126507503/3fbc0184-c1a6-43d0-9c35-653073d15dc6/download)

This needs to be looked at

ClusterRole                    <undefined>                                       eventrouter                                       rbac.authorization.k8s.io/v1beta1      rbac.authorization.k8s.io/v1 (1.8.0)
ClusterRoleBinding             <undefined>                                       eventrouter                                       rbac.authorization.k8s.io/v1beta1      rbac.authorization.k8s.io/v1 (1.8.0)

**Comment by vijay-veeranki** [comment]
event router is updated in the helm chart, maybe it need a new release and get it applied
https://github.com/ministryofjustice/cloud-platform-helm-charts/blob/main/eventrouter/templates/clusterrole.yaml
