### ISSUE TITLE
Test AWS EKS upgrade process

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4180]
## Background

Upgrade the test cluster using the standard recommended AWS EKS process. We are looking for issues we have experience during previous upgrades. Can we replicate those issues? If issue occur, how do we fix them?

## Definition of done

- [ ] AWS EKS upgrade followed
- [ ] Document and issues and resolutions

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1dd8WkQIA3c4M5TqNPo2ASL9cTyXhuti6iAGbhRLhb9s/edit#
