### ISSUE TITLE
Create Terraform module for Secrets Store / ASCP CSI Driver

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4182]
## Background

A Terraform module for deploying both [Kubernetes Secret Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/) and associated [AWS Provider (ASCP) ](https://github.com/aws/secrets-store-csi-driver-provider-aws) in order to enable Cloud Platform cluster access to AWS Secrets Manager.

## Questions / Assumptions

Enable CSI driver as part of cluster build components level (as per existing EFS / EBS CSI driver modules)

Decisions / designs to be considered for enabling CP users to create and access Secrets Manager secrets.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Done. Old Ticket
