### ISSUE TITLE
Design process for Cloud Platform user access to AWS Secrets Manager

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4183]
## Background

Following creation of [Secrets Store CSI Driver module](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/4182), design and test a process for enabling Cloud Platform users to create and consume AWS Secrets Manager secrets in their namespaces & workloads.

## Proposed user journey

A user wishing to leverage AWS Secrets Manager has the ability to define necessary resources for their namespace and have necessary permissions to create/read secrets.

## Approach

Purpose of story is to figure out approach.

## Which part of the user docs does this impact

TBD

## Questions / Assumptions

How can AWS Secrets Manager secret access be locked down per user/team? Secret storage is based on flat hierarchy, can we lock down access using a path pattern ie `CP-user/my-namespace/-?????`

Relates to icebox issue:

https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/3423

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Done. Old Ticket
