### ISSUE TITLE
Rebuild Live-2 cluster

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4196]
## Background

We want to rebuild the `Live-2` cluster. This will test our destroy and rebuild process.

We will also rebuild `Live-2` with a new VPC with new IP ranges as per story #3454.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- Should the new cluster be called `Live-3`?

## Definition of done

- [ ] Tested destroy cluster process
- [ ] Tested cluster rebuild process
- [ ] New cluster has a new VPC with new IP ranges

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
VPC to be created in the IP range mentioned here: https://mojdt.slack.com/archives/C514ETYJX/p1666952433214819?thread_ts=1665581872.894299&cid=C514ETYJX

**Comment by poornima-krishnasamy** [comment]
Rebuild process through velero to recover lost resources. https://runbooks.cloud-platform.service.justice.gov.uk/disaster-recovery-scenarios.html#losing-the-whole-cluster

**Comment by poornima-krishnasamy** [comment]
Check for changes/impact on terraform modules whether they use any hardcoded default IP ranges
