### ISSUE TITLE
AlertManager route for interventions-prod-alert

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#4200]
## Service name

Refer and monitor an intervention (HMPPS)

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We'd like to route high profile alerts to the stakeholder team channel so that it's more widely known and visible

## Problem description

Information [requested](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#create-a-slack-webhook-and-amend-alertmanager):

**namespace name**: `hmpps-interventions-prod`
**team name**: HMPPS interventions
**application name**: `hmpps-interventions-ui` and `hmpps-interventions-api`
**slack channel**: `#interventions`
**kubernetes secret name where the webhook url is stored**: same webhook as for [the existing severity](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-interventions-prod/10-alerts.yaml#L20), but going to a different channel, if that is possible
**severity level (warning/information)**: warning

Could this have `severity: hmpps-interventions-prod-alert`, please?

## Contact person

`@David Lantos` on Slack

**Comment by vijay-veeranki** [comment]
@David Lantos Added the alert with severity: hmpps-interventions-prod-alert
