### ISSUE TITLE
Create a dry-run procedure to delete old ingress with out any downtime

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4201]
## Background

This change is tested in a test cluster
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/compare/main...remove-old-ic

We noticed that applying this will delete the ingress controller namespace and apply it again, which causes downtime.

So while applying it, we need to remove terraform state related to namespace creation from the old module and terraform import kubernetes_namespace using the new module, same with default certificate.

## Proposed user journey

Create a procedure to apply this change without any downtime, and do a dry-run to delete the old ingress without any downtime.

## Approach

So while applying it, we need to remove terraform state related to namespace creation from the old module and terraform import kubernetes_namespace using the new module, same with default certificate.

## Definition of done

- [x] procedure works with no downtime
- [x] another team member has reviewed
- [x] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1940
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/pull/51
