### ISSUE TITLE
Clarification around cluster name env_var

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4209]
## Background

User feedback on user guide (from @ willclarke):

On this page:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/using-circleci-for-continuous-deployment.html#setting-up-circleci

It refers to the cluster name to be used for the env_var is : https://DF366E49809688A3B16EEC29707D8C09.gr7.eu-west-2.eks.amazonaws.com

However it seems that if I enter that the actual env_var that is passed through is https://https/https://DF366E49809688A3B16EEC29707D8C09.gr7.eu-west-2.eks.amazonaws.com

Note the repeated https.

Suggest that the user guide makes it clear that the env var should not include the https:// at the beginning

## Approach

Review feedback. Is this bug? Update guide accordingly and fix if this is an error.

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/using-circleci-for-continuous-deployment.html#setting-up-circleci

## Definition of done

- [x] User guide updated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Updated guide:
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/1292/files
