### ISSUE TITLE
Terraform Module for AWS Cloudfront

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4224]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jakemulley** [comment]
I've started making some progress for this in [@ministryofjustice/cloud-platform-terraform-cloudfront](https://github.com/ministryofjustice/cloud-platform-terraform-cloudfront).

However, to use the recommended [Origin Access Control](https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-cloudfront-introduces-origin-access-control-oac/), we need to support Terraform provider 4.x.x (as it wasn't backported to 3.x.x) so this is blocked for now.

**Comment by AntonyBishop** [comment]
Done
