### ISSUE TITLE
Requesting Pingdom<->Slack integration IDs for laa-estimate-financial-eligibility-for-legal-aid

### ISSUE THREAD

**Issue by patrick-laa** [ministryofjustice/cloud-platform#4228]
## Service name
Estimate financial eligibility for legal aid (soon to be renamed to 'Check if your client qualifies for legal aid')

## Service environment

- [X] Staging
- [X] Prod / Production
- [X] Other (=UAT)

## Impact on the service

We are hoping to launch this service in private Beta in early December, and in preparation for this we want adequate monitoring of our environments.

## Problem description

We are setting up Pingdom monitoring of our environments and would like to be notified by Slack of any downtime. As per the [documentation](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#adding-slack-notification) in the user guide, I'd like to request 3 integration IDs for our UAT, staging and production environment.

The team name is 'Eligibility' or 'EFE'. The application name is 'Check if your client qualifies for legal aid'. The three Slack channels we would like to use are #eligibility-alerts-uat, #eligibility-alerts-staging and #eligibility-alerts-production.

## Contact person

Patrick Gleeson ([patrick.gleeson@digital.justice.gov.uk](mailto:patrick.gleeson@digital.justice.gov.uk), `@Patrick Gleeson` on Slack)

**Comment by patrick-laa** [comment]
PR for initial Pingdom setup (minus the integration IDs) at https://github.com/ministryofjustice/cloud-platform-environments/pull/9299

**Comment by patrick-laa** [comment]
PRs for Pingdom integration:
https://github.com/ministryofjustice/cloud-platform-environments/pull/9301
https://github.com/ministryofjustice/cloud-platform-environments/pull/9300
https://github.com/ministryofjustice/cloud-platform-environments/pull/9299

**Comment by poornima-krishnasamy** [comment]
Hi @patrick-laa , Please find the integration ID for the Pingdom checks
#eligibility-alerts-uat - 125950
#eligibility-alerts-staging - 125951
#eligibility-alerts-production - 125952

**Comment by patrick-laa** [comment]
Thank you!
