### ISSUE TITLE
Prepare for Kubernetes 1.23 upgrade

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4232]
## Background

We want to start planning for the 1.23 upgrade. This story is to verify if there are any breaking changes that may require our users or our team to do anything.

Check on aws addons current version is compatible with v1.23 and test upgrading to suggested version

Based on finding will lead to next set of stories.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- Are there any breaking changes?
- Do we need to update any other components?
- Do our users need to do anything in support of changes
- Test the upgrade in a test cluster to identify any issues

## Definition of done

- [ ] Feedback to team so we can determine next steps for upgrade

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1l_2Um_B9FL_CEczwwdi0mG1TOGir11NE94mK45ZfSAE/edit#

**Comment by pwyborn** [comment]
Hi @vijay-veeranki - just for info re https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/4239 ![Screenshot 2022-12-06 at 10.12.35.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/de7a7afa-4465-4b4f-9671-839192217f89)
