### ISSUE TITLE
Preparation for Gatekeeper

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4235]
## Background

We want to adopt Gatekeeper

Before we do this we need to research what's involved, what breaks etc so that we can plan the move to Gatekeeper

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- Are there any breaking changes?
- Do we need to update any other components?
- Do our users need to do anything in support of changes
- Test the upgrade in a test cluster to identify any issues

## Definition of done

- [x] Feedback to team so we can determine next steps for Gatekeeper

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Tested:
- updating module to use latest Gatekeeper Helm chart release (3.10)
- deploying gatekeeper on test cluster alongside OPA
- applying unique policies(constraints) to Gatekeeper and prove admission control works alongside OPA
- applying equivalent policy/constraint in both OPA and Gatekeeper (ingress clash) and demonstrate ability to switch control over from OPA to Gatekeeper gradually (turning off OPA policy immediately hands control over to Gatekeeper)
- Demo'd above to team

TO DO:

- Follow up ticket to enhance `cloud-platform-terraform-gatekeeper` module.
-
