### ISSUE TITLE
Ingress Controller Upgrade

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4239]
## Background

We want to start planning for the next ingress controller upgrade. This story is to verify if there are any breaking changes that may require our users or our team to do anything.

Based on finding will lead to next set of stories.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- Are there any breaking changes?
- Do we need to update any other components?
- Do our users need to do anything in support of changes
- Test the upgrade in a test cluster to identify any issues

## Definition of done

- [ ] Feedback to team so we can determine next steps for upgrade

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
Ingress-NGINX version	k8s supported version	Alpine Version	Nginx Version
v1.5.1	1.25, 1.24, 1.23	3.16.2	1.21.6
v1.4.0	1.25, 1.24, 1.23, 1.22	3.16.2	1.19.10†
v1.3.1	1.24, 1.23, 1.22, 1.21, 1.20	3.16.2	1.19.10†
v1.3.0	1.24, 1.23, 1.22, 1.21, 1.20	3.16.0	1.19.10†

**Comment by AntonyBishop** [comment]
Superseded
