### ISSUE TITLE
Upgrade cluster-autoscaler

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4240]
## Background

As we are on K8S 1.22 we need to upgrade the version of Autoscaler to the equivalent version.

This story is for carrying out the upgrade.

## Approach

TBC

## Questions / Assumptions

TBC

## Definition of done

- [ ] Version of Autoscaler updated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/README.md#releases

**Comment by poornima-krishnasamy** [comment]
There is no app-version v1.22.X to support kubernetes version 1.22. 
Issue related to this and a possible approach: https://github.com/kubernetes/autoscaler/issues/4850#issuecomment-1120399530

**Comment by poornima-krishnasamy** [comment]
Trying chart version 9.21.0 with clouster-autoscalar image version 1.22.3

**Comment by poornima-krishnasamy** [comment]
No major changes to values file https://github.com/kubernetes/autoscaler/commits/master/charts/cluster-autoscaler/values.yaml. from version 9.12.0

**Comment by poornima-krishnasamy** [comment]
For cluster-overprovisioner: https://github.com/kubernetes-sigs/cluster-proportional-autoscaler

**Comment by poornima-krishnasamy** [comment]
For using cluster-overprovisioner, https://charts.deliveryhero.io/ with `0.7.1` version is used. Need to understand how that works and the impact on upgrading to latest.
