### ISSUE TITLE
Amazon EBS CSI migration

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4241]
## Background

As part of the upgrade to 1.23 we need to [install Amazon EBS CSI Driver](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html).

FAQ - https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi-migration-faq.html

We need to assess impact of changes and plan this into the 1.23 upgrade.

## Definition of done

- [ ] We understand the impact of changes and when to plan this into the 1.23 upgrade.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
We already have ebs csi installed on the cluster
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/storage.tf#L5-L9

Will Amazon EKS make any changes to StorageClasses already present in my existing cluster when I update my cluster to version 1.23?
No

What is the default StorageClass applied in newly created Amazon EKS version 1.23 and later clusters?

The default StorageClass behavior remains unchanged. With each new cluster, Amazon EKS applies a kubernetes.io/aws-ebs based StorageClass named gp2. We don't plan to ever remove this StorageClass from newly created clusters. Though subject to change, we are currently targeting version 1.25 to remove the default annotation from the StorageClass applied to newly created clusters. Separate from the cluster default StorageClass, if you create an ebs.csi.aws.com based StorageClass without specifying a volume type, the Amazon EBS CSI driver will default to using gp3.

We already have gp3 set to default
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/storage.tf#L52-L88

**Comment by vijay-veeranki** [comment]
The CSI migration effort enables the replacement of existing in-tree storage plugins such as kubernetes.io/gce-pd or kubernetes.io/aws-ebs with a corresponding CSI driver from the storage backend. If CSI Migration is working properly, Kubernetes end users shouldn’t notice a difference. Existing StorageClass, PersistentVolume and PersistentVolumeClaim objects should continue to work. When a Kubernetes cluster administrator updates a cluster to enable CSI migration, existing workloads that utilize PVCs which are backed by in-tree storage plugins will continue to function as they always have. However, behind the scenes, Kubernetes hands control of all storage management operations (previously targeting in-tree drivers) to CSI drivers.
