### ISSUE TITLE
Add user guide to update Cronjob API with batch/v1

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4243]
Add user guide for cronjob Deprecated API for version 1.25 

Running kubent shows that cronjob API is getting depreciated and **removed** in 1.25, but it is supported to use the batch/v1.

EX:
KIND	NAMESPACE	NAME	         API_VERSION	  REPLACE_WITH (SINCE)
CronJob	kube-system	descheduler	batch/v1beta1	   batch/v1 (1.21.0)

**Comment by sj-williams** [comment]
User guide updates:

https://github.com/ministryofjustice/cloud-platform-user-guide/pull/1315/files
