### ISSUE TITLE
Add user guide to update PodDisruptionBudget API with policy/v1

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4244]
Add user guide for PodDisruptionBudget Deprecated API for version 1.25

Running kubent shows that PodDisruptionBudget API is getting depreciated in 1.25, but it is supported to use the policy/v1 

EX:
KIND       NAMESPACE  NAME                  API_VERSION    REPLACE_WITH (SINCE)
CronJob kube-system  rescheduled        policy/v1beta1    policy/v1 (1.21.0)

**Comment by sj-williams** [comment]
Updated guide:
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/1316/files
