### ISSUE TITLE
Create OPA policy to block ingress created with long host name

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4245]
We are getting alerted by alert-manger as it is errored to update the record.

Error: DomainLabelTooLong (Domain label is too long)
https://mojdt.slack.com/archives/C8QR5FQRX/p1669370094988609

Identify the length accepted by external-dns/route53 

Create an OPA policy to not let users create more than certain characters.

This rejection is from route53 when external-dns is trying to create a long record in the zone.

**Comment by sj-williams** [comment]
Policy created & OPA module release published as per PR:
https://github.com/ministryofjustice/cloud-platform-terraform-opa/commit/58f5153b9bd0ff61ea93a1978d2f9066c9bd704e

Upgraded OPA in `manager` `live-2` and `live` clusters
