### ISSUE TITLE
Weekly Kops update

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#426]
## Background

We want to ensure Kops is updated regularly. 

## Approach

Update Kops

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

1. Assumes there is an update to do.
2. Is there a best day of the week to do the update?

## Definition of done

- [ ] Kops updated
- [ ] Comment added to ticket to confirm update taken place

**Don't close this ticket**

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
What are we talking about here:
- Perform a kops update (i.e. update the version of kubernetes)??
- update the version of kops on your machine??

**Comment by pwyborn** [comment]
17/10/2018
mitch [12:45 PM]
this is for a `kops update` not an `upgrade` - it essentially updates various components / configuration coming from `kops` but not the actual kubernetes version

there’s no intention to automate any of it, we just do it manually for now
also, if you run `kops update`, it will tell you wether there’s a new supported version of kube out (edited)

paulwyborn [12:47 PM]
ok thanks Mitch for the clarification

**Comment by pwyborn** [comment]
Kops update carried out on live-0 by Jasonb at 13:55 - completely successful

I had previously carried one on test-2 - that consisted of:
Kops update
Kops update --yes
rolling-update
rolling-update --yes

This was less successful - as all the monitoring links no longer work
Trying to figure out what is actually down 
Still getting alerts in chaos slack channel though!

**Comment by pwyborn** [comment]
Kops updated on live-0
Doesn't seem to be time critical (carried out at 13:55)
New ticket required to recover test-2

**Comment by pwyborn** [comment]
Ticket back to To-do for next week

**Comment by pwyborn** [comment]
Going to try a Kops update on test_1

**Comment by pwyborn** [comment]
"Kops update" successfully carried out 11:45 29/10/2018

**Comment by pwyborn** [comment]
***Conclusion
- It looks like you can run the update at any time of the day (13:55 - live-0)
- Do not run the "Kops Update"  remotely. Successfully run on live-0 and test-1 from the office. It seems that any disruption to the network can result in problems/inconsistency bringing the services back up (as per test-2).
This makes the forthcoming backup ticket all the more important

**Comment by jasonBirchall** [comment]
Done for the week commencing 12th Nov.

**Comment by vijay-veeranki-moj** [comment]
Done for the week commencing 28th-Jan-2019

Issues Identified:

A Concourse worker was stuck in Terminating for ~30 mins, had to force delete, and the process continued.

"kubectl delete -n concourse pod concourse-worker-0"

**Comment by vijay-veeranki-moj** [comment]
Done for the week commencing 11-02-2019
No rolling-update required

**Comment by vijay-veeranki-moj** [comment]
Done for the week commencing 25-02-2019
No rolling-update required

**Comment by ollieanwyll** [comment]
Done for the week commencing 18-03-2019
Updates applied to `live-0` and `live-1`

**Comment by ollieanwyll** [comment]
Done for the week commencing 25-03-2019
Updates applied to `live-0` and `live-1`

**Comment by ollieanwyll** [comment]
Done for the week commencing 15-04-2019
Updates applied to `live-0` and `live-1`

**Comment by poornima-moj** [comment]
Done for week commencing 24-06-2019
Updates applied to `live-1`
Team discussed and decided not having to apply updates for `live-0`
