### ISSUE TITLE
Cloud Platform Metrics

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4266]
## Background

We produce lots of metrics but this information tends to be in different places. Within the Hosting Service we are looking at being better at surfacing out metrics and using them as a way of showing the value of the products we build.

Most of our metrics are also manually calculated or based on data from outside the platform.

We need to build a page that will be a single page linked to our user guide where users can view our metrics.

## Approach

We would like to have a page/site where we publish our metrics.

For each metric we should show a value for the current and previous month.

The metrics are as follows:

- Number of namespaces (currently on the HOODAW reports)
- Number of production namespaces
- Number of non-production namespaces
- Number of unique applications on the platform (currently on the HOODAW reports)
- Average cost per namespace
- MTTR (currently in our incident log)
- Number of deployments (CP deployments rather than user deployments)
- Number of failed deployments (we do have some code for this)

## Which part of the user docs does this impact

New page

## Questions / Assumptions

Assumption - Metrics are based on data at month end
Assumption - We may been to manually calculate some metrics and update the page each month
Assumption - We may not be able to automate some or all of the calculation
Assumption - We can calculate the metrics we want

## Definition of done

- [ ] New page/site in the guide where we can publish metrics

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
So far:
Grafana:



[AWS Cost metrics (Note - Need selector by Namespace)](https://grafana.cp-0202-1257.cloud-platform.service.justice.gov.uk/explore?orgId=1&left=%7B%22datasource%2[…]:%22now%2FM%22,%22to%22:%22now%22%7D%7D)
Prometheus Query/Metrics browser in Grafana:
`aws_costs{hosted_ns="abundant-namespace-dev"}`


[Unique Applications (Note - not giving previous days totals):](https://grafana.cp-0202-1257.cloud-platform.service.justice.gov.uk/explore?orgId=1&left=%7B%22datasource%22:%22prometheus%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22prometheus%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22count%28count%28namespace_details%7Bapplication%3D~%5C%22.%2A%5C%22%7D%29%20by%20%28application%29%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now%2FM%22,%22to%22:%22now%22%7D%7D)
Prometheus Query/Metrics browser in Grafana:
`count(count(namespace_details{application=~".*"}) by (application))`

[Namespaces by Prod/Non-Prod (Note - not giving previous days totals):](https://grafana.cp-0202-1257.cloud-platform.service.justice.gov.uk/explore?orgId=1&left=%7B%22datasource%2[…]:%22now%2FM%22,%22to%22:%22now%22%7D%7D)
Prometheus Query/Metrics browser in Grafana:
`count(namespace_details{is_production="true"})`
and 
`count(namespace_details{is_production="false"})`

**Comment by pwyborn** [comment]
Dashboard to be placed here:
https://github.com/ministryofjustice/cloud-platform-metrics/tree/main/kubectl_deploy

**Comment by pwyborn** [comment]
So far:
https://grafana.live.cloud-platform.service.justice.gov.uk/d/aws_costs_metrics/aws_costs_metrics?orgId=1&search=open&query=metric.
The ones with `metrics/monitoring` tags
