### ISSUE TITLE
Every sprint deploy an app using the guide

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#427]
## Background

It is essential that we keep the user guide up to date and that it is correct as it is our "front door" to the platform.

To ensure that it is up to date we will deploy an app every sprint. This will give us confidence in the guide and help us make improvements to the guide (in addition to feedback we receive from users).

Previously we have carried out this task however, we feel that we would learn more by out of our users carrying out the take with one of our team on hand to receive any feedback so that we can improve the guide.

## Proposed user journey

When a users wants to use the Cloud Platform they must have access to the latest correct information that will help them interact with the Cloud Platform.

## Approach

Every sprint a user should deploy an app to the platform by running through the guide. PR should be raised for changes to the guide.

## Which part of the user docs does this impact

N/A (However, updates may be required if any issues arise or changes are required)

## Definition of done

- [ ] App deployed using the guide
- [ ] PR raised for any minor corrections to the guide
- [ ] Comment added to the ticket to say when the deployment last carried out
- [ ] **Don't close the ticket**

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
done for this round, see https://circleci.com/gh/ministryofjustice/cloud-platform-reference-app

**Comment by vijay-veeranki-moj** [comment]
Completed deploying an App using the guide for sprint starting 28th-Jan-2019

**Comment by vijay-veeranki-moj** [comment]
Completed deploying an App using the guide for sprint starting 11th-Feb-2019 used namespace userguide-test-wc1102

**Comment by vijay-veeranki-moj** [comment]
Completed deploying an App using the guide for sprint starting 11th-Feb-2019 used namespace userguide-2702

**Comment by digitalronin** [comment]
I was chatting about this with Jason, earlier.

How about, instead of *us* deploying an app every so often, we collaborate with a developer while *they* go through the process?

That way, we avoid letting our own familiarity with the platform bias our view of how good the documentation is, and we spread knowledge of the platform among developers as a side-effect.

**Comment by vijay-veeranki-moj** [comment]
agree

**Comment by jasonBirchall** [comment]
This ticket is now obsolete. Recent documentation changes have changed this process dramatically.
