### ISSUE TITLE
Create alert for grafana dashbord error "no database write permissions because of duplicates"

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4271]
Recently a new restructure on the duplicate validator was added by grafana, this mechanism prevents overwriting due to duplicate data.

Grafana is unable to provision new dashboards if any of the dashboards use duplicate uid and dashboard titles.

It gives the below error and stops adding new dashboards.
"dashboards provisioning provider has no database write permissions because of duplicates"

Some notes as per the provisioning documentation:
Note: Provisioning allows you to overwrite existing dashboards which leads to problems if you re-use settings that are supposed to be unique. Be careful not to re-use the same title multiple times within a folder or uid within the same installation as this will cause weird behaviours.

There is an upstream issue raised related to this:
https://github.com/grafana/grafana/issues/39467

Until then we need to look into options of alerting us if any duplicates get created, so we can take action.

**Comment by vijay-veeranki** [comment]
No metrics available like grafana_provisioning_duplicates{type="uid|title"}

It may be implemented as part of this issue 
https://github.com/grafana/grafana/issues/39467

**Comment by AntonyBishop** [comment]
Look into basing alerts on Logs

**Comment by jackstockley89** [comment]
Fix was added.
