### ISSUE TITLE
Update terraform module to remove cluster_name variable

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4272]
## Background

As part of keeping the terraform modules cluster agnostic, ticket: https://github.com/ministryofjustice/cloud-platform/issues/4111, all modules are updated to not refer `live` or `manager`. The elasticsearch module has been updated to remove `cluster_name` and use `vpc_name` in the release 4.0.1.

- Update the users elasticsearch module to use release 4.0.1 and remove cluster_name from the variables.tf
- Update other user modules i.e. rds to use vpc_name and remove cluster_name from variables.tf
- Update cli template /variables.tf to remove cluster_name

## Definition of done

- [ ] user module for ES updated to latest release
- [ ] user terraform modules refering cluster_name is removed
- [ ] cli-template updated to remove cluster_name
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Completed this work
