### ISSUE TITLE
Fix s3 module terraform warnings

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4277]
After we upgrade aws provider in the s3 module, we see some warnings.

Fix them and test that it is not affecting the existing bucket.

There are around 5-6 warnings related to being fixed, related to an argument being deprecated.

For example:

```
Warning: Argument is deprecated

  on .terraform/modules/s3_bucket/main.tf line 26, in resource "aws_s3_bucket" "bucket":
  26: resource "aws_s3_bucket" "bucket" {

Use the aws_s3_bucket_cors_configuration resource instead
```

Some examples:
```

locals {
  bucket_name   = var.bucket_name == "" ? "cloud-platform-${random_id.id.hex}" : var.bucket_name
  s3_bucket_arn = "arn:aws:s3:::${aws_s3_bucket.bucket.id}"
  versioning    = var.versioning == "true" ? "Enabled" : "Disabled"
}

  # versioning {
  #   enabled = var.versioning
  # }

  # dynamic "logging" {
  #   for_each = var.logging_enabled == true ? [1] : []
  #   content {
  #     target_bucket = var.log_target_bucket
  #     target_prefix = var.log_path
  #   }

  # }

resource "aws_s3_bucket_logging" "logging" {
  for_each = var.logging_enabled == true ? toset([1]) : toset([])

  bucket = aws_s3_bucket.bucket.id

  target_bucket = var.log_target_bucket
  target_prefix = var.log_path
}

resource "aws_s3_bucket_versioning" "versioning_example" {
  bucket = aws_s3_bucket.bucket.id
  versioning_configuration {
    status = local.versioning
  }
}
```

**Comment by vijay-veeranki** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket/compare/update-s3-for-tf-upgrade?expand=1

These changes have warnings fixed, using separate resources.

But lifecycle_rule is not working because of this issue:
https://github.com/hashicorp/terraform-provider-aws/issues/23243

**Comment by vijay-veeranki** [comment]
Placed this on the block as there are a fair amount of changes and we don't want to apply them now before 1.2.5 upgrade.

**Comment by sj-williams** [comment]
Closing as will be covered here:
https://github.com/ministryofjustice/cloud-platform/issues/5594
