### ISSUE TITLE
Grouped Commits of changes

### ISSUE THREAD

**Issue by joelstobart-moj** [ministryofjustice/cloud-platform#4284]
## Service name

Calculate Release Dates
Manage Offences

## Service environment

Not Applicable

## Impact on the service

I found the rule about preventing multiple changes in different namespaces seems to reinforce some negative behaviours:
I can't group the exact change, for the same functionality, for the same ticket in different folders. I can't make a single pull request to provide consistent configuration for my project.

It's therefore making me duplicate changes between different pull requests. This potentially introduces copy-and-paste errors.
It means I have to get more people to review associated changes. With numerous duplicative pull requests, there is more likelihood of an error slipping through.

Is there a possibility of a rethink of this rule in the future?

Can't commit atomic changes in a single commit because they affect multiple namespaces

## Joel Stobart

joel.stobart@...
Joel Stobart on slack :)

**Comment by poornima-krishnasamy** [comment]
Hi @joelstobart-moj ,Cloud Platform suggest creating PR per namespace so the changes are tested one environment at a time. Thereby ensuring lower environment is deployed correctly before moving to production. 

Hoever, if you have a PR with a small editorial change or you know that change is fine to apply on all environments at once, 
 you can always check with us in #ask-cloud-platform and we can overwrite the check for that particular PR. 

Closing this ticket. Feel free to reach us for any further queries
