### ISSUE TITLE
New pingdom slack integrations

### ISSUE THREAD

**Issue by andrewrlee** [ministryofjustice/cloud-platform#4285]
## Service name

* create-and-vary-a-licence
* offender-management-allocation-manager
* hmpp-welcome-people-into-prison

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Problem description

Please can we have the following pingdom slack integrations set up?:

**team name**: create and vary a licence
**application names**:  create-and-vary-a-licence, offender-management-allocation-manager
**slack channel**: #cvl_alerts

**team name**: DPS shared
**application names**:  hmpps-welcome-people-into-prison
**slack channel**: #elp_alerts

Thanks

## Contact person

@Andrew Lee

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1671019968204059
