### ISSUE TITLE
New Slack Integration 

### ISSUE THREAD

**Issue by joelstobart-moj** [ministryofjustice/cloud-platform#4286]
## Service name

- Calculate Release Dates
- Manage Offences
- Digital Warrant Folder

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Problem description

Please can we have the following Pingdom slack integrations set up?:

team name: calculate-release-dates, manage-offences
application names: calculate-release-dates, calculate-release-dates-api, manage-offences, manage-offences-api
slack channel: #farsight-alerts

## Contact person
@Joel Stobart

**Comment by vijay-veeranki** [comment]
integration=126338
