### ISSUE TITLE
New Pingdom-Slack integration

### ISSUE THREAD

**Issue by steverendell** [ministryofjustice/cloud-platform#4288]
## Service name

hmpps-prisoner-contacts

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Problem description

Please can we have a Pingdom slack integration set up, so that the hmpps-prisoner-contacts-prod service (and other syscon services) sends alerts to the slack channel #syscon-alerts.

As I understand it, we just need an integrationid value to add to our pingdom.tf files

## Contact person

@Steve Rendell

**Comment by vijay-veeranki** [comment]
integration=126478
