### ISSUE TITLE
SPIKE: Splitting traffic using HAProxy

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#430]
## Background

Spike in exploring use of HAProxy to split traffic.

## Approach

Tech spike to answer the questions below.

## Questions / Assumptions

In this spike we want to answer the following questions:
1. This option provides the right functionality (split traffic to multiple endpoints based on %)
2. How does a user update/change the %
3. What do we have to maintain/keep high availability?
4. How to we provision the solution for other teams?
5. Are there any costs?

## Definition of done

- [x] spike questions answered

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by nayoa** [comment]
Launched an EC2 instance in `mojds-platform-integration` (eu-west-1). called `haproxy-test`. Installed ha-proxy via yum. Had difficulty configuring so returning to do column. You can use the `weight` feature to control the traffic split. 

https://www.bogotobogo.com/DevOps/AWS/aws-Load-Balancing-with-HAProxy-High-Availability-Proxy.php
https://www.haproxy.com/blog/haproxy-amazon-aws-best-practices-part-1/
http://www.robertsindall.co.uk/blog/blog/2013/03/25/installing-haproxy-on-amazon-linux-ami/

**Comment by nayoa** [comment]
hapee-test-elb-485402904.eu-west-1.elb.amazonaws.com

The user can change the weighting by amending the haproxy config in https://github.com/ministryofjustice/kubernetes-investigations/pull/80/files 

The cost is for a small infrastructure declared in the above PR. This includes an EC2 instance, load balancer, VPC etc. Note the EC2 size needs to change to ensure it can handle the traffic 

Lessons learnt:
Applying an ACM certificate to the haproxy proved difficult as we could not export the certificate as it's not private. Further investigation is required if this method is chosen.

**Comment by razvan-moj** [comment]
done, https://github.com/ministryofjustice/kubernetes-investigations/pull/80
