### ISSUE TITLE
New Alert Route in Alert manager

### ISSUE THREAD

**Issue by digitalali-moj** [ministryofjustice/cloud-platform#4301]
## Service name

Track a Query

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Allows prometheus alerts to be slacked to cdpt team channel
Namespace: track-a-query-production
Team: central-digital-product-team
Application: Track-a-query
Slack channel: #cdpt-central-digital-product-team
Secret name: slackwebhook
Severity level: Warning

## Problem description

Currently no Slack alerts if something goes wrong

## Contact person

Javid Ali - javid.ali@digital.justice.gov.uk

**Comment by vijay-veeranki** [comment]
severity = "cdpt-central-digital"
