### ISSUE TITLE
New Pingdom integration IDs for #dps_sed_alerts

### ISSUE THREAD

**Issue by mpbostock** [ministryofjustice/cloud-platform#4313]
## Service name

pathfinder, manage-soc-cases, offender-categorisation, hmpps-prisoner-communication-monitoring

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Allow us to connect pingdom alerts to a slack channel (#dps_sed_alerts)

## Problem description

We require a slack channel integration id (for #dps_sed_alerts) to use in our pingdom terraform configuration

## Contact person

Mike Bostock / Jon Hindle

**Comment by sj-williams** [comment]
Created.

integration=126838
