### ISSUE TITLE
SPIKE: Splitting traffic using AWS resources

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#432]
## Background

Spike in exploring use of AWS resources (e.g. WAF, CloudFront) to split traffic.

## Approach

Tech spike to answer the questions below.

## Questions / Assumptions

In this spike we want to answer the following questions:
1. This option provides the right functionality (split traffic to multiple endpoints based on %)
2. How does a user update/change the %
3. What do we have to maintain/keep high availability?
4. How to we provision the solution for other teams?
5. Are there any costs?

## Definition of done

- [ ] spike questions answered

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
To sum up:
1. Route53 works, easiest to set up
2. ELB doesn't work
3. ALB would normally work but requires peered VPCs and we have conflicting IP ranges
4. Shield Advanced would probably work but has a high initial cost and no trial option to test properly
