### ISSUE TITLE
Phase 4: Test RDS creds 

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#4329]
Test and write user-docs for the RDS creds step

**Comment by vijay-veeranki** [comment]
Preference 1:
https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/pull/138

Preference 2:
https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/pull/136

Preference 3:
https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/pull/137
