### ISSUE TITLE
SPIKE: Splitting traffic using LaunchDarkly

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#433]
## Background

Spike in exploring use of LaunchDarkly to split traffic.

## Approach

Tech spike to answer the questions below.

## Questions / Assumptions

In this spike we want to answer the following questions:
1. This option provides the right functionality (split traffic to multiple endpoints based on %)
2. How does a user update/change the %
3. What do we have to maintain/keep high availability?
4. How to we provision the solution for other teams?
5. Are there any costs?

## Definition of done

- [ ] spike questions answered

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ollieanwyll** [comment]
@kalbir @alkar From what I can see, for LaunchDarkly to work the application code itself has to be modified. Is this a dealbreaker?

**Comment by ollieanwyll** [comment]
**1.	This option provides the right functionality (split traffic to multiple endpoints based on %)**
	
LaunchDarkly does provide the functionality to split based on a percentage, but as far as I’m aware it’s not pointing to endpoints, but instead different blocks of code, one with the old and one with the new.

**2. 	How does a user update/change the %**

The user logs into the LaunchDarkly web portal and navigates to the ‘Feature Flag’ section and they can then adjust percentage via a slider from 100% on the far left for feature A to 100% on the far right for feature B.

**3.    What do we have to maintain/keep high availability?**

LaunchDarkly will require maintenance as it requires constant updates to the application code and the removal of feature flags when a rollout is complete.

**4. 	How do we provide the solution for other teams?**

As LaunchDarkly works by inserting IF and ELSE statements into the application’s code itself, if implemented it will very much be a thing maintained by the application teams. I anticipate it will be tough to convince all the application teams to get onboard.

**5. Cost **

LaunchDarkly operates it cost around the amount of traffic it serves to it’s users. The professional package costs roughly $325 a month and for the enterprise package, you need to contact the sales team a negotiate a fee based on your level of usage.
