### ISSUE TITLE
Phase 4: Cert-manager Test

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#4331]
Look into steps and write user-docs for user certificate in NSs

**Comment by vijay-veeranki** [comment]
Identify and delete the secret of the certificate.

There is a potential downtime of a few seconds.

`HTTP/2 200
date: Fri, 20 Jan 2023 17:37:57 GMT
content-type: text/html;charset=utf-8
content-length: 22
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=15724800; includeSubDomains

curl: (60) SSL: no alternative certificate subject name matches target host name 'abundant.yy-0601-0100.cloud-platform.service.justice.gov.uk'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
curl: (60) SSL: no alternative certificate subject name matches target host name 'abundant.yy-0601-0100.cloud-platform.service.justice.gov.uk'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
HTTP/2 200
date: Fri, 20 Jan 2023 17:38:03 GMT
content-type: text/html;charset=utf-8
content-length: 22
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=15724800; includeSubDomains
`
