### ISSUE TITLE
Phase 5: Trivy Scan

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#4332]
Run using script created

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-trivy-operator/

**Comment by jasonBirchall** [comment]
https://grafana.live.cloud-platform.service.justice.gov.uk/d/trivy_starboard_operator123/trivy-operator-image-vulnerability?orgId=1&refresh=30s
