### ISSUE TITLE
Change Slack channel for alerts

### ISSUE THREAD

**Issue by digitalali-moj** [ministryofjustice/cloud-platform#4337]
## Service name

Track a query

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

None

## Problem description

Need to change the Slack channel please for Alert manager. I've updated the secret in the namespace for "slackwebhook" - namespace track-a-query-production, team: central-digital-product-team, new slack channel: #cdpt-correspondence-tool. Old Slack channel to stop alerts: #cdpt-central-digital-product-team

## Contact person

javid.ali@digital.justice.gov.uk

**Comment by vijay-veeranki** [comment]
severity = "cdpt-correspondence"
