### ISSUE TITLE
Create NS record for integration-api.hmpps.service.justice.gov.uk

### ISSUE THREAD

**Issue by mcoffey-mt** [ministryofjustice/cloud-platform#4338]
## Service name

hmpps-integration-api

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

N/A

## Problem description

We've just created a Route53 zone and require a name server update.

## Contact person

Slack Channel: hmpps-integration-api
Email: matthew.coffey@digital.justice.gov.uk

**Comment by vijay-veeranki** [comment]
NS records added to dsd zone

**Comment by vijay-veeranki** [comment]
Deleted record "integration-api.hmpps.service.justice.gov.uk" under "service.justice.gov.uk" in dsd
