### ISSUE TITLE
Read-only Access to elasticache resources on AWS console

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/cloud-platform#4339]
## Service name

apply for civli legal aid

## Service environment

- [X] Dev / Development 
- [X] Staging
- [X] Prod / Production
- [X] UAT

## Impact on the service

to aid in migrations

## Problem description

access to check existing values

## Contact person

@jsugarman

**Comment by timckt** [comment]
ElastiCache supports ABAC
https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/security_iam_service-with-iam.html

**Comment by timckt** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/pull/33

https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2807

update the SSO modules and bump the cloud-infrastructure account sso modules

**Comment by timckt** [comment]
Updated the cloud platform runbook guide for modifying user permission on aws console
