### ISSUE TITLE
API Gateway in front of EKS with PrivateLink

### ISSUE THREAD

**Issue by emileswarts** [ministryofjustice/cloud-platform#4340]
## Service name

HMPPS Integration API 

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Potential delays to going live if security is unable to sign off on this.

## Problem description

Support API Gateway in front of EKS as mentioned here: https://aws.amazon.com/blogs/containers/integrate-amazon-api-gateway-with-amazon-eks/

Having API gateway in front of EKS provides a number of benefits, such as: 
  Client specific views on usage
  Client specific limits
  Client specific authentication keys
  Support for mutual TLS as an authentication mechanism

While it is possible to send requests directly to our EKS service (HTTP backend integration), this would traverse the public internet. A more secure approach would be integrating with PrivateLink, and have the containers run in a private subnet.

## Contact person

Emile Swarts (emile.swarts@digital.justice.gov.uk)

**Comment by poornima-krishnasamy** [comment]
Hi @emileswarts , is this ticket still relevant and required or have you decided to go on a different approach?
