### ISSUE TITLE
Pull Requests: run `terraform plan`

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#435]
## Background

As a user, when I make changes to terraform in my environments, I want to be given a summary of what it will do before I merge. This allows me to merge without worrying about what it will do.

## Proposed user journey

N/A

## Approach

When a PR is raised, have Concourse run `terraform plan` if any terraform files have changed.

Extract the last line of the plan (summary),
```
Plan: 3 to add, 1 to change, 1 to destroy.
```
and post it to the PR as a comment. You can use the `cloud-platform-moj` account to get a personal access token and do this.

The user can then look into the build logs if they need to see the full plan in detail.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] the above has been implemented and tested

## Reference
- https://github.com/jtarchie/github-pullrequest-resource

**Comment by vijay-veeranki-moj** [comment]
Created a new pipeline called plan-environments which will trigger when a new PR is raised in  ministryofjustice/cloud-platform-environments. for the pipeline to run Terraform plan crated a new file called plan in cloud-platform-environments/bin/.

**Comment by vijay-veeranki-moj** [comment]
Tested this , Terraform plan will be run when a new PR is raised.
