### ISSUE TITLE
Terraform upgrade to version 1.2.5 - update CLI image

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4350]
## Background

Add your new Terraform version to the CLI image along with the old version. This will allow you to run both versions simultaneously.

Upgrade Paths:
0.14 - 1.0.11
1.0.11 to currently 1.2.5

Update CLI image to have multiple terraform versions 0.14.8, 1.0.11, 1.2.5

## Which part of the user docs does this impact

TBC

## Questions / Assumptions

Do we have a runbook for this?

No breaking changes in v0.15
https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md

## Definition of done

- [ ] Terraform version upgraded to v1.2.5

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
https://github.com/ministryofjustice/cloud-platform-cli/releases/tag/1.24.0
