### ISSUE TITLE
Add conditional to environments repository to use 1.2 or 0.14 dependant on the versions.tf

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4351]
## Background

NOTE:- Depending on outcome of testing phase this story may not be required.

Adding condition so that both versions of TF can be used during upgrade. 

## Approach

https://runbooks.cloud-platform.service.justice.gov.uk/upgrade-terraform-version.html#add-conditional-logic

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

1. Dependant on testing phase.

## Definition of done

- [ ] Both versions of TF can be used during upgrade to avoid state issues.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
No longer needed - 1.2.5 is backwards compatible.
