### ISSUE TITLE
Check 3rd party providers can be upgraded to 1.2.5

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4353]
## Background

Ensure all "third-party" modules conform to the upgrade e.g. Pingdom provider.

Chen them all and identify any issues.

## Approach

TBC

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

Assumption - All 3rd party providers support TF 1.2.5

## Definition of done

- [ ] Any risks/issues identified

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Tested Pingdom and irsa modules which we use a third party, they ran ok with tf 1.2.5
