### ISSUE TITLE
Test upgrade on the abundant namespace (test namespace) and on an EKS module

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4356]
## Background

Test upgrade on the abundant namespace (test namespace) and on an EKS module.

One test each module.

## Approach

TBC

## Which part of the user docs does this impact

N/A

## Definition of done

- [ ] Testing complete
- [ ] Any issues identified and resolved 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Tested modules for plan and apply with 1.2.5:
aurora
dynamodb
elasticache
elastisearch
rds-postgres
s3
serviceaccount
sns
sqs
irsa

Tested Plan for dms module in hmpps-workload-preprod namespace

There are few changes to
- kubernetes_secret resource - Adds sensitive_attributes. Hence, the kubernetes_secret resources is updated when doing hte upgrade
- rds-postgres: - Adds sensitive_attributes
- rds-aurora: - Adds sensitive_attributes

Comparing the state files: Modules dependencies has been updated with data resource too

**Comment by poornima-krishnasamy** [comment]
Testing done and all modules changes to version 1.2.5
