### ISSUE TITLE
Test what happens when a namespace has 1.2 version and modules the binary is 0.14

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4358]
## Background

Upgrade test

## Definition of done

- [ ] Test completed successfully

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Scenario 1:

terraform binary version : Terraform v0.14.8
terraform namespace version : required_version = ">= 0.14"
terraform ecr module version: required_version = ">= 1.2"

Run terraform init: errors

Error: Unsupported Terraform Core version

on .terraform/modules/ecr-repo/versions.tf line 2, in terraform:
2: required_version = ">= 1.2"

Module module.ecr-repo (from cloud-platform-terraform-ecr-credentials) does not
support Terraform version 0.14.8. To proceed, either choose another supported
Terraform version or update this version constraint. Version constraints are
normally set for good reason, so updating the constraint may lead to other
errors or unexpected behavior.

**Comment by vijay-veeranki** [comment]
Scenario 2:

terraform binary version : Terraform v0.14.8
terraform namespace version : required_version = ">= 0.14"
terraform ecr module version: required_version = ">= 1.2"

Run terraform init: errors

Error: Unsupported Terraform Core version

Error: Unsupported Terraform Core version

on versions.tf line 3, in terraform:
3: required_version = ">= 1.2"

This configuration does not support Terraform version 0.14.8. To proceed,
either choose another supported Terraform version or update this version
constraint. Version constraints are normally set for good reason, so updating
the constraint may lead to other errors or unexpected behavior.

Error: Unsupported Terraform Core version

on .terraform/modules/ecr-repo/versions.tf line 2, in terraform:
2: required_version = ">= 1.2"

Module module.ecr-repo (from cloud-platform-terraform-ecr-credentials) does not
support Terraform version 0.14.8. To proceed, either choose another supported
Terraform version or update this version constraint. Version constraints are
normally set for good reason, so updating the constraint may lead to other
errors or unexpected behavior.
