### ISSUE TITLE
Delete unused test clusters

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#436]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
Terraform workspaces do not match eachother and what is running, the list below must be checked and unused resources cleaned up:

```
mc: cloud-platform-components$ terraform workspace list | grep test
  cloud-platform-test-3
  cloud-platform-test-5
  cloud-platform-test-7
  cloud-platform-test-8
  cloud-platform-test-lukasz
mc: cloud-platform$ terraform workspace list | grep test
  cloud-platform-test-0
  cloud-platform-test-3
  cloud-platform-test-7
  cloud-platform-test-8
  cloud-platform-test-lukasz
  cloud-platform-test-ollie
  cloud-platforms-test
  test-kuberos
```

**Comment by alkar** [comment]
also `kops get clusters` can be useful

**Comment by vijay-veeranki-moj** [comment]
removed below clusters which are unused test Clusters


cloud-platforms-sandbox | cloud-platforms-sandbox.k8s.integration.dsd.io
-- | --
cloud-platform-test-0 | cloud-platform-test-0.k8s.integration.dsd.io
cloud-platform-docs | cloud-platform-docs.k8s.integration.dsd.io
non-production | non-production.k8s.integration.dsd.io
