### ISSUE TITLE
Check for missing LICENSES in repos

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#437]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
- https://ministryofjustice.github.io/technical-guidance/standards/licencing-software-or-code/#licensing-software-or-code

**Comment by vijay-veeranki-moj** [comment]
Created LICENSE files for all those missing in Cloud Platform repos.

added License files for all the below repo's


https://github.com/ministryofjustice/cloud-platform-environments
https://github.com/ministryofjustice/cloud-platform-reference-app
https://github.com/ministryofjustice/cloud-platform-concourse
https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials
https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket
https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance
https://github.com/ministryofjustice/cloud-platform-hawkeye
https://github.com/ministryofjustice/cloud-platform-terraform-sqs
https://github.com/ministryofjustice/cloud-platform-smoke-tests
https://github.com/ministryofjustice/cloud-platform-terraform-dynamodb-cluster
https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance
https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials
https://github.com/ministryofjustice/cloud-platform-terraform-elasticache-cluster
https://github.com/ministryofjustice/cloud-platform-terraform-sns-topic
https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket
