### ISSUE TITLE
Create Incident Timeline - Docker Password Reset Incident

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4375]
## Background

Create an incident timeline for the Docker password reset Incident incident which will be an input for the postmortem.

## Definition of done

- [ ] Timeline created and ready for postmortem.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
google doc link:
https://docs.google.com/document/d/1euEdw8FzgVxHVIWeLXxXfB7eYvyv4k5Yj0AzkEQ2Rfo/edit#heading=h.gjdgxs
