### ISSUE TITLE
Create Incident Timeline - CJS Dashboard Performance

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4377]
## Background

Create an incident timeline for the CJS Dashboard performance incident which will be an input for the postmortem.

## Definition of done

- [ ] Timeline created and ready for postmortem.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/157eG261Kj2vf44bComgEZs7NU8eB_pgLWd7Qw9yvsUo/edit#
