### ISSUE TITLE
Monitoring: Add LB 5xx alerts

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#438]
Background:
One of the issues we investigated whilst performing the Chaos engineering tests was that we had a number of 5xx errors on the nginx-controller logs but no alert. 

Task:
Look at how we can set up a triggered alert using our current monitoring stack for:
if we receive > 10 5xx errors in 15 minutes
then trigger a warning in Prometheus/AlertManager.

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-prometheus/pull/34

**Comment by pwyborn** [comment]
Done
