### ISSUE TITLE
Access application logs from the application itself (by accessing the ElasticSearch cluster they're stored in)

### ISSUE THREAD

**Issue by patrick-laa** [ministryofjustice/cloud-platform#4380]
## Service name

"Check if your client qualifies for legal aid", a.k.a CCQ, aka 'laa-estimate-financial-eligibility-for-legal-aid'

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Our service cannot currently measure accurately and programmatically the completion rate (as [mandated](https://www.gov.uk/service-manual/measuring-success/data-you-must-publish) by the service manual). This is because we do not have our own data persistence to track this (and Google Analytics only covers the users who actively opt in, which does not give us a statistically significant sample size at present). The information we need to measure completion rate _is_ available in the application logs, and therefore we would like to be able to access those logs. 

If this is not possible then we need to set up alternative infrastructure to duplicate the logs in a more accessible place. (Which, to be fair, is totally possible, it's just more work for us.)

## Problem description

Our application logs are centralised using fluentbit into an ElasticSearch cluster (accessible via Kibana). We [have been told](https://mojdt.slack.com/archives/C57UPMZLY/p1676452867650619?thread_ts=1676450849.298329&cid=C57UPMZLY) it is not possible for our application to access that cluster.

## Contact person

Patrick Gleeson (patrick.gleeson@digital.justice.gov.uk)

**Comment by vijay-veeranki** [comment]
The team decided to duplicate the log data needed in a Postgres database, so that way they have easy access to it. 
Closing the ticket
