### ISSUE TITLE
Delay in processing traffic when there is a app deployment 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4381]
## Service name

Several apps experience the behaviour
https://mojdt.slack.com/archives/C57UPMZLY/p1674747282301369
https://mojdt.slack.com/archives/C57UPMZLY/p1676308375691789

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Delayed response from application

## Problem description

https://mojdt.slack.com/archives/C57UPMZLY/p1674747282301369
https://mojdt.slack.com/archives/C57UPMZLY/p1676308375691789

## Contact person

Michael Blatherwick
Stephen Dicks

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1oo1WIYqoCXyy9naLVU0g5UYigUlgWBt59cy_i68zUEw/edit

**Comment by vijay-veeranki** [comment]
Response time looks Ok after the calico upgrade.

I have tried it on the test cluster, and on live with peak and non-peak times of the network.

Used single and multiple replica to do the test, similar results.

Used below in the deployment for better results:
 strategy:
   rollingUpdate:
     maxSurge: 25%
     maxUnavailable: 25%
   type: RollingUpdate

       readinessProbe:
         failureThreshold: 10
         httpGet:
           path: /
           port: http
           scheme: HTTP
         initialDelaySeconds: 20
         periodSeconds: 20
         successThreshold: 1
         timeoutSeconds: 10

**Comment by exonian** [comment]
From Slack [on Monday](https://mojdt.slack.com/archives/C57UPMZLY/p1678711645300159?thread_ts=1678120747.909119&cid=C57UPMZLY)
> Percentage of the requests served within a certain time (ms)
  50%     44
  66%     48
  75%     51
  80%     57
  90%     72
  95%     84
  98%    116
  99%    150
 100%  19090 (longest request)
Reliably 15-20s for the slowest response via ab , but successful responses. I don’t understand this behaviour at the moment.
But anecdotally unable to trigger a slow request via the browser so far, which used to be absolutely trivial to do.

**Comment by exonian** [comment]
Outstanding work to be done on this issue, which appears to have come to a halt:

1) is that slow response that ab notices expected and unavoidable? What causes it? It appears to be a very short window of time that it happens in (unlike the previous, which was a window of multiple seconds) but obviously if a user hit it it would be bad. Is that always there in k8s environments and the zero-downtime assertion accepts it? Or is there still work to be done to identify what is causing it and how to fix it?
2) What is Calico? Why did upgrading it solve the issue? What was the old version doing or not doing that caused endpoint propagation to take orders if magnitude longer than normal?
3) Was it a scheduled upgrade that happened to coincide with you getting around to working on this or was it done in response to the issue?
4) How can we be confident that this service degradation won't happen in the future? What platform-level alerting is in place to identify a regression? What are the thresholds for that alerting and will we be informed? (I am conscious that users weren't informed this time, after I brought it to the team's attention, unless I missed an update)

I think that while I can have devs test whether deployments appear to be smooth now, I can't tell teams or stakeholders that things are fine now without being able to answer their questions, and they absolutely will ask me all the above
