### ISSUE TITLE
Secrets Management User Research

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4388]
## Background

We are looking at implementing a secrets management feature for users of the Cloud Platform.

We should understand what this means to users. What secrets do they need to manage? How do they manage secrets now? What challenges to users have managing secrets?

## Approach

Do some user research to understand user needs.

## Communicate changes

- [ ] Contact various groups to get volunteers for research.

## Questions / Assumptions

- What secrets need to be managed?
- What problems to users encounter when managing secrets?
- What tools are teams currently to manage secrets?

## Definition of done

- [ ] We have a much better understanding of our users needs to that we can provide appropriate solution to their problems.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Current MoJ Policy on Managing Secrets - https://security-guidance.service.justice.gov.uk/secrets-management/#secrets-management

**Comment by AntonyBishop** [comment]
LAA Secrets Management Round Table - https://jamboard.google.com/d/1AnsipuACnkLSJp0E3GnjZeLfflkxsRKrMiOw0BxVQy4/edit?usp=sharing

**Comment by ScottSeaward** [comment]
Held a Secrets workshop with users. Outputs are on this doc https://docs.google.com/document/d/18KMey0_XquR6hc3mYNrRAPoEWk6RmirPgPncSLye0gE/edit?usp=sharing
