### ISSUE TITLE
Create NS record for data-platform.service.justice.gov.uk

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/cloud-platform#4390]
## Service name

Data Platform Production

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

N/A

## Problem description

Pull request has merged https://github.com/ministryofjustice/cloud-platform-environments/pull/10974 and has been deployed https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/3778

## Contact person

Slack: [data-platform-tech](https://mojdt.slack.com/archives/C04EZAZQV1V)
Email: data-platform-tech@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
Created the NS record for `data-platform.service.justice.gov.uk` on root domain `service.justice.gov.uk in DSD account
