### ISSUE TITLE
Pingdom slack integration request

### ISSUE THREAD

**Issue by Coupey** [ministryofjustice/cloud-platform#4393]
## Service name

- hmpps-assess-risks-and-needs
- hmpps-assessments

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Problem description

Please can we have the following pingdom slack integrations set up?:

team name: hmpps-assess-risks-and-needs
application names: hmpps-assess-risks-and-needs, hmpps-assessments
slack channel: #hmpps-assessments-notifications

Thanks

## Contact person

Paul Coupe

**Comment by vijay-veeranki** [comment]
integration id =127850
