### ISSUE TITLE
Ability to get vulnerability report from container scans

### ISSUE THREAD

**Issue by moj-is** [ministryofjustice/cloud-platform#4395]
## Background

As I understand, we run vulnerability scans on running Containers which generate report of all potential vulnerabilities on each run. This is then stored in Prometheus.

We would like access to this report via an API (Internal to MOJ)

## Approach

e.g. REST returning a json format of each vulnerability identified along with its details such as Critical/High/Medium etc.

## Which part of the user docs does this impact

Vulnerability Scanner on running containers

## Questions / Assumptions

- We don't have access to k8s
- Our application is currently running on AWS Cloud so ideally we'd like this application to have the correct permissions to fetch this report

## Definition of done

- [ ] We have an api using which we should be able to fetch the scan reports at various intervals.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Conversation [here](https://mojdt.slack.com/archives/C57UPMZLY/p1677509957173349).

The initial idea here is as follows:
either
1. give security a role to pole the Kubernetes API for trivy vulnerabilities, i.e. `kubectl get vuln -A`. This would happen via a serviceaccount with the relevant permissions. They can then create a namespace, host an API for the external app to call.
2. we build a simple API that does the above on their behalf. Give security an API access key for them to read data only.

**Comment by warmanaMOJ** [comment]
@jasonBirchall Thank you - these are helpful points.

What is the correct way to progress this? Anything we can do to help/expedite?

**Comment by mattops** [comment]
Just bumping this issue, would be a good thing to have.

**Comment by poornima-krishnasamy** [comment]
Hi @warmanaMOJ , I have created a ticket to implement the report app. We will discuss with in the team to see when we can start implementing that. We will add more information on the below ticket regarding the progress.

https://github.com/ministryofjustice/cloud-platform/issues/5371
