### ISSUE TITLE
How do we manage access to Secrets Manager - JML Process

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4397]
## Background

How do JML processes impact Secrets  Manager?

## Approach

Questions to answer:
1. How to we ensure that leavers have access to secrets removed? 
2. What happens when users change teams and need access to different secrets? 
3. What about new platform users?
4. How do we revoke of change access?

## Which part of the user docs does this impact

N/A

## Communicate changes

N/A

## Definition of done

- [ ] We have documented and answered the questions.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Document updated with answers: https://docs.google.com/document/d/1toVzSOKffB5ZoNr9x1dWLvPPZWh1aFCLbgYcDLCbR7E/edit?usp=sharing

**Comment by sj-williams** [comment]
Reviewed doc. All looks good.
