### ISSUE TITLE
Audit Features of Secrets Manager

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4399]
## Background

What audit capability do we have around Secrets Manager?

## Approach

SPIKE

## Which part of the user docs does this impact

N/A

## Communicate changes

N/A

## Questions / Assumptions

- How to we audit access, changes to secrets etc?
- How do we access any logs
- How to we determine inappropriate use or a security breach?
- What sort of alarms/alerts might we need to operate the service?

## Definition of done

- [ ] We have documented answers to the questions.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1Xr1FC-L_kcZWV05iMYHQbH0yEZ6M828svUVgw55POkg/edit#heading=h.wvee9l7i2e3m

**Comment by vijay-veeranki** [comment]
Closed this as raised another ticket for alerts
https://github.com/ministryofjustice/cloud-platform/issues/4539
