### ISSUE TITLE
How to we ensure separation between CP and User secrets

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4400]
## Background

We need to ensure separation between CP and User secrets. can we make sure this is the case.

## Questions:

- Can we ensure our secrets are seperate?
- To what extent to we allow users to share or access secrets
- What permissions are required to limit access.

## Definition of done

- [ ] We are confident that there is suitable separation.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
module example 
https://github.com/ministryofjustice/cloud-platform-terraform-secrets-manager/tree/concourse

**Comment by tom-j-smith** [comment]
Separation between CP and User secrets document: https://docs.google.com/document/d/19dg4LTsqrx82Eb6j9kJeh5UD7OkxQAE0LXJQhc0Hybw/edit#heading=h.kvuvs7vnyyb1
