### ISSUE TITLE
How can we ensure namespace A doesn't have access to the secrets of namespace B?

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4401]
## Background

Question: How can we ensure namespace A doesn't have access to the secrets of namespace B?

## Approach

Determine how to ensure that the above outcome can be achieved. What controls need to be in place etc?

## Which part of the user docs does this impact

N/A

## Communicate changes

N/A

## Definition of done

- [ ] We are sure that namespace A doesn't have access to the secrets of namespace B.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
module example 
https://github.com/ministryofjustice/cloud-platform-terraform-secrets-manager/tree/concourse

**Comment by AntonyBishop** [comment]
Duplicate
