### ISSUE TITLE
How would users interact with Secrets Manager via the Console?

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4404]
## Background

This story is to look into how users might interact with Secrets Manager. We have a number of questions to address as part of this spike. 

This spike assumes that the intended route is for users to interact via the console.

## Questions / Assumptions

- Do we allow users write access via the console?
- Can/How can users "self-service" Secrets Manager?
- How will users create, and then insert new secrets?
- Do we use assumed roles?
- Is it the same process for users and CP
- Maybe per namespace role?
- How to authenticate users?

## Definition of done

- [ ] We are able to make some design decisions about how users would interact with Secrets Manager.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Split story into Console Story and CLI story

**Comment by AntonyBishop** [comment]
Split story into Console Story and CLI story

**Comment by poornima-krishnasamy** [comment]
While @ScottSeaward do the user Research, I am looking at the technical aspect of how the console access can be acheived.

**Comment by cloud-platform-dummy-user** [comment]
Step 1: Add the required permissions to the “access-via-github” role. This role is used to map the resource tags with the same PrincipalTag when authenticated via SAML
E.g:
```
 {
            "Sid": "VisualEditor9",
            "Effect": "Allow",
            "Action": "Action" : [ "secretsmanager:Put*", "secretsmanager:Update*", ], ?? TODO need to define correct permissions
            "Resource": "*",
            "Condition": {
                "StringLike": {
                    "aws:PrincipalTag/GithubTeam": "*:${aws:ResourceTag/GithubTeam}:*"
                }
            }
        }
```

Step 2: Tag the secret resource with Key "GithubTeam" and Value "<the github team who needs to access>"

Step 3: Set the ResourcePolicy when creating each secret:
```
{
  "Version" : "2012-10-17",
  "Statement" : [ {
    "Sid" : "VisualEditor1",
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "arn:aws:iam::418216798584:role/access-via-github"
    },
    "Action" : [  "secretsmanager:Put*", "secretsmanager:Update*" ],
    "Resource" : "<arn of the secret resource>",
    "Condition" : {
      "StringEquals" : {
        "AWS:SourceOwner" : "<AWS account ID>"
      }
    }
  }, {
    "Sid" : "VisualEditor2",
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "arn:aws:iam::418216798584:role/access-via-github"
    },
    "Action" : [ "secretsmanager:ListSecrets", "secretsmanager:DescribeSecret" ],
    "Resource" : "*",
    "Condition" : {
      "StringEquals" : {
        "AWS:SourceOwner" : "<AWS Account ID>"
      }
    }
  } ]
}
```
Now login using SAML who belong to specific github team and access the specific secret using the secret name. e.g. https://eu-west-2.console.aws.amazon.com/secretsmanager/secret?name=abundant-namespace-dev/slack-api&region=eu-west-2. If the secret name is "abundant-namespace-dev/slack-api"

**Comment by poornima-krishnasamy** [comment]
Step 1: Add the required permissions to the “access-via-github” role. This role is used to map the resource tags with the same PrincipalTag when authenticated via SAML
E.g:
```
 {
            "Sid": "VisualEditor9",
            "Effect": "Allow",
            "Action": "Action" : [ "secretsmanager:Put*", "secretsmanager:Update*", ], ?? TODO need to define correct permissions
            "Resource": "*",
            "Condition": {
                "StringLike": {
                    "aws:PrincipalTag/GithubTeam": "*:${aws:ResourceTag/GithubTeam}:*"
                }
            }
        }
```

Step 2: Tag the secret resource with Key "GithubTeam" and Value "<the github team who needs to access>"

Step 3: Set the ResourcePolicy when creating each secret:
```
{
  "Version" : "2012-10-17",
  "Statement" : [ {
    "Sid" : "VisualEditor1",
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "arn:aws:iam::418216798584:role/access-via-github"
    },
    "Action" : [  "secretsmanager:Put*", "secretsmanager:Update*" ],
    "Resource" : "<arn of the secret resource>",
    "Condition" : {
      "StringEquals" : {
        "AWS:SourceOwner" : "<AWS account ID>"
      }
    }
  }, {
    "Sid" : "VisualEditor2",
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : "arn:aws:iam::<account_id>:role/access-via-github"
    },
    "Action" : [ "secretsmanager:ListSecrets", "secretsmanager:DescribeSecret" ],
    "Resource" : "*",
    "Condition" : {
      "StringEquals" : {
        "AWS:SourceOwner" : "<AWS Account ID>"
      }
    }
  } ]
}
```
Now login using SAML who belong to specific github team and access the specific secret using the secret name. e.g. https://eu-west-2.console.aws.amazon.com/secretsmanager/secret?name=abundant-namespace-dev/slack-api&region=eu-west-2. If the secret name is "abundant-namespace-dev/slack-api"

**Comment by poornima-krishnasamy** [comment]
For secrets which are encrypted with kms-key, in order for user to retrieve/update the secret, tags should be added to the new KMS key

**Comment by poornima-krishnasamy** [comment]
If the secrets use `aws/secretsmanager` encryption key, there is no tags so user can retrive/update secrets fine

**Comment by poornima-krishnasamy** [comment]
Do we allow users write access via the console?
Yes, we have a SSO configured already for accessing aws resources. So it can be extended to write secret values in secrets manager. But users will not be allowed to create secrets using console. Draft PR: https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/pull/21

Can/How can users "self-service" Secrets Manager?
For users secrets which belong to their application, users can use a terraform module with input of secret name. The module will create the given secret/secrets with <namespace> prepended, and policy to access the secret values. 

How will users create, and then insert new secrets?
Users will use the module in environments repo passing the secret names which they want to create.
https://github.com/ministryofjustice/cloud-platform-terraform-secrets-manager

Do we use assumed roles?
Yes the secrets-manager module will output the policy which has permissions only to access secrets starting with <namespace>/ which is passed to IRSA module which creates serviceaccount which the pod uses to access the secret.

Is it the same process for users and CP
Yes, if CP has to store secrets in the secrets manager, it would also use the same module.

Maybe per namespace role?
Yes, each namespace will get a iam-role with permissions to read secrets under <namespace>/

How to authenticate users?
Users are authenticated using SSO with the github credentials.
