### ISSUE TITLE
custom staging subdomain for "assure HMRC data" service

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/cloud-platform#4405]
## Service name

Assure HMRC data

## Service environment

- [ ] Dev / Development
- [X] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Would a custom subdomain for staging environment of this app
https://staging.assure-hmrc-data.service.justice.gov.uk

## Problem description

Not a problem

## Contact person

@jsugarman

**Comment by poornima-krishnasamy** [comment]
Hosted zone created for production domain: https://github.com/ministryofjustice/cloud-platform-environments/pull/11200

**Comment by poornima-krishnasamy** [comment]
Sub domain `assure-hmrc-data.service.justice.gov.uk` NS records added to the root domain service.justice.gov.uk.
