### ISSUE TITLE
Create budget monitoring on Cloud-Platform AWS account

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#441]
BACKGROUND: 
I believe we should be monitoring and thus creating a budget trigger on our new AWS account. This will trigger an alert if the account spend is > x

TASK: 
Decide what X is and use the following or equivalent: https://github.com/ministryofjustice/cloudplatforms-aws-account

**Comment by AntonyBishop** [comment]
Duplicate - Closed
