### ISSUE TITLE
Update front page of guide to clarify that we also support production on the new platform

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#442]
**Background**
The front page of the user guide needs a text update to reflect that also support production services. New users interested in using the new platform might be put off or confused if we state that the platform is only for non-production.

Change the section titled "What do we currently support" to:

"Users can create non-production and production environments and get access to the Kubernetes API for those environments."

**Approach**
Update text in guide

**Definition of Done**
Text in guide updated

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-user-docs/pull/89/files

**Comment by pwyborn** [comment]
Done
