### ISSUE TITLE
Use cloud-platform cli for infrastructure apply pipelines

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4421]
We have infrastructure pipelines which do plan and apply and we are using shell commands to do the plan and apply.

If we want to expand it to hide the secrets, it is better to use cloud-platform cli commands and hide logs similar to those here

https://github.com/ministryofjustice/cloud-platform-environments/blob/main/lib/cp_env/logger.rb#L4-L11

Currently, the divergence pipeline does the plan, we can take that as an example and expand it to use for our apply pipelines.

**Comment by sj-williams** [comment]
Refactored sensitive Concourse Helm values to use `set_sensitive`

https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/246

**Comment by sj-williams** [comment]
cli plan & apply command WIP:
https://github.com/ministryofjustice/cloud-platform-cli/pull/360
