### ISSUE TITLE
EKS module upgrade from 1.17 to 1.18: Run this on test cluster

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4423]
This is related to https://github.com/ministryofjustice/cloud-platform/issues/3884

Upgrading to 1.18 has breaking changes.

Follow this process in test cluster and verify this process is working as expected

We choose to discard the existing node groups from the state and create new ones and then migrate workload on new node groups. This allows for keeping the existing control plane.

https://docs.google.com/document/d/1Nv1WsqdYMBzjpO8jfmXEqjAY5nZ9GYWUpNNaMJVJyaw/edit#

DOD:

The process working without any issues
Update the process if any changes noticed

**Comment by jackstockley89** [comment]
currently reading upgrade guide 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-18.0.md

**Comment by poornima-krishnasamy** [comment]
Ran the updates steps mentioned in the doc on test cluster.
- All nodes nodes came back fine with the workload moved
- No downtime when checking with curl on starter-pack apps
