### ISSUE TITLE
Bring back live-2 environment pipeline 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4428]
## Background

The live-2 environment pipeline was removed as part of circleCI incident to avoid rate limits. Now the circleCI incident is finished, bring back live-2 environment pipeline. 

live-2 environment pipeline is needed to apply changes to the live-2 namespaces. e.g. terraform upgrade to 1.2.5 needs to be applied to live-2

## Approach

PR which removed the live-2: https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/197

## Questions / Assumptions
Check for cli image changes and dont add any filters like folder to the check resource

## Definition of done

- [ ] pipeline brought back and tested plan, apply and apply-namespaces
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
No longer required as decommissioning Live-2
