### ISSUE TITLE
Deploy cla_backend to production

### ISSUE THREAD

**Issue by rowlando** [ministryofjustice/cloud-platform#443]
## Service name

Civil Legal Advice (CLA) Backend

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Our team have not made a release of `cla_backend` before. We need to get confident in doing so because we're starting to make changes. Given the trouble encountered with previous apps under the CLA/FALA banner, we want to deploy to production with the support of Cloud Platform just in case anything goes awry.

The previous [successful deployment was on 03/05/2018](https://ci.service.dsd.io/view/CLA/job/DEPLOY-cla_backend/183/).

## Problem description

The deployment to production needs to happen outside of business hours. These are 09:00 to 20:00. @lukaszraczylo has agreed to do it around 21:00 on 11/10/2018.

Here are the details of the build that needs to be deployed:

| Parameters | Value |
| ----------------| ------ |
| **APP_BUILD_TAG** | master.9d2261f |
| **environment** | prod |
| **deploy_repo_branch** | master |

The same build [has been deployed to staging](https://ci.service.dsd.io/view/CLA/job/DEPLOY-cla_backend/188/parameters/).

## Contact person

Slack: @nick

**Comment by lukaszraczylo** [comment]
Deploying backend as of now ( 21:42 )

**Comment by lukaszraczylo** [comment]
Deployment green. Proceeding to the frontend.
