### ISSUE TITLE
Fix create-test-destroy cluster pipeline

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4431]
## Background
After the terraform upgrade, the create cluster pipeline failed to run.
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/eks-create-test-destroy/jobs/create-cluster-eks/builds/307

This could be because of wrong image, terraform version. Investigate and fix the pipeline 

## Definition of done

- [ ]  pipeline can create cluster, run tests and destroy successfully
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Caused by Ruby version update in newer tools image. Fixed script:
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2113
