### ISSUE TITLE
Next steps for Cloud Platform metrics

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4432]
## Background

As part of the ticket: https://github.com/ministryofjustice/cloud-platform/issues/4266, namespaces related metrics and aws costs metrics are developed. Here are the dashboard: https://grafana.live.cloud-platform.service.justice.gov.uk/dashboards?query=metrics

## Approach

Record below metrics and add to dashboard to see historic data. They are
MTTR (currently in our incident log) - See if that can be parsed from runbook page
Number of deployments (CP deployments rather than user deployments) - reuse existing code to expose metrics: https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/tree/main/reports/infrastructure-deployments
Number of failed deployments (we do have some code for this) - - reuse existing code to expose metrics: https://github.com/ministryofjustice/cloud-platform-how-out-of-date-are-we/tree/main/reports/infrastructure-deployments

- Display the exposed metrics in grafana dashboard

- Create automatic deployment using github actions

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform-metrics

## Communicate changes

- [ ] Weeknotes item

## Definition of done

- [ ] Additional metrics exposed
- [ ] Grafana dashboard created for new metrics
- [ ] Automatic deployment done
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
Deployments graph:
https://github.com/ministryofjustice/cloud-platform-metrics/pull/42

**Comment by pwyborn** [comment]
MTTR graph:
https://github.com/ministryofjustice/cloud-platform-metrics/pull/48
