### ISSUE TITLE
Guidance on how users write their own Terraform for AWS resources

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4436]
## Background

We have given permission to users to create their own Terraform for AWS resources e.g. Cognito, API Gateway.

However, we just leave users to figure out how to do that. We should add a section to our guide that covers some best practices for how to do this on the Cloud Platform.

## Proposed user journey

As a user of the Cloud Platform I can understand when it is appropriate to write our own Terraform for AWS resources and how and where that code should be managed.

## Approach

Add some guidance to [Adding AWS resources to your environment](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/add-aws-resources.html#versioning). Guidance should include:

- Where users should add their code?
- Clarify how that code will be deployed (i.e. via Concourse)
- List would sort of things that we don't think users should be able to create in TF.

## Which part of the user docs does this impact

[Adding AWS resources to your environment](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/add-aws-resources.html#versioning)

## Communicate changes

- [ ] Note should be added to the PM's fortnightly sprint update.

## Questions / Assumptions

N/A

## Definition of done

- [ ] Guide updated.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
We should also consider if we want users to create modules and if so how. In particular the risk of loosing visibility of the code if modules are in separate repos.
