### ISSUE TITLE
Deploy cla_frontend to production

### ISSUE THREAD

**Issue by rowlando** [ministryofjustice/cloud-platform#444]
## Service name

Civil Legal Advice (CLA) Frontend

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Our team have not made a release of `cla_frontend` before. We need to get confident in doing so because we're starting to make changes. Given the trouble encountered with previous apps under the CLA/FALA banner, we want to deploy to production with the support of Cloud Platform just in case anything goes awry.

The previous [successful deployment was on 18/04/2018](https://ci.service.dsd.io/view/CLA/job/DEPLOY-cla_frontend/94/).

## Problem description

The deployment to production needs to happen outside of business hours. These are 09:00 to 20:00. @lukaszraczylo has ~not yet~ agreed to do it around 21:00 on 11/10/2018 ~but hopefully will~.

Here are the details of the build that needs to be deployed:

| Parameters | Value |
| ----------------| ------ |
| **tag** | master.ec69821 |
| **environment** | prod |
| **branch** | master |

Yesterday, I [deployed `develop.ec69821` to the demo environment](https://ci.service.dsd.io/view/CLA/job/DEPLOY-cla_frontend/108/). I merged `develop` into `master` and have [tried deploying `master.ec69821` to the staging environment](https://ci.service.dsd.io/view/CLA/job/DEPLOY-cla_frontend/109/). ⚠️Deployment to staging failed.

## Contact person

Slack: @nick

**Comment by lukaszraczylo** [comment]
Please note that after merge the correct docker image name is merge.a76b789
We can investigate naming convention but few attempts of building the new image with 'master' name in it were proven to be unsuccessful.

**Comment by lukaszraczylo** [comment]
Deploying mentioned image into staging environment at the moment.

**Comment by lukaszraczylo** [comment]
Deployment to staging was successful ( https://ci.service.dsd.io/view/CLA/job/DEPLOY-cla_frontend/110/console )

**Comment by lukaszraczylo** [comment]
Deployment successful ( according to our alerting system )
