### ISSUE TITLE
New Alert Route in Alert manager

### ISSUE THREAD

**Issue by vertism** [ministryofjustice/cloud-platform#4442]
## Service name

find-unclaimed-court-money

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Allows prometheus alerts to be slacked to cdpt-find-unclaimed-court-money channel
Namespace: find-unclaimed-court-money-production
Team: central-digital-product-team
Application: find-unclaimed-court-money
Slack channel: #cdpt-find-unclaimed-court-money
Secret name: slackwebhook
Severity level: Warning

## Problem description

Currently no Slack alerts if something goes wrong

## Contact person

Andrew Pepler andrew.pepler@digital.justice.gov.uk

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1678795114152109?thread_ts=1678786688.679469&cid=C57UPMZLY
