### ISSUE TITLE
Identify Terraform Modules with Helm sensitive values

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4444]
## Background

We have taken the decision to refactor all Terraform modules which pass sensitive data to Helm chart values templates to use the `set_sensitive` field in `helm_release` resources:

https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#set_sensitive

As preparation for this and to determine the amount of work required & issues created, we need to generate a list of all Terraform modules that will need to be addressed. 

## Epic link
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform-user-guide/1392

## Approach

- Get a list of all terraform modules that pass sensitive values. Values can be passed in various methods ie:

`helm_release` `values` field, rendering template file; ex:
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/blob/main/main.tf#L47

`helm_release` `set` field, ex:
https://github.com/ministryofjustice/cloud-platform-terraform-kuberhealthy/blob/main/main.tf#L30

## Definition of done

We have a complete list of modules requiring update, and have issues created to address accordingly.

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

**Comment by tom-j-smith** [comment]
Document has been created to show results of sensitive values findings at the components level:
https://docs.google.com/document/d/1FfW1WOAF9BE3XW1g0dnZE_iX1iCRd3mRj_bsAyzcxlc/view#
