### ISSUE TITLE
Terraform Module set sensitive values: cloud-platform-terraform-monitoring

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4446]
## Background

This ticket is for refactoring module:
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring

Helm chart values deemed sensitive need to be passed using `set_sensitive` `helm_release` field :
(https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#set_sensitive)

An example of this for Concourse module here:
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/246/files

## Approach

Identify sensitive Helm values, switch over to `set_sensitive`, test terraform plan/apply and check rendered values.yaml output on test cluster

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
Team decided to work on this ticket once the environment repo modules are updated for sensitive outputs

**Comment by sj-williams** [comment]
Done, captured in ticket:
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4588
