### ISSUE TITLE
Concourse module sensitive values

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4448]
## Background

This ticket is to cover rollout of `cloud-platform-terraform-concourse` module update bringing `set_sensitive` features to Helm deployment.

PR:
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/246

## Approach

Plan and schedule rollout of module release to upgrade existing Concourse deployment in manager cluster with minimal impact to service.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/compare/main...sensitive

**Comment by tom-j-smith** [comment]
Work has been completed for this issue. All sensitive value outputs in the concourse module have been hidden with the use of set_sensitive.

PR: https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/260

Testing: No issues with building from nothing on the this branch, but upgrading from newest release to this branch will cycle the pods. The web front end becomes temporarily unavailable but it seemed to keep the job I was running during testing alive when the pods came back up.
