### ISSUE TITLE
SPKIE: Split modsec audit logs by namespace

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4449]
## Background

ModSecurity audit logs are stored inside ingress-controller pods under `/var/log/modsec_audit.log`. This is one cumbersome file containing audit logs from all namespace traffic.

Find ways to split the logs by namespace so either it can be send to elasticsearch for fine-grained access(https://github.com/ministryofjustice/cloud-platform/issues/4441) 

or 

to send it as a report to a namespace (https://github.com/ministryofjustice/cloud-platform/issues/4443). 

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
add the following block to your application ingress to tag the audit log messages:

`nginx.ingress.kubernetes.io/modsecurity-snippet: |
        SecRuleEngine On
        SecDefaultAction "phase:2,pass,log,tag:foobarrium"`
