### ISSUE TITLE
Fix grafana dashboard issue caused by duplicate UID

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4451]
Dashboard changes applied for grafana is not been applied when there are duplicate dashboard UID's in the cluster.

* the "uid" needs to be unique across Cloud Platform dashboards. It should be 8+ alphanumeric characters using: [A-Za-z0-9]
* the "title" (at the top level) needs to be unique across Cloud Platform dashboards

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/prometheus.html#configure-a-dashboard-by-copying-an-existing-one

To fix this either we have to restart the pod or remove the duplicate id's

The request raised to users to fix the duplicate uid
https://mojdt.slack.com/archives/C57UPMZLY/p1677235789869729

Figure out a process to stop duplicates or fix to avoid applying new or updated dashboards. Also, update the docs to have better visibility related to this issue.

**Comment by jaskaransarkaria** [comment]
- We should write a admission validation controller that makes sure the new dashboard uid and title is unique

**Comment by poornima-krishnasamy** [comment]
This is covered in this: https://github.com/ministryofjustice/cloud-platform/issues/5368
