### ISSUE TITLE
User Guide RDS Snapshots for replicas

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4456]
## Background

The RDS Snapshots user guide document:

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/rds-snapshots.html#rds-snapshots

should include additional steps required for dealing with replica RDS instances. 

This has been brought to our attention when a snapshot restore PR failed with:
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-live/builds/3652#L640055cd:46357

`Error: cannot elect new source database for replication`

See also here:
https://github.com/hashicorp/terraform-provider-aws/issues/16054

## Which part of the user docs does this impact
Test RDS snapshot restore process with a replica in place.

Update RDS Snapshots guide for dealing with RDS replicas.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
As part of this ticket, can we revisit the original process of rds restore from snapshot?

The guide was written on Feb 2020: https://github.com/ministryofjustice/cloud-platform-user-guide/pull/223. There was an open provider issue and hence the process was that CP team has to rename the RDS instance. But with recent testing with laa-cla-backend-production, the restore went find with just providing the snapshot-identifier and doing a terraform apply.

**Comment by tom-j-smith** [comment]
[Link to docs findings](https://docs.google.com/document/d/1zyeFyI3DwmmgNjV8DE4VEUd2ZJN9Rg5pFcx8fxM0poE) - Screenshots and testings of multiple methods before arriving at the solution.

[Updated user guide documentation](https://github.com/ministryofjustice/cloud-platform-user-guide/commit/c0b194634574677c2a3b7fb6aa5d2689fb3eedc2)
