### ISSUE TITLE
Move route53 config to new namespace for find-unclaimed-court-money

### ISSUE THREAD

**Issue by vertism** [ministryofjustice/cloud-platform#4457]
## Service name
Find Unclaimed Court Money

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Required to put new service live

## Problem description

The existing [Find Unclaimed Court Money](https://find-unclaimed-court-money.service.justice.gov.uk/) site is being ported to a new codebase. 
As part of this we need to move the route53 config to the new namespace
old staging namespace - https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live.cloud-platform.service.justice.gov.uk/ubi-staging
new staging namespace - https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live.cloud-platform.service.justice.gov.uk/find-unclaimed-court-money-staging

old production namespace - https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live.cloud-platform.service.justice.gov.uk/ubi-prod
new production namespace - https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live.cloud-platform.service.justice.gov.uk/find-unclaimed-court-money-production

A PR for the new route53 has been created - https://github.com/ministryofjustice/cloud-platform-environments/pull/11667

SSL certificates for staging and production environments have been created already (https://github.com/ministryofjustice/cloud-platform-environments/pull/11656, https://github.com/ministryofjustice/cloud-platform-environments/pull/11657)

## Contact person

Andrew Pepler
andrew.pepler@digital.justice.gov.uk

**Comment by AntonyBishop** [comment]
Work completed. PR merged.
