### ISSUE TITLE
Persistent Volume Claim not terminating

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#447]
## Service name

NA - playing with kubernetes on new cloud platform using own namespace

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description

When I try to delete a persistent volume claim, the command line hangs. The persistent volume claim remains with the state 'terminating'

- volume - 'pvc-1216d428-d080-11e8-9530-027b09f83346'
- name - 'rails-app-toby-postgresql'
- namespace - 'toby-myapp-dev'

## Contact person

@TobyRetallick / toby.retallick@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
for now, `$ kubectl --context live-0 -n toby-myapp-dev delete pvc rails-app-toby-postgresql` ; will revisit if it happens again
