### ISSUE TITLE
CPU-Critical work: trivy

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4475]
we have high-priority alerts for CPU spike

https://mojdt.slack.com/archives/C8PF51AT0/p1679477480193049

It may be caused by trivy. 

Investigate the options to reduce the CPU by trivy:

- Separate node group fro trivy
- Single replica
- Upgrading the trivy.

**Comment by sj-williams** [comment]
Following clientServer mode upgrade, continuing to watch trivy resource usage.
CPU load for scans running on image target nodes greatly reduced, and scan jobs are executing far more quickly (typically between ~5 secs - 1 min each).

Bug surfaced in 0.12.1 chart:
https://github.com/aquasecurity/trivy-operator/issues/1078

Has a fix PR in progress

**Comment by AntonyBishop** [comment]
@sj-williams what's the latest on this? Is this still open?
