### ISSUE TITLE
CPU-Critical work: Instance types and number of nodes

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4476]
we have high-priority alerts for CPU spike

https://mojdt.slack.com/archives/C8PF51AT0/p1679477480193049

We need to consider new instance types which can handle more burstable CPU.

Investigate the options to reduce the CPU:

- Instance types which provide more CPU
- More burstable CPU
- Cost of it

Current:
node_groups_count = {
live = "54"
live-2 = "7"
manager = "4"
default = "3"
}

Default node group minimum capacity
default_ng_min_count = {
live = "42"
live-2 = "7"
manager = "4"
default = "2"
}

node_size = {
live = ["r5.xlarge", "r5.2xlarge", "r5a.xlarge"]
live-2 = ["r5.xlarge", "r5.2xlarge", "r5a.xlarge"]
manager = ["m5.xlarge", "m5.2xlarge", "m5a.xlarge"]
default = ["m5.large", "m5.xlarge", "m5a.large"]
}

monitoring_node_size = {
live = ["r4.2xlarge", "r5.2xlarge"]
live-2 = ["r4.2xlarge", "r5.2xlarge"]
manager = ["t3.medium", "t2.medium"]
default = ["t3.medium", "t2.medium"]
}

This ticket is to look into updating the current node types to a more recent gen and bigger nodes which can handle higher CPU requests made by deployments.

Things to consider:
Memory, CPU and max pod count per node/cluster
Node count
Should we change type from memory optimised to general use
Can we update the AMI version to latest when deploying the new node group
An example google sheet used when last looking at node types (This was primarily based of hitting number of pods limit on EKS)

**Comment by jackstockley89** [comment]
Spreadsheet to compare currently cluster instance with alternative options  
https://docs.google.com/spreadsheets/d/1jnTfdUNm9Cs4blaUpyBFvK75UNBS6ZqldMIF7quyoBw/edit#gid=0

**Comment by jackstockley89** [comment]
googlesheets addon for aws pricing 
https://workspace.google.com/u/1/marketplace/app/aws_pricing_by_strake/378787760903

**Comment by jackstockley89** [comment]
Tickets crested for the work to be carried out
