### ISSUE TITLE
Cannot deploy FALA to staging

### ISSUE THREAD

**Issue by rowlando** [ministryofjustice/cloud-platform#448]
## Service name

Find A Legal Adviser

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We cannot release new versions of the FALA application to staging. When this is fixed, we want to immediately deploy to production - will the same error occur?

## Problem description

As a pre-cursor to releasing FALA to production, we deployed to our staging environment. The deploy job was unsuccessful:

https://ci.service.dsd.io/job/DEPLOY-fala/56/console 

## Contact person

Slack: @nick

**Comment by sldblog** [comment]
```
boto3 1.7.74 has requirement botocore<1.11.0,>=1.10.74, but you'll have botocore 1.12.25 which is incompatible.
```

**Comment by razvan-moj** [comment]
fixed by pinning awscli
