### ISSUE TITLE
Check and fix the opensearch ism_policy that moves logs from warm to cold

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#4482]
## Background

Following an incident where warm storage filled up and returned a disk full error, we lost 3 days of logs. Our response to this was to bump the number of warm storage instances from 3 to 5. This leaves us at risk of the alarm being triggered again once these instances disks fill up.

## Approach

Take a look at our opensearch instance and check logs are correctly moving from warm to cold storage.

## Definition of done
Logs correctly move from warm to cold storage

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
Hi @jaskaransarkaria 
Does this fix this problem Jaz?:
This ticket completed  [Fix ISM Policy for cp-live-modsec-audit Opensearch#4578](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4578)
https://logs.cloud-platform.service.justice.gov.uk/_dashboards/app/opensearch_index_management_dashboards#/cold-indices

**Comment by pwyborn** [comment]
Duplicate of ticket [] (pp.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4578)
