### ISSUE TITLE
CPU-Critical work: Visibility of CPU/Memory usage 

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#4491]
During the issue when the AP-Gold application was using up the majority of CPU for a node, we did not have visibility of this.

When using `top nodes` we could see the node was at 100% CPU

However, we did not have visibility of what pod(s) were/was using up all the CPU either via the description of the node which only gives the defaults and limits or via Grafana. We require current usage as opposed to the pod default/limit. 

This ticket is to look into how we monitor and alert when a single pod is using up the majority of CPU or memory of a node. 
Currently we only get an alert when the node is already using 90-95% of the resource for over 10 mins

**Comment by vijay-veeranki** [comment]
closed this as raised a new ticket
https://github.com/ministryofjustice/cloud-platform/issues/4538
