### ISSUE TITLE
Interventions: Auth Dependency SSL Issues

### ISSUE THREAD

**Issue by awhodgson256** [ministryofjustice/cloud-platform#4498]
## Service name

hmpps-interventions-service / Refer and Monitor an Intervention

## Service environment

- [ x] Prod / Production

## Impact on the service

End users are encountering errors on login, due to SSL handshake problems when we call out to auth.  Auth support team say we have successful health endpoint calls, so believe the issue is network related.

## Problem description

We are seeing regular SSL handshake / dependency failures for our call out to auth, particularly in the morning during our service login ramp up (but issues occur less frequently during the day).

EG: multiple failures at 10:19 on 31/03/2023

Auth endpoint in our service is configured as follows

HMPPSAUTH_BASEURL: "https://sign-in.hmpps.service.justice.gov.uk/auth"

We are unsure which cluster is in use...

## Contact person

Andrew Hodgson / @Andrew Hodgson / andrew.hodgson@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
Had a chat with Andrew and got more details of logs.
Getting service dependency errors: https://grafana.live.cloud-platform.service.justice.gov.uk/d/PyQ91ARnk/hmpps-refer-and-monitor-an-intervention?orgId=1&from=1681367084944&to=1681388684944&viewPanel=31

The end users see a 5xx http code and at the same time the app throw SSL Handshake error.
https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover?#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-13T09:58:00.000Z',to:'2023-04-13T09:59:00.000Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'167701b0-f8c0-11ec-b95c-1d65c3682287',key:kubernetes.namespace_name,negate:!f,params:(query:hmpps-interventions-prod),type:phrase),query:(match_phrase:(kubernetes.namespace_name:hmpps-interventions-prod)))),index:'167701b0-f8c0-11ec-b95c-1d65c3682287',interval:auto,query:(language:kuery,query:handshake),sort:!())

Asked for more details of exactly at which step of transaction between services, the end user is getting error? And exaclty at which step of the transaciton the application is throwing the  error.

Will continue debugging.

**Comment by awhodgson256** [comment]
Seems to timeout when our service calls the following endpoint https://sign-in.hmpps.service.justice.gov.uk/auth/api/authuser/[user]/groups

We also have 502 errors, but I think they relate to a separate less frequent fault

**Comment by poornima-krishnasamy** [comment]
While debugging, most of the SSL handshake failure are send to uri `/sent-referral/` with 500
Auth team looking into increasing the replicas to handle the load.

**Comment by poornima-krishnasamy** [comment]
Moving this to blocked until user tests the cross-namespace policy and feedback on the test results.

**Comment by poornima-krishnasamy** [comment]
Hi, Cloud Platform team did a ingress-controller upgrade on 11 July and after that, I dont see the SSL handshake failure from the app. 
kibana link: https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover?#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1w,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'167701b0-f8c0-11ec-b95c-1d65c3682287',key:kubernetes.namespace_name,negate:!f,params:(query:hmpps-interventions-prod),type:phrase),query:(match_phrase:(kubernetes.namespace_name:hmpps-interventions-prod)))),index:'167701b0-f8c0-11ec-b95c-1d65c3682287',interval:auto,query:(language:kuery,query:handshake),sort:!())

Hence, closing this ticket. Feel free to contact us if you experience any issues.
