### ISSUE TITLE
Request to enabling readonly access to API Gateway CloudWatch events

### ISSUE THREAD

**Issue by atharmajeed** [ministryofjustice/cloud-platform#4499]
## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

We are working on a prototype to build an adaptor for Crime Apply and Crime Apps. Unfortunately, we are not able to see the logs for API Gateway. 

## Problem description

Crime Apps is working on a Spike to create a Cognito and API Gateway for JWT token verification. We have managed to create both of these services and looking to enable logging on for these services. However, we are seeing some issues and cannot see any log groups, matrics, etc. 

Having read-only access to CW logs would help further investigate our spike. We have created this web page on Confluence that has much more information about what we are trying to achieve. 

https://dsdmoj.atlassian.net/wiki/spaces/ASLST/pages/4361486738/Creating+Amazon+API+Gateway+and+Cognito+on+Cloud+Platform

We have been talking on Slack Channel and have been told to create a ticket. 
https://mojdt.slack.com/archives/C57UPMZLY/p1680534849818469

## Contact person

@AtharMajeed - athar.majeed@digital.justice.gov.uk
Sriram - sriram.kasthuri@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
hi @atharmajeed , we have enabled Cloudwatch logs to be readable via aws console. Can you please check if you can view the cloudwatch logs of your log group.
Thanks
