### ISSUE TITLE
Setup new domains for track-a-query

### ISSUE THREAD

**Issue by misaka** [ministryofjustice/cloud-platform#450]
## Name of service

track-a-query
correspondence tool staff
answer a question

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [x] Other

## Impact on the service

At worst, the site may be inaccessible to some users (staff) when Google Safe Browsing kicks in.

## Problem description

When Google decides to make browsing safer for users, our site gets blocked by a Big Splash of Red (tm), making it inaccessible to certain staff members.  

This is likely due to our site being hosted at `track-a-query.dsd.io`, and as this service is now past beta assessment and being relied upon by users, a domain change to `service.justice.gov.uk` is appropriate and necessary.

Specifically, at this point I've created DNS records for:

- `track-a-query.service.justice.gov.uk`
- `staging.track-a-query.service.justice.gov.uk`
- `dev.track-a-query.service.justice.gov.uk`
- `demo.track-a-query.service.justice.gov.uk`

And have begun to change the deploy repo to provision the demo environment to the above host. We need to complete the process now.

## Contact person

misha.gorodnitzky@digital.justice.gov.uk
@misha

**Comment by kcbotsh** [comment]
@misaka please redirect this request to domains@digital.justice.gov.uk 
This is not something the team can help with at this time. I will close this ticket

**Comment by misaka** [comment]
Hi @kcbotsh. Just to check my understanding, but I thought that template deploy was something that fell under Cloud Platforms' remit, and that domains@digital.justice.gov.uk was just responsible for creating domains in the DNS zone?

**Comment by kcbotsh** [comment]
Moved back into to do. Clarified with Mischa that this is configuring Template Deploy to point to the new domains using new certificates

**Comment by razvan-moj** [comment]
Working on
https://github.com/ministryofjustice/correspondence-staff-deploy/pull/59
and
https://github.com/ministryofjustice/correspondence-staff-deploy/pull/60

**Comment by razvan-moj** [comment]
merged, https://track-a-query.service.justice.gov.uk is up, any further app changes will not affect this setup
