### ISSUE TITLE
New alert route in Alertmanager

### ISSUE THREAD

**Issue by LucasCairns** [ministryofjustice/cloud-platform#4500]
## Service name

`hmpps-strengths-based-needs-assessments`

## Description

**namespace name:** `hmpps-strengths-based-needs-assessments-dev`
**team name:** HMPPS Assess Risks and Needs
**application name:** `hmpps-strengths-based-needs-assessments`
**slack channel:** `hmpps-strengths-based-needs-assessments-alerts`
**kubernetes secret name where the webhook url is stored:** `slack-webhook-secret`
**severity level (warning/information):** `warning`

## Contact

Lucas Cairns
Slack: `#hmpps-assessments-dev`

**Comment by vijay-veeranki** [comment]
severity = "hmpps-strengths-based-needs-assessments"
