### ISSUE TITLE
Create an Alert/Notification when Node Count goes up or down

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#4505]
Create a Prometheus alert/notification when the cluster autoscaler scales up or down the cluster.

This is to have visibility of changes to the node count and possible issues with resource availability and/or temporary spike in requests.

**Comment by tom-j-smith** [comment]
I have created and tested an alert for prometheus that will trigger whenever it detects a change in the node count. [Github commit here](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/commit/c184ce3cd020fa26e5b2e9f3797a0a12c74016d4)

The alert uses a count on `node_uname_info` which returns how many nodes there are and triggers when it doesnt match the result from the previous minute.

I have tested deploying the alert into a test cluster's Prometheus and tested the rule by scaling up/down the cluster using terraform.

Below are two screenshots of when the alert is triggering and the graph view of when the alert gets triggered:
![changeinnodecount_alert_triggered.png](https://images.zenhubusercontent.com/640f3d5804b2a4a0e862177b/ce64af4c-b48b-46aa-a12f-88c6ca3b06d0)![triggered_changeinnodecount_graph.png](https://images.zenhubusercontent.com/640f3d5804b2a4a0e862177b/1be77ba1-f47f-41d5-833c-0054a0e0d302)

Follow up questions:
- Would we want to notify every time the node count changes? Would this be too much spam?
