### ISSUE TITLE
Review thresholds for when cluster scale down node count

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#4506]
https://github.com/kubernetes/autoscaler

https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler

Review the current threshold for when the cluster scales down node count.
Currently when the cluster scales up during a temp surge in resource request, the cluster very rarely scales back down as the threshold has been set too low. 

One of the reasons for this is daemonsets probably use up more resources than the current threshold to scale down.

**Comment by sj-williams** [comment]
ignore-daemonsets-utilization parameter added to scale-down config
https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler/commit/505a978d6ca49a4ac879d292f5bdf1063794851b
