### ISSUE TITLE
Production: Performance issues on CLA_Frontend

### ISSUE THREAD

**Issue by rowlando** [ministryofjustice/cloud-platform#451]
## Service name

Civil Legal Aid Call Handling System - cla_frontend

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Agilisys reporting that Call Handling System went down for 30 seconds and is now slow.

## Problem description

On first looks, it looks like a production EC2 instance has vanished. This could be why it's slowed down. We did not receive any alerts.

## Contact person

Slack: @nick

**Comment by razvan-moj** [comment]
as discussed in Slack, doesn't seem like an instance count issue as the config has always had just 1; will revisit after feedback from Nick/David
