### ISSUE TITLE
Investigate External Secrets Operator

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4513]
## Background

As part of our exploratory work into leveraging AWS Secrets Manager, we have identified [External Secrets Operator](https://external-secrets.io/v0.8.1/) as a potential solution for managing and rotating Kubernetes secret resources via AWS Secrets Manager.

This project is a new incarnation of a now archived tool [kubernetes-external-secrets](https://github.com/external-secrets/kubernetes-external-secrets) which Cloud Platform spiked previously, see:
https://docs.google.com/document/d/1frGF2ZwVCDly0grWZe5xq1uYO7KzdItRD0LJ1YRZYLI/edit#heading=h.s29pawruln0m
https://docs.google.com/document/d/1qms0Tqtf0j5Cnqjvz0kHNa8dhqMjgR7umgUgTA3VQLI/edit?usp=sharing

We should revisit this so that we can evaluate it and compare its features against Secrets Store CSI Driver.

## Approach

Install operator on test cluster and explore secrets management capabilities.

## Questions / Assumptions

- Can namespace isolation of secrets be achieved?
- How would employing the operator impact how end users consume secrets in their environments?
- What changes would be required regarding creation and lifecycle management of secrets?

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
https://docs.google.com/document/d/1t3FWOZbhkxjwOjd8QG6l4uG6l3Bj9ULFmyY-mNRY5Ew/edit#
