### ISSUE TITLE
Auth JWKS Response Times

### ISSUE THREAD

**Issue by ravmoj** [ministryofjustice/cloud-platform#4518]
## Service name
hmpps-auth

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

While services requesting for jwks file from auth endpoint (GET /auth/.well-known/jwks.json) failed with ReadTimeoutException. ([Slack link](https://mojdt.slack.com/archives/C02S71KUBED/p1682072430848029))
Auth being a central service , it's effecting all dependent services.

## Problem description

Added details to the document.
(https://docs.google.com/document/d/1XR3zbnRNQ7du7PBfWrTClc3hKzmtVn46MHCPZ8hdPV4/edit)

## Contact person
Name: Ravindra Kumar (#hmpps-auth-audit-registers)
email: ravindra.kumar@digital.justice.gov.uk
slack handle:https://mojdt.slack.com/archives/D03D551B9T4

**Comment by poornima-krishnasamy** [comment]
Hi @ravmoj ,

Can you perform few things as mentioned below in order to investigate more on this issue.

1. Are there any additional debug logs in prod auth API services in order to determine whether timeout requests ever actually reach the endpoint?

2. Can you simulate traffic in the non-prod to replicate this error? If you can replicate, you can try the 2 things
    - enable cross-namespace traffic routing between client services and auth endpoint and observe traffic behaviour. You can setup the network policy to connect between 2 services inside the cluster. https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/network-policy.html

 - Temporarily enable access to auth API via default nginx ingress.

**Comment by ravmoj** [comment]
Hi @poornima-krishnasamy ,
Thanks your comments .
Updated starts for last 24 hours in https://dsdmoj.atlassian.net/browse/HAAR-1392
Also as per suggestions : 
https://github.com/ministryofjustice/cloud-platform-environments/pull/12795
https://github.com/ministryofjustice/hmpps-auth/pull/1519

Can you please review cloud platform changes and ngnix ingress changes?
Thank you

**Comment by poornima-krishnasamy** [comment]
Hi @ravmoj , I have added a comment on the PR. Can u please have a look. https://github.com/ministryofjustice/cloud-platform-environments/pull/12795#discussion_r1183938993. 

Thanks

**Comment by poornima-krishnasamy** [comment]
User is testing the networkpolicy to access the services internally. Moving it to blocked until user finishes testing

**Comment by ravmoj** [comment]
Discussed with @poornima-krishnasamy ,

After changing to internal call for 4 services (token-verification-api, hmpps-manage-users-api, hmpps-audit-api and hmpps-manage-users-api )with hmpps-auth, response times of jwks endpoint has improved significantly.

To see whether MOD security has any role in slow response times, disabling it in DEV to test the same

 Other services still taking more response time in DEV.

logged all changes to : https://dsdmoj.atlassian.net/browse/HAAR-1392

**Comment by ravmoj** [comment]
Hi @poornima-krishnasamy , after taking off Mod security from  HMPPS-AUTH service 
Last 24 hours stats shows fewer came under category of 7-15 secs (may be we have to take longer duration to compare)

 
![image](https://github.com/ministryofjustice/cloud-platform/assets/104509282/8df4da33-bcbd-4359-9b2c-b880c2045712)

**Comment by ravmoj** [comment]
144 took more than half sec
Period: 25/05/2023 13:24 to 26/05/2023 13:24
Total request : 5906
144 took more than 5 sec to respond
2.44% request took more than half sec to serve 'GET /auth/.well-known/jwks.json'
9 took more than half sec
Period: 01/06/2023 13:24 to 02/06/2023 13:24
Total request : 4496
9 took more than 5 sec to respond
 0.09% request took more than half sec to serve 'GET /auth/.well-known/jwks.json'

**Comment by ravmoj** [comment]
Stats for one week period:
**With MOD security**
727 took more than half sec
Period: 17/05/2023 08:50  to 24/05/2023 08:50
Total request : 29359
2.4762% request took more than half sec to serve 'GET /auth/.well-known/jwks.json'
17-24/05/2023 :[Go to Log Analytics and run query](https://portal.azure.com/#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fc27cfedb-f5e9-45e6-9642-0fad1a5c94e7%2FresourceGroups%2Fnomisapi-t3-rg%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnomisapi-t3/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA62OvQ6CMBRG9z7FXQyT7e0PFLobVwdeoNEaBGxjW%252BT1lcQwaIyL60nO9x0tNOQQBriG6CB31kNnxzMkdyQHFy%252FhZIArhiUTKCRgbUqEpwHiDZI2ZDtCdLfJpQwGRCPLhgiqdCU2K%252F%252FytSwmF%252B8Oiv2uBWan3DE6u3HcDj7MnvXzkGifgi%252BIwp%252FFkq9xXBu5CICaYfVi0gj1GSxVrQhSrlH%252BM%252FgB2qhEamMBAAA%253D/timespan/2023-05-31T17%3A32%3A32.000Z%2F2023-06-07T12%3A01%3A32.000Z)

**Without ModSecurity**
40 took more than half sec
Period: 31/05/2023 17:30 to 07/06/2023 13:24
Total request : 23484
0.1703% request took more than half sec to serve 'GET /auth/.well-known/jwks.json'
31/05 to 07/06/2023 : [Go to Log Analytics and run query](https://portal.azure.com/#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fc27cfedb-f5e9-45e6-9642-0fad1a5c94e7%2FresourceGroups%2Fnomisapi-t3-rg%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnomisapi-t3/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAz3NvQrCMBSG4d2rOFsVtOniWAdBujmIu8Tkk6ZNzin5IShevJ1cX3h4LRawBRuHtPlSHRFBrAOo76kZLndSuuRRtRXeH2aWymqqc2qnJNz8hS1RZydMp2PXrTWVEHR0H5CRwnm7I6Web1oQXxKDZoNzMTPy3ngp9nETj%252Bs6%252FQF23Hz%252FjgAAAA%253D%253D/timespan/2023-05-17T08%3A50%3A27.000Z%2F2023-05-24T08%3A50%3A27.000Z) (edited)

**Comment by ravmoj** [comment]
Hi @poornima-krishnasamy , thanks for your time. Please let us know next steps , you may require from us to investigate MOD security

**Comment by poornima-krishnasamy** [comment]
Hi @ravmoj , thanks for the investigation. It is clear that the % of requests which has response more that half sec is luch small when using the internal service url and with default ingress controller.

I understand that the modsecurity plays a vital role in processing each request. To rule out the case of bottleneck from modsec ingress controller pods, we will increase the number of replicas of modsec. I will let you know once this is done and lets see the stats for a week if that has improved any.

Alternatively, I would suggest to continue to use internal service url if you want to reduce the 2.4% slow response.

**Comment by poornima-krishnasamy** [comment]
Hi @ravmoj , before I increase the number of replicas, can we take a pre-stats of 
1. When the 2.44% slow response time happening? i.e. the timings of the day
2. What type of call? I am assuming its the GET request? Please confirm
3. Number of rules enabled on the ingress to process any requests to the auth url
4. Stats of any other GET request and response times that are send to Auth url to compare with the jwt.json

**Comment by ravmoj** [comment]
Hi @poornima-krishnasamy , thanks for your time today. 
As discussed will investigate point 4 and get back to u.
it would be great, if you could let us know further findings with respect to modsec.
thanks

**Comment by poornima-krishnasamy** [comment]
Hi @ravmoj , after discussing with yourself and @mattops , its found that on load testing of any endpoint e.g ping from one namespace to another endpoint inside the cluster, there are 2 - 3% slow responses. 
This is happening when the modsec is turned off and the secRuleEngine: Off as well. 

2 options we are planning as next steps:
- CP can try to reproduce the same setup in test environment and see if we can reproduce the problem.
- CP will create a new modsec controller which will allow to point the hmpps-auth to the new controller. That way we can test the configuration changes at the controller level

i will let u know after doing the above

**Comment by poornima-krishnasamy** [comment]
Hi @ravmoj , while doing the load testing with ab on test cluster, I can see the slow responses in general for 1-2% of traffic. Not sure if this is specific to the JWK responses too. I was able to get a better response after increasing the pod replicas.

I think we havent tested this before. Can you please increase the number of replicas of the hmpps-auth pods and observe the responses. 

Thanks,
Poornima.

**Comment by poornima-krishnasamy** [comment]
Also, I have tested with changing the modsecurity configurations by turning off the below but, the % of slow responses are the same. 
SecRuleEngine Off and SecAuditEngine Off. 

So it looks there is no performance changes in terms of modsecurity configuration.

**Comment by poornima-krishnasamy** [comment]
Hi all, I have spun a new modsec controller in live cluster. `modsec-02`. Can you please point any of your non-prod hmpps-auth ingress to the new modsec ingressClass `modsec-02`.

 And also, take some initial numbers on how the performance, % of slow responses etc. Once that is done and recorded, let us know here. The things that are discussed to modify in ingress-controller config
 `SecResponseBodyAccess Off`
`SecAuditEngine Off`
and check the numbers for every change in the config

**Comment by jaskaransarkaria** [comment]
Potential leads around sockets exceeding the kernel limit and being dropped:

https://thanos.live.cloud-platform.service.justice.gov.uk/graph?g0.expr=(node_nf_conntrack_entries%2Fnode_nf_conntrack_entries_limit)%20*%20100&g0.tab=0&g0.stacked=0&g0.range_input=1w&g0.max_source_resolution=0s&g0.deduplicate=1&g0.partial_response=0&g0.store_matches=%5B%5D

https://thanos.live.cloud-platform.service.justice.gov.uk/graph?g0.expr=node_nf_conntrack_stat_drop&g0.tab=0&g0.stacked=0&g0.range_input=1w&g0.max_source_resolution=0s&g0.deduplicate=1&g0.partial_response=0&g0.store_matches=%5B%5D

https://thanos.live.cloud-platform.service.justice.gov.uk/graph?g0.expr=node_nf_conntrack_stat_invalid&g0.tab=0&g0.stacked=0&g0.range_input=1w&g0.max_source_resolution=0s&g0.deduplicate=1&g0.partial_response=0&g0.store_matches=%5B%5D

https://deploy.live/blog/kubernetes-networking-problems-due-to-the-conntrack/

**Comment by ravmoj** [comment]
Without ModSecurity
74 took more than half sec
117 took more than 250 milli seconds 
Period: 11/07/2023 11:00 to 19/07/2023 11:00
Total request : 154743
0.0478 % request took more than half seconds to serve 'GET /auth/.well-known/jwks.json'
0.0756 % request took more than 250 milli seconds  to serve 'GET /auth/.well-known/jwks.json'

[](https://portal.azure.com#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa5ddf257-3b21-4ba9-a28c-ab30f751b383%2FresourceGroups%2Fnomisapi-prod-rg%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnomisapi-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAz2MOw7CMBAF%252B5xiuyRF%252FAEbQxE6hETNBaxkpXzXKLZlgTg8SQq6pxnNa%252FGF1CI1PfrsC6nDBYHsjFDXkN9vT%252BA2ho6zhNNUjeQS8SGNng3eUf4v2rjY0DuCKxy0WLGP82yX%252FoPQuEihKCHjXMrqEac3BAfysq2VgdTKqOOmjQItBMyeoBBMKHMu98gwxtbXVezc6FP5A2k%252Falu3AAAA/timespan/2023-07-11T15%3A00%3A12.000Z%2F2023-07-19T10%3A07%3A12.000Z)
