### ISSUE TITLE
New domains request

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#4520]
## Service name

We are requesting 2 new domains for our production namespaces. Both Route 53 have been created.

Details:

1. domain: `apply-for-criminal-legal-aid.service.justice.gov.uk`
service name: Apply for criminal legal aid
namespace: laa-apply-for-criminal-legal-aid-production
Zone ID: Z096062430VSQ6TQPRK7D

2. domain: `review-criminal-legal-aid.service.justice.gov.uk`
service name: Review criminal legal aid applications
namespace: laa-review-criminal-legal-aid-production
zone ID: Z0366806VB8XM8RMHUIZ

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Contact person

Slack `#laa-crime-apply`

**Comment by vijay-veeranki** [comment]
Completed adding NS records to DSD for apply-for-criminal-legal-aid.service.justice.gov.uk and review-criminal-legal-aid.service.justice.gov.uk
