### ISSUE TITLE
Enable prod check to rds_auto_start_stop

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4521]
We currently have enable_rds_auto_start_stop, which will stop RDs at night and re-start in the morning.

The user requested a prod check so they don't accidentally add this to prod RDs.

https://mojdt.slack.com/archives/C57UPMZLY/p1682679802828519

**Comment by Matt-Alinosn** [comment]
Agreed we won't do at this time.
