### ISSUE TITLE
Create AWS Secrets Manager Module

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4527]
## Background

Create AWS Secrets Manager Module

## Questions / Assumptions

TBC

## Definition of done

- [x] Module created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-secrets-manager
