### ISSUE TITLE
cluster-creation: disable CodePipeline

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#453]
## Background

As agreed, we will disable CodePipeline, work on the various aspect of the cluster creation process and then re-implement the pipeline in Concourse.

For now, we want to disable it to avoid having it run as we make changes to the code.

## Approach

Feel free to leave the pipeline definition in `kubernetes-investigations` around, if you think it might be useful for reference.

## Definition of done

- [x] the pipeline in `CodePipeline`, any associated builds in `CodeBuild` and webhooks have been removed
## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Pipeline removed but code remains in kubernetes-investigation repo.
