### ISSUE TITLE
Add in ability to configure working hours for syscon alert manager route 

### ISSUE THREAD

**Issue by petergphillips** [ministryofjustice/cloud-platform#4532]
## Service name
All our namespaces, so:
- check-my-diary-dev
- check-my-diary-preprod
- check-my-diary-prod
- hmpps-domain-event-logger-dev
- hmpps-domain-event-logger-preprod
- hmpps-domain-event-logger-prod
- hmpps-nomis-mapping-service-dev
- hmpps-nomis-mapping-service-preprod
- hmpps-nomis-mapping-service-prod
- hmpps-prisoner-from-nomis-migration-dev
- hmpps-prisoner-from-nomis-migration-preprod
- hmpps-prisoner-from-nomis-migration-prod
- hmpps-prisoner-to-nomis-update-dev
- hmpps-prisoner-to-nomis-update-preprod
- hmpps-prisoner-to-nomis-update-prod
- hmpps-restricted-patients-api-dev
- hmpps-restricted-patients-api-preprod
- hmpps-restricted-patients-api-prod
- hmpps-restricted-patients-dev
- hmpps-restricted-patients-preprod
- hmpps-restricted-patients-prod
- offender-events-dev
- offender-events-preprod
- offender-events-prod
- prisoner-offender-search-dev
- prisoner-offender-search-preprod
- prisoner-offender-search-prod

## Service environment
- [x] Dev / Development
- [x] Prod / Production

## Impact on the service
See [this](https://mojdt.slack.com/archives/C57UPMZLY/p1683287193993229?thread_ts=1683284836.443909&cid=C57UPMZLY) slack conversation for background.
Further to the email from @jakemulley entitled '[Action recommended] Turn off your non-production Cloud Platform database instances overnight' we have started turning off some of our databases overnight.  This quickly led us to realise that it was a good idea to scale our pods down to 0 during those times otherwise they would fill up our logs with errors during those times.  Unfortunately our prometheus rules still fire overnight so we are getting lots of slack messages due to services being down, messages not being read off queues etc.  This means that a previously fairly quiet alerts channel is now full of messages, which makes it very difficult to see any real issues that are going on.

## Problem description
We can configure prometheus rules for our namespaces, but seem unable to configure the alert manager so that we can set time intervals that the service is active for, or mute intervals that we don't want to be alerted.  

Please can someone investigate how we can set active time periods per alert route / namespace so that alerts are only raised during working hours.

## Contact person
Me or `#syscon-devs` channel in slack

**Comment by poornima-krishnasamy** [comment]
Hi @petergphillips , 
I can see the hmpps-helm-charts has the capability to add alerts during business_hours. https://github.com/ministryofjustice/hmpps-helm-charts/blob/8b70ecd7bf6475de5e3fb110f7dcbf237cab2b70/charts/generic-prometheus-alerts/templates/rules.yaml.

is this still needed?
