### ISSUE TITLE
Enable csi-node-driver in monitoring node group

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4534]
## Background

During the k8s upgrade 1.23, we found that some of the csi-node-driver daemonset of calico-system were not installed in monitoring node group.

To enable daemonset pods into monitoring nodegroup, tolerations needs to be added, e.g. https://github.com/ministryofjustice/cloud-platform-terraform-logging/blob/main/templates/fluent-bit.yaml.tpl#L15-L18

## Proposed user journey

csi-node-driver is optional and need not be required to run on all the nodes. https://github.com/projectcalico/calico/issues/7344
But in order to keep the consistency that all daemonsets run on all nodes, enable csi-node-driver on monitoring nodes

## Approach

csi-node-driver are automatically deployed using tigera-operator. The calico system are managed by installation API and are under `installation`. https://github.com/projectcalico/calico/blob/master/charts/tigera-operator/values.yaml#L3-L5

Update the CSIDriverDaemonset spec using the document: https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.CSINodeDriverDaemonSet in the values file

https://github.com/ministryofjustice/cloud-platform-terraform-tigera-calico/blob/main/templates/values.yaml.tpl#L3-L5

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform-terraform-tigera-calico

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] csi-node-driver installed on monitoring node
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
Blocked - pending reply to issue raised:
https://github.com/projectcalico/calico/issues/7685

**Comment by pwyborn** [comment]
In view of update comments made on issue projectcalico/calico#7685 re new helm release:
Reopening this to try new release on test cluster
https://github.com/projectcalico/calico/issues/7685#issuecomment-1589881154

**Comment by pwyborn** [comment]
https://github.com/projectcalico/calico/issues/7685#issue-1722432938

**Comment by pwyborn** [comment]
Release v3.26.1 has been released - will try this today

**Comment by pwyborn** [comment]
See https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4579
The conclusion of which is:
