### ISSUE TITLE
Request for a new alert route in Alertmanager

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#4537]
# Service name

This webhook will be used to send alerts pertaining to multiple services, but overall the service name can be `Apply for criminal legal aid`.

# Description

namespace name: `laa-apply-for-criminal-legal-aid-staging`
kubernetes secret name where the webhook url is stored: `slack-webhook-secret`

team name: `laa-crime-apply`
application name: Is this the name of the slack app? If so, it is `LAA Crime Apply Alerts`.
slack channel: `#laa-crime-apply-alerts`
severity level (warning/information): `warning`

# Contact

Slack: #laa-crime-apply

**Comment by sj-williams** [comment]
Added alert
