### ISSUE TITLE
Enable CloudTrail in the cloud-platform account

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#454]
## Approach

Enable CloudTrail for all regions and services (does that include Route53?).

## Definition of done

- [x] `CloudTrail` is enabled in the cloud-platform account
- [x] `CloudTrail` configuration is managed in https://github.com/ministryofjustice/cloud-platform-aws-meta-configuration/

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Cloudtrail: cloud-platform-cloudtrail
