### ISSUE TITLE
Check for k8s.gcr.io registry images usage in the Cloud Platform 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4540]
## Background

k8s.gcr.io registry is deprecated and all images in that registry are moved to registry.k8s.io. https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/

Check all Cloud Platform images for any reference to k8s.gcr.io images and take an inventory if any used.
Find the similar image on registry.k8s.io and update the code

## Definition of done

- [ ] Images from k8s.gcr.io are no longer referenced in Cloud Platform
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by Matt-Alinosn** [comment]
1.27 will not be released to old registry
