### ISSUE TITLE
Enable users to be able to restore back-up

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4553]
## Background

We have a restore process but it requires the CP Team to so the last part of the process. This means that the restoration process is difficult out of support hours for end users and can cause some delays in restoring service.

## Proposed user journey

As a Developer I can restore a backup at any time so that I can recover/restore my service without intervention from the Cloud Platform Team.

## Approach

Investigate options to make back up restore more self service.

## Which part of the user docs does this impact

N/A

## Communicate changes

N/A

## Questions / Assumptions

What risks are there to users?
What risk is there to the platform?
What is blocking users being able to do this?

## Definition of done

- [ ] We understand if we can offer users a more self service experience when restoring back-ups.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
The user guide for snapshot restore is mentioned here: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/rds-snapshots.html#3-update-your-current-rds-manifest-file-usually-called-rds-tf-in-the-cloud-platform-environments-repo-to-include-snapshot-identifier-and-raise-the-pr
The area when service team need CP intervention are
- approve snapshot-restore PR
- Pause the pipeline
- Rename RDS instance

- Approve restore PRs: 
Cloud Platform is looking into adding github teams who own the namespace to be CODEOWNERS. This means service teams can approve their own PRs which could be useful when raising PR for backup restore. 

- Pause the pipeline
This is acheived by adding a APPLY_PIPELINE_SKIP_THIS_NAMESPACE file and raising a PR. This PR needs approval from CP and once the above CODEOWNERS and self approval process is implemented

 - Rename RDS instance
Cloud Platform provides service teams to access AWS console to view their resources. This access have permissions to perform ModifyDBInstance to rename the rds. So users can do it themselves
