### ISSUE TITLE
LimitRange: Set Minimum and Maximum Namespace Limits 

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4562]
## Background

Currently, our namespace LimitRange configuration defines `default` limits and requests. We are now aware that this value is only applied to containers which do _not_ specify their own resource requests and limits:

Current configuration:
https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespace-resources-cli-template/02-limitrange.yaml

```
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: {{ .Namespace }}
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1000Mi
    defaultRequest:
      cpu: 10m
      memory: 100Mi
    type: Container
```

In order to apply strict limits for deployment specified resource requests/limits, we need to add `min` and `max` fields to our LimitRange manifest, as described in the docs:

https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace/#attempt-to-create-a-pod-that-exceeds-the-maximum-memory-constraint

## Considerations

It is understood that applying this change will not impact currently running workloads, but _will_ upon pod restarts. It should also deny deployment limit requests which exceed LimitRange limits at point of apply.  This means that we will need to think about how we roll this out across the cluster, as existing deployments with their own limits that exceed those we set will fail upon pod restart.

We could start with create an OPA policy that denies any future deployments from exceeding our intended limits, and roll this out along with comms regarding upcoming LimitRange changes. This would give users a period in which to check their existing deployment limit requests so as to avoid possible failures on pod restarts.

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/reference/namespace-definition-files.html#kubernetes-namespace-definition-files

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference
Links:
https://stackoverflow.com/questions/61356073/relation-between-limitranges-default-defaultrequest-max-and-min-limits

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Current stats of the live cluster: 
https://docs.google.com/spreadsheets/d/1wXBwm5YsEIPZhHh6WwYg6QqdRKFkefb3EzUBDxVb_js/edit?usp=sharing

**Comment by poornima-krishnasamy** [comment]
Looking at the stats for live cluster,

For the requests: it looks many are setting the requests for cpu and memory higher than the limitrange. We have to allow users to set higher requests if required (for example: jobs, startup burstable resource etc). Hence, as a platform we will suggest the recommondations in a report based on the current usage of the app.

**Comment by poornima-krishnasamy** [comment]
Further ticket raised to spike into tools for resource recommondations
https://github.com/ministryofjustice/cloud-platform/issues/4624
https://github.com/ministryofjustice/cloud-platform/issues/4625
