### ISSUE TITLE
OPA Policy: Deny CPU/Mem Namespace Limit Exceeded

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4563]
## Background

Write and deploy an OPA policy to deny creation of new deployments within the cluster exceeding Cloud Platform defined maximum limits for CPU and memory. 

This will allow us to adopt a phased approach to rolling out changes to enforce this via namespace LimitRange configuration and to help avoid unintended pod failures, see ticket:

https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4562

## Approach

- Create and test OPA policy for denial of excessive deployment limit requests.
- Determine what we want those limit values to actually be.
- Communicate upcoming limit changes to users (OPA & LimitRange rollout implications, checks to be carried out), time period before updated LimitRange is deployed.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Blocked: Awaiting shift from OPA to gatekeeper

**Comment by poornima-krishnasamy** [comment]
This ticket is a followup after the limitrange - min, max fields has been introduced to the namespace. https://github.com/ministryofjustice/cloud-platform/issues/4562. As part of that investigation, we found that the resource requests will vary between the pods inside a namespace. And that cannot be controlled by the limitrange. For the resource limits, none of htem are setting a limitrange greater than the one set at namespace.
Revisit after investigating on krr and vpa.
