### ISSUE TITLE
Auth0 deprecating Rules and Hooks - Investigate move to Actions

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4564]
## Background

Auth0 have announced deprecation of the [Hooks and Rules features](https://mojdt.slack.com/archives/C02D2NEF9CJ/p1684311530080069) by 18th November 2024.

We should investigate the implications of these changes and plan what changes are required.

## Approach

There is guidance of moving from the current features to Actions:
- [Migrate from Rules to Actions](https://auth0.com/docs/customize/actions/migrate/migrate-from-rules-to-actions?utm_medium=email&utm_source=mkto&utm_campaign=2023-05-email-rules-hooks-deprecation&mkt_tok=ODU1LVFBSC02OTkAAAGLxUUNt6Z8GdxjRrP3XBsr2Os0DaRf-ptaPql-PPToV8SzYKaYeRohJmjX8mFS6s9C8mO7xIGU-dTLs6X4cOgmgguK6vgOMUmNcN_ZEcc0TYLHLKpC)
- [Migrate from Hooks to Actions](https://auth0.com/docs/customize/actions/migrate/migrate-from-hooks-to-actions?utm_medium=email&utm_source=mkto&utm_campaign=2023-05-email-rules-hooks-deprecation&mkt_tok=ODU1LVFBSC02OTkAAAGLxUUNt6slo7yt-LPvojDz6JfbapF43myYb0rRu_RxmMJaDhBiUbgcEaedaAHfiGdlb9wWBG9H-QuV-KlOMnRkVOBuyhcnHSThn4NRqmPMYlp_ZFI0)

## Which part of the user docs does this impact

N/A

## Communicate changes

N/A

## Questions / Assumptions

- Do these changes break how we use this service or other associated services?
- Are there any other dependancies that need to be addressed to implement these changes?
- Any downtime requirements?
- Do changes impact users/require users to do anything?

## Definition of done

- [ ] We understand what changes are required and can plan move to Actions.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveMarshall** [comment]
@jakemulley and @davidkelliott will look into how AP/MP are going to deal with this, and work out a standard approach for all teams.

**Comment by davidkelliott** [comment]
Done for main org - https://github.com/ministryofjustice/moj-terraform-aws-sso/compare/v2.0.0...main see here for comparison of changes
