### ISSUE TITLE
Dockerhub Pull Investigation

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4574]
## Background

We have been notified by Operations Engineering that Cloud Platform is making, on average, 44,000 Dockerhub pulls per day. This is much higher than expected.

Here is the slack thread - https://mojdt.slack.com/archives/C514ETYJX/p1684848427916879

Docker Pull Request definition - https://docs.docker.com/docker-hub/service-accounts/#how-a-pull-is-defined

Here is some metrics from Docker - https://docs.google.com/spreadsheets/d/1MaJK9byeFxu4VoMCJnnQW6H2m8C3sUenhbRCr2INDDM/edit?usp=sharing

Here is image metrics we created - https://docs.google.com/spreadsheets/d/1_QBfVE5T56MBr0daIIIDVNBMyXe3o-9uyLAHfTnDwXk/edit?usp=sharing

Docker daily image pull data - https://docs.google.com/spreadsheets/d/1_zBAIkmPe1L_gAcocHsoaZxbqwtqf-UAJyHlJKrGMHU/edit?usp=sharing

Longer term we will need to determine a fix, however we currently don't understand what is causing this behaviour. This story is to determine the root cause and identify next steps.

We can call in support from Docker and to help with investigation.

## Which part of the user docs does this impact

N/A

## Communicate changes

N/A

## Questions / Assumptions

TBC

## Definition of done

- [ ] We have a better understanding of what is causing this undesired behaviour.
- [ ] We can determine approach to address this issue.
- [ ] We can create stories for next steps
- [ ] Inform Operations Engineering of outcome/progress

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
AWS Case ID 12908126301

**Comment by sj-williams** [comment]
trivy-operator module now set to image scan _only_ from filesystem (no registry pulls)

https://github.com/ministryofjustice/cloud-platform-terraform-trivy-operator/commit/789a7d955b7b983768deafa400c06de2610fc13e

https://github.com/ministryofjustice/cloud-platform-terraform-trivy-operator/commit/6039b10afab6daa96b457d953bf08374de90f743

**Comment by AntonyBishop** [comment]
Updated stats - https://docs.google.com/spreadsheets/d/1IWM46xALRQzp-yIEWgPlar2a5sZ9QRYIaMWfwvG14Tc/edit?usp=sharing

**Comment by AntonyBishop** [comment]
Awaiting data from Docker

**Comment by jackstockley89** [comment]
Rate limit seems to have dropped below the 5000 requests after the trivy fix implemented, Docker confirmed they are. no longer getting alerts but have not passed any new stats
