### ISSUE TITLE
Fix ISM Policy for cp-live-modsec-audit Opensearch

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4578]
## Background

Modsec audit logs are stored in cp-live-modsec-audit Opensearch cluster. There is a Index State Management Policy to move indices after 14 days to ultra warm and after 30 days to cold storage. Refer code here:

But the indicies are not moved as per the policy and throwing error
```
 Error fetching hot indices. {"error":{"root_cause":[{"type":"security_exception","reason":"_opendistro_security_dls_query does not match (SG 900D)"}],"type":"security_exception","reason":"_opendistro_security_dls_query does not match (SG 900D)"},"status":500}

```

https://logs.cloud-platform.service.justice.gov.uk/_dashboards/app/opensearch_index_management_dashboards#/hot-indices

## Approach

Investigate the error and fix the policy management

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/aws-accounts/cloud-platform-aws/account
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/modsecurity.html#sensitive-logs

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] ISM fixed for cp-live-modsec-audit Opensearch
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-opensearch
https://opensearch.org/docs/2.5/security/configuration/system-indices/

**Comment by pwyborn** [comment]
Issue raised with Opensearch forum:
https://forum.opensearch.org/t/error-message-being-thrown-what-is-sg-900d/14846
![Screenshot 2023-06-28 at 09.06.00.png](https://images.zenhubusercontent.com/5cd14e317c13c23a96974cd5/49843c0a-3019-41bd-996c-893b9793e3b4)

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2318

**Comment by pwyborn** [comment]
Policy - successfully corrected and applied.
The latest 5 policies - correctly attached from config
The rest retrospectively manually attached policy
The indexes appear to be correctly moving between hot/warm and cold (none to be deleted yet - none 366 days old yet)

**Comment by pwyborn** [comment]
Duplicate ticket (https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4482)
