### ISSUE TITLE
Upgrade `terraform-provider-aws` across `cloud-platform-infrastructure`

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/cloud-platform#4580]
## Background

Hashicorp has released [v5.0.0 of `terraform-provider-aws`](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#500-may-25-2023). We need to upgrade `cloud-platform-infrastructure` to use the latest major version of the provider.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by Matt-Alinosn** [comment]
Already moved past 5.0.0
