### ISSUE TITLE
Upgrade `terraform-provider-aws` across `cloud-platform-environments`

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/cloud-platform#4581]
## Background

We need to check the state of terraform-aws-provider versions across all `cloud-platform-environments` and user facing module code and update to use the latest major version of the provider.

As part of this ticket, find all the modules that are affected and needs bumping to latest provider
Create tickets to work on the modules to update to major version

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tmahmood72** [comment]
16 Modules to upgrade:
CloudFront									version = ">= 4.0.0	
Database Migration Service (DMS)	                         version = ">= 4.0.0"
DynamoDB cluster							        version = ">= 4.0.0"							
Elastic Container repository			                         version = ">= 4.0.0"	
ElastiCache for Redis cluster		                                 version = ">= 4.0.0, < 5.0.0"
Kubernetes: IAM role for service accounts (IRSA)																 
                                                                                           version = ">= 4.0.0"		
_Kubernetes: service account__			                        _not applicable_ 
Kubernetes: service pod				                version = ">= 4.0.0"
OpenSearch								        version = ">= 4.0.0"	
_Pushgateway									not applicable_ 
RDS Aurora cluster						                version = ">= 4.0.0"
RDS database instance					                version = ">= 4.0.0"
S3 bucket								        version = ">= 4.0.0"
Secrets Manager							        version = ">= 4.0.0"	
SNS topic									version = ">= 4.0.0"	
SQS queue									version = ">= 4.0.0"	
OpenSearch Cluster						        version = ">= 4.0.0"	
IRSA									        version = ">= 4.0.0"

**Comment by sj-williams** [comment]
Milestone and associated module update tickets created:
https://github.com/ministryofjustice/cloud-platform/milestone/34
