### ISSUE TITLE
Upgrade Velero Module

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4582]
## Background

We are currently running Velero at `v1.9.1` with Helm Chart `2.31.7`

Velero is now at `v1.11` and associated Helm Chart has significant configuration changes:

https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero#upgrading

We should upgrade our Velero deployment and chart to latest available version.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
As of Jan 2024, velero is on version 1.11.1
