### ISSUE TITLE
Use auth0 provider to setup applications on the tenant

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#459]
## Background

We want to manage auth0 tenants using terraform.

## Proposed user journey

Investigate the most viable auth0 provider (most active & feature-rich project on github). Use that to create a new app for the cluster (used for kube auth in the spec and later by kuberos) at cluster creation time.

## Questions / Assumptions
Until now, we've had different tenants per cluster. What felt like a good idea initially now feels like a burden. We do not have a use case that dictates the use of separate tenants and having multiple ones makes it difficult to manage apps.

For this ticket, create a *new* tenant that uses a generic name (eg.: `cloud-platform` if it's available). This tenant will host all our needs for OIDC in the cloud-platform account (separate apps of course).

## Definition of done

- [x] the auth0 app that the cluster uses (see [here](https://github.com/ministryofjustice/kubernetes-investigations/blob/master/kops/cloud-platform-live-0.yaml#L199)) is managed with terraform in https://github.com/ministryofjustice/kubernetes-investigations
- [x] since this is not a 'core' provider, provide short instructions on how to set it up (a link to upstream docs is fine)
- [ ] bonus: if #458 is finished, look into adjusting the template to take advantage of this.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by nayoa** [comment]
https://github.com/yieldr/terraform-provider-auth0

**Comment by jasonBirchall** [comment]
I believe this work has already been carried out - 
https://github.com/ministryofjustice/kubernetes-investigations/tree/master/auth0

**Comment by jasonBirchall** [comment]
- the auth0 app that the cluster uses (see here) is managed with terraform in https://github.com/ministryofjustice/kubernetes-investigations/auth0

- short instructions on how to setup terraform:
https://github.com/ministryofjustice/kubernetes-investigations/auth0/README

- new tenant created for a live env:
https://justice-cloud-platform.eu.auth0.com

**Comment by alkar** [comment]
Some thoughts:

So we have a few different things to manage on auth0:
1. SAML for integrating with AWS
1. cluster app (also used by kuberos)
1. cluster components (eg.: monitoring proxy)
1. other apps (???)

Each has a different lifecycle and I wonder if we should look into managing them separately. For example:
1. Is this something we can manage with tf? If not, do we have documentation on how to set it up? (one-off)
1. Shouldn't this be part of the cloud-platform tf? (once per-cluster)
1. Shouldn't this live as part of the components tf? (once per-cluster most likely)
1. ???
