### ISSUE TITLE
Investigate Route53 rate limit error on external-dns

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4608]
## Background

External-dns errors with [ErrorsInExternalDNS] on lower-priority-alerts channel. While debugging the external-dns logs, the error was shown as below:

```
failed to list resource records sets for zone /hostedzone/Z07210662M8OYJQO6PG1N: Throttling: Rate exceeded\n\tstatus code: 400
```
This alert has been received on all production clusters. live, manager and live-2

Investigate why there are rate limit exceeded error. 

Some questions to answer:
How many api calls are made to Route53 to cause this?
What is the rate limit of AWS? Can it be increased?
Is it because all production clusters can access, checking and requesting all hosted-zone in CP account?
This could be an issue when multiple clusters are requested all hosted zone in one aws account.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] Investigation done and questions answered. Further actions based on the investigation to resolve this alert
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
Only on manager cluster now (in external-dns logs):
```
time="2023-07-02T16:57:51Z" level=error msg="failed to list resource records sets for zone /hostedzone/Z09203692ASE5GNMS3RW0: Throttling: Rate exceeded\n\tstatus code: 400,"
```
```
time="2023-07-03T05:04:25Z" level=error msg="records retrieval failed: failed to list hosted zones: Throttling: Rate exceeded\n\tstatus code: 400"
```

Pointed out to me a lot of test clusters deleted last week (Friday 30th June 2023):
https://mojdt.slack.com/archives/C514ETYJX/p1688139810915509

**Comment by pwyborn** [comment]
https://docs.aws.amazon.com/search/doc-search.html?searchPath=documentation-guide&searchQuery=Frequency%20of%20Amazon%20Route%2053%20API%20requests&this_doc_product=Amazon%20Route%2053&this_doc_guide=Developer%20Guide&facet_doc_product=Amazon%20Route%2053&facet_doc_guide=Developer%20Guide

**Comment by pwyborn** [comment]
https://rtfm.co.ua/en/kubernetes-externaldns-records-retrieval-failed-failed-to-list-hosted-zones-throttling-status-code-400-2/
```
To solve it, add two options – --interval and --events.

In the --interval specify to check for updates once per two minute instead of the default 1 minute, see Parameters, and --events will activate an additional handler of the ExternalDNS which will trigger an API action if an update will be found in Kubernetes Ingress objects.

We are deploying ExternalDNS with Ansible and Helm – update its Ansible task:

- name: "Deploy ExternalDNS chart inside {{ eks_env }}-devops-external-dns-ns namespace (and create it)"
  community.kubernetes.helm:
    kubeconfig: "{{ kube_config_path }}"
    name: "external-dns"
    chart_ref: "bitnami/external-dns"
    release_namespace: "{{ eks_env }}-devops-external-dns-ns"
    create_namespace: true
    values:
      interval: 2m
      triggerLoopOnEvent: true
    ...
Deploy, and now everything is clear.
```

**Comment by pwyborn** [comment]
Looked today -
Throttling messages are back on "Live" (new ones since I last looked) and new ones on "Manager" - nothing on "live-2"

**Comment by poornima-krishnasamy** [comment]
Same as above link where Paul mentioned: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md#throttling. Looking at the chart to see if we can amend the options

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2362
Close for now re-open if throttling issue not so
Checking logs - and #lower-priority-alarms `in:#lower-priority-alarms ErrorsInExternalDNS`

**Comment by pwyborn** [comment]
https://support.console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=13307717171&language=en

**Comment by pwyborn** [comment]
Deleted a lot of orphaned route53 hosted from HOODAW (and other cp-* and yy-*) on Tuesday 18th July

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2381
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2382

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/pull/37/files  for review

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2395
