### ISSUE TITLE
Add google as authentication option for Grafana or public read-only dashboards

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#4619]
## Background

Currently grafana can only be accessed with a GitHub account. We have some team members that would benefit from being able to access some application dashboards with metrics that will help us iterate our product and keep it healthy, but these members don't have GitHub.

PM, DM, BA, user researchers, etc.

We can create a snapshot of a dashboard, but it will not update over time, is just that, frozen in time.

## Proposed user journey

Similar to current Github authentication, there would be a Google one. However we are not really interested in access to all dashboards and to be able to edit them, we are just interested in granting access to individual dashboards as read-only.

## Approach

Maybe but not sure if this would be possible, only dashboards tagged explicitly with something, like "google-account" would be visible when using google as auth method. Just in case allowing google to ALL dashboards opens up too much internal information.
Also, ideally, everything should be read-only.

## Which part of the user docs does this impact

Grafana docs maybe.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Questions / Assumptions

Consider if this is a security risk.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by zheileman** [comment]
An update on this. Apparently, there might be (depending on which grafana’s version we have on CP) already a way to create public dashboards. But I believe the feature needs to be turned on?

https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/

Although not sure if it will be all perfect, seems to be a few limitations currently
https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/#limitations

Particularly worrying the “Template variables are not currently supported, but support is planned in the future.” as we use template variables to select namespace etc from dropdowns.
I suppose we could rework some of these dashboards, if we wanted to make them public, to not use template variables.

**Comment by tom-j-smith** [comment]
https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/

**Comment by jaskaransarkaria** [comment]
It might be worth investigated whether we can tweak the existing ouath2 proxy to add google. This may be as simple as adding google config
