### ISSUE TITLE
Create RDS Postgres Host key / value pair in kubernetes secrets

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#462]
## Service name

Offender Management Allocation API

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

We want to make sure we use Cloud Platform defined secrets where possible, rather than having to alter them and store them in our own secrets.

## Problem description

We've been working on the kubernetes config to hook up one of our rails applications to postgres (via Amazon RDS). We've noticed that the `rds_input_endpoint` contains both the host and the port. We were wondering if it were possible to provide a new key / value pair for the host only e.g. `rds_input_host: [VALUE]`. This will save us from having to store a new value in secrets ...

## Contact person

Toby Retallick / @TobyRetallick

**Comment by nayoa** [comment]
From feedback - It's worth adding the `port` output too
