### ISSUE TITLE
NS record for check-your-client-qualifies-for-legal-aid.service.gov.uk

### ISSUE THREAD

**Issue by patrick-laa** [ministryofjustice/cloud-platform#4621]
## Service name

Check if your client qualifies for legal aid / CCQ / Estimate financial eligibility for legal aid / EFE

## Service environment

Production

## Problem description

Hello, we're following the [documentation](check-your-client-qualifies-for-legal-aid.service.gov.uk) and would like to request an NS record in the DSD account for check-your-client-qualifies-for-legal-aid.service.gov.uk. Thank you!

## Contact person

Patrick - patrick.gleeson@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
laa-estimate-financial-eligibility-for-legal-aid-production, added in https://github.com/ministryofjustice/cloud-platform-environments/pull/14280/files
