### ISSUE TITLE
Spike: Investigate krr to generate report on resource recommendations

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4624]
## Background

Cloud Platform allow users to set different level of resource requests and limits using LimitRange, requests in deployments etc. It would be good to show users some recommendations based on the current usage of the application from a report.

## Proposed user journey

Users would be able to update the correct resource requests based on recommendations

## Approach

There are several ways to acheive that: One on the way is to use tool krr: https://github.com/robusta-dev/krr. This will run inside the cluster, get resource requests and limits from metric server and get the current usage from prometheus. And generate a report.

Export the report to a place(e.g. hoodaw) where users can view and use that for setting up the requests and limits. 

## Which part of the user docs does this impact
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/concepts/namespace-limits.html

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Questions / Assumptions

Is HOODAW the right place to generate this report. Is it ok to expose all these values without any auth?

## Definition of done

- [ ] tool spiked and report generated, demoed to team
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mikebell** [comment]
I don't think this is something we can take forward.

* krr requires cadvisor which requires way too many restricted priveledges, root and access to nodes root filesystems
  *  we could override podsecurity for that namespace but it requires a daemonset across all nodes, we have enough issues with kuberhealthy
* krr requires access to prometheus which is done through oauth, we'd need to figure a work around to that
* the dev effort in getting krr into hoodaw would be quite large
