### ISSUE TITLE
Identify and document unsupported Terraform in use of the Platform

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4632]
## Background

We don't support all AWS resources and we have allowed users to use their own Terraform if they want to use unsupported resources e.g. API Gateway.

However we still end up providing a level of support on these resources which diverts us from the things we should be supporting.

We haven't helped ourselves as we haven't set any guidelines to our users.

So that we can better assess what we should do about this problem we first need to understand the scope of the problems.

This story is to identify what TF is in use on the CP that is not supported.

## Approach

Identify and document what TF is in use that isn't supported. We are need to know what resources are being used and how much i.e. 4 teams have TF for API Gateway.

If would be beneficial to know the Team information as well should we need to do follow up engagement with team.

## Which part of the user docs does this impact

N/A

## Communicate changes

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] Information about unsupported TF
- [ ] We are able to make some decisions around how we want to take this forward.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/add-aws-resources.html#adding-your-own-terraform-to-create-aws-resources
