### ISSUE TITLE
Improve: `apply-live` pipeline failure behaviour

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#4636]
## Background

Currently, the apply-live pipeline runs alphabetically and through each namespace apply the namespace terraform. If the terraform in a namespace fails the pipeline fails and the namespaces which follow do not get their terraform applied. 

## Proposed user journey

When terraform fails do not cause the entire pipeline to fail. Catch the errors and report them when the pipeline finishes running (and maybe into slack too?)

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Covered in this ticket: https://github.com/ministryofjustice/cloud-platform/issues/5270
