### ISSUE TITLE
Disclosure checker production - add alert manager hooks to slack

### ISSUE THREAD

**Issue by lucas-shaw** [ministryofjustice/cloud-platform#4637]
## Service name

disclosure-checker-production

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Use Webhooks Slack app to provide Kubernetes pod issues for Disclosure Checker Production environment.

## Problem description

An alert is needed in AlertManager

Namespace: disclosure-checker-production
Team: Central Digital Product Team
Application name: Disclosure checker
Slack channel: cdpt-disclosure-checker
kubernetes secret name: slackwebhook
severity level: warning

## Contact person

lucas.shaw@digital.justice.gov.uk
cdpt-disclosure-checker

**Comment by poornima-krishnasamy** [comment]
The Alertmanager Route created. Please use the severity `"cdpt-disclosure-checker"` in your prometheus rules
