### ISSUE TITLE
New alert route in AlertManager

### ISSUE THREAD

**Issue by Emterry** [ministryofjustice/cloud-platform#4639]
## Service name

namespace name :  data-platform-app-gold-scorecard-form-dev
team name :  Data Platform
application name : gold-scorecard-form
slack channel :  #analytical-platform-notifications -  The alerts in here however are routed to via pagerduty
kubernetes secret name where the pagerduty information is stored :  gold-scorecard-form-dev-alert-secret
severity level (warning/information) - Warning

## Service environment

- [x ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

This will allow the team to better monitor our applications to address issues quicker and more efficiently for users

## Contact person
Emma Terry

**Comment by poornima-krishnasamy** [comment]
for application specific alerts, we support sending alerts from alertmanager or pingdom to slack channel. So we can setup Alertmanager Route so when a alert is triggered from prometheus, it can be notified to Slack. Similarly, we can integrate pingdom url alerts to send to your slack channel.

Is the current system send alerts from pagerduty to slack? And do u want to change that to Alertmanager to Slack?

**Comment by Emterry** [comment]
currently we manage all our other alerting via pagerduty integrations that then go to a slack channel. It appeared on the cloud platform architecture diagram (https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/prometheus.html#using-the-cloud-platform-monitoring-and-alerting-stack) that alertmanager goes to pagerduty?  is this not the case ?

**Comment by jacobwoffenden** [comment]
Hi @poornima-krishnasamy,

As @Emterry mentioned, PagerDuty is [referenced](https://openmetadata.slack.com/archives/C02AZGN0WKY/p1689099995742899) in Cloud Platform's user guide.

> **AlertManager**
AlertManager handles alerts sent by client applications such as the Prometheus server. It takes care of deduplicating, grouping, and routing them to the correct receiver integration such as **PagerDuty**. It also takes care of the silencing and inhibition of alerts.

In Data Platform, we have chosen PagerDuty as our main alerting system. We do have Slack as an option, but would prefer PagerDuty.

**Comment by pwyborn** [comment]
Hi @@Emterry @jacobwoffenden. Sorry if the guidance is a bit misleading we will revisit the guide to check.

- I think the links that you referenced are general information on what 'AlertManager' is.

- We do not support integration to PagerDuty for Cloud Platform users - only to slack

Would you still like to proceed with integration to Slack please [Creating your own custom alerts](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html)?

- I do notice that the slack webhook referenced in your secrets in your 2 tickets is the same for 2 different slack channels (unless I am looking at the wrong one - please let me know?)
- 
Thanks @pwyborn

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1690284616915079?thread_ts=1689152595.099519&cid=C57UPMZLY

Emma Terry
  30 minutes ago
Hi Paul it was set up last week via a slack channel by a member of your team. There will be further work needed but we are currently on a firebreak sprint I don’t think there is anything  outstanding on that raised issue now





Paul Wyborn
  8 minutes ago
Ok - 
@Emma Terry
 Emma :+1: tickets not updated - that is the case for both of these requests? (edited) 





Paul Wyborn
  2 minutes ago
I will close them
