### ISSUE TITLE
Parliamentary questions production - add alert manager hooks to slack

### ISSUE THREAD

**Issue by lucas-shaw** [ministryofjustice/cloud-platform#4640]
## Service name

parliamentary-questions-production

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Use Webhooks for Slack channel to provide Kubernetes pod issues for parliamentary questions production environment.

## Problem description

Namespace: parliamentary-questions-production
Team: Central Digital Product Team
Application name: Parliamentary Questions
Slack channel: cdpt-pqtracker
kubernetes secret name: slackwebhook
severity level: warning

## Contact person

lucas.shaw@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
The Alertmanager Route created. Please use the severity `"parliamentary-questions"` in your prometheus rules
