### ISSUE TITLE
Contact MOJ - add alert manager hooks to Slack

### ISSUE THREAD

**Issue by lucas-shaw** [ministryofjustice/cloud-platform#4641]
## Service name

Contact MOJ 

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Use Webhooks for Slack channel to provide Kubernetes pod issues for Contact MOJ production environment.

## Problem description

Namespace: contact-moj-production
Team: Central Digital Product Team
Application name: Contact MOJ
Slack channel: cdpt-ask-a-question-public-tool
kubernetes secret name: slackwebhook
severity level: warning

## Contact person

lucas.shaw@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
The Alertmanager Route created. Please use the severity `"contact-moj"` in your prometheus rules
