### ISSUE TITLE
Family Mediators API - add alert manager hooks to Slack

### ISSUE THREAD

**Issue by lucas-shaw** [ministryofjustice/cloud-platform#4643]
## Service name

Family Mediators API

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service
Use Webhooks for Slack channel to provide Kubernetes pod issues for Family Mediators API production environment.

## Problem description
Namespace: family-mediators-api-production
Team: Central Digital Product Team
Application name: Family Mediators API
Slack channel: cdpt-family-mediators-api
kubernetes secret name: slackwebhook
severity level: warning

## Contact person
lucas.shaw@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
The Alertmanager Route created. Please use the severity `"family-mediators-api"` in your prometheus rules
