### ISSUE TITLE
slack channel for alertmanager

### ISSUE THREAD

**Issue by Emterry** [ministryofjustice/cloud-platform#4654]
## Prometheus Alert

namespace name : data-platform-app-gold-scorecard-form-dev
team name : Data Platform
application name : gold-scorecard-form
slack channel : #data-platform-application-migration-alerts 
kubernetes secret name where the webhook url is stored: gold-scorecard-form-dev-alert-secret
severity level (warning/information) - Warning

## Service environment

- [x ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

This will allow the team to better monitor our applications to address issues quicker and more efficiently for users

## Contact person

Emma Terry

**Comment by pwyborn** [comment]
Hi @Emterry @jacobwoffenden. Sorry if the guidance is a bit misleading we will revisit the guide to check.

- I think the links that you referenced are general information on what 'AlertManager' is.

- We do not support integration to PagerDuty for Cloud Platform users - only to slack.

Would you still like to proceed with integration to Slack please [Creating your own custom alerts](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html)?

- I do notice that the slack webhook referenced in your secrets in your 2 tickets is the same for 2 different slack channels (unless I am looking at the wrong one - please let me know?).

Thanks @pwyborn

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1690284616915079?thread_ts=1689152595.099519&cid=C57UPMZLY

Emma Terry
  30 minutes ago
Hi Paul it was set up last week via a slack channel by a member of your team. There will be further work needed but we are currently on a firebreak sprint I don’t think there is anything  outstanding on that raised issue now





Paul Wyborn
  8 minutes ago
Ok - 
@Emma Terry
 Emma :+1: tickets not updated - that is the case for both of these requests? (edited) 





Paul Wyborn
  2 minutes ago
I will close them
