### ISSUE TITLE
Identify Components that require upgrade as a result of EKS upgrade

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4663]
## Background

We need to identify which components need to be upgrade to align with Kubernetes 1.24.

The purpose of this story is to identify the components that require and upgrade to work with 1.24 and above.

## Approach

Make a list and write a story for each component upgrade

## Which part of the user docs does this impact

Update the runbook - https://runbooks.cloud-platform.service.justice.gov.uk/components-versions.html#components-versions

## Communicate changes

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] We know which components will require an upgrade

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
Put this back for the time being, as other tickets more pressing

**Comment by AntonyBishop** [comment]
Aged out
