### ISSUE TITLE
New Pingdom integration request

### ISSUE THREAD

**Issue by AndySweilam** [ministryofjustice/cloud-platform#4666]
## Team Name:
manage-a-workforce

## Application name
workforce-management-prod

## Slack Channel for alerts:
#manage_a_workforce_dev

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X ] Prod / Production
- [ ] Other

## Impact on the service
No Impact.

## Problem description

Creating a new pingdom terraform file for the allocations tool. We need the [integrationids] to create the pingdom file. This is required to provide a metrics request.

## Contact person

Andy Sweilam.

**Comment by sj-williams** [comment]
integration name:
workforce-management-prod-allocation-tool

id:
130615
