### ISSUE TITLE
EKS add-ons upgrade

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4667]
## Background

As post k8s 1.24 upgrade, we need to bump to latest supported versions of eks add-ons:

- coredns
- vpc cni
- kube-proxy

## COREDNS
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-43b80e04-7fff-7232-b507-eea70a3f097b"><div dir="ltr" style="margin-left:0pt;" align="left">

Kubernetes version | 1.27 | 1.26 | 1.25 | 1.24 | 1.23
-- | -- | -- | -- | -- | --
  | v1.10.1-eksbuild.2 | v1.9.3-eksbuild.5 | v1.9.3-eksbuild.5 | v1.9.3-eksbuild.5 | v1.8.7-eksbuild.7

</div></b>

## VPC CNI
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-d7fe114f-7fff-7ff9-d5ea-c227a8080a76"><div dir="ltr" style="margin-left:0pt;" align="left">

Kubernetes version | 1.27 | 1.26 | 1.25 | 1.24 | 1.23
-- | -- | -- | -- | -- | --
Amazon EKS type of VPC CNI version | v1.13.2-eksbuild.1 | v1.13.2-eksbuild.1 | v1.13.2-eksbuild.1 | v1.13.2-eksbuild.1 | v1.13.2-eksbuild.1

</div></b>

## kube-proxy
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-dd1fa09f-7fff-0051-894e-f53fe14d8752"><div dir="ltr" style="margin-left:0pt;" align="left">

Image type | 1.27 | 1.26 | 1.25 | 1.24 | 1.23
-- | -- | -- | -- | -- | --
kube-proxy (default type) | Only minimal type is available | Only minimal type is available | Only minimal type is available | v1.24.10-eksbuild.2 | v1.23.16-eksbuild.2
kube-proxy (minimal type) | v1.27.1-minimal-eksbuild.1 | v1.26.2-minimal-eksbuild.1 | v1.25.6-minimal-eksbuild.2 | v1.24.10-minimal-eksbuild.1 | v1.23.16-minimal-eksbuild.2

</div></b>

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
coredns upgrade PR : https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2370
vpc-cni upgrade PR:  https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2376

**Comment by poornima-krishnasamy** [comment]
kube-proxy upgrade step 1 https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2378:

**Comment by poornima-krishnasamy** [comment]
kube-proxy upgrade step 2: https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2392

Version `v1.24.15-eksbuild.1` is hte latest but not the default. The image used in the kube-proxy is the kube-proxy:v1.24.15-minimal.
