### ISSUE TITLE
Scale services from CloudWatch metrics

### ISSUE THREAD

**Issue by ben-cart3r** [ministryofjustice/cloud-platform#4679]
## Service name

hmpps-electronic-monitoring
(the service doesn't exist yet but will likely be within this namespace)

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

N/A

We'd like to be able to scale a service based on the size of an SQS queue. This seems to be possible and is described in this AWS [article](https://aws.amazon.com/blogs/compute/scaling-kubernetes-deployments-with-amazon-cloudwatch-metrics/).

A possible use case:

1. File is uploaded to S3
2. ObjectCreated event is published to a SQS queue
3. The HorizontalPodAutoscaler scales the service in response to the `AWS/SQS/ApproximateNumberOfMessagesVisible` metric
4. As more pods are added to the service, each container will receive a message (or batch of messages) from the queue (using boto3 or similar) and process the relevant file
5. After the file is processed the message is deleted from the queue
6. As the queue empties, the HPA will scale down the service.

I realise there may be some problems, specifically not being able to determine the pods being terminated as the metric falls below the threshold which would stop the processing of a file prematurely.

I haven't fully thought this through but I thought it could be an interesting pattern to explore anyway. (I also know there are existing SQS pattens but they're not ephemeral).

## Contact person

ben.carter@justice.gov.uk

**Comment by timckt** [comment]
https://docs.google.com/document/d/1DT_VTPLIV1-A3NdJfmqYYnBnNhzWCv8hE0Tbht6WoQM/edit

The above document is the insight and high level summary to enable scaling the services according to the SQS queue.
