### ISSUE TITLE
Nginx Default Backend Issue

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#4691]
If you browse to a an invalid apps.* URL you are not redirected to the default backend

e.g. https://asjdhak.apps.live.cloud-platform.service.justice.gov.uk/

Look into our other domains and see if we have the same issue, the differences and find root cause. 

Need to look into how to avoid this happening again

**Comment by pwyborn** [comment]
Contact us seems to link to:
find-unclaimed-court-money-production

**Comment by pwyborn** [comment]
Note to me:
It has come to light that for “.apps” and “.live…) route 53 is routing to this:
a77370a09d8684f74bf8751253a40dc0-6c06823e856bebac.elb.eu-west-2.amazonaws.com
example https://asjdhak.apps.live.cloud-platform.service.justice.gov.uk/
I see that other load balancers route to “service not available”
as in https://a55afa3f5f5eb45c895e1f6175638f67-20fe843f3979a08a.elb.eu-west-2.amazonaws.com/
Do you know did we ever have a dedicated page referencing “cloud platform + a contact” or was it “service unavailable” as in my example?

**Comment by pwyborn** [comment]
Look at external_dns has this affected it?
To eliminate revert back to v1.11.0?

**Comment by pwyborn** [comment]
No issues since - will therefore close
