### ISSUE TITLE
Add ingress clarification about why apps don't need to be public facing

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#4711]
## Background

Users seem to be confused about apps being publically facing and what the role of ingresses are. Clarify this in the user docs

see here https://mojdt.slack.com/archives/C57UPMZLY/p1692291815961779

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mikebell** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/1629

**Comment by mikebell** [comment]
Page is now live.
