### ISSUE TITLE
slack webhook secret for laa-not-on-libra-auto-search-application-prd

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/cloud-platform#4726]
## Service name

laa-not-on-libra-auto-search-application-prd

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

This is required for custom alerts to slack.

## Problem description

namespace name - laa-not-on-libra-auto-search-application-prd
team name - LAA Ops
application name - not-on-libra-auto-search-application
slack channel - #cp-laa-alerts-nolasa-prod
kubernetes secret name where the webhook url is stored -  webhook-for-laa-not-on-libra-auto-search-application-prd
severity level (warning/information) - warning

## Contact person

@mikereid
mike.reid@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
Severity:  not-on-libra-auto-search-application-prod
