### ISSUE TITLE
Wrong env variables in template deploy env

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#473]
## Service name

moving-people-safely

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description

From @cesidio (in slack):

some time ago I asked for a PR to our moving-people-safely-deploy to be reviewed, merged and do highstate

this was the PR

https://github.com/ministryofjustice/moving-people-safely-deploy/commit/c0b41e44f013c77cb0432d080dff91910c2fd2f3

it was about changing an env variable for staging environment
but when I ssh into staging server

and do

```env |grep MOJSSO_URL
MOJSSO_URL=https://www.signon.dsd.io/```

I still see the old value
I should see

```env |grep MOJSSO_URL
MOJSSO_URL=https://staging.signon.service.justice.gov.uk/```

can you please help on that? thanks 

## Contact person

<!-- Name, slack handle, email address of the person we can contact for further information. -->

@cesidio in slack.

**Comment by pwyborn** [comment]
Summary:
What this in fact needed was a fab update following the merge to master - to update the docker env variables. The Jenkins job does not do this
