### ISSUE TITLE
Create Sentry project for FALA staging

### ISSUE THREAD

**Issue by rowlando** [ministryofjustice/cloud-platform#474]
## Service name

Find A Legal Adviser (FALA)

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

No impact on the service as this is about setting up Sentry for our staging environment.

## Problem description

I'm updating the Sentry configuration for FALA and I need to be able to test in staging that I've not broken anything before pushing the changes to production.

There's a team called "Find a Legal Adviser - FALA". We need a Sentry project set up under this called "[staging] FALA". Please provide the project's DSN when complete.

## Contact person

Slack: @nick

**Comment by pwyborn** [comment]
paulwyborn [4:56 PM] 30/10/2018
Hi @nick - have pull request for sentry staging dsn for merger https://github.com/ministryofjustice/fala-deploy/pull/30. Have also set up staging on sentry.
