### ISSUE TITLE
Slack Webhook for laa-not-on-libra-auto-search-application-tst

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/cloud-platform#4742]
## Service name

laa-not-on-libra-auto-search-application-tst

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [x] Other

## Impact on the service

Required for the move of the above application from LAA LZ to Cloud Platform.

## Problem description

We are planning to move this environment to Cloud Platform over the next two weeks and slack alerting is required for us to complete it.

## Contact person

Michael Reid
mike.reid@digital.justice.gov.uk
Slack - @mikereid

**Comment by poornima-krishnasamy** [comment]
Discussed with Michael Reid to use the existing non-prod route
Severity: not-on-libra-auto-search-application
Slack channel: #cp-laa-alerts-nolasa-non-prod
