### ISSUE TITLE
Slack Webhook for laa-not-on-libra-auto-search-application-preprod

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/cloud-platform#4743]
## Service name

laa-not-on-libra-auto-search-application-preprod

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Required for the move of the above application from LAA LZ to Cloud Platform.

## Problem description

We are planning to move this environment to Cloud Platform over the next two weeks and slack alerting is required for us to complete it.

## Contact person

Michael Reid
[mike.reid@digital.justice.gov.uk](mailto:mike.reid@digital.justice.gov.uk)
Slack - @MikeReid

**Comment by poornima-krishnasamy** [comment]
New route added.
Severity: not-on-libra-auto-search-application
Slack channel: #cp-laa-alerts-nolasa-non-prod
