### ISSUE TITLE
Ensure all EKS Add-ons are the latest versions for 1.24 and able to support upgrade to 1.25

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4744]
**Background**

Ensure all EKS Add-ons are the latest versions for 1.24 and able to support upgrade to 1.25

Definition of Done

- [x] All add-ons reviewed
- [x] All add-ons are supported in 1.24
- [ ] All add-ons will work with 1.25
- [ ] Stories raised for any remediation work

**Comment by sablumiah** [comment]
github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons

#4667
