### ISSUE TITLE
Fix Low Priority Alerts

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4746]
## Background

He have a backlog of low priority alarms that need investigation.

## Approach

Investigate an fix low priority alarms

## Definition of done

- [ ] Less alarms/unresolved issues in low priority

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Closing this as individual tickets will be raised for every alert received in lower-priority-alarms channel
