### ISSUE TITLE
Decommission Live 2

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4747]
## Background

We have a Live-2 cluster that is not being used. Decommission as one less cluster to maintain, and reduce cost.

## Approach

Decommission Live-2 cluster

## Definition of done

- [ ] We no longer have a live 2 cluster

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Team would like to revisit re-purposing Live-2 as a test cluster. It was used are part of EKS module testing and had some value. It is also a test cluster that is fully managed via pipelines. To be discussed.

**Comment by Matt-Alinosn** [comment]
Agreed to close ticket and keep cluster as eng used by team.
