### ISSUE TITLE
Kubernetes 1.25 Upgrade Communication

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4748]
## Background

There are significant user impacting changes involved in the 1.25 upgrade. We need to communicate these changes so that users know what is expected for the 1.25 upgrade, and so that their applications are not negatively impacted.

## Approach

There are lots of things we need to communicate:
1. The over plan and timeline
2. Any user specific milestones
3. Details of changes that service teams need to make
4. Needs to include Service Account messages about not using yaml files and clean up of yaml files

## Which part of the user docs does this impact

TBC

## Communicate changes

TBC

## Questions / Assumptions

Questions:
- Do we need content for inclusion in the user guide?

Assumptions:
- We have completed all testing and identified all user impacting changes.

## Definition of done

- [ ] We can communication that we can issue to users.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Depends on: #4749, #4752

**Comment by poornima-krishnasamy** [comment]
Need to send a updated comms to cover the serviceAccount migration from yaml to terraform as part of 1.24 upgrade

**Comment by poornima-krishnasamy** [comment]
Closing this.
Seperate ticket created for serviceaccount migration from yaml to terraform: https://github.com/ministryofjustice/cloud-platform/issues/4837
