### ISSUE TITLE
Check for all changes on 1.25 for compatibility with our code/clusters

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4749]
## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
- Check changelog for changes to the kubernetes when moving to 1.25. i.e any infrastructure change
- Run a tf plan and check if the cluster work, integration test pass and apps run ok

Based on the testing, find if this needs breaking down
