### ISSUE TITLE
Deploy PVB2 Staging (Jenkins)

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#475]
## Service name
Prison Visits Booking

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Cannot deploy PVB2 to staging
## Problem description

https://ci.service.dsd.io/view/PVB2/job/deploy-pvb2-staging/238/console

Deploy job fails with
```
Encountered error pulling tutum/cleanup:latest: Error 500: {"message":"Get https://registry-1.docker.io/v2/tutum/cleanup/manifests/latest: received unexpected HTTP status: 503 Service Unavailable"}
```

## Contact person

@TobyRetallick

**Comment by razvan-moj** [comment]
hi - was a docker.io temporary issue, now green
