### ISSUE TITLE
Review change in 1.26, 1.27 and 1.28

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4751]
**Background**

The 1.25 includes a number of user impacting changes. To minimise the impact on end users we want to take a forward look at any other changes relating to future upgrades that may also include changes we need users to make to their applications.

**Approach**

Review change log and upgrade notes for 1.26, 1.27 and 1.28 for any user impacting changes.

**Definition of Done**

- [ ] We have identified other changes that may be user impacting from these version upgrades to include in 1.25 upgrade comms.

**Comment by tom-j-smith** [comment]
Document of major changes from 1.26 to 1.28 - https://docs.google.com/spreadsheets/d/1oBepddNAdG7-ai8H2VrloRDfsXPTPSHGEdwxEksQDxg

**Comment by tom-j-smith** [comment]
Reviewed by Poornima - Apart from the hpa, we dont have any to inform iusers
