### ISSUE TITLE
Check what APIs teams are are using (the deprecated ones)

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4752]
## Background

This story is to identify user impacting changes.

## Definition of done

- [ ] List of services with deprecated APIs and versions

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
https://docs.google.com/spreadsheets/d/1LUzlfRpIa3G7ok83lx3b8vtwqkuPc6zVRgxFAS6PPyg/edit#gid=1506107570
