### ISSUE TITLE
Update upgrade runbooks

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4754]
## Background

We need a reliable runbook that we can use to support upgrade word. 

## Approach

Update the runbook ready for the upgrade. This will be based on all our testing and other research.

## Which part of the user docs does this impact

https://runbooks.cloud-platform.service.justice.gov.uk/upgrade-eks-cluster.html

## Questions / Assumptions

N/A

## Definition of done

- [ ] Runbook fit for purpose for whoever will carry out the upgrade work.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Post 1.25 upgrade testing, any changes to steps or procedures.

**Comment by poornima-krishnasamy** [comment]
Include the below to the runbook update
As part of recent EKS module upgrade changes, update the runbook to include the below things to check

- Compare launch template before and after the upgrade and check for any variable changes
- Check for disk space, Ip subnet and IP allocations changes using cni logs
- Check if the rds or any aws resource bound to vpc can be connected
