### ISSUE TITLE
Recover mojdsd AWS access

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#476]
## Problem description

I think my credentials expired or have been removed.
I need to get access to **mojdsd** AWS console and specifically access to Amazon SES, in order to be able to monitor and configure SES for `Family Justice C100 application`.

Thank you.

## Contact person

Jesus @ slack

**Comment by nayoa** [comment]
Password reset. 
After discussion with @sid234 we have decided to add the Full SES policy to the Developers group. This will be revisited to ensure the correct level of SES access is available to developers.

**Comment by nayoa** [comment]
Note: In order to use SES, SNS is required. Therefore, SNS has also been added to developers group
