### ISSUE TITLE
FIREBREAK: Spike weave-gitops

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4765]
## Background

We previously explored flux2 and decided to implement it in the cluster. The flux2 has one missing component a UI to see the code getting applied to the namespace. 
https://github.com/weaveworks/weave-gitops

Spike weave-gitops and see if that can be integrated with flux system and be a UI to view the controller and the namespace getting applied from source code

## Questions / Assumptions

To work on this ticket, u will need flux already installed. So this can be done after: https://github.com/ministryofjustice/cloud-platform/issues/3887. Or install flux with cli.

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Does next steps require User Research?
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by mikebell** [comment]
Findings - https://docs.google.com/document/d/1scv4mN-J7mlQKdVj7KGcFdq1zN6WF1N2zxBFdXQWA-o/edit?usp=sharing

Overall Weave isn't powerful for our needs.
