### ISSUE TITLE
Tweak alarm: Fluentbit  OOMKilled

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#4767]
## Background

Currently, the alert is failing to resolve, even though the pod is fine. This is because the alert checks the last terminated status, It should also validate that the pod is not continuing to be OOM killed

https://alertmanager.live.cloud-platform.service.justice.gov.uk/#/alerts?receiver=slack-warning

**Comment by pwyborn** [comment]
See
https://mojdt.slack.com/archives/C8QR5FQRX/p1698370033707739
