### ISSUE TITLE
Claim-criminal-injuries request for a new alert route in Alertmanager

### ISSUE THREAD

**Issue by BarryPiccinni** [ministryofjustice/cloud-platform#4769]
## Service name

claim-criminal-injuries-compensation-prod

## Service environment

- [    ] Dev / Development
- [    ] Staging
- [ x ] Prod / Production
- [    ] Other

## Problem description

Currently we have a shared channel for all our alerts and it can be very noisy due to work in our dev environments. I've added a new channel specifically for Production alerts ping to.

namespace name: 
> claim-criminal-injuries-compensation-prod

team name: 
> Cica dev team

slack channel: 
> cica-prod-alerts

kubernetes secret name where the webhook url is stored: 
> collection name: shared-secrets
> secret name: webhook_prod_alerts_slack

severity level (warning/information):
> Warning

## Contact person

Barry Piccinni

**Comment by poornima-krishnasamy** [comment]
The AlertManager Route has been created. Please use the severity `claim-criminal-injuries-compensation-prod`
