### ISSUE TITLE
Our default node group is using gp2 for disk storage upgrade to gp3

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#4773]
## Background

We should upgrade to the latest disk and benefit from increased performance for our default node group

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html

https://github.com/awslabs/aws-support-tools/tree/master/EBS/VolumeLimitCalculator

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Completed : https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2657
