### ISSUE TITLE
Deleted cron job firing

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#478]
## Service name

Prison Visits Booking (PVB2)

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Receiving errors on Sentry - a cron job is firing which has previously been deleted. The cron job is trying to execute a rake task which has also since been deleted.

## Problem description

Since yesterday, a previously deleted cron job has been firing.
`docker exec pvb_sidekiq bash -c 'RAILS_ENV=production rake pvb:email_slot_availability'`

Kibana log: https://dsd-kibana.apps.cloud-platform-live-0.k8s.integration.dsd.io/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T04:00:00.000Z',mode:absolute,to:'2018-11-01T04:00:10.000Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:f743b2c0-102a-11e8-8051-835cfbcbba58,key:'@project',negate:!f,params:(query:pvb,type:phrase),type:phrase,value:pvb),query:(match:('@project':(query:pvb,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:f743b2c0-102a-11e8-8051-835cfbcbba58,key:'@environment',negate:!f,params:(query:prod,type:phrase),type:phrase,value:prod),query:(match:('@environment':(query:prod,type:phrase))))),index:f743b2c0-102a-11e8-8051-835cfbcbba58,interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc))

Sentry: https://sentry.service.dsd.io/mojds/pvb2-prod/issues/33764/?referrer=slack

We tried running a fab update on pvb2 production again which completed, but the old cron job still appears to be there.

## Contact person

Toby Retalllick / @TobyRetallick

**Comment by razvan-moj** [comment]
Cronjobs gone after fab+jenkins. Root cause: the untrapped broken Salt highstate applied an old copy of the repo.
