### ISSUE TITLE
Spike: Can you change the existing private subnet of live-1  to include more ip addresses

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4780]
## Background

As a result of ENI prefix limits issue encountered during EKS Module v18 upgrade work, we need to explore better ways of allocating and managing ip addresses within Cloud Platform VPC.

The live-1 vpc has a CIDR range of 172.20.0.0/16 which can provision 65k IP addresses. But the live-1 private subnet configuration only provides around 8k ipaddress e.g existing private subnet 172.20.32.0/19. 

When the live cluster scales up to many nodes, we see the below error in cni ipamd logs

```“Unable to get IP address from CIDR: no free IP available in the prefix```
and the pods event logs has```"failed to assign an IP address to container" ``` error

## Approach

Are we managing the subnet provision from the vpc cidr range efficiently?

https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/main.tf#L45-L75

- Can the range be modified
- Can more subnects be added to that region
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/main.tf#L45-L75

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Questions / Assumptions

- Does the subnet modification needs recreating?
- Does the route table is updated and all aws resources can be connected to the new range of subnet 

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by prakash-moj** [comment]
@poornima-krishnasamy - Given the VPC CIDR range, we can add more private subnets and allocate them fully for EKS worker nodes if that's preferred approach.


```
(env) ➜ terraform console
> cidrsubnet("172.20.0.0/16", 3,4)
"172.20.128.0/19"
> cidrsubnet("172.20.0.0/16", 3,5)
"172.20.160.0/19"
> cidrsubnet("172.20.0.0/16", 3,6)
"172.20.192.0/19"
>  

```

**Comment by prakash-moj** [comment]
Possible steps

1) Add 3 private additional subnets
2) Associate new private subnets with CIDR reservations which can be used for IP Prefixes
3) Update existing security groups with additional subnet ranges before switching EKS worker nodes.
4) Manually change the cluster to include additional PRIVATE subnets. Updating through terraform tried to recreate the cluster which we don't want to.
5) Make sure all existing security groups rules reflecting the new PRIVATE subnets.
6) Apply subnet changes on EKS node group to replace existing nodes with new PRIVATE subnets.


PR Covers 1 & 2

https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2634

@sj-williams - FYI

**Comment by sj-williams** [comment]
This is no longer relevant, as we have completed the work to increase prefix capacity here:
https://github.com/ministryofjustice/cloud-platform/issues/6030
