### ISSUE TITLE
Create staging LB env for CLA

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#479]
## Service name

CLA public

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

none for now, just staging

## Problem description

We need an instance of ALB+HAproxy as described in https://github.com/ministryofjustice/kubernetes-investigations/tree/master/haproxy, fronting the staging URLs of the CLA app, namely
staging-public.cla.dsd.io
and
laa-cla-public-staging.apps.cloud-platform-live-0.k8s.integration.dsd.io

The setup needs to run in the DSD account, as that has the Route53 zone.
Terraform will need a state S3 bucket, and will create DNS/ACM/ASG/ALB/EC2/Cloudwatch alarms

Users will need SSH access to the instances, this is in the tf output

The example built in the "chaos" account can be deleted

## Contact person

Nick/David/Anna

**Comment by razvan-moj** [comment]
The example in kubernetes-investigations is not the most complete right now and should be changed to match https://github.com/ministryofjustice/correspondence-staff-deploy/tree/master/tf-alb as that one has multiple hostnames and SNS

**Comment by jasonBirchall** [comment]
Traffic split 80/20.
checklegalaid.staging.service.justice.gov.uk
