### ISSUE TITLE
claim-criminal-injuries New alert manager route

### ISSUE THREAD

**Issue by BarryPiccinni** [ministryofjustice/cloud-platform#4797]
## Service name

CICA online application service

## Service environment

- [ X ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

New alert required in our channel.

## Problem description

We require an informational alert. Currently all our other custom severity alerts are warnings. Info:

 - namespace name: claim-criminal-injuries-compensation-dev
 - team name: cica-dev-team
 - application name: claim-criminal-injuries-compensation-dev
 - slack channel: cica_inf_alerts
 - kubernetes secret name where the webhook url is stored:
 - - secret name: shared-secrets
 - - secret key: webhook_dev_reporter_slack
 - severity level (warning/information): information

## Contact person

Barry Piccinni

**Comment by poornima-krishnasamy** [comment]
Conversation on slack: https://mojdt.slack.com/archives/C57UPMZLY/p1695809794510479
Update the user guide for clarity on information alerts: https://github.com/ministryofjustice/cloud-platform-user-guide/pull/1547
