### ISSUE TITLE
PSP removal Phase 1: Helm Chart [service] 

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4802]
**Clone this ticket for each Helm chart**

## Background

For each of our system components that configure bespoke psps:

Prometheus
Descheduler
Gatekeeper
Autoscaler
Calico

we need to check the Helm release allows for disabling of PSPs prior to k8s 1.25 upgrade.

Steps to follow:

1) Ensure test cluster has PSA enforce: privileged enabled for CP system namespace(s)
1) Test disabling of Helm managed PSPs at k8s 1.24. Ensure service works as expected
1) Apply any required updates to TF module, update release and apply to production clusters.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Add concourse from manager cluster

**Comment by tom-j-smith** [comment]
Documentation for ticket here - https://docs.google.com/document/d/16srZZ7psTkscQmjn7GbFkoO3B0PmWgSnSwiiZfDUMok

**Comment by tom-j-smith** [comment]
Calico - No PR as a part of this ticket, this is as the only way to remove Calico is by being on a version of Kube where the PodSecurityPolicy API is not supported. The Calico helm chart will then not create the PSP - [source](https://github.com/projectcalico/calico/issues/7686#issuecomment-1561596503)
Autoscaler - [PR Here](https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler/pull/30)
Descheduler - [PR Here](https://github.com/ministryofjustice/cloud-platform-terraform-descheduler/pull/17)
Gatekeeper - [PR Here](https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/pull/41)
Monitoring/Prometheus - [PR Here](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/182)

**Comment by tom-j-smith** [comment]
Extra Descheduler tests added to document
