### ISSUE TITLE
PSP Removal Phase 2: `aws-node` and other current custom PSPs, migrate them to Gatekeeper

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#4803]
## Background

We lose some of our specific policy permissions in our move to PSA. Instead the workloads will all be granted privileged permission which is fine but we may want to lock down these workloads to the same level as they were during the PSP era. To do that we need to replicate these policies in gatekeeper.

See the policy library for examples. https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
two constraints to cover include:

- `fsGroup`
- `supplementalGroups`

**Comment by jaskaransarkaria** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/0a57fb1163d8e5643695bb04fff1e60096d279c5/terraform/aws-accounts/cloud-platform-aws/vpc/eks/psp.tf

**Comment by poornima-krishnasamy** [comment]
All system namespaces excluding kube-system, ingress-controllers can be locked down to have less capabilities
```
  allowed_capabilities = [
      "NET_BIND_SERVICE",
      "NET_ADMIN",
    ]

    required_drop_capabilities = [
      "NET_RAW"
    ]
```

`SYS_CHROOT` is required for ingress controllers namespace
` "NET_RAW"` is required for kube-system namespace

**Comment by poornima-krishnasamy** [comment]
Draft PR: https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/pull/49
TODO: 
- Set the message to fetch from spec.parameters. Failing unit tests
- Testing in test cluster including all components in system namespaces, include live compoents like concourse, exporter etc

Review again if the AllowedCapabilities are opening any gates for restricted namespaces.
