### ISSUE TITLE
PSP removal Phase 2: Test 1.25 upgrade and it's affect on PSP resources

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4805]
## Background

Besides Helm managed PSPs, we have some privileged policies for system workloads defined in infrastructure repo:

https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/aws-accounts/cloud-platform-aws/vpc/eks/psp.tf

This ticket is essentially just testing what happens to PSP when we upgrade to 1.25. Do we need to explicitly delete the PSP resources pre upgrade? or ideally we can delete these resources post upgrade?

Steps to follow:

1) Ensure test cluster has PSA privileged enabled for CP system namespace(s)
1) Ensure test cluster has PSA restricted test namespaces with psp bypassed (rolebinding = privileged)
1) Upgrade test cluster from 1.24 to 1.25 and repeat checks
1) Check to see that namespaces are all still using PSA (perhaps run the tests in [this repo](https://github.com/jaskaransarkaria/k8s-psa-pss-testing) again)
1) what happens to the role bindings after a upgrade?

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
This ticket is essentially just testing what happens to PSP when we upgrade to 1.25. Do we need to explicitly delete the PSP resources pre upgrade? or ideally we can delete these resources post upgrade?

- Most of the psp has been removed and covered my 0-super-privileged psp. 
- This psp can stay in the cluster when the live cluster is upgraded. All pods will be shifted to new node and hence at that time, all pods will be created as per namespace psa labels.

1. Ensure test cluster has PSA privileged enabled for CP system namespace(s)
All PSA labels are added in terraform. If there is any changes, the divergence will highlight the drift.

Ensure test cluster has PSA restricted test namespaces with psp bypassed (rolebinding = privileged)
The bypass rolebinding will not be needed as the 0-super-privileged psp has cluster-role-binding referencing system:authenticated group.

Upgrade test cluster from 1.24 to 1.25 and repeat checks - DONE
Check to see that namespaces are all still using PSA (perhaps run the tests in [this repo](https://github.com/jaskaransarkaria/k8s-psa-pss-testing) again) - DONE

what happens to the role bindings after a upgrade? Removing rolebinding PR: TBD
