### ISSUE TITLE
Update s3 bucket migration instructions

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4807]
## Background

We have steps on the terraform module s3 bucket on how to migrate content from one s3 bucket to another. 
https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket#migrate-from-existing-buckets

As Cloud Platform moved away from using IAM keys and to short-lived credentials, update the steps on how to migrate the s3 bucket using IRSA and a service pod.

## Approach
User able who need to migrate content from one s3 bucket to another can update the policy in the irsa and use the service pod to access both s3 buckets and perform aws s3 sync

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Questions / Assumptions

Can this be converted into user guide so it can be reviewed and updated or is it make sense to be inside the repo?

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Tackled in this ticket:
https://github.com/ministryofjustice/cloud-platform/issues/5414

**Comment by Matt-Alinosn** [comment]
Duplicate ticket to be closed - as per conversation on planning 24/6/24
