### ISSUE TITLE
court-probation-prod connection refused errors

### ISSUE THREAD

**Issue by rschallapalli** [ministryofjustice/cloud-platform#4808]
## Service name

prepare-a-case

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

This has impacted live court staff users using the prepare-a-case application as it failed with 500 system error

## Problem description

There were http connection refused errors when the frontend, prepare-a-case-* pods, tried to invoke backend api court-case-service pods(url: https://court-case-service.apps.live-1.cloud-platform.service.justice.gov.uk/)

**Dates:** on 7th and 18th September

**Namespace**: court-probation-prod

**App Insights query** - if checked for last 30 days spikes are seen on 7th and 18th September

```
  customEvents | where name == 'PiCPrepareACaseErrorTrace'
  | summarize TotalNumberofErrors=sum(itemCount) by bin(timestamp, 1d)
  | render timechart 
```

## Contact person

 **Slack:** @Ravi
 **Email:**  ravishankar.challapalli@justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
Hi @rschallapalli , To understand more about the problem, can you get the details below

Can you send me a screenshot of the app insights query results. We dont have access to AppInsights so it would be good to see how much is the spike? How much % of traffic was affected?

I can see few things in kibana: https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-06T23:00:00.000Z',to:'2023-09-18T22:30:00.000Z'))&_a=(columns:!(_source),filters:!(),index:'8a728bc0-00eb-11ec-9062-27aa363b66a2',interval:auto,query:(language:kuery,query:'%22court-case-service.apps.live-1.cloud-platform.service.justice.gov.uk%22%20AND%20%22connection%20refused%22'),sort:!()). 
Does this corelated to what you see in AppInsights?

Do you see a similar spike both 7th and 18th ?

Are there any additional debug/error logs in prepare-a-case pods during that time on how long it waited for connection or anything similar.

**Comment by poornima-krishnasamy** [comment]
As the team couldnt replicate the issue, I am closing this for now. Feel free to open a new ticket when you want us to look at the infra side of the issue.

**Comment by ravi** [comment]
Please stop tagging me in your issues and other GitHub activities.
