### ISSUE TITLE
Add details of error to ErrorsInExternalDNS alert

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4826]
## Background

We get alerts in lower-priority-alarms when there is an increased error in external-dns. This could be for many reasons. Add details to the alert based on what the error message is logged in external-dns.

Some possible reasons be
1. "failed to list hosted zones: Throttling: Rate exceeded"
2. "InvalidChangeBatch"
3. Ingress Rule lacking weighted annotation

## Proposed user journey

We dont know why the ErrorsInExternalDNS alert is triggered until u go into the external-dns logs and debug.

## Approach

Add details in the alert by parsing the logs for specific reason for the alert

## Which part of the user docs does this impact

https://runbooks.cloud-platform.service.justice.gov.uk/external-dns-error.html#troubleshooting

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Questions / Assumptions

Would a Prometheus alert be able to get the reasons or a log based alerting be needed?

## Definition of done

- [ ] Reason for the error is added to the alert
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4746

**Comment by SteveMarshall** [comment]
If we can address these elsewhere (eg in Gatekeeper), consider doing so.

**Comment by jaskaransarkaria** [comment]
When ready merge in the below and create a release, then we can close this ticket:

https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/pull/40

**Comment by jaskaransarkaria** [comment]
Also, there's nothing we can do about throttling errors so perhaps consider increasing the threshold to lower noise
