### ISSUE TITLE
Apply nginx-ingress.tf to `live-0`

### ISSUE THREAD

**Issue by nayoa** [ministryofjustice/cloud-platform#483]
## Background

connects to #466 

As part of #466, a requirement was to apply the `nginx-ingress.tf` to all clusters. The change has been applied to `test-1`. However, for `live-0`, applying the `nginx-ingress.tf` requires deleting the current nginx-ingress and applying the new terraform one. 

## Approach

A discussion needs to be made with teams that have live applications in `live-0`. 

(At this moment in time, it's only laa-fee-caculator)

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

Is there a suitable time at all?

Should this change only be applied to new live clusters e.g. `live-1` ?

- `live-0` will go down for a couple of seconds/minutes during the helm delete

- `laa-fee-calculator` team are the only team who have a live application

## Definition of done

- [ ] Speak to laa-fee-calculator team to find a suitable time to apply `nginx-ingress.tf` to `live-0`
- [ ] Inform `#cloud-platform-users` slack channel what will happen
- [ ] Delete the current nginx-ingress - `helm del --purge nginx-ingress`
- [ ] Terraform apply nginx-ingress.tf with the `cloud-platform-live-0` workspace

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Mitch is doing this work tonight. Duplicate.
