### ISSUE TITLE
Investigate ways to reduce Github API limits in concourse pipelines

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4833]
## Background

The cloud-platform plan, apply-namespace and apply pipeline runs on namespaces to perform terraform plan and apply. Most of the namespaces has github resources and needs to connect to Github via API. Often the API limit is hit and the pipelines stops to perform plan or apply on any namespace. 

```
403 API rate limit exceeded for user ID 36888942. If you reach out to GitHub Support for help, please include the request ID 15F0:53D3:37AEE73:383FB5B:651BFD3A. [rate reset in 48m57s]
```
https://mojdt.slack.com/archives/C514ETYJX/p1696333144529169

## Proposed user journey

This means users cannot raise a PR to perform a terraform plan using pipeline and cannot do a terraform apply on a PR merged via the pipeline. These has to be done either manually by Cloud Platform if it is urgent or wait for the rate.to be reset. 

## Approach

Investigate what are the API calls which are causing this rate limit.

One of the reason is the terraform module serviceaccount and ecr which creates github action secrets to application repository. Check which operation the rate limit is increased largely. Is it a read or write operation? Check if a delay can be added to that?

Find alternative ways to connect to github API via terraform. Can we create multiple personal access token, one to perform plan, one to perform apply-namespace and one to perform the apply?

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
This issue has gone quiet since ECR module bump for removal of redundant GH api calls. Closing
