### ISSUE TITLE
Update ChangeInNodeCount alert with details of  FROM to TO

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4834]
## Background

When there is a change of node count to the live cluster, we get a information alert ChangeInNodeCount. This only tells the count of what it has changed to. Update the alert to include from what number it has to this.

Current: The Node count has changed to 46
Update to: The Node count has changed from 47( or whichever was the previous count) to 46

https://mojdt.slack.com/archives/C8QR5FQRX/p1696385171227459

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tom-j-smith** [comment]
ChangeInNodeCount alert has been split into Increasing and decreasing alerts to allow them to trigger more consistently.
https://prometheus.live.cloud-platform.service.justice.gov.uk/alerts?search=InNodeCount
