### ISSUE TITLE
Access for new developers to FALA/CLA

### ISSUE THREAD

**Issue by rowlando** [ministryofjustice/cloud-platform#484]
## Service name

Our team has two new developers:

- @Katy600
- @farrepa

Please can you set the up as below?

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

None

### AWS Access
- [x] moj-cla-dev (https://moj-cla-dev.signin.aws.amazon.com)
- [x] moj-laalaa aws (https://moj-laalaa.signin.aws.amazon.com)

### SSH Access
- [x] SSH access to all `fala` environments
- [x] SSH access to all `cla_public` environments
- [x] SSH access to all `cla_backend` environments
- [x] SSH access to all `cla_frontend` environments
- [x] SSH access to all `laa-legal-aid-advisers` environments

### Monitoring
- [x] Login for https://sentry.service.dsd.io/mojds/
- [x] Added to the appropriate Sentry projects

## Contact person

Slack: @nick
Email: nick.rowlands@digital.justice.gov.uk

**Comment by pwyborn** [comment]
Hi the following easy pull requests please (ssh key update):

``` 
https://github.com/ministryofjustice/fala-deploy/pull/31
https://github.com/ministryofjustice/laalaa-deploy/pull/40
https://github.com/ministryofjustice/cla_public-deploy/pull/70
https://github.com/ministryofjustice/cla_frontend-deploy/pull/89
https://github.com/ministryofjustice/cla_backend-deploy/pull/88
```

**Comment by pwyborn** [comment]
Everything done
