### ISSUE TITLE
Alert when grafana throw "failed to load dashboard " error

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4842]
## Background

When there is a json error on any of the newly created grafana dashboard, the grafana pod logs show error 

```
msg="failed to load dashboard from " file=/tmp/dashboards/XXX-dashboard.json error="invalid character 'i' looking for beginning of value"
```

But this error is logged in grafana pod and not visible to users when the create the dashboard using the configMap.

## Proposed user journey

Users often raise question in the #ask channel, that they have applied a configmap to create a new dashboard and can see the configmap. But cannot see the dashboard in the Grafana UI. 

This is because one of the previously applied configmap might have some json parsing errors.

## Approach

Cloud Platform team only know about this when the user reports of an issue. Create a log based alert when a grafana pod errors with log message "failed to load dashboard .."

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tom-j-smith** [comment]
Monitor has been created on kibana to alert when a log matches the following search: `"failed to load dashboard" AND kubernetes.container_name: grafana`
