### ISSUE TITLE
Replicate cloud-platform-live Elasticsearch in Opensearch

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4861]
## Background

As part of investigating JVMMemoryPressure, the instance size can be reduced with similar EBS storage and at the same time can increase the number of nodes to the existing count.

## Approach

 Instead of upgrading the current ES, it would be better to create a new Opensearch cluster with similar configuration, latest version, r6g.2xlarge.search and with better iops and throughput configration. This will allow to monitor the heap memory and at the same time the other parameters like CPU, disk storage and metworking

## Which part of the user docs does this impact

Create the new Opensearch here: https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/aws-accounts/cloud-platform-aws/account 
comparing 

https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/global-resources/elasticsearch.tf

Also, look for better IOPs and throughput as per this PR: https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2457

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jakemulley** [comment]
> I think we should use this ticket as a way to set up the logging part of Observability Platform + very possibly explore OpenTelemetry as a wider logging collector (via fluentbit, naturally) rather than just "replacing it", if that makes sense.
> 
> We can then dual run ElasticSearch + new OpenSearch for 30 days or however long we need to, and then scale down ES to keep the historical logs for a year (or back them up).

from planning, 8th November 2023
