### ISSUE TITLE
Integration test ginkgo version is mismatched

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#4870]
## Background

upgrade the ginkgo integration test version in `cloud-platform-infrastructure` to match the cli

```
  Ginkgo CLI Version:

    2.11.0

  Mismatched package versions found:

    2.12.0 used by test
```

**Comment by poornima-krishnasamy** [comment]
Closed. https://github.com/ministryofjustice/cloud-platform-tools-image/pull/107
