### ISSUE TITLE
Bypass PSP Phase 1: Keep PSP in place but allow PSA to supercede

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#4872]
## Background

In order to bypass PSP we need to do 2 things:

1) enforce PSA (restricted and privileged)
1) bypass PSP by elevating permissions to privileged for each (user and system) namespace as outlined in the [technical document](https://docs.google.com/document/d/1sVCHVlFEjeIK26d07enmv0JE60aHNfl0NO6NUH25hWE/)

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
- updated github action and conftest check 
-

**Comment by poornima-krishnasamy** [comment]
Update on this ticket: 
- The enforce:restricted label has been reverted as the mutation was failing on initContainers 
- Draft PR to test initContainer mutations: https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/pull/40
- Tests for init containers: https://github.com/jaskaransarkaria/k8s-psa-pss-testing/pull/1
