### ISSUE TITLE
Upgrade Cluster Autoscalar to 1.24.x

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4873]
## Background

The Cloud Platform Cluster is in k8s version 1.24. Hence upgrade the cluster-autoscalar to match the k8s version.

## Approach

https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler
https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler

- test the upgrade in test cluster
- upgrade live-2, manager and live

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform/issues/4794

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] cluster-autoscalar upgraded to live02, manager and live
- [ ] Latest version updated to the EPIC issue
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Autoscaler bump:
https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler/releases/tag/1.5.0

Overprovision:
https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler/releases/tag/1.5.1

CPA:
https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler/releases/tag/1.5.2
