### ISSUE TITLE
New integration Id for #launchpad-alerts

### ISSUE THREAD

**Issue by psoleckimoj** [ministryofjustice/cloud-platform#4874]
## Service name
Launchpad

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Allow us to add Pingdom for Launchpad

## Problem description

Slack channel is #launchpad-alerts and this will be used for Launchpad (hmpps-launchpad-prod) and Content Hub (prisoner-content-hub-frontend/backend) alerting.

## Contact person

Paul Solecki / @psoleckimoj / paulsolecki / paul.solecki@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
The integration-id for #launchpad-alerts : 132036
