### ISSUE TITLE
Upgrade descheduler to v0.24.x

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4875]
## Background

The Cloud Platform Cluster is in k8s version 1.24. Hence upgrade the descheduler to match the k8s version.

## Approach

https://github.com/kubernetes-sigs/descheduler#%EF%B8%8F--documentation-versions-by-release

https://github.com/ministryofjustice/cloud-platform-terraform-descheduler

- Enable descheduler and test the upgrade in test cluster
- Upgrade the module in live-2, manager and live

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform/issues/4794

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] descheduler upgraded on live-2, manager, live
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
done
https://github.com/ministryofjustice/cloud-platform-terraform-descheduler/releases/tag/0.4.0
