### ISSUE TITLE
Do we still need EFS CSI driver?

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4877]
## Background

The Cloud Platform cluster has AWS EFS Driver installed. It is not configured for actual use by CP users. Also, its runs as a daemonset, and is not up to date.

There are discussions around moving the chart as a efs-utils addon and installed by system-manager.
https://mojdt.slack.com/archives/C514ETYJX/p1689588085979529

We should consider what we want to do about this component. It probably should be deleted, but prior to this we should see if there is a suitable NFS like / read-write-many solution that is now available for us to look at.

If found, create ticket for spiking.

## Proposed user journey

There is also no urgent user need from user: https://github.com/ministryofjustice/cloud-platform/issues/3994

## Approach

Investigate if there is still a user need for this module or else, remove the installation from the cluster. 

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform/issues/4794

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jakemulley** [comment]
Can we loop in Data Platform to a conversation on this as in conversation they have expressed interest in requiring EFS for a service.
