### ISSUE TITLE
New integration Id for #hmpps-sre-alerts

### ISSUE THREAD

**Issue by psoleckimoj** [ministryofjustice/cloud-platform#4878]
## Service name
SRE

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Allow us to add Pingdom for all SRE related services

## Problem description

Slack channel is #hmpps-sre-alerts and this will be used for SRE related services (hmpps-portfolio-management-prod).

## Contact person

Paul Solecki / @psoleckimoj / paulsolecki / paul.solecki@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
Integration ID for  #hmpps-sre-alerts : 132037
