### ISSUE TITLE
Review ingress controller count

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4886]
## Background
We currently have our ingress controller replica count set to 12 for both `default` and `modsec` flavours of our deployments. We should review this count and consider whether we ought to scale back to down.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
https://www.nginx.com/blog/microservices-march-reduce-kubernetes-latency-with-autoscaling/

We want to scale on ~100 active processes per ingress. This is based on load testing that shows the controller starts to drop requests when we exceed this number

**Comment by poornima-krishnasamy** [comment]
https://nginx.org/en/docs/http/ngx_http_limit_conn_module.html

**Comment by poornima-krishnasamy** [comment]
TODO: add a info alert when the number of process connections is reached certain limit
