### ISSUE TITLE
Upgrade ministryofjustice/cloud-platform-tools-image helm from 3.6.3 to 3.7+

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/cloud-platform#4887]
## Service name

laa-apply-for-legalai

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X] Other/UAT/All

## Impact on the service

Would like to make use of helm 3.7+'s ability to reference `Subcharts` helpers, at least

## Problem description

Was hoping to make use of 3.7+ ability to refer to Subcharts to simplify and provide a more resilient helm upgrade when setting envs var values (for a `REDIS_HOST` in this case). Currently HELM is set to 3.6.3.
e.g.
```yaml
{{- $redis_fullName := (include "common.names.fullname" .Subcharts.redis) -}}
```

[example of failure raised on circleci](https://app.circleci.com/pipelines/github/ministryofjustice/laa-apply-for-legal-aid/24548/workflows/9a929053-7466-4a8a-b311-79ce56475782/jobs/128028)

[Dockerfile](https://github.com/ministryofjustice/cloud-platform-tools-image/blob/main/Dockerfile#L29)

## Contact person

@jsugarman

**Comment by jackstockley89** [comment]
New release created for tools image 2.7.0 with helm 3.7
