### ISSUE TITLE
Create a dsd.io URL for C100 staging k8s URL

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#489]
## Service name

Apply to court about child arrangements (C100)

## Service environment

- [ ] Dev / Development
- [X] Staging
- [ ] Prod / Production
- [ ] Other

## Problem description

We've created a staging k8s environment, and we would like a `dsd.io` URL to make it easier to access.

The k8s URL is: https://c100-application-staging.apps.cloud-platform-live-0.k8s.integration.dsd.io
(it is behind http auth, as this is not a production env, it is used for demo and user research).

Ideally we would like something like: `c100-application-staging.dsd.io`

## Contact person

Jesus @ slack

**Comment by lukaszraczylo** [comment]
DNS CNAME record c100-application-staging.dsd.io has been created and pointed at desired URL. There's certificate error though as the certificate itself has been issued for *.apps.cloud-platform-live-0.k8s.integration.dsd.io

**Comment by zheileman** [comment]
This is something of no urgency for us, we just wanted to have a more "friendly" URL to share with stakeholders and demo / user research purposes.

For the production env then yes we will need to have this into consideration as we already have a domain and would like to transition that domain over the new k8s architecture (we are now on Heroku).

But ideally we would like to know if this problem with the certificate can be solved on our side or not. Is this just not possible at the moment, but will be in the future perhaps?

**Comment by AntonyBishop** [comment]
Need to ensure as part of the work that the DNS zone is created.

**Comment by AntonyBishop** [comment]
Hosted zone already set up. Section in the guide to allow domain to access cert manager to be followed.

**Comment by mtrblmoj** [comment]
No longer required.
