### ISSUE TITLE
Request to amend the severity name re Issues #4888

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/cloud-platform#4895]
## Service name

These are the details that should have been provided:

namespace name - laa-information-exchange-development
team name - information-exchange-non-prod
application name - information exchange (aka infox)
slack channel - cp-laa-alerts-infox-non-prod
kubernetes secret name where the webhook url is stored - webhook-for-laa-information-exchange-development
severity level (warning/information) - warning

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

--

## Problem description

The "team name" which sets the severity name was provided with the wrong value. This is to correct that.

## Contact person

@ministryofjustice/mikereid
mike.reid@ditigtal.justice.gov.uk

**Comment by jackstockley89** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2523
