### ISSUE TITLE
track-a-query filter based on header

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#490]
## Service name
Correspondence Tool

## Service environment
- [x] Dev / Development
- [x] Staging
- [x] Prod / Production

## Problem description
As per the conversation with @misaka , the app must accept only incoming requests with a justice.gov.uk Host header; this is to identify if said filter should be added in the fronting Nginx or in the app itself and implement the change in https://github.com/ministryofjustice/correspondence-staff-deploy

## Contact person
Misha

**Comment by misaka** [comment]
Just to be clear, we want to respond to:

- Redirect requests from `track-a-query.dsd.io` to `track-a-query.service.justice.gov.uk`.
- Drop requests for any domain other than `track-a-query.dsd.io` or `track-a-query.service.justice.gov.uk`.

Additionally, we need to ensure that any ping/healthchecks requests still work. `curl` from the cmdline should work for debugging, even if we have to use the form:

    $ curl --connect-to 52.31.190.188:443 https://track-a-query-dev.dsd.io/ping.json

And any health checks by HAProxy or ELB should still work.

**Comment by lukaszraczylo** [comment]
Latest commit in PR ( aa126e3849085b6904c34fc241a4c3fe2fab3c67 ) reverts the required change.
