### ISSUE TITLE
Support for Cloud Platform Prometheus to scrape non-Cloud Platform applications e.g. MAAT

### ISSUE THREAD

**Issue by stone-dj** [ministryofjustice/cloud-platform#4915]
## Service names

- LAA MAAT (Means Assessment and Administration Tool) - https://github.com/ministryofjustice/laa-maat-application
- LAA MLRA (Managed Libra Record Application) - https://github.com/ministryofjustice/laa-mlra-application

## Service environment

- [ x] Dev / Development
- [ x] Staging
- [ x] Prod / Production
- [ ] Other

## Impact on the service

No immediate impact to service provision.
The purpose of raising this issue is to explore efficiency savings for two of our legacy apps with regards to application metrics, monitoring and alerts.

## Problem description

Is there a way to create a ServiceMonitor such that the Cloud Platform Prometheus will scrape a non-Cloud Platform application metrics endpoint?
Or otherwise, are there any other options for collecting metrics from legacy applications in Cloud Platform Prometheus?

## Background and context

We own x2 legacy applications (MAAT & MLRA) which are hosted on the Modernisation Platform (aka LAA AWS Landing Zone)  https://user-guide.modernisation-platform.service.justice.gov.uk/#modernisation-platform
https://github.com/ministryofjustice/laa-aws-infrastructure/

We also own a number of APIs hosted on the Cloud Platform, which going forwards will increase in number. With a long term goal to replace both MAAT & MLRA.

We would like to collect all our application metrics in one strategic place, Cloud Platform Prometheus. Allowing us to use consistent tooling across all our applications with regards to application metrics, monitoring and alerts.

## Contact person
Alex Stone
@Stone, Alex
alex.stone@digital.justice.gov.uk

Backup:
Nathan Leahy
@Nathan Leahy
nathan.leahy@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
Hi @stone-dj , With the current setup we have, Cloud Platform Prometheus cannot scrape metrics hosted externally. Other teams we know use AppInsights and Sentry for application metrics, if you would like to explore on those.

We're also looking at whether all hosting teams can centralise observability as a strategic approach to this, and MAAT/MLRA being in the Modernisation Platform should help simplify this in the future.

**Comment by stone-dj** [comment]
Hi @poornima-krishnasamy thank you for confirming I appreciate your prompt reply :)

Do you have any indication of the time frame for a strategic, centralised observation capability? This would help us best determine how to implement a solution to our metrics requirements for our legacy applications.

**Comment by jakemulley** [comment]
Hello @stone-dj,

The centralised observability capability is very much in discovery mode at the moment, starting at a platform level (i.e. observability for Cloud Platform, Modernisation Platform, and Data Platform themselves), though we're looking to start a round of research with application teams as we progress that initial work to help us understand the needs of users and teams more widely.

Given this is very early stages, I would suggest that a tactical solution, for the short term, is beneficial for your legacy applications.

Naturally, we'd be happy to share any outcomes we find and involve you in the research when it happens to help you build your strategy.

How does that sound? Feel free to reach out on Slack if easier.

thanks!

**Comment by poornima-krishnasamy** [comment]
Hi @stone-dj , I am closing this ticket. Feel free to reach out to us on Slack for any further questions
