### ISSUE TITLE
Default Root Domain absent from MoJ CloudFront distribution

### ISSUE THREAD

**Issue by wilson1000-MoJ** [ministryofjustice/cloud-platform#4917]
## Service name

[Justice Archiver (dev)](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/justice-archiver-dev/resources/cloudfront.tf) - _links to cloud platform live resource_

namespace = `justice-archiver-dev`

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

The user gets an error when navigating to the [root domain](https://d2188sguqzuw6r.cloudfront.net/). 

![Screenshot 2023-10-25 at 18 08 34](https://github.com/ministryofjustice/cloud-platform/assets/47327051/3d5b34c7-f77c-415a-8370-0093e5863553)

## Problem description

[Our CloudFront Terraform module](https://github.com/ministryofjustice/cloud-platform-terraform-cloudfront/tree/main) is not currently set up to accept a top-level variable (`default_root_object`) that would allow us to specify a default root object.

A default root object is a value that is useful in CloudFront distributions when S3 is acting as the origin. We can instruct CloudFront to append the default root object when the root domain is requested. 

For example, the following link produces the error shown in the screenshot above.

https://d2188sguqzuw6r.cloudfront.net/

If we append `index.html` to the URL, the error goes away, and the correct resource is returned.

https://d2188sguqzuw6r.cloudfront.net/index.html

Setting `default_root_object` to `index.html` would allow the user to visit the root domain without error.

![Screenshot 2023-10-25 at 18 22 50](https://github.com/ministryofjustice/cloud-platform/assets/47327051/7c317815-0690-4954-a24d-6a02488a618c)

For reference:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#default_root_object

## Contact person

[Damien Wilson](https://moj.slack.com/team/UFX45TQJY) - _links to Slack profile_

Email: damien.wilson@digital.justice.gov.uk

**Comment by jakemulley** [comment]
released in [cloud-platform-terraform-cloudfront v1.2.0](https://github.com/ministryofjustice/cloud-platform-terraform-cloudfront/releases/tag/1.2.0)
