### ISSUE TITLE
Extra containers started up on new servers.

### ISSUE THREAD

**Issue by misaka** [ministryofjustice/cloud-platform#492]
## Service name

Correspondence Staff Tool

## Service environment

- [X] Dev / Development
- [?] Staging
- [?] Prod / Production
- [ ] Other

## Impact on the service

Old, unused, containers are running on servers using up resources and potentially picking up jobs and processing them with old code.

## Problem description

New servers appear to be get old containers which we no longer run started. For example on demo, which we re-provisioned 19 days ago, has these containers running on them, which we no longer use or deploy:

```
7e251c0c3083        registry.service.dsd.io/correspondence-staff:master.c011a2c           "./run-reports.sh"       2 weeks ago         Up 2 weeks          3000/tcp                 correspondence-staff-reports
c9af9d188fce        registry.service.dsd.io/correspondence-staff:master.c011a2c           "./run-mailer.sh"        2 weeks ago         Up 2 weeks          3000/tcp                 correspondence-staff-mailer
```

There are no mentions of `reports` or `mailer` in the [correspondence-staff-deploy](http://github.com/ministryofjustice/correspondence-staff-deploy) repo, so we're guessing there's some kind of metadata in AWS that is triggering this: perhaps an old image is being used or there are some autoscale group tags set incorrectly.

## Contact person

- misha / misha.gorodnitzky@digital.justice.gov.uk
- #ct-chat / correspondence@digital.justice.gov.uk

**Comment by lukaszraczylo** [comment]
Updates run on both dev and demo environments, no duplicated containers were found afterwards. I've cleared jenkins workspaces for deployment project as a precaution.

Misha has confirmed that this solution produced the desired outcome.

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1542121705069300
