### ISSUE TITLE
A user's cronjob is getting scheduled for a time in the past

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#4920]
## Background

A user has a cronjobs reporting that they are long-running. I suspect this is because k8s API hasn't got a timezone adjusted time, so times are an hour behind, however, Prometheus is time zone adjusted so prometheus alerts that the job is long-running as it is time zone adjusted.

https://mojdt.slack.com/archives/C57UPMZLY/p1696839800256199

## Approach

Add a timezone file to `kube-state-metrics` https://github.com/kubernetes/kube-state-metrics/issues/500#issuecomment-408075043

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Additional info from user:
https://mojdt.slack.com/archives/C57UPMZLY/p1713338714703329
