### ISSUE TITLE
Create a user guide entry that explains how using Cloud Platform supports Service Teams in meeting the Service Standard

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4933]
## Background

We get asked questions about how Cloud Platform supports the Service Standard. We are either unclear about the benefits or we have the come up with a bespoke answer each time.

For consistence and and a selling point for the Cloud Platform we should add something to our user guide that clearly states where Cloud Platform can help you in meeting parts of the Service Standard.

Recent thread - https://mojdt.slack.com/archives/C57UPMZLY/p1698071819633419

## Proposed user journey

**As a** Service Manager/Product Manager
**I want** information on how user Cloud Platform will help me meet the Service Standard throughout the lifecycle of my product
**so that** I better understand the value of the Cloud Platform, can reference this at Service Assessment, and reduce duplicaion of effort on criteria that Cloud Platform will meet for me by default.

## Value

Documenting this information will mean there is a default response which will save teams time in coming up with an answer each time users ask the question.

This is also a showing the value of adopting Cloud Platform for hosting of services.

## Approach

Create user guide entry

## Which part of the user docs does this impact

New part of user guide, however it may reference documentation that already exists e.g. DR offering, ITHC etc

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] post for #service-standard
- [ ] include in Weeknotes

## Questions / Assumptions

Assumes that we understand the Service Standard and can relate pertinent information that supports assessment criteria.

## Definition of done

- [ ] New user docs created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by timckt** [comment]
Have written the first draft for how Cloud Platform meet the service standard in the [link](https://docs.google.com/document/d/1E4GYBRxhtD4tTMzUGNDMCOpkcYrIdKbU9GaJ1rMp6XM/edit?usp=sharing). 

I would like to explain how CP help service teams meet the service standard. Below is the logic flow for the article:
1. From the foundation part - AWS infrastructure, to we are Cloud-native by default with AWS EKS and the advantage. 
2.  Then we are using DevOps CICD pipeline and IAC to manage all the resource and how we manage the code on GIthub.
3.  The automated testing part is introduced here.
4.  Will also talk about the monitoring and alerting stack we used in CP and how to maintain operational awareness and facilitate rapid incident response.
5.  Highlight some benefits and the conclusion

**Comment by timckt** [comment]
will try to upload the images to the images folder under user guide repo and make see the result. If the images are not good for accessibility, will try to enrich the content for PR part in the document.
