### ISSUE TITLE
Setup domain for subject-access-request preprod

### ISSUE THREAD

**Issue by HorstmannA** [ministryofjustice/cloud-platform#4938]
## Service name

hmpps-subject-access-request

## Service environment

- [ ] Staging

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

N/A

## Problem description

A DNS is required to set up the service.

## Contact person

April Dawson, Cai Kingston, Emile Stewarts, Anna Horstmann (all Made Tech, members of the MOJ #subject-access-requests-hmpps-internal Slack channel)

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/C57UPMZLY/p1699875208127529

**Comment by pwyborn** [comment]
Hi Anna 
@Anna Horstmann
:
You created 3 issue tickets 10 days ago:
Is everything ok then (can I close them)?
Screenshot 2023-11-13 at 14.59.19.png

https://mojdt.slack.com/archives/C57UPMZLY/p1699887691084019?thread_ts=1699875208.127529&cid=C57UPMZLY
