### ISSUE TITLE
PSP Removal Phase 3: tidy up PSP leftovers

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#4942]
## Background

- Remove role bindings used to set up the PSP bypass
- find and remove references to audit
- remove PSP tests (and remove the need for the bypassPspRoleName variable in templates)
- remove any orphaned tf state/ resources (eg `psp:0-super-privieged`)
- remove rolebindings from -> (cluster-autoscaler, overprovision, external-secrets-operator, starter-pack)

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Removed superpriv psp rolebinding resources from infra components:

https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2638
