### ISSUE TITLE
Polish the new cluster creation configuration

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#495]
## Background

We need to test that the cluster creation process works end-to-end and is improving on the previous work.

## Approach

Please see the comments below for instructions / details.

## Questions / Assumptions

We assume that all the clusters are one-size and built in the integrations account.

## Definition of done

- [ ] test that you can create a functional cluster with no issues
- [ ] cleanup the cluster
- [ ] update the docs / fix minor issues

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
The first round of cluster creation is complete. @alkar & @jasonBirchall have built test-3 using automated steps. 

Notes are located here: 
https://docs.google.com/document/d/1s6dc5Jt2ETdZ_-Ehak0mzEQ8f6u8YHfIim23p17Wgwg

Will destroy and rebuild again today.

**Comment by jasonBirchall** [comment]
Team one work complete...
Docs are located here: 
https://github.com/ministryofjustice/kubernetes-investigations#how-to-create-a-new-cluster
Personal notes on the process made here:
https://docs.google.com/document/d/1s6dc5Jt2ETdZ_-Ehak0mzEQ8f6u8YHfIim23p17Wgwg
Route taken: 
- Created test-3 based on README.
- Made relevant changes.
- Deleted test-3 based on README.
- Made relevant changes.
- Created test-4 based on README.
- Made relevant changes.
- Deleted test-4 based on README.
- Made relevant changes.

Test-3 and test-4 no longer exist so team 2 can start from test-3 if they wish.

**Comment by lukaszraczylo** [comment]
Step-by-step from me, working for both deletion and creation. Documentation updates will follow as soon as rest of the team#2 will be ready.

[New cluster creation.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/552ba0dcaad27153005f1aea/125516c66e82c728ace21e0d46c6918d63818fbc9cfdba51e45ee29128522e7c2746ef696097ec22ba416f43554d4bfd175d0d41aefe8929afb63f748a5c09e8873e5d72906803b0aac04ee155e57dd205d0f4ae805ec1e13724e28f8d473e16021a8ffc5c37b2d4.pdf)

**Comment by razvan-moj** [comment]
team 2 done too: https://github.com/ministryofjustice/kubernetes-investigations/pull/103

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/114
