### ISSUE TITLE
Investigate velero backup failure and update root cause

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4954]
https://mojdt.slack.com/archives/C8QR5FQRX/p1699294475931819

This is part of Fixing lower-priority-alerts

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
elastic search query `kubernetes.pod_name: velero-85bf65c9c9-q4lhv and log: "level=error"`

```
time="2023-11-20T09:11:14Z" level=error msg="Error backing up item" backup=velero/velero-allnamespacebackup-20231120090023 error="error getting volume info: rpc error: code = Unknown desc = InvalidVolume.NotFound: The volume 'vol-08d317558ab5bd46b' does not exist.\n\tstatus code: 400, request id: 3a288a83-3eba-4ebe-812c-783f77c5be1d" logSource="pkg/backup/backup.go:448" name=pvc-c575b9f9-e846-4e83-8298-5a74c2533733
```
I suspect that this is because this volume is rotated during the backup and so the backup errors as it can't find the volume

**Comment by jaskaransarkaria** [comment]
https://runbooks.cloud-platform.service.justice.gov.uk/disaster-recovery-scenarios.html#resolving-a-partiallyfailed-backup-alert
