### ISSUE TITLE
AlertManager route for hmpps-prisoner-profile

### ISSUE THREAD

**Issue by davidmiddletonmoj** [ministryofjustice/cloud-platform#4957]
## Service name

HMPPS Prisoner Profile - hmpps-prisoner-profile

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Route alerts to the preset Slack channels so that we can respond appropriately when there is an issue.

### NonProd Alerts

**namespace name:** hmpps-prisoner-profile-dev AND hmpps-prisoner-profile-preprod
**team name:** Connect DPS
**application name:** hmpps-prisoner-profile
**slack channel:** #connect-dps-non-prod-alerts
**kubernetes secret name where the webhook url is stored:** ALERTS_WEBHOOK_URL
**severity level (warning/information):** warning

### Prod Alerts

**namespace name:** hmpps-prisoner-profile-prod
**team name:** Connect DPS
**application name:** hmpps-prisoner-profile
**slack channel:** #connect-dps-prod-alerts
**kubernetes secret name where the webhook url is stored:** ALERTS_WEBHOOK_URL
**severity level (warning/information):** warning

## Contact person

`@David Middleton` on Slack

**Comment by tom-j-smith** [comment]
Non-Prod route - hmpps-prisoner-profile-non-prod
Prod route - hmpps-prisoner-profile-prod
