### ISSUE TITLE
AlertManager route for hmpps-digital-prison-services

### ISSUE THREAD

**Issue by davidmiddletonmoj** [ministryofjustice/cloud-platform#4959]
## Service name

HMPPS Digital Prison Services - hmpps-digital-prison-services

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Route alerts to the preset Slack channels so that we can respond appropriately when there is an issue.

### NonProd Alerts

**namespace name:** hmpps-digital-prison-services-dev AND hmpps-digital-prison-services-preprod
**team name:** Connect DPS
**application name:** hmpps-digital-prison-services
**slack channel:** #connect-dps-non-prod-alerts
**kubernetes secret name where the webhook url is stored:** ALERTS_WEBHOOK_URL
**severity level (warning/information):** warning

### Prod Alerts

**namespace name:** hmpps-digital-prison-services-prod
**team name:** Connect DPS
**application name:** hmpps-digital-prison-services
**slack channel:** #connect-dps-prod-alerts
**kubernetes secret name where the webhook url is stored:** ALERTS_WEBHOOK_URL
**severity level (warning/information):** warning

## Contact person

`@David Middleton` on Slack

**Comment by tom-j-smith** [comment]
Non-prod - hmpps-digital-prison-services-non-prod
Prod route - hmpps-digital-prison-services-prod
