### ISSUE TITLE
Unable to access CLA Frontend staging

### ISSUE THREAD

**Issue by farrepa** [ministryofjustice/cloud-platform#496]
## Service name

CLA Frontend staging

## Service environment

- [ ] Dev / Development
- [X] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Development blocker

## Problem description

I'm unable to access https://staging-frontend.cla.dsd.io/ (via browser or curl)

## Contact person

Patrick Farrell
`@Patrick Farrell` on Slack
patrick.farrell@digital.justice.gov.uk

**Comment by lukaszraczylo** [comment]
Issue caused by race condition between nginx running within app container (!) and nginx on the host. After investigation I've stopped application container, restarted host nginx, deployed latest available build onto the staging host. Specified URL is accessible again.
