### ISSUE TITLE
Check the status of deprecated APIs for 1.25

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#4964]
We have a  list of resources who uses the deprecated API for 1.25. https://mojdt.slack.com/archives/CH6D099DF/p1696246978779719

Check the current status/count of the list
Send reminder to users to update as we start the upgrade work next sprint w/c 20 Nov
Check for resources which belong to system namespaces

- [ x] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
Consider how we can capture these in gatekeeper https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/general/verifydeprecatedapi/samples

**Comment by poornima-krishnasamy** [comment]
Google spreadsheet updated for current list of deprecated APIs
Reminder on deprecated API list send to cloud-platform-update channel
