### ISSUE TITLE
PQ deploy to dev has failed

### ISSUE THREAD

**Issue by danielatdigital** [ministryofjustice/cloud-platform#497]
## Service name
PQ Tracker

## Service environment
Dev

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service
Need to deploy to live to fix security vulnerability, must deploy to dev/staging first.

## Problem description

Deploy shows as failed

https://ci.service.dsd.io/job/BUILD-parliamentaryquestions/53/console

## Contact person

Daniel Penny @danielpenny

**Comment by lukaszraczylo** [comment]
Issue fixed by re-running deployment.
