### ISSUE TITLE
Leavers - Nayo and Kalbir

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#498]

**Comment by pwyborn** [comment]
https://docs.google.com/document/d/1TUFZPksBFcy1NT6OY1JF8JsQ74t5cHauWAVHhrJLvI0/edit

**Comment by pwyborn** [comment]
As per above document - all deploys (that I know about) ssh updated plus pull requests submitted. Just awaiting reviews/mergers
