### ISSUE TITLE
Issue with AWS Connectivity from Pod in Cloud Platform - VPC Flow Logs requested

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/cloud-platform#4983]
## Service name

Create-A-Derived-Table Self-Hosted-Runner
gha-shr-mojas-create-a-derived-table-cc95cd5c5-78dwg

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Intermittent and hard to diagnose issues with accessing AWS means this runner is currently not able to function for its intended purpose. This runner is intended to be used for the deployment of all tables from Create-A-Derived-Table, and so would have a large number of customers who are currently unable to rely on it

The runner we've set up is experiencing intermittent connectivity issues with AWS STS, leading it to be unable to successfully execute AWS API calls. This is problematic, as this runner is sending SQL queries to athena, and connectivity issue mid-deployment can lead to tables failing to refresh. These errors, listed below, are proving hard to diagnose from within the pod:

`urllib3.exceptions.SSLError: TLS/SSL connection has been closed (EOF)`
`botocore.exceptions.SSLError: SSL validation failed for https://sts.eu-west-1.amazonaws.com/ TLS/SSL connection has been closed (EOF)`

As such we'd like to request the VPC flow logs relating to our pod - specifically relating to [traffic associated with this job run](https://github.com/moj-analytical-services/create-a-derived-table/actions/runs/6817383284/job/18540779582). Of particular interest to us is the period immediately before and after 21:17:08 and 21:18:37 on 2023-11-09, as these timestamps are the last and first successful response from the pod before/after a period of lost connectivity (as seen in the logs at [lines 297](https://github.com/moj-analytical-services/create-a-derived-table/actions/runs/6817383284/job/18540779582#step:11:297) and 3933). We hope these flow logs will help us better understand why the pod is failing TLS/SSL validation during the period.

## Contact person

Jacob Hamblin-Pyke/@jhpyke on slack is best point of contact, happy to provide further info if required.

**Comment by poornima-krishnasamy** [comment]
Hi @jhpyke , I am querying the vpc flow logs for the given date and time. To narrow down the results from 4GB data, can you please provide info of srcport or destination port?

**Comment by poornima-krishnasamy** [comment]
Checking with team it looks the data engineering changed the forked process count in their code and they didn't see the timeout.

Cleaned all the resources create for this investigation. e.g. s3 bucket, athena workflow and cf stack

**Comment by jacobwoffenden** [comment]
Closing this issue. Analytical Platform will engage with Data Engineering at a later date to test runners on Cloud Platform, but for now, they're running on Analytical Platform's EKS.
