### ISSUE TITLE
Protect our `/metrics` endpoints for our canary apps

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#5024]
## Background

Our `/metrics` endpoints are public and have been advised is displaying potentially sensitive info. see https://mojdt.slack.com/archives/C57UPMZLY/p1700490092581309

## Approach

Add an ingress deny to the canary app like this https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/171/files#diff-563ed0c5bba45b6381997f46ff9f6e24f7bb6d2d5519229bba21d6be129868efR206

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mikebell** [comment]
Canary app has been modified in both live and live-2 clusters.

Cloud platform metrics app has been updated and deployed.
