### ISSUE TITLE
Add gpg user to `oocp-familymediators-deploy` repo (git-crypt)

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#504]
## Service name

https://github.com/ministryofjustice/oocp-familymediators-deploy

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production

## Impact on the service

I've inherited this service and in order to be able to SSH and change deployment things like ENV variables I need to have my gpg key added to the repo, as it uses git-crypt to handle secrets.

## Problem description

At the moment there are reports the application is failing and I need to SSH and see the logs. I can't until I can clone and decrypt the repo.

GPG key ID to be added: `4A8BC1CEB255EBD7D7DF7AE820341F7A582FC4D2`

## Contact person

Jesus @ slack

**Comment by pwyborn** [comment]
19/11/2018 paulwyborn [11:24 AM]
If you do a git pull now - you should be added now?

19/11/2018 jesus [11:25 AM]
ok let me see
yay! all good, I can now unlock the repo
thanks!

19/11/2018 paulwyborn [11:28 AM]
Great thanks - will close the ticket
