### ISSUE TITLE
Split Infrastructure Components

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5040]
## Background

With the introduction of Gatekeeper pod mutations for support of PSP removal in k8s 1.25, we have reached the conclusion it is time for us to split our terraform infrastructure `components` into 2 separate layers, in order to ensure 'core' services are stood up in advance of additional cluster supporting services.

To do:

Add a `core-components` (or appropriately named) folder & corresponding s3 state layer and move foundational components into this:

- Gatekeeper
- Calico
- RBAC
- Storage
- Custom system namespace labelling resources

(and review other appropriate candidates)

Once we have this structural change in code, test builds and terraform state move for existing clusters.

- [ ] #5365
- [ ] #5359
- [ ] #5315 
- [ ] #5316 
- [ ] #5317 
- [ ] #5375
- [ ] #5318
- [ ] #5319 
- [ ] #5320
- [ ] #5321
- [ ] #5322
- [ ] #5323
- [ ] #5361
- [ ] #5376
- [x] #5300 
- [x] #5335

**Comment by sj-williams** [comment]
Notes:
https://docs.google.com/document/d/1xngnLF7wtnxnqL0TvaSfFRrPDc9JKpNQ5gz5BeR0twE/edit#heading=h.th49plkg8gop

**Comment by mikebell** [comment]
Closing in favour of milestones
