### ISSUE TITLE
New AlertManager notification rule

### ISSUE THREAD

**Issue by ayqazi** [ministryofjustice/cloud-platform#5041]
## Service name

offender-management

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

None, this just creates an Alertmanager rule to alert our channels, we are not using it yet.

## Problem description

This requests a new alert route in Alertmanager:

- namespace: offender-management-production
- team: offender-management
- application: allocation-manager
- slack channel: #mpc-alerts
- kubernetes secret name where the webhook url is stored: `slack-webhook-alertmanager` -> `HMPPS_OFFENDER_MANAGEMENT_ALERTS_WEBHOOK`
- severity level: error

## Contact person

Asfand Qazi
Slack: `@Asfand`
Email: asfand.qazi@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
Discussed with Andy White from offender-management. The team has set up alert with another route coming to moic-alerts. Can be ignored
