### ISSUE TITLE
Alarms Missing for Correspondence Staff Tool

### ISSUE THREAD

**Issue by misaka** [ministryofjustice/cloud-platform#505]
## Service name

Correspondence Staff Tool

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

We don't know when the service is down. Recently we've had a recurring issue that is occasionally taking one the service down, and we really should be getting alarms for this. 

## Problem description

We aren't receiving alarms. Recent outages that have made one of the prod servers unresponsive for long periods have not triggered any alarms.

## Contact person

misha.gorodnitzky@digital.justice.gov.uk

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloudplatforms-terraform-ops/pull/30
pingdom updated
21/11/2018 
Hi @misha @Raz  - think we will monitor things to see if the pingdom check gives us any more visibility. @misha could you perhaps please keep a log of times there are problems and we will see if pingdom reports problems? Lets close this ticket and open another one as required?
