### ISSUE TITLE
Unable to build correspondence- gpg: cannot open '/dev/tty': No such device or address

### ISSUE THREAD

**Issue by stephenrichards** [ministryofjustice/cloud-platform#506]
## Service name

correspondence_tool_staff

## Service environment

- [X ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Unable to build or deploy.  This is stopping us from current a bug fix to the live system

## Problem description

When building, get this output:

Preparing to unpack .../apt-transport-https_1.4.8_amd64.deb ...
Unpacking apt-transport-https (1.4.8) ...
Setting up apt-transport-https (1.4.8) ...
 ---> 96dcffc5d3b5
Removing intermediate container 62c6cd7bc24f
Step 6 : RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
 ---> Running in 6b46a9c199c3
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.mFx67KKJ8F/gpg.1.sh --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
gpg: cannot open '/dev/tty': No such device or address
The command '/bin/sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8' returned a non-zero code: 2
Build step 'Execute shell' marked build as failure
Strings match run condition: string 1=[demo], string 2=[none]
Run condition [Not] enabling perform for step [[Trigger parameterized build on other projects]]
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Strings match run condition: string 1=[demo], string 2=[none]
Run condition [Not] enabling perform for step [Builder to mark whether executed]
Finished: FAILURE

## Contact person

slack: stephenrichards
email: stephen.richards@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
fixed by using ipv4 IP for gpg keyserver and also --no-tty so warnings are not printed, this confused apt
