### ISSUE TITLE
Verify DNS Name Server records for migration of https://casetracker.justice.gov.uk/

### ISSUE THREAD

**Issue by mark-butler-solirius** [ministryofjustice/cloud-platform#5069]
## Service name

Civil Appeals Case Tracker (Namespace = civil-appeal-case-tracker-prod)
URL: https://casetracker.justice.gov.uk/

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [*] Prod / Production
- [ ] Other

## Impact on the service

Migration of production website from AWS Tactical Products account to Cloud Platform scheduled for Thursday 7th at 08.30am
We are bringing down the existing service at 07.00 am and migrating the resources across to CP.
The final step is to implement the DNS delegation.

## Problem description

We need to prepare for the migration of the Route 53 DNS of the above service into Cloud Platform.
I have generated a new Hosted Zone and certificate

`cloud-platform decode-secret -n civil-appeal-case-tracker-prod -s casetracker-route53-zone-output`
`cloud-platform decode-secret -n civil-appeal-case-tracker-prod -s casetracker-justice-app-cert-xcwzs`

1. Can you please verify that the certificate and hosted zone have been created correctly with the relevant A records and new NS records? 
2. Can you please provide the new NS records so that I can raise a PR to delegate the DNS from the current DSD Route 53 account? (assuming this is how it is still managed)

## Contact person
Mark Butler
mark.butler@HMCTS.NET

**Comment by sj-williams** [comment]
Complete.
https://mojdt.slack.com/archives/C57UPMZLY/p1701939273221939
