### ISSUE TITLE
Oracle RDS on Cloud Platform

### ISSUE THREAD

**Issue by cmehtarahul** [ministryofjustice/cloud-platform#5073]
## Service name
Oracle RDS on Cloud Platform

## Service environment
- [ ] Dev / Development
## Impact on the service
Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Looking at the potential to migrate older systems into Cloud Platform rather than Mod Platform

## Problem description

We are looking of the viability of migrating one of our older systems from LAA Landing Zone over to Cloud Platform. One of the current blockers is the ability to run Oracle RDS in Cloud Platform. Understanding if this is possible and being able to link with LZ and Mod Platform will enable us to understand the way forward. 
It's worth noting that the application itself is containerised and so an ideal candidate for being hosted on cloud platform except for the Oracle RDS database which is a dependency.

## Contact person
Rahul Mehta
Mike Reid
Paul King

Rahul.Mehta@digital.justice.gov.uk,
mike.reid@digital.justice.gov.uk
paul.king@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
Draft PR to support oracle in tf module: https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/pull/159
Namespace that uses oracle: https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/laa-crown-court-remuneration-sandbox-admin/resources/rds.tf

**Comment by poornima-krishnasamy** [comment]
Spoke to the service teams and the RDS - Oracle instance is up and running.
