### ISSUE TITLE
Investigation: Prometheus restarts

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5075]
## Background

We are still experiencing Prometheus restarts (4/12 & 5/12) triggering high priority alerts and prompting queries from CP users in the ask channel.

Following the approach of previous[ investigation ticket ](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4928), we have increased readiness & liveliness [probe values again](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/commit/4284a512abcb65d56853321fb728ff323589231d) - but we need to have a closer inspection and try to identify the root cause of these failures.

Kibana graph with recent [restart timestamps](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-04T10:30:00.000Z',to:'2023-12-05T15:00:00.000Z'))&_a=(columns:!(kubernetes.namespace_name),filters:!(),index:'167701b0-f8c0-11ec-b95c-1d65c3682287',interval:auto,query:(language:kuery,query:'%22prometheus-prometheus-operator-kube-p-prometheus-0%22%20and%20%22SIGTERM%22'),sort:!()))

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
Another restart pf prometheus occured on 15/01/2024: https://mojdt.slack.com/archives/C8PF51AT0/p1705315848195709

**Comment by sj-williams** [comment]
Stale ticket, prometheus architecture has changed substantially since this issue.
