### ISSUE TITLE
Update maintenance-page guidance to support short-lived credentials

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5078]
## Background

Users use the maintenance-page repo when they want to signpost end users when the app is updergoing any maintainance activity. https://github.com/ministryofjustice/cloud-platform-maintenance-page.

## Proposed user journey

The Readme suggest to build your own image and deploy in to the cluster. As the platform has stopped using long-terms credentials, it is not possible to get ecr dredentials to build the image locally.

## Approach

Update the readme to fork/copy the repo into the users own github repo and use their own app ecr repo and ci to build and push the maintenance page,

Example suggestion here: https://mojdt.slack.com/archives/C57UPMZLY/p1694099999454519

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform-maintenance-page?tab=readme-ov-file#custom-html

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mikebell** [comment]
Complete as part of https://github.com/ministryofjustice/cloud-platform-maintenance-page/pull/26
