### ISSUE TITLE
HTTP Streaming with HAProxy

### ISSUE THREAD

**Issue by misaka** [ministryofjustice/cloud-platform#508]
## Service name

Correspondence Staff Tool

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Problem description

We want to implement a streaming response to resolve another issue which is causing system outages in prod (generating a large CSV response). The streaming response has been implemented and works locally, but is breaking in dev. The main difference we can think of is nginx + haproxy.

## Contact person

misha.gorodnitzky@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
As discussed in Slack, the stream feature is HTTP/2 specific, which is not well supported by HAproxy (https://www.mail-archive.com/haproxy@formilux.org/msg28004.html), so we'll need to check 2 options:
1. Fix / add HTTP/2 support in HAproxy (might not be trivial) - raz
2. Try to implement the same functionality in HTTP/1.1 - misha

**Comment by razvan-moj** [comment]
This looks more like an protocol implementation issue in the application module, to test we
1. bypassed haproxy entirely by going to ELB->nginx
2. bypassed ELB, going directly to nginx
3. deployed the latest release of nginx&openssl in a separate container listening on port 444 

still curl shows alternatively 310 or 994 bytes of data, while the file is 6k
`curl -v -k -H 'Host: demo.track-a-query.service.justice.gov.uk' -H 'Cookie: seen_cookie_message=yes; _correspondence_platform_session=cookiefrombrowserhere;' https://34.242.177.196:444/cases/closed.csv
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 20 Nov 2018 16:32:40 GMT
< Content-Type: text/csv
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Expires: -1
< Strict-Transport-Security: max-age=31536000, includeSubDomains
< Content-Disposition: attachment; filename="closed-cases-2018-11-20-163240.csv"
< X-Request-Id: 2be440ca-9b02-41f4-a8be-c4f9d0560f19
< X-Runtime: 0.185669
<
{ [310 bytes data]
`

**Comment by razvan-moj** [comment]
putting on hold as discussed with @misaka ; dev team has the setup needed to test options, no change needed from us for now
