### ISSUE TITLE
New alert route in Alertmanager for HMPPS Integration API

### ISSUE THREAD

**Issue by emileswarts** [ministryofjustice/cloud-platform#5088]
## Service name

HMPPS Integration API

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

No impact, service isn't live yet

## Problem description

New alert route in Alertmanager.

namespace name: hmpps-integration-api-prod
team name: HMPPS Integration API Team
application name: HMPPS Integration API
slack channel: hmpps-integration-api-alerts
kubernetes secret name where the webhook url is stored: other-services/slack-webhook-url
severity level: warning

## Contact person

Name: Emile Swarts
Slack Handle: Emile Swarts
Email: emile.swarts@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
New Alertmanager route added. Please use the severity label: `hmpps-integration-api-alerts`  to be used in the prometheus rules to setup alerts
