### ISSUE TITLE
Remove ex-staff access

### ISSUE THREAD

**Issue by KPobeeNorris** [ministryofjustice/cloud-platform#509]
## Service name

PVB / Allocation Manager

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Alan Kennedy no longer works for MOJ and we are currently going through the process of removing his access to various services. We would like to request that any access he has via Cloud Platform (e.g. AWS/SSH) also be revoked.

## Problem description

We want to ensure ex-staff are unable to continue to access services within MOJ. 

## Contact person

Slack - @kath.pobee-norris

**Comment by lukaszraczylo** [comment]
pvb public: staging, prod
pvb staff : staging, prod
All mentioned environments were updated.
