### ISSUE TITLE
Test GKE features

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#510]
## Approach
Deploy test clusters in trial Google accounts, check feature parity where applicable

 - infrastructure cost
 - Terraform support
 - authentication methods
 - level of API access granted to admin users
 - privilege separation / multi-tenant
 - logging and monitoring is done by ?
 - can infrastructure can scale horizontally?

## Definition of done

Status of the list above is documented

**Comment by jasonBirchall** [comment]
Code will be stored here:
https://github.com/jasonBirchall/jcp-infrastructure

**Comment by jasonBirchall** [comment]
All questions answered and demo prepared.
