### ISSUE TITLE
Add 10.200.0.0/20 and 10.200.16.0/20 as outbound TransitGateway routes.

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/cloud-platform#5107]
## Service name

This requirement is in support of products currently hosted in the LAA LandingZone that are to be migrated to Cloud Platform in the new year.

Currently Cloud Platform has the following outbound routes via the TransitGateway attachment which route traffic to the 5 main LAA LandingZone VPCs:

- 10.202.0.0/20
- 10.203.0.0/20
- 10.204.0.0/20
- 10.205.0.0/20
- 10.206.0.0/20

The requirement is to add routing to our two Shared Services VPCs. The destination CIDRs are:

10.200.0.0/20
10.200.16.0/20

This is so the LAA Digital Product teams will be using AWS Workspaces hosted in these VPCs to administer code & data held within Oracle RDS databases that are part of the migration.

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Without this routing in place, the product teams will not be able to administer the databases & so we will need to migrate the services to Modernisation Platform, something that will take considerably longer.

## Problem description

The issue is that Cloud Platform has no routing via the TransitGateway to the LAA Shared Services VPCs which are required.

## Contact person

mike.reid@digital.justice.gov.uk / @mikereid 
rahul.mehta@digital.justice.gov.uk / @Rahul Mehta

**Comment by prakash-moj** [comment]
The required changes applied. The end users facing some issue which they are investigating.

More info here - https://mojdt.slack.com/archives/C57UPMZLY/p1702909842073469
