### ISSUE TITLE
PQ staging deployment issue

### ISSUE THREAD

**Issue by danielatdigital** [ministryofjustice/cloud-platform#512]
## Service name
PQ Tracker

## Service environment

- [ ] Dev / Development
- [ X ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service
Need to deploy security fix to live (but staging comes first)

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description
Deploy says OK, but site not loading (again)

https://ci.service.dsd.io/view/PQ/job/pq-deploy/181/console

## Contact person
@danielpenny

**Comment by lukaszraczylo** [comment]
First issue: Someone ran update on the cluster without including secrets file ( or without secrets file being decrypted ) which caused application lose the access to the database server. I've fixed it by re-running update which applied necessary env variables for containers.
