### ISSUE TITLE
AWS RDS permissions

### ISSUE THREAD

**Issue by farrepa** [ministryofjustice/cloud-platform#513]
## Service name

AWS

## Service environment

- [ ] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Development/product enhancement blocker

## Problem description

Could I get the `rds:DescribeDBInstances` permission assigned in AWS?  And the permissions required to update DB parameter groups?

I'm working on a ticket to turn on RDS logging for `cla-prod-read-replica`

## Contact person

patrick.farrell@digital.justice.gov.uk

**Comment by jasonBirchall** [comment]
Added `AmazonRDSReadOnlyAccess` to the required group in cla account.
