### ISSUE TITLE
EKS addon: Update kube-proxy from v1.25.15-eksbuild.2 to the latest version

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/cloud-platform#5132]
## Background

There is a new version of the EKS add-on kube-proxy. kube-proxy needs updating on the live cluster. When this issue was created, the latest supported add-on version for Kubernetes 1.25 was v1.25.16-eksbuild.1.

See the [Amazon EKS add-ons](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) documentation for more information about addons, or find the latest versions for these EKS add-ons directly:

- [coredns](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html)
- [kube-proxy](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)
- [vpc-cni](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html)

## Environments

- [ ] live2
- [ ] manager
- [ ] live

**Comment by sj-williams** [comment]
Tested upgrade to `v1.25.16-eksbuild.1`.

Diff shows only changes to:
```
deprecated.daemonset.template.generation
generation
resourceVersion
```

and `image`:

- before:
`602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/kube-proxy:v1.25.15-minimal-eksbuild.2`

- after:
`image: 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/kube-proxy:v1.25.16-minimal-eksbuild.1`

**Comment by sj-williams** [comment]
side note, submitted AWS support query re changelog information for kube-proxy and coredns addons:
https://support.console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=170600437301394&language=en
