### ISSUE TITLE
EKS addon: Update vpc-cni from v1.15.3-eksbuild.1 to the latest version

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/cloud-platform#5133]
## Background

There is a new version of the EKS add-on vpc-cni. vpc-cni needs updating on the live cluster. When this issue was created, the latest supported add-on version for Kubernetes 1.25 was v1.15.5-eksbuild.1.

NOTE - latest is now `1.16.0-eksbuild.1`

See the [Amazon EKS add-ons](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) documentation for more information about addons, or find the latest versions for these EKS add-ons directly:

- [coredns](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html)
- [kube-proxy](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)
- [vpc-cni](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html)

## Environments

- [ ] live-2
- [ ] manager
- [ ] live

**Comment by mikebell** [comment]
Changes:

* `CLUSTER_ENDPOINT` env variable has been removed, we're happy with this change so can ignore.
* `--conntrack-cache-cleanup-period=300` argument has been added - @jackstockley89 is looking into it

**Comment by jackstockley89** [comment]
Raised a support ticket on the conntrack change 
https://support.console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=170566391901114&language=en

**Comment by sj-williams** [comment]
Notes on this:


`conntrack-cache-cleanup-period=300` flag introduced from [network-policy-agent 1.0.7](https://github.com/aws/aws-network-policy-agent/pull/151) to replace env VAR setting.

Default value has not changed between 1.05 > 1.07, see:

https://github.com/aws/aws-network-policy-agent/blob/v1.0.5/controllers/policyendpoints_controller.go#L43
