### ISSUE TITLE
reset rattic user account

### ISSUE THREAD

**Issue by sid234** [ministryofjustice/cloud-platform#515]
## Service name

Rattic

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [x] Other

## Impact on the service

Unable to login to rattic service

## Problem description

Password reset for users SidElangovan & PaulWyborn. I think we locked out ourselves by trying too many failed attempts. Also the Forgot Password link does not work

## Contact person

@sid

**Comment by lukaszraczylo** [comment]
Passwords for both users changed, users notified using secure means.

**Comment by sid234** [comment]
works! thanks for the quick response!
