### ISSUE TITLE
Update cloud platform terraform module examples with relative source reference

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5159]
## Background

The examples folder of the terraform module is used by unit tests. But many of the terraform modules refer the latest release as source reference. Hence the unit tests doesnt check the PR changes.

e.g. https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/main/examples/rds-mariadb.tf

Update all examples to refer the source by relative reference. 

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Questions / Assumptions

cloud-platform-cli also uses this examples/ to generate terraform files. Update the cli before making the changes to modules that depend on cli

Blocked by: https://github.com/ministryofjustice/cloud-platform/issues/4830

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by timckt** [comment]
|   Modules Name | Status   |   
|---|---|
|   |   |   
|   |   |

**Comment by timckt** [comment]
|   Modules Name | Status   |   
|---|---|
|   |   |   
|   |   |   
|   |   |

**Comment by timckt** [comment]
|   Modules Name | Status   |   
|---|---|
|   |   |   
|   |   |   
|   |   |   |   |   |

**Comment by timckt** [comment]
| Modules Name | Status |   
|---|---|
| [CloudFront](https://github.com/ministryofjustice/cloud-platform-terraform-cloudfront) | NA |   
| [DMS](https://github.com/ministryofjustice/cloud-platform-terraform-dms) | Updated |   
| [ECR](https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials) |  |
| [DynamoDB Cluster](https://github.com/ministryofjustice/cloud-platform-terraform-dynamodb-cluster) | Updated  |   
| [ElastiCache for Redis cluster](https://github.com/ministryofjustice/cloud-platform-terraform-elasticache-cluster)  | NA   |   
| [IRSA](https://github.com/ministryofjustice/cloud-platform-terraform-irsa) | NA |
| [Service Account](https://github.com/ministryofjustice/cloud-platform-terraform-serviceaccount) | |
| [Service Pod](https://github.com/ministryofjustice/cloud-platform-terraform-service-pod) | |
