### ISSUE TITLE
Create a starter pack for test clusters

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#516]
## Background

When I create a new test cluster I would like to have a bundle of apps / resources to deploy on it that will help me test things I work on.

## Proposed user journey

When I create a cluster, I can then `kubectl apply -f starter-pack/`.

## Approach

Each team member selects one <thing> to add to the pack and provides a manifest for it.

## Definition of done

- [ ] we have a starter pack I can apply on a new test cluster
- [ ] the starter pack is in git (possibly in kubernetes-manifests?) 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ollieanwyll** [comment]
Going to implement the following:
*  demo- reference-app
* httpbin
*  Wordpress site
