### ISSUE TITLE
Investigate cloud-provider=external

### ISSUE THREAD

**Issue by mikebell** [ministryofjustice/cloud-platform#5163]
## Background

Attention: In EKS 1.26 the AWS specific logic in the kubelet has been disabled. If you used the EKS optimized AMI prior to 1.26, the kubelet was configured to use the in-tree cloud provider. This was configured by passing the --cloudprovider=aws flag to kubelet’s extra-args. This triggered the kubelet to call the EC2 DescribeInstance API which returned the PrivateDnsName of the instance. Starting with 1.26, the kubelet is configured to use --cloud-provider=external or --cloud-provider=“” by default. This could cause issues if you’re using a custom AMI and/or you’ve configured your VPC with a DHCP option set that includes a custom domain suffix, such as example.com. Unless you pass the --hostname-override=$PRIVATE_DNS_NAME flag to the kubelet’s extra-args, the kubelet will use the operating system’s hostname as the node name, e.g. i-0c9e5eff964fb6eea.example.com or ip-192-168-52.example.com. Nodes with names like this will fail to register with the cluster because the [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) expects the node’s name to always match the node’s PrivateDnsName. For additional information about this issue, see [Override hostname to match EC2’s PrivateDnsName](https://github.com/awslabs/amazon-eks-ami/pull/1264). The latest version of the EKS Optimized AMI, v20230501, has been updated to include the --hostname-override flag. If your nodes are having issues joining the cluster after upgrading to 1.26, please verify that you’re using v20230501 or higher. You can find the latest EKS Optimized AMI in your region by querying Parameter Store as described in [Retrieving Amazon EKS optimized Amazon Linux AMI IDs](https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html). Custom AMIs built from the Packer scripts available at [awslabs/amazon-eks-ami](https://github.com/awslabs/amazon-eks-ami) should be rebuilt using the latest version, [Release AMI Release v20230501](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230501).

## Approach
Does this affect our current cluster?

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed

**Comment by mikebell** [comment]
I don't think this is an issue because as far as I can tell we're not using a custom AMI.

**Comment by poornima-krishnasamy** [comment]
This is specific to custom AMI and because we have managed node group and CP cluster are provisioned with AWS recommended AMI.

`live` cluster uses the AMI : 1.25.15-20231201 which is higher than the one mentioned above: v20230501 
Test clsuter when upgraded uses `20240110` which is the latest one for 1.26 mentioned in the changelog :https://github.com/awslabs/amazon-eks-ami/blob/master/CHANGELOG.md

happy to close this
