### ISSUE TITLE
Update eventrouter image

### ISSUE THREAD

**Issue by jackstockley89** [ministryofjustice/cloud-platform#5171]
## Background

image version: 0.3.3 > 0.4.3
appVersion: 0.3  > 0.4

## Proposed user journey

update cloud-platform-helm-charts for Eventrouter to move to the latest version

## Approach

test updated image in a test cluster before applying to live clusters

## Definition of done

Update: https://github.com/ministryofjustice/cloud-platform/issues/5149

- [ ] readme has been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by poornima-krishnasamy** [comment]
The eventrouter repo is archived and hence look for alternatives. One of the option to spike is: https://github.com/ministryofjustice/cloud-platform/issues/5284

**Comment by poornima-krishnasamy** [comment]
We dont need eventrouter for CP. The feature has been covered by £5284. Closing
