### ISSUE TITLE
Show the thing 31/05/18

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform#52]
## Background

Cloud platform team scheduled to present at show the thing on 31/05/18

This ticket is to prepare a demo that we can show as part of show the thing. Bear in mind that:

* We only have 5 mins 
* It will be recorded
* You can use slides and a screen
* People watching will be varied in roles/interests -- there will be all team roles and also senior people from the MoJ Digital and Tech

@AntonyBishop will be the main presenter, you will be supporting him with the demo. So you need to work with him to identify what to demo and how it fits into his presentation.

## Thought

It would be really good to show something bringing value to users, rather than just some stuff we built.

## Done when

** This all needs to be done a couple of days before the 31st ** 

- [x] We have a less than 5 min demo of some of the work we have been doing
- [x] It fits into @AntonyBishop's presentation
- [ ] It has been practised to the team 
- [x] Someone is nominated to do it in the session

**Comment by AntonyBishop** [comment]
Decision - We are going to do a demo around the MVP

**Comment by AntonyBishop** [comment]
Discussing potential thing to demo - Deploying Test app with CircleCI

**Comment by AntonyBishop** [comment]
We will be doing a demo of deploying the test app using CircleCI. Tony will be doing the talk and Raz will run the demo.
