### ISSUE TITLE
CAS2 Pingdom slack integration request

### ISSUE THREAD

**Issue by tahb** [ministryofjustice/cloud-platform#5201]
## Service name

short-term-accommodation-cas-2

AKA: CAS2, Community Accommodation Tier 2, hmpps-community-accommodation-tier-2-ui

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Without this notification nobody will know if the service goes offline.

## Problem description

CAS2 would like Pingdom to send alerts to Slack when the service goes down so the team can respond.

CAS is made up of three tiers and they share the same namespace in the platform. We earlier added [this pingdom check for CAS1 and 3](https://github.com/ministryofjustice/cloud-platform/issues/4665). This request is to enable CAS2 to follow suite with another Slack integration.

team name: hmpps-community-accommodation-tier-2
application names: hmpps-community-accommodation-tier-2-ui
slack channel: #hmpps-cas-2-team-events

[We need an integration ID to put into the platform change here](https://github.com/ministryofjustice/cloud-platform-environments/pull/18814/files#diff-a07d28040bc185bdaeddf9a958a479d26cbd208f1f95f5502b043c4ddaac0ed3R27).

## Contact person

Tom Hipkin

**Comment by poornima-krishnasamy** [comment]
Hi @tahb , the integration id for this Pingdom integration is "133623"
