### ISSUE TITLE
New alert route in Alertmanager for Hale-Platform Namespaces

### ISSUE THREAD

**Issue by danielglen-moj** [ministryofjustice/cloud-platform#5212]
## Service name

Hale Platform

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [x] Demo

## Problem description

New alert route in Alertmanager in the following 3 namespaces. We already have this setup in hale-platform-dev

namespace name: hale-platform-staging, hale-platform-demo, hale-platform-prod
team name: Website Builder
application name: Hale-Platform
slack channel: website-builder-alerts
kubernetes secret name where the webhook url is stored: alert_slack_webhook_url  
severity level: warning

## Contact person

Name: Daniel Glen
Slack: @daniel.glen

**Comment by poornima-krishnasamy** [comment]
Hi @danielglen-moj , I see you have setup alert route for hale-platform-dev and wanted to configure the same for other environments. If the slack channel is going to be the same for all environments, you can use the same severity `hale-platform-alerts` to configure the prometheus alerts for all environments. You dont need a seperate route for each of the namespaces.

**Comment by danielglen-moj** [comment]
Thank you @poornima-krishnasamy - WIll close issue.
