### ISSUE TITLE
Spike: Implement KEDA for new scaling approach  

### ISSUE THREAD

**Issue by jackstockley89** [ministryofjustice/cloud-platform#5217]
## Background

User raised a ticket to investigate scaling services from CloudWatch metrics 

This work has been done in ticket #4679

## Approach

Test implementing KEDA in a test cluster 

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mikebell** [comment]
Came accross this talk from CNCF on Keda might be interesting - https://www.youtube.com/watch?v=-nbzE_tSSS4

**Comment by jackstockley89** [comment]
tested keda in a test cluster and created a module as a starting point for implementing keda in the future
https://github.com/ministryofjustice/cloud-platform-terraform-keda
