### ISSUE TITLE
Request a new alert route in AlertManager for CDA Prod

### ISSUE THREAD

**Issue by mtac50** [ministryofjustice/cloud-platform#5225]
## Service name

Court Data Adaptor

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

No impact to the live service

## Problem description

**namespace name**
For prod: laa-court-data-adaptor-prod

**team name**
laa-crime-apps-team

**application name**
laa-court-data-adaptor

**slack channel**
laa-court-data-adaptor-alerts-prod

**kubernetes secret name where the webhook url is stored:**
court-data-adaptor-alert-webhook-prod

**severity level:**
warning

## Contact person

Michael Clancy

**Comment by poornima-krishnasamy** [comment]
Hi @mtac50 , the severity label for this route is: `laa-court-data-adaptor-alerts-prod`. Please use this label when configuring the prometheus rules.
