### ISSUE TITLE
Decommission Legacy Transit Gateway

### ISSUE THREAD

**Issue by kyphutruong** [ministryofjustice/cloud-platform#5228]
## Background

As part of migrating the CP transit gateway to connect directly to PTTP transit gateway, the legacy Cloud Platform Transit Gateway needs to be decommissioned. This should be carried out after #4977 has been completed.

## Proposed user journey

Legacy transit gateway should no longer exist

## Approach

- Delete Transit Gateway VPC Attachments in `Cloud Platform Transit Gateways AWS account` (confirm with @julialawrence these can be deleted)
- Delete Transit Gateway Peering Attachment in  `Cloud Platform Transit Gateways AWS account` (confirm with @davidkelliott this can be deleted)
- Terraform destroy all redundant Transit Gateway related resources in Cloud Platform Transit Gateways AWS account that are currently being managed by terraform. These are mainly just the transit gateway and ram resources that are not in use.
- Remove redundant code from [transit-gateways repo](https://github.com/ministryofjustice/transit-gateways)
- Inform @davidkelliott legacy repo and account can been archived and closed.

## Which part of the user docs does this impact

https://runbooks.cloud-platform.service.justice.gov.uk/cloud-platform-to-tgw.html

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by julialawrence** [comment]
Pending confirming reviews of flow logs prior to deletion, this can be removed.
