### ISSUE TITLE
Setup permissions for S3 containers to moj-s3-virus-scan.

### ISSUE THREAD

**Issue by misaka** [ministryofjustice/cloud-platform#524]
## Service name

MoJ S3 Virus Scan

https://github.com/ministryofjustice/moj-s3-virus-scan

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Service is non-operational.

## Problem description

The service that's running doesn't have access to the bucket it needs to access. The way it's meant to work is it received an HTTP request with a bucket name a key for a file to scan. It downloads the file, performs the scan, and updates a key on the S3 object to indicate that it has been scanned. At the moment, I'm testing it with the bucket `correspondence-staff-case-uploads-dev` but we're going to need a way to give this service access to different buckets, for the correspondence-staff tool and potentially other S3 buckets if it's going to be used more widely.

## Contact person

misha.gorodnitzky@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
Decided to go with a form that allows users to edit their own bucket list and credentials; to authenticate said users an OIDC proxy linked to Auth0 will front the app.
Proxy deployed as defined in https://github.com/ministryofjustice/moj-s3-virus-scan/pull/2

**Comment by razvan-moj** [comment]
closing this as it's deviated quite a bit from the initial thoughts; will be resumed in a new one as the app evolves
