### ISSUE TITLE
EKS 1.26 Upgrade - Capture cluster components for updating

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5245]
## Background

This ticket is for checking all cluster component releases and capturing any updates available / recommended / required for 1.26 compatibility. Record the findings in comments below.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tom-j-smith** [comment]
Could be useful to make a runbook of the list of components running in the clusters.

**Comment by tom-j-smith** [comment]
https://docs.google.com/spreadsheets/d/1HaNLg2U86x5SFrSeXqALhfFn3z-G4tfHWBOhfTYPndc/edit?pli=1#gid=816615146

**Comment by poornima-krishnasamy** [comment]
https://github.com/ministryofjustice/cloud-platform/issues/5279
https://github.com/ministryofjustice/cloud-platform/issues/5280
