### ISSUE TITLE
Support setting up prototype on Cloud Platform

### ISSUE THREAD

**Issue by michaelchambersjnr** [ministryofjustice/cloud-platform#5253]
## Problem description

Having trouble setting up Cloud Platform on my machine, just need a bit of help to set up a new prototype for my team. Currently getting errors that I'm not familiar with to troubleshoot. 

## Contact person

Michael Chambers
https://moj.enterprise.slack.com/archives/D065MR419KQ

**Comment by poornima-krishnasamy** [comment]
User facing problem cloning and updating the prototype repo. Gave instructions on git password authentication.
