### ISSUE TITLE
Upgrade thanos to 0.34

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5281]
## Background

Current Thanos image in the cluster is 0.28.1. And the latest is 0.34.0. Upgrade thanos to latest available 

The thanos is seperate helm chart and can be upgraded independent of prometheus. 

Check if there is any version dependency with prometheus that this will be blocked.

## Which part of the user docs does this impact

https://runbooks.cloud-platform.service.justice.gov.uk/container-images.html

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
current
https://artifacthub.io/packages/helm/bitnami/thanos/11.6.2
newest
https://artifacthub.io/packages/helm/bitnami/thanos/13.1.0
