### ISSUE TITLE
Frequent Ingress Disconnects and Timeouts

### ISSUE THREAD

**Issue by mxco86** [ministryofjustice/cloud-platform#5289]
## Service name

Probation Integration Services

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Clients of API services are seeing a frequent need to retry requests adding overhead and noise to the overall running of services on Cloud Platform. Some teams are bypassing the CP ingress and using internal cluster URLs to access APIs.

## Problem description

Some of our teams have noticed frequent disconnects and timeouts when accessing API services via the CP ingress. The API service itself doesn’t receive the request and the client will either receive a `GOAWAY` frame or nothing at all. In most cases the client retries and the request then succeeds. When trying to replicate the issue we have seen up to 1/40 requests failing via the ingress. In testing using an internal service address we see no disconnects or request timeouts at all.

The problem is such that some teams have started bypassing the ingress and using service addresses for internal service to service communication, which is not ideal as it adds management overhead and means we are unable to use the capabilities of the ingress when required. We’d be happy to provide the data we have if someone were able to look into it.

## Contact person

Matthew Ryall, '@Matt Ryall', matthew.ryall@digital.justice.gov.uk

**Comment by andrewl** [comment]
Might be related to https://dsdmoj.atlassian.net/wiki/spaces/MRD/pages/4238213353/Connection+timeouts+to+Auth+endpoints ?

**Comment by andrewl** [comment]
I'm not sure this is fixed - https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/4f97f916f44ccd239bf34bcc96d48499

**Comment by poornima-krishnasamy** [comment]
Some more info on the slack thread: https://mojdt.slack.com/archives/C57UPMZLY/p1707903329123159?thread_ts=1707823359.330919&cid=C57UPMZLY

**Comment by jaskaransarkaria** [comment]
https://mojdt.slack.com/archives/C514ETYJX/p1709563385828399

Closing: Following a thorough investigation with the user we were able to pin down the issue to client-side issue with jdk/ spring and http2. We verified the ingress has no issues with http2 by load requesting several thousand http2 requests.
