### ISSUE TITLE
Remove old/outdated repos 

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform#53]
## Background

Cloud Platform and it's predecessors opened a lot of github repos, many of which are no longer required. We need to get rid of those repos that we no longer have a use for. 

## Done When

- [x] A list of all the Cloud Platform repos we can find is attached to this issue (they may not all have `cloud-platform` in their names). 
- [x] That list has been reviewed by the lead team members.
- [x] The unused/unneeded repos from this list have been removed.

**Comment by pwyborn** [comment]
https://docs.google.com/spreadsheets/d/1zeJjeRJMUwwYyi-tpJLI7P6N4hX3kSe5tbkOUu6Sf-I/edit#gid=0

**Comment by pwyborn** [comment]
Filter the spreadsheet column "Potentials" by "Yes"

**Comment by pwyborn** [comment]
![Screen Shot 2018-06-05 at 09.46.44.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/552623ee84cd341100ffe224/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f66b7191a378e60c2f57415b4abe5d4a1f06a3a3dc78e2a436628f0d5de883680d73c63f18acbb861fbf03bf76d84d83e0e99850d2aa6c7bb3d4d216744b470a83ed5c33aa984eca50f743e94956a311366af43b.png)

**Comment by pwyborn** [comment]
For reference - those not deleted/archived (as at 05/06/2018):
![Screen Shot 2018-06-05 at 09.51.59.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/552623ee84cd341100ffe224/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f66b7191a378e60c2e50415a47be5d4a1f06a3a3dc78e2a436628f0d5de883680d73c63f18acbb861fbf03bf76d84d83e0e99850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca50f743e84d56a01b3266f43b.png)
![Screen Shot 2018-06-05 at 09.52.28.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/552623ee84cd341100ffe224/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f66b7191a378e60c2e53415d46be5d4a1f06a3a3dc78e2a436628f0d5de883680d73c63f18acbb861fbf03bf76d84d83e0e99850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca50f743e84d5da116366af43b.png)
![Screen Shot 2018-06-05 at 09.52.59.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/552623ee84cd341100ffe224/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f66b7191a378e60c2e53415a47be5d4a1f06a3a3dc78e2a436628f0d5de883680d73c63f18acbb861fbf03bf76d84d83e0e99850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca50f743e84c57ac123661f43b.png)
![Screen Shot 2018-06-05 at 09.53.32.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/552623ee84cd341100ffe224/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f66b7191a378e60c2e52415c4cbe5d4a1f06a3a3dc78e2a436628f0d5de883680d73c63f18acbb861fbf03bf76d84d83e0e99850d2aa6c7bb3d4d216744b470a83ed5c33aa984eca50f743e84c5da6143464f43b.png)
