### ISSUE TITLE
Update gavinbunny/kubectl provider that is pinned

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5301]
## Background

We have been pinning `gavinbunney/kubectl` terraform provider at v1.13.2 for a while now. Dependabot wants to bump to latest release v1.14.0. This currently errors at components level plan/apply due to mismatch with components level modules also pinning the provider.

Test bumping to 1.14.0 in test cluster & components modules.

is the provider still upated or do we need to look for alternative

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
This ticket will be rendered obsolete; we are now switching from gavinbunney/kubectl to alekc.

Relevant ticket:
https://github.com/orgs/ministryofjustice/projects/65/views/3?pane=issue&itemId=56046700
