### ISSUE TITLE
Remove Erlestoke from ACL/WAF for Prisoner Content Hub Development Cloudfront

### ISSUE THREAD

**Issue by Eli-TW** [ministryofjustice/cloud-platform#5306]
## Service name

Prisoner Content Hub

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Development Cloudfront WAF for Prisoner Content Hub has a (now) unnecessary set of IP addresses whitelisted.

## Problem description

https://github.com/ministryofjustice/cloud-platform/issues/5293 was implemented to test the Cloudfront WAF/ACL into a prison environment using the development Cloudfront bucket. This is no longer required, and the IP addresses added to the WAF for Erlestoke under that ticket should now be removed from the development Cloudfront WAF.

## Contact person

Elliot Ward / elliot.ward@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
The Ip address related to Erlestoke has been removed. And the resource has been updated with the latest list.
