### ISSUE TITLE
S3 bucket policy.

### ISSUE THREAD

**Issue by EarthlingDavey** [ministryofjustice/cloud-platform#5308]
## Service name

[justice-gov-uk](https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live.cloud-platform.service.justice.gov.uk/justice-gov-uk-dev)

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Images and media cannot be put in an S3 bucket.

## Problem description

We are using S3, CloudFront and server roles. A WordPress plugin that we're using has the following [minimum requirements](https://deliciousbrains.com/wp-offload-media/doc/custom-iam-policy-for-amazon-s3/#minimum-policy):

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ObjectLevel",
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:DeleteObject"
      ],
      "Resource": "arn:aws:s3:::mybucket/*"
    },
    {
      "Sid": "BucketLevel",
      "Effect": "Allow",
      "Action": [
        "s3:GetBucketPublicAccessBlock",
        "s3:GetBucketOwnershipControls",
        "s3:ListBucket",
        "s3:GetBucketLocation"
      ],
      "Resource": "arn:aws:s3:::mybucket"
    }
  ]
}
```

We are troubleshooting why it's not working, and suspect that some of these permissions are missing. Or, possibly all of the permissions are being overwritten by the policy that allows CloudFront access. 

I have spoken to @poornima-krishnasamy on slack. She had the following suggestion, which we would like to try.

> I can create a branch for you which would have those permissions and u can try and see if that fixes your problem. 

Thank you.

## Contact person

Davey Brown - slack: @Davey

Thread: https://mojdt.slack.com/archives/C57UPMZLY/p1708358036487829

**Comment by poornima-krishnasamy** [comment]
Hi @EarthlingDavey , can you try this branch `add-perms` for your s3 module and test if that permissions help.

**Comment by poornima-krishnasamy** [comment]
Hi @EarthlingDavey , is the permissions added for s3 fixed the issue?

**Comment by EarthlingDavey** [comment]
@poornima-krishnasamy unfortunately we haven't resolved the plugin issue yet. But, this branch could be part of the solution.

Until now, we have been loosing some logs, I think sterr has been captured in kibana, but stout is being missed. 
Tomorrow I plan to write everything to sterr and hopefully see some meaningful logs.

**Comment by EarthlingDavey** [comment]
BTW the plugin author has suggested opening up all S3 permissions and working our way backwards once it's working. I assume that's probably not a good approach.

**Comment by poornima-krishnasamy** [comment]
stdout and stderr should be outputted to container logs. Check if you see both stdout and stderr when u do `kubectl logs <pod-name> -n <amespace>

By open all s3 permissions, what issue u were trying to solve? If it is just to test if its permissions the real issue, I can update the branch to perform all operations on that bucket. But if u know that permissions are the real issue, adding permissions one by one until it resolves would be a good approach. By going reverse, we will end up with more permissions than needed.

**Comment by EarthlingDavey** [comment]
Hey @poornima-krishnasamy I just fixed our issue after forcing WordPress to log all WP_Errors. I needed to set an option `'use-bucket-acls' => false` on the plugin, it was not documented.

I'll trial our environment with 5.1.0 and let you know the outcome.

Thanks for sharing the methodology around adding permissions rather than going reverse. Hopefully it won't come to that now :)
