### ISSUE TITLE
Attempt to create Amazon SMTP credentials fails

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#531]
## Problem description

I'm trying to create a set of SMTP credentials for sending emails with Amazon SES, but when I try, it fails with the following error message:

```
We encountered the following errors while processing your request:   
User: arn:aws:iam::880656497252:user/JesusLaiz is not authorized to perform: iam:ListUsers on resource: arn:aws:iam::880656497252:user/
```

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html?icmpid=docs_ses_console

## Contact person

Jesus @ slack

**Comment by jasonBirchall** [comment]
After a chat with @zheileman the ability to create iam users will remain restricted.
