### ISSUE TITLE
EKS: Planning upgrade to EKS 1.27

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5314]
## Background

Go through the release notes of EKS 1.27 and create a plan to upgrade our clusters

Things to consider:

- Review changelog & release notes
- EKS Module support at current version?
- Are there any API deprecations & removals? (Check insights)
- Are there new components being added?
- What changes are being introduced to current components?
- Are there changes to core infra of the CP required? i.e. Are all our current components compatible with 1.27?
- Are there changes users need to make?
- Do we need to expand any of our smoke/integration testing?

- Create EPIC & individual tickets for upgrade work as per cluster upgrade template [WIP]
- Create additional tickets needed for any findings specific to this upgrade.

https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-27/

Cluster upgrade Runbook:
https://runbooks.cloud-platform.service.justice.gov.uk/upgrade-eks-cluster.html

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by timckt** [comment]
https://docs.google.com/spreadsheets/d/1iE1SyrZJffgwJyWECH9lGXKI7wmy0aHD6EYAg9IzIxk/edit#gid=2041369881
