### ISSUE TITLE
Firebreak idea: Setup GuardDuty in AWS Cloud Platform Account

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#532]
GOAL: 
- Setup GuardDuty in Cloud Platform AWS account
- All managed via terraform in the infrastructure repo. 
- Docs, docs, docs
- GuardDuty > slack integration
- Runbook created for events.

SOURCE:
https://aws.amazon.com/guardduty/

IDEA/INSPIRATION:
https://github.com/ministryofjustice/laa-aws-infrastructure/tree/master/security

**Comment by sid234** [comment]
Reference -
https://github.com/trussworks/terraform-aws-guardduty-notifications
https://github.com/LeapBeyond/terraform-aws-guardduty

**Comment by pwyborn** [comment]
To Do:
* Documentation
* Set up sub-aws accounts
* Consider - how to alert from guardduty only for higher priority alerts (currently alerting for all low/medium/high)

**Comment by pwyborn** [comment]
All done - however On suggestion of Jason - a restructure of global-resources so that guardduty state is included. Problem with the existing auth0 terraform which Jason is looking into. Once sorted I will run terraform plan/apply again in new location. Maybe terraform destroy before I re-create

**Comment by pwyborn** [comment]
Done - however there is a bug with the iplist. This will be raised as an aws issue
So will need a new ticket for this + the next stage to create lambda functions to take action when findings raised (will need to pai with Sid on this)?

**Comment by pwyborn** [comment]
Reopened to fix iplist bug:
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/147

**Comment by pwyborn** [comment]
Fixed (Thank you Sid)
