### ISSUE TITLE
FIREBREAK: Revisit ACK to manage AWS services

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5324]
## Background

Cloud Platform has spiked the features of AWS Controller for Kubernetes in this ticket:
https://github.com/ministryofjustice/cloud-platform/issues/2647. But this project was in its early years. Revisit if the tool will be useful for provisioning resources like RDS, s3 etc

There is also a user request to explore this tool to provision lambda functions. Explore the options to how this can be used in a multi-tenancy approach.
https://github.com/ministryofjustice/cloud-platform/issues/4081 

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Does next steps require User Research?
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by timckt** [comment]
https://github.com/aws-controllers-k8s/community

https://aws-controllers-k8s.github.io/community/docs/community/overview/

**Comment by timckt** [comment]
Finding document: https://docs.google.com/document/d/1oWATEEPyTn0MWpJbvZiTz2TX5AKq-1NYVlKf8OQFh2Q/edit?usp=sharing

**Comment by timckt** [comment]
We already have mature, stable, and efficient workflows using GitOps with Terraform. Advantage of current version ACK may not be justified. We should keep our existing practice.
