### ISSUE TITLE
External-dns: Route53 Throttling Errors

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5326]
## Background
We continue to see Throttling Errors in External DNS alarms. We should have another review of our configuration for external-dns, and see if we can tune our polling frequency (perhaps look at different values for non-prod clusters too)?

Route53 Throttling guidance:
https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md#throttling

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Fixed test cluster filtering config for production clusters
https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/commit/7199bdb59009eff9fb30d72ca74b83580179427a

**Comment by sj-williams** [comment]
Increased batch-change value:
https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/commit/1dd7c891365a7719fef8c5f2a97d3339afe9e42f

**Comment by sj-williams** [comment]
Reduce API polling for test clusters

https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/pull/49

**Comment by poornima-krishnasamy** [comment]
The throtlling rate is reduced subsequently as the time at which the throtling is detected has been updated. Run it for another week to get the stats and check if the alert is actually capturing every problematic scenario and not miss any

![Image](https://github.com/ministryofjustice/cloud-platform/assets/51324851/7adde071-a0d1-4bed-aed7-1a164fe368db)
