### ISSUE TITLE
Reducing replica count for ingress controller on test clusters

### ISSUE THREAD

**Issue by kyphutruong** [ministryofjustice/cloud-platform#5328]
## Background

Replica count for `ingress-controller` is `12` at the moment. With test cluster node instances currently being at 8GiB (instance type `m6a.large`, and `ingress-controller` requesting at least 12 x 1GiB), any node on a test cluster can quickly reach the threshold, making that node _unschedulable_ 

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
Still reducing the number of controllers because it's unnecessary to have 12 on a test cluster and it won't impact the majority of testing
