### ISSUE TITLE
Request a new alert route in AlertManager for CMA Prod

### ISSUE THREAD

**Issue by mtac50** [ministryofjustice/cloud-platform#5337]
## Service name

Crime Means Assessment

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

No impact to the live service

## Problem description

namespace name
For prod: laa-crime-means-assessment-prod

team name
laa-crime-apps-team

application name
laa-crime-means-assessment

slack channel
laa-crime-means-assessment-alerts-prod

kubernetes secret name where the webhook url is stored:
crime-means-assessment-alert-webhook-prod

severity level:
laa-crime-means-assessment-alerts-prod

## Contact person

Michael Clancy

**Comment by poornima-krishnasamy** [comment]
New route added : https://alertmanager.cloud-platform.service.justice.gov.uk/#/status
Severity: laa-crime-means-assessment-alerts-prod
