### ISSUE TITLE
Get notifications about potentially/actually hitting quota limits

### ISSUE THREAD

**Issue by solidgoldpig** [ministryofjustice/cloud-platform#534]
## Service name

Form Builder

## Service environment

- [ x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

No new services could be deployed

## Problem description

Form Builder hit its memory quota limit and new pods were failing to be created.

```
45m         56m          9       jeez-test-1-76f57d5558.156b95afb9232662                                            ReplicaSet                                                                       Warning   FailedCreate            replicaset-controller                                   (combined from similar events): Error creating: pods "jeez-test-1-76f57d5558-q9467" is forbidden: exceeded quota: namespace-quota, requested: requests.memory=128Mi, used: requests.memory=8Gi, limited: requests.memory=8Gi
```

Obviously we need to update our scripts that check whether our pods actually have been created  rather than just rely on the fact we have managed to create the deployment.

However, it would be nice for platforms to automatically alert the namespace owner that the quota is about to be/has been exceeded. I was actually under the impression that this already happened (or that platforms at least kept an eye on such things) - so maybe it's just that Form Builder hasn't configured something correctly? 

## Contact person

Alex Robinson
@solidgoldpig 
@alex.robinson (slack)
alex.robinsn@digital.justice.gov.uk

**Comment by jasonBirchall** [comment]
@AntonyBishop Original issue has been resolved but can this go into backlog grooming?

**Comment by AntonyBishop** [comment]
Will create a new ticket for the backlog for alerting owners when quotas about to be exceeded. Thanks @jasonBirchall

**Comment by AntonyBishop** [comment]
Resolved
