### ISSUE TITLE
Update vpc-cni from `v1.16.2-eksbuild.1` to the version needed for current k8s version

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5342]
Check for the latest supported addon version for the current kubernetes version and update the clusters

Production Clusters Checklist:

- [ ] live-2
- [ ] manager
- [ ] live

See the [Amazon EKS add-ons](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) documentation for more information about addons, or find the latest versions for these EKS add-ons directly:

- [coredns](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html)
- [kube-proxy](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)
- [vpc-cni](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html)

 Related to: #5341

**Comment by timckt** [comment]
As of 06-03, the latest version of vpc-cni for k8s 1.26 is v1.16.3-eksbuild.2, will upgrade to it.

```
➜  ~ git:(main) ✗ eksctl utils describe-addon-versions --kubernetes-version 1.26 --name vpc-cni | grep AddonVersion
			"AddonVersions": [
					"AddonVersion": "v1.16.3-eksbuild.2",
					"AddonVersion": "v1.16.2-eksbuild.1",
					"AddonVersion": "v1.16.0-eksbuild.1",
					"AddonVersion": "v1.15.5-eksbuild.1",
					"AddonVersion": "v1.15.4-eksbuild.1",
					"AddonVersion": "v1.15.3-eksbuild.1",
					"AddonVersion": "v1.15.1-eksbuild.1",
					"AddonVersion": "v1.15.0-eksbuild.2",
					"AddonVersion": "v1.14.1-eksbuild.1",
					"AddonVersion": "v1.14.0-eksbuild.3",
					"AddonVersion": "v1.13.4-eksbuild.1",
					"AddonVersion": "v1.13.3-eksbuild.1",
					"AddonVersion": "v1.13.2-eksbuild.1",
					"AddonVersion": "v1.13.0-eksbuild.1",
					"AddonVersion": "v1.12.6-eksbuild.2",
					"AddonVersion": "v1.12.6-eksbuild.1",
					"AddonVersion": "v1.12.5-eksbuild.2",
					"AddonVersion": "v1.12.0-eksbuild.2",
```

**Comment by timckt** [comment]
https://github.com/aws/amazon-vpc-cni-k8s/issues/2807
Some user reported that with vpc-cni `v1.16.3-eksbuild.2` and they are facing high CPU usage on medium instance size and we decide to skip this version.

`v1.16.4` is released and will test it when it is propogated to AWS architecture.

**Comment by timckt** [comment]
`v1.16.4-eksbuild.2` is propogated to AWS architecture. Will test and implement after verification.

```
➜  ~ git:(main) ✗ eksctl utils describe-addon-versions --kubernetes-version 1.26 --name vpc-cni | grep AddonVersion
			"AddonVersions": [
					"AddonVersion": "v1.16.4-eksbuild.2",
					"AddonVersion": "v1.16.3-eksbuild.2",
					"AddonVersion": "v1.16.2-eksbuild.1",
					"AddonVersion": "v1.16.0-eksbuild.1",
					"AddonVersion": "v1.15.5-eksbuild.1",
					"AddonVersion": "v1.15.4-eksbuild.1",
					"AddonVersion": "v1.15.3-eksbuild.1",
					"AddonVersion": "v1.15.1-eksbuild.1",
					"AddonVersion": "v1.15.0-eksbuild.2",
					"AddonVersion": "v1.14.1-eksbuild.1",
					"AddonVersion": "v1.14.0-eksbuild.3",
					"AddonVersion": "v1.13.4-eksbuild.1",
					"AddonVersion": "v1.13.3-eksbuild.1",
					"AddonVersion": "v1.13.2-eksbuild.1",
					"AddonVersion": "v1.13.0-eksbuild.1",
					"AddonVersion": "v1.12.6-eksbuild.2",
					"AddonVersion": "v1.12.6-eksbuild.1",
					"AddonVersion": "v1.12.5-eksbuild.2",
					"AddonVersion": "v1.12.0-eksbuild.2",
```

**Comment by timckt** [comment]
bump vpc-cni to `v1.16.4-eksbuild.2` with https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2891
