### ISSUE TITLE
Test EKS 1.27 on live-like cluster

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5346]
Follow instructions from creating a live like cluster runbook: https://runbooks.cloud-platform.service.justice.gov.uk/creating-a-live-like.html#creating-a-live-like-cluster

 Related to: #5341

**Comment by timckt** [comment]
1. Completed the upgrade in the live live cluster.

| Node Group | Time |
|-|-|
| Monitoring Node Group - 2 nodes | ~ 30 mins |
| Default Node Group - 55 Nodes | ~ 170 mins|

2. In the live like cluster terraform workspace, run `terraform plan` and no change is present with ```cluster_version = { default = 1.27 }```.



![Image](https://github.com/ministryofjustice/cloud-platform/assets/152907271/120f9e54-a1e5-4d0c-94a5-598e5798b490)

**Comment by timckt** [comment]
After switching kubectl provider, created a live like test cluster

1. Completed the upgrade in the live live cluster and the below table shows that time used for each component.

| Node Group | Time |
|-|-|
| Control Plane | ~ 10 mins |
| Monitoring Node Group - 2 nodes | ~ mins |
| Default Node Group - 55 Nodes | ~ mins|

**Comment by timckt** [comment]
5. After scaling down the default node group, bump up the starter_package and `terraform apply` success.


![Image](https://github.com/ministryofjustice/cloud-platform/assets/152907271/2840859f-c2be-48fc-8795-ce8935218afc)


6. Scaling down the starter_package and `terraform apply` success.


![Image](https://github.com/ministryofjustice/cloud-platform/assets/152907271/9c795329-9983-4978-b487-c59e55d7e337)

**Comment by timckt** [comment]
7. After a night of soaking in for the new cluster, bump up the starter_package and `terraform apply` success.


![Image](https://github.com/ministryofjustice/cloud-platform/assets/152907271/37adb65d-baf3-4461-86ac-5342078c69cd)

**Comment by timckt** [comment]
8. Updated gatekeeper version (ministryofjustice/cloud-platform#5372) and the integration test (ministryofjustice/cloud-platform#5373). 
Integration test success.


![Image](https://github.com/ministryofjustice/cloud-platform/assets/152907271/9e417ec0-f3c8-4f9b-9023-191eb726521f)
