### ISSUE TITLE
EKS: Upgrade Production clusters to Kubernetes 1.27

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5347]
https://runbooks.cloud-platform.service.justice.gov.uk/upgrade-eks-cluster.html

Production Clusters Checklist:

- [x] live-2
- [x] manager
- [x] live

 Related to: #5341

**Comment by timckt** [comment]
live-2 upgraded to k8s 1.27. https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2934
