### ISSUE TITLE
Update vpc-cni to the latest version for the upgraded k8s 1.27

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5348]
Check for the latest supported addon version for the upgraded kubernetes version and update the clusters

Production Clusters Checklist:

- [ ] live-2
- [ ] manager
- [ ] live

See the [Amazon EKS add-ons](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) documentation for more information about addons, or find the latest versions for these EKS add-ons directly:

- [coredns](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html)
- [kube-proxy](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)
- [vpc-cni](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html)

 Related to: #5341

**Comment by timckt** [comment]
As of 26-03, the latest version on k8s 1.27 for vpc-cni is v1.17.1-eksbuild.1

```
→  eksctl utils describe-addon-versions --kubernetes-version 1.27 --name vpc-cni | grep AddonVersion
			"AddonVersions": [
					"AddonVersion": "v1.17.1-eksbuild.1",
					"AddonVersion": "v1.16.4-eksbuild.2",
					"AddonVersion": "v1.16.3-eksbuild.2",
					"AddonVersion": "v1.16.2-eksbuild.1",
					"AddonVersion": "v1.16.0-eksbuild.1",
					"AddonVersion": "v1.15.5-eksbuild.1",
					"AddonVersion": "v1.15.4-eksbuild.1",
					"AddonVersion": "v1.15.3-eksbuild.1",
					"AddonVersion": "v1.15.1-eksbuild.1",
					"AddonVersion": "v1.15.0-eksbuild.2",
					"AddonVersion": "v1.14.1-eksbuild.1",
					"AddonVersion": "v1.14.0-eksbuild.3",
					"AddonVersion": "v1.13.4-eksbuild.1",
					"AddonVersion": "v1.13.3-eksbuild.1",
					"AddonVersion": "v1.13.2-eksbuild.1",
					"AddonVersion": "v1.13.0-eksbuild.1",
					"AddonVersion": "v1.12.6-eksbuild.2",
					"AddonVersion": "v1.12.6-eksbuild.1",
					"AddonVersion": "v1.12.5-eksbuild.2",
```

**Comment by timckt** [comment]
vpc-cni `v1.17.1` introduce [NETWORK_POLICY_ENFORCING_MODE](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/README.md#network_policy_enforcing_mode-v1171), which maybe useful when we would like to tighten our security standard.

**Comment by timckt** [comment]
Integration test for new vpc-cni.


![Image](https://github.com/ministryofjustice/cloud-platform/assets/152907271/b061d8b7-305e-4190-b16c-4e13559cd522)
