### ISSUE TITLE
Update kube-proxy to the latest version for the upgraded k8s 1.27

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5349]
Check for the latest supported addon version for the upgraded kubernetes version and update the clusters

Production Clusters Checklist:

- [ ] live-2
- [ ] manager
- [ ] live

See the [Amazon EKS add-ons](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) documentation for more information about addons, or find the latest versions for these EKS add-ons directly:

- [coredns](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html)
- [kube-proxy](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)
- [vpc-cni](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html)

 Related to: #5341

**Comment by timckt** [comment]
As of 26-03, the latest version on k8s 1.27 for kube-proxy is v1.27.10-eksbuild.2

```
→  eksctl utils describe-addon-versions --kubernetes-version 1.27 --name kube-proxy | grep AddonVersion
			"AddonVersions": [
					"AddonVersion": "v1.27.10-eksbuild.2",
					"AddonVersion": "v1.27.8-eksbuild.4",
					"AddonVersion": "v1.27.8-eksbuild.1",
					"AddonVersion": "v1.27.6-eksbuild.2",
					"AddonVersion": "v1.27.4-eksbuild.2",
					"AddonVersion": "v1.27.3-eksbuild.2",
					"AddonVersion": "v1.27.3-eksbuild.1",
					"AddonVersion": "v1.27.1-eksbuild.1",
					"AddonVersion": "v1.26.13-eksbuild.2",
					"AddonVersion": "v1.26.11-eksbuild.4",
					"AddonVersion": "v1.26.11-eksbuild.1",
					"AddonVersion": "v1.26.9-eksbuild.2",
					"AddonVersion": "v1.26.7-eksbuild.2",
					"AddonVersion": "v1.26.6-eksbuild.2",
					"AddonVersion": "v1.26.6-eksbuild.1",
					"AddonVersion": "v1.26.4-eksbuild.1",
					"AddonVersion": "v1.25.16-eksbuild.3",
					"AddonVersion": "v1.25.16-eksbuild.2",
					"AddonVersion": "v1.25.16-eksbuild.1",
					"AddonVersion": "v1.25.15-eksbuild.2",
					"AddonVersion": "v1.25.14-eksbuild.2",
					"AddonVersion": "v1.25.11-eksbuild.2",
					"AddonVersion": "v1.25.6-eksbuild.2",
```

**Comment by timckt** [comment]
The difference between before and after pod yaml file for kube-proxy are similarly the same, just some IP and image difference

**Comment by timckt** [comment]
integration test for new kube proxy passed.


![Image](https://github.com/ministryofjustice/cloud-platform/assets/152907271/ff532ce9-63a6-4db9-abef-e6048be30238)
