### ISSUE TITLE
Update Form Builder's dev quotas

### ISSUE THREAD

**Issue by solidgoldpig** [ministryofjustice/cloud-platform#535]
## Service name

Form Builder

## Service environment

- [ x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

We're very close to our memory quota - that will prevent users creating new forms via our Publisher service

## Problem description

We need to update our quotas - I'm not expert enough in K8s to know what we should change them too and would appreciate discussing what sane values should be.

## Contact person

Alex Robinson
@solidgoldpig 
@alex.robinson (slack)
alex.robinsn@digital.justice.gov.uk

**Comment by jasonBirchall** [comment]
Opened communication channel with Alex.

**Comment by jasonBirchall** [comment]
Current resource usage:
```
Resource Quotas
 Name:            namespace-quota
 Resource         Used     Hard
 --------         ---      ---
 limits.cpu       15       20
 limits.memory    18000Mi  64Gi
 requests.cpu     6        10
 requests.memory  7680Mi   8Gi
```

**Comment by jasonBirchall** [comment]
Updated the env mem alloc to 16GiB as requested by user.
