### ISSUE TITLE
Update core-dns to the latest version for the upgraded k8s 1.27

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5350]
Check for the latest supported addon version for the upgraded kubernetes version and update the clusters

Production Clusters Checklist:

- [ ] live-2
- [ ] manager
- [ ] live

See the [Amazon EKS add-ons](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) documentation for more information about addons, or find the latest versions for these EKS add-ons directly:

- [coredns](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html)
- [kube-proxy](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)
- [vpc-cni](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html)

 Related to: #5341

**Comment by timckt** [comment]
As of 26-03, the latest version on k8s 1.27 for coredns is v1.10.1-eksbuild.7

```
~ →  eksctl utils describe-addon-versions --kubernetes-version 1.27 --name coredns | grep AddonVersion
			"AddonVersions": [
					"AddonVersion": "v1.10.1-eksbuild.7",
					"AddonVersion": "v1.10.1-eksbuild.6",
					"AddonVersion": "v1.10.1-eksbuild.5",
					"AddonVersion": "v1.10.1-eksbuild.4",
					"AddonVersion": "v1.10.1-eksbuild.3",
					"AddonVersion": "v1.10.1-eksbuild.2",
					"AddonVersion": "v1.10.1-eksbuild.1",
					"AddonVersion": "v1.9.3-eksbuild.11",
					"AddonVersion": "v1.9.3-eksbuild.10",
					"AddonVersion": "v1.9.3-eksbuild.9",
					"AddonVersion": "v1.9.3-eksbuild.7",
					"AddonVersion": "v1.9.3-eksbuild.6",
					"AddonVersion": "v1.9.3-eksbuild.5",
					"AddonVersion": "v1.9.3-eksbuild.3",
```

**Comment by timckt** [comment]
integration test pass for new coredns version.


![Image](https://github.com/ministryofjustice/cloud-platform/assets/152907271/bbb0f28c-10d4-4d2e-9bed-a316ea88c563)

**Comment by timckt** [comment]
The node-role.kubernetes.io/master tolerations will be disappeared in new coredns.
![Image](https://github.com/ministryofjustice/cloud-platform/assets/152907271/415bb0d9-9611-411e-ac9c-91c1176d3495)

**Comment by timckt** [comment]
In the test cluster coredns deployment, the default replicas will be decreased from 5 to 3



![Image](https://github.com/ministryofjustice/cloud-platform/assets/152907271/4e364c3e-5b72-4a6c-ac12-eaa09b377ee8)
