### ISSUE TITLE
Fix Correspondence Tool Bucket Access Policies

### ISSUE THREAD

**Issue by misaka** [ministryofjustice/cloud-platform#536]
## Service name

Correspondence Tool Staff

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Buckets are accessible from any AWS account.

## Problem description

The ACLs for the Correspondence Tool Staff buckets allow access from any AWS account. Although this doesn't seem to include reading object data, it does include listing objects at a minimum. In trying to fix this, I've removed this access on the dev bucket to test it, but this breaks the application.

The buckets in question:

dev -- this one has had public access removed, but this has broken the dev instance of the app.
staging&prod -- still accessible to the public

## Contact person

misha

**Comment by razvan-moj** [comment]
Not sure what is expected from us: remove the ACLs and break the app? Rewrite the app so it doesn't break? Let's clarify please the steps

**Comment by misaka** [comment]
@razvan-moj Agreed. How can we make the buckets accessible to the app? Via the IAM Role assigned to the EC2 instances?

**Comment by razvan-moj** [comment]
yes, done for dev, if all looks fine will copy to stg&prd

**Comment by misaka** [comment]
We've discovered the error in the policy setup (the bucket specified was for the Correspondence Tool, not the Correspondence Staff Tool). Fixed and now working as expected, we'll continue to remove public permissions on the buckets.
