### ISSUE TITLE
Create new concourse pipeline to test SCI clusters

### ISSUE THREAD

**Issue by mikebell** [ministryofjustice/cloud-platform#5361]
## Background

Once the cloud platform cli has been updated to handle the new `core` layer we need to create a new pipeline in concourse to test the builds.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
- create and do not destroy cluster (run test clusters against)
- use live as a pipeline a structure cd into dir and plan and apply (use the test cli)

**Comment by mikebell** [comment]
Not needed
