### ISSUE TITLE
New alert routes in alertmanager for  legacy-replacement-alerts and legacy-replacement-alerts-non-prod

### ISSUE THREAD

**Issue by ldlharper** [ministryofjustice/cloud-platform#5362]
## Service name

hmpps-adjustments
hmpps-adjustments-api
hmpps-unused-deductions-listener
calculate-release-dates-api
calculate-release-dates
hmpps-custody-manager-api
hmpps-custody-manager-ui

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Problem description

We would like two new alert severities, legacy-replacement-alerts and legacy-replacements-alerts-non-prod. The slack channels are #legacy-replacement-alerts and #legacy-replacements-alerts-non-prod

I've created secrets containing the webhook URL within hmpps-adjustments-dev for legacy-replacements-alerts-non-prod and hmpps-adjustments-prod for legacy-replacement-alert.

## Contact person

Luke Harper
luke.harper@digital.justice.co.uk

**Comment by tmahmood72** [comment]
The **non-prod** Alertmanager route is created with severity legacy-replacements-alerts-non-prod

**Comment by tmahmood72** [comment]
The Prod Alertmanager route is created with severity legacy-replacements-alerts

**Comment by tmahmood72** [comment]
Hi Luke,

I have made the severity and slack channel changes as requested, so please can you check the alerts are coming through to both channels. 

Thanks
