### ISSUE TITLE
laa-assess-crime-forms-dev custom domain request

### ISSUE THREAD

**Issue by ivanELEC** [ministryofjustice/cloud-platform#5369]
## Service name

Assess Criminal Legal Aid Forms 
## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

No Impact

## Problem description

I'm setting up a custom domain in the namespace laa-assess-crime-forms-dev. According to [the documentation](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/route53-zone.html#route53-tf) I need to raise a ticket: 

> "Provide them with the domain name, the Cloud Platform team will finalize the process by creating a matching NS record in the DSD account."

Domain:
https://dev.assess-crime-forms.service.justice.gov.uk
Namespace: laa-assess-crime-forms-dev

## Contact person

Ivan Yohuno - ivan.yohuno@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
Hi @ivanELEC , I spoke to you via slack, Please find the same added as comment.

We no longer have access to the DSD account. Can you please contact Operations Engineering team in [#ask-operations-engineering](https://mojdt.slack.com/archives/C01BUKJSZD4) to update the NS record in the DSD account. The user guide needs updating.

https://user-guide.operations-engineering.service.justice.gov.uk/documentation/services/domainmgt.html#domain-management

The Operations Engineering team would need the nameserver details which you can get by adding the below
resource "kubernetes_secret" "nscc_route53_zone_sec" {
  metadata {
    name      = "route53-zone-output"
    namespace = var.namespace
  }

  data = {
    zone_id = aws_route53_zone.nscc_route53_zone.zone_id
    nameservers = join("\n", aws_route53_zone.nscc_route53_zone.name_servers)
  }
}

And you can see the nameservers in the secret created
