### ISSUE TITLE
Automatically alert the namespace owner that the quota is about to be/has been exceeded

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#537]
## Background

Originated as a support ticket - #534 

## Proposed user journey

An automated alert will be sent to users when a quota is about to be exceeded so that corrective action can be taken.

## Which part of the user docs does this impact

TBD

## Questions / Assumptions

- At what threshold do we set up alerts? 
- Where do alerts get sent?
- What information is needed in an alert?

## Definition of done

TBC

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
```100 * kube_resourcequota{job="kube-state-metrics",type="used",namespace="formbuilder-services-dev"} / ignoring(instance, job, type) (kube_resourcequota{job="kube-state-metrics",type="hard"} > 0) > 90```
