### ISSUE TITLE
Set all cluster critical daemonsets with high Pod priority 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5374]
## Background

KuberhealthyDaemonsetCheck triggers in lower-priority-alarms channel with error `waiting for all pods to come online. Node(s) missing daemonset pod`

While investigating we found that the kuberhealthy test should be fine tuned to have high pod priority in order to replicate any daemonset of the cluster.

As part of this ticket: Check if all daemonsets have higher pod priority. Some options are discussed in the slack-thread:
https://mojdt.slack.com/archives/C514ETYJX/p1709835937548109

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tom-j-smith** [comment]
Velero, logging and monitoring daemonsets are now set to system-cluster-critical.
