### ISSUE TITLE
Tighten Default Pod Network Security: Prevent all egress by default

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#5377]
## Background

@davidread suggests that we flip the default egress network policy to be completely blocked to the external internet by default (in the cli template). This helps to promote good security practice of only enabling egress when required and therefore decreases our attack surface and hardens our security posture.

https://mojdt.slack.com/archives/C57UPMZLY/p1709922104835799

Action: Update user guide on how to block egress using the network policy

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
- Do not implement this but provide documentation instructing users how to block egress if needed.
- We'll have a follow-up meeting, examing security in the cluster and we will decide the priority of security tasks

**Comment by davidread** [comment]
Awesome!! I'll circulate this
