### ISSUE TITLE
Revert setting the `kube-prometheus-stack` chart to manage our `kube-state-metrics` version

### ISSUE THREAD

**Issue by kyphutruong** [ministryofjustice/cloud-platform#5384]
## Background

We need to switch back over to setting the `kube-prometheus-stack` chart to manage our kube-state-metrics versioning. This was temporarily overridden for 1.26 upgrade work to retain compatibility, see here for the change that was made in the prom values template:
[ministryofjustice/cloud-platform-terraform-monitoring@9caded0](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/commit/9caded0d5a5e60ea742b968a0bca06502a15338a)

Currently we've overridden the default in the [prom values to use version ](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/commit/9caded0d5a5e60ea742b968a0bca06502a15338a)v2.9.1 - which is the correct version to use for EKS 1.26 according to the [compatibility matrix](https://github.com/kubernetes/kube-state-metrics?tab=readme-ov-file#compatibility-matrix).
The default for value for the current helm chart is to use kube-state-metric v2.10.1 , which is for EKS 1.27

## Approach

Remove override and use default after EKS 1.27 upgrade

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
This has been set back to default config as of 1.27
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/blob/main/templates/prometheus-operator-eks.yaml.tpl#L337
