### ISSUE TITLE
Failed staging deploy for cla_public

### ISSUE THREAD

**Issue by farrepa** [ministryofjustice/cloud-platform#539]
## Service name

CLA Public staging

## Service environment

- [ ] Dev / Development
- [X] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Development blocker to test changes required for reduced operator working hours over Christmas.

## Problem description

[Job failed](https://ci.service.dsd.io/job/DEPLOY-cla_public/151/console). Possible component version mismatch?

```
  File "/var/cache/salt/minion/extmods/modules/dockerng.py", line 922, in _client_wrapper
    exc.explanation)
CommandExecutionError: Error 400: {"message":"client is newer than server (client API version: 1.29, server API version: 1.24)"}
```

## Contact person

Patrick Farrell
`@Patrick Farrell` on Slack
patrick.farrell@digital.justice.gov.uk

**Comment by pwyborn** [comment]
04/12/2018 paulwyborn [11:22 AM]
Hi Patrick - looking at your deployment problem re staging. I have just run it against master.latest - can you tell me if your changes are there?
cla-public that is

paulwyborn [11:32 AM]
Sorry - Just going to try something else

Patrick Farrell [11:34 AM]
Sure. I was deploying a feature branch yesterday so will try the same again when you're ready?

paulwyborn [11:41 AM]
master.797755b worked as well (as long as your changes are on stating)

Patrick Farrell [11:42 AM]
Ah, perfect, yes changes are merged to that :thumbsup:

paulwyborn [12:10 PM]
Hi Patrick can I close that ticket please (or is there something else - I think the difficulty lies in the fact that you are no longer building in Jenkins)
So not sure re the branch implications (edited)

Patrick Farrell [12:17 PM]
Yes, please do close the :ticket: , thanks!
