### ISSUE TITLE
Need custom domain plan-your-future.gov.uk for plan your future service

### ISSUE THREAD

**Issue by abdulrkalam** [ministryofjustice/cloud-platform#5391]
## Service name
Plan your future

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service
Product team need domain to move into private beta

## Problem description
The Prison Leavers (Person on probation)  need to access their Appointments and Licence condition upon leaving the prison. This service need to be easily access and So that the URL looks legitimate and can easily be entered manually if necessary.

## Contact person
Thomas Halsom, #hmpps-resettlement-passport, thomas.halson@digital.justice.gov.uk
Carragan Moore, #hmpps-resettlement-passport, carragan.moore@digital.justice.gov.uk

**Comment by mikebell** [comment]
Hi Abdul,

We have a user guide on [custom domains](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/custom-domain-cert.html#using-a-custom-domain) if your service is hosted on the Cloud Platform.

**Comment by abdulrkalam** [comment]
Hi @mikebell  Actually not sure what next?  should i need to contact contact the parent zone’s administrators (usually GDS) to set this up.

**Comment by AntonyBishop** [comment]
No. You can't have that domain. It doesn't conform to MoJ or Cabinet Office naming standards.

That name would imply the service will be hosted on [gov.uk](http://gov.uk/). I don't think that is what you want?

It sounds like this would be more appropriately assigned to a [service.gov.uk](http://service.gov.uk/) or [service.justice.gov.uk](http://service.justice.gov.uk/) subdomain.

Both of these variations have a different process to follow to gain approval for use.

Grateful if you could clarify the intent?

Happy to grab some time to discuss further.
