### ISSUE TITLE
Understand CPU Critical and scheduling during k8s upgrade

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5413]
During the upgrade of our Amazon EKS default node group from Kubernetes version 1.26 to 1.27 on 26th March 2024 on production cluster "live", we observed some resource allocation challenge

Initially when the upgrade started, all existing nodes running version 1.26 turned to Ready, SchedulingDisabled state to prevent further pod assignments. Concurrently, a limited number of new nodes running version 1.27 are created and begin to accept pod assignments.
This transition results in a temporary but critical imbalance between the cluster's available computing resources and the demands of ongoing workloads

High Resource Utilization: The initial batch of version 1.27 nodes experiences high CPU and memory usage as they begin to process workloads and some new user deployments.
Pod Scheduling Constraints: The disparity in resource availability and demand leads to constrained pod scheduling capacity. Consequently, we notice a significant spike in pod creation failures and delays.

Raise support ticket with AWS to investigate why this is happening anything that can be done to avoid the symptoms.

https://support.console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=171146060401080&language=en

**Comment by poornima-krishnasamy** [comment]
https://docs.aws.amazon.com/eks/latest/userguide/managed-node-update-behavior.html#managed-node-update-scale-up
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/07be37dc7a7506f685717b63e913fbac7737c998/docs/UPGRADE-18.0.md?plain=1#L369-L371

**Comment by jaskaransarkaria** [comment]
Following investigation, the parameter mentioned was bumped to 100% and this did what was expected, the same number of new nodes were brought up ie. in a 55 default node group 55 new nodes were spun up to transition workloads. However, the impact of this was that workloads were drained too vigorously which could potentially cause workloads to experience downtime. @poornima-krishnasamy will really this information back to aws and see if they have any further suggestions
