### ISSUE TITLE
Push Ruby 2.5.3 images to dockerhub

### ISSUE THREAD

**Issue by matthewrudy** [ministryofjustice/cloud-platform#542]
## Service name

Moving People Safely

## Service environment

- all

## Impact on the service

Want to upgrade Ruby to 2.5.3 for a couple of security fixes,
but stuck on 2.5.1

## Problem description

The Docker Templates were updated to allow ruby 2.5.3
https://github.com/ministryofjustice/docker-templates/pull/49

But Dockerhub only has the 2.5.1 tags
https://hub.docker.com/r/ministryofjustice/ruby/tags/

Specifically I'd like a `ministryofjustice/ruby:2.5.3-webapp-onbuild` tag to do a direct swap for moving-people-safely

## Contact person

@matthewrudy on slack

**Comment by lukaszraczylo** [comment]
Docker images `ministryofjustice/ruby:2.5.3-webapp-onbuild` and `ministryofjustice/ruby:2.5.3` released.
