### ISSUE TITLE
Investigation: automount_service_account_token

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5420]
## Background
[PLACEHOLDER]

We should look into how we deal with autogenerated tokens which are now considered legacy.

For example we use this field in the irsa module:

https://github.com/ministryofjustice/cloud-platform-terraform-irsa/blob/main/main.tf#L75

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by Matt-Alinosn** [comment]
Review of service account token status will form part of next upgrade planning cycle
