### ISSUE TITLE
Need custom domain plan-your-future.service.gov.uk for plan your future service

### ISSUE THREAD

**Issue by abdulrkalam** [ministryofjustice/cloud-platform#5431]
## Service name

Plan Your Future

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Product team need domain to move into private beta

## Problem description

The Prison Leavers (Person on probation) need to access their Appointments and Licence condition upon leaving the prison. This service need to be easily access and So that the URL looks legitimate and can easily be entered manually if necessary.
Also, got the approval from HMPPS for this domain.

## Contact person

Thomas Halsom, #hmpps-resettlement-passport, [thomas.halson@digital.justice.gov.uk](mailto:thomas.halson@digital.justice.gov.uk)
Carragan Moore, #hmpps-resettlement-passport, [carragan.moore@digital.justice.gov.uk](mailto:carragan.moore@digital.justice.gov.uk)

**Comment by poornima-krishnasamy** [comment]
Hi @abdulrkalam , The domain request is done with domains team/Operations engineering team. As discussed in slack, the nameservers for this domain has been provided. Is there anything you need regarding this request?

**Comment by poornima-krishnasamy** [comment]
Hi @abdulrkalam , I am closing this as the nameserver details are already been given to Ops eng team. We have also updated the guidance to do the same. https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/route53-zone.html#main-tf
