### ISSUE TITLE
New pingdom integration for LAALAA API

### ISSUE THREAD

**Issue by starswan** [ministryofjustice/cloud-platform#5435]
## Service name

LAA-Legal-Adviser-API

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Problem description

Please provide a new pingdom integration for the LAALAA API as follows:

team name CCQ and Refer
application name laa-laa (Legal Advisor API) - staging
the target slack channel laa-fala-laalaa-alerts-staging

## Contact person

@Stephen Dicks

**Comment by poornima-krishnasamy** [comment]
Hi @starswan , please find the integration id for the LAA-Legal-Adviser-API - Staging Pingdom integration: `134947`
