### ISSUE TITLE
Decommission Postcodeinfo API - Part 1

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#544]
## Background

Postcodeinfo API no longer provides value. We are migrating users to OS Places as a more valuable alternative. When all services have been migrated we can decommission the legacy API.

This also means we do not need to migrate the API to the new Cloud Platform.

## Approach

This is part one of a two stage decommissioning approach.

This first part involves making the API unavailable to users. 

Whilst we have made all attempts to contact all users of the service it is still possible that some users of the service may have been missed. We want to turn off the service in such a way that we can reinstate it at short notice if required.

After a two week period we will decom the infrastructure. A separate ticket will be raised for the second part of the work.

## Which part of the user docs does this impact

N/A. 

## Questions / Assumptions

N/A

## Definition of done

- [x] API unavailable to users.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Schedule to end of June 2019.

**Comment by pwyborn** [comment]
Auto-scaling Instances for staging and production set to standby
RDS instances stopped
PagerDuty service postcodeinfo "disabled"
Pingdom service "Paused"

**Comment by pwyborn** [comment]
See if anyone shouts. Part 1 completed (API unavailable to users)
