### ISSUE TITLE
Remove grafana snapshot 

### ISSUE THREAD

**Issue by riccardo-noviello-moj** [ministryofjustice/cloud-platform#5447]
## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description

Remove Grafana Snapshot please 
https://snapshots.raintank.io/dashboard/snapshot/cCSN61xA2pJ9GS0OOzKOAv1ui9ZHElut?orgId=0&from=1712629604715&to=1712651204715

## Contact person

Riccardo Noviello

**Comment by poornima-krishnasamy** [comment]
Checked with @riccardo-noviello-moj and this is not related. Closing
