### ISSUE TITLE
Please provide new pingdom integration for LAALAA Production

### ISSUE THREAD

**Issue by starswan** [ministryofjustice/cloud-platform#5451]
## Service name

Legal Advisor API

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description

Please provide a new pingdom integration for the LAALAA API as follows:

team name CCQ and Refer
application name laa-laa (Legal Advisor API) - production
the target slack channel laa-fala-laalaa-alerts-production

## Contact person

@Stephen dicks github:starswan

**Comment by poornima-krishnasamy** [comment]
Hi @starswan , the integration id for "(Legal Advisor API) - production" is `135034`
