### ISSUE TITLE
LNP-650: Add National Prison Radio IP address to Cloudfront WAF for Prisoner Content Hub in Production

### ISSUE THREAD

**Issue by Eli-TW** [ministryofjustice/cloud-platform#5467]
## Service name

Prisoner Content Hub

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

This is a blocker on moving from signed URLs for S3 access to Cloudfront controlled by WAF, as we need NPR to be able to upload and access resources. 

## Problem description

We need to add the static IP address used by National Prison Radio to the WAF for the cloudfront instance in the prisoner-content-hub-production namespace. The IP address is 194.75.49.10.

## Contact person

[Eli-TW](https://github.com/Eli-TW). or if actioned after 25/4/24, [sweetymj](https://github.com/sweetymj)

**Comment by sj-williams** [comment]
ip address added
