### ISSUE TITLE
Update RDS module ca_cert_identifier to update RDS SSL/TLS Certificates

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/cloud-platform#5469]
## Background

The current `ca_cert_identifier` is set to `rds-ca-2019`.
https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/main/variables.tf#L94

This is due to expire on 22nd August 2024, see AWS Health warnings here - 
https://mojdt.slack.com/archives/C8QR5FQRX/p1712903196552559
https://health.aws.amazon.com/health/home?region=us-east-1#/event-log?eventID=arn:aws:health:eu-west-2::event/RDS/AWS_RDS_PLANNED_LIFECYCLE_EVENT/AWS_RDS_PLANNED_LIFECYCLE_EVENT_451b72e53d2adb9f241be597664be7c601cbb524965a86f36465ac9f20dafee3&eventTab=details

This affects 510 RDS databases.

>Description
[AWS Health may periodically trigger reminder notifications about this communication.]
You are receiving this message because your AWS Account has one or more Amazon RDS, or Amazon Aurora database instances in the EU-WEST-2 Region using a SSL/TLS Certificate that is expiring on August 22, 2024.
A list of your affected resources can be found in the 'Affected resources' tab.
This is a follow-up notification for SSL/TLS CA certification expiration. If you believe you have already finished this work and still received this email, it is likely because you created new instances using the 2019 Certificate Authority (CA). After January 25, 2024 all newly created instances that do not explicitly specify a different CA will use the ‘rds-ca-rsa2048-g1’ CA. For information on setting an account level CA override, see the modify-certificates API documentation [1].
If your applications connect to these instances using the SSL/TLS protocol, you will need to take action before August 22, 2024 to prevent connectivity failures to your existing database instances. Even if you do not currently use SSL for your connections, you could still be affected if your databases server certificate expires, so we still recommend updating your CA.
To protect your communications with your database instances, a CA generates time-bound certificates that are checked by your database client software to authenticate any database instance before exchanging information. Following industry best practices, AWS renews the CA and creates new certificates on a routine basis to ensure customer connections are properly protected for years to come. The current CA in the EU-WEST-2 Region will expire on August 22, 2024. Before this date you will need to update your DB server certificate. The following is the general process to do this:
First, update your application clients with the new certificate, if your application client is using a trust store then add the new CA certificates into the trust stores of your client applications. RDS provides download links to the CA certificates in our User Guide [2]. For more detailed instructions on updating the trust stores on your client application see our documentation [3].
Second, update the certificate on all your affected database instances to one of the newly issued CAs. ‘rds-ca-rsa2048-g1’ is the default recommended CA because there is no algorithm change. The other CAs use new key algorithms so it could require more testing of your client setup to ensure compatibility. For more information on the new CAs see our documentation [4].
Third, if you want to use a different CA than the default ‘rds-ca-rsa2048-g1’, you will need to set an account level CA override so your new instances will use the CA of your choice. To do this a modify-certificates API is available that will allow you to override the default CA on newly created database instances to either the old or one of the new CAs. This override will only apply while the CA you are overriding to is valid. To use this API you will need to be running the AWS CLI version 1.17 or later. For more information see the modify-certificates API documentation [1]. There is also a describe-certificates API [5], that will indicate your current default CA override if you have one set. To set a specific CA during instance creation use the ca-certificate-identifier option on the create-db-instance API to create a DB instance with a specific CA. For more information, see the create-db-instance API documentation [6].
For more detailed instructions on how to perform these updates, please see the Amazon RDS instances [7] and Amazon Aurora instances [8] documentation.
Please be aware of the following timeline:

1. As soon as possible - You should update your client trust store, then you can update your instances server certificate to one generated by one of the new CAs.

2. After January 26, 2024 - any new database instances default to using the ‘rds-ca-rsa2048-g1’ certificate. If you wish for new instances to use a different certificate, you can specify which certificate to use with the AWS console or the AWS CLI. For more information, see the create-db-instance API documentation [6].

3. After August 22, 2024 - ‘rds-ca-2019’ will expire. You will need to take action before August 22, 2024, to prevent connectivity failures to your existing database instances.

For more information see our blog [9], and if you have questions or concerns, please contact AWS Support [10].

[1] https://docs.aws.amazon.com/cli/latest/reference/rds/modify-certificates.html
[2] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.CertificatesAllRegions
[3] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html#UsingWithRDS.SSL-certificate-rotation-updating
[4] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.RegionCertificateAuthorities
[5] https://docs.aws.amazon.com/cli/latest/reference/rds/describe-certificates.html
[6] https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html
[7] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html
[8] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.SSL-certificate-rotation.html
[9] https://aws.amazon.com/blogs/aws/rotate-your-ssl-tls-certificates-now-amazon-rds-and-amazon-aurora-expire-in-2024/
[10] https://console.aws.amazon.com/support/home

## Approach

This should be updated to the latest default value - `rds-ca-rsa2048-g1`, and users advised to take the steps outlined in the AWS 

## Which part of the user docs does this impact

None

## Communicate changes

Users should be made aware of the actions required above.

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by timckt** [comment]
- Create new branch in rds module to use new ca cert
https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/tree/update-ca-cert-identifier?tab=readme-ov-file

- Update rds module in test namespace to use new branch for cert rotation

- No downtime in the testing environment, and it took around 2 mins for the certificate replacement

**Comment by timckt** [comment]
We have completed the testing and published the comms to advice user to upgrade and test their RDS module.

We agree to close it and create 3 tickets for bumping dev/non-prod/prod environment.
