### ISSUE TITLE
Parliamentary Questions - staging server unresponsive 

### ISSUE THREAD

**Issue by njpreddy** [ministryofjustice/cloud-platform#548]
## Service name

Parliamentary Questions

## Service environment

- [ ] Dev / Development
- [X ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

We cannot deploy anything to staging.  This is completely blocking further development work.

## Problem description

Initially the application login page (https://staging.pq.dsd.io/users/sign_in) would consistently time out and render nothing.  Now, Jenkins fails to deploy to the server with the following error:

"Fatal error: One or more hosts failed while executing task 'run_deploy'. Underlying exception: Timeout opening channel."

## Contact person

Nick Preddy
@nick.preddy
nick.preddy@digital.justice.gov.uk

**Comment by lukaszraczylo** [comment]
https://ci.service.dsd.io/view/PQ/job/pq-deploy/188/consol
