### ISSUE TITLE
Setup CloudWatch alerts to Modsec and App Opensearch clusters

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5486]
## Background

Cloud Platform has 2 Opensearch clusters configured to log modsec audit logs and applications logs. Setup Cloudwatch alert to monitor the Opensearch clusters and configure to send alerts to #lower-priority-alarms channel

## Approach

Current Elasticsearch Cluster alert setup: https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/terraform/global-resources/elasticsearch.tf#L274-L284

The 2 Opensearch clusters are configured from here: https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/main/terraform/aws-accounts/cloud-platform-aws/account

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] cloudwatch alert configured and tested for modsec-audit and app-logs OS
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by timckt** [comment]
We are currently using [dubiety/elasticsearch-cloudwatch-sns-alarms](https://github.com/dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms) for Elasticsearch Cloudwatch alarm. It was not update to date for Opensearch Cloudwatch alarm and we need to create our new module for this.

Reference for new modules:
1. [dubiety/elasticsearch-cloudwatch-sns-alarms](https://github.com/dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms)
2. [UKHomeOffice/acp-tf-aws-opensearch-alerting](https://github.com/UKHomeOffice/acp-tf-aws-opensearch-alerting/tree/main)
