### ISSUE TITLE
Add GPG key to CLA deployment repos

### ISSUE THREAD

**Issue by farrepa** [ministryofjustice/cloud-platform#549]
## Service name

CLA Backend
CLA Frontend
CLA Public
LAALAA
FALA

## Service environment

- [x] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

No impact at present, just a development pre-requisite.

## Problem description

I need to add and change secrets with git-crypt in our deployment repos:

https://github.com/ministryofjustice/cla_backend-deploy
https://github.com/ministryofjustice/cla_frontend-deploy
https://github.com/ministryofjustice/cla_public-deploy
https://github.com/ministryofjustice/laalaa-deploy
https://github.com/ministryofjustice/fala-deploy

@Katy600 requested this yesterday for `cla_frontend-deploy` but will also soon need access to secrets in the other four above, if that helps save time.

(Key is newly available on usual keyservers, so may not have propagated yet. Slack me for my key or confirmation. Thank you!)

## Contact person

Patrick Farrell
@Patrick Farrell on Slack
patrick.farrell@digital.justice.gov.uk

**Comment by lukaszraczylo** [comment]
Access to mentioned repos granted.
