### ISSUE TITLE
MPS dev environment fails to deploy for Disk space

### ISSUE THREAD

**Issue by cesidio** [ministryofjustice/cloud-platform#550]
## Service name

MPS (Moving People Safely)

## Service environment

- [ X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Dev environment is used for demos at the moment, it's not urgent

## Problem description

Deployments are broken because there is no space left on disk

## Contact person

Lukasz Raczylo

**Comment by lukaszraczylo** [comment]
Disk space for both dev servers bumped from 10gb to 50.
