### ISSUE TITLE
Restore RDS instance in hmpps-workload-preprod

### ISSUE THREAD

**Issue by sambailey-moj** [ministryofjustice/cloud-platform#5511]
## Service name

Manage A Workforce - hmpps-workload-preprod

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

In order to support testing of Probation Reset new tiers, we need to roll back the RDS for this environment

## Problem description

1. Rollback database to around 9am Monday 22/4/24

## Contact person

Sam Bailey/Natalie Wood [sam.bailey1@digital.justice.gov.uk](mailto:sam.bailey1@digital.justice.gov.uk)
[natalie.wood@digital.justice.gov.uk](mailto:natalie.wood@digital.justice.gov.uk)

**Comment by sambailey-moj** [comment]
Apologies, could we make that 12 midday instead of 9am if possible - thanks!

**Comment by sj-williams** [comment]
User update: This is no longer required
