### ISSUE TITLE
Request a new alert route in AlertManager for MAAT Orchestration Prod

### ISSUE THREAD

**Issue by venkat980** [ministryofjustice/cloud-platform#5519]
## Service name

MAAT Orchestration

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

No impact to the live service

## Problem description

namespace name
For prod: laa-maat-orchestration-prod

team name
laa-crime-apps-team

application name
laa-maat-orchestration

slack channel
laa-maat-orchestration-alerts-prod

kubernetes secret name where the webhook url is stored:
maat-orchestration-alert-webhook-prod

severity level:
laa-maat-orchestration-alerts-prod

## Contact person

Venkat Velpuri

**Comment by poornima-krishnasamy** [comment]
Hi @venkat980, I dont see a secret named `maat-orchestration-alert-webhook-prod` in the namespace ` laa-maat-orchestration-prod`. Can you check and confirm?

**Comment by venkat980** [comment]
Secret is added.

**Comment by poornima-krishnasamy** [comment]
AlertManager route setup completed. Please use this severity when configuring prometheus alerts : laa-maat-orchestration-alerts-prod
