### ISSUE TITLE
Failed cla_public production deploy

### ISSUE THREAD

**Issue by farrepa** [ministryofjustice/cloud-platform#552]
## Service name

cla_public

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Failed to deploy new containers to production: `https://ci.service.dsd.io/job/DEPLOY-cla_public/156/console`. Public facing service is affected: https://checklegalaid.service.gov.uk

## Problem description

[Failed production deploy](https://ci.service.dsd.io/job/DEPLOY-cla_public/156/console)

With same version mismatch error seen recently in a staging deploy:

```
File "/var/cache/salt/minion/extmods/modules/dockerng.py", line 922, in _client_wrapper
  CommandExecutionError: Error 400: {"message":"client is newer than server (client API version: 1.29, server API version: 1.24)"}
```

## Contact person

Patrick Farrell
@Patrick Farrell on Slack
patrick.farrell@digital.justice.gov.uk

**Comment by farrepa** [comment]
@ollieanwyll I amended the ticket to state that the public facing service is affected: https://checklegalaid.service.gov.uk

**Comment by razvan-moj** [comment]
fixed by editing the job adding `export DOCKER_API_VERSION=1.24`; it's a well-known issues with Docker 1.12
