### ISSUE TITLE
Add Chelmsford IP address for Prisoner Content Hub Production Cloudfront

### ISSUE THREAD

**Issue by sweetymj** [ministryofjustice/cloud-platform#5520]
## Service name

Prisoner Content Hub

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Delay of Cloudfront rollout for Content Hub once Chelmsford prison is live

## Problem description

We are moving from securing S3 resources via presigned URLs to Cloudfront paired with a WAF / ACL.
The WAF for Content Hub already exists but does not yet whitelist the newest prison to be have the Content Hub rolled out, Chelmsford.
This ticket is to add the IP addresses for Chelmsford to this WAF.
Please reach out to the originator of this PR to obtain the IP addresses.

## Contact person

Sweety Mariam John / [sweety.john@digital.justice.gov.uk](mailto:sweety.john@digital.justice.gov.uk)

**Comment by psoleckimoj** [comment]
@mikebell I've just dropped the IP range @sweetymj passed you into https://www.ipaddressguide.com/cidr and it doesn't give any issues? It's showing the first ending `.144` and last IP ending `.159` ?

**Comment by mikebell** [comment]
Updated and applied to the WAF
