### ISSUE TITLE
FIREBREAK: Can we create blue-green Prometheus

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5526]
## Background

Cloud Platform has one prometheus for monitoring the whole platform. This is in a statefulset and when this needs upgrading, there is a downtime and lost of data during that downtime. Is it possible to  create another prometheus like blue-green style. This will allow testing the changes in one prometheus without affecting the live monitoring

Spike ways to create a blue-green prometheus. Some of the ways might be
- create a copy of the data that is in the blue prometheus to green 
- Allow both prometheus to scrape metrics so both blue and green has same data ingested

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Does next steps require User Research?
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by jaskaransarkaria** [comment]
No longer necessary as we now have multiple prom instances
