### ISSUE TITLE
Update env var for Correspondence Tool

### ISSUE THREAD

**Issue by misaka** [ministryofjustice/cloud-platform#554]
## Service name

Correspondence Tool

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Emails are being sent out with a 'From' address for the product development team.

## Problem description

We need to change an env var for the production system to change the From address used in emails being sent out. There is a PR for this, https://github.com/ministryofjustice/correspondence-tool-deploy/pull/50, but more importantly it I believe this will require someone to run 'fab update'. The team is out this afternoon, so I'd appreciate it if someone could merge the PR and do the fab update for us, it's our understanding that just changing the env var has little or no risk, but even so I will be available to deal with any problems that may arise while out.

## Contact person

Misha Gorodnitzky

**Comment by misaka** [comment]
This PR has now been merged and we would like a fab update performed to update the production environment.

CC: @lukaszraczylo

**Comment by misaka** [comment]
Just noticed that the PR listed here is the old one. A new one was created and merged since the one mentioned here: ministryofjustice/correspondence-tool-deploy#51.

**Comment by lukaszraczylo** [comment]
Update done. Also - Increased instances disks to 50G
