### ISSUE TITLE
Add Slack webhooks to AlertManager routing

### ISSUE THREAD

**Issue by stevomcallister** [ministryofjustice/cloud-platform#5555]
## Service name

Accredited Programmes

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Prometheus AlertManager notifications

## Problem description

Setting up new prometheus alerts for Accredited programmes. 

Team name: Accredited Programmes
Namespace: hmpps-accredited-programmes-prod

Slack channel: [#accredited-programmes-events](https://moj.enterprise.slack.com/archives/C05FDSCK8AH)

kubernetes secret name where the webhook url is stored: slack-webhook-url

## Contact person

stephen.mcallister@digital.justice.gov.uk

**Comment by poornima-krishnasamy** [comment]
Hi @stevomcallister , The Alertmanager route is created. Please use the severity `hmpps-accredited-programmes-alerts-prod` when setting Prometheus alerts
