### ISSUE TITLE
Request an integration id for CCR

### ISSUE THREAD

**Issue by Katy600** [ministryofjustice/cloud-platform#5563]
## Service name

Crown Court Remuneration

## Service environment

- [ laa-crown-court-remuneration-dev] Dev / Development

## Impact on the service
As part of implementing Pingdon, we will not receive alerts in the slack channel relating to the health of CCR.

## Problem description

Please could you generate an integration id for CCR to allow us to enable the option to send a failing alert to the CCR Slack.

**Team name**: Crime Higher Billing
**Application name:** crown court remuneration
**The target slack channel:** #laa-alerts-ccr-non-prod

## Contact person

Name: Katy McCann, slack handle: Katherine McCann, email address: Katherine.McCann@digital.justice.gov.uk

**Comment by tom-j-smith** [comment]
Hi @Katy600, the Pingdom integration ID for "#laa-alerts-ccr-non-prod Slack" is `135401`

**Comment by Katy600** [comment]
Thank you @tom-j-smith :)
