### ISSUE TITLE
Pingdom integration id request for crime-portal-gateway

### ISSUE THREAD

**Issue by Obsiye** [ministryofjustice/cloud-platform#5564]
## crime-portal-gateway

Requesting for a Pingdom integration id for `crime-portal-gateway` **production** under the k8s namespace `court-probation-prod`

team name: `probation-in-court`
service name: `crime-portal-gateway`
the target slack channel name: `#probation_in_court_alerts_prod`

## Service environment

- [X] Prod / Production

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

It'll alert the team when the service is down, allowing us to quickly debug and resolve any issues.

## Problem description

We aren't immediately aware of the health status of the service.

## Contact person

name: Abdirizak Obsiye
team: probation-in-court

Further information:

This is related to the user guide [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#create-a-pingdom-check)

**Comment by poornima-krishnasamy** [comment]
The Slack Integration for Pingdom alert is configured. Please use the integration id: 135404
