### ISSUE TITLE
Github Action to detect resource name renaming in yaml

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5568]
## Background

Users of Cloud Platform sometimes request PR for renaming kubernetes resources created in cloud-platform-environments repo. But the cloud-platform cli only perform `kubectl apply -f `. This means new resource gets created for the changes but the exiting resource doesnt get deleted.

It might be easier to detect resource deleting/ renaming via contest, take a look at if it's possible in conftest first.

## Approach

 It is not generally advisable to rename kubernetes resources and instead delete and recreate. Hence,
Implement a way to detect these kind of change to the resource names and add a comment in the PR or fail the checks so this is prevented during PR creation.

One of the suggestion to configure conftest to check the resource kind: namespace and if the name is getting changed 

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform-environments

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tom-j-smith** [comment]
Will work with Jack on Monday on a GO solution

**Comment by tom-j-smith** [comment]
Attempted to compare only changes from PR in yaml files to see if .metadata.name is gets changed, this seems to not work as the line diffs break YAML structure and then any name could be seen as a change causing the failed test.

**Comment by tom-j-smith** [comment]
Go script created that pulls YAML from changed files and compares metadata and fails if it detects changes to metadata.name or metadata.namespace

**Comment by tom-j-smith** [comment]
PR to add working test for yaml renaming into `main` - https://github.com/ministryofjustice/cloud-platform-environments/pull/27370

Tests have been carried out on fork of `cloud-platform-environments` and in a branch of the main version.

Scenarios tested:
![Image](https://github.com/user-attachments/assets/9ef9a9f3-10f5-41cf-b65f-5a78e1f8470e)
