### ISSUE TITLE
Update core-dns from "v1.10.1-eksbuild.7" to the version needed for current k8s version

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5573]
Check for the latest supported addon version for the current kubernetes version and update the clusters
[Runbook link](https://runbooks.cloud-platform.service.justice.gov.uk/upgrade-eks-addons.html#listing-available-eks-upgrades)

Production Clusters Checklist:

- [ ] live-2
- [ ] manager
- [ ] live

See the [Amazon EKS add-ons](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) documentation for more information about addons, or find the latest versions for these EKS add-ons directly:

- [coredns](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html)
- [kube-proxy](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)
- [vpc-cni](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html)

 Related to: #5569

**Comment by tmahmood72** [comment]
coredns add-on version upgrade from v1.10.1-eksbuild.7 to v1.10.1-eksbuild.11 on test cluster, integration test completed successfully.

**Comment by tmahmood72** [comment]
completed the upgrade in the clusters - live, live2 and manager
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/3132
