### ISSUE TITLE
Update vpc-cni from "v1.18.1-eksbuild.3" to the version needed for the upgraded k8s version

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5577]
Check for the latest supported addon version for the upgraded kubernetes version and update the clusters
[Runbook link](https://runbooks.cloud-platform.service.justice.gov.uk/upgrade-eks-addons.html#listing-available-eks-upgrades)

Production Clusters Checklist:

- [ ] live-2
- [ ] manager
- [ ] live

See the [Amazon EKS add-ons](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) documentation for more information about addons, or find the latest versions for these EKS add-ons directly:

- [coredns](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html)
- [kube-proxy](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)
- [vpc-cni](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html)

 Related to: #5569

**Comment by tmahmood72** [comment]
The current vpc-cni version is detailed in:-
https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/blob/main/variables.tf

variable "addon_vpc_cni_version" {
  default     = "v1.18.1-eksbuild.3"
  description = "Version for addon_create_vpc_cni"
  type        = string
}

Checked the versions that are supported for EKS 1.28:
eksctl utils describe-addon-versions --kubernetes-version 1.28 addon --name vpc-cni | grep AddonVersion
			"AddonVersions": [
					"AddonVersion": "v1.18.2-eksbuild.1",
					"AddonVersion": "v1.18.1-eksbuild.3",
					"AddonVersion": "v1.18.1-eksbuild.1",
					"AddonVersion": "v1.18.0-eksbuild.1",
					"AddonVersion": "v1.17.1-eksbuild.1",
					"AddonVersion": "v1.16.4-eksbuild.2",
					"AddonVersion": "v1.16.3-eksbuild.2",
					"AddonVersion": "v1.16.2-eksbuild.1",
					"AddonVersion": "v1.16.0-eksbuild.1",
					"AddonVersion": "v1.15.5-eksbuild.1",
					"AddonVersion": "v1.15.4-eksbuild.1",
					"AddonVersion": "v1.15.3-eksbuild.1",
					"AddonVersion": "v1.15.1-eksbuild.1",
					"AddonVersion": "v1.15.0-eksbuild.2",
					"AddonVersion": "v1.14.1-eksbuild.1",
					"AddonVersion": "v1.14.0-eksbuild.3",
					"AddonVersion": "v1.13.4-eksbuild.1",
					"AddonVersion": "v1.13.3-eksbuild.1",

Although this module is not on the Latest available version it does 'not' need to be upgraded for EKS 1.28
