### ISSUE TITLE
Update kube-proxy from "v1.27.10-eksbuild.2" to the version needed for the upgraded k8s version

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5578]
Check for the latest supported addon version for the upgraded kubernetes version and update the clusters
[Runbook link](https://runbooks.cloud-platform.service.justice.gov.uk/upgrade-eks-addons.html#listing-available-eks-upgrades)

Production Clusters Checklist:

- [ ] live-2
- [ ] manager
- [ ] live

See the [Amazon EKS add-ons](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) documentation for more information about addons, or find the latest versions for these EKS add-ons directly:

- [coredns](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html)
- [kube-proxy](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)
- [vpc-cni](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html)

 Related to: #5569

**Comment by tmahmood72** [comment]
The current  version is detailed in:-
https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/blob/main/variables.tf
variable "addon_kube_proxy_version" {
  default     = "**v1.27.10-eksbuild.2**"
  description = "Version for addon_kube_proxy_version"
  type        = string
}

Checked the versions that are supported for EKS 1.28:
eksctl utils describe-addon-versions --kubernetes-version 1.28 addon --name kube-proxy | grep AddonVersion
			"AddonVersions": [
					"AddonVersion": "v1.28.8-eksbuild.5",
					"AddonVersion": "v1.28.8-eksbuild.2",
					"AddonVersion": "v1.28.6-eksbuild.2",
					"AddonVersion": "v1.28.4-eksbuild.4",
					"AddonVersion": "v1.28.4-eksbuild.1",
					"AddonVersion": "v1.28.2-eksbuild.2",
					"AddonVersion": "v1.28.1-eksbuild.1",
					"AddonVersion": "v1.27.12-eksbuild.5",
					"AddonVersion": "v1.27.12-eksbuild.2",
					"AddonVersion": "**v1.27.10-eksbuild.2"**,
					"AddonVersion": "v1.27.8-eksbuild.4",
					"AddonVersion": "v1.27.8-eksbuild.1",
					"AddonVersion": "v1.27.6-eksbuild.2",
					"AddonVersion": "v1.27.4-eksbuild.2",
					"AddonVersion": "v1.26.15-eksbuild.5",
					"AddonVersion": "v1.26.15-eksbuild.2",
					"AddonVersion": "v1.26.13-eksbuild.2",
					"AddonVersion": "v1.26.11-eksbuild.4",
					"AddonVersion": "v1.26.11-eksbuild.1",
					"AddonVersion": "v1.26.9-eksbuild.2",
					"AddonVersion": "v1.26.7-eksbuild.2",
					"AddonVersion": "v1.25.16-eksbuild.8",
					"AddonVersion": "v1.25.16-eksbuild.5",
					"AddonVersion": "v1.25.16-eksbuild.3",
					"AddonVersion": "v1.25.16-eksbuild.2",
					"AddonVersion": "v1.25.16-eksbuild.1",
					"AddonVersion": "v1.25.15-eksbuild.2",
					"AddonVersion": "v1.25.14-eksbuild.2",
					"AddonVersion": "v1.25.11-eksbuild.2",

Although this module is not on the Latest available version it does 'not' need to be upgraded for EKS 1.28
