### ISSUE TITLE
Update core-dns from v1.10.1-eksbuild.11 to the version needed for the upgraded k8s version

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5579]
Check for the latest supported addon version for the upgraded kubernetes version and update the clusters
[Runbook link](https://runbooks.cloud-platform.service.justice.gov.uk/upgrade-eks-addons.html#listing-available-eks-upgrades)

Production Clusters Checklist:

- [ ] live-2
- [ ] manager
- [ ] live

See the [Amazon EKS add-ons](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) documentation for more information about addons, or find the latest versions for these EKS add-ons directly:

- [coredns](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html)
- [kube-proxy](https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html)
- [vpc-cni](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html)

 Related to: #5569

**Comment by tmahmood72** [comment]
The current core-dns version is detailed in:-
https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/blob/main/variables.tf
**v1.10.1-eksbuild.11**

eksctl utils describe-addon-versions --kubernetes-version 1.28 addon --name coredns | grep AddonVersion
			"AddonVersions": [
					"AddonVersion": "**v1.10.1-eksbuild.11**",
					"AddonVersion": "v1.10.1-eksbuild.10",
					"AddonVersion": "v1.10.1-eksbuild.7",
					"AddonVersion": "v1.10.1-eksbuild.6",
					"AddonVersion": "v1.10.1-eksbuild.5",
					"AddonVersion": "v1.10.1-eksbuild.4",
					"AddonVersion": "v1.10.1-eksbuild.3",
					"AddonVersion": "v1.10.1-eksbuild.2",
					"AddonVersion": "v1.9.3-eksbuild.15",
					"AddonVersion": "v1.9.3-eksbuild.11",
					"AddonVersion": "v1.9.3-eksbuild.10",
					"AddonVersion": "v1.9.3-eksbuild.9",
					"AddonVersion": "v1.9.3-eksbuild.7",

This module does 'not' need to be upgraded for EKS 1.28
