### ISSUE TITLE
Add GPG key to CLA deployment repos

### ISSUE THREAD

**Issue by farrepa** [ministryofjustice/cloud-platform#558]
## Service name

CLA Backend
CLA Frontend
CLA Public
LAALAA
FALA

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

No impact at present, just a development pre-requisite.

## Problem description

I need to add and change secrets with git-crypt in our deployment repos:

https://github.com/ministryofjustice/cla_backend-deploy
https://github.com/ministryofjustice/cla_frontend-deploy
https://github.com/ministryofjustice/cla_public-deploy
https://github.com/ministryofjustice/laalaa-deploy
https://github.com/ministryofjustice/fala-deploy

Key ID: `4D60EDEE`
Email: `patrick.farrell@digital.justice.gov.uk`

Please contact me for key if not yet available on key servers.

## Contact person

Patrick Farrell
`@Patrick Farrell` on Slack
patrick.farrell@digital.justice.gov.uk

**Comment by lukaszraczylo** [comment]
User added to git-crypt.
