### ISSUE TITLE
Review and upgrade kube-state-metrics for the upgraded cluster version 1.28

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#5581]
https://runbooks.cloud-platform.service.justice.gov.uk/container-images.html#container-images-used-by-cluster-components

https://github.com/kubernetes/kube-state-metrics?tab=readme-ov-file#compatibility-matrix

Review the compatibility matrix of kube-state-metrics and verify if the image is compatible with the upgraded Kubernetes version. If the version is a mismatch, check if the whole kube-prometheus-chart needs updating to get the default version of kube-state-metrics from the chart-> values. Otherwise, pin the kube-state-metrics image to match the Kubernetes version.

 Related to: #5569

**Comment by sj-williams** [comment]
kube-state-metrics | Kubernetes client-go Version
-- | --
v2.10.1 | v1.27
v2.11.0 | v1.28
v2.12.0 | v1.29



kube-prometheus-stack release w/ matching `1.28` `kube-state-metrics` version:

https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-57.2.0/charts/kube-state-metrics/Chart.yaml

**Comment by sj-williams** [comment]
Values diff between `56.21.4` and `57.2.0`
https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack/57.2.0?modal=values&compare-to=56.21.4

**Comment by sj-williams** [comment]
full chart compare
https://github.com/prometheus-community/helm-charts/compare/kube-prometheus-stack-56.21.4...kube-prometheus-stack-57.2.0

**Comment by sj-williams** [comment]
CRD upgrade reqs:
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-56x-to-57x

**Comment by sj-williams** [comment]
post prom crd migrate test of prom upgrade:

core
```
Plan: 0 to add, 10 to change, 0 to destroy.
```

components
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.monitoring.helm_release.prometheus_operator_eks will be updated in-place

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by sj-williams** [comment]
This will be managed via a full kube-prometheus-stack release bump.

TODO Monday 01/07
