### ISSUE TITLE
Replace court-probation-preprod Slack webhook for the AlertManager routing

### ISSUE THREAD

**Issue by Obsiye** [ministryofjustice/cloud-platform#5588]
## Service name

`court-probation-preprod` (app: `prepare-a-case`)

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Prometheus alerts will be sent to the new slack channel.

## Problem description

We have a new slack webhook to use for prometheus alerts 

I followed these instructions: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts

Requested information:

**namespace**: `court-probation-preprod`
**team**: `probation-in-court`
**application**: `prepare-a-case`
**slack channel**: the webhook is in the k8s secret `probation-in-court-preprod-slack-webhook`

## Contact person

Abdirizak Obsiye

**Comment by jackstockley89** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/3060
