### ISSUE TITLE
Test etcd backups

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#560]
## Background

Can we successfully restore a cluster from our `etcd` backups?

## Approach

Use a test cluster and test backup restoration.

## Definition of done

- [x] backups have been tested
- [x] there is a document that documents the recovery process

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/136
