### ISSUE TITLE
Setup smoke test pipeline

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#561]
## Approach

Using the tests defined in https://github.com/ministryofjustice/cloud-platform-smoke-tests/ and setup a concourse pipeline (or something, if concourse is not a good fit) to run the tests regularly (every morning?) on the `live-0` cluster.

## Definition of done

- [x] the tests are being ran periodically against `live-0`
- [x] any resources created, config etc. are version controlled

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-concourse/pull/41
