### ISSUE TITLE
FIREBREAK: Private LoadBalancer for VPC bound EKS application access

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5617]
## Background

Investigate the options available for accessing Cloud Platform applications internally via VPC endpoints / TGW.

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Does next steps require User Research?
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by sj-williams** [comment]
https://aws.amazon.com/blogs/networking-and-content-delivery/implement-a-central-ingress-application-load-balancer-supporting-private-amazon-elastic-kubernetes-service-vpcs/


https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/access-container-applications-privately-on-amazon-eks-using-aws-privatelink-and-a-network-load-balancer.html

**Comment by poornima-krishnasamy** [comment]
There is a sprint ticket to explore on vpc endpoints: https://github.com/ministryofjustice/cloud-platform/issues/5106. It would be interesting to see what output we get from this firebreak

**Comment by sj-williams** [comment]
Documented steps here:

https://docs.google.com/document/d/1-ft67dLsGK6K_tTkGTlDyvMxudkXhWnbfeDFFexj9Oc/edit#heading=h.7uj7x44fhjf8
