### ISSUE TITLE
Replace court-probation-dev Slack webhook for the AlertManager routing

### ISSUE THREAD

**Issue by Obsiye** [ministryofjustice/cloud-platform#5619]
## Service name

`court-probation-dev` (app: `prepare-a-case`)

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Prometheus alerts will be sent to the new slack channel.

## Problem description

We have a new slack webhook to use for prometheus alerts 

I followed these instructions: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts

Requested information:

**namespace**: `court-probation-dev`
**team**: `probation-in-court`
**application**: `prepare-a-case`
**slack channel**: the webhook is in the k8s secret `probation-in-court-slack-webhook`

**Slack channel name is**: `#probation_in_court_alerts_dev`

## Contact person

Abdirizak Obsiye

**Comment by tmahmood72** [comment]
The webhook severity **probation_in_court_alerts_dev** has been setup in the channel #probation_in_court_alerts_dev

Please can you confirm this is all correct

**Comment by tmahmood72** [comment]
User confirmed the webhook is working
