### ISSUE TITLE
Decommission Product Tracker

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#565]
## Background

Product Tracker no longer provides value. We can decommission the product as per the request from Steve Marshall.

## Proposed user journey

Decommission

## Approach

- Turn it off
- Turn off any alerting or monitoring etc

The deploy repo has already been archived.

## Which part of the user docs does this impact

N/A

## Definition of done

- [x] Product Tracker decommissioned

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
![Screen Shot 2018-12-17 at 15.38.07.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5af99512f7ba4500119c1fce/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f46b7191a379ea0c2859415f49be5d4a1f06a3a3dc78e2a436628f0d5de883680d73c63f18acbb861fbf03bf76d84d83e0e99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc5df64de04f57a7103562f43b.png)

**Comment by AntonyBishop** [comment]
![Screen Shot 2018-12-17 at 15.38.26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5af99512f7ba4500119c1fce/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f46b7191a379ea0c2859415d48be5d4a1f06a3a3dc78e2a436628f0d5de883680d73c63f18acbb861fbf03bf76d84d83e0e99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc5df64de04f51ad1a3266f43b.png)

**Comment by pwyborn** [comment]
Product tracker is no more - all AWS components removed. Jenkins jobs also deleted
