### ISSUE TITLE
Determine why kuberos crashes

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#566]
## Background

`kuberos` is crashing (seems to be related to running 2 replicas).

## Approach
Figure out what's wrong with it and fix it.
There are some new commits upstream we might want to pull in our fork if it helps fix the issue.

## Which part of the user docs does this impact

N/A
## Questions / Assumptions

N/A
## Definition of done

- [ ] `kuberos` is not crashing and we have a fix

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
Putting this back as it's decided to stop crashing?
```$ kubectl --context live-0 -n kuberos get pods
NAME                       READY   STATUS    RESTARTS   AGE
kuberos-6f68f489db-gqkwp   1/1     Running   0          22d```
Same for the newer test-7.
Looks more like other unrelated changes we were making in live-0 caused the instability.
