### ISSUE TITLE
Form Builder needs to own entire subdomain on Cloud Platform

### ISSUE THREAD

**Issue by solidgoldpig** [ministryofjustice/cloud-platform#568]
## Service name

Form Builder

## Service environment

- [ x] Dev / Development
- [x ] Staging
- [ x] Prod / Production
- [ ] Other

## Impact on the service

None currently, but would require us to change all our dev and staging domains in future if the change is not made now.

The impact is more the potential ramifications for Cloud Platform.

## Problem description

Form Builder currently creates domains for forms as subdomains of `apps.cloud-platform-live-0.k8s.integration.dsd.io`

```
eg $FORM-$ENV.apps.cloud-platform-live-0.k8s.integration.dsd.io
```

As Form Builder users can create forms with arbitary names, they could potentially clobber other services running in Cloud Platforms.

## Contact person

Alex Robinson
@alex.robinson

**Comment by AntonyBishop** [comment]
Duplicate

**Comment by solidgoldpig** [comment]
Duplicate of what @AntonyBishop ?

**Comment by AntonyBishop** [comment]
Is this superseded by #694?

**Comment by digitalronin** [comment]
> Is this superseded by #694?

Yes. When the wildcard certificates are set up, the formbuilder team can use the corresponding external URLs (e.g. leaver-dev.forms.service.justice.gov.uk), and should not need a corresponding leaver-dev-forms.apps.cloud-platform-live-0.k8s.integration.dsd.io (or whatever) hostname on the cluster.

**Comment by solidgoldpig** [comment]
> Is this superseded by #694?

Hopefully ;)  Everything David says at the moment is gold for the FB team because we don't need to do anything and everything will just turn out right!
