### ISSUE TITLE
New secrets env var missing from cla_frontend container

### ISSUE THREAD

**Issue by farrepa** [ministryofjustice/cloud-platform#569]
## Service name

cla_frontend and cla_frontend-deploy

## Service environment

- [ ] Dev / Development
- [X] Staging
- [ ] Prod / Production
- [X] Other: Training

## Impact on the service

Deployment blocker for replacing postcodeinfo service that will be switched off 2018-12-31.

## Problem description

A new `OS_PLACES_API_KEY` env var added to `secrets.sls` (merged [in commit 4986e6e](https://github.com/ministryofjustice/cla_frontend-deploy/commit/4986e6ef7d4c581fdb63896a7ace3750acef4576)) is not present in our staging and training containers.

The [latest Jenkins](https://ci.service.dsd.io/job/DEPLOY-cla_frontend/123/console) job is pulling that `cla_frontend-deploy` commit.

## Contact person

Patrick Farrell
`@Patrick Farrell` on Slack
patrick.farrell@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
done for testing&staging
```root@i-0692123728103885c:~# docker exec 051cbd332c94 env | grep OS_PLACES
OS_PLACES_API_KEY=odx...
root@i-060bd399327940e52:~# docker exec -ti 608b39668f01 env | grep OS_
OS_PLACES_API_KEY=odx```
