### ISSUE TITLE
Investigate why apply-live pipelines are failing with terraform locks

### ISSUE THREAD

**Issue by mikebell** [ministryofjustice/cloud-platform#5691]
## Background

@TODO add more detail

## Note

I have a theory that throttled worker pods (two heavy workers on same node) may be related to the increasing number of lock instances in apply-live. Difficult to prove, but now this one is in:

https://github.com/ministryofjustice/cloud-platform/issues/5837

It would be worth monitoring for a week or two and seeing if we get less lock issues.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
I'm closing this one as I'm happy that state locks are much less frequent now - those that I have seen since worker fixes seem just the usual competing apply live / apply namespace job runs.
