### ISSUE TITLE
Add AlertManager integration for Change Someone's Cell

### ISSUE THREAD

**Issue by jimbali** [ministryofjustice/cloud-platform#5716]
## Service name

Change Someone's Cell

## Service environment

- [x] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [x] Preprod

## Impact on the service

Enable slack notification for Prometheus alerts to allow us to monitor our service and stop spamming the main #dps_alerts channel

## Problem description

Namespace name - hmpps-prisoner-cell-allocation-dev, hmpps-prisoner-cell-allocation-preprod, hmpps-prisoner-cell-allocation-prod
Team name - Move a Prisoner
Application name - Change Someone's Cell
Slack channel - #move-a-prisoner-alerts
Kubernetes secret name where the webhook url is stored - slack-webhook
Severity level - warning

## Contact person

Name: Jim Bailey
Slack handle: jim.bailey
Email address: jim.bailey@digital.justice.gov.uk

**Comment by jackstockley89** [comment]
waiting on slack webhook to be created

**Comment by jimbali** [comment]
Slack webhook is now in a secret in each namespace.
Secret name: `slack-webhook`
Key: `webhook`
