### ISSUE TITLE
Set a reminder to rotate IAM cortex_xsiam_user access key

### ISSUE THREAD

**Issue by kyphutruong** [ministryofjustice/cloud-platform#5724]
## Background

We have an access key used by the SecOps Cortex Xsiam cloud infrastructure to connect to the CP Cloudtrail logs & the sqs queue where cloudtrail log updates are presented. The PR for this work was implemented [here](https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/3140)

Currently the cortex architecture cannot use IAM role to AssumeRole, hence having to use an IAM user.

## Proposed user journey

Set a reminder to Cloud Platform (maybe to Slack) to rotate keys when the age of the keys are approaching 180 days.

Process should be something like this:

1. Email the Monitoring & Integration team via monitoring-and-integration-platform@justice.gov.uk to confirm a new key pair is being created which will need to be applied to their Cortex Xsiam system.
2. Once they have responded confirming they are ready for the key, create a new one for the cortex_xsiam_user in the Cloud Platform account and email that to the named person who responded. This avoids the key being shared too widely.
3. When the M&I team have confirmed the new key has been applied and the console shows it in use, delete the existing key.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
Idea of how this could be automated
```
#!/bin/bash

# This script rotates the access key for the specified IAM user.

# Usage: rotate-access-key.bash <IAM-USER-NAME>

# The IAM user name is passed as an argument to the script.

# The script performs the following steps:
# 1. Create a new access key for the specified IAM user.
# 2. Delete the old access key for the specified IAM user.
# 3. Send the new access key to the specified email address.

# Check if the IAM user name is passed as an argument to the script.
if [ -z "$1" ]; then
  echo "Usage: rotate-access-key.bash <IAM-USER-NAME>"
  exit 1
fi

# Get the IAM user name from the argument.
IAM_USER_NAME=$1

# Check if the IAM user exists.
aws iam get-user --user-name $IAM_USER_NAME > /dev/null
if [ $? -ne 0 ]; then
  echo "IAM user $IAM_USER_NAME does not exist."
  exit 1
fi

# List the access keys for the specified IAM user.
aws iam list-access-keys --user-name $IAM_USER_NAME
if [ $? -ne 0 ]; then
  echo "Failed to list access keys for the IAM user."
  exit 1
fi

# Set Current access key to old access key
OLD_ACCESS_KEY=$(aws iam list-access-keys --user-name $IAM_USER_NAME | jq -r '.AccessKeyMetadata[0].AccessKeyId')

# Create a new access key for the specified IAM user.
aws iam create-access-key --user-name $IAM_USER_NAME
if [ $? -ne 0 ]; then
  echo "Failed to create a new access key for the IAM user."
  exit 1
fi

# Delete the old access key for the specified IAM user.
aws iam delete-access-key --user-name $IAM_USER_NAME --access-key-id $OLD_ACCESS_KEY
if [ $? -ne 0 ]; then
  echo "Failed to delete the old access key for the IAM user."
  exit 1
fi

echo `$(aws iam list-access-keys --user-name $IAM_USER_NAME | jq -r '.AccessKeyMetadata[0].AccessKeyId')` > /tmp/Access_Key.txt
echo `$(aws iam list-access-keys --user-name $IAM_USER_NAME | jq -r '.AccessKeyMetadata[0].SecretAccessKey')` > /tmp/Secret_Access_Key.txt

EMAIL=<email-id>

mail -s "Key Rotation" -a /tmp/Access_Key.txt $EMAIL
mail -s "Key Rotation" -a /tmp/Secret_Access_Key.txt $EMAIL
```

**Comment by jackstockley89** [comment]
The message is scheduled for 14th January at 10:00 it will appear in the cloud-platform channel, and the message will tag the cloud-platform-team in the message
