### ISSUE TITLE
Redirect hmpps-document-management-api-non-prod alerts (Dev and Preprod) to its own new channel

### ISSUE THREAD

**Issue by FaizJD030** [ministryofjustice/cloud-platform#5737]
## Service name

https://mojdt.slack.com/archives/C05T4DYEWTU/p1716272683397069
https://dsdmoj.atlassian.net/browse/DOC-69

Ticket to request a new alert route in Alertmanager

## Service environment

hmpps-document-management-api

namespace name : hmpps-document-management-dev and hmpps-document-management-preprod
team name : Calculate Release Dates
application name : hmpps-document-management-api
slack channel : hmpps-document-management-nonprod-alerts
kubernetes secret name where the webhook url is stored : slack-web-hook-non-prod
severity level (warning/information) : hmpps_document_management_api_non_prod

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description

The alerts are firing in the wrong channel.

## Contact person

Name : Faiz Ibrahim
slack handle: @faiz Ibrahim
email address: [faiz.ibrahim@digital.justice.gov.uk](mailto:faiz.ibrahim@digital.justice.gov.uk)

**Comment by timckt** [comment]
User confirmed the route is working.
