### ISSUE TITLE
Alertmanager queries report "Network error" when user session times out

### ISSUE THREAD

**Issue by solidgoldpig** [ministryofjustice/cloud-platform#574]
## Service name

Alertmanager web interface
https://alertmanager.apps.cloud-platform-live-0.k8s.integration.dsd.io/#/alerts

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Confuses users (this user at least)

## Problem description

Alertmanager web interface silently times out - any attempt to execute queries after that happens result in a cryptic "Network error" message.

Logging back in makes the problem go away, but it took me some time to realise that was the problem - I presume this is actually just a Alertmanager/Prometheus issue and it's hardly a show stopper.

NB. similar if not related to https://github.com/ministryofjustice/cloud-platform/issues/573

<img width="502" alt="alertmanager" src="https://user-images.githubusercontent.com/4856/50636655-d19b6a80-0f4e-11e9-9dfb-2093e4829d82.png">

## Contact person

Alex Robinson @alex.robinson

**Comment by jasonBirchall** [comment]
Issue is with the docker image we're currently using. It has a hardcoded expire value of one hour, without any room for maneuver. This ticket will now be used to investigate other proxy options. I will keep this issue open but will close the duplicate.

**Comment by jasonBirchall** [comment]
Moving this to backlog while discussion takes place.

**Comment by jasonBirchall** [comment]
Issue has been moved to:
https://github.com/ministryofjustice/cloud-platform/issues/633

Work has been done to replace proxy and now waiting PR. Will close this issue, any further work to be carried out under #633.
