### ISSUE TITLE
Concourse: GitHub tokens review

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5749]
## Background
We have several unique github tokens (some PAT) that are in use by Concourse pipelines

```
cloud_platform_infrastructure_pr_git_access_token
github_token
how_out_of_date_are_we_github_token
authorized_keys_github_token
github_actions_secrets_token
```

We need to review all of these, ensure that they belong to / are created by the appropriate user. ie if they are concourse-bot GH user PATs, we should look at renaming the var to reflect this.

Alternatively, we could look at possibility of managing them all via GH Concourse App?

relates to #5748

**Comment by sj-williams** [comment]
`github_token` : cloud-platform-concourse-bot

**Comment by tmahmood72** [comment]
`how_out_of_date_are_we_github_token` : `Machine user for the MoJ Cloud Platform team`

**Comment by tmahmood72** [comment]
curl command used to get the above token details:-
**curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ?????" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/user**

**Comment by tmahmood72** [comment]
1) Checked the tokens for GH user cloud-platform-concourse-bot and **this token has no expiration date**:
hammer-bot
cloud-platform-concourse-bot

2) Checked the tokens for GH user **cloud-platform-moj** (which is username for Machine user for the MoJ Cloud Platform team) and **This token has no expiration date**:
cloud-platform-review-docs
cloud-platform-infrastructure-plan-pipeline
cloud-platform-runbooks PUBLISHING_GIT_TOKEN
https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk
authorized-keys-provider

3) Need to check the expiry date of token **github_actions_secrets_token** which was generated by GH user @sablumiah.  @sablumiah please can you check this
