### ISSUE TITLE
Failed cla_public demo deploy

### ISSUE THREAD

**Issue by farrepa** [ministryofjustice/cloud-platform#575]
## Service name

cla_public

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X] Other

## Impact on the service

Failed to deploy new image to demo environment: `https://ci.service.dsd.io/job/DEPLOY-cla_public/161/console`.

## Problem description

[Failed demo deploy](https://ci.service.dsd.io/job/DEPLOY-cla_public/161/console). Looks the same as [Issue 552](https://github.com/ministryofjustice/cloud-platform/issues/552), just a different environment.

```
File "/var/cache/salt/minion/extmods/modules/dockerng.py", line 922, in _client_wrapper
  CommandExecutionError: Error 400: {"message":"client is newer than server (client API version: 1.29, server API version: 1.24)"}
```

## Contact person

Patrick Farrell
`@Patrick Farrell` on Slack
patrick.farrell@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
Known issue, TD strikes again, fixed by adding `--set DOCKER_API_VERSION=1.24` to the `fab` line in the Jenkins job, https://ci.service.dsd.io/job/DEPLOY-cla_public/162/ is green
