### ISSUE TITLE
Grant MohammedAbubakar MOJDSD Permission

### ISSUE THREAD

**Issue by cakeben** [ministryofjustice/cloud-platform#577]
## Service name

MOJDSD

## Service environment

- [/] Dev / Development
- [/] Staging
- [/] Prod / Production
- [/] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description

I need an account created for Mohammed Abubakar to MOJDSD AWS account both console and programmatic access. He is a new DevOps Engineer who is helping us transition our HMCTS applications from the MOJDSD account onto our own Azure Subscription

MohammedAbubakar would be an acceptable username, please copy all the permissions of the user BenjaminNeill

## Contact person

bneill_hmcts

**Comment by jasonBirchall** [comment]
confirmed it is okay to create this user account with secops.
