### ISSUE TITLE
Add AWS read-only S3 permissions

### ISSUE THREAD

**Issue by farrepa** [ministryofjustice/cloud-platform#578]
## Service name

AWS S3

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X] Other

## Impact on the service

Dev blocker.

## Problem description

Missing read-only S3 permissions for IAM user `PatrickFarrell` on `moj-cla-dev` account, needed to verify app behaviour.

## Contact person

Patrick Farrell
`@Patrick Farrell` on Slack
patrick.farrell@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
done (added AmazonS3ReadOnlyAccess)
