### ISSUE TITLE
Cloud Platform Leavers Guide

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#5784]
Follow the CP leavers guide

https://runbooks.cloud-platform.service.justice.gov.uk/leavers-guide.html#leavers-guide

**Comment by sj-williams** [comment]
infra repo done
awsaccount-iam done

**Comment by sj-williams** [comment]
slack??

Ops eng:

AWS Cloud Platform Transit Gateways

AWS dsd account AND single-sign-on AND native user login AWS accounts

Question (we've done x y z with our infra / iam repos for our CP accounts, do ops eng need to do anything else?)

Request Password Management removal - [1Password](https://1password.com/)

[Auth0 justice-cloud-platform](https://auth0.com/docs/authenticate/login)

[Auth0 moj-cloud-platforms](https://auth0.com/docs/authenticate/login)

[Pagerduty](https://moj-digital-tools.pagerduty.com/users)

[DockerHub MoJ teams](https://cloud.docker.com/orgs/ministryofjustice/teams)

[Pingdom](https://www.pingdom.com/)

[1Password](https://1password.com/)

[Sentry](https://ministryofjustice.sentry.io/settings/teams/)

[MoJ Github Organisation](https://github.com/ministryofjustice)

[GitHub Projects](https://github.com/orgs/ministryofjustice/projects/65/views/3)
