### ISSUE TITLE
AWS Login

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#580]
## Service name
AWS Login

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X ] Other

## Problem description

I am a developer on the get access team and need AWS login for the following projects:
moj-cla-dev
moj-laalaa

Can I please also get the same permissions that the PatrickFarrell user

## Contact person
Said Shire

**Comment by jasonBirchall** [comment]
After a chat with the user, this is no longer needed.
