### ISSUE TITLE
Firebreak idea: Dashboard auto-login

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#581]
Proposal:
We want to be able to log in to the dashboard in PF with as little effort as possible.

Current setup:
Currently, we login locally with admin privileges and auth to dashboards with either our own accounts or access tokens. 

What do we want:
We want to be able to automate the dashboard login, from switching the screen on to authenticating with our dashboards. 

Suggested approach: 
- Automate the screen switching on at 0800 and off at 1800. 
- Create a 'user' with basic privileges locally. This user should be able to open apps but not make changes. 
- Create a read-only GitHub user that's allowed to auth against our dashboards. Mainly Kibana and Kube-ops.

**Comment by ollieanwyll** [comment]
The Mac has been configured to auto-launch Chrome on start-up and also open the Kube Ops and Waffle board pages.

The TV settings have been configured so it turns on at 8 am and goes off at 6 pm Mon-Fri.

Caffeine has been installed and enabled on the Mac that keeps the machine awake indefinitely. 

Auto-login could not be activated, as this would require FileVault to be deactivated, and I'm pretty sure this is breaking policy.
