### ISSUE TITLE
New secrets env var missing after cla_backend deploy

### ISSUE THREAD

**Issue by farrepa** [ministryofjustice/cloud-platform#582]
## Service name

cla_backend-deploy

## Service environment

- [ ] Dev / Development
- [X] Staging
- [X] Prod / Production
- [X] Other: Training

## Impact on the service

Deployment blocker

## Problem description

A new `AWS_DELETED_OBJECTS_BUCKET_NAME` env var added to `secrets.sls` (merged [in commit 6213ca4](https://github.com/ministryofjustice/cla_backend-deploy/commit/6213ca4387ae6fd33a101bae8a1b528baa9b33b3)) is not present after deploying.

The [latest Jenkins](https://ci.service.dsd.io/job/DEPLOY-cla_backend/224/console) job is pulling that `cla_backend-deploy` commit.

## Contact person

Patrick Farrell
`@Patrick Farrell` on Slack
patrick.farrell@digital.justice.gov.uk

**Comment by jasonBirchall** [comment]
Now in touch with Patrick. Using the template-deploy-jump image I was able to update training and staging. 

Prod needs a little more care and deployments have to happen OOH so will arrange it with him.

**Comment by jasonBirchall** [comment]
CLA_backend release happening tonight.

**Comment by jasonBirchall** [comment]
CLA_backend prod released and confirmed env exists.
