### ISSUE TITLE
Do a walkthrough/demo of Prometheus and Alertmanager

### ISSUE THREAD

**Issue by solidgoldpig** [ministryofjustice/cloud-platform#586]
## Service name

N/A

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Would help all devs

## Problem description

I've read the Cloud Platform documentation ([Using the Cloud Platform Prometheus, AlertManager and Grafana](https://ministryofjustice.github.io/cloud-platform-user-docs/03-other-topics/006-prometheus)) and I've read through the Prometheus and Alertmanager documentation.

I've played around with the Prometheus and Grafana queries.

But...

I'm still not really sure what metrics Cloud Platform is providing automatically and also what basic alerts would be a good idea using those metrics.

So it would be great if Cloud Platforms could do a walkthrough/demo/show and tell that shows off what comes out of the box and what best practices. (Either a dedicated session or a TechTime takeover?)

Record the session and publish whatever slides were prepared and it could be added to the documentation  so clueless newbs like me have a resource for the future and no need to use CP team as their own personal FAQ machine.

## Contact person

Alex Robinson

**Comment by AntonyBishop** [comment]
Hi Alex. Will include as something for our next sprint starting on Monday 14th.

**Comment by AntonyBishop** [comment]
Hi Alex. We took this story through planning last week. We will be breaking this down into a number of smaller stories focused on improved guidance, as well as a session at an upcoming TechTime.

**Comment by AntonyBishop** [comment]
New stories raised.
