### ISSUE TITLE
Add AlertManager integration for laa-crown-court-remuneration-production

### ISSUE THREAD

**Issue by mpw5** [ministryofjustice/cloud-platform#5882]
## Service name

Crown Court Remuneration (CCR)

## Service environment

Production

## Impact on the service

Enable slack notification for Prometheus alerts to allow us to monitor our service.

## Problem description

Namespace name - laa-crown-court-remuneration-production
Team name - laa-crime-higher-billing
Application name - crown-court-remuneration
Slack channel - #laa-alerts-ccr-prod
Kubernetes secret name where the web-hook url is stored - ccr-env-vars (`SLACK_ALERTS_WEBHOOK`)
Severity level - warning

## Contact person

Name: Mark Whitaker
Slack handle: mark.whitaker
Email address: mark.whitaker@digital.justice.gov.uk

Name: Victor Olorunleye
Slack handle: Victor Olorunleye
Email address: [victor.olorunleye@digital.justice.gov.uk)

**Comment by Matt-Alinosn** [comment]
Victor added as 2nd contact to cover Mark while on AL. Request for this was made by Matthew Mayes (PM).
