### ISSUE TITLE
Add Pingdom integration for laa-crown-court-remuneration-production

### ISSUE THREAD

**Issue by mpw5** [ministryofjustice/cloud-platform#5884]
## Service name

Crown Court Remuneration (CCR)

## Service environment

Production

## Impact on the service

Enable slack notifications for Pingdom alerts to allow us to monitor our service.

## Problem description

Please could you generate a Pingdom integration id to allow us to display availability alerts in the appropriate channel.

Team name: Crime Higher Billing
Application name: crown–court-remuneration
The target slack channel: #laa-alerts-ccr-prod

## Contact person

Name: Mark Whitaker
Slack handle: mark.whitaker
Email address: [mark.whitaker@digital.justice.gov.uk](mailto:mark.whitaker@digital.justice.gov.uk)

Name: Victor Olorunleye
Slack handle: Victor Olorunleye
Email address: [victor.olorunleye@digital.justice.gov.uk)

**Comment by Matt-Alinosn** [comment]
Victor added as 2nd contact to cover Mark while on AL. Request for this was made by Matthew Mayes (PM).

**Comment by sj-williams** [comment]
Passed integration id to team
