### ISSUE TITLE
Investigate removing wait timers in gatekeeper and cert_manager

### ISSUE THREAD

**Issue by mikebell** [ministryofjustice/cloud-platform#5886]
## Background

Do we need the timers in gatekeeper and cert_manager now that they've been moved to `core`. This could save around a minutes on build time.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tom-j-smith** [comment]
Not removing gatekeeper's wait for a couple of reasons:
- Discussed with Jas, Gatekeeper's waits are used for other resources within the module
- From testing, Certmanager takes longer to finish building than Gatekeeper (including its waits) so removing the waits should not make a difference to overall time. 

[PR created](https://github.com/ministryofjustice/cloud-platform-terraform-certmanager/pull/46) for Certmanager to remove the wait - 
This change has been tested using a test cluster and no issues were seen when building core and components.
The change should reduce cluster build times by 1 minute as certmanager is the last component to finish building at the core level.
