### ISSUE TITLE
Spike: Event driven architecture on Cloud Platform

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/cloud-platform#5888]
## Background

There are workflows that are event driven and do not require containers running all the time.  This spike is to look at how we could allow event driven workflows on the Cloud platform.

## Proposed user journey

Spike into various solutions and patterns, such as using Keda or potentially reassessing Lambda.  It would be good to do some user research to understand what user needs are.

## Communicate changes

N/A

## Definition of done

- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
This was spiked [keda](https://github.com/ministryofjustice/cloud-platform-terraform-keda)

**Comment by jackstockley89** [comment]
module working in a test cluster, to test the user experience of using this module we need to create a test application 
[#6605](https://github.com/ministryofjustice/cloud-platform/issues/6605) has been created for this work. This will enable us to test the scaling of the pod with event-driven scaling
