### ISSUE TITLE
Give users read only permission to Athena

### ISSUE THREAD

**Issue by timckt** [ministryofjustice/cloud-platform#5891]
## Background

Users have started using Athena on the CloudPlatform in development, they can invoke the Athena API using only a IAM role, but being able to see Athena details in the console would help with development.

## Approach

Update https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso to include a new file for Athena. Viewing custom models could should be restricted with tags as per other resources.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Contacted Athena-using team, there is no need for AWS console access for the service at this time.
