### ISSUE TITLE
build docker image is broker

### ISSUE THREAD

**Issue by StupidCodeFactory** [ministryofjustice/cloud-platform#59]
## Service name

PVB

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

we can't deploy code to either staging nor prod

## Problem description

Since this build it docker can't push the new build image:
https://ci.service.dsd.io/view/PVB2/job/pvb-build-staff/974/console

## Contact person

@stupidcodefactory

**Comment by razvan-moj** [comment]
Fixed, was https://moj-digital-tools.pagerduty.com/postmortems/1530eef5-84a4-0abd-5558-24db98b6c550
