### ISSUE TITLE
MPS not alerting

### ISSUE THREAD

**Issue by lukaszraczylo** [ministryofjustice/cloud-platform#591]
Issue:
Servers were returning default nginx welcome page instead of service and our alerting systems haven't picked it up for some reason.
Needs investigation.

**Comment by pwyborn** [comment]
3 checks added to pingdom:
mps_healthcheck
mps_homepage
mps_ping

Tested alarm
Have also added slack integration extension to the "#moving-people-safely" slack channel (in addition to existing "#high-priority-alarms"

**Comment by lukaszraczylo** [comment]
We should ensure that applied checks and changes are reflected in our terraform configuration for mentioned services to avoid the same issue in future.

**Comment by pwyborn** [comment]
Please see https://github.com/ministryofjustice/cloudplatforms-terraform-ops/pull/33
The checks were actually there (however pingdom check names were "Person Escort Record" etc. I have added "Moving People Safely" to these names to help with identification
Will just retest these

**Comment by pwyborn** [comment]
I wonder if the original alert got missed because they were under "Person Escort Record"? Would the nginx welcome page have returned a 200 for pingdom?
