### ISSUE TITLE
AWS console account for Apply for Legal Aid

### ISSUE THREAD

**Issue by stephenrichards** [ministryofjustice/cloud-platform#592]
## Service name

apply-for-legal-aid

## Service environment

- [ ] Dev / Development
- [ x] Staging
- [ x] Prod / Production
- [ ] Other

## Impact on the service

needed for ongoing development

## Problem description

We need to be able to access the AWS console to view our EC2, RDS, elasticache resources on this project.  I have an account, stephenrichards.  We also need accounts for the following team members:
Rob Nichols,
Mark Whitaker
Tony McKernan
Julien Sansot
Will Clarke
Damon Fergus

## Contact person

Stephen Richards
stephen.richards@digital.justice.gov.uk
@stephenrichards

**Comment by jasonBirchall** [comment]
After a chat with Stephen, this was no longer required.
