### ISSUE TITLE
EBS Active snapshots limit

### ISSUE THREAD

**Issue by mikebell** [ministryofjustice/cloud-platform#5921]
## Background

https://mojdt.slack.com/archives/C8QR5FQRX/p1721905415494979

The amount of Active snapshots is growing by around 600 a day. That gives us around 71 days until we max out again. We've already upped it twice in the past 2 months from 175000 to 250000 and it's already over double the default quota value as well. 

Investigate to see if this is just normal usage or whether there is something wrong.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tmahmood72** [comment]
[ebs_snaps.csv](https://github.com/user-attachments/files/16563699/ebs_snaps.csv)

**Comment by tmahmood72** [comment]
EBS snapshots increase from 210189 on 31/07/2024 to 213718 on 09/08/2024 - which equates to an **approx weekly increase of 3529**

Currently the Velero backup retention is 30 days, so we should consider reducing this  (14 days ?)
Need to discuss if we need to go back further

Steve Williams
If we're not resolving loss of namespace for individual team within that period somethings off.
And as for total loss of cluster.

**Comment by sj-williams** [comment]
This tickets scope has been covered. Next steps:

Next sprint:
https://github.com/ministryofjustice/cloud-platform/issues/5954

If this fails to identify a useful archiving process for velero snapshots, then we will need to consider adjusting the velero retention period.
