### ISSUE TITLE
Trivy scan is showing issues in Dockerfile https://github.com/ministryofjustice/cloud-platform-maintenance-page/blob/main/Dockerfile.

### ISSUE THREAD

**Issue by jodiejones-moj** [ministryofjustice/cloud-platform#5924]
## Problem description

Whilst undertaking an Application Security our Trivy test has highlighted a few issues with a dockerfile that is getting pulled from cloud platforms. I believe this is the repo https://github.com/ministryofjustice/cloud-platform-maintenance-page/blob/main/Dockerfile.

There is a mixture of high, medium and low issues found which can be see in the following report  https://docs.google.com/document/d/167kRblNjIcpp7LEPJC4hoWCkGfYkg6Eh/edit 

Here are some examples:
```
Container 'maintenance-page-staff' of Deployment 'maintenance-page-staff' should set 'securityContext.allowPrivilegeEscalation' to false 
(A program inside the container can elevate its own privileges and run as root, which might give the program control over the container and node)
```
```

Container 'maintenance-page-staff' of Deployment 'maintenance-page-staff' should set 'securityContext.runAsNonRoot' to true 

(Force the running image to run as a non-root user to ensure least privileges) 
```

```
container "maintenance-page-staff" of deployment "maintenance-page-staff" in "default" namespace should specify a seccomp profile

(A program inside the container can bypass Seccomp protection policies.)
```
```
Container 'maintenance-page-staff' of Deployment 'maintenance-page-staff' should set 'securityContext.readOnlyRootFilesystem' to true 

(An immutable root file system prevents applications from writing to their local disk. This can limit intrusions, as attackers will not be able to tamper with the file system or write foreign executables to disk.)
```

Please let me know if you need access to this report or require any additional information.

## Contact person

jodie.jones@digital.justice.gov.uk](mailto:jodie.jones@digital.justice.gov.uk or slack channel #ask-panda-cyber

**Comment by sj-williams** [comment]
Have reviewed this ticket - I believe that these findings are likely being simulated in a sandboxed cluster environment (we don't allow running of any pods in `default` namespace).

Additionally the example securityContext and seccomp findings are covered at cluster level by our Gatekeeper constraints and mutations. Reached out to security team and provided some links explaining how we mitigate this level of container permissions.
