### ISSUE TITLE
New Low Priority alerts for Elasticsearch and Opensearch

### ISSUE THREAD

**Issue by mikebell** [ministryofjustice/cloud-platform#5928]
## Background

During the 25/07/24 logging incident we had no high priority alarms to indicate there was anything wrong. We need to put in place the following:

* diskspace on Elasticsearch
* diskspace on Opensearch
* number of logs below n threshold

Feel free to edit and add more to this ticket.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by timckt** [comment]
did some traffic analysis for our ElasticSearch.

We can run below command in Kibana Dev Console to calculate the average number of logs per minute during a specific time window.

```
GET /live_kubernetes_cluster*/_search
{
  "size": 0, 
  "query": {
    "range": {
      "@timestamp": {
        "gte": "2024-08-13T09:00:00",
        "lte": "2024-08-13T17:00:00",
        "format": "strict_date_optional_time"
      }
    }
  },
  "aggs": {
    "logs_per_minute": {
      "date_histogram": {
        "field": "@timestamp",
        "fixed_interval": "1m"
      }
    },
    "avg_logs_per_minute": {
      "avg_bucket": {
        "buckets_path": "logs_per_minute._count"
      }
    }
  }
}
```
| Index                    | avg logs per min during working hours | avg logs per min during non working hours | avg log per mins in 1 week |
|--------------------------|---------------------------------------|-------------------------------------------|----------------------------|
| *                        | ~1610000                              | ~700000                                   | ~1600000                   |
| live_kubernetes_cluster* | ~1000000                              | ~360000                                   | ~720000                    |

We can then use these figures and then determine the baseline threshold.

**Comment by timckt** [comment]
- Turn on alert for elasticsearch total node storage
  - https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/update-cw-alert-for-es/terraform/global-resources/elasticsearch.tf#L288
