### ISSUE TITLE
A user need to understand how to get application metrics from Prometheus

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#593]
## Background

This story was created following #586 . On review of this story we have identified that we do not have sufficient information to help users understand how to use Prometheus to get application metrics.

To help our users we need to create some additional guidance.

## Proposed user journey

As a user I need to understand what metrics Prometheus provides so that I can better understand what information is available to me and what I might need to set up in Prometheus so that I can better support my application.

## Approach

Create some guidance for the user guide that will help users understand where to find information about what metrics Prometheus provides and how to set up Prometheus to find metrics for their application.

## Which part of the user docs does this impact

New section of user guide

## Definition of done

- [x] user docs have been updated
- [ ] users know where to go to access the information they need to understand their app metrics

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by alkar** [comment]
https://github.com/ministryofjustice/offender-management-allocation-api/pull/64/ might be a good reference for this!

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-user-docs/commit/c7a8cedbc6f2389dbfc870b26728d2620afa994d
