### ISSUE TITLE
A user knows how to set up alerts based on Prometheus metrics

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#594]
## Background

This story was created following #586 . On review of this story we have identified that we do not have sufficient information to help users understand how to create alerts based on their Prometheus app metrics.

To help our users we need to create some additional guidance.

## Proposed user journey

How to setup alerting routes to specific slack channels for custom alerts 

## Approach

Create guidance in the guide to create custom routes.

## Which part of the user docs does this impact

New section in user guide.

## Definition of done

- [x] user docs have been created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
This ticket has been amended to how to add different routes in AM to specific channels. The work for this ticket will be done as part of #593

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-user-docs/pull/109#discussion_r258981261
