### ISSUE TITLE
Prepare a session on Prometheus and Alert Manager for an upcoming TechTime

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#595]
## Background

Users have asked for additional guidance on Prometheus and Alert Manager. To help meet this need we are producing some additional guidance, but will also run a session at an upcoming TechTime.

We are not the experts on Prometheus and Alert Manager, however we can provide some insights on how we use Prometheus and Alert Manager. We can share any tips of tricks we have come up with.

## Approach

Prepare a session for an upcoming TechTime

## Definition of done

- [ ] Session prepared
- [ ] TechTime session booked in
- [ ] TechTime Session held

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Agreed with the team that this issue can be closed.
