### ISSUE TITLE
Velero Backups Cleanup

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5951]
## Background

Our velero S3 bucket `cloud-platform-velero-backups` contains backup data for many old test clusters.

Clean these up and verify no dangling EBS snapshots.

We should also consider a means of automatically deleting velero backups for environments that have deliberately been removed (at least any test cases)

## Definition of done

- [ ] do we want a runbook entry for this?
- [ ] another team member has reviewed
- [ ] anything of value for demoing on this task?

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tmahmood72** [comment]
1) Checked there are no current test clusters that on the S3 Folder list below:-
2) Checked there are no Snapshots in the below S3 Folders:-
api-latency/		
autoscaler/			
big/				
certman-repo/		
cm/					
coredns/			
cortex/				
cp-0310-1352/		
cp-0503-1138/
cp-0603-1554/
cp-0610-0724/
cp-0703-0850/
cp-0804-1315/
cp-1103-1411/
cp-1104-1419/
cp-1202-1341/		
cp-1303-1134/
cp-1303-1501/
cp-1306-0739/
cp-1508-1408/
cp-1803-0857/
cp-1903-0814/
cp-2111-0854/
cp-2501-1205/
cp-2802-1409/
dev-alpha/
metend/				
nginx/							
opa/				
prometheus/			
raz-test-two/		
raz-test/			
yy-0209-0000/		
yy-0509-0001/

The remaining Folders in the S3 bucket cloud-platform-velero-backups is:-
![Image](https://github.com/user-attachments/assets/a15a412b-29a5-4b8e-994c-fe625a261df7)
