### ISSUE TITLE
New webhook for LAA legal Adviser API production

### ISSUE THREAD

**Issue by starswan** [ministryofjustice/cloud-platform#5953]
## Service name

Legal Adviser API

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

New webhook for alerting

## Problem description

New webhook for alerting matching that created for staging

namespace name laa-legal-adviser-api-production
team name. CCQ Refer
application name Legal Adviser API
slack channel eligibility-alerts-production
kubernetes secret name where the webhook url is stored slack-webhook/webhook
severity level (warning/information) warning

## Contact person

Stephen Dicks

**Comment by FolarinOyenuga** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/3285
