### ISSUE TITLE
Investigate NodeMemoryMajorPagesFaults alert

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5963]
## Background
We're seeing another new lower priority alert coming through from node-exporter.

We need to do some reading into this, attempt to understand why we are seeing it now. Is it a noisy alarm we can ignore or is it pointing towards an emergent problem with the cluster / some app running on it.

Document findings here.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
From the alert this morning which started at 6.35am on node `172.20.113.35` we can see a unusual memory spike related to a modsec controller. Further investigation is needed but the [common logs](https://logs.cloud-platform.service.justice.gov.uk/_dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-07T05:23:44.833Z',to:'2024-08-07T06:00:00.000Z'))&_a=(columns:!(github_teams,log),filters:!(),index:b95d8900-dd15-11ed-87c8-170407f57c9c,interval:auto,query:(language:kuery,query:'kubernetes.pod_name:%20%22nginx-ingress-modsec-controller-65595cc9bd-fw9c8%22'),sort:!())) around that time are related to `hale-platform` and a variety of phase 2 blocks / access denied with 403.

https://mojdt.slack.com/archives/C8QR5FQRX/p1723008922049909

![Image](https://github.com/user-attachments/assets/b78d481c-179f-4f23-8b25-1a010985eb95)


![Image](https://github.com/user-attachments/assets/db5e4ac9-18c8-4946-9684-2d1df98d1f8e)

**Comment by tom-webber** [comment]
The resource usage spikes on the `nginx-ingress-modsec-controller` pod (high CPU load, growing memory, high context switches & interrupts, high network usage) and the `NodeMemoryMajorPagesFaults` alerts in the lower-priority-alarms channel all correlate with a very high frequency of `"upstream prematurely closed connection"` messages in the `nginx-ingress-modsec-controller` pod logs (not the ingress logs). 

Here's an [example of time period with and without errors](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-08T07:00:00.000Z',to:'2024-08-08T18:31:54.382Z'))&_a=(columns:!(log),filters:!(),index:'8a728bc0-00eb-11ec-9062-27aa363b66a2',interval:auto,query:(language:kuery,query:'%22upstream%20prematurely%20closed%20connection%22'),sort:!())), that lines up with alerts in low-priority channel (search string: _[FIRING:1] :warning: NodeMemoryMajorPagesFaults before:2024-08-09 after:2024-08-07 in:#lower-priority-alarms_)

These `"upstream prematurely closed connection"` messages are seen across a number of different applications throughout the day.

Looking into these warnings, there are a number of ingress settings that could be altered in response to seeing this message:
* "[Higher timeout for the nginx proxy](https://stackoverflow.com/a/48858256/10478115)"
* "[Increase proxy_max_temp_file_size](https://stackoverflow.com/a/66686878/10478115)"

**Comment by tom-webber** [comment]
Over the last week the issue appears to be primarily with `*staging.checklegalaid.service.gov.uk`

![Image](https://github.com/user-attachments/assets/768b2117-ec16-4799-8ef6-220f8f7490c7)

**Comment by jaskaransarkaria** [comment]
The last alarm was triggered Weds 21st Aug https://alertmanager.live.cloud-platform.service.justice.gov.uk/#/alerts?receiver=slack-warning
