### ISSUE TITLE
cla_frontend demo instance deploy failed with full disk

### ISSUE THREAD

**Issue by farrepa** [ministryofjustice/cloud-platform#597]
## Service name

cla_frontend

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X] Other: Demo

## Impact on the service

Deployment blocker.

## Problem description

[Failed deploy](https://ci.service.dsd.io/job/DEPLOY-cla_frontend/134/console) to cla_frontend demo instance:

```
[52.16.24.163] out:   File "/usr/lib/python2.7/dist-packages/salt/utils/__init__.py", line 1123, in flopen
[52.16.24.163] out:     fcntl.flock(fp_.fileno(), fcntl.LOCK_UN)
[52.16.24.163] out: IOError: [Errno 28] No space left on device
[52.16.24.163] out: 

Fatal error: One or more hosts failed while executing task 'run_deploy'

Aborting.
```

I would clear space on the instance myself, but I don't have access.

## Contact person

Patrick Farrell
`@Patrick Farrell` on Slack
patrick.farrell@digital.justice.gov.uk

**Comment by jasonBirchall** [comment]
Cleaned up new instance. Will ask if they want the volume increased.

**Comment by jasonBirchall** [comment]
No need to increase. Closing.
