### ISSUE TITLE
infrastructure-repo: remove dangerfile

### ISSUE THREAD

**Issue by mikebell** [ministryofjustice/cloud-platform#5990]
## Background

We no longer need the `dangerfile` so it can be removed from the cloud-platform-infrastructure repo.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tmahmood72** [comment]
PR created https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/3384

**Comment by tmahmood72** [comment]
PR approved, merged to main.
