### ISSUE TITLE
Review Disaster Recovery Scenario: Losing the whole cluster

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5999]
## Background
This DR scenario documentation is now out of date - it relies on using the obsolete create-cluster ruby script (no longer working since we introduced the `core` terraform layer and has not been maintained since we switched to CP CLI).

## Approach

Run through the steps for simulating total loss of a test cluster and restore using the CLI [create cluster](https://github.com/ministryofjustice/cloud-platform-cli/blob/main/doc/cloud-platform_cluster_create.md) command.

Once testing is complete, update the runbook.

Finally, now would be a good time to remove the old ruby cluster scripts from the infra repo.

## Questions / Assumptions

Has any part of the DR process changed other than the move to the CLI create cluster?

## Definition of done

- [ ] runbook has been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by FolarinOyenuga** [comment]
### Will be done with this in sprint 15.

**Comment by FolarinOyenuga** [comment]
## Recreation Process and Log Output

### Test Cluster Creation
After running **cloud-platform cluster create --name dr-scenario** as instructed [in this runbook entry](https://runbooks.cloud-platform.service.justice.gov.uk/eks-cluster.html#provisioning-an-eks-cluster-with-the-cloud-platform-cli), all needed resources were created, but this error popped up after terraform was done applying:
`FATA[0215] error describing vpc: MissingRegion: could not find region configuration  subcommand=create-cluster`

**Comment by FolarinOyenuga** [comment]
Had a blocker on this last week before taking down the initial test cluster. But i seem to have found a fix.

**Comment by FolarinOyenuga** [comment]
## Findings

### Restore a Deleted Namespace
After deleting a namespace in the test cluster, ran **velero restore create my-starter-pack-restore --from-backup velero-allnamespacebackup-20241212120053 --include-namespaces starter-pack-0 --wait** which ran successfully. But **kubectl get all -n my-starter-pack-restore** returned **No resources found in my-starter-pack-restore namespace.**

#### Further Probe and Findings
**velero restore describe my-starter-pack-restore --details** returned the following:
<img width="1645" alt="Image" src="https://github.com/user-attachments/assets/737d4007-5c84-4f78-9186-1152fbc51de8" />


When i ran `velero version`, it generated the following along with the error at the bottom:
<img width="805" alt="Image" src="https://github.com/user-attachments/assets/22ecb43c-5ae5-43e3-b28e-fd04ebc6a472" />

**Comment by FolarinOyenuga** [comment]
Another attempt at restoring a namespace I created and created a deployment on on a different test cluster worked by running this command **velero restore create restore-ns --from-backup velero-allnamespacebackup-20241217090042 --include-namespaces ns-restore --wait**

However, i noticed neither the deployment nor the pods within it were restored along with the namespace. These were created in the namespace within the 3hr backup window.

**Comment by FolarinOyenuga** [comment]
### Restore a Deleted Object/Deployment
I created a deployment with 3 replicas **my-deployment** in the **ns-restore** namespace within the backup window, then deleted it after it had been successfully backed up to s3. I then went on to delete the namespace, which deleted the deployment and its pods too. However, I realized the namespace was empty after I restored it to the cluster, which shouldn't be.

**Restore**: Going by [this](https://runbooks.cloud-platform.service.justice.gov.uk/disaster-recovery-scenarios.html#losing-a-kubernetes-component-or-object-possible-cause) part of the runbook, I ran **velero restore create <restore-name> --from-backup <backup-name> --include-namespaces <namespace> --wait
** to restore the deployment, then **kubectl get deployments -n ns-restore**, but the namespace was still empty.

**Solution**: This successfully got the deployment along with its pods back **velero restore create restore-deployment --from-backup velero-allnamespacebackup-20241217090042 --selector=my-deployment --include-namespaces ns-restore --wait**. Confirmed this by running **kubectl get deployments -n ns-restore**

**Comment by FolarinOyenuga** [comment]
### Restore a Cluster
I began by restoring an old test cluster onto a new one (they have different names).
This required me having in hand the following:
- old cluster's backup-location CLUSTER?PREFIX value
- old cluster's backup-location NAME (usually default)
- old cluster's backup name

#### Scenario 1: When Velero has been enabled on theNew Cluster and now has a backup-location Different from the Old Cluster

Steps:

- unset the backup-location of the new cluster: velero backup-location set <new-cluster-backup-location-name> --default=false
- create a .yaml file that contains details of the old cluster's backup-location in this format:
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: **<any-name-except-default>**
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: cloud-platform-velero-backups
    prefix: cp-0000-0000 #velero backup-location get (from the old cluster)
  config:
    region: eu-west-2

- kubectl apply -f backup-location-name.yaml
- velero backup-location set **<any-name-except-default>** --default=true
- velero restore create --from-backup velero-allnamespacebackup-timestamp (get this on the old cluster by running **velero backup get**)
- confirm the restore by running **velero backup-location get**. What you get will be same as the old cluster's backup location. **velero backup get** will return the old cluster's backup name too.

**Comment by FolarinOyenuga** [comment]
### Deleted Terraform State
[This](https://runbooks.cloud-platform.service.justice.gov.uk/disaster-recovery-scenarios.html#deleted-terraform-state) step-by-step process was followed and the namespace was successfully imported and re-added to the state file. 

Although I did this within a Terraform workspace, I took extra caution by first creating a feature branch before deleting the namespace from terraform state.

**Comment by FolarinOyenuga** [comment]
### Recovering More Complex Scenarios

**Comment by FolarinOyenuga** [comment]
### Resolving a PartiallyFailed Backup Alert
Going through [this section](https://runbooks.cloud-platform.service.justice.gov.uk/disaster-recovery-scenarios.html#resolving-a-partiallyfailed-backup-alert)

**Comment by FolarinOyenuga** [comment]
### Deleting a Backup Storage Location After Test's Done
When you're done running necessary tests or no longer need the data in your current cluster's backup-location:

1. check the backup locations attached to the current cluster (typically called default unless modified): **kubectl get backupstoragelocation -n velero** or **velero backup-location get**
2. Delete it: kubectl delete backupstoragelocation <backup-location-name> -n velero
3. delete the backup data from the s3 bucket: **aws s3 rm s3://cloud-platform-velero-backups/<cluster-name> --recursive**

This is imperative to avoid leaving behind orphaned resources or cluttering the **Backups** bucket.
