### ISSUE TITLE
Remove a number of onDmarc addresses from the domains via Route53

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#600]
## Service name

Domains

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [x] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

No impact on running of services. We no longer want DMARC reports being sent to OnDMARC

## Problem description

We have 63 Domains that are sending DMARC reports to OnDMARC that we no longer require.

Each domain needs to have the OnDMARC email address removed in Route53.

Tony has the list of domains.

## Contact person

Tony Bishop, @AntonyBishop, antony.bishop@digital.justice.gov.uk

Tony has the list of domains that require changes. Speak to Tony.

**Comment by lukaszraczylo** [comment]
I've checked random records from the list ( marked as red ) and I can't find any of dmarc settings mentioned.

**Comment by lukaszraczylo** [comment]
Records were daisychained to  _dmarc_$something_policy.justice.gov.uk which I've modified. DNS propagation may take anywhere from one minute to one day.
