### ISSUE TITLE
Audit against Lowest security-related baseline for MOJ AWS accounts

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#601]
## Background

https://docs.google.com/document/d/1TWdeTmiMDbjcEnOzEXizr6254fGsZ6Wc77tKygCi4Ng/edit?usp=sharing

## Approach

- Review of Lowest security-related baseline for MOJ AWS accounts
- Evidence how we meet needs
- Document actions to meet baseline

## Definition of done

- [ ] Comment against each category
- [ ] Able to raise any stories to meeting any categories we do not meet

**Comment by sid234** [comment]
Baseline Templates completed. There are some minor fixes in Readme and how to deploy templates which is followed up in the card #231
