### ISSUE TITLE
Add ECR Lifecycle Policies to clean up ECR repos

### ISSUE THREAD

**Issue by mpw5** [ministryofjustice/cloud-platform#602]
## Service name

laa-apply-for-legal-aid

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [x] Other (UAT)

## Impact on the service

Hitting the 1000 image limit of our ECR repository temporarily stopped us pushing any further changes until we resolved it, which took ~60 minutes and hindered development/testing during that time. Our service is not currently live so impact was minimal but we would like to implement something to prevent such interruptions occurring regularly in future.

## Problem description

We had a problem recently where the laa-apply-for-legal-aid service hit the 1000 image limit of our ECR repository, which temporarily stopped us pushing any further changes. While we’ve resolved it for now, we’re looking into ways of preventing it happening again in future. 

One suggestion was ECR Lifecycle Policies - https://aws.amazon.com/blogs/compute/clean-up-your-container-images-with-amazon-ecr-lifecycle-policies.

Can the possibility of implementing this please be investigated?

## Contact person

Mark Whitaker - @mpw5 on GitHub and Slack, mark.whitaker@digital.justice.gov.uk by email.

**Comment by ollieanwyll** [comment]
Life cycle policies support has now been added to the module.
See release [2.1](https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials/releases/tag/2.1)
