### ISSUE TITLE
Block concourse restart applies from running on concourse

### ISSUE THREAD

**Issue by tom-webber** [ministryofjustice/cloud-platform#6021]
## Background

`terraform apply` scenarios that lead to restarting concourse services (e.g. changing resource allocations for concourse-web / concourse-worker) should be run locally, as they will cause issues if they are run on concourse itself. We need to detect these scenarios and block them from running before they are sent to concourse.

This could be a candidate for OPA validation #5996 (depends on #5996)

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jaskaransarkaria** [comment]
Maybe a simplier way to do this is add some conditional check to make sure that the node group changes aren't being run on manager default node group

**Comment by jaskaransarkaria** [comment]
duplicate https://github.com/ministryofjustice/cloud-platform/issues/6038
