### ISSUE TITLE
Unable to log in to Kubernetes pods for a project I am part of

### ISSUE THREAD

**Issue by chloepugh** [ministryofjustice/cloud-platform#6029]
## Service name

rd-hr-smart-knowledge-management-dev

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

As a team (https://github.com/orgs/ministryofjustice/teams/research-and-development) we need to be able to access the Kubernetes pods for the app we're developing, so that we can check the logs and run scripts manually if necessary. We are a small team, and due to upcoming leave we all need to have access to reduce delays. At the moment I am unable to access the pods despite having followed the instructions to connect to the Kubernetes cluster [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/kubectl-config.html#connecting-to-the-cloud-platform-39-s-kubernetes-cluster) and being a member of the github team.

## Problem description

I am unable to log into the pods for an app that I'm part of the github team for. I have followed the setup instructions but get the error `Error from server (Forbidden): pods is forbidden` when I run the command `kubectl -n rd-hr-smart-knowledge-management-dev get pods`.

I have tried running `cloud-platform kubecfg id-token-claims` (following guidance [here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/check-id-token.html#checking-the-github-groups-in-your-id-token)) and the only group I can see listed is `"github:all-org-members"`. I am a member of this github team but can't see it listed: https://github.com/orgs/ministryofjustice/teams/research-and-development.

Is anyone able to work out what's going on? Many thanks.

## Contact person

Chloe Pugh (also Chloe Pugh on Slack), chloe.pugh1@justice.gov.uk

**Comment by sj-williams** [comment]
Tried: 
- auth0 user delete
- delete old kube configs
- incognito method of re-authing into kuberos
- tested adding team to another namespace

So far no good. Interestingly the google auth step never happens, which is a new one for me.

May have to do a bit of log debugging on auth0 side as next step

**Comment by sj-williams** [comment]
This one was tracked down to the github teams api call only returning 30 teams per page (pagination ticket up next sprint will resolve this issue more cleanly). Once some AP org team membership cleanup was done, auth to cluster started working.
