### ISSUE TITLE
ECR Console read-only access

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#6036]
## Background
Our SSO module doesn't have a configuration for `ResourceTag` based filtering for ECR readonly permissions in AWS console.

It looks like we can add this for this resource type:
https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonelasticcontainerregistry.html#amazonelasticcontainerregistry-resources-for-iam-policies

Add ECR config to the [sso module](https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso) with appropriate IAM policy.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tom-j-smith** [comment]
ECR read only access has been added to the SSO module.
This has been tested using the `cloud-platform-dummy-user`

Can get all info about repositories and images that user is in group for, but is unable to see scanning and vulnerabilities section on image. This will require additional `inspector2` permissions.
Also tested with repositories user is not tagged in. They are able to list all repositories but when trying to open one it will display no images or further information about the repository.
