### ISSUE TITLE
Unarchive AMQ broker terraform module

### ISSUE THREAD

**Issue by timckt** [ministryofjustice/cloud-platform#6064]
## Background

Our [AMQ broker terraform module](https://github.com/ministryofjustice/cloud-platform-terraform-amq-broker) is now in archived state.

There are some user would like to use it but the module's configuration is out of date.

Update the module, verify it and make a new release 

## Approach

There is a updated [fork](https://github.com/ministryofjustice/cloud-platform-terraform-amq-broker/compare/main...georgepstaylor:cloud-platform-terraform-amq-broker:support-amq-5?expand=1) from our user and we may take this as a reference 

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tom-j-smith** [comment]
If there is more requirement for this module then we can unarchive.
