### ISSUE TITLE
Accessing Grafana dashboard on large screens

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#607]
## Service name

Grafana

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X ] Other

## Impact on the service

LGA-478 -- Display cla_public dashboard on TV for the team

## Problem description
We currently have a Grafana dashboard that we would like to displays on one of the large screens(uses raspberry pi) https://grafana.apps.cloud-platform-live-0.k8s.integration.dsd.io/d/87a9fc9281061289879d05928d54a80c6b57818a/laa-cla-public?orgId=1. 

We are currently accessing the dashboard through github authentication. and the authentication expires after a while and we have to re-authenticate.

We need a way to access the dashboard without re/authenticating on github

## Contact person
Name: Said Shire
Slack: [at]Said

**Comment by kcbotsh** [comment]
spoken to team. Will inform them if solution discovered. For now work around of having to log in once a day

**Comment by said-moj** [comment]
Hi @kcbotsh 
After speaking to digitalservicedesk, we can't add GH users to the organisation if they are not a MOJ user. 
This means we can't create a bot GH user to use on the large screen to authenticate with grafana. Is there any other option than using our own pesonal GH account which is not ideal?

**Comment by kcbotsh** [comment]
Hi @said-moj we do not currently have an alternative solution. This ticket is in our backlog but has not been prioritised up as a) there is a workaround b) it will require a lot of effort which we cannot currently accommodate with the current workload.
