### ISSUE TITLE
LGA-482: Access for Said to CLA/FALA EC2 instances

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#608]
## Service name

Our most recent new joiner is @said-moj  🎉 

I do not have sufficient privileges to create/apply the following permissions. Could you help, please?

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

None

### AWS access

- [x] moj-laalaa aws (https://moj-laalaa.signin.aws.amazon.com)

### EC2 instance SSH access

Please apply the following pull requests to all changed environments:

- [x] https://github.com/ministryofjustice/cla_public-deploy/pull/82
- [x] https://github.com/ministryofjustice/cla_frontend-deploy/pull/94 **<sup>note</sup>**
- [x] https://github.com/ministryofjustice/cla_backend-deploy/pull/94 **<sup>note</sup>**
- [ ] https://github.com/ministryofjustice/fala-deploy/pull/34
- [x] https://github.com/ministryofjustice/laalaa-deploy/pull/42

**<sup>note</sup>**:  ⚠️ Requires out of hours deploy to production: before 8:45 or after 20:15.

## Contact person

I am `@David Lantos` on Slack, however, I am off until 6 February 2019.
In my absence, please contact `@Said` on Slack.

**Comment by sldblog** [comment]
cc @said-moj

**Comment by lukaszraczylo** [comment]
PRs merged, deployment will follow OOH.

**Comment by lukaszraczylo** [comment]
*LAALAA*: STAGING, DEV, PROD

**Comment by pwyborn** [comment]
AWS access given to https://moj-laalaa.signin.aws.amazon.com

**Comment by pwyborn** [comment]
Duplicate ticket
