### ISSUE TITLE
Access for new developer to FALA/CLA

### ISSUE THREAD

**Issue by rowlando** [ministryofjustice/cloud-platform#611]
## Service name

Our team has one new developers:

- @said-moj 

Please can you set the up as below?

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

None

### AWS Access
- [ ] moj-cla-dev (https://moj-cla-dev.signin.aws.amazon.com)
- [ ] moj-laalaa aws (https://moj-laalaa.signin.aws.amazon.com)

### SSH Access
- [ ] SSH access to all `fala` environments
- [ ] SSH access to all `cla_backend` environments
- [ ] SSH access to all `cla_frontend` environments
- [ ] SSH access to all `laa-legal-aid-advisers` environments

### Monitoring
- [ ] Login for https://sentry.service.dsd.io/mojds/
- [ ] Added to the appropriate Sentry projects

## Contact person

Slack: @said
Email: said.shire@digital.justice.gov.uk

**Comment by pwyborn** [comment]
Duplicate ticket? https://waffle.io/ministryofjustice/cloud-platform/cards/5c4b0f7db16ef302ebcc411a

**Comment by kcbotsh** [comment]
Archiving as this is duplicate
