### ISSUE TITLE
Ingress: AWS Advanced Shield findings 

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#6114]
## Background
If we want to wrap AWS Shield Advanced around our ingress NLBs, we need to rebuild the load balancers with a new EIP configuration.

How we might approach this needs considering as there are many ways we could handle:

- downtime?
- new ingress class and move users over
- other things?

Also, we have found that even if we do replace our NLB config with EIPs, the Shield options are very limited, and relies on passive AWS monitoring, we cannot attach our own WAF rules to NLB IPs. In contrast, using ALBs for our ingress would allow us to do these things.

Capture all of the details in a google doc (linked [here](https://docs.google.com/document/d/1BCSbvee29LRzAHhhXrZ-ea3al97RK_BepPTizOAEXJw/edit)), and the possible options we have to move this forward. Share with team for wider discussion (we probably need to setup a session for this).

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by timckt** [comment]
We shall back to this ticket and have team discussion on this after our vpc cni incident.

**Comment by timckt** [comment]
We have discussed AWS Shield Advanced and ModSec in our team day on 10/Dec.

The next step on this will be having more spike on Shield and ModSec to let us understand more on the their functionality.
