### ISSUE TITLE
Get a database export out of Family Mediators API

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#612]
## Family Mediators API

App repo:
https://github.com/ministryofjustice/family-mediators-api

Template deploy repo:
https://github.com/ministryofjustice/oocp-familymediators-deploy

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [ ] Other

## Problem description

We've created the staging and production k8s environments for this service. We soon intend to decommission the current template deploy envs, and move 100% to k8s, but we would like to import current data from database to the new RDS k8s instance. Only for production environment.

As this is an old, template deploy service, I'm struggling to do this. I've tried SSH but no luck. I've also tried looking for the RDS in AWS mojdsd console but the names are not evident, and as I can't login by SSH can't actually "see" the RDS connection string to get the name.

I get this error when running fab ssh command:

```bash
bootstrap_cfn.errors.ZoneIDNotFoundError: Could not find a zone id for zone name 'familymediatorsapi.dsd.io'.Please check that this hosted zone exists and is in the account you've specified
```

We are happy with either:

- Get the RDS endpoint, so we can connect directly and export the data ourselves.
- Get access by SSH to do this ourselves.
- Get a zip/tar file with the export.
- Any other alternative?

## Contact person

Jesus @ slack

**Comment by razvan-moj** [comment]
Added a public IP to the staging database, and edited the security group to allow access from the k8s cluster
