### ISSUE TITLE
Overview for Digital Studio on how we use Github for authentication

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#613]
The Digital Studio Team would like to understand more about how we use Github for our authentication with the Platform.

This should include a bit of architectural overview and how we implemented the solution.

Digital Studio are thinking of adopting a similar approach and would like to learn from our experience.

**Comment by razvan-moj** [comment]
waiting for availability from DS team, should be tomorrow

**Comment by razvan-moj** [comment]
scheduled for Mon 4 Mar 2019 10:45am – 11:10am (GMT)
