### ISSUE TITLE
Intranet: Request for new alert route in Alertmanager 

### ISSUE THREAD

**Issue by EarthlingDavey** [ministryofjustice/cloud-platform#6134]
## Service name

intranet

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Problem description

Please may we have a new alert route?

namespace name: `intranet-dev`, `intranet-staging`, `intranet-production`
team name: `central-digital-product-team`
application name: `intranet`
slack channel: [#cdpt-intranet-and-justice-cloud-platform-alerts](https://moj.enterprise.slack.com/archives/C07LQH2TX88)
kubernetes secret: ns: `intranet-production` secret name: `intranet-alerts-slack-webhook` key: `url`
severity level (warning/information) `warning`

## Contact person

Davey Brown Slack: `@Davey`

**Comment by tmahmood72** [comment]
User also requested webhook alert for intranet-demo NS
