### ISSUE TITLE
check/change RDS deployments

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#614]
## Service name

RDS TF module

## Service environment

- [ ] Prod / Production

## Impact on the service

Blocks new deployments

## Problem description

We've hit a limit of 50 database subnet groups per VPC which according to AWS support feedback is not adviseable, so they will only increase it "with a serious business justification" whatever that means.
There are empty subnet groups, most likely forgotten from past experiments, so I have deleted a couple to unblock us but the problem remains.

Permanent solution would be to change the TF module so RDS DBs share a single subnet group

## Contact person

cloud-platform team

**Comment by pwyborn** [comment]
Since this ticket was created - the number of  database subnet groups per VPC has been increased to 100. So for time being this has been resolved (probably need to look at the whole rds solution in the future)
