### ISSUE TITLE
Amazon MQ Console access

### ISSUE THREAD

**Issue by georgepstaylor** [ministryofjustice/cloud-platform#6142]
## Service name

I am unable to access the Amazon MQ part of the AWS Console

<img width="1781" alt="image" src="https://github.com/user-attachments/assets/2675cfe6-9b77-404d-908a-309173c57c88">

## Service environment

- [x] Dev / Development
- [X] Staging
- [X] Prod / Production
- [X] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

I am attempting to access the ActiveMQ console to clear a number of queues, I would like to be able to see the console page for monitoring etc

## Problem description

I am unable to access the Amazon MQ part of the AWS Console

## Contact person

`@George Taylor` on slack

**Comment by sj-williams** [comment]
Contacted George about where things are at with this one.

MQ is a standalone terraform config for this CP team (not module), so adding to read-only SSO is not ideal. 

Maybe IAM + IRSA for service pod access to the queues will do?
