### ISSUE TITLE
Refactor Concourse creation Terraform

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#615]
BACKGROUND
The Concourse Terraform (https://github.com/ministryofjustice/cloud-platform-concourse/tree/master/resources) was written before the Helm provider was made available. This means it's slightly convoluted and hard to read. 

TASK
Refactor the Terraform code in the above location. There's already a Helm chart available in stable/helm that we use and the `values.yaml` file is templated and managed by terraform. Use these with the helm provider and discuss with the team the best version to use.

Additionally, the new version of concourse supports OIDC auth and we want to move away from OAuth2. We should use the auth0 provider (see examples in cloud-platform-components) and generate an app that we can use directly with Concourse. Finally, provided this works, clean up the Github oauth app we have been using.

**Comment by vijay-veeranki-moj** [comment]
There are two tasks in it 1) Refactor the Terraform code 2) use OIDC for concourse , which is been later added.

Completed task 1 which is originally this story is about , task 2 will be a separate story.

To complete Refactor Terraform code added resource "helm_release" "concourse" in terraform and removed setup-on-cluster script and updated the README.
