### ISSUE TITLE
preparing to enable Auto-merge for environments repo

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#6154]
## Background

https://mojdt.slack.com/archives/C57UPMZLY/p1718638917414309 before we enable auto-merge for the environments repo we need to verify that the quick succession of merged prs does not cause concourse to miss any applies.

Create several PRs (10 to 20) with minor changes and in quick succession (write a script) merge them in and check each apply is picked up in concourse

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
How do we separate between environments, also what about teams who don't want to auto-merge?

**Comment by tmahmood72** [comment]
We need to discuss this further as a team, with more detail from Jaskaran
