### ISSUE TITLE
Alerts manager route for hmpps-book-a-video-link

### ISSUE THREAD

**Issue by smcveigh941** [ministryofjustice/cloud-platform#6173]
## Service name

hmpps-book-a-video-link

team name: Book a video link
application name: hmpps-book-a-video-link
severity level (warning/information): warning

Dev:
namespace name: hmpps-book-a-video-link-dev
slack channel: #book-a-video-link-alerts
kubernetes secret name where the webhook url is stored: slack-alerts-hook

Preprod:
namespace name: hmpps-book-a-video-link-preprod
slack channel: #book-a-video-link-alerts
kubernetes secret name where the webhook url is stored: slack-alerts-hook

## Service environment

- [/] Dev / Development
- [/] Preprod
- [] Prod / Production (We dont have a prod environment yet)

## Impact on the service

Custom slack channel for easier monitoring of app issues

## Contact person

Stephen McVeigh (find me on slack)
stephen.mcveigh@digital.justice.gov.uk

**Comment by Kami-prog** [comment]
maybe this will help
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)

**Comment by tom-j-smith** [comment]
Created with the severity `hmpps-book-a-video-link-dev` and `hmpps-book-a-video-link-preprod`
It appears that there may be a `\n` left at the end of the kube secret in both namespaces, removed in configuration.
