### ISSUE TITLE
Refactor Prometheus Custom Rules

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#618]
BACKGROUND
Since an exporter version change the custom prom alerts that we've created no longer work. This is due to a metrics name change.

Current custom alerts:
`https://github.com/ministryofjustice/cloud-platform-prometheus/tree/master/custom-alerts`

TASK
Apply alerts on test cluster
Go through each alert and confirm the metrics still exist;
IF not then change the metric.

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/193
