### ISSUE TITLE
Querying on JSON log fields in Kibana

### ISSUE THREAD

**Issue by jennyd** [ministryofjustice/cloud-platform#619]
## Service name

Offender management (but probably any service on the new cloud platform)

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We aren't able to use our [application logs](https://kibana.apps.cloud-platform-live-0.k8s.integration.dsd.io/_plugin/kibana/app/kibana#/discover?_g=()&_a=(columns:!(kubernetes.labels.app,log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'15f41150-9a2e-11e8-914b-fd83344e98bd',key:kubernetes.namespace_name,negate:!f,params:(query:offender-management-staging,type:phrase),type:phrase,value:offender-management-staging),query:(match:(kubernetes.namespace_name:(query:offender-management-staging,type:phrase))))),index:'15f41150-9a2e-11e8-914b-fd83344e98bd',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc))) effectively to understand how our applications are behaving because we can't query on `status`, `path`, `controller`, `duration` etc.

## Problem description

Our application logs are already in JSON, but the log fields aren't available for querying on in Kibana. It should be possible for logstash to [parse the JSON fields](https://www.elastic.co/guide/en/logstash/current/plugins-filters-json.html) and make them queryable.

## Contact person

Toby Retallick

**Comment by vijay-veeranki-moj** [comment]
Worked on this task to parse the JSON fields and felt they are more dis-advantages parsing JSON fields with the current set up (EFK)

As shown in the demo, fields are parsed but missing the field mapping which missing the actual requirement of searching the parsed fields.

Refresh field list in Kibana management didn't help in mapping the fields.

![After applying parsing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c484b96e3e1000011d1ac6b/125516c66e82c728ace21e0d46c9928e2690c3a89ff9b35aad53f7d439473560200aa4693cc7f33ab0487e021b4d44be44090941aefcdb2ca6b4357089580bedd3680927c43b47f9aa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4a3e16011a80fd5431a59f5985.png)

**Comment by vijay-veeranki-moj** [comment]
Closed this as parsing the JSON fields is not working as expected.

will create a separate task in the backlog to do some research on any alternatives.
