### ISSUE TITLE
Move pingdom slack integration for family-mediators-api-production

### ISSUE THREAD

**Issue by vertism** [ministryofjustice/cloud-platform#6196]
## Service name

family-mediators-api-production

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

No impact

## Problem description

We would like to move the slack channel pingdom alerts are received on to cdpt-family-mediators-api

## Contact person

email: andrew.pepler@digital.justice.gov.uk
slack: `@Andrew Pepler`

**Comment by sj-williams** [comment]
Updated pingdom ids for:

- family mediators prod API
- disclosure checker production

Posted ids to @vertism
