### ISSUE TITLE
Search repos for `goo.gl` links and replace.

### ISSUE THREAD

**Issue by mikebell** [ministryofjustice/cloud-platform#6202]
## Background

goo.gl links are being deprecated by google (https://developers.googleblog.com/en/google-url-shortener-links-will-no-longer-be-available/), I've found one in the user guide so there may be others that need removing. Search our repos and see if there are any goo.gl links and replace with none shortened versions.

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by FolarinOyenuga** [comment]
## Findings

Upon investigation, it was discovered that the following repositories had goo.gl URL shorteners in some of their files:

User-guide repo - 4 files, each having a **goo.gl** url shortener
Runbook repo - 1 file containing two **goo.gl** shorteners


## Fixes
User Guide repo - [fix](https://github.com/ministryofjustice/cloud-platform-user-guide/pull/1737)
Runbooks repo - [fix](https://github.com/ministryofjustice/cloud-platform/pull/6219)
