### ISSUE TITLE
HMPPS Prison Person API (PROD): Request for new alert route in Alertmanager

### ISSUE THREAD

**Issue by brightonsbox** [ministryofjustice/cloud-platform#6204]
## Service name

HMPPS Prison Person API

## Service environment

This request is for the PRODUCTION environment:

## Problem description

Please may we have a new (production) alert route?

namespace name: `hmpps-prison-person-api-prod`
team name: `Connect DPS`
application name: `HMPPS Prison Person API`
slack channel: [#connect-dps-prod-alerts](https://moj.enterprise.slack.com/archives/C05V6LC5J2G)
kubernetes secret: ns: `hmpps-prison-person-api-prod` secret name: `hmpps-prison-person-api` key: `ALERTS_WEBHOOK_URL`
severity level (warning/information) `warning`

## Contact person

Jon Brighton Slack: `@Jon Brighton`

**Comment by tmahmood72** [comment]
Prod webhook alert created for namespace hmpps-prison-person-api-prod
User notoified=https://mojdt.slack.com/archives/C57UPMZLY/p1728903776875049
