### ISSUE TITLE
Change RoleBindings from cluster-admin to admin

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#621]
## Background

N/A

## Proposed user journey

N/A

## Approach

A number of `RoleBindings` in user namespaces reference the `cluster-admin` `ClusterRole`. We should change them to use the `admin` `ClusterRole` instead.

That is a built-in `ClusterRole` designed to be used in namespaces and is also easily modifiable by using [`ClusterRole` aggregation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles).

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

This should not have an effect on users. In fact, a large number of user `RoleBindings` are defined properly.

## Definition of done

- [ ] the changes have been made in `cloud-platform-environments`
- [ ] the changes have been applied and we've had no issues

## Reference

```
kubectl get rolebinding --all-namespaces -o json  | jq '.items[] | select(.roleRef.name == "cluster-admin") | .metadata.namespace + "/" + .metadata.name'
```

**Comment by AntonyBishop** [comment]
Check Financial Eligibility Checker

**Comment by AntonyBishop** [comment]
Done

**Comment by vijay-veeranki-moj** [comment]
Done,PR for this

https://github.com/ministryofjustice/cloud-platform-environments/pull/1873/files
