### ISSUE TITLE
C100 application memory issues

### ISSUE THREAD

**Issue by zaparka** [ministryofjustice/cloud-platform#6212]
## Service name
Family Justice C100 Service

c100 
## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service
Slow or no response - preventing from people submitting applications.

## Problem description
We deployed latest changes to production. The applications is running in our environments. But when we are testing if it works correctly it's slow and eventually unresponsive. We also seen a error message code 137 in console.

I tried to run 

kubectl get hpa

but not getting anything anything just "No resources found in c100-application-production namespace"

## Contact person
petr.zaparka@hmcts.net  or petr zaparka on Slack

**Comment by timckt** [comment]
This should be working fine now.

https://mojdt.slack.com/archives/C57UPMZLY/p1727776029656459?thread_ts=1727702610.840099&cid=C57UPMZLY
