### ISSUE TITLE
Add NS Delegation for victim-support production domain

### ISSUE THREAD

**Issue by brettminnie** [ministryofjustice/cloud-platform#622]
## Service name

vcms

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Preparatory work for migration in February

## Problem description

We have created a hosted zone on our production aws account, we need to add the ns record to the apex domain

For the sub-domain `victim-support.service.justice.gov.uk` on `service.justice.gov.uk` we need the following ns record to be created

```
ns-19.awsdns-02.com.
ns-1959.awsdns-52.co.uk.
ns-1111.awsdns-10.org.
ns-874.awsdns-45.net.
```

## Contact person

brett.minnie@digital.justice.gov.uk
maximillian.lakanu@digital.justice.gov.uk (PM)

**Comment by kcbotsh** [comment]
Need verification from PM/ DM or SM

**Comment by robhettrick** [comment]
Verified from me.

**Comment by brettminnie** [comment]
@kcbotsh please see PM verification, if anything further is needed please contact @robhettrick

**Comment by lukaszraczylo** [comment]
Delegation set and is active as of now.
