### ISSUE TITLE
FALA: Not being able to trust Prometheus alerting & Kibana logs

### ISSUE THREAD

**Issue by MazOneTwoOne** [ministryofjustice/cloud-platform#6226]
## Service name

[Find a Legal Adviser](https://find-legal-advice.justice.gov.uk/)

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

- When we get these alerts in slack, we are assuming that our service is down, so we go to investigate on Grafana, Kibana & Prometheus and see nothing appearing and also that our site is still up. We are consistently getting false alarms. 

## Problem description

- We have a custom prometheus alerting rule (`namespaces/live.cloud-platform.service.justice.gov.uk/laa-fala-production/07-prometheus-custom-rules.yaml`) that is set-up in our `laa-fala-production namespace`, that is alerting us of 500 HTTP errors for the `fala-laa-fala` ingress. Annoyingly, when we go to check this in Grafana, Kibana & Prometheus we don’t see any such errors and our service is still up. 

- We added the Prometheus alerting with [this PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/25433) on 23/08/24 and the first sentry alert came in on 27/08/24 at 17:09 and then resolved itself at 17:14. We then got an alert every day, then every other day then 3 to 4 days.
- It’s the same alerting rule used on our other service `laa-check-client-qualifies-production`, which is not experiencing this, hence thinking it's something other than the prometheus alert rule.

With the help of Cloud Platform we were able to work out the following:
- For this alert which came in at 20:00 on 02/10/24: ![Image](https://github.com/user-attachments/assets/9fd3e552-dc4e-40d2-ac29-73f042694b0e)    
- We were able to see 502 errors on Prometheus using the following alert rule and going to exact date: ![Image](https://github.com/user-attachments/assets/50354ef6-cf6d-45ec-8d57-11062dfd4c6a)
- We then checked Open Search/Kibana with this search query` "nginx-ingress-modsec-controller-8c5f8b554-5vz58" AND log_processed.kubernetes_namespace: "laa-fala-production"` which picked out a pod with the most 502 errors (according to Prometheus) in the correct date range and could not see any 502 errors: ![Image](https://github.com/user-attachments/assets/33678922-a3dc-42fe-bcc5-65c3b653c901)

- This is the services deployment.yml https://github.com/ministryofjustice/fala/blob/main/.circleci/config.yml

## Contact person

[masum.khan@digital.justice.gov.uk](mailto:masum.khan@digital.justice.gov.uk)

**Comment by MazOneTwoOne** [comment]
Adding some further content. On the 11/10/24 at 19:46 our prometheus 500 alerts fired off these alerts in quick succession. The service was up and our Open Search/Kibana  logs did not see anything. 

They were quickly resolved. 

![Image](https://github.com/user-attachments/assets/f97aeade-6243-4c81-b253-dd82e2455a51)

**Comment by sj-williams** [comment]
This is still an issue for the team. Keeping in prog for next sprint - will require some support team priority to investigate.

**Comment by sj-williams** [comment]
Have spied a suspicious looking event in ingress logs:

https://app-logs.cloud-platform.service.justice.gov.uk/_dashboards/app/discover#/doc/ef705d70-0d2e-11ef-afac-8f79b1004d33/live_kubernetes_ingress-2024.11.11?id=DBEF91C7-0763-88DB-F3EF-3A4AB2842351

`upstream prematurely closed connection while reading response header from upstream`

**Comment by sj-williams** [comment]
Big spike in pod events in that window of time as well:
https://app-logs.cloud-platform.service.justice.gov.uk/_dashboards/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!f,sort:!()),metadata:(indexPattern:bb90f230-0d2e-11ef-bf63-53113938c53a,view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-11T17:49:00.000Z',to:'2024-11-11T17:51:00.000Z'))&_q=(filters:!(),query:(language:kuery,query:'kubernetes.namespace_name:%20%22laa-fala-production%22'))

**Comment by sj-williams** [comment]
Closing off as these findings marry up with alerts firing.
