### ISSUE TITLE
Review usage of mean-time-to-repair and potentially remove

### ISSUE THREAD

**Issue by mikebell** [ministryofjustice/cloud-platform#6251]
## Background

After converting the mean-time-to-repair go script there are some questions around whether it's useful or not.

1. Do we actually care about mean time to repair/resolve, each incident is unique and should be treated as such
2. No one is looking at these numbers
3. The incident log format needs an overhaul and update

I suggest we review it's usage in 6 months and decide if we want to remove this functionality.

**Comment by jaskaransarkaria** [comment]
@mikebell has removed this functionality as it isn't being used. @davidkelliott will find out which metrics we need.
