### ISSUE TITLE
RDS: Complete module upgrades

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#6270]
## Background
We have some outstanding work to do getting our RDS module changes merged in, with a release cut capturing all new features, and bump all module calls across environments repo.

We also need to publish comms around the new release and any action required due to the changing default behaviours.

Current releases and re-release targets:

| RDS Release | Details | Target release |
|-------------|--------|---------------|
| `7.2.0`        | Pre iops and IAM reboot release | `7.2.0` |
| `7.2.1`   |  IAM reboot only | ?? |
| `7.3.0`        | new iops and storage release | `8.0.0` |
| `7.3.1`        | new iops and storage + IAM reboot | `8.0.0` |
| `migration` | used by Oracle teams to migrate legacy DBs | a future `8.*.*` release |

- cut new `8.0.0` release
- bump all `7.3.0` / `.1`/ releases to `8.0.0`
- comms out for new major release `8.0.0`
- worry about `migration` branch later....

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by timckt** [comment]
- bumped the abundant ns existing `7.2.1` one to `7.3.0`
- created new `7.3.1` one in abundant ns 
- cut a new `8.0.0` release
- bumped 2 abundant ns RDS to `8.0.0`
- bumped user RDS from `7.3.0` to `8.0.0`
- bumped user RDS from `7.3.1` to `8.0.0`
