### ISSUE TITLE
Post OpenSearch migration: Remove ElasticSearch related content in our documents

### ISSUE THREAD

**Issue by timckt** [ministryofjustice/cloud-platform#6274]
## Background

After we have migrated to OpenSearch and decommission the ElasticSearch, we need to check and update our document to remove the ElasticSearch related content in our documents.

The should be done after https://github.com/ministryofjustice/cloud-platform/issues/5650 completed.

## Approach

- Search through our documents, include but not limited to:
  - User guide
  - repo readme
  - runbook
  - else where

- Remove the ElasticSearch related content

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Some updates to runbooks have been carried out here:
https://github.com/ministryofjustice/cloud-platform/pull/6460/files

**Comment by sj-williams** [comment]
Some new tickets created to cover additional documentation checks and rewrites:

https://github.com/ministryofjustice/cloud-platform/issues/6504

https://github.com/ministryofjustice/cloud-platform/issues/6503

https://github.com/ministryofjustice/cloud-platform/issues/6502

https://github.com/ministryofjustice/cloud-platform/issues/6501
