### ISSUE TITLE
Forbidden access to namespaces and pods for pathfinder, offender-categorisation, manage-soc-cases

### ISSUE THREAD

**Issue by cruffymoj** [ministryofjustice/cloud-platform#6276]
## Background

I cannot access pods and namespaces currently for security intelligence team as I get a forbidden message. I require access to pathfinder, soc, and offender-categorisation. This issue happens every two weeks so usually I open a incognito window and recreate the kubeconf file as instructed in - https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/kubectl-config.html#generating-a-kubeconfig-file. However this hasn't solved the issue this time. Can someone resolve this issue please? Ideally without having to regenerate the file every 10 days would be great.

## Proposed user journey

I would expect to not be locked out and forbidden from using these namespaces every two weeks

## Approach

Allow permissions to be permanent

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Spoken with Christian, this issue seemed to have ceased occurring as regularly as before, requested that should it happen again, please raise in CP ask channel.
