### ISSUE TITLE
Add additional AWS Elasticache metrics to the CloudWatch Exporter

### ISSUE THREAD

**Issue by mtac50** [ministryofjustice/cloud-platform#6277]
## Service name

Cloudwatch Exporter

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Unable to create Prometheus alerts based on a % threshold memory usage for an AWS elasticache instance.

## Problem description

Currently the CloudWatch exporter does not export the AWS Elasticache metric `DatabaseMemoryUsagePercentage`. This means that we cannot create alerts based on a % threshold memory usage for our REDIS instances. Currently we can only use the freeable memory which is an absolute quantity rather than a percentage.

## Contact person

michael.clancy@digital.justice.gov.uk

**Comment by jaskaransarkaria** [comment]
You can add the required metric here https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/blob/875ab774cf862aec7be3b69b4b1aecbd10f6abe5/templates/yace-cloudwatch-exporter.yaml#L444

**Comment by mtac50** [comment]
@jaskaransarkaria Am I ok to make the change and raise a PR or does that need to be done internally?
