### ISSUE TITLE
AWS Account Clean Up

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#628]
## Service name

AWS Account (See list held by Tony)

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X] Other

## Impact on the service

No impact. We have a number of potential AWS accounts that are no longer required.

## Problem description

There are potentially 34 AWS accounts that could be closed as they are no longer used.

We want to close unwanted accounts to improve security and reduce cost.

This task will involve the following:
- Confirm whether Cloud Platform team has access to an account
- If we have access to the account does it contain anything?
- If the account contains nothing then request account to be closed.
- If account contains anything notify Tony so that we can engage with owner to determine if account is still required.
- If we can't access the account update the log.

Update the log with findings.

## Contact person

Tony Bishop

**Comment by pwyborn** [comment]
* List Updated
* Rattic updated where accounts have been suspended/closed

Note:
 support calls:
* 5779080531	2019-02-12T11:21 
The gist of which is:
The suspended accounts have been closed - therefore we should not be being billed for them. From June 2018 - for any  account suspended after that date - you have 90 days if you want to reinstate that account -
My understanding is that any account prior to June 2018 would have been closed straight away
* 5780184391    2019-02-12T11:21Account Deletion (no root details kept regarding access - is the account suspended/closed) MoJ-Security	MoJ-Security@digital.justice.gov.uk	583321680329	Created on 5/1/18 - still awaiting AWS reply
* #opg-devops checking re 2 accounts not in Rattic:
** MoJ OPG Identity    aws+moj-opg-identity@digital.justice.co.uk    811982441201    Created on 8/3/18
(edited)
and
** MoJ OPG Identity    aws+moj-opg-identity-DEL2@digital.justice.gov.uk    660017192602    Created on 8/3/18

**Comment by pwyborn** [comment]
Information regarding AWS accounts provided  to Anthony/Steve on https://docs.google.com/spreadsheets/d/1Q7zfVaRVUrwsaHgQGbXY71B_FmRT2VvgsnqJqCM4xpM/edit#gid=977276284. 

To be closed
