### ISSUE TITLE
Archive cloud-platform-prometheus

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#629]
## Background

https://github.com/ministryofjustice/cloud-platform-prometheus/ is no longer used and we manage prometheus in https://github.com/ministryofjustice/cloud-platform-infrastructure/ as a 'component'.

Archive the repository after you've extracted docs & any other useful bits.

## Proposed user journey

N/A

## Approach

N/A

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

As defined above.

## Reference
N/A

**Comment by vijay-veeranki-moj** [comment]
![Screen Shot 2019-02-12 at 18.13.56.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c484b96e3e1000011d1ac6b/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216455f16b7191a379e70c2a52415a48be5d4a1f06a3a3dc78e2a436628f0d5de883680d73c63f18acbb861fbf03bf76d84d83e0e99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc51ff42e44f5da01b3f6af43b.png)

Archived the cloud-platform-prometheus remote repo, made a local copy also an did an download zip of this repo.
