### ISSUE TITLE
Pingdom prod integration for slack

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/cloud-platform#6294]
## Service name

Requesting for a Pingdom integration id for DataHub Catalogue prod under the k8s namespace `data-platform-datahub-catalogue-prod`

Team name: `data-catalogue`
Application name: `DataHub Catalogue`
Target slack channel name: `#data-catalogue-alerts-prod`

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Separate out prod pingdom alerts into a new slack channel

## Problem description

We currently have integration id `135556` across all our pingdom environments sending alerts to one channel. I would like to create a new integration to separate out the prod alerts:

## Contact person

Murdo Moyse (poster)

**Comment by murdo-moj** [comment]
Old Issue https://github.com/ministryofjustice/cloud-platform/issues/5640

**Comment by sj-williams** [comment]
Completed, posted new id to @murdo-moj
