### ISSUE TITLE
Obtain a copy of the Postcodeinfo database

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#630]
## Background

We are in the process of migrating users away from Postcodeinfo to OS Places. This will enable us to decommission the legacy postcodinfo API.

The Home Office have decided that in the interim they will stand up their own instance of the API on their own Infrastructure based on MoJ code. However, they have come across issues that means that the data import doesn't work. To get around this we have suggested that maybe we can provide an extract of our complete database that they can use in the interim whilst a longer term replacement is delivered.

## Proposed user journey

Home Office have a cut of data they can upload into their instance of the Postcodeinfo API.

## Approach

- Confirm we can provide an extract of data
- Extract data
- Get data to Home Office

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- Can we do this work? Small spike to determine if this is possible.

## Definition of done

- [x] Confirm we can produce an extract of data from the database
- [ ] Produce extract/copy of database
- [ ] Determine how to get data to Home Office
- [ ] Transfer data to Home Office

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by lukaszraczylo** [comment]
@AntonyBishop Could you put me in touch ( let's do it on Slack ) with someone who issued the request?

**Comment by lukaszraczylo** [comment]
RAW dump is 10G, compressing it.

**Comment by lukaszraczylo** [comment]
HO staff provided with encrypted & packed ( 2.2G ) dump of the db.
