### ISSUE TITLE
RDS Module: Major Version upgrades parameter group failure to create

### ISSUE THREAD

**Issue by jackstockley89** [ministryofjustice/cloud-platform#6304]
## Background

During the major upgrade, the parameter group tries to recreate if the name already exists. This will fail during the terraform apply stage. 

## Approach

This is due to the prepare for major version flag not being set. We need to check our documentation to make sure this step is clear to our users before upgrading  

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
We have instructions in the user-guide:
![Image](https://github.com/user-attachments/assets/c62f6be4-84fa-4456-a4db-7216602e450b)

Do we need to make it more clear?
