### ISSUE TITLE
Add new git-crypt collaborator to pflr-cait-deploy

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#631]
## Service name

https://github.com/ministryofjustice/pflr-cait-deploy

## Problem description

I need to be added as a git-crypt collaborator in this old template deploy repo.
GPG key is public in the keyserver for my digital justice address.

Thank you.

## Contact person

Jesus @ slack

**Comment by lukaszraczylo** [comment]
That's done.
