### ISSUE TITLE
Create alert when low/no IP prefixes available to live cluster

### ISSUE THREAD

**Issue by kyphutruong** [ministryofjustice/cloud-platform#6311]
## Background

We now have vpc-cni/ipamd logs going to [opensearch](https://app-logs.cloud-platform.service.justice.gov.uk/_dashboards/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!f,sort:!()),metadata:(indexPattern:'6d5c66d0-8d35-11ef-a6ba-a7191f5fb1c2',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_q=(filters:!(),query:(language:kuery,query:'')))

Set up alerts for when a node has CNI errors for prefix allocation and/or low/no IP prefixes available to live cluster

## Proposed user journey

Alerts going to low-priority channel when low/no IP prefixes available to live cluster

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by tom-j-smith** [comment]
[OpenSearch monitor](https://app-logs.cloud-platform.service.justice.gov.uk/_dashboards/app/alerting#/monitors/8-U4bpMBsjVF4H6CxEbg?alertState=ALL&from=0&monitorIds=8-U4bpMBsjVF4H6CxEbg&monitorType=query_level_monitor&search=&severityLevel=ALL&size=20&sortDirection=desc&sortField=start_time) has been created for `InsufficientCidrBlocks`. Currently configured to send alert messages into high-priority-alarms but should be sent to pagerduty instead to notify on call.

[New service created on PagerDuty](https://moj-digital-tools.pagerduty.com/service-directory/PG9BY5U/integrations) for OpenSearch high-priority alerts. Changes are being made to allow the [cloud-platform-terraform-opensearch-alert](https://github.com/ministryofjustice/cloud-platform-terraform-opensearch-alert) module to enable it to use custom webhooks, not just slack webhooks.


Issue [#6550](https://github.com/ministryofjustice/cloud-platform/issues/6550) needs to be completed before the low prefixes alert can be created on prometheus as the available prefixes metric is required.

**Comment by tom-j-smith** [comment]
Closing issue as remaining work is no longer in the scope of this issue. Additional issues have been created and are in the backlog.

#6571 - Low IP Prefixes alert (depends on #6550 being completed first)
#6572 - Making a way for OpenSearch to be able to send high priority alerts to PagerDuty
#6573 - Update alert created in this issue to use high priority channel to send alerts to PagerDuty (depends on #6572 being completed first)
