### ISSUE TITLE
Parliamentary Questions - Ruby upgrade won't deploy on Staging.

### ISSUE THREAD

**Issue by njpreddy** [ministryofjustice/cloud-platform#635]
## Service name

Parliamentary Questions

## Service environment

- [ ] Dev / Development
- [X] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Further develoment of application blocked and potential security issues. 

## Problem description

The ruby version PQ uses needs to be upgraded from 2.3.1 to 2.4.5.

Deployment to staging fails with the following error:

"You must use Bundler 2 or greater with this lockfile.
The command '/bin/sh -c cd /usr/src/app  &&     bundle config --global without build &&     bundle  install -j 5 &&     install -m 755 docker-ng/rails/run-pq.sh /run.sh &&     install -m 755 docker-ng/rails/entrypoint.sh /entrypoint.sh &&     echo 'export PATH=${APP_HOME}/bin:$PATH' >> /etc/bash.bashrc' returned a non-zero code: 20
Build step 'Execute shell' marked build as failure"

## Contact person

@nick.preddy

**Comment by lukaszraczylo** [comment]
It is a pure application issue. I have switched into your branch 'ruby-version-upgrade' and tried building the docker container and can confirm - error popped out immediately. 
From my experience with RoR - remove Gemfile.lock, install latest / desired ruby version on your local machine, run 'gem install bundler', then 'bundle install' and everything goes back to normal. I have confirmed it by doing so on my local machine ( and successful image build ).

**Comment by njpreddy** [comment]
Thanks for that Lukasz, I did as you said and fixed a few test problems and now the branch passes on Travis.

The problem is it won't build in Jenkins.  I just get the same error:

    You must use Bundler 2 or greater with this lockfile.
    The command '/bin/sh -c cd /usr/src/app  &&     bundle config --global without build &&     bundle  install -j 5 &&     install -m 755 docker-ng/rails/run-pq.sh /run.sh &&     install -m 755 docker-ng/rails/entrypoint.sh /entrypoint.sh &&     echo 'export PATH=${APP_HOME}/bin:$PATH' >> /etc/bash.bashrc' returned a non-zero code: 20
    Build step 'Execute shell' marked build as failure
    Performing Post build task...
    Could not match :.*docker run.*  : False
    Logical operation result is FALSE
    Skipping script  : echo "Cleaning up after build"
    docker rm -f "$JOB_NAME-$BUILD_NUMBER-db" > /dev/null 2>&1
    docker rm -f "$JOB_NAME-$BUILD_NUMBER-app" > /dev/null  2>&1
    END OF POST BUILD TASK  : 0
    [INFO] HipChat notification sent to the following rooms: PQ (Parliamentary Questions)
    Finished: FAILURE

This is odd as the lockfile states: 'BUNDLED WITH 2.0.1'

Any ideas?
