### ISSUE TITLE
Feature request: Setting CORS rules of S3 resource

### ISSUE THREAD

**Issue by Kalagan** [ministryofjustice/cloud-platform#636]
## Service name

`laa-apply-for-legalaid`
https://github.com/ministryofjustice/laa-apply-for-legal-aid

## Service environment

- [ ] Dev / Development
- [X] Staging
- [X] Prod / Production
- [X] UAT

## Impact on the service

It's not a blocker and not critical but would be very nice to have. It would make file uploads faster and reduce the load on our web server.

## Problem description

Our service let users upload documents which we store in S3.
At the moment the file is first uploaded to the web server and then pushed to S3.
We would like to have the file uploaded directly from the user's computer to S3.
However, S3's default CORS does not allow that.
We would like to be able to modify S3 CORS rules.

## Contact person

julien.sansot@digital.justice.gov.uk
slack: Julien Sansot

**Comment by vijay-veeranki-moj** [comment]
Hi Julien,

Thanks for raising the ticket, it needs some work and as you stated it is not a blocker will discuss this in the planning for the coming sprint.

**Comment by kcbotsh** [comment]
@digitalronin to chat to team to clarify before work begins

**Comment by digitalronin** [comment]
I had a chat with Julien, and confirmed that this change would create a new security vulnerability (currently, uploaded files are scanned for malware before they are accepted - this change would break that step).

This change should be put on hold until we can put in place some process to automatically scan uploaded files (e.g. using a lambda function triggered by the file appearing).

**Comment by AntonyBishop** [comment]
@Kalagan Is there still a need for this?

**Comment by Kalagan** [comment]
@AntonyBishop, no we don't need it at the moment.

**Comment by AntonyBishop** [comment]
Thanks @Kalagan . Can we close it and reopen an issue when it is needed?

**Comment by Kalagan** [comment]
@AntonyBishop yes that's fine 🙂
