### ISSUE TITLE
Investigation: Cert-manager issuing failures

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#6367]
## Background

On several occasions recently certificate issuing has been failing to complete,  cert-manager pod has required a restart to resolve.

We need to have a closer look at cert-manager and determine what the issue is, and fix.

**Comment by jackstockley89** [comment]
- If we need to enable Debug on the log to investigate, there is no point waiting for it to fail before enabling it, as we will then have to wait again for it to fail. 

- when enabling Debug, we must think about the impact on OpenSearch storage, as we have had problems in the past with it filling. There shouldn't be an impact as this was due to log incorrect dating but we should still have this in the back of our minds as this doesn't just affect us it also affects users

**Comment by sj-williams** [comment]
Best practice replica notes for cert-manager:

https://cert-manager.io/docs/installation/best-practice/#high-availability

**Comment by sj-williams** [comment]
Have had to bounce certmanager pods since this applied. Details:

`2/12/24 @ 12:18`

Team reports cert for https://hmppsinsights.service.justice.gov.uk/ is not in state `Ready: False`.

Logs of interest (recent first)

```
1 conditions.go:203] Setting lastTransitionTime for Certificate "hmppsinsights.service.justice.gov.uk" condition "Ready" to 2024-12-02 13:29:32.491576426 +0000 UTC m=+240.744019392
```

```
I1202 13:28:21.644715       1 util.go:83] "cert-manager/controller/certificaterequests-issuer-acme/handleOwnedResource: owning resource not found in cache" resource_name="hmppsinsights.service.justice.gov.uk-1-2080190060" resource_namespace="hale-platform-prod" resource_kind="Order" resource_version="v1" related_resource_namespace="hale-platform-prod" related_resource_name="hmppsinsights.service.justice.gov.uk-1" related_resource_kind="CertificateRequest"
```


```
E1202 13:28:21.644772       1 controller.go:165] "cert-manager/orders: order in work queue no longer exists" err="order.acme.cert-manager.io \"hmppsinsights.service.justice.gov.uk-1-2080190060\" not found"
```


-- Cert deleted & pods bounced ---


```
I1202 13:27:26.135603       1 controller.go:162] "cert-manager/challenges: re-queuing item due to optimistic locking on resource" key="hale-platform-prod/hmppsinsights.service.justice.gov.uk-1-2080190060-2941551458" error="when updating the status: Operation cannot be fulfilled on challenges.acme.cert-manager.io \"hmppsinsights.service.justice.gov.uk-1-2080190060-2941551458\": the object has been modified; please apply your changes to the latest version and try again"
```

```
E1202 13:25:19.477637       1 sync.go:190] "cert-manager/challenges: propagation check failed" err="DNS record for \"hmppsinsights.service.justice.gov.uk\" not yet propagated" resource_name="hmppsinsights.service.justice.gov.uk-1-2080190060-2941551458" resource_namespace="hale-platform-prod" resource_kind="Challenge" resource_version="v1" dnsName="hmppsinsights.service.justice.gov.uk" type="DNS-01"
```
