### ISSUE TITLE
Justice UK: Request *change of severity-level* for alert route in Alertmanager

### ISSUE THREAD

**Issue by EarthlingDavey** [ministryofjustice/cloud-platform#6378]
## Service name

justice-gov-uk

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [x] Other (Demo)

## Problem description

Hi team 👋 Thanks @sj-williams  for setting up the alert rules last week, for this ticket https://github.com/ministryofjustice/cloud-platform/issues/6305

Since it's been set up, we have a minor issue in that our channel has received alerts from various other teams/services.

It must be because the severity level of `justice-gov-uk-alerts` is quite generic, and it's been used by other teams - possibly as a placeholder.

Would it be possible for you to remove the level `justice-gov-uk-alerts` from our Slack webhook?

And, create 4 new alert routes, (that have not been used by another team):

e.g.

- justice-gov-uk-dev-alerts
- justice-gov-uk-demo-alerts
- justice-gov-uk-staging-alerts
- justice-gov-uk-production-alerts

Edit: For context, our channel has 8 alerts in the last 24 hours, all from other teams/services. 

Many thanks

## Contact person

Davey Brown Slack: `@Davey`

**Comment by tom-j-smith** [comment]
Hi Davey, Ive split `justice-gov-uk-alerts` into 4 different ones.

The 4 new severities are:
`justice-gov-uk-dev-alerts`
`justice-gov-uk-demo-alerts`
`justice-gov-uk-staging-alerts`
`justice-gov-uk-production-alerts`

**Comment by EarthlingDavey** [comment]
Awesome - thank you @tom-j-smith !
