### ISSUE TITLE
Update ECR repositories with lifecycle policies

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#638]
## Background

In response to #602 we've added a default lifecycle policy for the ECR repositories.

## Proposed user journey

As a user, I want the lifecycle policy to apply by default to my repository.

## Approach

- Update the module invocations to use the latest version of the module which includes the lifecycle policy.
- Let the pipelines run!

## Which part of the user docs does this impact

Potentially the ECR module docs?

## Questions / Assumptions

N/A

## Definition of done

- [ ] changes have been made in `cloud-platform-environments`
- [ ] all our ECR repos have the default lifecycle policy attached to them
- [ ] Update user docs to make policy clear.

## Reference

N/A

**Comment by vijay-veeranki-moj** [comment]
for the the namespaces using ecr, completed updating the source to "github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials?ref=2.1"  which applied the default lifecycle policy.

updated the use-guide
