### ISSUE TITLE
Unable to connect to IMS Postgres DB via port forwarding.

### ISSUE THREAD

**Issue by Stubbs** [ministryofjustice/cloud-platform#6384]
## Mercury/IMS

Generated from conversation on Slack: https://mojdt.slack.com/archives/C57UPMZLY/p1730291843251409

I'm having an issue with port forwarding from a pod to my local box. It's so I can access Postgres using dbeaver, I set it up and it's working fine to one server, but another I get this error when I try and actually connect to the db over the forward:

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X] Other

## Impact on the service

handover from managed service who are coming to the end of their contract. This is related to a knowledge transfer of the essential data migration work from Mercury to IMS. We are unable to complete the handover until this KT session is complete.

## Problem description

```
~ ᐅ kubectl -n $k8sNameSpc port-forward port-forward-pod-db-noel $LOCAL_PORT:5432
Found existing alias for "kubectl". You should use: "k"
Forwarding from 127.0.0.1:5434 -> 5432
Forwarding from [::1]:5434 -> 5432
Handling connection for 5434
E1030 11:36:04.225029    4636 portforward.go:413] an error occurred forwarding 5434 -> 5432: error forwarding port 5432 to pod 80ffa02db356ddd10a8c2a2ed7d65edaa0f2ff6ff26ca744b827d8ea0d9bf47f, uid : failed to execute portforward in network namespace "/var/run/netns/cni-69865ef7-7565-05b3-94f3-b4e5bbd2b814": failed to connect to localhost:5432 inside namespace "80ffa02db356ddd10a8c2a2ed7d65edaa0f2ff6ff26ca744b827d8ea0d9bf47f", IPv4: dial tcp4 127.0.0.1:5432: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
error: lost connection to pod
```
I've tried re-doing the pf pod a couple of times but I still get the error.

## Contact person

Stuart Grimshaw
Slack: @stuart
Email: stuart.grimshaw@digital.justice.gov.uk

**Comment by sj-williams** [comment]
Port forwarding is now working
