### ISSUE TITLE
Add Pingdom integration for laa-crown-court-litigator-fees-production

### ISSUE THREAD

**Issue by mpw5** [ministryofjustice/cloud-platform#6393]
## Service name

Crown Court Litigator Fees (CCLF)

## Service environment

Production

## Impact on the service

Enable slack notifications for Pingdom alerts to allow us to monitor our service.

## Problem description

Please could you generate a Pingdom integration id to allow us to display availability alerts in the appropriate channel.

Team name: Crime Higher Billing
Application name: crown–court-litigator-fees
The target slack channel: #laa-alerts-cclf-prod

## Contact person

Name: Mark Whitaker
Slack handle: mark.whitaker
Email address: [mark.whitaker@digital.justice.gov.uk](mailto:mark.whitaker@digital.justice.gov.uk)

**Comment by tmahmood72** [comment]
Pingdom integration ID setup for application crown–court-litigator-fees:
140132
