### ISSUE TITLE
New alert receivers for hmpps-sre team

### ISSUE THREAD

**Issue by andrewrlee** [ministryofjustice/cloud-platform#6396]
## Service name

This will be used by a few services that the SRE team manage

## Service environment

- [x] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We need to set up proper alerting as currently they get funneled to a shared channel which we aren't observing.
We already have a slack webhook

## Problem description

We need two alert receivers set up to direct alerts to slack channels:

**Prod:** 
severity: `hmpps-sre-alerts-prod`
slack channel: `#hmpps-sre-alerts`

**Non prod:**
severity: `hmpps-sre-alerts-nonprod` 
slack channel: `#hmpps-sre-alerts-nonprod`

## Contact person
Me or `#ask-prisons-digital-sre`

Thanks!

**Comment by tmahmood72** [comment]
@andrewrlee the new alerts have been setup as requested
