### ISSUE TITLE
Uploading file up to 50MB

### ISSUE THREAD

**Issue by Kalagan** [ministryofjustice/cloud-platform#640]
## Service name

`laa-apply-for-legalaid`
https://github.com/ministryofjustice/laa-apply-for-legal-aid

## Service environment

- [ ] Dev / Development
- [X] Staging
- [X] Prod / Production
- [X] UAT

## Impact on the service

Our service should allow users to upload files up to 50MB. This doesn't work.

## Problem description

Our service let users upload files. However, it fails when the file is more than a certain size. For example, 15MB is fine but 19MB always fails with *This site can’t be reached. ERR_CONNECTION_RESET*.
Our web server (ruby on rails) doesn’t show any error. 

## Contact person

slack: Julien Sansot

**Comment by vijay-veeranki-moj** [comment]
updated proxy-body-size: "50m" in "nginx-ingress"

Will get effected when it get merged.

**Comment by Kalagan** [comment]
Would it be possible to increase it higher than that?
We will reject files bigger than 50MB but we would like to show them a proper error message.
How big can we go? Would 100MB be ok?

**Comment by vijay-veeranki-moj** [comment]
Hi Julien, 
Changing the configuration for this will effect globally for all Ingress rules, by default we give you 50m.

If you want more, use an annotation and can configure it yourself _for your services.

https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size

**Comment by Kalagan** [comment]
Ok, thanks Vijay 🙂

**Comment by vijay-veeranki-moj** [comment]
Hi Julien, applied the change can you please give a try now and let me know

**Comment by Kalagan** [comment]
It works. Thanks :+1:
