### ISSUE TITLE
Update Elasticsearch "write blocks" alarm

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#641]
## Background

We currently alert on writes being blocked to Elasticseach but it is set as a low priority alert. As a follow up to the incident we had with our cluster, we want to change it to a high priority alert. This alarm indicates that elasticsearch is not ingesting records and should be acted on.

## Proposed user journey

N/A
## Approach
N/A

## Which part of the user docs does this impact
N/A

## Questions / Assumptions
N/A

## Definition of done

- [ ] as described above

## Reference
N/A

**Comment by AntonyBishop** [comment]
No longer required.
