### ISSUE TITLE
Cannot connect to prod and staging S3 bucket

### ISSUE THREAD

**Issue by Kalagan** [ministryofjustice/cloud-platform#643]
## Service name

`laa-apply-for-legalaid`
https://github.com/ministryofjustice/laa-apply-for-legal-aid

## Service environment

- [ ] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] UAT

## Impact on the service

File upload not working

## Problem description

We have 3 S3 resources via this Pull request: https://github.com/ministryofjustice/cloud-platform-environments/pull/398
one for each of our environments (UAT, Staging, Production).
The UAT one works well. Our app can connect and I can also connect via Cyberduck on my computer.
However, we can't connect to the staging and production ones.
We get the error "The AWS Access Key Id you provided does not exist in our records."

## Contact person

slack: Julien Sansot

**Comment by vijay-veeranki-moj** [comment]
staging: 
kubectl get secrets apply-for-legal-aid-s3-instance-output -n laa-apply-for-legalaid-staging -o json | jq -r '.data[] | @base64d'

production: 
kubectl get secrets apply-for-legal-aid-s3-instance-output -n laa-apply-for-legalaid-production -o json | jq -r '.data[] | @base64d'

uat:
kubectl get secrets apply-for-legal-aid-s3-instance-output -n laa-apply-for-legalaid-uat -o json | jq -r '.data[] | @base64d'


Please use the above to get the aws_access_key_id and aws_secret_access_key for the s3 buckets you created for staging/production/uat.

You will need to set the environment variable AWS_PROFILE=YourS3AWSProfile if values are copied to ~/.aws/credentials or set the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.

**Comment by Kalagan** [comment]
Hi Vijay, that's what I did but only the UAT ones work

**Comment by vijay-veeranki-moj** [comment]
Thanks for your reply, we are in meeting, will look in to it this afternoon.

**Comment by vijay-veeranki-moj** [comment]
Hi Julien,

Fixed the issue, where aws IAM policy for this s3 bucket user is set to a non-access group by mistake, set the user to active , now you should access these buckets.

Please test it and update the ticket.

**Comment by Kalagan** [comment]
I tested and it works now. Thank you
