### ISSUE TITLE
Downsize 4x Prison Visits RDS instances (Pre&Prod)

### ISSUE THREAD

**Issue by KristianGregor** [ministryofjustice/cloud-platform#6432]
## Service name

Visit Someone In Prison

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

4x RDS instances for Visits someone in Prison service were over-allocated storage and should be downsized to free up unnecessary storage allocation and return it to the account for other teams usage. The resolution is expected to involve downtime and replacing the RDS instances with new instances and a data migration, and one of the instances is a very mature, large production instance, so the operation is high risk.

## Problem description
We've detailed out the background to the issue and our plan for executing the downsizing here (work in progress). Please contact Kristian Gregory to request access if its not immediately available
https://dsdmoj.atlassian.net/wiki/spaces/PSCH/pages/5269618719/Database+downsizing

We have an problem that needs dealing with fairly urgently and will involve some significant risk and possibly some weekend work. Back in February of this year [a change was made](https://github.com/ministryofjustice/cloud-platform-environments/pull/21268) to the production Visit Scheduler RDS instance that set db_allocated_storage to 16,000GiB. This setting must have been misunderstood as this is a huge amount of storage way beyond the needs of the database, and that setting physically allocates that storage and reserves it for the usage of that database, which takes a big amount of storage allowance out of the MoJ account. This seems to have gone unnoticed for a long time.

However, Thursday 7th November, in an attempt to bring the preprod databases in line with production, the scheduler and PVB PreProd instances had the same settings as prod applied. This meant there is now  even more RDS instances consuming vast amounts of the storage allowance and this has now maxed out the account. The kicker is, this setting can be set, it can be increased, but it cannot be decreased. The space can only be freed up by creating new RDS instances, migrating the data across and destroying the original RDS instance. Doing this on production instances is clearly going to be a high risk exercise requiring much caution.

Service | Environment | DB Name | Date of mem allocation | Allocated size | Instance class | Actual size (Approx) | Proposed allocation minimum
-- | -- | -- | -- | -- | -- | -- | --
Visit Scheduler | Prod | cloud-platform-c6e5432ed45afd19 | 2024-02-27 | 16TB | db.t4g.small |   |  
Visit Scheduler | PreProd | cloud-platform-04ac12afe74f79b5 | 2024-11-07 | 16TB | db.t4g.small |   |  
Visit booker registry | Prod | cloud-platform-7520cc9334a6f330 | 2024-07-23 | 16TB | db.t4g.small |   |  
Visit booker registry | PreProd | cloud-platform-dda6d077d1df7076 | 2024-11-07 | 16TB | db.t4g.small |   |  

## Contact person
Kristian Gregory HMPPS Digital TA for Visits kristian.gregory@digital.justice.gov.uk & on slack

**Comment by sj-williams** [comment]
preprod visits scheduler recreated:
https://github.com/ministryofjustice/cloud-platform-environments/pull/27940

**Comment by sj-williams** [comment]
All 16TB instances have now been resized, freed up 64tb of account-wide rds storage.
