### ISSUE TITLE
Add GPG public key to repos

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#646]
## Service name

CLA Backend
CLA Frontend
LAALAA
FALA

## Service environment

- [ x] Dev / Development
- [ x] Staging
- [ x] Prod / Production
- [] Other

## Impact on the service

Add gpg pkey to the following template-deploy repos please (confirm key on slack):
https://github.com/ministryofjustice/fala-deploy
https://github.com/ministryofjustice/cla_backend-deploy
https://github.com/ministryofjustice/cla_frontend-deploy
https://github.com/ministryofjustice/laalaa-deploy

## Contact person
Name: Said Shire
Slack:[at]Said

**Comment by pwyborn** [comment]
Done - confirmed by Said

**Comment by pwyborn** [comment]
Didn't mean to archive this
