### ISSUE TITLE
PQ Staging DB import not running.

### ISSUE THREAD

**Issue by njpreddy** [ministryofjustice/cloud-platform#647]
## Service name

Parliamentary Questions

## Service environment

- [ ] Dev / Development
- [X] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Cannot test Ruby upgrade on staging properly.  Without the upgrade gem security issues will persist.

## Problem description

Live to staging database import job does not seem to be running.

## Contact person

@nick.preddy

**Comment by njpreddy** [comment]
Could I get an idea of when this issue might be fixed please?

**Comment by lukaszraczylo** [comment]
1. RUN AS ROOT: ```/usr/local/bin/load_restore_from_prod.sh ( this one succeeded )```
2. RUN AS ROOT: ```docker exec pq bash -c 'RAILS_ENV=production bundle exec rake db:staging:sync'``` ( this one I have no idea if it succeeded as your application does not produce any logs for this rake task )

I've done it for you but please keep in mind that data sync between production and staging environments isn't done in the most efficient way and this process can and should be improved before migrating your project into new cloud platform.
