### ISSUE TITLE
Write an architecture document for the cloud platform team

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#65]
## Background

Part of #62 

We want some documentation for the cloud platform team on the pipeline for creating AWS resources.  This should give an overview of the bits involved in the pipeline, the user flow and how they connect together.

## Done when

- [x] There is a document in the `cloud-platform` repo under the `docs` directory that explains how the AWS resource creation process works
- [x] There is a diagram in that document that shows the user flow for the process and which components are involved
- [x] The document is reviewed by @mitch or @kerin

**Comment by ollieanwyll** [comment]
Picked this up and made a branch for the doc.
Let me know if anyone thinks of some crucial things to include.

**Comment by ollieanwyll** [comment]
https://github.com/ministryofjustice/cloud-platform/pull/107
@kerin @alkar @kalbir
