### ISSUE TITLE
Splitting Traffic for Prison Visits Booking (PVB) Migration

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#650]
## Background

PVB are working on their migration from Template Deploy to the Cloud Platform. As part of their migration they want to split traffic between existing and new service. 

To assist the migration activities the Cloud Platform need to set up HAProxy to split traffic similar to the migration of (CLA Public)

## Proposed user journey

Users are able to define how much traffic they wish to split across legacy and new platform. 

Cloud Platform set up HAProxy to meet user needs.

## Approach

As per documented process for setting up HAProxy.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- Need to confirm when this needs to be ready (within the next two weeks)
- Need to confirm percentage traffic to be split (recommended start 5% to 10%)

## Definition of done

- [ ] Able to split traffic using HAProxy

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Toby has confirmed via slack that this is no longer required and will be re-visited when time has been allotted to the migration. 

```
TobyRetallick [3 minutes ago]
@jasonb @antony.bishop - just been speaking to @Edwin Bajomo (the Prison Visits product manager) and we are going to hold fire on traffic splitting on Prison Visits Staging as we don't think it will add any value right now. We will definitely split traffic on production once the migration in this environment is complete. As yet we are not sure when production will be migrated to the new Cloud Platform as the devs (myself included) are having to prioritise the launch of another project. Myself or Edwin will keep you posted on next steps
```
