### ISSUE TITLE
Add custom alarms to Prometheus Operator install

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#654]
## Background

We require a number of custom alerts added to our `prometheusRule` resource. We had this previously under another version but somewhere along the line this got lost. 

##Approach

Take the alarms from here: https://github.com/ministryofjustice/cloud-platform-prometheus/blob/master/custom-alerts/custom-alerts.yaml and add a process of execution to our current Prometheus installation in Terraform (https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/terraform/cloud-platform-components/prometheus.tf).

## Which part of the user docs does this impact

README only. 

## Questions / Assumptions

Custom alarms are picked up by executing a `kubectl apply -n monitoring -f <customAlarms1>

## Definition of done

When the custom alarms are managed in `/terraform/cloud-platform-components`

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
completed the task and raised a PR, will merge it when custom alerts are fixed so we can apply this with proper alerts
