### ISSUE TITLE
Git access to https://github.com/ministryofjustice/cloud-platform-environments

### ISSUE THREAD

**Issue by andymarke** [ministryofjustice/cloud-platform#655]
## Service name

court-probation

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Unable to push to https://github.com/ministryofjustice/cloud-platform-environments

## Problem description

I am following the setup instructions in https://ministryofjustice.github.io/cloud-platform-user-docs/01-getting-started/002-env-create/#create-your-namespace-and-namespace-resources but I unable to push my branch to git.

GitHub user is `andymarke` and I am in the https://github.com/ministryofjustice organisation but I get a push error trying to push my branch

```ERROR: Permission to ministryofjustice/cloud-platform-environments.git denied to andymarke.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Do I need to be in some additional group? Would this affect everyone in my team?

## Contact person

Slack: Andy Marke
Email: andy.marke@digital.justice.gov.uk

**Comment by vijay-veeranki-moj** [comment]
Added digital-studio-sheffield as collaborator and gave write permission to get access.
