### ISSUE TITLE
Troubleshooting slow app performance

### ISSUE THREAD

**Issue by tomd-moj** [ministryofjustice/cloud-platform#6554]
## Service name

gpc-anomalies (webapp)

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Service users aren't able to work at their normal rate. They may decide not to use the service until we can improve it's performance.

## Problem description

The prod version of the app is much slower than the last time we were using it (maybe 1 month ago). 

The app is used to query (and write to) Athena tables. We have recently added more data to the Athena tables, but not a large volume of data. The performance of the dev version of the app has not degraded similarly, although the dev Athena tables contain less data.

We're trying to troubleshoot the performance issues - any suggestions we could try on the platform side of things would be much appreciated. We can't see any errors in the logs, although there is quite a lot of activity.

## Contact person

Tom Dykins, thomas.dykins@justice.gov.uk

**Comment by timckt** [comment]
The resource metrics and the application log does not indicate that the pods themselves are bottlenecked at CPU or memory. 
The application’s CPU and memory usage are well below the requested and allocated resources. The webapp container image is using about 60–65m of CPU (limit is 1) and around 2.5Gi of memory (limit is 12Gi). This indicates that the CPU and memory capacity are not being strained and are unlikely to be the source of the performance issues.
https://grafana.live.cloud-platform.service.justice.gov.uk/d/a87fb0d919ec0ea5f6543124e16c42a5/kubernetes-compute-resources-namespace-workloads?from=now-2d&to=now&timezone=utc&var-datasource=prometheus&var-cluster=&var-namespace=data-platform-app-gpc-anomalies-prod&var-type=$__all&refresh=10s

There are not too many resource in the namespace, mainly the application pod, and ecr.
https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live.cloud-platform.service.justice.gov.uk/data-platform-app-gpc-anomalies-prod/resources

As the application also involve Athena in AP account, have suggested user to look into if there is any Athena performance issue at the same time, potentially Athena query performance or concurrency issues.

**Comment by timckt** [comment]
The resource metrics and the application log does not indicate that the pods themselves are bottlenecked at CPU or memory. Helped restart the pod on 18/Dec morning but no much improvement observed for slow app. 
The problem probably wont be in the application pod and in Cloud Platform and user agreed to close the ticket for now.

The difference between between dev and prod Athena would probably be one of the key reasons for slow app. User was also suggested to clear out some of the snapshots from their iceberg table.
