### ISSUE TITLE
New alert route in Alertmanager

### ISSUE THREAD

**Issue by vertism** [ministryofjustice/cloud-platform#6559]
namespace name: request-personal-information-production
team name: Central Digital Product Team
application name: Request Personal Information
slack channel: #cdpt-request-personal-information
kubernetes secret name where the webhook url is stored: slackwebhook
severity level (warning/information): warning

## Service name

Request Personal Information

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Contact person

`@Andrew Pepler`
andrew.pepler@digital.justice.gov.uk

**Comment by timckt** [comment]
User confirmed that alert manager is working as expected.
