### ISSUE TITLE
Add AlertManager integration for Prison Roll Count

### ISSUE THREAD

**Issue by ashleygyngell** [ministryofjustice/cloud-platform#6563]
## Service name

Establishment Roll

## Service environment

- [✅] Dev / Development
- [ ] Staging
- [✅] Prod / Production
- [✅] Preprod

## Impact on the service

Enable slack notification for Prometheus alerts to allow us to monitor our service

## Problem description

Namespace name - hmpps-prison-roll-count-dev, hmpps-prison-roll-count-preprod, hmpps-prison-roll-count-prod
Team name - Move a Prisoner
Application name - Establishment Roll
Slack channel - #move-a-prisoner-alerts
Kubernetes secret name where the webhook url is stored - slack-webhook
Severity level - warning

## Contact person

Name: Ash Gyngell
Slack handle: Ash Gyngell
Email address: [ashley.gyngell@digital.justice.gov.uk](mailto:ashley.gyngell@digital.justice.gov.uk)

**Comment by tom-j-smith** [comment]
3 new severities created:
`hmpps-establishment-roll-dev`
`hmpps-establishment-roll-preprod`
`hmpps-establishment-roll-prod`
