### ISSUE TITLE
Change Slack channel for alert severity `hmpps-prison-person-api-prod`

### ISSUE THREAD

**Issue by brightonsbox** [ministryofjustice/cloud-platform#6577]
## Service name
hmpps-prison-person-api

## Service environment
Prod / Production

## Impact on the service
We are getting production alerts sent to the wrong channel, making it more difficult to spot issues.

## Contact person
[Jon Brighton](https://moj.enterprise.slack.com/archives/DNHAD50J2)

Hi, please could alert severity `hmpps-prison-person-api-prod` be set up to send alerts to the [#connect-dps-prod-alerts](https://moj.enterprise.slack.com/archives/C05UPLNGQDD) channel (instead of `-non-prod-alerts`)

**Comment by tom-j-smith** [comment]
The severity `hmpps-prison-person-api-prod` has been updated to now send notifications to `#connect-dps-prod-alerts`
