### ISSUE TITLE
Moving environments Terraform state to new state structure

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#659]
## Background

We have the following terraform states we manage:
- [x] `cloud-platform-account`
- [x] `global-resources`
- [x] `cloud-platform`
- [x] `cloud-platform-components`
- [ ] `cloud-platform-environments`

The only missing bit is the last item, which still lives in its old bucket.

## Proposed user journey

N/A

## Approach

1. Pause any pipelines that deal with resources from `cloud-platform-environments` (as well as the `bootstrap` pipeline!).

2. Move the files to the new bucket, under the `cloud-platform-environments` prefix. See the s3 backend definitions in the other terraform directories for how to configure it (be careful of leading and trailing slashes, terraform is picky about these things!)

3. Update any references. Specifically, the scripts under `bin/` in the `cloud-platform-environments` will have the bucket name hardcoded.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] The references in the `apply`/`plan` scripts and anywhere else have been updated to point to the new bucket (mind the prefixes there!)
- [ ] The actual state files have been moved.
- [ ] The pipelines are running again and there's no issues.
- [ ] The old bucket is removed.

## Reference
@jasonBirchall :D

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
Copied the buckets from account mojds-platforms-integration/moj-cp-k8s-investigation-environments-terraform to account  cloud-platform-aws under cloud-platform-environments but as the concourse configuration change accessing the new bucket in different account(cross-account access to objects that are in Amazon S3 buckets) is considerably lot of work, so holding this task.

Removed the buckets copied in cloud-platform-aws under cloud-platform-environments to avoid confusion.

**Comment by vijay-veeranki-moj** [comment]
live1 is now  created in  https://s3-eu-west-1.amazonaws.com/cloud-platform-terraform-state/cloud-platform-environment/live-1.cloud-platform.service.justice.gov.uk
