### ISSUE TITLE
Run Terraform in Docker

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#660]
## Background

We want to be able to run `terraform` for the estate we manage in a common, reproducible way, avoiding any issues due to tooling version mismatch.

## Proposed user journey

Instead of invoking `terraform` directly, we could run it inside a docker container, with an image that has specific versions of the tools and automatically passes any common flags etc.

## Approach

Turns out, [we have a image](https://github.com/ministryofjustice/cloud-platform-tools-image) that's probably fit for purpose! 

Write a script that runs terraform in a docker container (mounts the appropriate directories in the right places, performs any initialisation needed etc).

Example:
If I'm updating `cloud-platform-components`, I should be able to invoke that script from `<some-path>/cloud-platform-infrastructure/terraform/cloud-platform-components` and it behaves in the same way invoking `terraform` directly would.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] I can run `terraform` in any of our terraform directories by invoking our wrapper script
- [ ] The script is version controlled in `cloud-platform-infrastructure`
- [ ] The script behaves like plain `terraform`
## Reference
N/A
[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mtrblmoj** [comment]
The solution is not versioned  in cloud-platform-infrastructure, but in cloud-platform-infrastructure-image.

Notes:
- Not to alter the current platform-tool-image, I created another  docker image. 
- This solutions allows any terraform sitting in cloud-platform-infrastructure and environment to be applied, but the script needs to be ran at the root of the repos, to mount all the relevant pieces. 
- Fully tested
