### ISSUE TITLE
Create a migration document/checklist

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#662]
## Background

To help users understand how to migrate from Live 0 to Live 1 they will need come guidance. We need to create some guidance that makes it easier for users to migrate.

## Proposed user journey

A users wishes to migrate from Live 0 to Live 1. They can access some guidance or a checklist that will help then plan their migration.

## Approach

We'll need to do some thinking about what this guide will include. We don't fully understand what is required so we'll probably need to trial stuff and then document an approach.

## Which part of the user docs does this impact

Requires new guidance. 

## Definition of done

- [ ] Guidance created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ollieanwyll** [comment]
BLOCKED

This checklist realistically cannot be written until `live-1` is ready for migrations to be simulated on.
