### ISSUE TITLE
Update User Guide and other documentation

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#663]
## Background

As part of building Live 1 there will be a lot of documentation to update. That should be carried out as part of individual stories where possible. However, we'll need a once over of everything to check for consistence. That includes readme docs too.

## Proposed user journey

N/A

## Approach

Review the docs. Maybe a deploy and app run through might be a good approach.

## Which part of the user docs does this impact

All of it.

## Definition of done

- [ ] Documentation reviewed
- [ ] Updates identified and made

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ollieanwyll** [comment]
This needs to be reviewed and can only be merged when Live-1 is released to our users.
