### ISSUE TITLE
Concourse for "Live 1"

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#666]
## Background

Needs to set up Concourse for Live 1.

## Proposed user journey

N/A

## Which part of the user docs does this impact

\

N/A

## Questions / Assumptions

Need to determine how we run concourse for Live 1. We will still need to run a pipeline for Live 0, do we run separate pipelines? Do we want a new Concourse. Decisions to be made.

## Definition of done

- [ ] We have an agreed approach for how we run Concourse for Live 1
- [ ] New pipeline running for Live 1

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Decision: 1 Concourse in Live 1 with 2 pipelines.

**Comment by vijay-veeranki-moj** [comment]
Deploy concourse in live-1 completed and can be accessed https://concourse.apps.live-1.cloud-platform.service.justice.gov.uk

**Comment by vijay-veeranki-moj** [comment]
Live0 build environments and Live1 build environments pipeline in https://concourse.apps.live-1.cloud-platform.service.justice.gov.uk
for live-0 cluster updated apply.sh in cloud-platform-environments and created a new one for live-1 apply-live1.sh
