### ISSUE TITLE
Create new IAM user for Concourse to create resources

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#667]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
In moj-cp created IAM user for concourse named as cloud-platform-live-1-concourse-user and assign  a policy  cloud-platform-live-1-concourse-user-policy.
