### ISSUE TITLE
Create new Live 1 Cluster in new AWS Account

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#669]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
After having a chat with Mitch, we agreed that the best method for separation is to branch live-0 off and change master to link to live-1.
