### ISSUE TITLE
AWS permissions

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#67]
## Service name

Prison Visits

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [x] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Ability to debug deploys

## Problem description

Please can you give a Yann permissions to view ec2 instances and cloudwatch on AWS.
yann.marquet@digital.justice.gov.uk / @stupidcodefactory

## Contact person

yann.marquet@digital.justice.gov.uk / @stupidcodefactory

**Comment by razvan-moj** [comment]
done, key had to be reset
