### ISSUE TITLE
Create new Auth0 tenant

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#670]
## Definition of done

- [x] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Already been done. Auth0 justice-cloud-platform tenant exists.
