### ISSUE TITLE
Create a service account

### ISSUE THREAD

**Issue by Katy600** [ministryofjustice/cloud-platform#675]
## Service environment
- [x] Staging

## Impact on the service

Our remote worker is not able to access Kubernetes, so the scope of what he is able to do is more limited. 

## Problem description

Hi, I am trying to create a service account for somebody who is currently working remotely, so is not part of the MoJ Github organisation. They therefore don't have access to any of our Kubernete's workspaces. Am I able to create a service account for them myself, or do I need to go through you?

The service account should have permissions to do everything apart from access to secrets (it should not be possible to view secrets).

## Contact person
katherine.mccann@digital.justice.gov.uk
slack Katy McCann

**Comment by kcbotsh** [comment]
DO not pick up until expressly authorised by security or Steve Marshall @kcbotsh to chase

**Comment by kcbotsh** [comment]
Hi @Katy600 .This raises compliance question our team does not authority to answer. I advise this is redirected to the security team for further guidance.
 
I will close this ticket as should this be permissible, I believe you have the needed access to carry out this task.

thanks
