### ISSUE TITLE
Fix cloud-platform-environment apply and plan script as it is using moj-cp-k8s-investigation-platform-terraform bucket

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#679]
## Background

Cloud-platform-environment apply and plan script is still using below
terraform plan \
          -var="cluster_name=${cluster%.k8s.integration.dsd.io}" \
          -var="cluster_state_bucket=moj-cp-k8s-investigation-platform-terraform"

where  -var="cluster_state_bucket=moj-cp-k8s-investigation-platform-terraform" is not needed any more
 

## Proposed user journey

N/A

## Approach

fix the apply and plan script buy removing moj-cp-k8s-investigation-platform-terraform.

test the apply and plan pipeline still running with out any issues.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

we are not using moj-cp-k8s-investigation-platform-terraform.

## Definition of done

not use moj-cp-k8s-investigation-platform-terraform any more in apply and plan pipeline

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Implemented under another ticket. Duplicate closed.

**Comment by vijay-veeranki-moj** [comment]
As discussed closing this issue, as we will be cleaning it along with live-0.
