### ISSUE TITLE
Provide Kubernetes cluster access to Prison Visits Booking staging database

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#681]
## Service name

Prison Visits Booking
## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

We are migrating Prison Visits Booking to the new Cloud Platform but wish to point to the existing db instance on staging

Please modify db `pr8eauev30aqm3` to be accessible by the cluster

## Contact person

Toby Retallick

**Comment by razvan-moj** [comment]
done, as discussed in chat
