### ISSUE TITLE
Cleanup cla-public HAProxy deployment

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#683]
## Background

TBC
(kind of) depends on #588 

## Definition of done

- [ ] haproxy setup has been destroyed
- [ ] terraform states cleaned up
- [ ] traffic for cla-public flows directly into the cluster

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by kcbotsh** [comment]
@alkar are we able to put ore detail on this one yet?

**Comment by alkar** [comment]
@kcbotsh just updated this morning with some objectives but there's not much else to add.
Pending https://github.com/ministryofjustice/cla_public/pull/824 before we can action this.

**Comment by alkar** [comment]
Blocked by https://github.com/ministryofjustice/cloud-platform/issues/737

**Comment by alkar** [comment]
This is now complete.
