### ISSUE TITLE
Support for FALA migration to the Cloud Platform

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#685]
## Background

FALA are migrating to the Cloud Platform next week. There are some supporting activities that need to take place.

## Approach

Based on notes form discussion with David Lantos:
Summary

- We (FALA Team) need to add certificate changes to Kubernetes YML ourselves (new certificate resource), pull request in FALA, review, test, with the help of @alkar.

- Then release after the above change, next working day 8 am (Tuesday): switching DNS.

- Service team monitors after release. Half a day or day standby for reverts.

- Similar change is needed for removing `cla_public`’s haproxy. (edited) 

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] FALA successfully migrated to the Cloud Platform

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by said-moj** [comment]
Hi

Can we get the switch over to be done at 8:30 AM 13 March 2019 please

**Comment by alkar** [comment]
@said-moj that sounds good, I'll be picking it up tomorrow.

**Comment by alkar** [comment]
Blocked by https://github.com/ministryofjustice/cloud-platform/issues/737

**Comment by alkar** [comment]
This is now complete.
