### ISSUE TITLE
Decommission Opsmanual and legacy Cloud Platforms Confluence Pages

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#687]
## Background

Both Opsmanual and Confluence are out of date. All our documentation is now in Github. 

They should be decommissioned/archived.

## Approach

- Determine of there is any content we need in from either of the legacy sources.
- Obtain copies of what we need and find that content a new home.
- Decommission Opsmanual and associated infrastructure
- Archive the confluence pages
- Tell users where relevant information is kept.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- Is this dependant on our Runbook related stories? see #686 

## Definition of done

- [x] Review of documentation
- [x] Identify anything that needs saving
- [x] Transfer information we need to keep
- [x] Decommission Opsmanual
- [ ] Decommission Confluence pages

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
On-call - https://github.com/ministryofjustice/cloud-platform/pull/1168

**Comment by pwyborn** [comment]
Template deploy - Runbooks
https://github.com/ministryofjustice/cloud-platform/pull/1184

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/opsmanual - archived
https://github.com/ministryofjustice/opsmanual-deploy - archived

**Comment by pwyborn** [comment]
Create a new joiner guide in our internal cloud platform runbooks#1224 created

**Comment by pwyborn** [comment]
ticket complete
