### ISSUE TITLE
New alert route in Alertmanager

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#688]
## Service name

 New alert route in Alertmanager

## Service environment

- [ ] Dev / Development
- [x ] Staging
- [ ] Prod / Production
- [ ] Other

## Problem description

Hi
As per https://github.com/ministryofjustice/cloud-platform-user-docs/blob/master/03-monitoring-an-app/002-how-to-create-alarms.md
Can I please request a new alert route in Alertmanager.

namespace name: laa-fala-staging
team name:laa-cla-fala
application name:FALA staging
slack channel:cla-alerts

## Contact person
Slack:[at]said

**Comment by pwyborn** [comment]
“custom severity level" supplied to Said as required - think this can be closed now

**Comment by digitalronin** [comment]
Closing as per Paul's comment.
