### ISSUE TITLE
Alertmanager/Prometheus custom severity levels

### ISSUE THREAD

**Issue by ushkarev** [ministryofjustice/cloud-platform#691]
## Service environment

- [x] test
- [x] prod

## Description

We would like to have Alertmanager/Prometheus custom severity levels set up for our 2 cloud platform namespaces:

namespace: `money-to-prisoners-test`
team: `prisoner-money`
application: `money-to-prisoners`
slack: `#prisoner-money-alerts`

namespace: `money-to-prisoners-prod`
team: `prisoner-money`
application: `money-to-prisoners`
slack: `#prisoner-money-alerts`

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/185
