### ISSUE TITLE
Random 504 GATEWAY_TIMEOUT errors in pods

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#693]
We've been observing in all of our services deployed to k8s (staging and production envs across 3 different namespaces) tiny downtimes as a consequence of some requests hitting what seems to be a bad proxy or load balancer or IP, I don't know how to diagnose this.

I can observe this myself by going to a service URL and repeatedly reload the page until eventually, the 504 error happens.

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

Some URLs that I've been probing:

https://family-mediators-api-staging.apps.cloud-platform-live-0.k8s.integration.dsd.io/ping.json

https://fj-cait-staging.apps.cloud-platform-live-0.k8s.integration.dsd.io/ping.json

Pingdom report showing the probes failures:

<img width="619" alt="screen shot 2019-03-05 at 11 48 00" src="https://user-images.githubusercontent.com/687910/53804507-a1b51700-3f3f-11e9-9122-08df5ba09d56.png">
<img width="688" alt="screen shot 2019-03-05 at 11 55 29" src="https://user-images.githubusercontent.com/687910/53804508-a1b51700-3f3f-11e9-8ba3-5804f84e9a07.png">

It seems the problems started around 26th or 27th February:

<img width="517" alt="screen shot 2019-03-05 at 11 57 16" src="https://user-images.githubusercontent.com/687910/53804509-a1b51700-3f3f-11e9-8d15-dd0491d4ae2b.png">

## Contact person

Jesus @ slack

**Comment by digitalronin** [comment]
I've confirmed this on 

https://fj-cait-staging.apps.cloud-platform-live-0.k8s.integration.dsd.io/ping.json

I got a 504 (very) roughly once every 50 requests.

I didn't get any 504s on 

https://family-mediators-api-staging.apps.cloud-platform-live-0.k8s.integration.dsd.io/ping.json

But, just because it didn't happen in the 100 or so requests I sent, doesn't mean it's not happening.

**Comment by zheileman** [comment]
Quick update. 24 hours after the bump in cpu/ram allocations we've not had any outage/downtime in any of our pods across 3 different services.

Looks good so far 👍

**Comment by digitalronin** [comment]
@zheileman How is the service looking? Any more 504s?

**Comment by zheileman** [comment]
Sorry to report we've had a few more blips recently in a couple environments.

Same 504 error. But I couldn't trigger myself any 504, so perhaps it has resolved again itself?

This is family mediators, after a couple days without 504 errors, we got 2:

<img width="511" alt="screen shot 2019-03-08 at 09 09 43" src="https://user-images.githubusercontent.com/687910/54019044-18d9ed80-4182-11e9-9115-627bad94d03f.png">

And this is CAIT, only one 504 so far:

<img width="506" alt="screen shot 2019-03-08 at 09 11 56" src="https://user-images.githubusercontent.com/687910/54019114-46269b80-4182-11e9-969d-00e14bf1c241.png">

**Comment by pwyborn** [comment]
One of the instances on the load balancer is "out of service" . Docker containers not running (looking into) Family Mediators/FM -0a84b5b061431548c

**Comment by pwyborn** [comment]
Initial reboot of instance

**Comment by zheileman** [comment]
Hi @pwyborn 

Is that template-deploy? This issue ticket was for k8s really. But if there is any issue with template deploy that can be solved quickly, then that's fine with me 👍 

The 504 errors seems to have disappeared now. But will continue monitoring it.

**Comment by pwyborn** [comment]
Yeah @zheileman - got my wires crossed there. Yes that was template deploy, and there was a problem with one of the instances - it is ok now.

Seemed ok when I check - admittedly only over 5 minutes on each

**Comment by pwyborn** [comment]
@zheileman - let me know if you are still getting problems. Difficult to analyse as I do not think application logs going to fluentd/kibana

**Comment by pwyborn** [comment]
@zheilman - have brought up 2 fresh pods on each - just incase this frees up anything (don't think it will though). Can you please continue to monitor.

**Comment by zheileman** [comment]
This continues happening although less frequently than before.

These are the micro downtimes for CAIT staging (k8s):
<img width="539" alt="Screen Shot 2019-03-14 at 10 38 06" src="https://user-images.githubusercontent.com/687910/54350584-859f2d00-4645-11e9-906d-c9aa9a798ff6.png">

And these are the micro downtimes for Family Mediators API staging (k8s):
<img width="532" alt="Screen Shot 2019-03-14 at 10 41 01" src="https://user-images.githubusercontent.com/687910/54350653-aebfbd80-4645-11e9-8dbd-2f006acbdf7b.png">

We are not currently monitoring the production environments (kubernetes) because these are not in use (we are still using the template deploy production envs instead) but I anticipate this is also happening in the production envs.

Please let me know if you need other information.

**Comment by razvan-moj** [comment]
hi @zheileman there have been quite a few upgrades in the meantime, how does the report look for you?

**Comment by zheileman** [comment]
Hi @razvan-moj 

We continue to observe micro-downtimes with 504 error. It seems to be particularly bad in mediators API production (it is soft-production, not public, we still use template deploy for the "real" production).

As far as I can see this is the only service where we've had 504 in the last 24 hours.

<img width="541" alt="Screen Shot 2019-03-28 at 11 31 06" src="https://user-images.githubusercontent.com/687910/55154564-0c2b3280-514d-11e9-9a0a-4b06c4341370.png">
<img width="571" alt="Screen Shot 2019-03-28 at 11 31 13" src="https://user-images.githubusercontent.com/687910/55154566-0c2b3280-514d-11e9-814e-595a05a089ac.png">

**Comment by razvan-moj** [comment]
@zheileman ingress configuration was changed today, removing ALBs and keeping NLBs which means all errors at HTTP level will reach your logs; please check again in e.g. 24 hrs if you still get the sporadic 504s

**Comment by zheileman** [comment]
@razvan-moj we've not observed any more 504's for the last few days. One caveat: we've started migrating to `live-1` some of these services, and stopped/removed the `live-0` ones, so not sure if that's the reason.

In any case, looking good so far 😃
