### ISSUE TITLE
Form Builder - wildcard certs for dynamically created domains

### ISSUE THREAD

**Issue by solidgoldpig** [ministryofjustice/cloud-platform#694]
## Service name

Form Builder

## Service environment

- [*] Dev / Development
- [*] Staging
- [*] Prod / Production
- [*] Other

Er, it's complicated

## Impact on the service

Without a solution for Form Builder's naming scheme for domains is needed to enable, our end users cannot create forms with nice names

## Problem description

Form Builder has 3 platform environments (live, integration and test) and within each of those, 3 deployment environments (production, staging and dev).

We would ideally like our domains to follow this pattern

`[DEPLOYMENT].SERVICE.[PLATFORM].forms.service.justice.gov.uk`

eg.
`leavers.forms.service.justice.gov.uk` - live production
`dev.leavers.forms.service.justice.gov.uk` - live dev
`leavers.integration.forms.service.justice.gov.uk` - integration production
`dev.leavers.integration.forms.service.justice.gov.uk` - integration dev
`leavers.test.forms.service.justice.gov.uk` - test production
`dev.leavers.test.forms.service.justice.gov.uk` - test dev

Will we need to make a cert and inject it for each and every one of these domains or can we get away with a wildcard to handle them all? Or somewhere in between?

The live production version of the `leavers` form is deployed to the `formbuilder-services-live-production` namespace etc

## Contact person

Alex Robinson @alex.robinson

**Comment by digitalronin** [comment]
I've just had a conversation with Alex & Jenny about this.

The formbuilder team can live with having 3 wildcard certs - one each for test/integration/live (where 'live' is *.forms.service.justice.gov.uk - i.e. no <platform> component in the domain.

So, taking some of the examples above:

```
leavers.forms.service.justice.gov.uk - live production
dev-leavers.forms.service.justice.gov.uk - live dev
leavers.integration.forms.service.justice.gov.uk - integration production
dev-leavers.integration.forms.service.justice.gov.uk - integration dev
```
