### ISSUE TITLE
Research Service Mesh

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#701]
## Background

What is a Service Mesh - https://www.nginx.com/blog/what-is-a-service-mesh/

Service meshes on kubernetes have employed sidecar proxy containers to intercept traffic from application containers in order to provide functionality. This does not work well on a cluster using `PodSecurityPolicies` as it effectively circumvents the protections (see this [issue](https://github.com/kubernetes/kubernetes/issues/55435)).

However, we've recently had:
- Istio release [`istio-cni`](https://github.com/istio/cni)
- Linkerd release the [`cni-plugin`](https://linkerd.io/2/features/cni/)

From the `istio-cni` README:
> The CNI handling the netns setup replaces the current Istio approach using a `NET_ADMIN` privileged `initContainers` container, `istio-init`, injected in the pods along with `istio-proxy` sidecars. This removes the need for a privileged, `NET_ADMIN` container in the Istio users' application pods.

Both these options effectively solve the aforementioned PSP issue.

## Approach

Investigate both service meshes:
- Feature comparison
- Performance (in terms of resource usage)
- Management "cost"

Both these approaches mean we'll be switching from the battle-tested [`calico`](https://github.com/projectcalico/calico) CNI to a much younger alternative (linkerd's feature is marked as experimental). Therefore, extra care should be taken in verifying the viability and validity of this approach. Additionally, our upgrade procedure should be tested thoroughly to ensure no downtime will occur for our tenants.

## Areas of interest

* Mutual TLS
* Routing outside the cluster over secure network links
* Monitoring and auditing access to services

## For reference

* https://diego-pacheco.blogspot.com/2019/02/running-istio-on-aws-with-kops.html

## Done when
- [ ]
- [ ]
- [ ]
- [ ]

**Comment by wmorgan** [comment]
Hi! Great to see this, and please feel free to pull me in to any discussions you think would be helpful on the @Linkerd side!

A couple quick comments:
- You don'tt need to replace Calico to use Linkerd's CNI plugin. In fact you can't. The Linkerd CNI plugin is designed to work with Calico.
- We've marked this plugin as "experimental" but that's mostly us being conservative. It's been tested quite a bit with Calico especially. We'll remove that label once it's seen a bit more use, and please do ping us if you encounter any issues.
- In terms of resource usage, we published some [Linkerd benchmarks](https://linkerd.io/2019/05/18/linkerd-benchmarks/) last month which you may want to check out.

Finally, we don't have a quantitative comparison of management cost, but we do speak to this directly in our [design principles](https://linkerd.io/2019/04/29/linkerd-design-principles/).

Hope that helps!

**Comment by alkar** [comment]
@wmorgan thanks for pitching in, that's all _very_ useful to know in advance!

**Comment by razvan-moj** [comment]
done, demoed and described in https://docs.google.com/document/d/1XveSXrCExasksScZcYplBoIKDW_5mvHDCuxw4DtOnQg/edit#

**Comment by wmorgan** [comment]
What was the result? Is that doc shareable? 😅

**Comment by AntonyBishop** [comment]
Hi @wmorgan,

Within this time boxed spike we had limited time to look at all options we'd have liked to. Regrettably Linkerd was not one of the ones we had time to look at, but hope to revisit in due course.

Unfortunatley due to the nature of the assessment, some of which is commercially sensitive we can't openly share the details at this time.

Just as en extra note one of the reasons Linkerd was not prioritised this time round was lack of support by KOPS on which we are heavily reliant. Maybe that position will change.

Hope that makes sense. Kind regards 
Tony

**Comment by wmorgan** [comment]
Bummer. Linkerd works great with KOPS btw. Lots of happy prod users. Happy to talk further.
