### ISSUE TITLE
Create a live like test cluster to be destroyed at 20:00 and recreated at 8:00

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#704]
Placeholder

**Comment by digitalronin** [comment]
FYI: This is a 10-minute talk about doing this kind of thing using AWS Lambda (via the 'serverless' framework). It might be worth a look.

https://skillsmatter.com/skillscasts/13431-automating-infrastructure-tasks-with-the-serverless-framework

**Comment by AntonyBishop** [comment]
We are now looking at a different approach.
