### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#707]
Placeholder

There is too much noise in the #ask-cloud-platform slack channel. Look into github actions to filter our all PR notifications to just new PR's

Related stories:
#708
#709

**Comment by lukaszraczylo** [comment]
I've issued PR for this - https://github.com/ministryofjustice/cloud-platform-environments/pull/704

**Comment by lukaszraczylo** [comment]
And following - https://github.com/ministryofjustice/cloud-platform-environments/pull/711
