### ISSUE TITLE
Build a concourse on the live-0 cluster

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#71]
## Background 

This will be the main cloud platform team concourse instance. 

## Done when 
- [x] There is a concourse environment on the `live-0` cluster that the webops team have access to
- [x] A concourse instance is running in this namespace
- [x] The concourse uses RDS as it’s backing database
- [x] This repo is renamed; https://github.com/ministryofjustice/concourse-CP 
- [x] We can run a helm command from this repository to spin up concourse in the concourse environment
- [x] Write a readme that explains how to install and update concourse

**Comment by alkar** [comment]
Blocked by https://github.com/ministryofjustice/cloud-platform/issues/98

**Comment by kalbir** [comment]
@alkar has created a new cluster `cloud-platform-live-0`, and deployed concourse onto it, that's where we will be doing the various concourse stories (I've updated the description here to reflect that).

**Comment by alkar** [comment]
Requires https://github.com/ministryofjustice/kubernetes-investigations/pull/31

**Comment by alkar** [comment]
@kalbir should we close this?
