### ISSUE TITLE
Create an Unprivileged Pod Security Policy

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#713]
## Background

TBC

## Proposed user journey

TBC

## Approach

TBC

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

We need to understand the impact of this policy on teams. We will as part of an other story access this impact.

## Definition of done

TBC

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by kcbotsh** [comment]
@AntonyBishop can you please complete ticket info

**Comment by AntonyBishop** [comment]
Is dependant on #714 and #715

**Comment by mtrblmoj** [comment]
I don't think this is needed anymore ?

**Comment by AntonyBishop** [comment]
Yep. Gonna close this one.
