### ISSUE TITLE
New alert route in Alertmanager?

### ISSUE THREAD

**Issue by Kalagan** [ministryofjustice/cloud-platform#716]
## Service name

`laa-apply-for-legal-aid`

## Service environment

- [ ] Dev / Development
- [X] Staging
- [ ] Prod / Production
- [ ] Other

## Problem description

As per https://github.com/ministryofjustice/cloud-platform-user-docs/blob/master/03-monitoring-an-app/002-how-to-create-alarms.md, could we have a new alert route in Alertmanager?

```
namespace: laa-apply-for-legalaid-staging
team: apply-for-legal-aid
application: laa-apply-for-legal-aid
slack: #apply-alerts-staging
```

## Contact person

Slack: Julien Sansot

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/197

**Comment by pwyborn** [comment]
team notified of  “custom severity level”

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/202
