### ISSUE TITLE
Amend wording in "Creating a slack webhook and amend Alertmanager" part of guide

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#717]
## Background

We've recently introduced guidance for "Creating a slack webhook and amend Alertmanager". In the guidance we ask users to:

<img width="804" alt="Screen Shot 2019-03-12 at 09 37 23" src="https://user-images.githubusercontent.com/36888942/54189819-7e8fe780-44aa-11e9-9ec2-8b376e66fd87.png">

This implies that users just post the request in the channel, when we actually want them to raise a request form. 

We will have users interacting with us who are maybe new or unfamiliar with our processes so should make our process clear in the guidance. 

By doing this they make their request once and we spend less time needing to redirect users.

Suggested wording:

"Use the Cloud Platform Support Request form, which can be found at the top of the #ask-cloud-platform slack channel, to request a new alert route in Alertmanager. Please include the following information in your request:" 

Include the direct link to the form. Make it easy for user the find the form.

## Proposed user journey

A user knows where and how to request support from the Cloud Platform Team, so they can make their request first time and get the outcome they require.

## Approach

Amend wording in guide.

## Which part of the user docs does this impact

Creating a slack webhook and amend Alertmanager

## Questions / Assumptions

None.

## Definition of done

- [x] wording amended

We should see a reduction in the number of times we have to redirect users to the request form.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-user-docs/commit/c7a8cedbc6f2389dbfc870b26728d2620afa994d
