### ISSUE TITLE
Create domain name

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#718]
## Service name

Managing Offenders in Custody (MOiC)

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Problem description

Please can you create a new domain name `https://moic.service.justice.gov.uk` and point it to our kubernetes production deployment - `https://allocation-manager-production.apps.cloud-platform-live-0.k8s.integration.dsd.io/`

## Contact person

Toby Retallick (#the_sassy_bears)

**Comment by TobyRet** [comment]
Please note domain name has been updated in ticket

**Comment by TobyRet** [comment]
Ideally we would like to have this up and running by middle of next week if possible @AntonyBishop @jasonBirchall

**Comment by jasonBirchall** [comment]
Still waiting on external-dns ticket. Will check in today.
