### ISSUE TITLE
Concourse pipelines are managed from code only

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#72]
## Background 

Part of #62. Related to #71 (needs to be done after #71 or in close discussion on the design with whoever does that one).

We don't want any pipelines to be created manually and if they are created manually we want them to be deleted. So let's put them all under source control and have a pipeline that builds these pipelines. 

## Suggested approach
Every pipeline in the repo is built on concourse
Only the pipelines in the repo are built on concourse
This is checked every hour

## Done when
 
- [x] There is a repository that contains all of our concourse pipelines - currently the `terraform` pipeline created in #74 and the environment creation pipeline created in #38.
- [x] There is a concourse pipeline that manages concourse pipelines -- it checks the repo and adds the pipelines from the repo
- [x] No manual changes are persisted on concourse -- when a user makes a manual change or adds something manually with `fly` it will get removed on a regular basis (e.g. once a day) 
- [x] There is a readme that says how to setup a pipeline in code

**Comment by alkar** [comment]
https://github.com/ministryofjustice/cloud-platform-concourse/pull/8 includes the pipeline from #38  but #74 is not done yet.

**Comment by alkar** [comment]
Merged https://github.com/ministryofjustice/cloud-platform-concourse/pull/8.
