### ISSUE TITLE
Timeouts deploying to our UAT system

### ISSUE THREAD

**Issue by reggieb** [ministryofjustice/cloud-platform#720]
## Service name

laa-apply-for-legal-aid

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [x] Other - UAT

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

We are unable to push new branches to UAT for review by other members of the team. This is holding up all our development.

## Problem description

Similar to previous problems: https://github.com/ministryofjustice/cloud-platform/issues/604

```
#!/bin/bash -eo pipefail
./bin/uat_deploy
There are currently 9 releases.
Cleaning the 7 most old ones...
[DRY-RUN] Deleting release apply-for-legal-aid-ap-268-provider-navigates-to-m...
[DRY-RUN] Deleting release apply-for-legal-aid-ap-375-show-selected-transacti...
[DRY-RUN] Deleting release apply-for-legal-aid-ap-379-applicant-summary-payme...
[DRY-RUN] Deleting release apply-for-legal-aid-ap-395-upload-files-with-javas...
[DRY-RUN] Deleting release apply-for-legal-aid-ap-403-respondent-details...
[DRY-RUN] Deleting release apply-for-legal-aid-ap-402-work-covered...
[DRY-RUN] Deleting release apply-for-legal-aid-portal-testing...
Deploying CIRCLE_SHA1: e12df9dbc325f4454adb0a935a909072cf9222f6 under release name: 'apply-for-legal-aid-ap-408-enter-details-of-latest'...
Error: UPGRADE FAILED: timed out waiting for the condition
Exited with code 1
```
https://circleci.com/gh/ministryofjustice/laa-apply-for-legal-aid/3609?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

## Contact person

On slack: RobNichols

**Comment by ollieanwyll** [comment]
Fixed by the following PR:
https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/341
