### ISSUE TITLE
Access required for AWS and Jenkins

### ISSUE THREAD

**Issue by mseedat-moj** [ministryofjustice/cloud-platform#722]
## Service name

Request for 2 users from Transformed Department (Correspondence Tool):

mohammed.seedat@digital.justice.gov.uk
stephen.dicks@digital.justice.gov.uk

*Project: Correspondence Tool*

*Request:*
1. Amazon AWS account required for mojdsd team
2. Jenkins authorisation required

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production
- [x] Other

## Impact on the service

*To the Jenkins System*
1. Deployment of system to existing staging and production environments (template deploy)
2. Practice migration on new cloud platform (kubernetes based deployment)
3. Manage Continuous Integration pipeline/issues/etc

*To AWS mojdsd*
1. For development purposes (S3, etc)
2. For dev/staging/production environments access
3. For commissioning additional servers if required

I ticked 'other' in case there are other systems we would need access to in order to perform deployments and setting up the migration of the existing app to the new cloud platform.

## Problem description

Cannot deploy latest updates to Correspondence tool application.

Cannot perform cloud platform migration work.

## Contact person

mohammed.seedat@digital.justice.gov.uk
@moseedat

**Comment by pwyborn** [comment]
Jenkins access provided to both (confirmed by them in slack)

**Comment by pwyborn** [comment]
To be closed
