### ISSUE TITLE
Ref app: fix Prom Django monitoring for Helm too

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#723]
**What**
While testing the user docs for https://github.com/ministryofjustice/cloud-platform-user-docs/pull/132 we noticed configuration covers only kubectl

**Why**
Would be nice to also show a working https://github.com/ministryofjustice/cloud-platform-reference-app/tree/master/helm_deploy/django-app

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-reference-app/pull/68
