### ISSUE TITLE
New alert routes in Alertmanager 

### ISSUE THREAD

**Issue by Kalagan** [ministryofjustice/cloud-platform#724]
## Service name

`laa-apply-for-legal-aid`

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X] Prod / Production
- [X] UAT

## Problem description

As per https://github.com/ministryofjustice/cloud-platform-user-docs/blob/master/03-monitoring-an-app/002-how-to-create-alarms.md, could we have a new alert route in Alertmanager?

```
namespace: laa-apply-for-legalaid-uat
team: apply-for-legal-aid
application: laa-apply-for-legal-aid
slack: #apply-alerts-uat
```

```
namespace: laa-apply-for-legalaid-production
team: apply-for-legal-aid
application: laa-apply-for-legal-aid
slack: #apply-alerts-prod
```

## Contact person

Slack: Julien Sansot

**Comment by Kalagan** [comment]
I should have included these as part of https://github.com/ministryofjustice/cloud-platform/issues/716. Sorry...

**Comment by kcbotsh** [comment]
@pwyborn do we need to delete this as a duplicate ticket?

**Comment by pwyborn** [comment]
Done. To be closed
