### ISSUE TITLE
SPIKE: Fluentd JSON Plug-in

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#725]
## Background

This story has been created to progress the problem identified by #678.

We will work with identified users to spike a possible solution using the Fluentd JSON plug-in.

We do not yet know if this will address this need.

## Proposed user journey

A user is able to parse the JSON fields from fluentd so they can be searchable in Kibana.

## Approach

- Demo of existing solution provided by Template Deploy
- Research with users into whether plug-in solves problem.

## Which part of the user docs does this impact

N/A. However, guidance may be required. Will be implemented under a new story if applicable.

## Questions / Assumptions

Does this plug-in address the problem. How involved is this solution?
What does the CP team need to do to implement a solution? 
What do users need to do to implement a solution?

## Definition of done

- [ ] We understand whether this plug-in resolves the issue.
- [ ] We understand what the CP Team needs to do support the solution.
- [ ] Users understand what they need to do to use the solution.
- [ ] We have identified follow up stories to progress the solution.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
for now, result is the 2 PRs linked; will be replaced by a story to implement/document
