### ISSUE TITLE
Turn off SendGrid notifications for the Cloud Platform Team

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#726]
## Background

The Cloud Platform Team doesn't use SendGrid nut we get a load of notifications to the team mailbox. We don't want or need these notifications. 

## Proposed user journey

The Cloud Platform no longer receive SendGrid notifications to the team mailbox.

## Approach

Get notifications turned off for the Cloud Platform Team

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] SendGrid notifications are no longer received by the Cloud Platform Team.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
platforms@digital.justice.gov.uk account disabled - should hopefully stop emails (we shall see!)

**Comment by pwyborn** [comment]
To close
