### ISSUE TITLE
Create a runbook for the Cloud Platform Team to support migrations from Templated Deploy to the Cloud Platform

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#728]
## Proposed user journey

User are migration from the legacy Template Deploy to the Cloud Platform.

As a result of the migration there are activities for the Cloud Platform Team to perform to decommission legacy infrastructure and tooling.

We need to capture what this is so that we have a documented process for the team to follow after each migration to ensure that services are fully decommissioned and nothing legacy is left behind.

## Approach

We need to document a list of things that we need to do to a service when it has migrated from Template Deploy to Cloud Platform.

Work out what those things are e.g. disabling alerts, archiving repos etc

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

What are the list of things we need to think about/do?

## Definition of done

- [x] We have a runbook that details what we need to do to a product when it has finished it's migration to the Cloud Platform.
- [x] Test it by using it on a product that has already migrated to the Cloud Platform.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Reference - PVB Migration Lessons Learned - https://mojdt.slack.com/files/U5X15FGEP/FGK2E4EQH/prison_visits_booking__pvb__migration_from_template_deploy_to_kubernetes

**Comment by digitalronin** [comment]
I've made a start on a document here: https://docs.google.com/document/d/1y-xOPYEKYoe245i9p0IPln0M3IQXKDVSRmVHTPn7HG0/edit?usp=sharing

**Comment by jasonBirchall** [comment]
I believe there is some confusion around this ticket. I've had a chat with contributors of this ticket and clarified: This document will contain a runbook for cloud-platform engineers to perform a post migration check and destruction.

**Comment by jasonBirchall** [comment]
Had a chat with some engineers with experience in this field. We agree on the following structure:
```
