### ISSUE TITLE
Create and setup AWS credentials for concourse

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#73]
## Background

Part of #62, depends on #71 (as this will have to sit on that instance).

Concourse needs credentials to run the pipelines that make AWS resources using terraform. To do this it will need a credential that can run commands like `terraform apply` on our AWS account.

## Done when

- [x] We’ve worked out the least privilege policy that can run the commands we need to run the S3 creation pipeline (we think this is S3 and IAM creds) 
- [x] There is a terraform file to create this credential in github - in the concourse repo as it will only be used by concourse
- [ ] There is a readme documenting how this credential can be generated
- [x] The creds have been manually added to Concourse kubernetes namespace as environment variables with standard AWS names e.g. `AWS_SECRET_ACCESS_KEY` and `AWS_SECRET_ACCESS_KEY`

**Comment by razvan-moj** [comment]
If a single credential set / IAM role is shared by all team, we might want to build in a restriction against accidental deletion (e.g. if the parent folder is removed from git, all the buckets would be deleted by a 'terraform apply')

**Comment by kalbir** [comment]
![img_20180605_111915](https://user-images.githubusercontent.com/3952074/40970717-50d81e3a-68b3-11e8-87af-15de4c427a9d.jpg)

For @jojuolape 😉

**Comment by alkar** [comment]
Connects to https://github.com/ministryofjustice/cloud-platform-concourse/pull/3
