### ISSUE TITLE
Unsubscribe from Sentry Alerts

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#732]
## Background

Cloud Platform Team doesn't use Sentry but we get all the alerts. We don't need these alerts so need to unsubscribe from all Sentry alerts.

## Proposed user journey

Cloud Platform Team doesn't get Sentry alerts

## Approach

Unsubscribe the platforms mail account from Sentry notifications

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] Cloud Platform Team no longer receives Sentry alerts.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
Unsubscribed platforms@digital.justice.gov.uk
 from emails (hopefully!)

**Comment by pwyborn** [comment]
To close
