### ISSUE TITLE
Managed Sentry for users of the Cloud Platform

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#733]
## Background

Users of the Cloud Platform will need to use Sentry. We use Sentry with Template Deploy. We want to consider migrating to a managed Sentry.

## Proposed user journey

TBC

## Approach

Discuss approach with security
Find out how much it costs

## Which part of the user docs does this impact

Guidance for users may be required, although currently teams manage this themselves.

## Questions / Assumptions

Is this story a Spike? Does this need further breakdown.
- Can we ship stuff to managed service? - Discuss with security. Is managed Sentry appropriate.
- Costs/Value

## Definition of done

TBC

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by kcbotsh** [comment]
Form Builder request for go live July 23rd

**Comment by AntonyBishop** [comment]
Going to replace this issue with a fresh spike.
