### ISSUE TITLE
Review of CloudWatch Alerts

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#734]
## Background

We use CloudWatch for monitoring and alerting on AWS resources. We created all our alerts with CloudFormation and they are all managed as code. This work was completed over 9 months ago and we want to review that our alerts are still fit for purpose.

## Approach

Review the alerts we have created.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

Review should answer:
1. Do we have all the alerts we need?
2. Are there alerts we no longer need?
3. Are the alerts we need set up correctly?

## Definition of done

- [x] complete review and answer questions
- [x] alerts we no longer need are removed
- [x] any new alerts are created using CloudFormation

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Answered questions here:
https://docs.google.com/document/d/1es_f1PfD7NxH16MfNPa-289SLfz2dDIC0C5dNRExe7k

**Comment by jasonBirchall** [comment]
Instead of a team meeting about this issue, i've created a  number of GH issues outlining the recommended actions for this task. Marking issue as resolved.
