### ISSUE TITLE
Review of Prometheus Alerts

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#735]
## Background

We use Prometheus for monitoring and alerting. Prometheus comes configures with no rules but has some default rules.

To ensure we can operate the Cloud Platform we need to ensure that we are getting the right types of alerts and that they are set at the right level of criticality.

We also have some application type metrics we require for some of our own namespaces.

## Approach

We need to review all the default config file rules (approx 50). We need to determine any changes that we require (we should use defaults where possible as our first choice).

Implement changes that we require. Depending on number or complexity this story may need to be broken down further.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

Design decision: Where possible we should use default rules rather than create custom rules. Custom rules creates a management overhead and increases complexity. Additional custom rules makes it more difficult to upgrade Prometheus.

Assumption: We'll manage this as one story from the outset. If size or complexity warrants it we may split the story up. This will be decided by whoever picks up this story.

## Definition of done

- [x] review completed
- [x] stories created to implement custom rules were required (might just form part of this story)
- [x] user guidance created and tested with a user (if applicable)

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/219
