### ISSUE TITLE
503 nginx errors on deployments

### ISSUE THREAD

**Issue by willc-work** [ministryofjustice/cloud-platform#736]
## Service name
apply-for-legal-aid

## Service environment

- [x] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [x] Other . - UAT

## Impact on the service

Unable to test the application in UAT, preventing us from getting tickets reviewed and impeding progress

## Problem description

After the deployment passes tests on circle ci and is deployed successfully the URL throws a 503 error.
example URLs:
ap-406-citizen-flow-applyforlegalaid-uat.apps.cloud-platform-live-0.k8s.integration.dsd.io
ap-426-remove-council-tax-applyforlegalaid-uat.apps.cloud-platform-live-0.k8s.integration.dsd.io

when we run `kubectl describe pod...` we get errors with liveness probes and readiness probes due to connection refused

Liveness probe failed: Get http://100.115.193.224:3002/status.json: dial tcp 100.115.193.224:3002: getsockopt: connection refuse

Readiness probe failed: Get http://100.115.193.224:3002/status.json: dial tcp 100.115.193.224:3002: getsockopt: connection refused

## Contact person

Will Clarke slack handle @willclarke
email william.clarke@digital.justice.gov.uk

**Comment by razvan-moj** [comment]
clarified in chat - application startup was slower than the healthcheck threshold, all good now

**Comment by willc-work** [comment]
👍
