### ISSUE TITLE
Create a pipeline for applying terraform from user input 

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#74]
## Background

Requires #166. You might also want to look at #75 which will get completed by this issue. 

Part of #62. Depends on #37, #73 and a bit on #71.

@mitch can help with this one 

We want users to add their terraform resources in their namespace directory and then we build those resources. #70 will define the structure that the user will use to create those resources, #69 will create the module that will create an S3 bucket. This story is to create the pipeline that takes the user input and the S3 module and runs terraform on it so that the resources (in this case an S3 bucket) get built. 

## Assumptions
We think that the pipelines should work so that a change in namespace folder triggers the env creation pipeline, if the change was also in the terraform folder it will run the terraform pipeline too.

## Done when

- [x] There is a pipeline in concourse that takes as input the terraform file from the user namespace directory and runs terraform successfully (in this case creates credentials and builds an S3 bucket) 
- [ ] The job also creates and sets an kube secret
- [ ] The pipeline is defined in code (maybe in concourse repo) 
- [x] Everytime there is a change to the terraform folder, the namespace pipeline runs first, then this pipeline runs (implementation left to team member, this could be one new pipeline, or a composed pipeline)
- [x] There is a new dedicated S3 bucket for terraform state files with access controls and encryption -- created using terraform
- [x] The pipeline notifies the `cp-build-notification` slack channel on success or failure

**Comment by ale-novo** [comment]
in a discussion with @alkar it was determined:
1) the terraform files will live in namespaces/<cluster>/<namespace>/terraform
2) this will be added as another step in the namespace creation pipeline (not a new pipeline)

**Comment by ale-novo** [comment]
this ticket depends on https://github.com/ministryofjustice/cloud-platform/issues/38

**Comment by ale-novo** [comment]
marked as blocked

**Comment by ale-novo** [comment]
bullet point ` The pipeline notifies the cp-build-notification slack channel on success or failure` was completed on https://github.com/ministryofjustice/cloud-platform/issues/38

**Comment by alkar** [comment]
Depends on #213
