### ISSUE TITLE
Waffle Migration

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform#746]
Waffle is closing on 16/05/19.

Prepare for Migration to Github projects

 The Waffle badges and graphs will stop working when Waffle closes, remove them before this.

Add sizes/ estimates as a label on each issue. 

Manually download all images and attachments from Waffle. They will not migrate.

**Comment by lukaszraczylo** [comment]
I'm thinking about ZenHub - It's free for public repos ( and that's what we have ).
