### ISSUE TITLE
Expand the pipeline so that the secrets end up in kubernetes

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#75]
## Background
From #74 we will have a terraform pipeline on concourse that will apply terraform on the inputs that the user has put in (defined in #70) and create AWS resources. We also want terraform to create a kubernetes secret resource and add any secrets that the user wants to add into the cluser. 

We propose using the kubernetes secret resource, using the snippet that @mitch has posted on #70 (also a comment below). To do this the pipeline will have to have the right credentials to create a secret in Kubernetes in any teams repositiory. 

## Done when

- [ ] The concourse terraform pipeline has access to a kubernetes service account that can read/create/delete secrets in all namespaces 
- [ ] The terraform pipeline in concourse successfully creates a kubernetes secret from the user input

**Comment by kalbir** [comment]
Suggested input style for -- to be confirmed by #70.

```hcl
module "my_s3_bucket" {
  source = "github.com/ministryofjustice/cloud-platform-terraform-s3-bucket?ref=master"

  team_name = "my-team"
  bucket_id = "my-bucket"
}

resource "kubernetes_secret" "my_s3_bucket_creds" {
  metadata {
    name = "my-s3-bucket-creds"
  }

  data {
    access_key_id     = "${module.my_s3_bucket.access_key_id}"
    secret_access_key = "${module.my_s3_bucket.secret_access_key}"
    bucket_name       = "${module.my_s3_bucket.bucket_name}"
  }
}
```

**Comment by nayoa** [comment]
Ticket depends on #74

**Comment by ollieanwyll** [comment]
provider "aws" {
  region = "eu-west-1"
}

module "example_sns_topic" {
  source = "github.com/ministryofjustice/cloud-platform-terraform-sns-topic?ref=master"

  team_name          = "example-repo"
  topic_name         = "example-topic-name"
  topic_display_name = "example-topic-display-name"
}

resource "kubernetes_secret" "example_k8_iam_secrets" {
  metadata {
    name      = "${module.example_sns_topic.topic_name}-sns-user"
    namespace = "example_namespace"
  }

  data {
    user_name         = "${module.example_sns_topic.iam_name}"
    access_key_id     = "${module.example_sns_topic.iam_access_key_id}"
    secret_access_key = "${module.example_sns_topic.iam_secret_access_key}"
    topic_arn         = "${module.example_sns_topic.topic_arn}"
  }
}

**Comment by kalbir** [comment]
Closing as this should get done by #74 but I'll connect them so that the info is shared.
