### ISSUE TITLE
User guide: Add instructions about non-root users in app. containers

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#750]
Our pod security policy on live-1 prevents containers running if their user is 'root'.

Add guidance in the user guide explaining this restriction, and telling developers what they should do in order to comply.

**Comment by vijay-veeranki-moj** [comment]
https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#how-to-adapt-to-the-pod-security-policies

https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#podsecuritypolicy
