### ISSUE TITLE
Review of Pingdom Alerts

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#752]
## Background

We use Pingdom for alerting. We created all our alerts with Terraform and they are all managed as code. We want to review that our alerts are still fit for purpose.

## Proposed user journey

N/A

## Approach

Review of alerts.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

Review should answer:
Do we have all the alerts we need?
Are there alerts we no longer need?
Are the alerts we need set up correctly?

## Definition of done
- [x] complete review and answer questions
- [x] alerts we no longer need are identified (application related alerts)
- [x] any new alerts are created using TF

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
Our existing terraform exists in pingdom now
I have added some cloud-platform alarms. This is a WIP that @sid is assisting with as I am off for a few days https://github.com/ministryofjustice/cloudplatforms-terraform-ops/pull/34

**Comment by pwyborn** [comment]
Removed manual "Platforms Registry - Ping" alert that was going to alert "IRAT low priority". Replaced it with terraform alert that goes to slack #lower-priority-alarms

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/C514ETYJX/p1554207270123100

**Comment by pwyborn** [comment]
The following changed from IRAT pingdom contact/webhook integration #hmcts-sustain-alerts slack:

Pingdom Check 
Apply to an Employment Tribunal - Jadu
Apply to an Employment Tribunal - Healthcheck
Apply to an Employment Tribunal - Payment
localgovernmentstandards.decisions.tribunals.gov.uk
External - SendGrid
Tribunal Decisions - Homepage
administrativeappeals.decisions.tribunals.gov.uk
asylumsupport.decisions.tribunals.gov.uk
carestandards.decisions.tribunals.gov.uk
charity.decisions.tribunals.gov.uk
cicap.decisions.tribunals.gov.uk
claimsmanagement.decisions.tribunals.gov.uk
consumercreditappeals.decisions.tribunals.gov.uk
employmentappeals.decisions.tribunals.gov.uk
estateagentappeals.decisions.tribunals.gov.uk
financeandtax.decisions.tribunals.gov.uk
http://civil-eligibility-calculator.justice.gov.uk/
immigrationservices.decisions.tribunals.gov.uk
informationrights.decisions.tribunals.gov.uk
landregistrationdivision.decisions.tribunals.gov.uk
landschamber.decisions.tribunals.gov.uk
phl.decisions.tribunals.gov.uk
siac.decisions.tribunals.gov.uk
sscs.venues.tribunals.gov.uk
tax.decisions.tribunals.gov.uk
taxandchancery_ut.decisions.tribunals.gov.uk
transportappeals.decisions.tribunals.gov.uk
webhelpdesk.dsd.io
