### ISSUE TITLE
Filter out Application related Pingdom alerts

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#753]
## Background

We have reviewed our Pingdom alerts - #752 

We have identified a number of application related alerts that we no longer need to receive. We need to filter the out of our channels so that we are not alerted.

## Proposed user journey

N/A

## Approach

Remove alerts we no longer need.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

Do we delete alerts?
Do we need to reroute any alerts to application teams?

## Definition of done

- [x] We no longer receive alerts that we don't require.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
Our existing terraform exists in pingdom now 
I have added some cloud-platform alarms. This is a WIP that @sid is assisting with as I am off for a few days https://github.com/ministryofjustice/cloudplatforms-terraform-ops/pull/34

**Comment by pwyborn** [comment]
https://docs.google.com/spreadsheets/d/1_jWDYVCfpNYdMTBFasGuOVMjOvW_Wj-IWCXxkkXc_no/edit#gid=0
Our existing terraform exists in pingdom now
I have added some cloud-platform alarms. This is a WIP that @sid is assisting with as I am off for a few days ministryofjustice/cloudplatforms-terraform-ops#34


Removed manual "Platforms Registry - Ping" alert that was going to alert "IRAT low priority". Replaced it with terraform alert that goes to slack #lower-priority-alarms.

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/C514ETYJX/p1554207270123100

**Comment by pwyborn** [comment]
The following changed from IRAT pingdom contact/webhook integration #hmcts-sustain-alerts slack:

Pingdom Check
Apply to an Employment Tribunal - Jadu
Apply to an Employment Tribunal - Healthcheck
Apply to an Employment Tribunal - Payment
localgovernmentstandards.decisions.tribunals.gov.uk
External - SendGrid
Tribunal Decisions - Homepage
administrativeappeals.decisions.tribunals.gov.uk
asylumsupport.decisions.tribunals.gov.uk
carestandards.decisions.tribunals.gov.uk
charity.decisions.tribunals.gov.uk
cicap.decisions.tribunals.gov.uk
claimsmanagement.decisions.tribunals.gov.uk
consumercreditappeals.decisions.tribunals.gov.uk
employmentappeals.decisions.tribunals.gov.uk
estateagentappeals.decisions.tribunals.gov.uk
financeandtax.decisions.tribunals.gov.uk
http://civil-eligibility-calculator.justice.gov.uk/
immigrationservices.decisions.tribunals.gov.uk
informationrights.decisions.tribunals.gov.uk
landregistrationdivision.decisions.tribunals.gov.uk
landschamber.decisions.tribunals.gov.uk
phl.decisions.tribunals.gov.uk
siac.decisions.tribunals.gov.uk
sscs.venues.tribunals.gov.uk
tax.decisions.tribunals.gov.uk
taxandchancery_ut.decisions.tribunals.gov.uk
transportappeals.decisions.tribunals.gov.uk
webhelpdesk.dsd.io

**Comment by pwyborn** [comment]
@AntonyBishop - in view of Steve's remarks https://mojdt.slack.com/archives/C514ETYJX/p1554280565138600?thread_ts=1554207270.123100&cid=C514ETYJX 
do we need to re-review these?:
The sendgrid one I have manually added #lower-priority-alerts (can add by terraform if we need to?
All remaining 27 are to   #hmcts-sustain-alerts manually

**Comment by AntonyBishop** [comment]
Have requested additional information from HMCTS Sustaining Team.

**Comment by AntonyBishop** [comment]
Have chased the HMCTS Sustaining Team again today.

**Comment by AntonyBishop** [comment]
@pwyborn few more updates from HMCTS. Please can the following alerts be redirected to #hmcts-sustain-alerts:

Apply to an Employment Tribunal - Jadu
Apply to an Employment Tribunal - Healthcheck
Apply to an Employment Tribunal - Payment
financeandtax.decisions.tribunals.gov.uk
financeandtax.decisions.tribunals.gov.uk

**Comment by AntonyBishop** [comment]
Remaining alerts to be investigated. Trying TP next:
https://docs.google.com/spreadsheets/d/1gecjHGh7T8FjZGUaQnZMIogEGTvZHPMJSglSTjHL3ho/edit?usp=sharing

**Comment by AntonyBishop** [comment]
Chased up TP DMs.

**Comment by AntonyBishop** [comment]
@pwyborn I have the final list. Grateful if all these in this list (https://docs.google.com/spreadsheets/d/1gecjHGh7T8FjZGUaQnZMIogEGTvZHPMJSglSTjHL3ho/edit?usp=sharing) could be redirected to #tactical_products.

When those are done we can close the ticket.

Incidentally do we have the url for the items described as "Tribunal Decisions - Homepage"?

**Comment by pwyborn** [comment]
Hi Tony - done from list to TP
Tribunal URL - https://tribunalsdecisions.service.gov.uk/utiac <https://tribunalsdecisions.service.gov.uk/utiac>


Paul Wyborn
Senior WebOps Engineer
Cloud Platforms | Justice Digital & Technology
10.54 Tower (Orange Core)

mailto: <>paul.wyborn@digital.justice.gov.uk

**Comment by AntonyBishop** [comment]
Thanks @pwyborn . Happy for ticket to be closed.
