### ISSUE TITLE
New Terraform for our Cloud Platform Pingdom Alerts

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#754]
## Background

We have reviewed all our Pingdom alerts and have a new state for our alerts. We need to ensure that all of these are captured in Terraform.

## Proposed user journey

N/A

## Approach

N/A

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

Should this be updated as we go along with #752 and #753? Rather than a separate story?

## Definition of done

- [ ] we can easily redeploy all our Pingdom alerts using Terrafom.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
ministryofjustice/cloudplatforms-terraform-ops#34

**Comment by pwyborn** [comment]
https://mojdt.slack.com/archives/C514ETYJX/p1554207270123100

**Comment by pwyborn** [comment]
The following changed from IRAT pingdom contact/webhook integration #hmcts-sustain-alerts slack:

Pingdom Check
Apply to an Employment Tribunal - Jadu
Apply to an Employment Tribunal - Healthcheck
Apply to an Employment Tribunal - Payment
localgovernmentstandards.decisions.tribunals.gov.uk
External - SendGrid
Tribunal Decisions - Homepage
administrativeappeals.decisions.tribunals.gov.uk
asylumsupport.decisions.tribunals.gov.uk
carestandards.decisions.tribunals.gov.uk
charity.decisions.tribunals.gov.uk
cicap.decisions.tribunals.gov.uk
claimsmanagement.decisions.tribunals.gov.uk
consumercreditappeals.decisions.tribunals.gov.uk
employmentappeals.decisions.tribunals.gov.uk
estateagentappeals.decisions.tribunals.gov.uk
financeandtax.decisions.tribunals.gov.uk
http://civil-eligibility-calculator.justice.gov.uk/
immigrationservices.decisions.tribunals.gov.uk
informationrights.decisions.tribunals.gov.uk
landregistrationdivision.decisions.tribunals.gov.uk
landschamber.decisions.tribunals.gov.uk
phl.decisions.tribunals.gov.uk
siac.decisions.tribunals.gov.uk
sscs.venues.tribunals.gov.uk
tax.decisions.tribunals.gov.uk
taxandchancery_ut.decisions.tribunals.gov.uk
transportappeals.decisions.tribunals.gov.uk
webhelpdesk.dsd.io

**Comment by pwyborn** [comment]
Complete

**Comment by pwyborn** [comment]
Update to remove "live-1" from the url

https://github.com/ministryofjustice/cloudplatforms-terraform-ops/pull/35
