### ISSUE TITLE
Pull-request slack bot: Ensure all our repos are being reported correctly

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#758]
The bot reports on open PRs in all repos which the 'WebOps' teams has access to.

Ensure all our repos are configured correctly, so that we see all the open PRs across our whole codebase.

**Comment by digitalronin** [comment]
Steve controls this? Ask him to do it.

**Comment by AntonyBishop** [comment]
@SteveMarshall grateful if you could point us in the direction of where we can find where the bot resides so we can make the suggested changes. Thanks.

**Comment by SteveMarshall** [comment]
The source for the bot is here: https://github.com/ministryofjustice/slack-prbot/, and it's running on the MOJ Heroku account, for which creds are in Rattic.

Per the [usage instructions](https://github.com/ministryofjustice/slack-prbot/#usage) in that repo:

> If you use the automated reminders then this will trigger a message which in turn will be sent to your bot.  But you can also perform manual queries by sending a channel message:
> 
>  * `open prs` - a default list of repositories
>  * `open prs in repo <x>` - queries a specific repository
>  * `open prs for team <x>` - queries all repos to which the team has access

Slackbot is currently configured to [remind](https://get.slack.help/hc/en-us/articles/208423427-Set-a-reminder) #cloud-platforms `Open prs for team webops`, meaning the bot will list [all repos for the GitHub team called `webops`](https://github.com/orgs/ministryofjustice/teams/webops/repositories). So: to remove things from the list it outputs, revoke that team's access, and to add them, grant that team access.

(Alternatively: set up a new `cloud-platform` GitHub team, grant it access where appropriate, and replace the notification with one for that… But I think that then also impacts how we do cluster admin auth, AWS auth, and more.)

**Comment by digitalronin** [comment]
Closed by https://github.com/ministryofjustice/slack-prbot/pull/15
