### ISSUE TITLE
Update (or kill?) the daily docs reminder slackbot

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#759]
If we want to keep announcing the docs, update the URL to the new one:

https://user-guide.cloud-platform.service.justice.gov.uk/

Or, if we decide to retire the bot, then do that.

**Comment by AntonyBishop** [comment]
Decision made to kill the bot and bot killed. Users ignore it as it is now just noise in the channel. A new feature of the guide that allows users to submit feedback would be more valuable and easier to use.
