### ISSUE TITLE
ATET-Deploy Configuration

### ISSUE THREAD

**Issue by cakeben** [ministryofjustice/cloud-platform#76]
## Service name

New Service: ET3

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

I'm trying to create a new service that is deployed from the ATET-Deploy repo. When deploying my container the nginx config for the URL doesn't create automatically. I was wondering whether someone could talk me through what I'm missing (this will be a template deploy thing)

## Problem description

""

## Contact person

bneill_hmcts

**Comment by kcbotsh** [comment]
Message sent to HMCTS team 31/05/18. Appears to be in conflict with hosting strategy.

**Comment by kcbotsh** [comment]
@SteveMarshall speaking to HMCTS sustaining team on 06/06/18. New services onto TD no longer accepted onto TD. Unlikely this work will be done

**Comment by kcbotsh** [comment]
Archiving this ticket. @SteveMarshall has agreed this is out of team scope
