### ISSUE TITLE
Guidance for inbound whitelisting

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#761]
## Background

We often get asked how to whitelist on the cluster in #ask-cloud-platform. To reduce requests we want to create an FAQ that explains to users how to do this.

We have created guidance for outbound IP whitelisting - https://user-guide.cloud-platform.service.justice.gov.uk/other-topics.html#ip-whitelisting

We should also add something about inbound whitelisting. i.e. how to whitelist the IPs from which an external system connects into your service on the cloud platform.

## Proposed user journey

A user is able to whitelist IPs on the cluster.

## Approach

This is creation of guidance that enables users to whitelist IPs

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/other-topics.html#ip-whitelisting

## Definition of done

- [ ] guidance added to FAQ section of the guide.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
This slack thread might have some helpful links: https://mojdt.slack.com/archives/C57UPMZLY/p1552910261282900

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/83

**Comment by pwyborn** [comment]
Pull request merged into master. Complete
