### ISSUE TITLE
Correct Namespace Annotations

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#768]
Need to go through all Namespaces owned by CP team and make sure all have been set up with the correct annotations and in environments repo. 

This is because all application monitoring for CP team is based on using the cloud_platform_justice_gov_uk_business_unit="cloud-platform" annotation. 

IMPORTANT: This also includes changing this annotation for namespaces which have variations of this i.e. Cloud-Platform, Cloud-platform, CP.

This ticket only applies to the "business-unit' annotation.

**Comment by vijay-veeranki-moj** [comment]
Gone through all the namespaces owned by CP team and all have been set up with the correct annotations and in environments repo.
