### ISSUE TITLE
Create an announcements slack channel

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#769]
#ask-cloud-platform is very noisy, and messages we post there will probably
not be seen by most service teams. So, if we have important information to
convey (e.g. the TLS config change we need all teams to make), then we need
some other way to ensure it gets noticed.

Done when:

- [x] We have a new slack channel (maybe '#cloud-platform-announcements')
- [ ] Only cloud-platform team members can post to the new channel (but anyone can join it)
- [x] We have communicated to all service teams' PMs that this is where we will make important announcements
- [x] We have communicated to the cloud platform team how this channel should be used.

**Comment by AntonyBishop** [comment]
As we are not Workspace admins we can't limit who can post to the channel. We will just have to police it and make it clear that only the Cloud Platform Team can post in the channel.
