### ISSUE TITLE
Whitelisting of Parole Board IPs for Intranet and PeopleFinder

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#77]
## Service name

Intranet and PeopleFinder

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [X ] Prod / Production
- [ ] Other

## Impact on the service

Parole Board users are currently unable to access MoJ Intranet and People finder. 

## Problem description

User at the Parole Board have recently migrated to Office 365 and as a result have new IP addresses. The IP addresses need to be white listed for Intranet and PeopleFinder.

Current Intranet team do not know how to add IP addresses and need assistance. As part of the work. The team would like some guidance on how to do this in future.

## Contact person

Kiera Poland, @Kiera, keira.poland@digital.justice.gov.uk

**Comment by AntonyBishop** [comment]
Blocked - awaiting confirmation of assistance from another team.

**Comment by AntonyBishop** [comment]
Unable to secure resource from Tactical Products. Will have to await Todd's return.

**Comment by tatyree** [comment]
I'm blocked waiting on the IPs that need to be whitelisted.

**Comment by tatyree** [comment]
See https://github.com/ministryofjustice/wp-cloudformation-params/pull/23 for a PR covering the instructions for updating the whitelist.

**Comment by tatyree** [comment]
Added to the moj-ip-addresses repo:

https://github.com/ministryofjustice/moj-ip-addresses/pull/21

Awaiting #security approval.

**Comment by tatyree** [comment]
Neither Ray nor Sunny are available to approve right now.  Adding `blocked` again while I wait to hear if Greg Smith is willing to do it in their absence.

**Comment by tatyree** [comment]
Waiting for approval for the Intranet changes.  Need to work out how to add it to Peoplefinder next.

**Comment by tatyree** [comment]
New IP has been promoted to intranet production.   Now working on getting it into People Finder.

**Comment by tatyree** [comment]
Blocked waiting on Keira to determine whether Parole Board should have admin or read-only access.  The discussion regarding this is in #ask-cloud-platform.

**Comment by tatyree** [comment]
After discussions with @jsugarman, decided to whitelist Parole Board in the read-only section.  Have branched, added and PR'd (https://github.com/ministryofjustice/pf-deploy/pull/103).  Awaiting PR signoff from @jsugarman before applying.

**Comment by tatyree** [comment]
Approved, merged and deployed to production.  Everything working.  I cannot confirm access from here.  Closing ticket and will re-open if Parole Board needs admin access or they cannot access.
