### ISSUE TITLE
Investigate Open Policy Agent

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#770]
## Background

We would like to enforce a number of policies on the cluster, such as safeguards around `Ingress` hostname usage: blocking `Ingresses` that use hosts already present in other `Ingress` resources and/or whitelisting domains per namespace.

## Proposed user journey

N/A
## Approach

Use OPA to try to enforce the above:
- https://github.com/open-policy-agent/opa
- https://github.com/helm/charts/tree/master/stable/opa

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] demo OPA and the policy language

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
completed working on it and Raised a PR: https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/242

This PR is to install OPA(open-policy-agent) using helm chart and create a ingress-conflicts policy.

This helm chart installs OPA as a Kubernetes admission controller. Using OPA, which can enforce fine-grained invariants over arbitrary resources in Kubernetes cluster.

Created a ConfigMap that contains the main OPA policy and default response. This policy is used as an entry-point for policy evaluations and returns allowed:true if policies are not matched to inbound data.

Created a policy ingress-conflicts that prevents Ingress objects in different namespaces from sharing the same hostname.

Also updated the default values in Helm chart to get the ingress-conflicts policy necessary permissions and resource access.
