### ISSUE TITLE
Adding external domains to MTP test cloud platform namespace

### ISSUE THREAD

**Issue by ushkarev** [ministryofjustice/cloud-platform#773]
## Service environment
- money-to-prisoners-test

## Description

https://user-guide.cloud-platform.service.justice.gov.uk/archive.html#using-an-externally-managed-hostname says we need to raise a ticket to request a `provider` name for creating certificates with certmanager. I want to test moving this environment in preparation for migrating the prod environment.

The domains in question are currently used by the old template-deploy system hence are in a different AWS account's R53.

What I really want to find out from this process is whether cloud-platform managed domains will be accessible from our users' machines (they use IE8 which in some cases does not support TLS+SNI).

Because if not, I *think* we might need to have ELBs added to support each domain separately.

**Comment by ushkarev** [comment]
Oh and another thing: how does this work with `*.service.gov.uk` domains?

**Comment by ushkarev** [comment]
our team has agreed on `*.prisoner-money.service.justice.gov.uk` as a replacement for our current `*.moneytoprisoners.dsd.io` domains

**Comment by mtrblmoj** [comment]
Hi @ushkarev, are we now able to close that ticket ? 
Were you able to confirm/test with your end-users ?

**Comment by ushkarev** [comment]
@mtrblmoj yeah you can close the ticket – it's point was to have the domains created. annoyingly, we still don't have confirmation about whether it'll work in IE8 (the default browser on Quantum machines). that's something we can handle separately.

**Comment by mtrblmoj** [comment]
Thank you.
