### ISSUE TITLE
Add SSH keys for Correspondence Tool

### ISSUE THREAD

**Issue by ollieanwyll** [ministryofjustice/cloud-platform#774]
This ticket is to add 2 users keys for the Correspondence Tool instances.

The two keys that need to be added are the last keys on these two users pages:
https://github.com/starswan.keys
https://github.com/mseedat-moj.keys

The Slack conversation is:
https://mojdt.slack.com/archives/C57UPMZLY/p1553518479424000

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/correspondence-tool-deploy/pull/53
Hi @Mo Seedat @Stephen Dicks - you should be able to ssh onto all of the correspondence-tool instances now - just going to look at correspondence-public now

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/correspondence-staff-deploy/pull/70
@Mo Seedat @Stephen Dicks - you should be able to ssh onto all of the correspondence-staff instances now. That should be everything now?

**Comment by kcbotsh** [comment]
@paul should this be closed now?

**Comment by pwyborn** [comment]
Thanks @karen - yes it should be closed now
