### ISSUE TITLE
Persistent storage example configs & documentation

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#775]
The formbuilder team have a requirement for some file storage for
their service. This would be used by their webserver process, and
should present as a normal filesystem.

It seems that a sensible way to do this would be via a PersistentVolume
and PersistentVolumeClaim, using EBS for storage. At this point,
it is not clear which of these would need to be configured in the
environments repo, and which in the formbuilder team's application
repo.

Whatever the answer to the above, we should create a working example
of a PersistentVolume and PersistentVolumeClaim that the formbuilder
team, and other teams, can use as a basis to build from.

### Definition of done

- [ ] We have an example of creating and using EBS-backed PVC
- [ ] We have a walkthrough in the user guide

**Comment by kcbotsh** [comment]
Please sit with Form builder team to review when this ticket is closed as part of the review

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/118

https://github.com/ministryofjustice/cloud-platform/pull/1021

https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/291
