### ISSUE TITLE
Migrate a test/demo application from Live-0 to Live-1 

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#779]
## Background

Live 1 is ready for production services to migrate to it. We have users on Live 0 that we want to migrate to Live 1.

We want to trial the migration process so that we are better informed to help users with their migrations.

## Proposed user journey

As a user I can migrate my product from Live 0 to Live 1.

## Approach

To help users we created a checklist for migration #662 .

We intend to carry out a dry run (maybe 3 times) of this checklist using the test app. We will review and iterate on this checklist.

We will then use this list as a basis for discussion with teams using Live 0 to plan their migration. We will prioritise services in Production (CLA, FALA and Fee Calculator)

## Which part of the user docs does this impact

We will be creating guidance as part of #662 

## Definition of done

- [ ] dry-run(s) completed
- [ ] we have identified changes to the checklist
- [ ] revisions to checklist made (we should test again after revisions)
- [ ] We have a revised checklist for migrations that we can use as a basis for migration planning discussions.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki-moj** [comment]
Completed dry-run, terraform module migration to be added in the checklist advising to use the latest modules when migration to live1.

**Comment by jasonBirchall** [comment]
App migrated from live-0 to live-1 following the documentation. No comments to add.
