### ISSUE TITLE
Webops team can login to concourse using github team authentication

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#78]
## Background

The current implementation provides user authentication to a list of github users that are provided in the `values.yml` file (e.g. https://github.com/ministryofjustice/concourse-CP/blob/master/concourse/values.yaml). 

We want to be able to provide a github team to concourse so that everyone in that team can authenticate to github rather naming a set of users individually. We can then manage team membership in github and those users will have access to our pipelines on concourse.

There is possibly a bug that is stopping this from working right now. @razvan-moj has the best view of what is not working here. 

## Done when

- [ ] We can specify that the webops team have access to concourse pipelines and each person in the team can then login and see the pipelines. 
- [ ] When we add a user to the webops team they can access our concourse pipelines 
- [ ] When we remove a user from the webops team they get removed from our repo

**Comment by razvan-moj** [comment]
FYI https://github.com/concourse/concourse/issues/2243

**Comment by kalbir** [comment]
I asked the GDS team about their issue that @razvan-moj references in the above. 

They said they have got around it by adding users manually, they have a couple of bits that show how they build their config:

https://github.com/alphagov/paas-bootstrap/blob/master/concourse/pipelines/create-bosh-concourse.yml#L1314-L1371

https://github.com/alphagov/paas-bootstrap/tree/master/manifests/concourse-manifest/github_auth

They put it down to the team not being public but @razvan-moj suspects this is not the case as he tried with a public team.

**Comment by razvan-moj** [comment]
Some more detail: the Github API does behave strangely with the MoJ org, because nested teams are not supported (although everybody uses them), see the note in https://developer.github.com/v3/teams/
As an example,
```
curl -s -H "Accept: application/vnd.github.v3+json" -H "Accept: application/vnd.github.hellcat-preview+json" -H "Authorization: token 123" https://api.github.com/orgs/ministryofjustice/teams | jq '.[] | .name, .id'
```
will not return WebOps in the list, but
```
$ curl -s -H "Authorization: token 123" https://api.github.com/user/teams | jq '.[] | .name,.id'
"WebOps"
345
```
and
```
$ curl -s -H "Authorization: token 123" https://api.github.com/teams/345/members | jq '.[] | select(.login | contains("razvan")) | .login,.id'
"razvan-moj"
678
```
Still, I used a separate free account, created an org and a visible team in it, same issue.

**Comment by razvan-moj** [comment]
Fixed, as discovered by @kerin the OAUTH creds must be owned by the org, and his commit https://github.com/ministryofjustice/concourse-CP/commit/e9e997da2bb7e1885632110afa67fc7de302b20a adds those in
