### ISSUE TITLE
Add external role to bucket policy

### ISSUE THREAD

**Issue by s-block** [ministryofjustice/cloud-platform#780]
## Service name

HMCTS

## Service environment

S3 Bucket

## Impact on the service

We need to send data from the MOJ analytical platform to an s3 bucket in MOJ cloud platform. We would prefer not to use the access key/secret as this will be accessed/written from an automated job which assumes role and doesn't have access to secrets.

## Problem description

We need to grant an external IAM role from moj-analytical-services AWS account access to read/write an s3 bucket in clout platform. 

External IAM role arn: `arn:aws:iam::593291632749:role/airflow_viper_to_external`

Cloud platform bucket arn: `arn:aws:s3:::cloud-platform-911c893e32afaa59f26d922be89f875a`

## Contact person

Josh Rowe (slack: josh)

**Comment by alkar** [comment]
This has been implemented and tested.
