### ISSUE TITLE
Enable running nginx, to serve static content, without needing root privileges

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#782]
Teams often need to run nginx, as part of their services, in order to serve
static content.

The default nginx docker image, which many people use, expects to run as root.
This violates our pod security policy on live-1, so such containers will not
run.

This ticket is to find a way to run nginx containers, to serve static content,
without needing nginx to run as root.

**Comment by alkar** [comment]
Recommendation added in https://github.com/ministryofjustice/cloud-platform-user-guide/pull/79
