### ISSUE TITLE
PVB2 staging build failing - Jenkins

### ISSUE THREAD

**Issue by KPobeeNorris** [ministryofjustice/cloud-platform#784]
## Service name

Prison Visits Staff (PVB2)

## Service environment

- [ ] Dev / Development
- [X] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

We are unable to deploy to staging, and therefore unable to deploy to production. We have slot updates for prisons that we need to deploy as incorrect times will impact visitors' ability to book visits.  

## Problem description

PVB2 staging builds are failing on Jenkins (template deploy); full details can be seen here https://ci.service.dsd.io/view/PVB2/job/deploy-pvb2-staging/468/console.  
Screenshot: <img width="1262" alt="Screen Shot 2019-04-01 at 08 52 14" src="https://user-images.githubusercontent.com/20423761/55311683-7c8ec800-545b-11e9-8bbd-3fb971fb3f2a.png">

## Contact person

Slack -> @kath.pobee-norris

**Comment by digitalronin** [comment]
It looks like this last worked on 28/03/19 https://ci.service.dsd.io/view/PVB2/job/deploy-pvb2-staging/466/
What's changed since then?

Also, this seems like it might be related to this issue: https://github.com/saltstack/salt/issues/15616
Are you able to modify the template deploy code to use `salt.utils` instead of `__salt__`?

**Comment by KPobeeNorris** [comment]
Thanks for looking into this @digitalronin.  The only thing merged in this morning was a Dependabot update for one of our test related dependencies (Capybara), so can't see that having much of an impact. I merged in the same update for our public facing PVB app this morning and that built/deployed to staging without issue.  

I've just had a look at both the PVB Staff( PVB2) and Public deployment repos and can see references to both `__salt__` & `salt.utils`. As the Public app is deploying without issue I wonder if something else might be causing the issue?

**Comment by KPobeeNorris** [comment]
Also, to be honest we've never maintained the deployment scripts themselves, just managed the contents of the secrets file. So, whilst not wanting to shy away from any work, we also have no insight into how it works.  If memory serves me right we've usually had help from Raz or Lukasz in the past when it comes to this type of failure.

**Comment by lukaszraczylo** [comment]
```Error pulling image (master.89db541) from registry.service.dsd.io/pvb, failed to register layer: Error processing tar file(exit status 1): mkdir /usr/src/app/tmp/cache/assets/sprockets/v3.0/iO: no space left on device```

**Comment by lukaszraczylo** [comment]
Cleanup done, on both staging servers and docker registry(x2)

**Comment by TobyRet** [comment]
@lukaszraczylo - builds have failed again from 8.23am for the same reason 
https://ci.service.dsd.io/view/PVB2/job/deploy-pvb2-staging/
```
08:27:03 [52.214.168.12] out: NameError: global name '__salt__' is not defined
08:27:03 [52.214.168.12] out: [INFO    ] Log opened: Tue Apr  2 08:26:49 2019 UTC
08:27:03 [52.214.168.12] out: [INFO    ] Found elasticache engine 'redis' with group id 'pve1ls67twclcoo1'
08:27:03 [52.214.168.12] out: [INFO    ] Loading fresh modules for state activity
08:27:03 [52.214.168.12] out: [INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://top.sls'
08:27:03 [52.214.168.12] out: [INFO    ] Syncing grains for environment 'base'
08:27:03 [52.214.168.12] out: [INFO    ] Loading cache from salt://_grains, for base)
08:27:03 [52.214.168.12] out: [INFO    ] Caching directory '_grains/' for environment 'base'
08:27:03 [52.214.168.12] out: [INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://_grains/ec2_neighbours.py'
08:27:03 [52.214.168.12] out: [INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://_grains/elasticache.py'
08:27:03 [52.214.168.12] out: [INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://_grains/elb_lbs.py'
08:27:03 [52.214.168.12] out: [INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://_grains/tags_to_grains.py'
08:27:03 [52.214.168.12] out: [INFO    ] Copying u'/var/cache/salt/minion/files/base/_grains/ec2_neighbours.py' to u'/var/cache/salt/minion/extmods/grains/ec2_neighbours.py'
08:27:03 [52.214.168.12] out: [INFO    ] Copying u'/var/cache/salt/minion/files/base/_grains/elasticache.py' to u'/var/cache/salt/minion/extmods/grains/elasticache.py'
08:27:03 [52.214.168.12] out: [INFO    ] Copying u'/var/cache/salt/minion/files/base/_grains/elb_lbs.py' to u'/var/cache/salt/minion/extmods/grains/elb_lbs.py'
08:27:03 [52.214.168.12] out: [INFO    ] Copying u'/var/cache/salt/minion/files/base/_grains/tags_to_grains.py' to u'/var/cache/salt/minion/extmods/grains/tags_to_grains.py'
08:27:03 [52.214.168.12] out: local:
08:27:03 [52.214.168.12] out:     ----------
08:27:03 [52.214.168.12] out:     zero_downtime_deploy:
08:27:03 [52.214.168.12] out:         False
08:27:03 [52.214.168.12] out: 
08:27:03 
08:27:03 
08:27:03 Fatal error: One or more hosts failed while executing task 'run_deploy'
08:27:03 
08:27:03 Aborting.
08:27:03 Build step 'Execute shell' marked build as failure
08:27:04 [ERROR] HipChat notification failed with error message: Unexpected IO error occurred while sending notification: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
08:27:04 Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
08:27:04 Finished: FAILURE
```

**Comment by lukaszraczylo** [comment]
It was _one_ build which failed ( at 0822 ), probably due to connectivity issues, all the following ones you've triggered ( 0827, 0921, 0931 ) worked just fine.

**Comment by pwyborn** [comment]
New instance brought into auto-scaling group + highstate. Got rid of offending instance - https://ci.service.dsd.io/view/PVB2/job/deploy-pvb2-staging/478/consoleFull
May have been a network glitch anyway.
Anyway all well now
