### ISSUE TITLE
Kuberos token expiration

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#786]
## Service name

Kuberos/Auth0 in Live-1. After authenticating to the cluster users @rossjones, @ushkarev and others are finding their certificates/tokens are expiring within a day or two. This is not intended behaviour.   

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Although effected staff are able to re-authenticate, this becomes a blocker when trying to call the kube api. 

## Problem description

- Post authentication, after a day or two users receive an error message:
```
Error from server (Forbidden): pods is forbidden: User "https://justice-cloud-platform.eu.auth0.com/#rossjones" 
cannot list pods in the namespace "offender-management-production"
```

## Contact person

@rossjones

**Comment by ushkarev** [comment]
yup, this happens to me daily. can't provide any more details really… i log into live-1 in exactly the same way as i had logged into live-0.

**Comment by ushkarev** [comment]
my live-1 token seems to have expired again… it lasted longer this time! less than a week though
