### ISSUE TITLE
Correspondence Tool Nginx configuration out of date - traffic not routing through?

### ISSUE THREAD

**Issue by mseedat-moj** [ministryofjustice/cloud-platform#788]
## Service name
Correspondence Staff Tool (Development)

https://github.com/ministryofjustice/correspondence_tool_staff

## Service environment

- [X] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service
Application is not accessible on DEV environment (latest version):

https://dev.track-a-query.service.justice.gov.uk/
(currently rolled back to last known good version, latest master causes 503 service unavailable error).

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Cannot demonstrate latest work to users.

## Contact person
Mohammed Seedat (Slack Mo Seedat)

**Comment by mseedat-moj** [comment]
<img width="363" alt="Screen Shot 2019-04-02 at 13 12 57" src="https://user-images.githubusercontent.com/47113046/55401574-17b19b80-5549-11e9-923f-d6d7070b54c4.png">

Conversation regarding OLD nGinx config causing potential problem

**Comment by razvan-moj** [comment]
Fixed for all environments with an edit in https://github.com/ministryofjustice/correspondence-staff-deploy/tree/master/salt/moj-docker-deploy/apps/templates and `fab update`
