### ISSUE TITLE
After 1st May, remove Kerin's admin account on mojds-platform-integration

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#789]
I've reinstated Kerin as an admin on this AWS account, so that he can
experiment with VPN connectivity into a test cluster.

Check after 1st May and, if he doesn't need the account anymore, remove his
access.

### Definition of done

  - [ ] KerinCosgrove removed from Admin group
  - [ ] KerinCosgrove added to suspended users group
  - [ ] KerinCosgrove no longer has console access enabled

**Comment by lukaszraczylo** [comment]
Can't find mentioned account in the AWS account, so access was completely deleted I presume.
