### ISSUE TITLE
Access for new developer to FALA/CLA

### ISSUE THREAD

**Issue by exonian** [ministryofjustice/cloud-platform#794]
## Service name
FALA/CLA team

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

None

## Problem description

Please could you set me up with the following?

### AWS Access
 - [x] moj-cla-dev (https://moj-cla-dev.signin.aws.amazon.com)
 - [x] moj-laalaa aws (https://moj-laalaa.signin.aws.amazon.com)

### SSH Access
 - [x] SSH access to all fala environments
 - [x] SSH access to all cla_backend environments
 - [x] SSH access to all cla_frontend environments
 - [x] SSH access to all laa-legal-aid-advisers environments

### Monitoring
 - [x] Login for https://sentry.service.dsd.io/mojds/
 - [x] Added to the appropriate Sentry projects

## Contact person

Slack: @michaelblatherwick 
Email: michael.blatherwick@digital.justice.gov.uk

**Comment by digitalronin** [comment]
@exonian For Sentry access, you need to ask in the #digitalservicedesk slack channel.

**Comment by digitalronin** [comment]
@exonian Also, most access to resources is controlled via github teams within the ministryofjustice organisation, so you should use the "request to join" button on the relevant pages, e.g. 
https://github.com/orgs/ministryofjustice/teams/laa-apply-for-legal-aid/members

**Comment by exonian** [comment]
@digitalronin I'm in https://github.com/orgs/ministryofjustice/teams/laa-get-access but I don't know how that helps me with the above, like access to the AWS console. Could point me in the right direction for that at all?

**Comment by digitalronin** [comment]
@exonian We (the cloud platform team) don't manage those AWS accounts. I assume it must be someone in the relevant departments, but I'm afraid I don't know who. Best bet is to ask in your team to find out who is in control.

**Comment by exonian** [comment]
@digitalronin Ah ok. I took the issue example from my team's onboarding docs, but something must have changed since they were written. Thanks

**Comment by rowlando** [comment]
@digitalronin 

Here's a previous, similar request - https://github.com/ministryofjustice/cloud-platform/issues/484

It was done by @pwyborn.

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cla_frontend-deploy/pull/95
https://github.com/ministryofjustice/cla_backend-deploy/pull/95
https://github.com/ministryofjustice/fala-deploy/pull/35
https://github.com/ministryofjustice/laalaa-deploy/pull/43

**Comment by exonian** [comment]
Brilliant, thanks @pwyborn

**Comment by pwyborn** [comment]
In adding Michael - it removed Said - as we was not part of github cla team - added him - now rerunning everything
