### ISSUE TITLE
Better nginx ingress controller fallback templates

### ISSUE THREAD

**Issue by ushkarev** [ministryofjustice/cloud-platform#796]
## Service name

This is not service-specific

## Service environment

This is not environment-specific

## Problem description

Not a high priority by any means, but I think it'd be great to improve the page templates the nginx ingress controller returns in the case of not finding a backend and if the request is forbidden based on IP address white-listing.

There does not appear to be a way to instruct the ingress controller to use a custom template in these two cases, but I think users who've somehow landed there ought to get something a little more helpful. Ideally, it'd be great to have this customisable with ingress annotations.

E.g. some of our apps use IP white-listing and it would be better to say something like "This service is only accessible from DOM1 or Quantum networks." than "Forbidden".

I expect this would have to be an extension to the nginx ingress controller…

**Comment by ushkarev** [comment]
It seems that this is doable if we don't want ingress-specific templates:
https://kubernetes.github.io/ingress-nginx/examples/customization/custom-errors/

**Comment by AntonyBishop** [comment]
Also needed for Formbuilder which has raised the priority. Automated pages for error messages e.g. 404

**Comment by sid234** [comment]
@ushkarev could you mention the wording you are expecting when it is unreachable?

**Comment by ushkarev** [comment]
@sid234 ideally, it'd be up to the service to determine their own via templates in the environments repo! does the default backend get any information that'd allow it to choose something intelligently?

**Comment by sid234** [comment]
I would suggest a default template that provides generic information if the user is accessing the ingress from an external network. if it is an internal user, then we could provide more details. 
ideally we would not want to display details of the type of network we use when the user connects from the outside 
the default backend does get a set of headers from the ingress https://kubernetes.github.io/ingress-nginx/user-guide/custom-errors/

**Comment by ushkarev** [comment]
yeah i think a generic page is definitely a good start. from above, it sounds like the formbuilder team might have an idea of what needs to go there.

but just to clarify, _can_ the default backend tell which ingress it was that the user ended up hitting? the use case i'm thinking of is to do with our ip whitelisting. just getting "forbidden" is not helpful, but since the correct ingress was hit, can whatever it is that served the forbidden message serve something else instead that's specific to that ingress? that way our service would say "use DOM1 etc." but another service would attach something else to their ingresses if they want.

**Comment by sid234** [comment]
I looked at ingress-nginx custom-http-errors and looks like it can pass certain header information (like url, service name, namespace of the service etc) to the default-backend. though it is possible to have custom error messages specific to each service namespace, It doesn't have source IP. so I don't think the default-backend can identify source IP from the http-header information. maybe use a waf before the ingress? the "dom1" specific custom message requires arch redesign and need to see if this is a priority for business, analyse the risk etc. 

as you had said, it would be interesting to see what the form-builder team would like out of the custom-error page. "The page you're looking for could not be found. " is the default custom-error page

**Comment by ushkarev** [comment]
this is a slightly different issue from having the default backend respond because the ingress controllers and services couldn't route the request.

the default backend doesn't need to know the user's ip address. our ingresses already has filtering in place. what i'm imagining is just that _our service’s_ ingress controllers could serve special templates rather than nginx's generic ones.

at the moment, if you're not on the pre-set networks, you get:
```
403 Forbidden
nginx
```

i'd prefer that we could show something more like:
```
In order to access this site, you need to be on XXX network.
```

i get that this is a special case and likely not a priority! i don't know if this is possible with the nginx ingress controller without extending it.

**Comment by sid234** [comment]
I will dig further, discuss with team and get back to you about this scenario
