### ISSUE TITLE
Analytical platform domain

### ISSUE THREAD

**Issue by sh31** [ministryofjustice/cloud-platform#797]
## Service name

Analytical Platform

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Hosted zone created in the Analytical Platform account for `analytical-platform.service.justice.gov.uk`.

NS record to be created in the `service.justice.gov.uk` hosted zone with the following value:

`ns-1954.awsdns-52.co.uk.
ns-305.awsdns-38.com.
ns-1496.awsdns-59.org.
ns-706.awsdns-24.net.`

Cnames for the following to point to `analytical-platform.service.justice.gov.uk`:
`analyticalplatform.service.justice.gov.uk`
`analytical_platform.service.justice.gov.uk`
`ap.service.justice.gov.uk`

## Contact person

Slack: Serj or mikael

**Comment by razvan-moj** [comment]
done, records added manually in DSD
