### ISSUE TITLE
Create Route53 zone terraform module

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#798]
## Background

Connects to #783

As part of our work to provide custom domains for applications and properly manage them, we've agreed to develop a terraform module for users to be able to create zones, as part of their service's resources.

## Proposed user journey
As a user, I want to be able to create a Route53 zone for my service, in the same way I can create an RDS instance or an S3 bucket.

## Approach
Develop a terraform module that creates a Route53 zone and returns the NS records for its authoritative servers.

Initially, we only want to support new zones under the following parent zones:
- `*.service.gov.uk`
- `*.service.justice.gov.uk`

TBC:
- ~whether we automate the setup of NS records in the parent zones where possible~ we've agreed that NS records are going to be setup manually for now - out of scope

- ~how we restrict domains~ we do not have to restrict domains since we will manually update parent zones with NS records (and also, new zones are requested through a PR we review)

## Which part of the user docs does this impact

We will need to write a document on how a user can create a zone and the follow-up steps (where required) set it up.

## Questions / Assumptions

Moving forward, any zones we create for services will be managed through our main cloud-platform account.

To reduce the scope, this new route53 zone module does not need to be compatible with our `live-0` cluster.

## Definition of done

- [ ] the `cloud-platform-terraform-route53-zone` module has been created and includes example and documentation
- [ ] a new, user-oriented document is created which explains how zones are managed on the new platform
- [ ] internal documents are updated for handling relevant support requests, if applicable

## Reference
N/A

**Comment by vijay-veeranki-moj** [comment]
user-docs updated Creating a Route 53 Hosted Zone, as a team decided to not create a module but provide guidance how to create terraform resource for Route 53 Hosted Zone.

https://github.com/ministryofjustice/cloud-platform-user-guide/pull/82
