### ISSUE TITLE
Add "support" label as part of issue template for support requests

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#80]
## Background 

Issues are not getting pushed into the waffle board support queue as when they are created they do not have the support label. 

Support requests have an issue template (you can find it in the `cloud platform` repo). If we add the support label to the template then they will go into the correct column in waffle.

**Comment by lukaszraczylo** [comment]
Issues have 'support team' label applied automatically. We have updated the support request link to add that label automatically. Has the label requirement changed?

**Comment by kalbir** [comment]
They don't have the support label if they are created through the template -- I think maybe templates don't support adding labels as a feature?

**Comment by lukaszraczylo** [comment]
Templates don't have that feature - they're simple markdown files, that's why I have created the "short url" to apply template and labels automatically to avoid confusion and shorten user journey ( and things users need to remember )

**Comment by kalbir** [comment]
Yep, that’s what I was suspecting. The only problem is sometimes people go
straight to the repo and create an issue from there, bypassing the short
link. In that case it doesn’t get labeled.

I think the best option for that is to keep an eye on the channel where the
tickets get created and add the label when we see a new one?


On 31 May 2018 at 10:48:45, Lukasz Raczylo (notifications@github.com) wrote:

Templates don't have that feature - they're simple markdown files, that's
why I have created the "short url" to apply template and labels
automatically to avoid confusion and shorten user journey ( and things
users need to remember )

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ministryofjustice/cloud-platform/issues/80#issuecomment-393477504>,
or mute the thread

**Comment by lukaszraczylo** [comment]
Agree. Closed the ticket with hope that our users will use provided link :)
