### ISSUE TITLE
Confirm we can resize an RDS instance via Terraform

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#800]
This is to answer a question from the MTP team.

### Definition of done

 - [ ] Create an RDS instance via Terraform
 - [ ] Add some data
 - [ ] Change the amount of storage, in the terraform code
 - [ ] Confirm that the database storage has increased
 - [ ] Confirm that the test data is still present (i.e. the database has not just been nuked and a bigger one created)

**Comment by AntonyBishop** [comment]
In support of MTP migration activities.
