### ISSUE TITLE
Fix CPUThrottlingHigh prometheus alert

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#801]
This alert is triggering all the time. It's unclear what it's trying to tell us, and whether we should be concerned or not.

This is causing concern to service teams (e.g. MTP), who do not understand whether or not it indicates a genuine problem.

### Definition of done

 - [x] We understand what this alert is telling us
 - [x] The alert is only firing when we actually need to take action.

The second part may be achieved by any combination of the following, depending on our understanding of what the alert is trying to tell us:

 * Deleting the alert altogether
 * Adjusting the alert parameters to better indicate a problem we actually care about
 * Changing the cluster resources so that the alert doesn't fire anymore

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/74

**Comment by ushkarev** [comment]
so the guide implies to me that our cpu throttling alert might be because of low cpu limits… is that right? but the app that's alerting in our namespace has a very constant usage of 0.02 (with request of 0.18 and limit of 0.5). i'm not sure what to change to make it not alert. surely not to _decrease_ it's cpu request or limit?

**Comment by sablumiah** [comment]
This alert can be a bit misleading in regards to there is not necessarily a problem that needs addressing especially if the throttling is not causing user errors or application problems. This alert just shows that throttling happened which is not always an issue. Its recommended that in this case you lower your request to closer to the actual usage (in your case its 9 times higher than average usage) and increase the limit based on how much is used during usage spikes. You could try just a limit increase first? Unfortunately it seems CFS is quite harsh and triggers a lot on the CPU usage of most of the applications in our cluster where average usual is quite low but has usage spikes where it has to throttle incase all applications require the limit (or want to go over) all at once.
