### ISSUE TITLE
Matthew Rudy needs access to Sentry

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#81]
## Service name

Architecture

## Service environment

- [ ] Dev / Development
- [ x] Staging
- [ x] Prod / Production
- [ ] Other

## Impact on the service

Stops him from helping teams diagnose their production issues. 

## Problem description

Matthew Rudy needs acces to sentry prod and staging. 

## Contact person

@matthewrudy on slack (and github)

**Comment by jasonBirchall** [comment]
Access granted but there appears to be an issue with the the email services. Creating a separate ticket.
