### ISSUE TITLE
Update the support labelling app with a new token

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#812]
## Background

We have an app that labels support issues. It currently uses a personal github token.

## Definition of done

- [x] replace that token with one from a machine user
- [x] if possible, version control it the token

**Comment by jasonBirchall** [comment]
As part of this ticket I felt it was appropriate to migrate the app and registry to to live-1. 

Environment created here:
https://github.com/ministryofjustice/cloud-platform-environments/tree/master/namespaces/live-1.cloud-platform.service.justice.gov.uk/support-labelling-webhook

ECR here:
https://eu-west-2.console.aws.amazon.com/ecr/repositories/webops/support-labelling-webhooks/?region=eu-west-2

Repository here: 
https://github.com/ministryofjustice/cloud-platform-support-labelling-webhook/tree/migrate/live-1

New GitHub access token created in the robot account `cloud-platform-moj` and added as a k8s secret. The secret needs base64 encoding (sorry!).

The oauth web app was created and repointed here:
https://github.com/ministryofjustice/cloud-platform/settings/hooks/54408506

This has been tested but not working. Passing over to colleague to investigate whilst I'm on leave.

**Comment by razvan-moj** [comment]
the token must have been wrong, as when copying the one from live-0 the update works

**Comment by jasonBirchall** [comment]
Raz has confirmed this work was complete and the app is now working. Closing issue.
