### ISSUE TITLE
Automate the removal of unused, empty namespaces

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#813]
We have a process we ask developers to follow, when they have finished with a namespace:

https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#cleaning-up

At the end of this process, there should be no AWS resources associated with the namespace, and no kubernetes objects within it, and the folder which defines the namespace will have been removed from the cloud-platform-environments repository.

The final step is for a member of the cloud platform team to manually delete the namespace from the cluster, but in practice this rarely happens.

Instead of relying on a manual intervention, this ticket is to automate the process of detecting and removing namespaces which are no longer used by creating a tool to identify and delete them on a regular basis. If the tool were to mistakenly delete a namespace containing a live service, the consequences would be significant. So we need to take the development of this tool seriously, and make sure that never happens.

### Definition of done

 - [ ] We have a tool which, when invoked, identifies namespaces which meet all the following conditions:
         * The namespace is empty (i.e. contains no kubernetes objects). [This issue comment](https://github.com/kubernetes/kubectl/issues/151#issuecomment-402003022) might be relevant/useful
         * There is no matching namespaces/live-1.cloud-platform.service.justice.gov.uk/[namespace] folder in the [env repo](https://github.com/ministryofjustice/cloud-platform-environments)
 - [ ] The tool has a suite of unit tests which ensure that it does not affect non-empty namespaces, or those with a defining folder in the env repo
 - [ ] The tool reports its actions in the \#cloud-platform slack channel
 - [ ] The tool is documented in the main cloud platform repository (this could be a link to the README in the tool's own repository), including how it can be upgraded to a later version, and how it can be disabled
 - [ ] The tool is invoked periodically in the live cluster (once per week?)

**Comment by vijay-veeranki-moj** [comment]
This task will be covered in #813 
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/813

**Comment by jasonBirchall** [comment]
Closing this issue - please see #710
