### ISSUE TITLE
Cloud Platform Support Runbook

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#814]
## Background

All services should have runbooks so that people know how to get in touch with the team supporting it when something goes wrong.

At present the Cloud Platform has this information documented in two places in two different formats:
1. [Cloud Platform operational processes](https://github.com/ministryofjustice/cloud-platform/blob/c84adcb5eaabd36a131d564a502d87d1191df9a2/docs/INFO-our-ops-processes.md)
2. [Cloud Platform Support](https://docs.google.com/document/d/1M89TXQJIQAqu8yb2wzatlI8PgsXrgOi-GxLtB76XgjU/edit?usp=sharing)

We want to combine these documents so that we have a single runbook that explains to users what we support, how they access the support and how we will deliver that support.

## Proposed user journey

A user is easily able to find our support process documentation via runbook. The user can understand what support is available and how to access support via a single runbook.

## Approach

Combine existing documents into a single support document. Tony is happy to help work on content.

## Which part of the user docs does this impact

We already reference Cloud Platform Support in the user guide. The runbook would replace that.

## Questions / Assumptions

Our runbook for follow the style as set by [Document our standard for service runbooks](https://github.com/ministryofjustice/technical-guidance/pull/53#pullrequestreview-225497718)

## Definition of done

- [x] Our support processes is documented in a single runbook
- [ ] Reviewed by Tony
- [ ] Publish Runbook for the user guide
- [ ] Communicate runbook via the #cloud-platform-update slack channel

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveMarshall** [comment]
@AntonyBishop Please don't start work on this till [the standard is merged](https://github.com/ministryofjustice/technical-guidance#53)!

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/125/
