### ISSUE TITLE
Automate regular 'kops update'

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#817]
[This is a placeholder ticket. Please fill in more details, Mitch]

We planned to (manually) run `kops update` every week. AFAIK, this isn't happening.

Instead, let's automate this so that it runs every week (or however often we think is appropriate) and tells us what it did.

**Comment by AntonyBishop** [comment]
We are looking to move away from Kops so this need my disappear. Keep in the icebox as low priority.
