### ISSUE TITLE
CLA-PUBLIC -  Cloud Formation Stack deletion

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#819]
## Service name

Cloud Formation Stack - deletion

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ x] Prod / Production
- [ ] Other

## Problem description

On Monday 15th April 2019, we will be removing the following production cloud formation stacks as we have migrated from AWS to Kubernetes. Cloud platform will need to be available to help with any issues that may arise:

- [ ] cla-public-prod-2e49f9ce
- [ ] CLA-public-prod-monitoring

## Contact person
Slack: [at]Said
Slack channel: [#]cla-traffic-split

**Comment by sldblog** [comment]
This is now completed.

**Comment by vijay-veeranki-moj** [comment]
Comments show as completed so moved to done.
