### ISSUE TITLE
Parliamentary Questions app is rendering without any css styling.

### ISSUE THREAD

**Issue by njpreddy** [ministryofjustice/cloud-platform#820]
## Service name

Parliamentary Questions

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production
- [ ] Other

## Impact on the service

Users are finding the service unuseable.

## Problem description

Parliamentary Questions app is rendering without any css styling in Prod, Dev and Staging.

## Contact person

@nick.preddy

**Comment by jabley** [comment]
https://trackparliamentaryquestions.service.gov.uk/assets/fonts-a5aa57b6ceaab0b585d834d1d78e46d8b76dd3f80502da205736cdd3060b9b86.css is returning a 403, for example.

**Comment by sid234** [comment]
it was caused due to the new feature of s3 - prevent public acls to be added to private s3 buckets. It was applied to the buckets as part of baseline controls. The change has been reverted on the buckets hosting the site. sorry for the impact it has caused
