### ISSUE TITLE
Correct Naming in RDS Module

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#822]
## Background
To allow RDS monitoring and alerting we need a proper naming structure for the RDS instances we create via [module](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/master/main.tf). 

The overall target is to allow users to create Prometheus rules to monitor their RDS instances. At the moment this is very difficult due to the RDS [naming](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/blob/master/main.tf#L23).

We need to change this naming convention to allow easily recognizable and searchable names.  

## Proposed user journey
Fundamentally, a user needs to be able to write Prometheus rules for their RDS instances. Things like `write latency` etc.

## Approach

Ensure RDS naming convention is defined by the RDS module. 

## Which part of the user docs does this impact

Module documentation and any additional user-guides. 

## Questions / Assumptions
N/A

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Needs discussion/breaking down in planning
