### ISSUE TITLE
Add "How to alert on RDS failure" in User-Guide

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#824]
## Background
This ticket relies on the RDS names being changed and the addition of CloudWatch to Prometheus exporter.

Basically, we need documentation to show a developer how to trigger an alert on an RDS instance failure or something similar.  

## Proposed user journey
As a Developer I can search the user guide to see how to setup RDS triggered alerts.

## Approach
Write a 'how to' task explaining how to alert on an RDS outage.

## Which part of the user docs does this impact

N/A

## Questions / Assumptions
We have searchable RDS names.
We have the Cloudwatch exporter enabled in live-1.

## Definition of done
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mtrblmoj** [comment]
waiting for user feedback
