### ISSUE TITLE
Custom URL request - data-capture-service.uat.claim-criminal-injuries-compensation.service.justice.gov.uk

### ISSUE THREAD

**Issue by ross75** [ministryofjustice/cloud-platform#825]
## Cloud Platform

URL

## 

- [x ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description

Hi, I'm trying to get a custom url for my app. I need to be able to access it on:

data-capture-service.uat.claim-criminal-injuries-compensation.service.justice.gov.uk

The app is currently up and running on the cluster but it is accessible on:

data-capture-service.uat.claim-criminal-injuries-compensation.apps.live-1.cloud-platform.service.justice.gov.uk

I need to drop the …..apps.live-1.cloud-platform.... from the url

I understand that you will provide the certificate provider name and I will update the ingress file and a certificate yaml.

## Contact person

Ross Callaghan
@rosscallaghan
ross.callaghan@cica.gov.uk

**Comment by pwyborn** [comment]
paulwyborn [12:03 PM]
Hi Ross. I am looking at your ticket
```https://waffle.io/ministryofjustice/cloud-platform/cards/5cb5fa47adeca3051dd6391f```
. Think you are following the instructions here
```https://user-guide.cloud-platform.service.justice.gov.uk/archive.html#using-an-externally-managed-hostname```
?
If you are using the host name in our CP account - then the provider is “route53-cloud-platform”

paulwyborn [12:10 PM]
Does this help you Ross - going forward?

**Comment by pwyborn** [comment]
rosscallaghan [24/04/2019 10:36 AM]
Hi Paul, i think that's what I need. So to get my custom url for this file I just follow the instructions in the link, create a certificate.yml and change the ingress file?

paulwyborn [24/04/2019 10:39 AM]
Yes sure - thanks Ross - if you follow the instructions you should be ok. If you get any problems - go to the #ask-cloud-platform channel

**Comment by razvan-moj** [comment]
done, hostname&cert created
