### ISSUE TITLE
Fix terraform fmt check

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#826]
## Background

We have a CircleCI job running `terraform validate` as a check for incoming pull requests in `cloud-platform-environments`. This seems to check the entire repository, as opposed to the terraform folders where files have been changed. As a result we've had the following situation:

- [#641](https://github.com/ministryofjustice/cloud-platform-environments/pull/641) introduces [the error](https://github.com/ministryofjustice/cloud-platform-environments/pull/641/files#diff-743101741448442567519a7d78724003R1) and the validate check seems to not have ran against it
- [#647](https://github.com/ministryofjustice/cloud-platform-environments/pull/647) is blocked because of the previously introduced error
- [#648](https://github.com/ministryofjustice/cloud-platform-environments/pull/648) is the hotfix

We have a way of determining the changed files, used in the plan script in `cloud-platform-environments` which can be reused here.

## Proposed user journey
As a user, I want the check to only look into files I have changed.

## Definition of done

- [ ] the validate test only applies against files modified by the PR (or, the entire directories) but not against the entire repo

**Comment by vijay-veeranki-moj** [comment]
Applied changes similar to plan pipeline where it will run Terraform format and validation check only on the changes been made.

https://github.com/ministryofjustice/cloud-platform-environments/pull/745
