### ISSUE TITLE
Fix - #cloud-platform-jira slack channel is not receiving notifications when issues are opened or closed

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#827]
## Service name

#cloud-platform-jira slack channel

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Unable to receive notifications when issues are opened or closed.

## Problem description

There have been no slack notification to the #cloud-platform-jira slack channel since 3rd April.

Investigate why notifications have stopped and fix the problem.

We may also want to rename the channel as we don't use jira anymore. Maybe call it #cloud-platform-issues?

Key thing is to get notifications going again.

## Contact person

Tony or Karen

**Comment by pwyborn** [comment]
As per standup dropping this ticket
