### ISSUE TITLE
Fab update failed (AWS Cloud Formation 403) 

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#837]
## Service name
Prison Visits 2

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Unable to make template deploy configuration changes

## Problem description

Whitelist settings were recently updated. See - https://github.com/ministryofjustice/pvb2-deploy/pull/227

When I deploy the changes using 
`fab -u TobyRet aws:mojdsd application:pvb environment:staging config:./cloudformation/pvb2.yaml passwords:./cloudformation/pvb2-secrets.yaml update:fraction=0.1`

I get a 403 error
```
  File "/Users/tobyretallick/.virtualenvs/pvb2-deploy/lib/python2.7/site-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidClientTokenId</Code>
    <Message>The security token included in the request is invalid.</Message>
  </Error>
  <RequestId>1847caf4-6730-11e9-bb41-b78ea32b65d0</RequestId>
</ErrorResponse>

```

## Contact person

Toby Retallick

**Comment by razvan-moj** [comment]
fixed by using https://github.com/ministryofjustice/template-deploy-jump
```Disconnecting from 52.48.35.90... done.
Disconnecting from 34.252.55.81... done.
Disconnecting from 52.214.168.12... done.```
