### ISSUE TITLE
Delete Ollie's Accounts

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#838]
## Background

Delete Ollie's Accounts

## Approach

Follow leavers process.

## Definition of done

- [x] Accounts closed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
See https://docs.google.com/document/d/1HbV1zivEJHxZr_t-a0d-vaQXjnKYACPJMQTbx1PSg_M/edit All accounts closed
