### ISSUE TITLE
ECR lifecycle policy expiration

### ISSUE THREAD

**Issue by ushkarev** [ministryofjustice/cloud-platform#839]
## Service name

Prisoner Money

## Service environment

- money-to-prisoners-test
- money-to-prisoners-prod

## Problem description

The current ECR lifecycle policy (as far as I know) deletes oldest images once there are more than 40.

The problem is that if there are multiple PRs and branches, continuous integration tools can fill up this limit and the currently deployed image in the cluster will no longer be available. This is bad in case of auto-scaling, deployment roll-back, automatic pod recreation and cron jobs.

We have some automatic clean-up already (untagged images are deleted) and I plan to add more (deleted PR images once merged).

So… is it possible to (in order of preference):
1) Update the policy template such that there is an additional rule with `tagPrefixList` that protects images with special tags? e.g. `protect-[app name]`
2) Turn off the policy in our namespaces? There appears to be a terraform key `enable_policy`… if I change it, will it update the policy? I cannot check as my IAM role does not have policy read permission.
3) Up the limit to, say, 100 for our two ECRs in the namespaces above?

**Comment by ushkarev** [comment]
Our situation is particularly bad because we have 6 apps and those not being updated fall off the list unless I put in very rigorous image deletion.

**Comment by ushkarev** [comment]
correction, there is only one ECR that's in money-to-prisoners-prod and shared amongst all our namespaces

**Comment by kcbotsh** [comment]
@vijay-veeranki-moj can you please bump this up?

**Comment by vijay-veeranki-moj** [comment]
Updated the ECR lifecycle policy expiry limit to 100, to get this change effected the latest ecr module "github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials?ref=3.3" should be used

**Comment by ushkarev** [comment]
@vijay-veeranki-moj – so what would happen if we changed `enable_policy` from point 2 above? Did cloud platform decide that option 1 is not viable?

**Comment by vijay-veeranki-moj** [comment]
Hi @ushkarev 
The better solution for now is to increase the expiry limit, as other options are complicating the ecr module.

In the ecr module we made the enable_policy to be default , so if you are using this module the policy will be applied by default.
https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials/blob/master/README.md#inputs

Please check how it works for you after increasing the limit

https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#ecr-lifecycle-policy

**Comment by ushkarev** [comment]
Hey @vijay-veeranki-moj 
Sure, but what I'm asking is will the policy be updated if I change the variable on an existing ECR?
I ask because I cannot check as my IAM role does not have policy read permission.

**Comment by vijay-veeranki-moj** [comment]
Hi

To get this policy change effected for your ECR you need to update the version of the ECR module you are using to "github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials?ref=3.3"

**Comment by ushkarev** [comment]
thought i'd drop in a few notes from yesterday's chat… just so there's a record of it!

- doesn't sound like my suggestion # 1 would work. the only lifecycle action is expire and you cannot exclude images based on tag prefix in a rule.
- imposing any limit on number of images is potentially dangerous unless teams have their own clean-up mechanism. lifecycle policies _silently_ delete images and kubernetes deployments/cronjobs/etc could fail without warning. a couple of scenarios:
  - an ECR hosts images for 1 application. a build pipeline adds images for every push to a feature branch so that things can be tested in a staging environment. an old image is currently deployed in production. the feature branch gets lots of updates and fills up the 40/100 image limit. ECR silently deletes the oldest image which just so happens to be deployed in production. there is no warning and nothing happens for a while. some time later, kubernetes decides to move the pods around and cannot find the image necessary so the production app is suddenly broken and it's not immediately obvious why.
  - an ECR hosts _multiple_ apps and a few base/helper images (our situation). one app is very rarely updated. we might accidentally forget to run our clean-up tasks and hit the limit because development continues on newer apps. kubernetes suddenly cannot run our daily cronjob because it just so happens to be our least regularly developed piece of code. luckily, this would be spotted very quickly and is easy to resolve. but it's still a danger.
- there is a lifecycle policy that i think is pretty safe and useful – deleting untagged images – as i would not expect people to use image hashes instead of tags in deployments. untagged images are really easy to leave lying around and you cannot easily tell what's inside them.
- there is a hard limit of 1000 images per repo. without a lifecycle policy cleaning things up, it's not unlikely for a big project to reach this limit. once reached, a build pipeline (and possibly a deployment pipeline) would stop working. personally, i find this less of a problem because not being able to build or deploy something new is nowhere near as bad as an existing deployment suddenly breaking seemingly randomly.

there are a bunch of clean-up tasks in our deployment pipeline that i've been working on. here's a sample of one that automatically removes images once a PR is merged. it's very specific to our tagging structure, but could easily be reworked for other teams
https://github.com/ministryofjustice/money-to-prisoners-api/tree/master/.github
