### ISSUE TITLE
I need a Single Sign On account

### ISSUE THREAD

**Issue by leoapost** [ministryofjustice/cloud-platform#84]
## Service name

Single Sign On

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

SSO stops me from accessing the Tax Tribunals downloader app.

## Problem description

I need to reproduce a production bug in the Tax Tribunals downloader app.

## Contact person

Name: Leonidas Apostolidis
Slack: leoapost
Email: leonidas.apostolidis@hmcts.net (leonidas.apostolidis@digital.justice.gov.uk)

**Comment by jasonBirchall** [comment]
Had a chat to Leonidas. He will speak to the project manager of SSO.
