### ISSUE TITLE
Kube-Ops installed on Live-1

### ISSUE THREAD

**Issue by ollieanwyll** [ministryofjustice/cloud-platform#842]
**WHY**
We need the Kube-Ops dashboard setup for Live-1.

https://github.com/hjacobs/kube-ops-view

The dashboard must be displayed on a new tab 
on the TV.

**Comment by digitalronin** [comment]
From Mourad;

> I can't find any kubeops pods on the cluster

So, this includes installing Kube-Ops on live-1

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/commit/780dc0a4e122f367b0149163e48817f0110be147
