### ISSUE TITLE
SPIKE - Replace Elasticsearch

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#845]
## Background

Spike to look at an alternative to Elasticsearch.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by digitalronin** [comment]
FYI, I met someone at Ruby Kaigi who is reasonably senior at Elastic. Let me know if you want me to ask about a trial/discount for their hosted service - we might not get anywhere, but it probably wouldn't hurt to ask.

**Comment by digitalronin** [comment]
I heard back from my contact at Elastic. Unfortunately, he wasn't able to help with any credits/special trial. He recommended getting in touch with a sales rep. via their website.

**Comment by AntonyBishop** [comment]
To be considered as part of the spike - https://mojdt.slack.com/archives/C8QR5FQRX/p1557481076002000
