### ISSUE TITLE
Make a list of things using postgres 9.3

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#85]
## Background

We currently have the a list of the things on the DSD account using postgres 9.3. We need to find the things on other accounts on the org. 

@sablu thinks the AWS TAM can run something that gives us a list against all of the accounts. 

We *may* have the emails. Sablu to check. 
Maybe Trent has the emails. 

**Done when**

- [x] We've got a list that covers all our AWS accounts
- [x] We've tried to check it with AWS TAM
- [x] The list says which team each of those databases belongs to

**Comment by sablumiah** [comment]
https://docs.google.com/spreadsheets/d/1iZUJ99tnPSH0SS4TE_JMNEigvjZWrMWNLgdoi8CrJ0E/edit?usp=sharing
