### ISSUE TITLE
Spike: Vulnerability/Image Scanners

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#855]
Types of scanning:

* Static image scanning (for known vulnerabilities in libraries. Clair, SonarQube)
* Runtime scanning
* Check for unauthenticated access to the kubernetes API (e.g. Aqua Security scanning tool)

**Comment by AntonyBishop** [comment]
Submitted by Jason - https://github.com/coreos/clair

**Comment by AntonyBishop** [comment]
Looks like GDS' GSP is also using Clair. As part of the spike we should take a look at what they are doing.

**Comment by vijay-veeranki-moj** [comment]
https://docs.google.com/document/d/1aB0rwj7lYw1pB_f0rZZK8KxXkcgAyBtkmM4Ld2Aqx2U/edit?usp=sharing

**Comment by vijay-veeranki-moj** [comment]
Created Individual tickets based on the spike for the ticket.

Findings here
https://docs.google.com/document/d/1aB0rwj7lYw1pB_f0rZZK8KxXkcgAyBtkmM4Ld2Aqx2U/edit?usp=sharing

**Comment by davidread** [comment]
List of tools we looked at during this spike:

Kubernetes image scanning and static analysis
* Clair
* Aqua Microscanner
* KubeXRay
* Trivy
* Anchore Engine
* Sonarqube

Kubernetes runtime security
* Sysdig open source
* Sysdig Falco

Kubernetes security audit
* Kube-bench
* Kube-hunter
