### ISSUE TITLE
Find out if any live sentrys are using 9.3

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#86]
## Background

Test, staging and prod sentry instances that people are interacting with -- what version of postgres are they using? It is confusing because a) there are 2 sentrys called prod and b) we are not sure if people are using the staging/dev sentrys (we think these were used for infrastructure testing). 

**Done when**

- [x] Find out: Why are there 2 prod sentry databases and which one is being actively used?
- [x] Find out: are any of the staging or test sentry's being used?
- [x] Find out: the version of the db for the staging and test sentrys?
- [x] Find out: are there any other non-cleaned-up ones?

**Comment by jasonBirchall** [comment]
------------
There is a staging Sentry:
http://sentry-staging.service.dsd.io/

The DB for this environment of Sentry is: 
`sentry-staging-cdde1be0`

The version of this DB is:
9.3.
------------
There is no test/dev environment of Sentry but there is a DB: 
`sentrytest`
This is not being used.

**Comment by jasonBirchall** [comment]
We will need to delete the following databases:
`sentry-prod` (not to be mistaken with sentry-prod-d816934f, which should not be deleting).
`sentrytest`

And upgrade the following to 9.6:
`sentry-staging-cdde1be0`

**Comment by jasonBirchall** [comment]
connects to: #87, #90, #91 and #92
