### ISSUE TITLE
Alter OPA policy to allow users to edit their ingresses

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#862]
We have an OPA [policy](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/live-0/terraform/cloud-platform-components/resources/opa/policy-ingress-conflicts.yaml) designed to prevent people from defining an ingress in their namespace whose hostname matches the ingress in a different namespace. For example, if someone were to copy and paste some code from the repository of a live servie into their development namespace, they might accidentally 'hijack' the domain name of the live service. This policy is designed to prevent that type of problem.

It seems the policy might be preventing people from *editing* their own ingresses, as per [this Slack thread](https://mojdt.slack.com/archives/C57UPMZLY/p1556187685030100).

### Definition of done

The policy has been altered such that it is still impossible to *create* a hostname which is already in use in the cluster, but allows users to *make changes* to their ingress definitions.

**Comment by vijay-veeranki-moj** [comment]
Altered the policy to allow users to make changes to their ingress definitions as well along with impossible to create a hostname which is already in use in the cluster.

**Comment by vijay-veeranki-moj** [comment]
applied policy on both live1 and live0
