### ISSUE TITLE
Adapt the multi-container demo app. to include an nginx container

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#863]
We should have an example of using an nginx container with a non-root user. This will both confirm that the bitnami nginx container is suitable, and provide an example for users who need this functionality in their services.

### Definition of done

 * Add a bitnami nginx container to the [multi-container demo app](https://github.com/ministryofjustice/cloud-platform-multi-container-demo-app), serving static assets
 * Add a path rule to the ingress such that requests to /static/app.css receive the app.css file from the nginx container
 * Update the build and deploy scripts to include the nginx container
 * Update the demo application web page to use static assets from the nginx container
 * Alter the walkthrough in the user guide accordingly

**Comment by AntonyBishop** [comment]
No longer required.
