### ISSUE TITLE
Access required for AWS and Jenkins

### ISSUE THREAD

**Issue by mseedat-moj** [ministryofjustice/cloud-platform#867]
## Service name

Request for users from Central Digital (Correspondence Tool):

ADD:
**ian.anderson@digital.justice.gov.uk**

REMOVE:
**stephen.dicks@digital.justice.gov.uk**

*Project: Correspondence Tool*

*Request:*
1. Amazon AWS account required for mojdsd team
2. Jenkins authorisation required

## Service environment

- [X] Dev / Development
- [X] Staging
- [X] Prod / Production
- [x] Other

## Impact on the service

*To the Jenkins System*
1. Deployment of system to existing staging and production environments (template deploy)
2. Practice migration on new cloud platform (kubernetes based deployment)
3. Manage Continuous Integration pipeline/issues/etc

*To AWS mojdsd*
1. For development purposes (S3, etc)
2. For dev/staging/production environments access
3. For commissioning additional servers if required

I ticked 'other' in case there are other systems we would need access to in order to perform deployments and setting up the migration of the existing app to the new cloud platform.

## Problem description

Cannot deploy latest updates to Correspondence tool application.

Cannot perform cloud platform migration work.

## Contact person

mohammed.seedat@digital.justice.gov.uk
@moseedat

**Comment by lukaszraczylo** [comment]
Ian already have an access to jenkins ( just confirmed ). 
I don't see any reason for the AWS account access for now as infrastructure autoscales regardless. Can provide Ian with mentioned access if he feels comfortable enough with using template-deploy on his own laptop.

**Comment by AntonyBishop** [comment]
Seems like a sensible approach.

**Comment by Polsonby** [comment]
Hey guys. So part of the request is about getting access to set up deployment to the new Cloud environment using Circle CI 

```To the Jenkins System
1. Deployment of system to existing staging and production environments (template deploy)
2. Practice migration on new cloud platform (kubernetes based deployment)
3. Manage Continuous Integration pipeline/issues/etc

To AWS mojdsd
1. For development purposes (S3, etc)
2. For dev/staging/production environments access
3. For commissioning additional servers if required
```

I don't know what you mean by "template deploy" but it sounds like it is something to do with Jenkins and I suspect this isn't enough to do everything I need to do

Perhaps Mo can give more background to what I need than I can as he's the one that authored the request

**Comment by lukaszraczylo** [comment]
Unfortunately, our new cloud platform does not use Jenkins and does not require an AWS access and I'd like to note that for template-deploy projects Jenkins access for the purpose of the deployment is sufficient.

You can learn more about the new platform from our user guide available here - https://user-guide.cloud-platform.service.justice.gov.uk/ - and used widely around the organisation. 
I can recommend having a look at the creation of a cloud platform environment section here where the whole process of bringing the new environment up is described:
https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#creating-a-cloud-platform-environment

**Comment by Polsonby** [comment]
Thanks for the explanation, Lukasz 

those are great resources, thanks for the links

**Comment by lukaszraczylo** [comment]
You are more than welcome! :)
I hope you'll find platform documenation easy to understand, but if you'll encounter any problems or have additional questions feel free to pop into #ask-cloud-platform channel and ask the team :)
