### ISSUE TITLE
Enable developers to create/destroy 'instant' development databases

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#874]
Our [RDS module](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance) enables developers to create RDS instances for their services.

This is exactly what teams should be doing for their production deployments
(and potentially for some test/staging deployments as well), but there are some
problems with using it in development environments:

* Both creating and destroying RDS instances takes around 30 minutes per operation
* RDS instances are quite costly

We could mitigate both of these issues by creating:

1. a dedicated RDS instance to host development databases
2. an 'rds-dev-database' terraform module, which manages databases in the shared RDS instance

This would **not** be suitable for production databases, but should be adequate for development purposes.

Creating and destroying databases on a shared RDS instance should be virtually
instantaneous, and an RDS instance hosting 100 shared development databases
will be much cheaper than creating 100 separate RDS instances. Provided these
databases are only used for development purposes, there should be no additional
security concerns (although we should check this with the security team).

### Definition of done

* We have confirmed with the security team that a shared RDS instance hosting multiple development databases is acceptable
* We have created an RDS instance large enough to host multiple development databases
* We have written a terraform module which manages databases on this RDS instance. As far as possible, this should be a drop-in replacement for our RDS instance module, so that developers can easily use 'rds-dev-database' for development, with minimal changes required to use 'rds' in production
* We have updated the user documentation to explain:
  * The tradeoffs in using the 'rds-dev-database' versus the 'rds' terraform module (quicker and cheaper, but not production-ready)
  * How to use the 'rds-dev-database' module

**Comment by mtrblmoj** [comment]
My thoughts, that ticket implies : 
- Having a common RDS instance, managed by the CP team
- Sharing the RDS credentials (from 0 the common namespace) with team's namespace that want to create a database (RDS != database)
- Having teams create database/credentials against that RDS from their namespaces

Can we confirm we want this ?

**Comment by kcbotsh** [comment]
@mitch @AntonyBishop @digitalronin. Please see comment above from @mtrblmoj

**Comment by AntonyBishop** [comment]
Couple of questions:
What are the security concerns specifically?
Do we have any users asking for this at the moment?

If the answer to the first one is significant issue then suggest we close, otherwise maybe we pull it back to the backlog for a bit of further triage?

**Comment by mtrblmoj** [comment]
> Do we have any users asking for this at the moment?
Not really. Some teams pointed out that creating RDS is taking a long time (~20min), which 

> What are the security concerns specifically?
- We would have to expose one set of _shared_ RDS credentials for the module to work, and create team-specific credentials (secret sprawl) 
- This is meant to be a (multi-tenant) dev environment. The fact that we won't be able to prevent potential close-to-prod data to be pushed on there is an issue.

**Comment by AntonyBishop** [comment]
Sounds like the main problem is provisioning time. 

Is there a way of reducing that time or is that a constraint that we can't influence? i.e. it's an AWS issue.

**Comment by digitalronin** [comment]
I agree with @mtrblmoj - the concerns of the security team seem very valid. The purpose of this ticket was to provide a way for teams to create "quick and dirty" throwaway databases for development, without having to wait half an hour every time. 

Perhaps a better option would be to create a user guide walkthrough of how to run postgres in a container, in their namespaces, and use that as a dev. DB. 

So yes, I'd agree that we should close this ticket, for now.

**Comment by digitalronin** [comment]
Sorry, to answer your question, Tony - no, there's nothing we can do to speed up AWS RDS creation
