### ISSUE TITLE
Failed staging deploy for LAA Legal Adviser API

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/cloud-platform#877]
## Service name

https://github.com/ministryofjustice/laa-legal-adviser-api, LAALAA

## Service environment

- [ ] Dev / Development
- [x] Staging
- [ ] Prod / Production **did not try, most likely affected by the same script**
- [ ] Other

## Impact on the service

Cannot deploy the service.

## Problem description

`fab` deployment fails with the following errors:

https://ci.service.dsd.io/job/DEPLOY-laalaa/157/console
```
+ pip install -r ./requirements-deploy.txt --upgrade
<snip>
ERROR: pygithub 1.43.7 has requirement requests>=2.14.0, but you'll have requests 2.11.1 which is incompatible.

+ fab application:laalaa aws:cross-account environment:staging config:./cloudformation/laalaa.yaml upload_assets:./static,/
<snip>
ImportError: No module named urllib3
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

## Contact person

@sldblog, `@David Lantos` on Slack.

**Comment by lukaszraczylo** [comment]
Added pip install urllib3 to the build configuration sorted the problem as per https://ci.service.dsd.io/job/DEPLOY-laalaa/163/console

**Comment by digitalronin** [comment]
Fixed by @lukaszraczylo 

Fix: added pip installation of urllib3 to the deploy job configuration

It's unclear why this deployment job broke now - either it should never have worked, or it should have kept on working. It's possible that there was a change in the underlying python libraries.
