### ISSUE TITLE
Find out how paroleboard.gov.uk is being redirected

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#878]
## Service name

paroleboard.gov.uk

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

No impact.

## Problem description

paroleboard.gov.uk is redirected to https://www.gov.uk/government/organisations/parole-board

Please can we find out how and where this is being redirected. We are trying to determine the purpose of the domain paroleboard.gov.uk and whether it requires an SSL certificate.

## Contact person

Tony

**Comment by lukaszraczylo** [comment]
Leaving note for future generation:
Mentioned domain is served by the proxy.digital.justice.gov.uk, yet - mentioned server does not support SSL.
Proxy server resides in DSD AWS account which will require extra investigation for the access.

**Comment by AntonyBishop** [comment]
Thanks @lukaszraczylo . So what do we need to find out next. If that server doesn't support SSL then that would probably also explain why there was no SSL in place.

In terms of ownership of that server do we have any idea?

**Comment by lukaszraczylo** [comment]
It was probably created ad-hoc by one of the consultancies, I've been trying to find out more by digging and searching through notes and old tickets, no joy for now.

**Comment by AntonyBishop** [comment]
Thanks @lukaszraczylo.

Possible that this is something set up and was support by Trent for some purpose. Have reached out to Trent to see if we can turn up anything else?

**Comment by AntonyBishop** [comment]
Turns out it wasn't one of Trent's services.

**Comment by AntonyBishop** [comment]
Unable to identify owner. No requirement for a certificate so closing the ticket.
