### ISSUE TITLE
Moving People Safely - update Production IP whitelist

### ISSUE THREAD

**Issue by jason-sims** [ministryofjustice/cloud-platform#880]
## Service environment

- [] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

**Comment by kcbotsh** [comment]
@jason-sims. We need more information in order to carry out this work. It is not clear what changes the CP team are required to make. We would also need pointers to files in github and information as to where your production IP is as well as what changes you need us to make. Thanks

**Comment by lukaszraczylo** [comment]
On this note I'd like to add that we should avoid posting list of IPs which require whitelisting in github comments as they're publicly available. For this purpose please use #ask-cloud-platform Slack channel.

**Comment by AntonyBishop** [comment]
Whitelist changes were made back in May
