### ISSUE TITLE
Create a document listing all the secrets we maintain

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#884]
For all the secrets, try to gather as much of the following information as possible:

 * Secret name
 * Description (what is it for?)
 * What uses it
 * How to rotate it
 * When was it last rotated

**Comment by pwyborn** [comment]
mitch   [22/05/2019 at 11:38 AM]
secret stuff thread
12 replies

mitch   [1 hour ago]
@paulwyborn I’m not sure it’s worth spending time on secrets managed by terraform in the environments repo.

I think all these can be under the “managed through environments” umbrella? 

mitch   [1 hour ago]
They’re all either randomly generated or provided by AWS (IAM keys) I believe, rotation is similar (`taint` the resource and re-create).

mitch   [1 hour ago]
If you omit them, it will significantly reduce the scope of this ticket.

mitch   [1 hour ago]
Although you’ve already done the work I suppose!

mitch   [1 hour ago]
@davidsalgado wdyt?

davidsalgado   [1 hour ago]
I agree. I really only had in mind the stuff that isn't automated.

davidsalgado   [1 hour ago]
Like, when Mitch had to rotate a whole bunch of git-crypt secrets

davidsalgado   [1 hour ago]
It would be good to have documented somewhere what those secrets are, what they're for, and how to rotate them.

davidsalgado   [1 hour ago]
The same will be true for things like our admin account with CircleCI, for example

paulwyborn   [1 hour ago]
ok noted - i’ll rethink this - can put them on separate sheet for now

davidsalgado   [1 hour ago]
Anything that's in code is basically self-documenting, in the sense that we can grep for it and then figure out from the code what's going on (which doesn't mean having good documentation isn't important). But stuff that's only in people's heads is hard.

mitch   [1 hour ago]
my thoughts exactly

**Comment by pwyborn** [comment]
Slack 12:33 #cloud-platform channel 22/05/2019:

Hi would it be possible please to add details of any un-automated “in people’s heads” secrets in the “Secrets” sheet (link in email I just shared with you)
Thank you

**Comment by pwyborn** [comment]
https://docs.google.com/spreadsheets/d/1QK6cZ8JJYuRixIrpZZrH8c7-VkbPVUhrUTkyWL-E63A/edit#gid=0 (link to document)

**Comment by pwyborn** [comment]
@digitalronin - Hi David - do you think I can take this ticket much further at the moment please.?Have asked a couple of times in #cloud-platform for anything to be added. Mitch has added a few secrets. Is there anything specific that you know of that has not been captured. 
Or should I treat this document as a starting point and close the ticket

https://docs.google.com/spreadsheets/d/1QK6cZ8JJYuRixIrpZZrH8c7-VkbPVUhrUTkyWL-E63A/edit#gid=0

**Comment by davidsalgado** [comment]
Hey, wrong David Salgado I’m afraid. I’m not @digitalronin.

cheers

**Comment by alkar** [comment]
@pwyborn I think the intention is to get a starting point indeed. If you're happy you've collected as much as possible, feel free to close this issue.

**Comment by pwyborn** [comment]
Thanks - to be closed
