### ISSUE TITLE
Update Leavers Process Documentation (placeholder for when centralised)

### ISSUE THREAD

**Issue by pwyborn** [ministryofjustice/cloud-platform#890]
## Background

The Leaver's process documentation has become out of date. 

## Approach

- Update the documentation as a place holder for the content (for when centralised)..

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

N/A

## Definition of done

- [ ] Review of leavers documentation
- [ ] Update of leavers documentation

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
Please see https://dsdmoj.atlassian.net/wiki/spaces/PLAT/pages/324076142/Leavers

**Comment by digitalronin** [comment]
LGTM - a great start

**Comment by sid234** [comment]
Hi Paul, Good work on the documentation
