### ISSUE TITLE
Documentation on how to decommission unused template deploy services

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#896]
Hello,

We now have 2 old template deploy services fully migrated to k8s. They've been running on k8s for more than 3 weeks without known issues and we are confident we can get rid of their template deploy counterparts.

Is there a documented procedure to decommission old/unused AWS resources, jenkins jobs, old docker images, old deploy repos, etc? Basically a proper spring cleaning.

Thank you.

## Contact person

Jesus @ slack

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/97

**Comment by sid234** [comment]
LGTM

**Comment by pwyborn** [comment]
Changes merged. To be closed
