### ISSUE TITLE
Upgrade any sentrys using 9.3 via template deploy

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#90]
## Background

Depending on the results of #86 there _might_ be a sentry or two using postgres 9.3. If there are we want to upgrade these to a 9.5.x to keep them in line with the current production version. 

## Approach

We want to ideally do this with template deploy so that if the team runs template deploy again there is no mismatch. The next worst option is to do it manually and update template deploy. The worst option is _just_ to do it manually. 

Which of these options we take will depend on #87, so we should talk after that one is done. 

## Questions / Assumptions

- Template deploy can supply a version for a postgres rds build

## Definition of done

- [ ] All sentry instances are using a 9.5.x postgres rds database
- [ ] If a team runs template deploy it will not error or try to downgrade the db

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
Following guidance here. We need 9.5.x so will need to perform two incremental installs. https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html

**Comment by jasonBirchall** [comment]
Posted the following in relevant slack rooms:
```
@here About to perform an upgrade of Sentry staging's postgres RDS instance from 9.3 to 9.5. Sentry staging will be unavailable during this time. Will post here when complete.
```

**Comment by jasonBirchall** [comment]
DB upgraded to PostgreSQL 9.5.12.
