### ISSUE TITLE
Move github notifications from #ask-cloud-platform to a new, dedicated slack channel

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#901]
We want #ask-cloud-platform to be a community support channel, but the github notifications add a lot of noise which probably works against that.

### Definition of done

 - [x] Rename #cp-build-notifications to #cp-notifications
 - [x] Send all github notifications to #827 
 - [x] Document that monitoring the channel is part of the responsibilities of the Hammer of Justice
 - [x] Tell people abou the new setup

**Comment by sablumiah** [comment]
New channel is now called #cloud-platform-notify

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform/pull/942/files
