### ISSUE TITLE
Custom URL request - uat.claim-criminal-injuries-compensation.service.justice.gov.uk

### ISSUE THREAD

**Issue by ermiasworku** [ministryofjustice/cloud-platform#904]
## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [x ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

## Problem description

Hi, I'm trying to get a custom url for my app. I need to be able to access it on:

uat.claim-criminal-injuries-compensation.service.justice.gov.uk

The app is currently up and running on the cluster but it is accessible on:

 uat.claim-criminal-injuries-compensation.apps.live-1.cloud-platform.service.justice.gov.uk

I need to drop the …..apps.live-1.cloud-platform.... from the url

I understand that you will provide the certificate provider name and I will update the ingress file and a certificate yaml.

This is similar work that completed last week using PR #825

## Contact person

Ermias Worku
@ermiasworku 
ermias.worku@cica.gov.uk

**Comment by ermiasworku** [comment]
Hi, 
please see update current url.

https://uat-claim-criminal-injuries-compensation.apps.live-1.cloud-platform.service.justice.gov.uk/

**Comment by vijay-veeranki-moj** [comment]
we created new route53 zone in cp account and new applied ingress and cert matching new zone to get it working.
https://uat-claim-criminal-injuries-compensation.service.justice.gov.uk/
