### ISSUE TITLE
Create a script to identify 'good' new namespace PRs

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#907]
We have an automated process people use to [create namespaces](https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#creating-a-cloud-platform-environment).
We then ask people to raise a PR, which we check for correctness and then approve/reject.

If the namespace files are created via a script, it should be possible to write a script to automatically identify those which are both correct and typical. Initially, this could save us time in checking PRs, leading to a quicker turnaround time. Eventually, this could become the basis for a github bot which automatically approves PRs which are obviously good, and notifies us about any which require a closer look.

The initial version of the script should, when invoked with the name of a branch, or the issue number of a PR on the environments repo:

 * Pull the latest version of the repo
 * Check out the relevant branch
 * Check that the PR consists of a single directory below the `namespaces/live1` directory
 * Check that the PR contains exactly N files, with the expected filenames
 * Check that the contents of each file is what we expect (e.g. 'name' property in '00-namespace.yaml' is the same as the directory name, all fields are completed with values which look like they're the right kind of string - email addres, source code URL, etc.)

Initially, the script should output a report to the console, with passing checks in green and any exceptions in red. So, if the PR is basically fine but, e.g., also defines an RDS instance, then whoever reviews the PR only needs to pay attention to the rds.tf file, and doesn't need to waste time checking everything else by hand.

**Comment by AntonyBishop** [comment]
Done
