### ISSUE TITLE
Cleanup any unused sentry infrastructure

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#91]
## Background

Our initial investigation shows that there might be a few versions of sentry hanging around that are not being used. So for any non live versions of sentry, let's get rid of the app, database and deployment method. 

**Only for sentry related stuff**

## Questions / Assumptions

- These were built using template deploy

## Definition of done
For any non-live sentry instances, the following have been removed:

- [x] RDSs running at 9.3
- [x] EC2 instances
- [x] certs, elbs, routes 
- [x] CF stacks
- [x] Monitoring stacks
- [x] Any template deploy artefacts (e.d. deploy job, repo)

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sablumiah** [comment]
Old Prod CF stack (full environment) deleted which included a 9.3 sentry-prod db
sentrytest 9.3 db deleted
