### ISSUE TITLE
FALA cloud formation stacks deletion

### ISSUE THREAD

**Issue by said-moj** [ministryofjustice/cloud-platform#910]
## Service name

Find a Legal Adviser (FALA)

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Problem description

The Find A Legal Adviser site has now fully moved to Kubernetes and we are looking to clean up the unused AWS resources. 

We need to have the following cloud formation stacks deleted:

- fala-staging-5292e4dc
- fala-prod-b5412c08
- fala-prod-6b4c951a

## Contact person
[at]Said
[#]laa-cla-fala
[#]cla-traffic-split

**Comment by lukaszraczylo** [comment]
Confirmed with Said green light for deletion of mentioned stacks.

**Comment by lukaszraczylo** [comment]
![Screenshot 2019-05-14 23.10.41.png](https://images.zenhubusercontent.com/5c93687c0e93bf7b2d1455a9/df6a8521-ff98-4ad1-b45d-2cbb5f690e15)

There's few more left - should they be deleted as well?

**Comment by said-moj** [comment]
Hi Lukasz

I think fala-prod-6b4c951a is also part of the fala stack and needs deletion

The rest are needed and should *not* be deleted

**Comment by lukaszraczylo** [comment]
Stacks mentioned in the ticket description were successfully deleted.
