### ISSUE TITLE
Change the FQDN for the CICA UAT environment

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#919]
CICA are running their UAT (user acceptance testing) deployment at:

https://uat-claim-criminal-injuries-compensation.service.justice.gov.uk/

(see: the domain setting [here](https://github.com/ministryofjustice/cloud-platform-environments/blob/6c7120fa587997355133617e28c493afbb52aa13/namespaces/live-1.cloud-platform.service.justice.gov.uk/claim-criminal-injuries-compensation-uat/resources/variable.tf#L29))

They would prefer this to be:

https://uat.claim-criminal-injuries-compensation.service.justice.gov.uk/

(i.e. uat-cla.. -> uat.cla..)

Eventually, their production service will be hosted at:

https://claim-criminal-injuries-compensation.service.justice.gov.uk

So please bear this in mind when making zone/sub-domain/certificate choices.

CICA Team contact: Ermias Worku <ermias.worku@cica.gov.uk>

**Comment by vijay-veeranki-moj** [comment]
users can now access
https://uat.claim-criminal-injuries-compensation.service.justice.gov.uk/
