### ISSUE TITLE
Meet with teams to discuss upgrade approach

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#92]
## Background

Depends on #85 

When we make the list of services using postgre 9.3 (#85) we expect to find some teams that have not upgraded. We want to talk to them to:

a) make sure they are aware that it needs to be upgraded
b) work out what help they need to get that done

As part of that talk we will:

- encourage them to take control of the upgrade (i.e. schedule it in the backlog, work out any implications it has on their app)
- walk through template deploy gotchas (i.e. if you upgrade manually template deploy might have a bad day)
- ensure that we're there to help if they need it

## Approach

@AntonyBishop to lead on talking to the teams, with an engineer in each meeting. 

## Definition of done

- [x] We have notified them that it is happening
- [x] Upgrade in each team's backlog
     - [X] Cloud Platform
     - [X] CCCD
     - [x] PeopleFinder
     - [x] PQ
- [x] We understand the kind of support they will need from us

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
A list of products using Postgres 9.3 can be found here:

https://docs.google.com/spreadsheets/d/1iZUJ99tnPSH0SS4TE_JMNEigvjZWrMWNLgdoi8CrJ0E/edit?usp=sharing

Status of engagement with each team will be updated in this document.

**Comment by AntonyBishop** [comment]
All D&T (Tab 1) Product owners notified on required upgrade. Awaiting any follow up and confirmation that work is accepted into backlog.

To do - notification to owners on other accounts as a courtesy. These accounts should have been notified by AWS directly. Notification to check no one has been missed.

**Comment by AntonyBishop** [comment]
CCCD (Alice Cudmore) has confirmed that activity has been added to their backlog. No support required. They will let us know when work is completed.

**Comment by AntonyBishop** [comment]
PeopleFinder update - Keira Poland (PM) has confirmed that PeopleFinder has no team to support it. Keira is making a request for some technical resource so that changes can be impact assessed and a team can be put in place (with assistance from us) to carry out the upgrades.

**Comment by AntonyBishop** [comment]
PQ update - Andy Robb (PM) has confirmed that they will need assistance with upgrade. A team exists to support the work. I will draft a plan to agree with TP (and PeopleFinder) to take forward upgrades.

**Comment by AntonyBishop** [comment]
Approach for upgrades to PeopleFinder and PQ sent to Product Teams. Awaiting agreement on approach and confirmation that items added to backlog. When agreed new issues will be created to the upgrades.

**Comment by AntonyBishop** [comment]
All work added to backlogs. Issues to be created for upgrades.
