### ISSUE TITLE
Setup concourse with the correct permissions for module.amq.aws_mq_broker.broker

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#920]
Concourse need to be able to manage module.amq.aws_mq_broker.broker for applications. Currently, it's been manually added to its role in IAM.

Definition of done: 
 concourse IAM role is adjusted to allow management of module.amq.aws_mq_broker.broker
 the permissions follow the least-privilege principle
 the change is version controlled as usual
 the apply pipeline is green

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-concourse/pull/78
Merged
