### ISSUE TITLE
Add default configuration for AMQ 

### ISSUE THREAD

**Issue by mtrblmoj** [ministryofjustice/cloud-platform#921]
Issue :
The AMQ terraform module does not define an AMQ configuration. AWS then creates a default one, that won't be tracked by terraform and therefore never cleaned-up. 

Solution : 
Define a default amq configuration object within the module.
https://www.terraform.io/docs/providers/aws/r/mq_configuration.html

**Comment by vijay-veeranki-moj** [comment]
There is no option to destroy the config, so as discussed with team leaving to use the default config.
