### ISSUE TITLE
Create a "cluster status" web page

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#927]
This will be a page that service teams can look at to confirm that the cluster is operating correctly (or not).

The rationale for this is teams supporting their services out of hours. If they can easily find out whether the cluster is operating correctly, they will know whether or not they should escalate the problem to the cloud platform team, or if the problem is with their service.

The old prometheus-operator had some cluster health/status dashboards that the new one does not provide. They can be found [here](https://github.com/coreos/prometheus-operator/tree/94b30526f43d589912a38193b69dce19b4fa1893/helm/grafana/dashboards) and are possibly very useful.

**Comment by vijay-veeranki-moj** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/871
