### ISSUE TITLE
FIREBREAK IDEA - Investigate sentry.io to replace template-deploy sentry

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform#93]
Currently we are hosting Sentry on Template-Deploy. As Template-Deploy is being replaced, it's worth investigating using sentry.io opposed to hosting it on our own servers.

Sentry.io is a managed service with support. A issue that occured a few months ago, was a developer that did not recieve the 'forgot password' e-mail. This was due to an instance being out of service. This may not have happened if we were using Sentry.io.

+Defintion of Done +

Compare open source Sentry to Sentry.io

Compare costs of template-deploy sentry servers to Sentry.io monthly fee

**Comment by nayoa** [comment]
https://sentry.io/pricing/ - SSO with Github and Google

**Comment by nayoa** [comment]
https://blog.sentry.io/2017/12/05/introducing-saml
