### ISSUE TITLE
Write a troubleshooting guide for service teams

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#930]
Add to the user guide a document which explains, in general terms, how teams can find the key logs, events and metrics they can use to resolve problems with their applications.

This is mainly aimed at service team members who are trying to fix out of hours problems that arise with their services.

### Definition of done

This doesn't need to be the complete guide to troubleshooting. The point is to get a document we can point people to which covers the most common things they should be doing before raising a support ticket.

After intial assignee completes, handover to another engineer to add on to and so forth

**Comment by alkar** [comment]
@AntonyBishop _might_ have a list of FAQs, could be very helpful for this ticket.

**Comment by kcbotsh** [comment]
This will be a working document. Will be expanded on as time goes on

**Comment by jasonBirchall** [comment]
https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#troubleshooting-guide

Passing to a colleague to add examples.
