### ISSUE TITLE
Delete template-deploy CAIT stack

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#935]
## Service name

CAIT - Child arrangements information tool

https://github.com/ministryofjustice/pflr-cait-deploy

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Description

We've fully migrated this service to new k8s cloud platform.

We would like for the template-deploy AWS stack and resources to be deleted. We've marked the repo as deprecated but we've not yet deleted or archived it so a proper cleanup can be done.

Please check with Mourad as he did the route 53 zone and DNS migration to evaluate if removing the template deploy would affect in any way, hopefully not, they should be separated now. 

**Regarding Jenkins:**
We've removed as much Jenkins jobs as possible ourselves but there are a couple we don't seem to have permission to remove:

* BUILD-cait
* BUILD-cait-OLDcopy

## Contact person

Slack [at]Jesus

**Comment by lukaszraczylo** [comment]
CAIT staging and dev deletion in progress.
