### ISSUE TITLE
Delete template-deploy Family Mediators API stack

### ISSUE THREAD

**Issue by zheileman** [ministryofjustice/cloud-platform#936]
## Service name

Out of Court Path Way - Family Mediators
aka.
Family Mediators API

https://github.com/ministryofjustice/oocp-familymediators-deploy

## Service environment

- [x] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Description

We've fully migrated this service to new k8s cloud platform.

We would like for the template-deploy AWS stack and resources to be deleted. We've marked the repo as deprecated but we've not yet deleted or archived it so a proper cleanup can be done.

Please check with Mourad as he did the route 53 zone and DNS migration to evaluate if removing the template deploy would affect in any way, hopefully not, they should be separated now. 

We've already removed everything in Jenkins related to this service.

## Contact person

Slack [at]Jesus

**Comment by lukaszraczylo** [comment]
Dev and staging deletion in progress.
