### ISSUE TITLE
Document use of the postgres_exporter

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#938]
## Background

The applications running on the cluster mostly use postgres. It would be useful to export postgres metrics by use of the
[`postgres_exporter`](https://github.com/wrouesnel/postgres_exporter) for users to be able to get insights on their db
performance or issues.

## Approach

The exporter works by establishing a connection to postgres and pulling metrics so this would be something that is
deployed per-namespace, by the users.

We want to provide any easy way by which users can deploy this. Create a manifest file (or helm chart if appropriate)
that deploys the exporter in a namespace, along with the necessary `ServiceMonitor` for prometheus.

Create a templated grafana dashboard that displays key metrics for postgres for a given namespace.

## Which part of the user docs does this impact

User guide on how to monitor the RDS instance.

## Definition of done

- [x] we have a way by which users can easily deploy `postgres_exporter` for their RDS instance
- [ ] we have a grafana dashboard that users can utilise after deploying the above in their namespace
- [ ] there is a new section in the user guide that details the process of setting up `postgres_exporter`

**Comment by alkar** [comment]
Pending https://github.com/helm/charts/pull/14918

**Comment by alkar** [comment]
Once the above is merged, the postgres exporter can easily be deployed through environments:
```
provider "helm" {
  namespace = "my-namespace"
}

resource "helm_release" "postgres_exporter" {
  name = "postgres-exporter"

  chart     = "stable/prometheus-postgres-exporter"
  namespace = "my-namespace"

  values = [<<EOF
config:
  datasource:
    host: ${module.rds.rds_instance_address}
    user: ${module.rds.database_username}
    password: ${module.rds.database_password}
    database: ${module.rds.database_name}
    sslmode: require
rbac:
  pspEnabled: false
serviceMonitor:
  enabled: true
securityContext:
  runAsUser: 65534
EOF
  ]

  lifecycle {
    ignore_changes = ["keyring"]
  }
}
```

**Comment by alkar** [comment]
There's at least one working dashboard for `postgres_exporter` on the Grafana dashboards directory!

**Comment by pwyborn** [comment]
Documented here : https://github.com/ministryofjustice/cloud-platform-user-guide/compare/add/grafana-prometheus-postgres-exporter?expand=1 

Blocked until we fix the pipeline to hide the terraform log (exposing rds credential secrets). Ticket to be raised for this: to hide logs for plan and apply pipeline, to add grep

**Comment by pwyborn** [comment]
Ticket [Hide Terraform logs for plan and apply pipeline, to add grep #1669](https://github.com/ministryofjustice/cloud-platform/issues/1669)

**Comment by davidread** [comment]
RDS performance insights still seem useful

**Comment by AntonyBishop** [comment]
Closed due to age of story.
