### ISSUE TITLE
Enable creating subscriptions in our SNS terraform module

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#939]
references https://github.com/ministryofjustice/cloud-platform-terraform-sns-topic/issues/9

**Comment by razvan-moj** [comment]
Fixed in release 3.0 of https://github.com/ministryofjustice/cloud-platform-terraform-sns-topic/releases and 3.1 of https://github.com/ministryofjustice/cloud-platform-terraform-sqs/releases
