### ISSUE TITLE
FIREBREAK IDEA - Invesigtate updating Pingdom probe server IP's on live services

### ISSUE THREAD

**Issue by kcbotsh** [ministryofjustice/cloud-platform#94]
Currently for applications that are not public, we have resulted to whitelisting a list of Pingdom IP's on the security group and adding the security group to the elb.

However, Pingdom IP's are regularly changed and could result in Pingdom thinking a site is down when actually it is not.

https://help.pingdom.com/hc/en-us/articles/203682601-Pingdom-probe-servers-IP-addresses

We currently have this setup on MPS, PVB2, CLA Frontend and perhaps more.

Lukasz Raczylo  explained in stand up that we have a script in ops-tools github repo that checks the pingdom ips against the Pingdom API.

https://github.com/ministryofjustice/ops-tools

Defintion of Done

Define a list of applications that have Pingdom IP's attached to their ELB

Check the ops-tools pingdom script to see how and if it still works

Define when the script is run. i.e. daily, weekly, monthly?

If the script does not work, find another way of updating the pingdom ips on security groups

**Comment by AntonyBishop** [comment]
Revisit if comes an issue.
