### ISSUE TITLE
Delete RDS instances from cccd k8s namespaces

### ISSUE THREAD

**Issue by colinbruce** [ministryofjustice/cloud-platform#943]
## Service name

CCCD
## Service environment

- [x] Dev / Development
- [x] Staging
- [ ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

No impact, but it will allow new RDS instances to be created with standardised names

## Problem description

RDS instances have been created on the live-1 cluster for `cccd-dev` and `cccd-staging`.  These were done at different times and therefore have slightly different naming conventions.  Due to the pipeline not handling object deletion at the moment, can these be deleted manually so that new versions can be created using a new, better, pattern

## Contact person

Colin Bruce on slack or github

**Comment by colinbruce** [comment]
See this thread https://mojdt.slack.com/archives/C57UPMZLY/p1559034427019700 and the issues with the original PR https://github.com/ministryofjustice/cloud-platform-environments/pull/793 for details

**Comment by alkar** [comment]
This has been actioned. New databases are in place.
