### ISSUE TITLE
custom url https://claim-criminal-injuries-compensation.service.justice.gov.uk 

### ISSUE THREAD

**Issue by ermiasworku** [ministryofjustice/cloud-platform#944]
## Service name

claim-criminal-injuries-compensation-prod 

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

This is a blocker for our internal deadline mvp project completion date.

## Problem description

Hi, I'm trying to get a custom url for my app. I need to be able to access it on:

claim-criminal-injuries-compensation.service.justice.gov.uk

The app is currently up and running on the cluster but it is accessible on:

claim-criminal-injuries-compensation.apps.live-1.cloud-platform.service.justice.gov.uk

I need to drop the …..apps.live-1.cloud-platform.... from the url

I understand that you will provide the certificate provider name and I will update the ingress file and a certificate yaml.s. 

## Contact person
Ermias Worku,  ermias.worku@cica.gov.uk.

**Comment by digitalronin** [comment]
@SteveMarshall Can we do this now, or do we need to wait for this service to go through an assessment?

**Comment by SteveMarshall** [comment]
@digitalronin Go ahead, [the guidance](https://ministryofjustice.github.io/technical-guidance/standards/naming-domains/#servicejusticegovuk) says:

> ## service.justice.gov.uk
> All other MOJ services should be served from a *.service.justice.gov.uk subdomain, including:
> - public-facing services which haven’t yet passed a beta assessment (but may be in private beta with a restricted set of users)
