### ISSUE TITLE
https://data-capture-service.claim-criminal-injuries-compensation.service.justice.gov.uk

### ISSUE THREAD

**Issue by ermiasworku** [ministryofjustice/cloud-platform#945]
## Service name

data-capture-service.claim-criminal-injuries-compensation.apps.live-1.cloud-platform.service.justice.gov.uk/docs/

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

This is a blocker for our internal deadline mvp project completion date.

## Problem description

Hi, I'm trying to get a custom url for my app. I need to be able to access it on:

data-capture-service.claim-criminal-injuries-compensation.service.justice.gov.uk

The app is currently up and running on the cluster but it is accessible on:

https://data-capture-service.claim-criminal-injuries-compensation.apps.live-1.cloud-platform.service.justice.gov.uk/docs/
I need to drop the …..apps.live-1.cloud-platform.... from the url

I understand that you will provide the certificate provider name and I will update the ingress file and a certificate yaml.s.-->

## Contact person

Ermias Worku. 
ermias.worku@cica.gov.uk

**Comment by digitalronin** [comment]
@SteveMarshall Same question as #944 Can we go ahead and do this now?

**Comment by digitalronin** [comment]
FYI, Steve answered this [here](https://github.com/ministryofjustice/cloud-platform/issues/944#issuecomment-496920462). Yes, we can go ahead and do this.
