### ISSUE TITLE
Find a way to create read-only RDS credentials

### ISSUE THREAD

**Issue by mtrbls** [ministryofjustice/cloud-platform#946]
Issue - 

The only set of credentials created by the RDS module is a the admin ones.
When delegating access to an RDS (Application or Third Party), users first manually creates read-only username/password for that purpose.

Why not do that via terraform ?

Potential Solutions - 

- Extend the TF module to create read_only_username & read_only_password
- Document how to use the postgres_role terraform module 
https://www.terraform.io/docs/providers/postgresql/r/postgresql_role.html
- any other way

**Comment by sablumiah** [comment]
This can be accessed by using the kubernetes secret in their namespace
