### ISSUE TITLE
Create a new test cluster with terraform 0.12

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#948]
## Background

`terraform` 0.12 [has been released](https://github.com/hashicorp/terraform/releases/tag/v0.12.0).

This bring a number of changes to `terraform` and HCL, some backwards incompatible. Read the release notes (or the
changelog, if you're interested in the detail!) for an understanding of what's changed.

## Approach
This is a timeboxed issue. 2 days then review

1. Read the [upgrade guide](https://www.terraform.io/upgrade-guides/0-12.html).

1. Download the version 0.12 binary (but do not install it on your workstation or it will prevent you from working on
the existing infrastructure).

1. Using this binary, follow the process for creating a new test cluster, taking into account any steps explained in
the upgrade guide.

## Questions / Assumptions

- Does it even work?
- Do we need to make a lot of changes in the code before we upgarde?
- Do the upgrade helper commands help at all?
- Estimate the complexity for the upgrade!
- What are the major three benefits of terraform 0.12?

## Definition of done

- [x] we have a branch that contains all the changes required to have a cluster built by terraform 0.12
- [x] we have answers to the questions above

**Comment by digitalronin** [comment]
You can use the technique described [here](https://blog.gruntwork.io/installing-multiple-versions-of-terraform-with-homebrew-899f6d124ff9) to install multiple versions of terraform and switch between them.

**Comment by yasn77** [comment]
@digitalronin I have found that an easier (and cross platform approach) using [tfenv](https://github.com/tfutils/tfenv) works better. It's basically the same approach as things like rbenv.

Hope that helps

**Comment by jasonBirchall** [comment]
We have a documented approach here:

**Comment by jasonBirchall** [comment]
Questions answered in the following PR: 
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/285
