### ISSUE TITLE
Explore elastic.co hosted ES

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#949]
## Background

Related to #846

We are using AWS ElasticSearch for logs. Explore the elastic.co offer [on the AWS marketplace](https://aws.amazon.com/marketplace/pp/B01N6YCISK). We're already registered with the product so you only need to login [here](https://cloud.elastic.co).

## Questions

- What are the differences between the two services? (pros/cons)
- Can we adjust ES configuration?
- How do we manage the deployment as code?
- What kind of support do we get?
- What does DR look like?
- How do we monitor the cluster (hopefully some kind of prometheus integration)?
- Do we get automated patching?
- Is the cost comparable to the existing solution?

 More specifically, things we're interested in:
- xpack features: how does that help us define log access based on user attributes (eg. team membership)?
- ES version 7

There's also a comparison page [here](https://www.elastic.co/aws-elasticsearch-service).

**Comment by jasonBirchall** [comment]
https://docs.google.com/document/d/11xzV4w7Lef8UJXS_MptjQmdZX43VmXfUfjptt6dIlnU/
