### ISSUE TITLE
Give users permissions to list namespaces

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#95]
## Background

When we users get access to a namespace they have permissions to run commands in the namespace (like `kubectl get pods`) but not the command to list all namespaces on the cluster. This has come up a couple of times as being a useful bit of functionality, especially when you are starting out (and potentially when you have multiple clusters). 

## Proposed user journey

* User authenticates against cluster using kuberos link for that cluster
* User installs kubectil
* User runs `kubectl get namespaces` in their terminal
* User gets back a list of all namespaces on the cluster

## Approach

This has been already implemented by @kerin: https://github.com/ministryofjustice/cloud-platform-environments/commit/9ff781f4c51dc5eda077c02b6679d930c5a18133

However, we agree that there is better approach to it. Neither `ClusterRole` nor `ClusterRoleBinding` are namespaced; they're global resources so it would make sense to only create them once for all users. This requires a way to handle global resources and so the pipeline would have to be modified appropriately.

This has been manually setup for the `live-0` cluster [here](https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/cloud-platform-live-0.k8s.integration.dsd.io/user-roles.yaml). The proposal is to keep non-namespaced resources at the top level of a cluster directory in the environments repository. We want to modify the environment creation pipeline to handle these resources.

## Definition of done

- [x] The proposed user journey works for a brand new user on the cluster.
- [x] The environment creation pipeline can also handle global resources.
- [x] These resources are only defined once per cluster.

## Reference
N/A

**Comment by kalbir** [comment]
@alkar is going to add more to this issue to make sure we come up with a better implementation. This is initially implemented by https://github.com/ministryofjustice/cloud-platform-environments/pull/5

**Comment by alkar** [comment]
Added some more information to the ticket.

**Comment by alkar** [comment]
The second item in the AC was implemented as part of https://github.com/ministryofjustice/cloud-platform-environments/pull/32
