### ISSUE TITLE
Expose force_ssl option for the RDS module

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#950]
Apart from documenting the process for setting up the postgres client to use SSL
(https://github.com/ministryofjustice/cloud-platform-user-guide/issues/69), we would also like to export the
[`rds.force_ssl parameter`](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.SSL).

This option should be disable for now, while we decide how to roll it out.

**Comment by mattops** [comment]
Starter for 10...

https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/pull/32/files

**Comment by alkar** [comment]
Merged and released [4.4](https://github.com/ministryofjustice/cloud-platform-terraform-rds-instance/releases/tag/4.4). Thanks @mattops !
