### ISSUE TITLE
Employment Tribunals alerts 

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#953]
## Service name

Employment Tribunals

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [x ] Prod / Production
- [ ] Other

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

No service impact.

## Problem description

HMCTS are trying to understand how alerts for Employment Tribunals is set up. They don't know how it works and don't have access to the tools. Existing documentation is out of date and doesn't contain the relevant information.

To help the team I am wondering if we can access Pingdom and PagerDuty to see what is set up. We don't want to document this information as we don't support the service, but can we maybe provide some screen shots or something to show what has been set up.

Lack of information is slowing down their migration. Sharing this information will enable them to migrate quicker so that TD can be decommissioned.

## Contact person

@AntonyBishop

**Comment by AntonyBishop** [comment]
Discussed approach with the team. We know nothing about these services and don't provide any support. We are not adding any value by carrying out an investigation.

Best approach would be to provide HMCTS access to the tools so that they can carry out the investigation. They support this product and there is no reason for them not to have access to Pingdom or PagerDuty.

**Comment by AntonyBishop** [comment]
Opened an thread with the HMCTS Sustaining Team over in their channel.

**Comment by kcbotsh** [comment]
Provided info to HMCT to complete this task.
