### ISSUE TITLE
Create a receiver and slack webhook

### ISSUE THREAD

**Issue by pkpaulk** [ministryofjustice/cloud-platform#956]
## Service name

Monitoring data-capture-service and cica-web for UAT and Production

## Service environment

- [x] Dev / Development
- [ ] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

Alerts monitoring

## Problem description
[UAT]
namespace name: claim-criminal-injuries-compensation-uat
team name: cica-dev-team
application name: data-capture-service 
URL=https://data-capture-service.uat.claim-criminal-injuries-compensation.service.justice.gov.uk
application name: cica-web 
URL=https://uat.claim-criminal-injuries-compensation.service.justice.gov.uk
slack channel: inf_alerts

[PROD] 
namespace name: claim-criminal-injuries-compensation-prod
team name: cica-dev-team
application name: data-capture-service 
URL=https://data-capture-service.claim-criminal-injuries-compensation.service.justice.gov.uk
application name: cica-web
URL=https://claim-criminal-injuries-compensation.service.justice.gov.uk
Slack channel: inf_alerts

## Contact person
user: pk
chan: #infrastructure-team

**Comment by pwyborn** [comment]
paulwyborn [11:26 AM] 04/06/2019
Hi Paul - looking at your ticket
```https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/956```
. I cannot access your slack channels #inf_alerts or #infrastructure-team - you will need to allow access to #inf_alerts to allow the incoming webhook please

**Comment by pwyborn** [comment]
Awaiting user so I can create slack webhook and add it to terraform.tfvars config:

https://github.com/ministryofjustice/cloud-platform-infrastructure/tree/new-alert-route-in-alertmanager-data-capture-service

**Comment by pwyborn** [comment]
paulwyborn [1:28 PM] 04/06/2019
Paul - config - all ready - just awaiting access to your slack channel - so I can created a webhook (and update config with it).

**Comment by pwyborn** [comment]
paulwyborn [11:08 AM] - 05/06/2019
Hi Paul @pkpaulk - Should be there now.  The “custom severity level” is “cica-dev-team”  . Please follow the instructions here  
```https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#creating-a-slack-webhook-and-amend-alertmanager```
. Please note that as your uat and prod alerts go to the same channel - you will need to configure your alarms as required. Can you please test? (edited)

**Comment by pwyborn** [comment]
pk [11:16 AM] - 05/06/2019
Hi, thanks I will update the configs shortly.

pk [11:27 AM]  - 05/06/2019
Looks like the alerts are firing. Nice1

paulwyborn [11:27 AM]  - 05/06/2019
Great

**Comment by pwyborn** [comment]
To be closed now
