### ISSUE TITLE
Placeholder: Investigate CloudFront for DDoS protection

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#960]
Relates to formbuilder work

**Comment by sablumiah** [comment]
Do we get this from AWS?

**Comment by AntonyBishop** [comment]
Have raised some questions with the AWS TAM.

**Comment by AntonyBishop** [comment]
AWS Accounts already come with AWS Shield Standard by default. This provides sufficient prevention and alerting. No further action.
