### ISSUE TITLE
Make environments checker script destructive

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#962]
## Background

This issues connects to https://github.com/ministryofjustice/cloud-platform/issues/710. 

The environments checker script now outputs a verbose plan of resources that need to be destroyed from the `cloud-platform-environments` repository. 

The next step to achieving the desired goal is to actually perform the destroy as part of the script. 

## Proposed user journey

Add function in the environments checker that will destroy both Terraform resources not in git and Kubernetes namespaces. This involves potential disruption to service so please pair on this.

The checker can be found here: 

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by AntonyBishop** [comment]
Duplicate
