### ISSUE TITLE
Firebreak idea: Spike Load Testing Tool (part 2)

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#964]
## Background

We're going to need some load testing in the future. I suggest we spike a number of tools, one of them being KBoom which is a Kubernetes native tool used for load testing and/or soak purposes.

KBOOM:
https://github.com/mhausenblas/kboom?utm_sq=g2i6dp5awv

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pwyborn** [comment]
See here: https://docs.google.com/document/d/1231jhhwJpLIWz8tKlHvExfUJz6zzg-yJvnyBKTo_Ytk/edit#
General Conclusion:
Locust is ok for app testing - however not for our kubernetes cluster purposes. Think this should go back research for a later date - when maybe something better on the market.

Would like like to have crack at this again - pair with someone with a bit more knowledge of Kubernetes load testing

**Comment by AntonyBishop** [comment]
No current user need.
