### ISSUE TITLE
Create a helm chart and user guide walkthrough for creating dev. databases

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#966]
The approach for teams to spin up 'quick and dirty' development databases outlined in #874 creates security concerns that make it not worthwhile to pursue.

A different approach would be to enable teams to run postgres in containers in their namespaces (with lots of caveats about this not being a good idea if you want your data to stick around).

Normally, when you spin up a postgres container, you make up some database credentials and supply them via environment variables. If teams do this, they will connect their applications to their databases in quite a different way in development versus production. It would be good to have a way for them to use postgres containers in a way that is more similar to the way teams use databases in production.

### Approach

* Create a Helm chart which, when executed:
    1. Creates a kubernetes secret containing a set of random database credentials
    2. Creates a pod with a postgres container, storing data on a persistent volume, initialised using the database credentials

There is an example [here](https://github.com/ministryofjustice/parliamentary-questions/blob/move-deployments-into-one-file/k8s-deploy/localhost/deployment.yaml) which might be relevant.

**Comment by AntonyBishop** [comment]
No longer required
