### ISSUE TITLE
Create a messaging terraform module, wrapping SNS, SQS and subscriptions

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#968]
Related to: https://github.com/ministryofjustice/cloud-platform-terraform-sns-topic/issues/9

References: 

* [CP SQS module](https://github.com/ministryofjustice/cloud-platform-terraform-sqs/blob/master/main.tf)
* [CP SNS module](https://github.com/ministryofjustice/cloud-platform-terraform-sns-topic/blob/master/main.tf)

There are 2 problems (at least, for the CCCD team) with the way we enable teams to manage SQS queues and SNS topics, because every SQS queue and SNS topic they create has its own IAM user/role, with a unique set of credentials:

1. There is no way to create a subscription, linking a queue and a topic, because there is no set of IAM credential which has permissions on both a queue and a topic - each set of credentials has access to one queue or one topic, never to multiple resources

2. Having one IAM user per object leads to 'credential bloat', adding complexity to the application source code. e.g. where formerly, the code might have had lines like this:

    foo_message = QueueReader.new(queue: 'foo', key: ENV['QUEUE_USER_KEY'], secret: ENV['QUEUE_USER_SECRET']).read
    bar_message = QueueReader.new(queue: 'bar', key: ENV['QUEUE_USER_KEY'], secret: ENV['QUEUE_USER_SECRET']).read

In the current way of doing things in the cloud platform, this would become:

    foo_message = QueueReader.new(queue: 'foo', key: ENV['FOO_QUEUE_USER_KEY'], secret: ENV['FOO_QUEUE_USER_SECRET']).read
    bar_message = QueueReader.new(queue: 'bar', key: ENV['BAR_QUEUE_USER_KEY'], secret: ENV['BAR_QUEUE_USER_SECRET']).read

i.e. teams have to manage a set of credentials *per AWS resource*, instead of being able to create credentials that can be used throughout their app. to manage multiple AWS resources.

Although the approach of one set of credentials per resource does have the effect of limiting the 'blast radius' if any credentials are compromised, it does impose an additional burden of complexity on teams with respect to application configuration and deployment. In the case of CCCD, where their service works with 4 SQS queues and 2 SNS topics, they are going from managing 2 environment variables in their code to 12 (a key and a secret per AWS resource).

This issue suggests a fix for these problems, by enabling the team to create a full stack of messaging infrastructure in one go, along with a single set of IAM credentials required to use it.

### Definition of done

We have a single 'publish and subscribe' terraform module (name TBD), which creates:

* As many SQS queues as required
* As many SNS topics as required
* Subscriptions connecting the queues and topics (however the user specifies)
* One IAM user, and policy with permission to use the queues and topics

If you need clarification, please contact the CCCD developers (@colinbruce, @kmahern, @jsugarman).

**Comment by razvan-moj** [comment]
Fixed in release 3.0 of https://github.com/ministryofjustice/cloud-platform-terraform-sns-topic/releases and 3.1 of https://github.com/ministryofjustice/cloud-platform-terraform-sqs/releases
