### ISSUE TITLE
Add monitoring to AWS resources

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#970]
Start gathering metrics on the AWS resources teams create, and enable teams to view them. This could be a matter of exporting CloudWatch data to Prometheus, or we may want to enable teams to add prometheus exporters to the AWS resources they use.

Examples of the kinds of metrics teams might want include:

- [ ] How many messages are currently in a given queue?
- [ ] How many objects are in this S3 bucket?
- [ ] CPU utilisation and number of current connections to an RDS instance
- [ ] How many images are stored in this ECR?
- [ ] All Terraform module resources 

Also requires update to the user guide.

**Comment by sablumiah** [comment]
https://github.com/ministryofjustice/cloud-platform-user-guide/pull/159
https://github.com/ministryofjustice/cloud-platform-infrastructure/commit/16c1152d76cc0ae9054a532f070c0fed2efa7c23
