### ISSUE TITLE
Slow down & solidify

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#973]
Recently, we have been pushing hard to deliver new functionality and to improve on a wide range of aspects of our services. This, along with the ever present need to assist the tenants of our platform in building and supporting their services leads us to the belief that we should spend some time taking a step back and evaluating the landscape of our infrastructure.

There are a number of areas that we should revisit and potentially rework. Some of the goals are:

- to verify the validity of certain choices
- to increase the quality and robustness of our code
- to enhance our ability to deliver new features safely
- to improve on areas that frequently cause issues or are otherwise inconvenient
- to ensure that we do not have any "orphan" resources, not managed by code

**Comment by AntonyBishop** [comment]
This story has now changed into a number of other threads. Close.
