### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#977]
Although we've been taking care to update and expand our user guide as the platform involves, we recognise that holding training sessions with service teams could help in sharing knowledge and speeding up adoption of the Cloud Platform itself as well as best practices when it comes to running services on it.

Based on experience from sessions we will be holding with specific service teams as well as the feedback we get from them, we should look into designing a more generic session that would help with the onboarding of new users.

**Comment by digitalronin** [comment]
Just adding this here as a reminder, for when we start to work on this.

We had a meeting with a group of Oracle DBAs and devops people working for part of the LAA.

From that, I'd suggest that some of the topics worth covering in a generic introductory session would include:

* How we use pipelines and infrastructure as code to build and run the cloud platform
* What are the benefits of taking an "everything is code" approach
* Recommendations for follow-up research and learning (e.g. there are a ton of tutorials on the internet for docker, terraform, kubernetes etc. We should create a curated list of some good ones, and make that available to people) This should probably be a separate, user-guide ticket.

**Comment by alkar** [comment]
Do you think this would be a separate kind of session, touching more on methodology?

I wrote this ticket thinking more on the specifics of cloud platform, essentially a hands-on session on what the user guide already covers.

**Comment by digitalronin** [comment]
I think we're going to end up with a few different sessions and maybe types of session.

One is going to be very much as you describe - set the scene and then work through a practical exercise like what's in the user guide

Another, perhaps to audiences which are less familiar with modern devops, would cover some of the stuff I mentioned above.

**Comment by AntonyBishop** [comment]
Duplicate.
