### ISSUE TITLE
Migrate all application zones to the cloud-platform account

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#984]
# Background

When we started managing domains and certificates for applications, we decided to allow for existing zones to remain in the accounts where they had been created, in order to make migrations easier.

The solution was to configure `cert-manager` and `external-dns` with access to two accounts and it was meant as a temporary workaround.

However, since then, at least a couple of zones have been migrated in the cloud-platform account and our approach has been proven suitable.

Right now, the current setup introduces unnecessary complexity and we would like to remove the temporary workaround and host all zones in our main account.

Generally, the zones in dsd should be listed in the `dsd_zones` local in terraform.

For certificates, we can also check the actual provider name used:
```
kubectl get certificates --all-namespaces -ojson | jq -r '.items[] | select(.spec.acme.config | length > 0) | .metadata.namespace + " / " + ( .spec.acme.config[] | .dns01.provider )'
```

# Done when

- [x] make sure all zones are currently hosted in the correct account
- [x] make sure all `Certificates` are configured correctly
- [x] remove `external-dns-dsd` and `cert-manager-dsd`
- [x] the user guide has been updated to reflect this change

**Comment by alkar** [comment]
The current setup could potentially cause problem for applications moving from the `live-0` into `live-1` so it needs to be done before starting to move apps.

**Comment by vijay-veeranki-moj** [comment]
There are Three dsd zones
dsd_zones = [
    "find-legal-advice.justice.gov.uk.",
    "checklegalaid.service.gov.uk.",
    "helpwithchildarrangements.service.justice.gov.uk.",
  ]

Below two are in live-0 , need to Migrate them to cp account, when they move to live-1
    "find-legal-advice.justice.gov.uk.",
    "checklegalaid.service.gov.uk.",

**Comment by vijay-veeranki-moj** [comment]
moved "helpwithchildarrangements.service.justice.gov.uk." to cp account
Need to remove ```https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/terraform/cloud-platform-components/main.tf#L63```

and apply it in live-1

Giving 24hrs to get the delegation completed.

Also need to do terraform import so that zone is managed by terraform

**Comment by vijay-veeranki-moj** [comment]
Completed below tasks.

 make sure all zones are currently hosted in the correct account
 make sure all Certificates are configured correctly
 remove external-dns-dsd and cert-manager-dsd
 the user guide has been updated to reflect this change
