### ISSUE TITLE
Placeholder: Add a curated list of learning resources to the user guide

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#986]
There is an overwhelming amount of training material on the web. Some of it is
good. Much of it is not.

IMO, it would be really helpful for users if we had a list of videos, books &
articles which we have found that are actually worth spending time on.

This doesn't mean we have to go out and spend time viewing everything to find the
good stuff, but if we (or users) come across something good, we just add it to the
list. Over time, this should build up into a helpful resource for service teams.

**Comment by AntonyBishop** [comment]
Stale story. Revisit if need arises.
