### ISSUE TITLE
Triggering a deploy from a Github Release

### ISSUE THREAD

**Issue by TobyRet** [ministryofjustice/cloud-platform#99]
## Service name

Prison Visits Bookings

## Service environment

Staging

## Impact on the service

Provide real impact description on the service mentioned. It can include any potential blockers for the product team.

Ability to streamline deploy process. Making use of Github Releases will help us to better keep track of what is being deployed and when. Ideally, we would like the creation of a release to automatically start a Jenkins deployment job to production.

## Problem description

After some investigation investigation it appears that the Jenkins git plugin is designed only to build based on new commits, not tags.

_"The plugin needs a separate commit before it will generate a new build (other than in the cases I described). That could be an empty commit, but it needs a separate commit."_  [See issue discussion here](https://github.com/jenkinsci/git-plugin/pull/340)

I wanted to see if you know if any other way way we could trigger a deploy upon creation of a Github Release?

## Contact person

Toby Retallick / @TobyRetallick

**Comment by jasonBirchall** [comment]
Had a chat to Toby about the future plans of dropping Jenkins and picking up ConcourseCI.
