### ISSUE TITLE
Web interface for developers to revoke AWS credentials

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#992]
Sometimes credentials get leaked. e.g. https://mojdt.slack.com/archives/C57UPMZLY/p1559924339056900

We could create a web page, protected by Auth0 so only ministryofjustice developers could access it, where you could submit an AWS access key, and have it rendered inactive, immediately.

There is a risk that this could be abused - anyone in ministryofjustice organisation could deactivate any credentials (including those belonging to production systems), if they know the access key.
Before releasing a tool like this, we should assess this risk. A possible mitigation would be to keep an audit log of the github user who deactivated each access key.

**Comment by AntonyBishop** [comment]
Closing - Will be replaced with story to write some guidance.
