### ISSUE TITLE
TF `plan` displays fields when renaming

### ISSUE THREAD

**Issue by razvan-moj** [ministryofjustice/cloud-platform#998]
When renaming or moving fields, the `plan` step ignores the `sensitive` property

**Comment by digitalronin** [comment]
Was this specifically for kubernetes secrets?

It might be worth raising as a bug here: https://github.com/terraform-providers/terraform-provider-kubernetes/issues

I had a quick look at the issues on that page, and on terraform's main github page, and nobody
else has reported on this yet.

**Comment by vijay-veeranki-moj** [comment]
This is fixed as part of https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/1004
